--------------------------------------------------------
--  DDL for Function DB_QUERY_WAIT_STATS_AS_OF
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" 
(
  v_date IN VARCHAR2
)
RETURN qpi_RBL_MISDB_PROD.db_query_wait_stats_as_of_pkg.tt_db_query_wait_stats_as_o_type PIPELINED
AS
   v_temp SYS_REFCURSOR;
   v_temp_1 TT_DB_QUERY_WAIT_STATS_AS_O%ROWTYPE;

BEGIN
   OPEN v_temp FOR
      SELECT * 
        FROM tt_db_query_wait_stats_as_o;

   LOOP
      FETCH v_temp INTO v_temp_1;
      EXIT WHEN v_temp%NOTFOUND;
      PIPE ROW ( v_temp_1 );
   END LOOP;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "MAIN_PRO";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "MAIN_PRO";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "RBL_STGDB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "RBL_STGDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "RBL_TEMPDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."DB_QUERY_WAIT_STATS_AS_OF" TO "ADF_CDR_RBL_STGDB";
