--------------------------------------------------------
--  Constraints for Table IO_VIRTUAL_FILE_STATS_SNAPSHOT
--------------------------------------------------------

  ALTER TABLE "QPI_RBL_MISDB_PROD"."IO_VIRTUAL_FILE_STATS_SNAPSHOT" MODIFY ("DATABASE_ID" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."IO_VIRTUAL_FILE_STATS_SNAPSHOT" MODIFY ("FILE_NAME" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."IO_VIRTUAL_FILE_STATS_SNAPSHOT" MODIFY ("SIZE_GB" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."IO_VIRTUAL_FILE_STATS_SNAPSHOT" MODIFY ("FILE_ID" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."IO_VIRTUAL_FILE_STATS_SNAPSHOT" MODIFY ("IO_STALL_READ_MS" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."IO_VIRTUAL_FILE_STATS_SNAPSHOT" MODIFY ("IO_STALL_WRITE_MS" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."IO_VIRTUAL_FILE_STATS_SNAPSHOT" MODIFY ("IO_STALL_QUEUED_READ_MS" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."IO_VIRTUAL_FILE_STATS_SNAPSHOT" MODIFY ("IO_STALL_QUEUED_WRITE_MS" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."IO_VIRTUAL_FILE_STATS_SNAPSHOT" MODIFY ("IO_STALL" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."IO_VIRTUAL_FILE_STATS_SNAPSHOT" MODIFY ("NUM_OF_BYTES_READ" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."IO_VIRTUAL_FILE_STATS_SNAPSHOT" MODIFY ("NUM_OF_BYTES_WRITTEN" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."IO_VIRTUAL_FILE_STATS_SNAPSHOT" MODIFY ("NUM_OF_READS" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."IO_VIRTUAL_FILE_STATS_SNAPSHOT" MODIFY ("NUM_OF_WRITES" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."IO_VIRTUAL_FILE_STATS_SNAPSHOT" MODIFY ("START_TIME" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."IO_VIRTUAL_FILE_STATS_SNAPSHOT" MODIFY ("END_TIME" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."IO_VIRTUAL_FILE_STATS_SNAPSHOT" ADD CONSTRAINT "PK__IO_VIRTU__D5BA53FAB0CF49B7" PRIMARY KEY ("DATABASE_ID", "FILE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "QPI_RBL_MISDB_PROD"."IO_VIRTUAL_FILE_STATS_SNAPSHOT" ADD CONSTRAINT "CK__IO_VIRTUA__NUM_O__092B1A0C" CHECK (
   ( num_of_reads >= (0) )
) ENABLE;
  ALTER TABLE "QPI_RBL_MISDB_PROD"."IO_VIRTUAL_FILE_STATS_SNAPSHOT" ADD CONSTRAINT "CK__IO_VIRTUA__NUM_O__0A1F3E45" CHECK (
   ( num_of_writes >= (0) )
) ENABLE;
