--------------------------------------------------------
--  Constraints for Table IO_VIRTUAL_FILE_STATS_SNAPSHOT_HISTORY
--------------------------------------------------------

  ALTER TABLE "QPI_RBL_MISDB_PROD"."IO_VIRTUAL_FILE_STATS_SNAPSHOT_HISTORY" MODIFY ("DATABASE_ID" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."IO_VIRTUAL_FILE_STATS_SNAPSHOT_HISTORY" MODIFY ("FILE_NAME" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."IO_VIRTUAL_FILE_STATS_SNAPSHOT_HISTORY" MODIFY ("SIZE_GB" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."IO_VIRTUAL_FILE_STATS_SNAPSHOT_HISTORY" MODIFY ("FILE_ID" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."IO_VIRTUAL_FILE_STATS_SNAPSHOT_HISTORY" MODIFY ("IO_STALL_READ_MS" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."IO_VIRTUAL_FILE_STATS_SNAPSHOT_HISTORY" MODIFY ("IO_STALL_WRITE_MS" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."IO_VIRTUAL_FILE_STATS_SNAPSHOT_HISTORY" MODIFY ("IO_STALL_QUEUED_READ_MS" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."IO_VIRTUAL_FILE_STATS_SNAPSHOT_HISTORY" MODIFY ("IO_STALL_QUEUED_WRITE_MS" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."IO_VIRTUAL_FILE_STATS_SNAPSHOT_HISTORY" MODIFY ("IO_STALL" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."IO_VIRTUAL_FILE_STATS_SNAPSHOT_HISTORY" MODIFY ("NUM_OF_BYTES_READ" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."IO_VIRTUAL_FILE_STATS_SNAPSHOT_HISTORY" MODIFY ("NUM_OF_BYTES_WRITTEN" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."IO_VIRTUAL_FILE_STATS_SNAPSHOT_HISTORY" MODIFY ("NUM_OF_READS" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."IO_VIRTUAL_FILE_STATS_SNAPSHOT_HISTORY" MODIFY ("NUM_OF_WRITES" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."IO_VIRTUAL_FILE_STATS_SNAPSHOT_HISTORY" MODIFY ("START_TIME" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."IO_VIRTUAL_FILE_STATS_SNAPSHOT_HISTORY" MODIFY ("END_TIME" NOT NULL ENABLE);
