--------------------------------------------------------
--  DDL for Index IX_IO_VIRTUAL_FILE_STATS_SNAPSHOT_HISTORY
--------------------------------------------------------

  CREATE INDEX "QPI_RBL_MISDB_PROD"."IX_IO_VIRTUAL_FILE_STATS_SNAPSHOT_HISTORY" ON "QPI_RBL_MISDB_PROD"."IO_VIRTUAL_FILE_STATS_SNAPSHOT_HISTORY" ("START_TIME", "END_TIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
