--------------------------------------------------------
--  Constraints for Table OS_PERFORMANCE_COUNTERS_SNAPSHOT
--------------------------------------------------------

  ALTER TABLE "QPI_RBL_MISDB_PROD"."OS_PERFORMANCE_COUNTERS_SNAPSHOT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."OS_PERFORMANCE_COUNTERS_SNAPSHOT" MODIFY ("VALUE" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."OS_PERFORMANCE_COUNTERS_SNAPSHOT" MODIFY ("OBJECT" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."OS_PERFORMANCE_COUNTERS_SNAPSHOT" MODIFY ("INSTANCE_NAME" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."OS_PERFORMANCE_COUNTERS_SNAPSHOT" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."OS_PERFORMANCE_COUNTERS_SNAPSHOT" MODIFY ("START_TIME" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."OS_PERFORMANCE_COUNTERS_SNAPSHOT" MODIFY ("END_TIME" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."OS_PERFORMANCE_COUNTERS_SNAPSHOT" ADD CONSTRAINT "PK__OS_PERFO__DFE47B6FE496E1BC" PRIMARY KEY ("NAME", "OBJECT", "INSTANCE_NAME", "TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
