--------------------------------------------------------
--  Constraints for Table OS_PERFORMANCE_COUNTERS_SNAPSHOT_HISTORY
--------------------------------------------------------

  ALTER TABLE "QPI_RBL_MISDB_PROD"."OS_PERFORMANCE_COUNTERS_SNAPSHOT_HISTORY" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."OS_PERFORMANCE_COUNTERS_SNAPSHOT_HISTORY" MODIFY ("VALUE" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."OS_PERFORMANCE_COUNTERS_SNAPSHOT_HISTORY" MODIFY ("OBJECT" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."OS_PERFORMANCE_COUNTERS_SNAPSHOT_HISTORY" MODIFY ("INSTANCE_NAME" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."OS_PERFORMANCE_COUNTERS_SNAPSHOT_HISTORY" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."OS_PERFORMANCE_COUNTERS_SNAPSHOT_HISTORY" MODIFY ("START_TIME" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."OS_PERFORMANCE_COUNTERS_SNAPSHOT_HISTORY" MODIFY ("END_TIME" NOT NULL ENABLE);
