--------------------------------------------------------
--  Constraints for Table OS_WAIT_STATS_SNAPSHOT
--------------------------------------------------------

  ALTER TABLE "QPI_RBL_MISDB_PROD"."OS_WAIT_STATS_SNAPSHOT" MODIFY ("WAIT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."OS_WAIT_STATS_SNAPSHOT" MODIFY ("WAITING_TASKS_COUNT" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."OS_WAIT_STATS_SNAPSHOT" MODIFY ("WAIT_TIME_S" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."OS_WAIT_STATS_SNAPSHOT" MODIFY ("MAX_WAIT_TIME_MS" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."OS_WAIT_STATS_SNAPSHOT" MODIFY ("SIGNAL_WAIT_TIME_S" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."OS_WAIT_STATS_SNAPSHOT" MODIFY ("START_TIME" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."OS_WAIT_STATS_SNAPSHOT" MODIFY ("END_TIME" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."OS_WAIT_STATS_SNAPSHOT" ADD CONSTRAINT "PK__OS_WAIT___B54472846C302EE8" PRIMARY KEY ("WAIT_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
