--------------------------------------------------------
--  Constraints for Table OS_WAIT_STATS_SNAPSHOT_HISTORY
--------------------------------------------------------

  ALTER TABLE "QPI_RBL_MISDB_PROD"."OS_WAIT_STATS_SNAPSHOT_HISTORY" MODIFY ("WAIT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."OS_WAIT_STATS_SNAPSHOT_HISTORY" MODIFY ("WAITING_TASKS_COUNT" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."OS_WAIT_STATS_SNAPSHOT_HISTORY" MODIFY ("WAIT_TIME_S" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."OS_WAIT_STATS_SNAPSHOT_HISTORY" MODIFY ("MAX_WAIT_TIME_MS" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."OS_WAIT_STATS_SNAPSHOT_HISTORY" MODIFY ("SIGNAL_WAIT_TIME_S" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."OS_WAIT_STATS_SNAPSHOT_HISTORY" MODIFY ("START_TIME" NOT NULL ENABLE);
  ALTER TABLE "QPI_RBL_MISDB_PROD"."OS_WAIT_STATS_SNAPSHOT_HISTORY" MODIFY ("END_TIME" NOT NULL ENABLE);
