--------------------------------------------------------
--  DDL for Procedure SNAPSHOT_WAIT_STATS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" 
(
  v_title IN NVARCHAR2 DEFAULT NULL 
)
AS

BEGIN

   MERGE  INTO qpi_RBL_MISDB_PROD.os_wait_stats_snapshot TARGET
   USING ( SELECT * 
           FROM qpi_RBL_MISDB_PROD.wait_stats_ex  ) SOURCE     ON ( TARGET.wait_type = SOURCE.wait_type
   -- docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-query-store-wait-stats-transact-sql?view=sql-server-2017#wait-categories-mapping-table
    )
   WHEN MATCHED THEN   UPDATE SET  TARGET.category_id = SOURCE.category_id,
                                   TARGET.wait_type = SOURCE.wait_type,
                                   TARGET.waiting_tasks_count = SOURCE.waiting_tasks_count,
                                   TARGET.wait_time_s = SOURCE.wait_time_s,
                                   TARGET.max_wait_time_ms = SOURCE.max_wait_time_ms,
                                   TARGET.signal_wait_time_s = SOURCE.signal_wait_time_s,
                                   TARGET.title = NVL(v_title, UTILS.CONVERT_TO_VARCHAR2(SYSDATE,30,p_style=>20
                                                      -- IMPORTANT: DO NOT subtract Source-Target because the source always has a diff.
                                                       -- On each snapshot wait starts are reset to 0 - see DBCC SQLPERF('sys.dm_os_wait_stats', CLEAR);
                                                       -- Therefore, current snapshot is diff.
                                                       -- #alzheimer
                                                      ))   
   WHEN NOT MATCHED THEN INSERT ( category_id,wait_type,waiting_tasks_count,wait_time_s,max_wait_time_ms,signal_wait_time_s,title )
   VALUES ( SOURCE.category_id,SOURCE.wait_type,SOURCE.waiting_tasks_count,SOURCE.wait_time_s,SOURCE.max_wait_time_ms,SOURCE.signal_wait_time_s,NVL(v_title, UTILS.CONVERT_TO_VARCHAR2(SYSDATE,30,p_style=>20)))  
   ;DBCC SQLPERF ( 'sys.dm_os_wait_stats' ,  --SQLDEV: NOT RECOGNIZED
   CLEAR() ;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "MAIN_PRO";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "MAIN_PRO";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "RBL_STGDB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "RBL_STGDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "RBL_TEMPDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."SNAPSHOT_WAIT_STATS" TO "ADF_CDR_RBL_STGDB";
