--------------------------------------------------------
--  DDL for Function WAIT_STATS_CATEGORY
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" 
(
  v_category_id IN NUMBER
)
RETURN qpi_RBL_MISDB_PROD.wait_stats_category_pkg.tt_wait_stats_category_type PIPELINED
AS
   v_temp SYS_REFCURSOR;
   v_temp_1 TT_WAIT_STATS_CATEGORY%ROWTYPE;

BEGIN
   DELETE tt_wait_stats_category;

   INSERT INTO tt_wait_stats_category
      SELECT CASE v_category_id
                               WHEN 0 THEN 'Unknown'
                               WHEN 1 THEN 'CPU'
                               WHEN 2 THEN 'Worker Thread'
                               WHEN 3 THEN 'Lock'
                               WHEN 4 THEN 'Latch'
                               WHEN 5 THEN 'Buffer Latch'
                               WHEN 6 THEN 'Buffer IO'
                               WHEN 7 THEN 'Compilation'
                               WHEN 8 THEN 'SQL CLR'
                               WHEN 9 THEN 'Mirroring'
                               WHEN 10 THEN 'Transaction'
                               WHEN 11 THEN 'Idle'
                               WHEN 12 THEN 'Preemptive'
                               WHEN 13 THEN 'Service Broker'
                               WHEN 14 THEN 'Tran Log IO'
                               WHEN 15 THEN 'Network IO'
                               WHEN 16 THEN 'Parallelism'
                               WHEN 17 THEN 'Memory'
                               WHEN 18 THEN 'User Wait'
                               WHEN 19 THEN 'Tracing'
                               WHEN 20 THEN 'Full Text Search'
                               WHEN 21 THEN 'Other Disk IO'
                               WHEN 22 THEN 'Replication'
                               WHEN 23 THEN 'Log Rate Governor'   END category  
        FROM DUAL ;

      OPEN v_temp FOR
      SELECT * 
        FROM tt_wait_stats_category;

   LOOP
      FETCH v_temp INTO v_temp_1;
      EXIT WHEN v_temp%NOTFOUND;
      PIPE ROW ( v_temp_1 );
   END LOOP;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "MAIN_PRO";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "MAIN_PRO";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "RBL_STGDB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "RBL_STGDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "RBL_TEMPDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY" TO "ADF_CDR_RBL_STGDB";
