--------------------------------------------------------
--  DDL for Function WAIT_STATS_CATEGORY_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" 
(
  v_wait_type IN VARCHAR2
)
RETURN qpi_RBL_MISDB_PROD.wait_stats_category_id_pkg.tt_wait_stats_category_id_type PIPELINED
AS
   v_temp SYS_REFCURSOR;
   v_temp_1 TT_WAIT_STATS_CATEGORY_ID%ROWTYPE;

BEGIN
   DELETE tt_wait_stats_category_id;

   INSERT INTO tt_wait_stats_category_id
      SELECT CASE 
                  WHEN v_wait_type = 'Unknown' THEN 0
                  WHEN v_wait_type = 'SOS_SCHEDULER_YIELD' THEN 1

                  --WHEN @wait_type = 'SOS_WORK_DISPATCHER'	THEN 1
                  WHEN v_wait_type = 'THREADPOOL' THEN 2
                  WHEN v_wait_type LIKE 'LCK_M_%' THEN 3
                  WHEN v_wait_type LIKE 'LATCH_%' THEN 4
                  WHEN v_wait_type LIKE 'PAGELATCH_%' THEN 5
                  WHEN v_wait_type LIKE 'PAGEIOLATCH_%' THEN 6
                  WHEN v_wait_type = 'RESOURCE_SEMAPHORE_QUERY_COMPILE' THEN 7
                  WHEN v_wait_type LIKE 'CLR%' THEN 8
                  WHEN v_wait_type LIKE 'SQLCLR%' THEN 8
                  WHEN v_wait_type LIKE 'DBMIRROR%' THEN 9
                  WHEN v_wait_type LIKE 'XACT%' THEN 10
                  WHEN v_wait_type LIKE 'DTC%' THEN 10
                  WHEN v_wait_type LIKE 'TRAN_MARKLATCH_%' THEN 10
                  WHEN v_wait_type = 'TRANSACTION_MUTEX' THEN 10
                  WHEN v_wait_type LIKE 'MSQL_XACT_%' THEN 10
                  WHEN v_wait_type LIKE 'SLEEP_%' THEN 11
                  WHEN v_wait_type IN ( 'LAZYWRITER_SLEEP','SQLTRACE_BUFFER_FLUSH','SQLTRACE_INCREMENTAL_FLUSH_SLEEP','SQLTRACE_WAIT_ENTRIES','FT_IFTS_SCHEDULER_IDLE_WAIT','XE_DISPATCHER_WAIT','REQUEST_FOR_DEADLOCK_SEARCH','LOGMGR_QUEUE','ONDEMAND_TASK_QUEUE','CHECKPOINT_QUEUE','XE_TIMER_EVENT' )
                   THEN 11
                  WHEN v_wait_type LIKE 'PREEMPTIVE_%' THEN 12
                  WHEN v_wait_type LIKE 'BROKER_%'
                    AND v_wait_type <> 'BROKER_RECEIVE_WAITFOR' THEN 13
                  WHEN v_wait_type IN ( 'LOGMGR','LOGBUFFER','LOGMGR_RESERVE_APPEND','LOGMGR_FLUSH','LOGMGR_PMM_LOG','CHKPT','WRITELOG' )
                   THEN 14
                  WHEN v_wait_type IN ( 'ASYNC_NETWORK_IO','NET_WAITFOR_PACKET','PROXY_NETWORK_IO','EXTERNAL_SCRIPT_NETWORK_IO' )
                   THEN 15
                  WHEN v_wait_type IN ( 'CXPACKET','EXCHANGE' )
                   THEN 16
                  WHEN v_wait_type IN ( 'RESOURCE_SEMAPHORE','CMEMTHREAD','CMEMPARTITIONED','EE_PMOLOCK','MEMORY_ALLOCATION_EXT','RESERVED_MEMORY_ALLOCATION_EXT','MEMORY_GRANT_UPDATE' )
                   THEN 17
                  WHEN v_wait_type IN ( 'WAITFOR','WAIT_FOR_RESULTS','BROKER_RECEIVE_WAITFOR' )
                   THEN 18
                  WHEN v_wait_type IN ( 'TRACEWRITE','SQLTRACE_LOCK','SQLTRACE_FILE_BUFFER','SQLTRACE_FILE_WRITE_IO_COMPLETION','SQLTRACE_FILE_READ_IO_COMPLETION','SQLTRACE_PENDING_BUFFER_WRITERS','SQLTRACE_SHUTDOWN','QUERY_TRACEOUT','TRACE_EVTNOTIFF' )
                   THEN 19
                  WHEN v_wait_type IN ( 'FT_RESTART_CRAWL','FULLTEXT GATHERER','MSSEARCH','FT_METADATA_MUTEX','FT_IFTSHC_MUTEX','FT_IFTSISM_MUTEX','FT_IFTS_RWLOCK','FT_COMPROWSET_RWLOCK','FT_MASTER_MERGE','FT_PROPERTYLIST_CACHE','FT_MASTER_MERGE_COORDINATOR','PWAIT_RESOURCE_SEMAPHORE_FT_PARALLEL_QUERY_SYNC' )
                   THEN 20
                  WHEN v_wait_type IN ( 'ASYNC_IO_COMPLETION','IO_COMPLETION','BACKUPIO','WRITE_COMPLETION','IO_QUEUE_LIMIT','IO_RETRY' )
                   THEN 21
                  WHEN v_wait_type IN ( 'REPLICA_WRITES','FCB_REPLICA_WRITE','FCB_REPLICA_READ','PWAIT_HADRSIM' )
                   THEN 22
                  WHEN v_wait_type LIKE 'SE_REPL_%' THEN 22
                  WHEN v_wait_type LIKE 'REPL_%' THEN 22
                  WHEN v_wait_type LIKE 'HADR_%'
                    AND v_wait_type <> 'HADR_THROTTLE_LOG_RATE_GOVERNOR' THEN 22
                  WHEN v_wait_type LIKE 'PWAIT_HADR_%' THEN 22
                  WHEN v_wait_type IN ( 'LOG_RATE_GOVERNOR','POOL_LOG_RATE_GOVERNOR','HADR_THROTTLE_LOG_RATE_GOVERNOR','INSTANCE_LOG_RATE_GOVERNOR' )
                   THEN 23
             ELSE NULL
                END category_id  
        FROM DUAL ;

      OPEN v_temp FOR
      SELECT * 
        FROM tt_wait_stats_category_id;

   LOOP
      FETCH v_temp INTO v_temp_1;
      EXIT WHEN v_temp%NOTFOUND;
      PIPE ROW ( v_temp_1 );
   END LOOP;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "MAIN_PRO";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "MAIN_PRO";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "RBL_STGDB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "RBL_STGDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "RBL_TEMPDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "QPI_RBL_MISDB_PROD"."WAIT_STATS_CATEGORY_ID" TO "ADF_CDR_RBL_STGDB";
