--------------------------------------------------------
--  File created - Wednesday-March-19-2025   
--------------------------------------------------------
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DATAUPLOAD_SCRIPTS\MOCACCOUNTDATAUPLOAD.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DATAUPLOAD_SCRIPTS\MOCACCOUNTDATAUPLOAD_MOD.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DATAUPLOAD_SCRIPTS\MOCCUSTOMERDATAUPLOAD.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DATAUPLOAD_SCRIPTS\MOCCUSTOMERDATAUPLOAD_MOD.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DATAUPLOAD_SCRIPTS\MOCACCOUNTDATAUPLOAD_DATA_TABLE.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DATAUPLOAD_SCRIPTS\MOCACCOUNTDATAUPLOAD_MOD_DATA_TABLE.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DATAUPLOAD_SCRIPTS\MOCCUSTOMERDATAUPLOAD_DATA_TABLE.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DATAUPLOAD_SCRIPTS\MOCCUSTOMERDATAUPLOAD_MOD_DATA_TABLE.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DATAUPLOAD_SCRIPTS\UTILS.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DATAUPLOAD_SCRIPTS\MOCACCOUNTDATAUPLOAD_CONSTRAINT.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DATAUPLOAD_SCRIPTS\MOCACCOUNTDATAUPLOAD_MOD_CONSTRAINT.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DATAUPLOAD_SCRIPTS\MOCCUSTOMERDATAUPLOAD_CONSTRAINT.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DATAUPLOAD_SCRIPTS\MOCCUSTOMERDATAUPLOAD_MOD_CONSTRAINT.sql
