--------------------------------------------------------
--  DDL for Procedure PRODUCTADDITION_15092023
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "RBL_STGDB"."PRODUCTADDITION_15092023" 
AS
   v_Counter NUMBER(10,0);
   v_FinalCounter NUMBER(10,0) := ( SELECT COUNT(*)  
     FROM ( SELECT DISTINCT Scheme_ProductCode 
            FROM ACCOUNT_ALL_SOURCE_SYSTEM 
            MINUS 
            SELECT DISTINCT productcode 
            FROM RBL_MISDB.DimProduct  ) A );

BEGIN

   v_Counter := 1 ;
   WHILE ( v_Counter <= v_FinalCounter ) 
   LOOP 
      DECLARE
         v_Productcode VARCHAR2(20) := ( SELECT * 
           FROM ( SELECT DISTINCT Scheme_ProductCode 
                  FROM ACCOUNT_ALL_SOURCE_SYSTEM 
                  MINUS 
                  SELECT DISTINCT productcode 
                  FROM RBL_MISDB.DimProduct  ) A 
           FETCH FIRST 1 ROWS ONLY );
         v_SecuredStatus VARCHAR2(30) := ( SELECT DISTINCT (CASE 
                                 WHEN SecuredStatus = 'U' THEN 'UNSECURED'
                           ELSE 'SECURED'
                              END) 
           FROM ACCOUNT_ALL_SOURCE_SYSTEM 
          WHERE  Scheme_ProductCode = v_Productcode );
         v_SchemeType VARCHAR2(30) := ( SELECT DISTINCT SchemeType 
           FROM ACCOUNT_ALL_SOURCE_SYSTEM 
          WHERE  Scheme_ProductCode = v_Productcode );

      BEGIN
         INSERT INTO RBL_MISDB.DimProduct
           ( ProductAlt_Key, ProductCode, ProductName, ProductGroup, ProductSubGroup, EffectiveFromTimeKey, EffectiveToTimeKey, CreatedBy, DateCreated )
           ( SELECT MAX(ProductAlt_key)  + 1 ,
                    v_Productcode ,
                    v_Productcode ,
                    v_SchemeType ,
                    v_SecuredStatus ,
                    1 ,
                    49999 ,
                    'D2K' ,
                    SYSDATE 
             FROM RBL_MISDB.DimProduct  );
         v_Counter := v_Counter + 1 ;

      END;
   END LOOP;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."PRODUCTADDITION_15092023" TO "ADF_CDR_RBL_STGDB";
