--------------------------------------------------------
--  DDL for Procedure TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" 
AS

BEGIN

   EXECUTE IMMEDIATE ' TRUNCATE TABLE RBL_STGDB.ExceptionFinalStatusType_AllData ';
   INSERT INTO RBL_STGDB.ExceptionFinalStatusType_AllData
     ( DateOfData, HostSystem, CustomerACID, CustomerID, UCIC, Flag, Amount, StatusDate, StatusType )
     ( SELECT * 
       FROM ( SELECT UTILS.CONVERT_TO_VARCHAR2(ReportData,200) date_  ,
                     'Finacle' HostSystem  ,
                     CustomerACID ,
                     CustomerID ,
                     NULL UCIC  ,
                     NULL Flag  ,
                     SUM(WRITEOFFAMOUNT)  AMOUNT  ,
                     MIN(UTILS.CONVERT_TO_VARCHAR2(WRITEOFFDATE,200))  StatusDate  ,
                     'TWO' StatusType  
              FROM DWH_DWH_STG.WriteOffData_SCF 
                GROUP BY CustomerACID,UTILS.CONVERT_TO_VARCHAR2(ReportData,200),HostSystem,CustomerID
              UNION ALL 
              SELECT UTILS.CONVERT_TO_VARCHAR2(ReportData,200) Date_  ,
                     HostSystem ,
                     CustomerACID ,
                     CustomerID ,
                     UCIC ,
                     WriteOffFlag ,
                     WriteOffAmount AMOUNT  ,
                     UTILS.CONVERT_TO_VARCHAR2(WRITEOFFDATE,200) StatusDate  ,
                     'TWO' StatusType  
              FROM dwh_DWH_STG.WriteOffData 
              UNION ALL 
              SELECT UTILS.CONVERT_TO_VARCHAR2(dateofdata,200) DATE_  ,
                     Sourcesystem ,
                     CustomerAcID ,
                     CustomerID ,
                     UCIC_ID ,
                     Settlement_Flag ,
                     NULL Amount  ,
                     UTILS.CONVERT_TO_VARCHAR2(Settlement_Date,200) StatusDate  ,
                     'Settlement' StatusType  
              FROM RBL_STGDB.ACCOUNT_ALL_SOURCE_SYSTEM 
               WHERE  ( Settlement_Date IS NOT NULL
                        OR Settlement_Flag = 'Y' )
              UNION ALL 
              SELECT Date_of_Data ,
                     'SCF' HostSystem  ,
                     RefSystemAcid ,
                     NULL RefSystemAcid_CIF_ID  ,
                     NULL RefSystemAcid_UCIC  ,
                     Settlement_Flag ,
                     NULL Amount  ,
                     MIN(UTILS.CONVERT_TO_VARCHAR2(Settlement_Date,200))  StatusDate  ,
                     'Settlement' StatusType  
              FROM dwh_DWH_STG.BILLS_DATA_STG_SCF 
               WHERE  ( Settlement_Date IS NOT NULL
                        OR Settlement_Flag = 'Y' )
                GROUP BY RefSystemAcid,Date_of_Data,Settlement_Flag
              UNION ALL 
              SELECT Date_of_data ,
                     'VisionPlus' HostSystem  ,
                     Customer_Ac_Id RefSystemAcid  ,
                     Customer_Id CustomerID  ,
                     ucic ,
                     Charge_Off_flag ,
                     NULL Amount  ,
                     UTILS.CONVERT_TO_VARCHAR2(Charge_Off_date,200) StatusDate  ,
                     'Charge Off' StatusType  
              FROM dwh_DWH_STG.account_data_visionplus 
               WHERE  ( Charge_Off_date IS NOT NULL
                        OR Charge_off_flag = 'Y' --AND Balance_Outstanding_INR>0
                       )
              UNION ALL 
              SELECT Date_of_data ,
                     'Finacle' HostSystem  ,
                     Customer_Ac_Id RefSystemAcid  ,
                     Customer_Id CustomerID  ,
                     ucic ,
                     Charge_Off_flag ,
                     NULL Amount  ,
                     Charge_Off_date StatusDate  ,
                     'Charge Off' StatusType  
              FROM dwh_DWH_STG.account_data_finacle 
               WHERE  ( Charge_Off_date IS NOT NULL
                        OR Charge_off_flag = 'Y' )
                        AND Balance_Outstanding_INR > 0
              UNION ALL 
              SELECT Date_of_data ,
                     source_system_name ,
                     issuerId RefSystemAcid  ,
                     NULL CustomerID  ,
                     ucic_id ,
                     Settlement_Flag ,
                     NULL Amount  ,
                     UTILS.CONVERT_TO_VARCHAR2(Settlement_Date,200) StatusDate  ,
                     'Settlement' StatusType  
              FROM DWH_DWH_STG.InvestmentIssuerDetail 
               WHERE  ( Settlement_Date IS NOT NULL
                        OR Settlement_Flag = 'Y' ) ) A );
   ETL_TEMP_RBL_TEMPDB.ExceptionFinalStatusType_Temp() ;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "MAIN_PRO";
  GRANT EXECUTE ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "MAIN_PRO";
  GRANT DEBUG ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "RBL_TEMPDB";
  GRANT DEBUG ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "RBL_STGDB"."TRANSFER_EXCEPTIONFINALSTATUSTYPEDATA_ALL_SOURCE_SYSTEM_22112023" TO "ADF_CDR_RBL_STGDB";
