--------------------------------------------------------
--  DDL for Procedure GOVTGUARAPPROPRIATION_TEST
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" /*=====================================
AUTHER : TRILOKI KHANNA
CREATE DATE : 27-11-2019
MODIFY DATE : 27-11-2019
DESCRIPTION :Govt Guar Appropriation
EXEC pro.GovtGuarAppropriation   @TIMEKEY=25140
====================================*/
(
  v_TimeKey IN NUMBER
)
AS

BEGIN

   BEGIN

      BEGIN
         /*-----UPDATE AppGovGur =0 --------------------------*/
         MERGE INTO A 
         USING (SELECT A.ROWID row_id, 0
         FROM A ,PRO_RBL_MISDB_PROD.ACCOUNTCAL_TEST A
                JOIN PRO_RBL_MISDB_PROD.CUSTOMERCAL B   ON A.CustomerEntityID = B.CustomerEntityID 
          WHERE B.FlgProcessing = 'N') src
         ON ( A.ROWID = src.row_id )
         WHEN MATCHED THEN UPDATE SET A.AppGovGur = 0;
         IF utils.object_id('TEMPDB..tt_TEMPTABLEAppGovGur_5') IS NOT NULL THEN
          EXECUTE IMMEDIATE ' TRUNCATE TABLE tt_TEMPTABLEAppGovGur_5 ';
         END IF;
         DELETE FROM tt_TEMPTABLEAppGovGur_5;
         UTILS.IDENTITY_RESET('tt_TEMPTABLEAppGovGur_5');

         INSERT INTO tt_TEMPTABLEAppGovGur_5 ( 
         	SELECT A.AccountEntityID ,
                 (CASE 
                       WHEN SUM(A.NetBalance) OVER ( PARTITION BY A.CustomerEntityID ) > 0 THEN (A.GovtGtyAmt * (A.NetBalance / SUM(A.NetBalance) OVER ( PARTITION BY A.CustomerEntityID )))   END) GovGur  
         	  FROM PRO_RBL_MISDB_PROD.ACCOUNTCAL_TEST A
         	 WHERE  A.FacilityType IN ( 'BP','BD' )

                    AND NVL(A.GovtGtyAmt, 0) > 0 );
         MERGE INTO A 
         USING (SELECT A.ROWID row_id, B.GovGur
         FROM A ,PRO_RBL_MISDB_PROD.ACCOUNTCAL_TEST A
                JOIN tt_TEMPTABLEAppGovGur_5 B   ON A.AccountEntityID = B.AccountEntityID 
          WHERE A.FacilityType IN ( 'BP','BD' )
         ) src
         ON ( A.ROWID = src.row_id )
         WHEN MATCHED THEN UPDATE SET A.AppGovGur = src.GovGur;
         MERGE INTO A 
         USING (SELECT A.ROWID row_id, GovtGtyAmt
         FROM A ,PRO_RBL_MISDB_PROD.ACCOUNTCAL_TEST A 
          WHERE NOT ( A.FacilityType IN ( 'BP','BD' )
          )) src
         ON ( A.ROWID = src.row_id )
         WHEN MATCHED THEN UPDATE SET A.AppGovGur = GovtGtyAmt;
         UPDATE PRO_RBL_MISDB_PROD.AclRunningProcessStatus_TEST
            SET COMPLETED = 'Y',
                ERRORDATE = NULL,
                ERRORDESCRIPTION = NULL,
                COUNT = NVL(COUNT, 0) + 1
          WHERE  RUNNINGPROCESSNAME = 'GovtGuarAppropriation';
         EXECUTE IMMEDIATE ' TRUNCATE TABLE tt_TEMPTABLEAppGovGur_5 ';

      END;
   EXCEPTION
      WHEN OTHERS THEN

   BEGIN
      -----------------Added for DashBoard 04-03-2021
      --Update BANDAUDITSTATUS set CompletedCount=CompletedCount+1 where BandName='ASSET CLASSIFICATION'
      UPDATE PRO_RBL_MISDB_PROD.AclRunningProcessStatus_TEST
         SET COMPLETED = 'N',
             ERRORDATE = SYSDATE,
             ERRORDESCRIPTION = SQLERRM,
             COUNT = NVL(COUNT, 0) + 1
       WHERE  RUNNINGPROCESSNAME = 'GovtGuarAppropriation';

   END;END;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "RBL_TEMPDB";
  GRANT DEBUG ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."GOVTGUARAPPROPRIATION_TEST" TO "ADF_CDR_RBL_STGDB";
