--------------------------------------------------------
--  DDL for Procedure INVESTMENTDERIVATIVEPROVISIONCAL_27042023
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" 
----/*=========================================
 ---- AUTHER : TRILOKI KHANNA
 ---- CREATE DATE : 27-11-2019
 ---- MODIFY DATE : 27-11-2019
 ---- DESCRIPTION : UPDATE InvestmentDataProcessing
 ---- --EXEC [PRO].[InvestmentDataProcessing] @TIMEKEY=26053
 ----=============================================*/

(
  v_TIMEKEY IN NUMBER
)
AS
/*=========================================
-- AUTHOR : TRILOKI KHANNA
-- CREATE DATE : 09-04-2021
-- MODIFY DATE : 09-04-2021
-- DESCRIPTION : Test Case Cover in This SP

--=============================================*/

BEGIN

   BEGIN

      BEGIN
         --DECLARE @TIMEKEY INT=@TimeKey
         ----/*----------------PROVISION ALT KEY ALL  ACCOUNTS--------------------------------*/
         /*  INVESTMENT  */
         MERGE INTO A 
         USING (SELECT A.ROWID row_id, 0
         FROM A ,InvestmentFinancialDetail A 
          WHERE ( A.EffectiveFromTimeKey <= v_TimeKey
           AND A.EffectiveToTimeKey >= v_TimeKey )) src
         ON ( A.ROWID = src.row_id )
         WHEN MATCHED THEN UPDATE SET PROVISIONALT_KEY = 0;
         MERGE INTO A 
         USING (SELECT A.ROWID row_id, D.ProvisionAlt_Key
         FROM A ,InvestmentFinancialDetail A
                JOIN DimAssetClass C   ON C.AssetClassAlt_Key = NVL(A.FinalAssetClassAlt_Key, 1)
                AND ( C.EffectiveFromTimeKey <= v_TIMEKEY
                AND C.EffectiveToTimeKey >= v_TIMEKEY )
                JOIN DimProvision_Seg D   ON D.EffectiveFromTimeKey <= v_TIMEKEY
                AND D.EffectiveToTimeKey >= v_TIMEKEY

                --AND A.DPD BETWEEN d.LowerDPD AND d.UpperDPD
                AND c.AssetClassShortName = D.PROVISIONSHORTNAMEENUM 
          WHERE C.ASSETCLASSGROUP = 'NPA'
           AND ( A.EffectiveFromTimeKey <= v_TIMEKEY
           AND A.EffectiveToTimeKey >= v_TIMEKEY )
           AND D.SEGMENT = 'IRAC') src
         ON ( A.ROWID = src.row_id )
         WHEN MATCHED THEN UPDATE SET A.ProvisionAlt_Key
                                      ----SELECT *
                                       = src.ProvisionAlt_Key;
         MERGE INTO A 
         USING (SELECT A.ROWID row_id, (CASE 
         WHEN NVL(B.ASSETCLASSSHORTNAMEENUM, 'STD') = 'LOS' THEN BookValueINR
         ELSE (NVL(A.BookValueINR, 0) * NVL(C.PROVISIONUNSECURED, 0) / 100)
            END) AS TotalProvison
         FROM A ,InvestmentFinancialDetail A
                JOIN DIMASSETCLASS B   ON B.EFFECTIVEFROMTIMEKEY <= v_TIMEKEY
                AND B.EFFECTIVETOTIMEKEY >= v_TIMEKEY
                AND NVL(A.FinalAssetClassAlt_Key, 1) = B.ASSETCLASSALT_KEY
                JOIN DIMPROVISION_SEG C   ON C.EFFECTIVEFROMTIMEKEY <= v_TIMEKEY
                AND C.EFFECTIVETOTIMEKEY >= v_TIMEKEY
                AND NVL(A.PROVISIONALT_KEY, 1) = C.PROVISIONALT_KEY 
          WHERE FinalAssetClassAlt_Key > 1
           AND A.EFFECTIVEFROMTIMEKEY <= v_TIMEKEY
           AND A.EFFECTIVETOTIMEKEY >= v_TIMEKEY) src
         ON ( A.ROWID = src.row_id )
         WHEN MATCHED THEN UPDATE SET B.TotalProvison = src.TotalProvison;
         /* STD PROVISION ALTKEY */
         MERGE INTO A 
         USING (SELECT A.ROWID row_id, D.ProvisionAlt_Key
         FROM A ,InvestmentFinancialDetail A
                JOIN DimAssetClass C   ON C.AssetClassAlt_Key = NVL(A.FinalAssetClassAlt_Key, 1)
                AND ( C.EffectiveFromTimeKey <= v_TIMEKEY
                AND C.EffectiveToTimeKey >= v_TIMEKEY )
                JOIN DimProvision_SegSTD D   ON D.EffectiveFromTimeKey <= v_TIMEKEY
                AND D.EffectiveToTimeKey >= v_TIMEKEY
                AND D.ProvisionName = 'Other Portfolio' 
          WHERE C.ASSETCLASSGROUP = 'STD'
           AND ( A.EffectiveFromTimeKey <= v_TIMEKEY
           AND A.EffectiveToTimeKey >= v_TIMEKEY )) src
         ON ( A.ROWID = src.row_id )
         WHEN MATCHED THEN UPDATE SET A.ProvisionAlt_Key
                                      ----SELECT *
                                       = src.ProvisionAlt_Key;
         /* STD PROVISION maount */
         MERGE INTO A 
         USING (SELECT A.ROWID row_id, (CASE 
         WHEN NVL(B.ASSETCLASSSHORTNAMEENUM, 'STD') = 'LOS' THEN BookValueINR
         ELSE (NVL(A.BookValueINR, 0) * NVL(C.PROVISIONUNSECURED, 0) / 100)
            END) AS TotalProvison
         FROM A ,InvestmentFinancialDetail A
                JOIN DIMASSETCLASS B   ON B.EFFECTIVEFROMTIMEKEY <= v_TIMEKEY
                AND B.EFFECTIVETOTIMEKEY >= v_TIMEKEY
                AND NVL(A.FinalAssetClassAlt_Key, 1) = B.ASSETCLASSALT_KEY
                JOIN DimProvision_SegStd C   ON C.EFFECTIVEFROMTIMEKEY <= v_TIMEKEY
                AND C.EFFECTIVETOTIMEKEY >= v_TIMEKEY
                AND NVL(A.PROVISIONALT_KEY, 1) = C.PROVISIONALT_KEY 
          WHERE FinalAssetClassAlt_Key = 1
           AND A.EFFECTIVEFROMTIMEKEY <= v_TIMEKEY
           AND A.EFFECTIVETOTIMEKEY >= v_TIMEKEY) src
         ON ( A.ROWID = src.row_id )
         WHEN MATCHED THEN UPDATE SET B.TotalProvison = src.TotalProvison;
         ----/*----------------PROVISION ALT KEY ALL  ACCOUNTS--------------------------------*/
         /* DERIVATIVE */
         MERGE INTO A 
         USING (SELECT A.ROWID row_id, 0
         FROM A ,CurDat_RBL_MISDB_PROD.DerivativeDetail A 
          WHERE ( A.EffectiveFromTimeKey <= v_TimeKey
           AND A.EffectiveToTimeKey >= v_TimeKey )) src
         ON ( A.ROWID = src.row_id )
         WHEN MATCHED THEN UPDATE SET A.PROVISIONALT_KEY = 0;
         /* NPA PROVISION ALTKEY */
         MERGE INTO A 
         USING (SELECT A.ROWID row_id, D.ProvisionAlt_Key
         FROM A ,CurDat_RBL_MISDB_PROD.DerivativeDetail A
                JOIN DimAssetClass C   ON C.AssetClassAlt_Key = NVL(A.FinalAssetClassAlt_Key, 1)
                AND ( C.EffectiveFromTimeKey <= v_TIMEKEY
                AND C.EffectiveToTimeKey >= v_TIMEKEY )
                JOIN DimProvision_Seg D   ON D.EffectiveFromTimeKey <= v_TIMEKEY
                AND D.EffectiveToTimeKey >= v_TIMEKEY

                --AND A.DPD BETWEEN d.LowerDPD AND d.UpperDPDS
                AND c.AssetClassShortName = D.PROVISIONSHORTNAMEENUM 
          WHERE C.ASSETCLASSGROUP = 'NPA'
           AND ( A.EffectiveFromTimeKey <= v_TIMEKEY
           AND A.EffectiveToTimeKey >= v_TIMEKEY )
           AND D.SEGMENT = 'IRAC') src
         ON ( A.ROWID = src.row_id )
         WHEN MATCHED THEN UPDATE SET A.ProvisionAlt_Key
                                      ----SELECT *
                                       = src.ProvisionAlt_Key;
         /* NPA PROVISION maount */
         MERGE INTO A 
         USING (SELECT A.ROWID row_id, (CASE 
         WHEN NVL(B.ASSETCLASSSHORTNAMEENUM, 'STD') = 'LOS' THEN POS
         ELSE (NVL(A.POS, 0) * NVL(C.PROVISIONUNSECURED, 0) / 100)
            END) AS TotalProvison
         FROM A ,CurDat_RBL_MISDB_PROD.DerivativeDetail A
                JOIN DIMASSETCLASS B   ON B.EFFECTIVEFROMTIMEKEY <= v_TIMEKEY
                AND B.EFFECTIVETOTIMEKEY >= v_TIMEKEY
                AND NVL(A.FinalAssetClassAlt_Key, 1) = B.ASSETCLASSALT_KEY
                JOIN DIMPROVISION_SEG C   ON C.EFFECTIVEFROMTIMEKEY <= v_TIMEKEY
                AND C.EFFECTIVETOTIMEKEY >= v_TIMEKEY
                AND NVL(A.PROVISIONALT_KEY, 1) = C.PROVISIONALT_KEY 
          WHERE FinalAssetClassAlt_Key > 1
           AND A.EFFECTIVEFROMTIMEKEY <= v_TIMEKEY
           AND A.EFFECTIVETOTIMEKEY >= v_TIMEKEY) src
         ON ( A.ROWID = src.row_id )
         WHEN MATCHED THEN UPDATE SET A.TotalProvison = src.TotalProvison;
         /* STD PROVISION ALTKEY */
         MERGE INTO A 
         USING (SELECT A.ROWID row_id, D.ProvisionAlt_Key
         FROM A ,CurDat_RBL_MISDB_PROD.DerivativeDetail A
                JOIN DimAssetClass C   ON C.AssetClassAlt_Key = NVL(A.FinalAssetClassAlt_Key, 1)
                AND ( C.EffectiveFromTimeKey <= v_TIMEKEY
                AND C.EffectiveToTimeKey >= v_TIMEKEY )
                JOIN DimProvision_SegSTD D   ON D.EffectiveFromTimeKey <= v_TIMEKEY
                AND D.EffectiveToTimeKey >= v_TIMEKEY
                AND D.ProvisionName = 'Other Portfolio' 
          WHERE C.ASSETCLASSGROUP = 'STD'
           AND ( A.EffectiveFromTimeKey <= v_TIMEKEY
           AND A.EffectiveToTimeKey >= v_TIMEKEY )) src
         ON ( A.ROWID = src.row_id )
         WHEN MATCHED THEN UPDATE SET A.ProvisionAlt_Key
                                      ----SELECT *
                                       = src.ProvisionAlt_Key;
         /* STD PROVISION maount */
         MERGE INTO A 
         USING (SELECT A.ROWID row_id, (CASE 
         WHEN NVL(B.ASSETCLASSSHORTNAMEENUM, 'STD') = 'LOS' THEN POS
         ELSE (NVL(A.POS, 0) * NVL(C.PROVISIONUNSECURED, 0) / 100)
            END) AS TotalProvison
         FROM A ,CurDat_RBL_MISDB_PROD.DerivativeDetail A
                JOIN DIMASSETCLASS B   ON B.EFFECTIVEFROMTIMEKEY <= v_TIMEKEY
                AND B.EFFECTIVETOTIMEKEY >= v_TIMEKEY
                AND NVL(A.FinalAssetClassAlt_Key, 1) = B.ASSETCLASSALT_KEY
                JOIN DimProvision_SegStd C   ON C.EFFECTIVEFROMTIMEKEY <= v_TIMEKEY
                AND C.EFFECTIVETOTIMEKEY >= v_TIMEKEY
                AND NVL(A.PROVISIONALT_KEY, 1) = C.PROVISIONALT_KEY 
          WHERE FinalAssetClassAlt_Key = 1
           AND A.EFFECTIVEFROMTIMEKEY <= v_TIMEKEY
           AND A.EFFECTIVETOTIMEKEY >= v_TIMEKEY) src
         ON ( A.ROWID = src.row_id )
         WHEN MATCHED THEN UPDATE SET A.TotalProvison = src.TotalProvison;
         --------------Added for DashBoard 04-03-2021
         UPDATE BANDAUDITSTATUS
            SET CompletedCount = CompletedCount + 1
          WHERE  BandName = 'ASSET CLASSIFICATION';

      END;
   EXCEPTION
      WHEN OTHERS THEN

   BEGIN
      UPDATE PRO_RBL_MISDB_PROD.AclRunningProcessStatus
         SET COMPLETED = 'N',
             ERRORDATE = SYSDATE,
             ERRORDESCRIPTION = SQLERRM,
             COUNT = NVL(COUNT, 0) + 1
       WHERE  RUNNINGPROCESSNAME = 'InvestmentDataProcessing';

   END;END;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "RBL_TEMPDB";
  GRANT DEBUG ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."INVESTMENTDERIVATIVEPROVISIONCAL_27042023" TO "ADF_CDR_RBL_STGDB";
