--------------------------------------------------------
--  DDL for Procedure MARKINGFLGPROCESSING_04122023
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" /*==========================================
 AUTHER : SANJEEV KUMAR SHARMA
 CREATE DATE : 04-04-2018
 MODIFY DATE : 04-04-2018
 DESCRIPTION : MARKING OF FLG PROCESSING
 --EXEC MarkingFlgProcessing  @TIMEKEY
==============================================*/
(
  v_TIMEKEY IN NUMBER
)
AS
   v_cursor SYS_REFCURSOR;

BEGIN

   BEGIN

      BEGIN
         UPDATE PRO_RBL_MISDB_PROD.CUSTOMERCAL
            SET FlgProcessing = 'Y'
          WHERE  ( EffectiveFromTimeKey <= v_TIMEKEY
           AND EffectiveTOTimeKey >= v_TIMEKEY );

      END;
   EXCEPTION
      WHEN OTHERS THEN

   BEGIN
      OPEN  v_cursor FOR
         SELECT 'ERROR PROCEDURE :' || utils.error_procedure || ' ERROR MESSAGE:' || SQLERRM 
           FROM DUAL  ;
         DBMS_SQL.RETURN_RESULT(v_cursor);

   END;END;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "RBL_TEMPDB";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."MARKINGFLGPROCESSING_04122023" TO "ADF_CDR_RBL_STGDB";
