--------------------------------------------------------
--  Constraints for Table PROCESSMONITOR
--------------------------------------------------------

  ALTER TABLE "MAIN_PRO"."PROCESSMONITOR" MODIFY ("IDENTITYKEY" NOT NULL ENABLE);
  ALTER TABLE "MAIN_PRO"."PROCESSMONITOR" ADD CONSTRAINT "PK__PROCESSM__796424B8162944A2" PRIMARY KEY ("IDENTITYKEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
