--------------------------------------------------------
--  DDL for Procedure PROCESSINGSTEPS_04122023
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "MAIN_PRO"."PROCESSINGSTEPS_04122023" 
AS
   v_cursor SYS_REFCURSOR;
   v_TimeKey NUMBER(10,0);
   v_ProcessingDateAudit VARCHAR2(200) := ( SELECT Date_ 
     FROM RBL_MISDB_PROD.Automate_Advances 
    WHERE  EXT_FLG = 'Y' );

BEGIN

   --UPDATE PRO.EXTDATE_MISDB SET LAST_EXTDATE = (SELECT MAX(PROCESSINGDATE)  FROM PRO.PACKAGE_AUDITHIST) WHERE Flg='Y'--Extration date
   --UPDATE PRO.EXTDATE_MISDB SET Flg='U' WHERE   Flg='Y'
   --UPDATE DBO.SysDataMatrix SET CurrentStatus='U' WHERE   CurrentStatus='C'
   --DECLARE  @vEffectivefrom  Int SET @vEffectiveFrom=(SELECT TimeKey FROM [dbo].Automate_Advances WHERE EXT_FLG='Y')
   --DECLARE @TimeKey  Int SET @TimeKey=(SELECT TimeKey FROM [dbo].Automate_Advances WHERE EXT_FLG='Y')
   --DECLARE @DATE AS DATE =(SELECT Date FROM [dbo].Automate_Advances WHERE EXT_FLG='Y')
   UPDATE RBL_MISDB_PROD.Automate_Advances
      SET EXT_FLG = 'U'
    WHERE  EXT_FLG = 'Y';
   UPDATE RBL_MISDB_PROD.SysDataMatrix
      SET CurrentStatus = 'U'
    WHERE  CurrentStatus = 'C';
   UPDATE RBL_MISDB_PROD.Automate_Advances
      SET EXT_FLG = 'Y'
    WHERE  TimeKey IN ( SELECT MAX(Package_AuditHist.TimeKey)  + 1 
                        FROM PRO_RBL_MISDB_PROD.Package_AuditHist 
                         WHERE  Package_AuditHist.IdentityKey = 5 )
   ;
   UPDATE SysDataMatrix
      SET CurrentStatus = 'C'
    WHERE  TimeKey IN ( SELECT MAX(Package_AuditHist.TimeKey)  + 1 
                        FROM PRO_RBL_MISDB_PROD.Package_AuditHist 
                         WHERE  Package_AuditHist.IdentityKey = 5 )
   ;
   OPEN  v_cursor FOR
      SELECT 'Checksum' TableName  ,
             COUNT(TABLE_NAME)  COUNT  ,
             UTILS.CONVERT_TO_VARCHAR2(ETL_DATE,200) ETL_DATE  
        FROM RBL_MISDB_PROD.EXTRACTION_STATUS 
       WHERE  ETL_DATE IN ( SELECT Date_ 
                            FROM RBL_MISDB_PROD.Automate_Advances 
                             WHERE  EXT_FLG = 'Y' --*******UNCOMMENT THIS LINE***********
               )

        GROUP BY ETL_DATE

         HAVING COUNT(TABLE_NAME)  = 2 ;
      DBMS_SQL.RETURN_RESULT(v_cursor);--***********TO BE SET TO 2***********
   OPEN  v_cursor FOR
      SELECT 'ExtractionStatus' TableName  ,
             Table_Name LoadedTables  ,
             ETL_Date ETLDate  
        FROM RBL_MISDB_PROD.EXTRACTION_STATUS  ;
      DBMS_SQL.RETURN_RESULT(v_cursor);--***********LINE TO BE ADDED***********
   OPEN  v_cursor FOR
      SELECT PARAMETERNAME TableName  ,
             ParameterValue TimePeriod  
        FROM SYSSOLUTIONPARAMETER 
       WHERE  PARAMETERNAME = 'REFRESHPERIOD' ;
      DBMS_SQL.RETURN_RESULT(v_cursor);
   OPEN  v_cursor FOR
      SELECT 'ProcessingStatus' TableName  
        FROM PRO_RBL_MISDB_PROD.Package_AUDIT 
       WHERE  IDENTITYKEY = '5'
                AND EXECUTIONSTATUS = 'Y'
                AND ProcessingDate = ( SELECT Date_ 
                                       FROM RBL_MISDB_PROD.Automate_Advances 
                                        WHERE  EXT_FLG = 'Y' ) ;
      DBMS_SQL.RETURN_RESULT(v_cursor);--***********LINE TO BE ADDED***********
   DELETE PRO_RBL_MISDB_PROD.Package_AUDIT

    WHERE  ProcessingDate IN ( SELECT MAX(ProcessingDate)  
                               FROM PRO_RBL_MISDB_PROD.Package_AuditHist 
                                WHERE  IdentityKey = 5 )
   ;--***********LINE TO BE ADDED***********
   SELECT TimeKey 

     INTO v_TimeKey
     FROM RBL_MISDB_PROD.Automate_Advances 
    WHERE  EXT_FLG = 'Y';
   OPEN  v_cursor FOR
      SELECT 'ProcessingDate' TableName  ,
             MonthLastDate PROCESSINGDATE  
        FROM SYSDATAMATRIX 
       WHERE  CURRENTSTATUS = 'C' --***********LINE TO BE MODIFIED***********
    ;
      DBMS_SQL.RETURN_RESULT(v_cursor);

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "RBL_TEMPDB";
  GRANT DEBUG ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."PROCESSINGSTEPS_04122023" TO "ADF_CDR_RBL_STGDB";
