--------------------------------------------------------
--  DDL for Procedure RECALCULATE_BALANCE_AGAIN_21082024
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" /*=========================================
 AUTHER : TRILOKI KHANNA
 CREATE DATE : 29-06-2020
 MODIFY DATE : 29-06-2020
 DESCRIPTION :Recalculate_Balance_Again
 EXEC [PRO].[Recalculate_Balance_Again] 4925
=============================================*/
(
  v_TIMEKEY IN NUMBER
)
AS

BEGIN

   /*----------------Calculate Balance Again in Account cal table ---------------------------- */
   MERGE INTO A 
   USING (SELECT A.ROWID row_id, NVL(PrincOutStd, 0) AS Balance
   FROM A ,PRO_RBL_MISDB_PROD.ACCOUNTCAL A ) src
   ON ( A.ROWID = src.row_id )
   WHEN MATCHED THEN UPDATE SET Balance = src.Balance;
   MERGE INTO A 
   USING (SELECT A.ROWID row_id, NVL(PrincOutStd, 0) + NVL(IntOverdue, 0) AS Balance
   FROM A ,PRO_RBL_MISDB_PROD.ACCOUNTCAL A 
    WHERE a.FinalAssetClassAlt_Key = 1) src
   ON ( A.ROWID = src.row_id )
   WHEN MATCHED THEN UPDATE SET Balance = src.Balance;
   --UPDATE A SET Balance=isnull(Balance,0)- isnull(AdvanceRecovery,0)
   MERGE INTO A 
   USING (SELECT A.ROWID row_id, (CASE 
   WHEN (NVL(A.Balance, 0) - (NVL(A.AdvanceRecovery, 0))) < 0 THEN (NVL(A.Balance, 0) - (NVL(A.AdvanceRecovery, 0)))
   ELSE (NVL(A.Balance, 0) - (NVL(A.AdvanceRecovery, 0)))
      END) AS Balance
   FROM A ,PRO_RBL_MISDB_PROD.ACCOUNTCAL A 
    WHERE NVL(AdvanceRecovery, 0) > 0) src
   ON ( A.ROWID = src.row_id )
   WHEN MATCHED THEN UPDATE SET Balance = src.Balance;
   --UPDATE  A SET BALANCE=0  FROM PRO.ACCOUNTCAL A  WHERE ISNULL(BALANCE,0)<0
   ---UPDATE NotionalInttAmt ---- 
   MERGE INTO A 
   USING (SELECT A.ROWID row_id, CASE 
   WHEN NVL(InttRate, 0) > 0 THEN (NVL(Balance, 0) * NVL(InttRate, 0)) / 100
   ELSE 0
      END AS NotionalInttAmt
   FROM A ,PRO_RBL_MISDB_PROD.ACCOUNTCAL A ) src
   ON ( A.ROWID = src.row_id )
   WHEN MATCHED THEN UPDATE SET NotionalInttAmt = src.NotionalInttAmt;
   IF utils.object_id('TEMPDB..tt_CUSTTOTOSCUST_3') IS NOT NULL THEN
    EXECUTE IMMEDIATE ' TRUNCATE TABLE tt_CUSTTOTOSCUST_3 ';
   END IF;
   DELETE FROM tt_CUSTTOTOSCUST_3;
   UTILS.IDENTITY_RESET('tt_CUSTTOTOSCUST_3');

   INSERT INTO tt_CUSTTOTOSCUST_3 ( 
   	SELECT CUSTOMERENTITYID ,
           SUM(NVL(BALANCE, 0))  BALANCE  
   	  FROM PRO_RBL_MISDB_PROD.ACCOUNTCAL 
   	  GROUP BY CUSTOMERENTITYID );
   UPDATE PRO_RBL_MISDB_PROD.CUSTOMERCAL
      SET TOTOSCUST = 0;
   MERGE INTO A 
   USING (SELECT A.ROWID row_id, BALANCE
   FROM A ,PRO_RBL_MISDB_PROD.CUSTOMERCAL A
          JOIN tt_CUSTTOTOSCUST_3 B   ON A.CustomerEntityID = B.CUSTOMERENTITYID ) src
   ON ( A.ROWID = src.row_id )
   WHEN MATCHED THEN UPDATE SET A.TOTOSCUST = BALANCE;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "RBL_TEMPDB";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."RECALCULATE_BALANCE_AGAIN_21082024" TO "ADF_CDR_RBL_STGDB";
