--------------------------------------------------------
--  DDL for Procedure UPDATEASSETCLASSFORPROVISION_21082024
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" /*==================================      
AUTHER : SANJEEV KUMAR SHARMA      
CREATE DATE : 25-03-2017      
MODIFY DATE : 25-03-2017      
DESCRIPTION : UPDATE  USER ASSET CLASS AND TXN ASSET CLASS AND SYSTEMASSETCLASS      
--EXEC UpdateAssetClassForProvision @Timekey=4463      
==========================================*/
(
  v_Timekey IN NUMBER
)
AS
   v_cursor SYS_REFCURSOR;

BEGIN

   BEGIN

      BEGIN
         /*----------******UPDATING CUSTOMERASSET_CLASS TO ALL ACCOUNTS OF the CUSTOMER     
                           FOR PROVISION  COMPUTATION AT ACCOUNT LEVEL****----------------------*/
         MERGE INTO B 
         USING (SELECT B.ROWID row_id, a.SrcAssetClassAlt_Key, a.SrcAssetClassAlt_Key
         FROM B ,PRO_RBL_MISDB_PROD.CUSTOMERCAL A
                JOIN PRO_RBL_MISDB_PROD.ACCOUNTCAL B   ON A.CustomerEntityID = B.CustomerEntityID ) src
         ON ( B.ROWID = src.row_id )
         WHEN MATCHED THEN UPDATE SET b.InitialAssetClassAlt_Key = src.SrcAssetClassAlt_Key,
                                      b.FinalAssetClassAlt_Key = src.SrcAssetClassAlt_Key;

      END;
   EXCEPTION
      WHEN OTHERS THEN

   BEGIN
      OPEN  v_cursor FOR
         SELECT 'ERROR PROCEDURE :' || utils.error_procedure || 'ERROR MESSAGE :' || SQLERRM 
           FROM DUAL  ;
         DBMS_SQL.RETURN_RESULT(v_cursor);

   END;END;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "RBL_TEMPDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEASSETCLASSFORPROVISION_21082024" TO "ADF_CDR_RBL_STGDB";
