--------------------------------------------------------
--  DDL for Procedure UPDATENETBALANCE_ACCOUNTWISE_21082024
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" /*==========================    
AUTHER : TRILOKI KHANNA    
CREATE DATE : 27-11-2019    
MODIFY DATE : 27-11-2019    
DESCRIPTION : UPDATE NET BALANCE ACCOUNT WISE    
--EXEC [dbo].[UpdateNetBalance_AccountWise] @TimeKey=25410       
======================================================*/
(
  v_TimeKey IN NUMBER
)
AS

BEGIN

   BEGIN

      BEGIN
         --UPDATE A         
         --SET  
         --		NetBalance = (CASE WHEN (isnull(A.Balance,0) - (isnull(A.CoverGovGur,0)+ ISNULL(UnAdjSubSidy,0)+ ISNULL(WriteOffAmount,0))) < 0      
         --         THEN 0         
         --     	   ELSE (isnull(A.Balance,0) - (isnull(A.CoverGovGur,0)+ ISNULL(UnAdjSubSidy,0)+ ISNULL(WriteOffAmount,0)))  
         --     END)        
         --FROM PRO.AccountCal A       
         MERGE INTO A 
         USING (SELECT A.ROWID row_id, NVL(PrincOutStd, 0) AS NetBalance
         FROM A ,tt_AccountCal_52 A
                JOIN DimAssetClass B   ON B.AssetClassAlt_Key = NVL(A.FinalAssetClassAlt_Key, 1)
                AND ( B.EffectiveFromTimeKey <= v_TimeKey
                AND B.EffectiveToTimeKey >= v_TimeKey ) 
          WHERE B.ASSETCLASSGROUP = 'NPA') src
         ON ( A.ROWID = src.row_id )
         WHEN MATCHED THEN UPDATE SET A.NetBalance = src.NetBalance;
         MERGE INTO A 
         USING (SELECT A.ROWID row_id, 0
         FROM A ,tt_AccountCal_52 A
                JOIN DimAssetClass B   ON B.AssetClassAlt_Key = NVL(A.FinalAssetClassAlt_Key, 1)
                AND ( B.EffectiveFromTimeKey <= v_TimeKey
                AND B.EffectiveToTimeKey >= v_TimeKey )
                JOIN ExceptionFinalStatusType C   ON C.ACID = A.CustomerAcID
                AND ( C.EffectiveFromTimeKey <= v_TimeKey
                AND C.EffectiveToTimeKey >= v_TimeKey ) 
          WHERE B.ASSETCLASSGROUP = 'NPA'
           AND C.StatusType IN ( 'TWO','WO','Charge Off' )
         ) src
         ON ( A.ROWID = src.row_id )
         WHEN MATCHED THEN UPDATE SET A.NetBalance = 0;
         -----------------------------------
         MERGE INTO A 
         USING (SELECT A.ROWID row_id, 0
         FROM A ,tt_AccountCal_52 A
                JOIN DimAssetClass B   ON B.AssetClassAlt_Key = NVL(A.FinalAssetClassAlt_Key, 1)
                AND ( B.EffectiveFromTimeKey <= v_TimeKey
                AND B.EffectiveToTimeKey >= v_TimeKey ) 
          WHERE B.ASSETCLASSGROUP = 'NPA'
           AND NVL(WriteOffAmount, 0) > 0) src
         ON ( A.ROWID = src.row_id )
         WHEN MATCHED THEN UPDATE SET A.NetBalance = 0;
         -------------------------------
         MERGE INTO A 
         USING (SELECT A.ROWID row_id, NVL(Balance, 0) AS NetBalance
         FROM A ,tt_AccountCal_52 A
                JOIN DimAssetClass B   ON B.AssetClassAlt_Key = NVL(A.FinalAssetClassAlt_Key, 1)
                AND ( B.EffectiveFromTimeKey <= v_TimeKey
                AND B.EffectiveToTimeKey >= v_TimeKey ) 
          WHERE B.ASSETCLASSGROUP <> 'NPA') src
         ON ( A.ROWID = src.row_id )
         WHEN MATCHED THEN UPDATE SET A.NetBalance = src.NetBalance;
         MERGE INTO A 
         USING (SELECT A.ROWID row_id, 0
         FROM A ,tt_AccountCal_52 A 
          WHERE NVL(NetBalance, 0) < 0) src
         ON ( A.ROWID = src.row_id )
         WHEN MATCHED THEN UPDATE SET A.NetBalance = 0;
         ---BELOW CODE SHIFTED TO NET BALANCE CALCULATION SP
         MERGE INTO A 
         USING (SELECT A.ROWID row_id, (A.NetBalance * A.AddlProvisionPer) / 100 AS AddlProvision
         FROM A ,tt_AccountCal_52 A 
          WHERE NVL(A.AddlProvisionPer, 0) <> 0) src
         ON ( A.ROWID = src.row_id )
         WHEN MATCHED THEN UPDATE SET A.AddlProvision = src.AddlProvision;
         UPDATE PRO_RBL_MISDB_PROD.AclRunningProcessStatus
            SET COMPLETED = 'Y',
                ERRORDATE = NULL,
                ERRORDESCRIPTION = NULL,
                COUNT = NVL(COUNT, 0) + 1
          WHERE  RUNNINGPROCESSNAME = 'UpdateNetBalance_AccountWise';

      END;
   EXCEPTION
      WHEN OTHERS THEN

   BEGIN
      ----------------Added for DashBoard 04-03-2021
      --Update BANDAUDITSTATUS set CompletedCount=CompletedCount+1 where BandName='ASSET CLASSIFICATION'
      UPDATE PRO_RBL_MISDB_PROD.AclRunningProcessStatus
         SET COMPLETED = 'N',
             ERRORDATE = SYSDATE,
             ERRORDESCRIPTION = SQLERRM,
             COUNT = NVL(COUNT, 0) + 1
       WHERE  RUNNINGPROCESSNAME = 'UpdateNetBalance_AccountWise';

   END;END;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "RBL_TEMPDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATENETBALANCE_ACCOUNTWISE_21082024" TO "ADF_CDR_RBL_STGDB";
