--------------------------------------------------------
--  DDL for Procedure UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" /*======================          
AUTHER : SANJEEV KUMAR SHARAMA          
CREATE DATE : 06-03-2017          
MODIFY DATE : 06-03-2017          
DESCRIPTION : UPDATE unServisedIntt AccountWise          
=======================================*/
(
  v_TimeKey IN NUMBER
)
AS
   v_cursor SYS_REFCURSOR;

BEGIN

   BEGIN
      DECLARE
         v_ProcessingDate VARCHAR2(200);

      BEGIN
         SELECT Date_ 

           INTO v_ProcessingDate
           FROM SysDayMatrix 
          WHERE  Timekey = v_TimeKey;

      END;
   EXCEPTION
      WHEN OTHERS THEN

   BEGIN
      ----- Update Net Balance Calculate Amount In AdvacCal Table in NetBalance column            
      --Update A             
      --Set unServisedIntt = 0            
      --From pro.AccountCal A          
      --UPDATE A             
      --SET A.unServisedIntt = (CASE WHEN isnull(A.InterestOverdue,0)+ISNULL(A.OtherOverdue,0)>  A.Balance      
      --                          THEN A.Balance       
      --                        ELSE isnull(A.InterestOverdue,0)+ISNULL(A.OtherOverdue,0) END )     
      --From pro.AccountCal A           
      --UPDATE A          
      --Set unServisedIntt = CASE When  DemandAmt> A.Balance THEN A.Balance ELSE DemandAmt END          
      --From pro.AccountCal A                  
      --Inner join (select CustomerACID,  sum(BalanceDemand) as DemandAmt from AdvAcCCDemandDetail           
      --			where BalanceDemand > 0 and  DemandType = 'INTEREST'         
      --			and DemandDate between  '2015-07-01' and  @ProcessingDate        
      --			Group by CustomerACID
      --			) B           
      --    On A.CustomerACID = B.CustomerACID           
      --where  A.Balance>0         
      OPEN  v_cursor FOR
         SELECT 'Procedure Name :' || utils.error_procedure || 'Error Message :' || SQLERRM 
           FROM DUAL  ;
         DBMS_SQL.RETURN_RESULT(v_cursor);

   END;END;

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "RBL_TEMPDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "MAIN_PRO"."UPDATEUNSERVISEDINTT_ACCOUNTWISE_04122023" TO "ADF_CDR_RBL_STGDB";
