--------------------------------------------------------
--  DDL for Table ACCESS$
--------------------------------------------------------

  CREATE TABLE "SYS"."ACCESS$" SHARING=METADATA 
   (	"D_OBJ#" NUMBER, 
	"ORDER#" NUMBER, 
	"COLUMNS" RAW(126), 
	"TYPES" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16384 NEXT 106496 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
