--------------------------------------------------------
--  DDL for Table ACLMVREFSTAT$
--------------------------------------------------------

  CREATE TABLE "SYS"."ACLMVREFSTAT$" SHARING=METADATA 
   (	"ACL_MVIEW_OBJ#" NUMBER, 
	"JOB_START_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"JOB_END_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"TOTAL_INSERTS" NUMBER, 
	"TOTAL_DELETES" NUMBER, 
	"TOTAL_UPDATES" NUMBER, 
	"ROW_UPDATE_COUNT" NUMBER, 
	"STATUS" NUMBER, 
	"ERROR_MESSAGE" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
