--------------------------------------------------------
--  DDL for Table ADO_IMSEGTASKDETAILS$
--------------------------------------------------------

  CREATE TABLE "SYS"."ADO_IMSEGTASKDETAILS$" SHARING=METADATA 
   (	"TASK_ID" NUMBER, 
	"OBJ#" NUMBER, 
	"ACTION" NUMBER, 
	"EST_IMSIZE" NUMBER, 
	"VAL" NUMBER, 
	"IM_POP_STATE" NUMBER, 
	"STATE" NUMBER, 
	"IMBYTES" NUMBER, 
	"BLOCKSINMEM" NUMBER, 
	"DATABLOCKS" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" VARCHAR2(128 BYTE), 
	"SPARE5" VARCHAR2(128 BYTE), 
	"SPARE6" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
