GRANT READ ON "SYS"."ALL_USERS" TO PUBLIC WITH GRANT OPTION;
  GRANT SELECT ON "SYS"."ALL_USERS" TO "XDB";
  GRANT SELECT ON "SYS"."ALL_USERS" TO "MDSYS";
  GRANT READ ON "SYS"."ALL_USERS" TO "DVSYS";
