--------------------------------------------------------
--  DDL for Table APPLY$_DEST_OBJ
--------------------------------------------------------

  CREATE TABLE "SYS"."APPLY$_DEST_OBJ" SHARING=METADATA 
   (	"ID" NUMBER, 
	"SOURCE_OWNER" VARCHAR2(128 BYTE), 
	"SOURCE_NAME" VARCHAR2(128 BYTE), 
	"TYPE" NUMBER, 
	"OWNER" VARCHAR2(128 BYTE), 
	"NAME" VARCHAR2(128 BYTE), 
	"APPLY#" NUMBER, 
	"STATUS" NUMBER, 
	"ERROR_NOTIFIER" VARCHAR2(92 BYTE), 
	"SPARE1" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
