--------------------------------------------------------
--  DDL for Table APPLY$_CHANGE_HANDLERS
--------------------------------------------------------

  CREATE TABLE "SYS"."APPLY$_CHANGE_HANDLERS" SHARING=METADATA 
   (	"CHANGE_TABLE_OWNER" VARCHAR2(128 BYTE), 
	"CHANGE_TABLE_NAME" VARCHAR2(128 BYTE), 
	"SOURCE_TABLE_OWNER" VARCHAR2(128 BYTE), 
	"SOURCE_TABLE_NAME" VARCHAR2(128 BYTE), 
	"HANDLER_NAME" VARCHAR2(128 BYTE), 
	"CAPTURE_VALUES" NUMBER, 
	"APPLY_NAME" VARCHAR2(128 BYTE), 
	"OPERATION" NUMBER, 
	"CREATION_TIME" TIMESTAMP (6), 
	"MODIFICATION_TIME" TIMESTAMP (6), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(4000 BYTE), 
	"SPARE4" VARCHAR2(4000 BYTE), 
	"SPARE5" TIMESTAMP (6), 
	"SPARE6" TIMESTAMP (6), 
	"SPARE7" RAW(2000)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
