--------------------------------------------------------
--  Constraints for Table APPLY$_DEST_OBJ
--------------------------------------------------------

  ALTER TABLE "SYS"."APPLY$_DEST_OBJ" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."APPLY$_DEST_OBJ" MODIFY ("SOURCE_OWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."APPLY$_DEST_OBJ" MODIFY ("SOURCE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."APPLY$_DEST_OBJ" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."APPLY$_DEST_OBJ" MODIFY ("OWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."APPLY$_DEST_OBJ" MODIFY ("NAME" NOT NULL ENABLE);
