--------------------------------------------------------
--  DDL for Table APPLY$_VIRTUAL_OBJ_CONS
--------------------------------------------------------

  CREATE TABLE "SYS"."APPLY$_VIRTUAL_OBJ_CONS" SHARING=METADATA 
   (	"OWNER" VARCHAR2(128 BYTE), 
	"NAME" VARCHAR2(128 BYTE), 
	"POWNER" VARCHAR2(128 BYTE), 
	"PNAME" VARCHAR2(128 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(128 BYTE), 
	"SPARE4" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
