--------------------------------------------------------
--  DDL for Table APPLY$_CONSTRAINT_COLUMNS
--------------------------------------------------------

  CREATE TABLE "SYS"."APPLY$_CONSTRAINT_COLUMNS" SHARING=METADATA 
   (	"OWNER" VARCHAR2(128 BYTE), 
	"NAME" VARCHAR2(128 BYTE), 
	"CONSTRAINT_NAME" VARCHAR2(128 BYTE), 
	"CNAME" VARCHAR2(128 BYTE), 
	"CPOS" NUMBER, 
	"LONG_CNAME" VARCHAR2(4000 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(128 BYTE), 
	"SPARE4" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
