--------------------------------------------------------
--  DDL for Table APPLY$_PROCEDURE_STATS
--------------------------------------------------------

  CREATE TABLE "SYS"."APPLY$_PROCEDURE_STATS" SHARING=METADATA 
   (	"APPLY#" NUMBER, 
	"SERVER_ID" NUMBER, 
	"SAVE_TIME" DATE, 
	"STARTUP_TIME" DATE, 
	"PROCEDURE_OWNER" VARCHAR2(128 BYTE), 
	"PACKAGE_NAME" VARCHAR2(128 BYTE), 
	"PROCEDURE_NAME" VARCHAR2(128 BYTE), 
	"LAST_UPDATE" DATE, 
	"TOTAL_EXECUTIONS" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" NUMBER, 
	"SPARE5" VARCHAR2(4000 BYTE), 
	"SPARE6" VARCHAR2(4000 BYTE), 
	"SPARE7" DATE, 
	"SPARE8" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
