--------------------------------------------------------
--  DDL for Table APPLY$_DEST_OBJ_OPS
--------------------------------------------------------

  CREATE TABLE "SYS"."APPLY$_DEST_OBJ_OPS" SHARING=METADATA 
   (	"OBJECT_NUMBER" NUMBER, 
	"SNAME" VARCHAR2(128 BYTE), 
	"ONAME" VARCHAR2(128 BYTE), 
	"APPLY_NAME" VARCHAR2(128 BYTE), 
	"APPLY_OPERATION" NUMBER, 
	"ERROR_HANDLER" VARCHAR2(1 BYTE), 
	"USER_APPLY_PROCEDURE" VARCHAR2(392 BYTE), 
	"HANDLER_NAME" VARCHAR2(128 BYTE) DEFAULT null, 
	"ASSEMBLE_LOBS" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"SET_BY" NUMBER DEFAULT NULL, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
