--------------------------------------------------------
--  Constraints for Table APPLY$_CONSTRAINT_COLUMNS
--------------------------------------------------------

  ALTER TABLE "SYS"."APPLY$_CONSTRAINT_COLUMNS" MODIFY ("OWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."APPLY$_CONSTRAINT_COLUMNS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."APPLY$_CONSTRAINT_COLUMNS" MODIFY ("CONSTRAINT_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."APPLY$_CONSTRAINT_COLUMNS" MODIFY ("CNAME" NOT NULL ENABLE);
