--------------------------------------------------------
--  Constraints for Table APPLY$_SOURCE_OBJ
--------------------------------------------------------

  ALTER TABLE "SYS"."APPLY$_SOURCE_OBJ" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."APPLY$_SOURCE_OBJ" MODIFY ("OWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."APPLY$_SOURCE_OBJ" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."APPLY$_SOURCE_OBJ" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."APPLY$_SOURCE_OBJ" MODIFY ("SOURCE_DB_NAME" NOT NULL ENABLE);
