--------------------------------------------------------
--  DDL for Table APPLY$_AUTO_CDR_COLUMN_GROUPS
--------------------------------------------------------

  CREATE TABLE "SYS"."APPLY$_AUTO_CDR_COLUMN_GROUPS" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"COLUMN_GROUP_NAME" VARCHAR2(128 BYTE), 
	"COLUMN_GROUP_ID" NUMBER, 
	"FLAGS" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" TIMESTAMP (6), 
	"SPARE5" VARCHAR2(4000 BYTE), 
	"SPARE6" VARCHAR2(4000 BYTE), 
	"SPARE7" VARCHAR2(4000 BYTE), 
	"SPARE8" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
