--------------------------------------------------------
--  DDL for Table APPLY$_ERROR_TXN
--------------------------------------------------------

  CREATE TABLE "SYS"."APPLY$_ERROR_TXN" SHARING=METADATA 
   (	"MSG_ID" RAW(16), 
	"LOCAL_TRANSACTION_ID" VARCHAR2(22 BYTE), 
	"TXN_MESSAGE_NUMBER" NUMBER, 
	"ERROR_NUMBER" NUMBER, 
	"ERROR_MESSAGE" VARCHAR2(4000 BYTE), 
	"FLAGS" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(4000 BYTE), 
	"SPARE4" VARCHAR2(4000 BYTE), 
	"SPARE5" RAW(2000), 
	"SPARE6" TIMESTAMP (6), 
	"SOURCE_OBJECT_OWNER" VARCHAR2(128 BYTE), 
	"SOURCE_OBJECT_NAME" VARCHAR2(128 BYTE), 
	"DEST_OBJECT_OWNER" VARCHAR2(128 BYTE), 
	"DEST_OBJECT_NAME" VARCHAR2(128 BYTE), 
	"PRIMARY_KEY" VARCHAR2(4000 BYTE), 
	"POSITION" RAW(64), 
	"MESSAGE_FLAGS" NUMBER, 
	"OPERATION" VARCHAR2(100 BYTE), 
	"SEQ#" NUMBER, 
	"RBA" NUMBER, 
	"INDEX#" NUMBER, 
	"SPARE7" NUMBER, 
	"SPARE8" NUMBER, 
	"SPARE9" VARCHAR2(4000 BYTE), 
	"SPARE10" VARCHAR2(4000 BYTE), 
	"SPARE11" RAW(1000), 
	"SPARE12" RAW(1000), 
	"MESSAGE" "SYS"."ANYDATA" , 
	"CG_INFO" VARCHAR2(4000 BYTE), 
	"SOURCE_PACKAGE_NAME" VARCHAR2(128 BYTE), 
	"DEST_PACKAGE_NAME" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" 
 OPAQUE TYPE ("MESSAGE") STORE AS SECUREFILE LOB (
  ENABLE STORAGE IN ROW CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES ) ;
