--------------------------------------------------------
--  DDL for Table APPLY$_SOURCE_SCHEMA
--------------------------------------------------------

  CREATE TABLE "SYS"."APPLY$_SOURCE_SCHEMA" SHARING=METADATA 
   (	"SOURCE_DB_NAME" VARCHAR2(128 BYTE), 
	"GLOBAL_FLAG" NUMBER, 
	"NAME" VARCHAR2(128 BYTE), 
	"DBLINK" VARCHAR2(128 BYTE), 
	"INST_SCN" NUMBER, 
	"SPARE1" NUMBER, 
	"INST_EXTERNAL_POS" RAW(64), 
	"SPARE2" VARCHAR2(4000 BYTE), 
	"SPARE3" RAW(2000), 
	"SOURCE_ROOT_NAME" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
  GRANT DELETE ON "SYS"."APPLY$_SOURCE_SCHEMA" TO "SYSBACKUP";
  GRANT INSERT ON "SYS"."APPLY$_SOURCE_SCHEMA" TO "SYSBACKUP";
