--------------------------------------------------------
--  DDL for Table APPLY$_ERROR_HANDLER
--------------------------------------------------------

  CREATE TABLE "SYS"."APPLY$_ERROR_HANDLER" SHARING=METADATA 
   (	"OBJECT_NUMBER" NUMBER, 
	"METHOD_NAME" VARCHAR2(92 BYTE), 
	"RESOLUTION_COLUMN" VARCHAR2(4000 BYTE), 
	"RESOLUTION_ID" NUMBER, 
	"SPARE1" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
