--------------------------------------------------------
--  DDL for Table AQ$_QUEUE_TABLE_AFFINITIES
--------------------------------------------------------

  CREATE TABLE "SYS"."AQ$_QUEUE_TABLE_AFFINITIES" SHARING=METADATA 
   (	"TABLE_OBJNO" NUMBER, 
	"PRIMARY_INSTANCE" NUMBER, 
	"SECONDARY_INSTANCE" NUMBER, 
	"OWNER_INSTANCE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
