--------------------------------------------------------
--  DDL for Table AQ$_SUBSCRIBER_TABLE
--------------------------------------------------------

  CREATE TABLE "SYS"."AQ$_SUBSCRIBER_TABLE" SHARING=METADATA 
   (	"SCHEMA" VARCHAR2(128 BYTE), 
	"TABLE_NAME" VARCHAR2(128 BYTE), 
	"TABLE_OBJNO" NUMBER, 
	"QUEUE_ID" NUMBER, 
	"SUBSCRIBER_ID" NUMBER, 
	"QUEUE_NAME" VARCHAR2(128 BYTE), 
	"NAME" VARCHAR2(512 BYTE) DEFAULT NULL, 
	"ADDRESS" VARCHAR2(1024 BYTE) DEFAULT NULL, 
	"PROTOCOL" NUMBER, 
	"SUBSCRIBER_TYPE" NUMBER, 
	"RULE_NAME" VARCHAR2(128 BYTE), 
	"TRANS_NAME" VARCHAR2(261 BYTE), 
	"RULESET_NAME" VARCHAR2(261 BYTE), 
	"NEGATIVE_RULESET_NAME" VARCHAR2(261 BYTE), 
	"CREATION_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"MODIFICATION_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"DELETION_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"SCN_AT_REMOVE" NUMBER, 
	"SCN_AT_ADD" NUMBER, 
	"CLIENT_SESSION_GUID" VARCHAR2(36 BYTE), 
	"INSTANCE_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
