--------------------------------------------------------
--  DDL for Table AQ$_QUEUE_SHARDS
--------------------------------------------------------

  CREATE TABLE "SYS"."AQ$_QUEUE_SHARDS" SHARING=METADATA 
   (	"QUEUE" NUMBER, 
	"SHARD" NUMBER, 
	"ENQUEUE_INSTANCE" NUMBER, 
	"PREFERRED_OWNER_INSTANCE" NUMBER, 
	"OWNER_INSTANCE" NUMBER, 
	"FLAGS" NUMBER DEFAULT 0, 
	"BASE_QUEUE" NUMBER DEFAULT 0, 
	"DELAY_SHARD" NUMBER DEFAULT NULL
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
