--------------------------------------------------------
--  DDL for Table AQ$_PROPAGATION_STATUS
--------------------------------------------------------

  CREATE TABLE "SYS"."AQ$_PROPAGATION_STATUS" SHARING=METADATA 
   (	"QUEUE_ID" NUMBER, 
	"DESTINATION" VARCHAR2(128 BYTE), 
	"SEQUENCE" NUMBER, 
	"STATUS" NUMBER, 
	"TXNID" VARCHAR2(22 BYTE), 
	"DESTQUEUE_ID" NUMBER, 
	"FLAGS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
  GRANT SELECT ON "SYS"."AQ$_PROPAGATION_STATUS" TO "AQ_ADMINISTRATOR_ROLE";
