--------------------------------------------------------
--  DDL for Table AQ$_DEQUEUE_LOG_PARTITION_MAP
--------------------------------------------------------

  CREATE TABLE "SYS"."AQ$_DEQUEUE_LOG_PARTITION_MAP" SHARING=METADATA 
   (	"QUEUE" NUMBER, 
	"QUEUE_PART#" NUMBER, 
	"SUBSCRIBER_ID" NUMBER, 
	"INSTANCE" NUMBER DEFAULT 0, 
	"PARTITION#" NUMBER, 
	"PARTNAME" VARCHAR2(128 BYTE), 
	"ROWMARKER" NUMBER DEFAULT 0, 
	"SUBSHARD" NUMBER DEFAULT 0, 
	"UNBOUND_IDX" NUMBER DEFAULT -1, 
	"PART_PROPERTIES" NUMBER DEFAULT 0, 
	"MIN_SUB_DELV_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"MIN_SUB_DELV_TIME_SN" NUMBER DEFAULT NULL, 
	"MIN_DELV_TIME_ENQ_SCN" NUMBER DEFAULT NULL, 
	"MIN_SUB_DELV_TIME_DEQ_SCN" NUMBER DEFAULT NULL, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
