--------------------------------------------------------
--  DDL for Table AQ$_SHARD_MAP
--------------------------------------------------------

  CREATE TABLE "SYS"."AQ$_SHARD_MAP" SHARING=METADATA 
   (	"QUEUE_ID" NUMBER, 
	"SOURCE_Q_OWNER" VARCHAR2(128 BYTE), 
	"SOURCE_Q_NAME" VARCHAR2(128 BYTE), 
	"SOURCE_SHARD_ID" NUMBER, 
	"SOURCE_DB" VARCHAR2(128 BYTE), 
	"QUEUE_SCHEMA" VARCHAR2(128 BYTE), 
	"QUEUE_NAME" VARCHAR2(128 BYTE), 
	"SHARD_ID" NUMBER, 
	"INST_ID" NUMBER, 
	"REP_NAME" VARCHAR2(128 BYTE), 
	"STATUS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
