--------------------------------------------------------
--  DDL for Table AQ$_DURABLE_SUBS
--------------------------------------------------------

  CREATE TABLE "SYS"."AQ$_DURABLE_SUBS" SHARING=METADATA 
   (	"SCHEMA" VARCHAR2(128 BYTE), 
	"QUEUE_ID" NUMBER, 
	"QUEUE_NAME" VARCHAR2(128 BYTE), 
	"TABLE_OBJNO" NUMBER, 
	"SUBSCRIBER_ID" NUMBER, 
	"NAME" VARCHAR2(4000 BYTE) DEFAULT NULL, 
	"ADDRESS" VARCHAR2(1024 BYTE) DEFAULT NULL, 
	"PROTOCOL" NUMBER, 
	"SUBSCRIBER_TYPE" NUMBER, 
	"POS_BITMAP" NUMBER, 
	"RULE_NAME" VARCHAR2(128 BYTE), 
	"TRANS_OWNER" VARCHAR2(128 BYTE), 
	"TRANS_NAME" VARCHAR2(128 BYTE), 
	"CREATION_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"PARENT_ID" NUMBER DEFAULT NULL
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
