--------------------------------------------------------
--  DDL for Table AQ$_QUEUE_PARTITION_MAP
--------------------------------------------------------

  CREATE TABLE "SYS"."AQ$_QUEUE_PARTITION_MAP" SHARING=METADATA 
   (	"QUEUE" NUMBER, 
	"SHARD" NUMBER, 
	"PRIORITY" NUMBER, 
	"SUBSHARD" NUMBER, 
	"PARTITION#" NUMBER, 
	"PARTNAME" VARCHAR2(128 BYTE), 
	"MAP_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"INSTANCE" NUMBER DEFAULT 0, 
	"UNBOUND_IDX" NUMBER DEFAULT -1, 
	"PART_PROPERTIES" NUMBER DEFAULT 0, 
	"BUCKET_TIMESTAMP" TIMESTAMP (6) WITH TIME ZONE, 
	"BUCKET_WIDTH" NUMBER, 
	"BUCKET_ID" NUMBER, 
	"MIN_DELV_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"MIN_DELV_TIME_SN" NUMBER, 
	"MIN_DELV_TIME_SCN" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
