--------------------------------------------------------
--  DDL for Table AQ$_PUBLISHER
--------------------------------------------------------

  CREATE TABLE "SYS"."AQ$_PUBLISHER" SHARING=METADATA 
   (	"PUB_ID" NUMBER, 
	"QUEUE_ID" NUMBER, 
	"P_NAME" VARCHAR2(128 BYTE), 
	"P_ADDRESS" VARCHAR2(1024 BYTE), 
	"P_PROTOCOL" NUMBER, 
	"P_RULE_NAME" VARCHAR2(257 BYTE), 
	"P_RULE" VARCHAR2(2000 BYTE), 
	"P_RULESET" VARCHAR2(257 BYTE), 
	"P_TRANSFORMATION" VARCHAR2(257 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
