--------------------------------------------------------
--  DDL for Table AQ$_SCHEDULES
--------------------------------------------------------

  CREATE TABLE "SYS"."AQ$_SCHEDULES" SHARING=METADATA 
   (	"OID" RAW(16), 
	"DESTINATION" VARCHAR2(390 BYTE), 
	"START_TIME" DATE, 
	"DURATION" VARCHAR2(8 BYTE), 
	"NEXT_TIME" VARCHAR2(200 BYTE), 
	"LATENCY" VARCHAR2(8 BYTE), 
	"LAST_RUN" DATE, 
	"JOBNO" NUMBER, 
	"FAILURES" NUMBER, 
	"DISABLED" VARCHAR2(1 BYTE), 
	"ERROR_TIME" DATE, 
	"LAST_ERROR_MSG" VARCHAR2(4000 BYTE), 
	"CUR_START_TIME" DATE, 
	"NEXT_RUN" DATE, 
	"PROCESS_NAME" VARCHAR2(8 BYTE), 
	"SID" NUMBER, 
	"SERIAL" NUMBER, 
	"TOTAL_TIME" NUMBER, 
	"TOTAL_MSGS" NUMBER, 
	"TOTAL_BYTES" NUMBER, 
	"TOTAL_WINDOWS" NUMBER, 
	"WIN_MSGS" NUMBER, 
	"WIN_BYTES" NUMBER, 
	"MAX_NUM_PER_WIN" NUMBER, 
	"MAX_SIZE" NUMBER, 
	"INSTANCE" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" VARCHAR2(1024 BYTE), 
	"JOB_NAME" VARCHAR2(128 BYTE), 
	"DESTQ" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
