GRANT SELECT ON "SYS"."AQ$_UNFLUSHED_DEQUEUES" TO "AQ_ADMINISTRATOR_ROLE";
  GRANT SELECT ON "SYS"."AQ$_UNFLUSHED_DEQUEUES" TO "AQ_USER_ROLE";
  GRANT SELECT ON "SYS"."AQ$_UNFLUSHED_DEQUEUES" TO "GSMADMIN_INTERNAL";
  GRANT SELECT ON "SYS"."AQ$_UNFLUSHED_DEQUEUES" TO "WMSYS";
