REM INSERTING into SYS.AQ$_SUBSCRIBER_TABLE
SET DEFINE OFF;
Insert into SYS.AQ$_SUBSCRIBER_TABLE (SCHEMA,TABLE_NAME,TABLE_OBJNO,QUEUE_ID,SUBSCRIBER_ID,QUEUE_NAME,NAME,ADDRESS,PROTOCOL,SUBSCRIBER_TYPE,RULE_NAME,TRANS_NAME,RULESET_NAME,NEGATIVE_RULESET_NAME,CREATION_TIME,MODIFICATION_TIME,DELETION_TIME,SCN_AT_REMOVE,SCN_AT_ADD,CLIENT_SESSION_GUID,INSTANCE_ID) values ('0','0',0,0,0,'0',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
