--------------------------------------------------------
--  DDL for Table AQ$_MESSAGE_TYPES
--------------------------------------------------------

  CREATE TABLE "SYS"."AQ$_MESSAGE_TYPES" SHARING=METADATA 
   (	"QUEUE_OID" RAW(16), 
	"SCHEMA_NAME" VARCHAR2(128 BYTE), 
	"QUEUE_NAME" VARCHAR2(128 BYTE), 
	"TRANS_NAME" VARCHAR2(257 BYTE), 
	"DESTINATION" VARCHAR2(128 BYTE), 
	"TOID" RAW(16), 
	"VERSION" NUMBER, 
	"VERIFIED" VARCHAR2(1 BYTE), 
	"PROPERTIES" NUMBER, 
	"NETWORK_NAME" VARCHAR2(256 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
