REM INSERTING into SYS.AQ$_QUEUE_TABLE_AFFINITIES
SET DEFINE OFF;
Insert into SYS.AQ$_QUEUE_TABLE_AFFINITIES (TABLE_OBJNO,PRIMARY_INSTANCE,SECONDARY_INSTANCE,OWNER_INSTANCE) values (19643,0,0,1);
Insert into SYS.AQ$_QUEUE_TABLE_AFFINITIES (TABLE_OBJNO,PRIMARY_INSTANCE,SECONDARY_INSTANCE,OWNER_INSTANCE) values (19670,0,0,1);
Insert into SYS.AQ$_QUEUE_TABLE_AFFINITIES (TABLE_OBJNO,PRIMARY_INSTANCE,SECONDARY_INSTANCE,OWNER_INSTANCE) values (19704,0,0,1);
Insert into SYS.AQ$_QUEUE_TABLE_AFFINITIES (TABLE_OBJNO,PRIMARY_INSTANCE,SECONDARY_INSTANCE,OWNER_INSTANCE) values (19762,0,0,1);
Insert into SYS.AQ$_QUEUE_TABLE_AFFINITIES (TABLE_OBJNO,PRIMARY_INSTANCE,SECONDARY_INSTANCE,OWNER_INSTANCE) values (20063,0,0,1);
Insert into SYS.AQ$_QUEUE_TABLE_AFFINITIES (TABLE_OBJNO,PRIMARY_INSTANCE,SECONDARY_INSTANCE,OWNER_INSTANCE) values (20280,0,0,1);
Insert into SYS.AQ$_QUEUE_TABLE_AFFINITIES (TABLE_OBJNO,PRIMARY_INSTANCE,SECONDARY_INSTANCE,OWNER_INSTANCE) values (20306,0,0,1);
Insert into SYS.AQ$_QUEUE_TABLE_AFFINITIES (TABLE_OBJNO,PRIMARY_INSTANCE,SECONDARY_INSTANCE,OWNER_INSTANCE) values (20318,0,0,1);
Insert into SYS.AQ$_QUEUE_TABLE_AFFINITIES (TABLE_OBJNO,PRIMARY_INSTANCE,SECONDARY_INSTANCE,OWNER_INSTANCE) values (20351,0,0,1);
Insert into SYS.AQ$_QUEUE_TABLE_AFFINITIES (TABLE_OBJNO,PRIMARY_INSTANCE,SECONDARY_INSTANCE,OWNER_INSTANCE) values (20477,0,0,1);
Insert into SYS.AQ$_QUEUE_TABLE_AFFINITIES (TABLE_OBJNO,PRIMARY_INSTANCE,SECONDARY_INSTANCE,OWNER_INSTANCE) values (20640,0,0,1);
Insert into SYS.AQ$_QUEUE_TABLE_AFFINITIES (TABLE_OBJNO,PRIMARY_INSTANCE,SECONDARY_INSTANCE,OWNER_INSTANCE) values (20784,0,0,1);
Insert into SYS.AQ$_QUEUE_TABLE_AFFINITIES (TABLE_OBJNO,PRIMARY_INSTANCE,SECONDARY_INSTANCE,OWNER_INSTANCE) values (22515,0,0,1);
