--------------------------------------------------------
--  DDL for Table ARGUMENT$
--------------------------------------------------------

  CREATE TABLE "SYS"."ARGUMENT$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"PROCEDURE$" VARCHAR2(128 BYTE), 
	"OVERLOAD#" NUMBER, 
	"PROCEDURE#" NUMBER, 
	"POSITION#" NUMBER, 
	"SEQUENCE#" NUMBER, 
	"LEVEL#" NUMBER, 
	"ARGUMENT" VARCHAR2(128 BYTE), 
	"TYPE#" NUMBER, 
	"CHARSETID" NUMBER, 
	"CHARSETFORM" NUMBER, 
	"DEFAULT#" NUMBER, 
	"IN_OUT" NUMBER, 
	"PROPERTIES" NUMBER, 
	"LENGTH" NUMBER, 
	"PRECISION#" NUMBER, 
	"SCALE" NUMBER, 
	"RADIX" NUMBER, 
	"DEFLENGTH" NUMBER, 
	"DEFAULT$" LONG, 
	"TYPE_OWNER" VARCHAR2(128 BYTE), 
	"TYPE_NAME" VARCHAR2(128 BYTE), 
	"TYPE_SUBNAME" VARCHAR2(128 BYTE), 
	"TYPE_LINKNAME" VARCHAR2(128 BYTE), 
	"PLS_TYPE" VARCHAR2(128 BYTE), 
	"TYPE_TYPE#" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16384 NEXT 106496 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  GRANT SELECT ON "SYS"."ARGUMENT$" TO "CTXSYS";
