REM INSERTING into SYS.ASSOCIATION$
SET DEFINE OFF;
Insert into SYS.ASSOCIATION$ (OBJ#,PROPERTY,INTCOL#,STATSTYPE#,DEFAULT_SELECTIVITY,DEFAULT_CPU_COST,DEFAULT_IO_COST,DEFAULT_NET_COST,INTERFACE_VERSION#,SPARE2) values (21891,6,null,21881,null,null,null,null,2,1);
Insert into SYS.ASSOCIATION$ (OBJ#,PROPERTY,INTCOL#,STATSTYPE#,DEFAULT_SELECTIVITY,DEFAULT_CPU_COST,DEFAULT_IO_COST,DEFAULT_NET_COST,INTERFACE_VERSION#,SPARE2) values (21888,3,null,21881,null,null,null,null,2,0);
Insert into SYS.ASSOCIATION$ (OBJ#,PROPERTY,INTCOL#,STATSTYPE#,DEFAULT_SELECTIVITY,DEFAULT_CPU_COST,DEFAULT_IO_COST,DEFAULT_NET_COST,INTERFACE_VERSION#,SPARE2) values (21784,6,null,21905,null,null,null,null,2,0);
Insert into SYS.ASSOCIATION$ (OBJ#,PROPERTY,INTCOL#,STATSTYPE#,DEFAULT_SELECTIVITY,DEFAULT_CPU_COST,DEFAULT_IO_COST,DEFAULT_NET_COST,INTERFACE_VERSION#,SPARE2) values (21772,3,null,21905,null,null,null,null,2,0);
Insert into SYS.ASSOCIATION$ (OBJ#,PROPERTY,INTCOL#,STATSTYPE#,DEFAULT_SELECTIVITY,DEFAULT_CPU_COST,DEFAULT_IO_COST,DEFAULT_NET_COST,INTERFACE_VERSION#,SPARE2) values (62664,6,null,62478,null,null,null,null,2,0);
Insert into SYS.ASSOCIATION$ (OBJ#,PROPERTY,INTCOL#,STATSTYPE#,DEFAULT_SELECTIVITY,DEFAULT_CPU_COST,DEFAULT_IO_COST,DEFAULT_NET_COST,INTERFACE_VERSION#,SPARE2) values (62665,6,null,62478,null,null,null,null,2,1);
Insert into SYS.ASSOCIATION$ (OBJ#,PROPERTY,INTCOL#,STATSTYPE#,DEFAULT_SELECTIVITY,DEFAULT_CPU_COST,DEFAULT_IO_COST,DEFAULT_NET_COST,INTERFACE_VERSION#,SPARE2) values (62658,3,null,62478,null,null,null,null,2,0);
Insert into SYS.ASSOCIATION$ (OBJ#,PROPERTY,INTCOL#,STATSTYPE#,DEFAULT_SELECTIVITY,DEFAULT_CPU_COST,DEFAULT_IO_COST,DEFAULT_NET_COST,INTERFACE_VERSION#,SPARE2) values (62677,6,null,null,null,1,null,null,0,0);
Insert into SYS.ASSOCIATION$ (OBJ#,PROPERTY,INTCOL#,STATSTYPE#,DEFAULT_SELECTIVITY,DEFAULT_CPU_COST,DEFAULT_IO_COST,DEFAULT_NET_COST,INTERFACE_VERSION#,SPARE2) values (62671,3,null,null,null,1000,4294967295,null,0,0);
Insert into SYS.ASSOCIATION$ (OBJ#,PROPERTY,INTCOL#,STATSTYPE#,DEFAULT_SELECTIVITY,DEFAULT_CPU_COST,DEFAULT_IO_COST,DEFAULT_NET_COST,INTERFACE_VERSION#,SPARE2) values (62680,6,null,62478,null,null,null,null,2,0);
Insert into SYS.ASSOCIATION$ (OBJ#,PROPERTY,INTCOL#,STATSTYPE#,DEFAULT_SELECTIVITY,DEFAULT_CPU_COST,DEFAULT_IO_COST,DEFAULT_NET_COST,INTERFACE_VERSION#,SPARE2) values (62678,3,null,62478,null,null,null,null,2,0);
Insert into SYS.ASSOCIATION$ (OBJ#,PROPERTY,INTCOL#,STATSTYPE#,DEFAULT_SELECTIVITY,DEFAULT_CPU_COST,DEFAULT_IO_COST,DEFAULT_NET_COST,INTERFACE_VERSION#,SPARE2) values (64212,6,null,64270,null,null,null,null,2,0);
Insert into SYS.ASSOCIATION$ (OBJ#,PROPERTY,INTCOL#,STATSTYPE#,DEFAULT_SELECTIVITY,DEFAULT_CPU_COST,DEFAULT_IO_COST,DEFAULT_NET_COST,INTERFACE_VERSION#,SPARE2) values (64213,6,null,64270,null,null,null,null,2,1);
Insert into SYS.ASSOCIATION$ (OBJ#,PROPERTY,INTCOL#,STATSTYPE#,DEFAULT_SELECTIVITY,DEFAULT_CPU_COST,DEFAULT_IO_COST,DEFAULT_NET_COST,INTERFACE_VERSION#,SPARE2) values (64148,3,null,64270,null,null,null,null,2,0);
Insert into SYS.ASSOCIATION$ (OBJ#,PROPERTY,INTCOL#,STATSTYPE#,DEFAULT_SELECTIVITY,DEFAULT_CPU_COST,DEFAULT_IO_COST,DEFAULT_NET_COST,INTERFACE_VERSION#,SPARE2) values (64135,3,null,64270,null,null,null,null,2,0);
Insert into SYS.ASSOCIATION$ (OBJ#,PROPERTY,INTCOL#,STATSTYPE#,DEFAULT_SELECTIVITY,DEFAULT_CPU_COST,DEFAULT_IO_COST,DEFAULT_NET_COST,INTERFACE_VERSION#,SPARE2) values (70902,6,null,70743,null,null,null,null,2,0);
