--------------------------------------------------------
--  Constraints for Table ATSK$_SCHEDULE_CONTROL
--------------------------------------------------------

  ALTER TABLE "SYS"."ATSK$_SCHEDULE_CONTROL" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."ATSK$_SCHEDULE_CONTROL" MODIFY ("ATSKID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."ATSK$_SCHEDULE_CONTROL" ADD CONSTRAINT "ATSK$_SCHEDULE_CONTROL_PK" PRIMARY KEY ("DBID", "ATSKID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
