--------------------------------------------------------
--  DDL for Table ATSK$_SCHEDULE_CONTROL
--------------------------------------------------------

  CREATE TABLE "SYS"."ATSK$_SCHEDULE_CONTROL" SHARING=METADATA 
   (	"DBID" NUMBER, 
	"ATSKID" NUMBER, 
	"MRCT_TASK_TIME" NUMBER DEFAULT 0, 
	"INTERVAL" NUMBER DEFAULT 0, 
	"SUSPENDABLE_TIME" NUMBER DEFAULT 0, 
	"STATUS" NUMBER DEFAULT 0, 
	"NUM_FAILURE" NUMBER DEFAULT 0, 
	"MAX_RUN_TIME" NUMBER DEFAULT 0, 
	"ENABLE" NUMBER DEFAULT 0, 
	"LAST_EXEC_INSTNUM" NUMBER DEFAULT 0, 
	"MRCT_TASK_TIME_TZ" TIMESTAMP (3) WITH TIME ZONE, 
	"DURATION" NUMBER DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
