--------------------------------------------------------
--  DDL for Table ATTRIBUTE$
--------------------------------------------------------

  CREATE TABLE "SYS"."ATTRIBUTE$" SHARING=METADATA 
   (	"TOID" RAW(16), 
	"VERSION#" NUMBER, 
	"NAME" VARCHAR2(128 BYTE), 
	"ATTRIBUTE#" NUMBER, 
	"ATTR_TOID" RAW(16), 
	"ATTR_VERSION#" NUMBER, 
	"SYNOBJ#" NUMBER, 
	"PROPERTIES" NUMBER, 
	"CHARSETID" NUMBER, 
	"CHARSETFORM" NUMBER, 
	"LENGTH" NUMBER, 
	"PRECISION#" NUMBER, 
	"SCALE" NUMBER, 
	"EXTERNNAME" VARCHAR2(4000 BYTE), 
	"XFLAGS" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" NUMBER, 
	"SPARE5" NUMBER, 
	"SETTER" NUMBER, 
	"GETTER" NUMBER
   ) CLUSTER "SYS"."C_TOID_VERSION#" ("TOID", "VERSION#");
