REM INSERTING into SYS.ATTRIBUTE_TRANSFORMATIONS$
SET DEFINE OFF;
Insert into SYS.ATTRIBUTE_TRANSFORMATIONS$ (TRANSFORMATION_ID,ATTRIBUTE_NUMBER,SQL_EXPRESSION) values (1,0,'SYS.haen_txfm_text(source.user_data)');
Insert into SYS.ATTRIBUTE_TRANSFORMATIONS$ (TRANSFORMATION_ID,ATTRIBUTE_NUMBER,SQL_EXPRESSION) values (2,0,'source.user_data.payload');
Insert into SYS.ATTRIBUTE_TRANSFORMATIONS$ (TRANSFORMATION_ID,ATTRIBUTE_NUMBER,SQL_EXPRESSION) values (3,0,'source.user_data');
