--------------------------------------------------------
--  Constraints for Table ATTRIBUTE$
--------------------------------------------------------

  ALTER TABLE "SYS"."ATTRIBUTE$" MODIFY ("TOID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."ATTRIBUTE$" MODIFY ("VERSION#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."ATTRIBUTE$" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."ATTRIBUTE$" MODIFY ("ATTRIBUTE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."ATTRIBUTE$" MODIFY ("ATTR_TOID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."ATTRIBUTE$" MODIFY ("ATTR_VERSION#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."ATTRIBUTE$" MODIFY ("PROPERTIES" NOT NULL ENABLE);
