--------------------------------------------------------
--  DDL for Table ATTRIBUTE_TRANSFORMATIONS$
--------------------------------------------------------

  CREATE TABLE "SYS"."ATTRIBUTE_TRANSFORMATIONS$" SHARING=METADATA 
   (	"TRANSFORMATION_ID" NUMBER, 
	"ATTRIBUTE_NUMBER" NUMBER, 
	"SQL_EXPRESSION" VARCHAR2(4000 BYTE), 
	"XSL_TRANSFORMATION" CLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("XSL_TRANSFORMATION") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
