--------------------------------------------------------
--  DDL for Table AUD$
--------------------------------------------------------

  CREATE TABLE "SYS"."AUD$" SHARING=METADATA 
   (	"SESSIONID" NUMBER, 
	"ENTRYID" NUMBER, 
	"STATEMENT" NUMBER, 
	"TIMESTAMP#" DATE, 
	"USERID" VARCHAR2(128 BYTE), 
	"USERHOST" VARCHAR2(128 BYTE), 
	"TERMINAL" VARCHAR2(255 BYTE), 
	"ACTION#" NUMBER, 
	"RETURNCODE" NUMBER, 
	"OBJ$CREATOR" VARCHAR2(128 BYTE), 
	"OBJ$NAME" VARCHAR2(128 BYTE), 
	"AUTH$PRIVILEGES" VARCHAR2(32 BYTE), 
	"AUTH$GRANTEE" VARCHAR2(128 BYTE), 
	"NEW$OWNER" VARCHAR2(128 BYTE), 
	"NEW$NAME" VARCHAR2(128 BYTE), 
	"SES$ACTIONS" VARCHAR2(19 BYTE), 
	"SES$TID" NUMBER, 
	"LOGOFF$LREAD" NUMBER, 
	"LOGOFF$PREAD" NUMBER, 
	"LOGOFF$LWRITE" NUMBER, 
	"LOGOFF$DEAD" NUMBER, 
	"LOGOFF$TIME" DATE, 
	"COMMENT$TEXT" VARCHAR2(4000 BYTE), 
	"CLIENTID" VARCHAR2(128 BYTE), 
	"SPARE1" VARCHAR2(255 BYTE), 
	"SPARE2" NUMBER, 
	"OBJ$LABEL" RAW(255), 
	"SES$LABEL" RAW(255), 
	"PRIV$USED" NUMBER, 
	"SESSIONCPU" NUMBER, 
	"NTIMESTAMP#" TIMESTAMP (6), 
	"PROXY$SID" NUMBER, 
	"USER$GUID" VARCHAR2(32 BYTE), 
	"INSTANCE#" NUMBER, 
	"PROCESS#" VARCHAR2(16 BYTE), 
	"XID" RAW(8), 
	"AUDITID" VARCHAR2(64 BYTE), 
	"SCN" NUMBER, 
	"DBID" NUMBER, 
	"SQLBIND" CLOB, 
	"SQLTEXT" CLOB, 
	"OBJ$EDITION" VARCHAR2(128 BYTE), 
	"RLS$INFO" CLOB, 
	"CURRENT_USER" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("SQLBIND") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("SQLTEXT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("RLS$INFO") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
