--------------------------------------------------------
--  DDL for Table AUD_POLICY$
--------------------------------------------------------

  CREATE TABLE "SYS"."AUD_POLICY$" SHARING=METADATA 
   (	"POLICY#" NUMBER, 
	"TYPE" NUMBER, 
	"SYSPRIV" VARCHAR2(2000 BYTE), 
	"SYSACTN" VARCHAR2(2000 BYTE), 
	"CONDITION" VARCHAR2(4000 BYTE), 
	"CONDITION_EVAL" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
