--------------------------------------------------------
--  DDL for Table AUD_OBJECT_OPT$
--------------------------------------------------------

  CREATE TABLE "SYS"."AUD_OBJECT_OPT$" SHARING=METADATA 
   (	"OBJECT#" NUMBER, 
	"POLICY#" NUMBER, 
	"ACTION#" VARCHAR2(100 BYTE), 
	"TYPE" NUMBER, 
	"COMP_INFO" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
