--------------------------------------------------------
--  DDL for Table AUDTAB$TBS$FOR_EXPORT_TBL
--------------------------------------------------------

  CREATE TABLE "SYS"."AUDTAB$TBS$FOR_EXPORT_TBL" SHARING=METADATA 
   (	"OWNER" VARCHAR2(128 BYTE), 
	"NAME" VARCHAR2(128 BYTE), 
	"TS_NAME" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
  GRANT SELECT ON "SYS"."AUDTAB$TBS$FOR_EXPORT_TBL" TO "SELECT_CATALOG_ROLE";
