--------------------------------------------------------
--  DDL for Table AUX_STATS$
--------------------------------------------------------

  CREATE TABLE "SYS"."AUX_STATS$" SHARING=METADATA 
   (	"SNAME" VARCHAR2(30 BYTE), 
	"PNAME" VARCHAR2(30 BYTE), 
	"PVAL1" NUMBER, 
	"PVAL2" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  GRANT DELETE ON "SYS"."AUX_STATS$" TO "GATHER_SYSTEM_STATISTICS";
  GRANT INSERT ON "SYS"."AUX_STATS$" TO "GATHER_SYSTEM_STATISTICS";
  GRANT SELECT ON "SYS"."AUX_STATS$" TO "GATHER_SYSTEM_STATISTICS";
  GRANT UPDATE ON "SYS"."AUX_STATS$" TO "GATHER_SYSTEM_STATISTICS";
