REM INSERTING into SYS.AUX_STATS$
SET DEFINE OFF;
Insert into SYS.AUX_STATS$ (SNAME,PNAME,PVAL1,PVAL2) values ('SYSSTATS_INFO','STATUS',null,'COMPLETED');
Insert into SYS.AUX_STATS$ (SNAME,PNAME,PVAL1,PVAL2) values ('SYSSTATS_INFO','DSTART',null,'05-30-2019 05:21');
Insert into SYS.AUX_STATS$ (SNAME,PNAME,PVAL1,PVAL2) values ('SYSSTATS_INFO','DSTOP',null,'05-30-2019 05:21');
Insert into SYS.AUX_STATS$ (SNAME,PNAME,PVAL1,PVAL2) values ('SYSSTATS_INFO','FLAGS',1,null);
Insert into SYS.AUX_STATS$ (SNAME,PNAME,PVAL1,PVAL2) values ('SYSSTATS_MAIN','CPUSPEEDNW',1111.75485688468,null);
Insert into SYS.AUX_STATS$ (SNAME,PNAME,PVAL1,PVAL2) values ('SYSSTATS_MAIN','IOSEEKTIM',10,null);
Insert into SYS.AUX_STATS$ (SNAME,PNAME,PVAL1,PVAL2) values ('SYSSTATS_MAIN','IOTFRSPEED',4096,null);
Insert into SYS.AUX_STATS$ (SNAME,PNAME,PVAL1,PVAL2) values ('SYSSTATS_MAIN','SREADTIM',null,null);
Insert into SYS.AUX_STATS$ (SNAME,PNAME,PVAL1,PVAL2) values ('SYSSTATS_MAIN','MREADTIM',null,null);
Insert into SYS.AUX_STATS$ (SNAME,PNAME,PVAL1,PVAL2) values ('SYSSTATS_MAIN','CPUSPEED',null,null);
Insert into SYS.AUX_STATS$ (SNAME,PNAME,PVAL1,PVAL2) values ('SYSSTATS_MAIN','MBRC',null,null);
Insert into SYS.AUX_STATS$ (SNAME,PNAME,PVAL1,PVAL2) values ('SYSSTATS_MAIN','MAXTHR',null,null);
Insert into SYS.AUX_STATS$ (SNAME,PNAME,PVAL1,PVAL2) values ('SYSSTATS_MAIN','SLAVETHR',null,null);
