--------------------------------------------------------
--  DDL for Table AW$
--------------------------------------------------------

  CREATE TABLE "SYS"."AW$" SHARING=METADATA 
   (	"AWNAME" VARCHAR2(128 BYTE), 
	"OWNER#" NUMBER, 
	"AWSEQ#" NUMBER, 
	"VERSION" NUMBER DEFAULT null, 
	"OIDS" NUMBER(10,0) DEFAULT null, 
	"OBJS" NUMBER(10,0) DEFAULT null, 
	"DICT" RAW(8) DEFAULT null, 
	"RSYGEN" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
