--------------------------------------------------------
--  DDL for Table AW$AWCREATE
--------------------------------------------------------

  CREATE TABLE "SYS"."AW$AWCREATE" SHARING=METADATA 
   (	"PS#" NUMBER(15,0), 
	"GEN#" NUMBER(10,0), 
	"EXTNUM" NUMBER(8,0), 
	"AWLOB" BLOB, 
	"OBJNAME" VARCHAR2(512 BYTE), 
	"PARTNAME" VARCHAR2(512 BYTE)
   ) USAGE AW PCTFREE 10 PCTUSED 40 INITRANS 4 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 LOB ("AWLOB") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" DISABLE STORAGE IN ROW CHUNK 8192 RETENTION MIN 1
  CACHE  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  GRANT READ ON "SYS"."AW$AWCREATE" TO PUBLIC;
