--------------------------------------------------------
--  DDL for Table AW_PRG$
--------------------------------------------------------

  CREATE TABLE "SYS"."AW_PRG$" SHARING=METADATA 
   (	"AWSEQ#" NUMBER, 
	"OID" NUMBER(20,0), 
	"GEN#" NUMBER(10,0), 
	"STM#" NUMBER, 
	"STMTEXT" BLOB, 
	"COMPCODE" BLOB, 
	"FLAGS" NUMBER, 
	"SPARE" BLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" 
 LOB ("STMTEXT") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("COMPCODE") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("SPARE") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
