--------------------------------------------------------
--  DDL for Table AW_PROP$
--------------------------------------------------------

  CREATE TABLE "SYS"."AW_PROP$" SHARING=METADATA 
   (	"AWSEQ#" NUMBER, 
	"OID" NUMBER(20,0), 
	"OBJNAME" VARCHAR2(512 BYTE), 
	"GEN#" NUMBER(10,0), 
	"PROPNAME" VARCHAR2(256 BYTE), 
	"PROPTYPE" NUMBER, 
	"PROPVAL" BLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 4 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" 
 LOB ("PROPVAL") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
