--------------------------------------------------------
--  DDL for Index AWMD_I$
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."AWMD_I$" ON "SYS"."AW$AWMD" ("PS#", "GEN#", "EXTNUM") 
  PCTFREE 10 INITRANS 4 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
