--------------------------------------------------------
--  DDL for Table BDSQL_USER_MAP
--------------------------------------------------------

  CREATE TABLE "SYS"."BDSQL_USER_MAP" SHARING=METADATA 
   (	"CLUSTER_NAME" VARCHAR2(128 BYTE), 
	"CURRENT_DATABASE_USER" VARCHAR2(128 BYTE), 
	"SYSCONTEXT_NAMESPACE" VARCHAR2(128 BYTE), 
	"SYSCONTEXT_PARM_HADOOP_USER" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
  GRANT DELETE ON "SYS"."BDSQL_USER_MAP" TO "BDSQL_ADMIN";
  GRANT INSERT ON "SYS"."BDSQL_USER_MAP" TO "BDSQL_ADMIN";
  GRANT SELECT ON "SYS"."BDSQL_USER_MAP" TO "BDSQL_ADMIN";
  GRANT READ ON "SYS"."BDSQL_USER_MAP" TO "BDSQL_USER";
