--------------------------------------------------------
--  DDL for Table CACHE_STATS_0$
--------------------------------------------------------

  CREATE TABLE "SYS"."CACHE_STATS_0$" SHARING=METADATA 
   (	"DATAOBJ#" NUMBER, 
	"INST_ID" NUMBER, 
	"CACHED_AVG" NUMBER, 
	"CACHED_SQR_AVG" NUMBER, 
	"CACHED_NO" NUMBER(*,0), 
	"CACHED_SEQ_NO" NUMBER(*,0), 
	"CHR_AVG" NUMBER, 
	"CHR_SQR_AVG" NUMBER, 
	"CHR_NO" NUMBER(*,0), 
	"CHR_SEQ_NO" NUMBER(*,0), 
	"LGR_SUM" NUMBER, 
	"LGR_LAST" NUMBER, 
	"PHR_LAST" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" NUMBER, 
	"SPARE5" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( MAXEXTENTS 2147483645)
  TABLESPACE "SYSTEM" ;
