--------------------------------------------------------
--  DDL for Table CAPTURED_PRIV$
--------------------------------------------------------

  CREATE TABLE "SYS"."CAPTURED_PRIV$" SHARING=METADATA 
   (	"ID#" NUMBER, 
	"OS_USER" VARCHAR2(128 BYTE), 
	"HOST" VARCHAR2(128 BYTE), 
	"MODULE" VARCHAR2(64 BYTE), 
	"CAPTURE" NUMBER, 
	"RUN_SEQ#" NUMBER, 
	"USER#" NUMBER, 
	"LOG_USER#" NUMBER DEFAULT NULL, 
	"ROLE#" NUMBER DEFAULT NULL, 
	"SYSPRIV#" NUMBER DEFAULT NULL, 
	"OBJPRIV#" NUMBER DEFAULT NULL, 
	"USERPRIV#" NUMBER DEFAULT NULL, 
	"OBJ#" NUMBER DEFAULT NULL, 
	"COL#" NUMBER DEFAULT NULL, 
	"OPTION$" NUMBER DEFAULT NULL, 
	"E_ROLES" "SYS"."ROLE_ARRAY" , 
	"APP_ROLES" "SYS"."ROLE_ARRAY" , 
	"CBAC_PLIST" "SYS"."PACKAGE_ARRAY" 
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" 
 VARRAY "CBAC_PLIST" STORE AS SECUREFILE LOB 
  ( TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES ) ;
