--------------------------------------------------------
--  DDL for Table CAPTURE_RUN_LOG$
--------------------------------------------------------

  CREATE TABLE "SYS"."CAPTURE_RUN_LOG$" SHARING=METADATA 
   (	"CAPTURE" NUMBER, 
	"RUN_SEQ#" NUMBER DEFAULT 0, 
	"START_TIME" TIMESTAMP (6) DEFAULT NULL, 
	"END_TIME" TIMESTAMP (6) DEFAULT NULL, 
	"SYSPRIV_GRANT#" NUMBER, 
	"OBJPRIV_GRANT#" NUMBER, 
	"RUN_NAME" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT SELECT ON "SYS"."CAPTURE_RUN_LOG$" TO "CAPTURE_ADMIN";
