--------------------------------------------------------
--  Constraints for Table CDB_LOCAL_ADMINAUTH$
--------------------------------------------------------

  ALTER TABLE "SYS"."CDB_LOCAL_ADMINAUTH$" MODIFY ("CON_UID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CDB_LOCAL_ADMINAUTH$" MODIFY ("GRANTEE$" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CDB_LOCAL_ADMINAUTH$" MODIFY ("PRIVILEGES" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CDB_LOCAL_ADMINAUTH$" MODIFY ("PASSWD" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CDB_LOCAL_ADMINAUTH$" MODIFY ("FLAGS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CDB_LOCAL_ADMINAUTH$" MODIFY ("FED_PRIVILEGES" NOT NULL ENABLE);
