--------------------------------------------------------
--  DDL for Table CDB_FILE$
--------------------------------------------------------

  CREATE TABLE "SYS"."CDB_FILE$" SHARING=METADATA 
   (	"FILE#" NUMBER, 
	"CON_ID#" NUMBER, 
	"MTIME" DATE, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" NUMBER, 
	"F_AFN" NUMBER, 
	"F_DBID" NUMBER, 
	"F_CPSWRP" NUMBER, 
	"F_CPSBAS" NUMBER, 
	"F_PRLSWRP" NUMBER, 
	"F_PRLSBAS" NUMBER, 
	"F_PRLSTIM" NUMBER, 
	"TS#" NUMBER, 
	"RELFILE#" NUMBER, 
	"CSCNWRP" NUMBER, 
	"CSCNBAS" NUMBER, 
	"SPARE5" VARCHAR2(1000 BYTE), 
	"SPARE6" DATE, 
	"SRC_AFN" NUMBER, 
	"TGT_AFN" NUMBER, 
	"STATUS" NUMBER, 
	"FLAGS" NUMBER, 
	"BLKS" NUMBER, 
	"SPARE7" NUMBER, 
	"SPARE8" NUMBER, 
	"SPARE9" NUMBER, 
	"SPARE10" NUMBER, 
	"SPARE11" VARCHAR2(128 BYTE), 
	"SPARE12" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
