--------------------------------------------------------
--  Constraints for Table CDB_FILE$
--------------------------------------------------------

  ALTER TABLE "SYS"."CDB_FILE$" MODIFY ("FILE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CDB_FILE$" MODIFY ("CON_ID#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CDB_FILE$" MODIFY ("F_AFN" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CDB_FILE$" MODIFY ("F_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CDB_FILE$" MODIFY ("F_CPSWRP" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CDB_FILE$" MODIFY ("F_CPSBAS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CDB_FILE$" MODIFY ("F_PRLSWRP" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CDB_FILE$" MODIFY ("F_PRLSBAS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CDB_FILE$" MODIFY ("F_PRLSTIM" NOT NULL ENABLE);
