--------------------------------------------------------
--  DDL for Table CDB_SERVICE$
--------------------------------------------------------

  CREATE TABLE "SYS"."CDB_SERVICE$" SHARING=METADATA 
   (	"NAME" VARCHAR2(64 BYTE), 
	"NETWORK_NAME" VARCHAR2(512 BYTE), 
	"CON_ID#" NUMBER, 
	"NAME_HASH" NUMBER, 
	"FLAGS" NUMBER, 
	"SPAREN1" NUMBER, 
	"SPAREN2" NUMBER, 
	"SPAREVC1" VARCHAR2(4000 BYTE), 
	"SPAREVC2" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
  GRANT SELECT ON "SYS"."CDB_SERVICE$" TO "DBSFWUSER";
  GRANT SELECT ON "SYS"."CDB_SERVICE$" TO "SYSRAC";
