--------------------------------------------------------
--  Constraints for Table CDB_TS$
--------------------------------------------------------

  ALTER TABLE "SYS"."CDB_TS$" MODIFY ("TS#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CDB_TS$" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CDB_TS$" MODIFY ("CON_ID#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CDB_TS$" MODIFY ("STATUS$" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CDB_TS$" MODIFY ("CSCNWRP" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CDB_TS$" MODIFY ("CSCNBAS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CDB_TS$" MODIFY ("FILECNT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CDB_TS$" MODIFY ("FLAGS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CDB_TS$" MODIFY ("PTYPE" NOT NULL ENABLE);
