--------------------------------------------------------
--  DDL for Table CDB_LOCAL_ADMINAUTH$
--------------------------------------------------------

  CREATE TABLE "SYS"."CDB_LOCAL_ADMINAUTH$" SHARING=METADATA 
   (	"CON_UID" NUMBER, 
	"GRANTEE$" VARCHAR2(128 BYTE), 
	"PRIVILEGES" NUMBER DEFAULT 0, 
	"PASSWD" VARCHAR2(4000 BYTE), 
	"FLAGS" NUMBER DEFAULT 0, 
	"SPARE1" NUMBER, 
	"SPARE2" VARCHAR2(128 BYTE), 
	"LCOUNT" NUMBER DEFAULT 0, 
	"ASTATUS" NUMBER DEFAULT 0, 
	"EXPTIME" DATE, 
	"LTIME" DATE, 
	"LSLTIME" DATE, 
	"PASSWD_PROFILE" VARCHAR2(128 BYTE), 
	"PASSWD_LIMIT" VARCHAR2(4000 BYTE), 
	"FED_PRIVILEGES" NUMBER DEFAULT 0, 
	"EXT_USERNAME" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
