REM INSERTING into SYS.CDB_RESOURCE_PLAN$
SET DEFINE OFF;
Insert into SYS.CDB_RESOURCE_PLAN$ (OBJ#,NAME,DESCRIPTION,STATUS,MANDATORY) values (19598,'DEFAULT_CDB_PLAN','Default CDB plan','ACTIVE',1);
Insert into SYS.CDB_RESOURCE_PLAN$ (OBJ#,NAME,DESCRIPTION,STATUS,MANDATORY) values (19599,'DEFAULT_MAINTENANCE_PLAN','Default CDB maintenance plan','ACTIVE',1);
Insert into SYS.CDB_RESOURCE_PLAN$ (OBJ#,NAME,DESCRIPTION,STATUS,MANDATORY) values (19600,'ORA$INTERNAL_CDB_PLAN','Internal CDB plan','ACTIVE',1);
Insert into SYS.CDB_RESOURCE_PLAN$ (OBJ#,NAME,DESCRIPTION,STATUS,MANDATORY) values (19601,'ORA$QOS_CDB_PLAN','QOS CDB plan','ACTIVE',1);
