--------------------------------------------------------
--  DDL for Table CHNF$_QUERIES
--------------------------------------------------------

  CREATE TABLE "SYS"."CHNF$_QUERIES" SHARING=METADATA 
   (	"QUERYID" NUMBER, 
	"QUERYFLAGS" NUMBER, 
	"SELECTLIST" CLOB, 
	"FROMLIST" RAW(100), 
	"WHERECLAUSE" CLOB, 
	"HASHVAL" RAW(20), 
	"SCN" NUMBER, 
	"USERID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("SELECTLIST") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("WHERECLAUSE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
