--------------------------------------------------------
--  DDL for Table CHNF$_QUERY_OBJECT
--------------------------------------------------------

  CREATE TABLE "SYS"."CHNF$_QUERY_OBJECT" SHARING=METADATA 
   (	"QUERYID" NUMBER, 
	"OBJN" NUMBER, 
	"FLAGS" NUMBER, 
	"VIRTUALCLAUSE" CLOB, 
	"SOURCE_QUERY_SEL" CLOB, 
	"SOURCE_QUERY_FROPOS" RAW(64), 
	"SOURCE_QUERY_WHR" CLOB, 
	"REFCOLS" RAW(32), 
	"POSITION" NUMBER, 
	"TOPCLAUSEID" NUMBER, 
	"JOINCLAUSEID" NUMBER, 
	"MAXDEPTH" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("VIRTUALCLAUSE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("SOURCE_QUERY_SEL") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("SOURCE_QUERY_WHR") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
