--------------------------------------------------------
--  DDL for Table CHNF$_GROUP_FILTER_IOT
--------------------------------------------------------

  CREATE TABLE "SYS"."CHNF$_GROUP_FILTER_IOT" SHARING=METADATA 
   (	"OBJECTNUM" NUMBER, 
	"EXPRFILTER" CHAR(1 BYTE), 
	"EXPRLHS" CLOB, 
	"COLID" NUMBER, 
	"OPERATOR" NUMBER, 
	"RHSVAL" RAW(500), 
	"FILTERID" NUMBER, 
	 PRIMARY KEY ("OBJECTNUM", "COLID", "OPERATOR", "RHSVAL") ENABLE
   ) ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 PCTTHRESHOLD 50 OVERFLOW
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
  TABLESPACE "SYSAUX" 
 LOB ("EXPRLHS") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
