--------------------------------------------------------
--  Constraints for Table CHNFDIRECTLOAD$
--------------------------------------------------------

  ALTER TABLE "SYS"."CHNFDIRECTLOAD$" MODIFY ("TABLEOBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CHNFDIRECTLOAD$" MODIFY ("PARTITIONOBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CHNFDIRECTLOAD$" MODIFY ("SCN" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CHNFDIRECTLOAD$" MODIFY ("LOWROWID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CHNFDIRECTLOAD$" MODIFY ("HIGHROWID" NOT NULL ENABLE);
