--------------------------------------------------------
--  DDL for Table CHNFDIRECTLOAD$
--------------------------------------------------------

  CREATE TABLE "SYS"."CHNFDIRECTLOAD$" SHARING=METADATA 
   (	"TABLEOBJ#" NUMBER, 
	"PARTITIONOBJ#" NUMBER, 
	"DMLOPERATION" NUMBER, 
	"SCN" NUMBER, 
	"LOWROWID" VARCHAR2(20 BYTE), 
	"HIGHROWID" VARCHAR2(20 BYTE), 
	"XID" RAW(8), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
