--------------------------------------------------------
--  DDL for Table CHNF$_CLAUSES
--------------------------------------------------------

  CREATE TABLE "SYS"."CHNF$_CLAUSES" SHARING=METADATA 
   (	"CLAUSEID" NUMBER, 
	"OBJECTNUM" NUMBER, 
	"CHILDLIST" CLOB, 
	"CLAUSEOP" NUMBER, 
	"LHS" CLOB, 
	"PREDICATEOP" NUMBER, 
	"RHSVAL" CLOB, 
	"RHSTYPE" NUMBER, 
	"CLAUSEFLAGS" NUMBER, 
	"GLOBAL_REFCOUNT" NUMBER, 
	"HASHVAL" RAW(20), 
	 PRIMARY KEY ("CLAUSEID") ENABLE
   ) ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 PCTTHRESHOLD 50 OVERFLOW
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
  TABLESPACE "SYSAUX" 
 LOB ("CHILDLIST") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("LHS") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("RHSVAL") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
