--------------------------------------------------------
--  Constraints for Table CLU$
--------------------------------------------------------

  ALTER TABLE "SYS"."CLU$" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CLU$" MODIFY ("TS#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CLU$" MODIFY ("FILE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CLU$" MODIFY ("BLOCK#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CLU$" MODIFY ("COLS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CLU$" MODIFY ("PCTFREE$" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CLU$" MODIFY ("PCTUSED$" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CLU$" MODIFY ("INITRANS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CLU$" MODIFY ("MAXTRANS" NOT NULL ENABLE);
