--------------------------------------------------------
--  DDL for Table CLUSTER_INSTANCES
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "SYS"."CLUSTER_INSTANCES" SHARING=METADATA 
   (	"INSTANCE_NUMBER" NUMBER, 
	"DATABASE_NAME" VARCHAR2(128 BYTE), 
	"INST_NAME" VARCHAR2(4000 BYTE), 
	"NODE_NAME" VARCHAR2(4000 BYTE), 
	"SPAREN1" NUMBER, 
	"SPAREN2" NUMBER, 
	"SPAREVC1" VARCHAR2(4000 BYTE), 
	"SPAREVC2" VARCHAR2(4000 BYTE)
   ) ON COMMIT PRESERVE ROWS ;
