REM INSERTING into SYS.CODEAUTH$
SET DEFINE OFF;
Insert into SYS.CODEAUTH$ (OBJ#,PRIVILEGE#) values (13953,39);
Insert into SYS.CODEAUTH$ (OBJ#,PRIVILEGE#) values (22248,27);
Insert into SYS.CODEAUTH$ (OBJ#,PRIVILEGE#) values (22248,28);
