--------------------------------------------------------
--  DDL for Table COL$
--------------------------------------------------------

  CREATE TABLE "SYS"."COL$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"COL#" NUMBER, 
	"SEGCOL#" NUMBER, 
	"SEGCOLLENGTH" NUMBER, 
	"OFFSET" NUMBER, 
	"NAME" VARCHAR2(128 BYTE), 
	"TYPE#" NUMBER, 
	"LENGTH" NUMBER, 
	"FIXEDSTORAGE" NUMBER, 
	"PRECISION#" NUMBER, 
	"SCALE" NUMBER, 
	"NULL$" NUMBER, 
	"DEFLENGTH" NUMBER, 
	"DEFAULT$" LONG, 
	"INTCOL#" NUMBER, 
	"PROPERTY" NUMBER, 
	"CHARSETID" NUMBER, 
	"CHARSETFORM" NUMBER, 
	"EVALEDITION#" NUMBER, 
	"UNUSABLEBEFORE#" NUMBER, 
	"UNUSABLEBEGINNING#" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" VARCHAR2(1000 BYTE), 
	"SPARE5" VARCHAR2(1000 BYTE), 
	"SPARE6" DATE, 
	"SPARE7" NUMBER, 
	"SPARE8" NUMBER, 
	"COLLID" NUMBER, 
	"COLLINTCOL#" NUMBER, 
	"SPARE9" NUMBER, 
	"SPARE10" NUMBER, 
	"SPARE11" VARCHAR2(1000 BYTE), 
	"SPARE12" VARCHAR2(1000 BYTE), 
	"SPARE13" TIMESTAMP (6), 
	"ACDRRESCOL#" NUMBER
   ) CLUSTER "SYS"."C_OBJ#" ("OBJ#");
  GRANT SELECT ON "SYS"."COL$" TO "GSMADMIN_INTERNAL";
  GRANT SELECT ON "SYS"."COL$" TO "XDB";
  GRANT SELECT ON "SYS"."COL$" TO "CTXSYS";
  GRANT SELECT ON "SYS"."COL$" TO "LBACSYS";
