--------------------------------------------------------
--  Constraints for Table COL$
--------------------------------------------------------

  ALTER TABLE "SYS"."COL$" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."COL$" MODIFY ("COL#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."COL$" MODIFY ("SEGCOL#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."COL$" MODIFY ("SEGCOLLENGTH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."COL$" MODIFY ("OFFSET" NOT NULL ENABLE);
  ALTER TABLE "SYS"."COL$" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."COL$" MODIFY ("TYPE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."COL$" MODIFY ("LENGTH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."COL$" MODIFY ("FIXEDSTORAGE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."COL$" MODIFY ("NULL$" NOT NULL ENABLE);
  ALTER TABLE "SYS"."COL$" MODIFY ("INTCOL#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."COL$" MODIFY ("PROPERTY" NOT NULL ENABLE);
