--------------------------------------------------------
--  Constraints for Table COLLECTION$
--------------------------------------------------------

  ALTER TABLE "SYS"."COLLECTION$" MODIFY ("TOID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."COLLECTION$" MODIFY ("VERSION#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."COLLECTION$" MODIFY ("COLL_TOID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."COLLECTION$" MODIFY ("COLL_VERSION#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."COLLECTION$" MODIFY ("ELEM_TOID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."COLLECTION$" MODIFY ("ELEM_VERSION#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."COLLECTION$" MODIFY ("PROPERTIES" NOT NULL ENABLE);
