--------------------------------------------------------
--  DDL for Table COMPARISON_SCAN$
--------------------------------------------------------

  CREATE TABLE "SYS"."COMPARISON_SCAN$" SHARING=METADATA 
   (	"COMPARISON_ID" NUMBER, 
	"SCAN_ID" NUMBER, 
	"PARENT_SCAN_ID" NUMBER, 
	"NUM_ROWS" NUMBER, 
	"STATUS" NUMBER, 
	"FLAGS" NUMBER, 
	"LAST_UPDATE_TIME" TIMESTAMP (6), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" VARCHAR2(1000 BYTE), 
	"SPARE5" NUMBER, 
	"SPARE6" NUMBER, 
	"SPARE7" NUMBER, 
	"SPARE8" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
