--------------------------------------------------------
--  DDL for Table COMPRESSION_STAT$
--------------------------------------------------------

  CREATE TABLE "SYS"."COMPRESSION_STAT$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"DATAOBJ#" NUMBER, 
	"AVGROWSIZE_NC" NUMBER(*,2), 
	"AVGROWSIZE_C" NUMBER(*,2), 
	"TS#" NUMBER, 
	"FILE#" NUMBER, 
	"BLOCK#" NUMBER, 
	"NBLK_NC" NUMBER, 
	"NBLK_ADVANCED" NUMBER, 
	"NBLK_EHCC" NUMBER, 
	"NBLK_UAHCC" NUMBER, 
	"NROWS_NC" NUMBER, 
	"NROWS_ADVANCED" NUMBER, 
	"NROWS_EHCC" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
