--------------------------------------------------------
--  DDL for Table COMPRESSION$
--------------------------------------------------------

  CREATE TABLE "SYS"."COMPRESSION$" SHARING=METADATA 
   (	"TS#" NUMBER, 
	"FILE#" NUMBER, 
	"BLOCK#" NUMBER, 
	"OBJ#" NUMBER, 
	"DATAOBJ#" NUMBER, 
	"ULEVEL" NUMBER, 
	"SUBLEVEL" NUMBER, 
	"ILEVEL" NUMBER, 
	"FLAGS" NUMBER, 
	"BESTSORTCOL" NUMBER, 
	"TINSIZE" NUMBER, 
	"CTINSIZE" NUMBER, 
	"TOUTSIZE" NUMBER, 
	"CMPSIZE" NUMBER, 
	"UNCMPSIZE" NUMBER, 
	"MTIME" DATE, 
	"ANALYZER" BLOB, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("ANALYZER") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
