--------------------------------------------------------
--  DDL for Table COMPARISON_ROW_DIF$
--------------------------------------------------------

  CREATE TABLE "SYS"."COMPARISON_ROW_DIF$" SHARING=METADATA 
   (	"COMPARISON_ID" NUMBER, 
	"SCAN_ID" NUMBER, 
	"LOC_ROWID" ROWID, 
	"RMT_ROWID" ROWID, 
	"IDX_VAL" VARCHAR2(4000 BYTE), 
	"STATUS" NUMBER, 
	"LAST_UPDATE_TIME" TIMESTAMP (6), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" VARCHAR2(1000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
