--------------------------------------------------------
--  DDL for Table COMPARISON_SCAN_VAL$
--------------------------------------------------------

  CREATE TABLE "SYS"."COMPARISON_SCAN_VAL$" SHARING=METADATA 
   (	"COMPARISON_ID" NUMBER, 
	"SCAN_ID" NUMBER, 
	"COLUMN_POSITION" NUMBER, 
	"MIN_VAL" VARCHAR2(4000 BYTE), 
	"MAX_VAL" VARCHAR2(4000 BYTE), 
	"FLAGS" NUMBER, 
	"LAST_UPDATE_TIME" TIMESTAMP (6), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" VARCHAR2(1000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
