--------------------------------------------------------
--  DDL for Table CONNECTION_TESTS$
--------------------------------------------------------

  CREATE TABLE "SYS"."CONNECTION_TESTS$" SHARING=METADATA 
   (	"PREDEFINED" NUMBER, 
	"CONNECTION_TEST_TYPE" NUMBER, 
	"SQL_CONNECTION_TEST" VARCHAR2(64 BYTE), 
	"SERVICE_NAME" VARCHAR2(128 BYTE), 
	"ENABLED" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" VARCHAR2(1000 BYTE), 
	"SPARE5" VARCHAR2(1000 BYTE), 
	"SPARE6" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
