REM INSERTING into SYS.CONNECTION_TESTS$
SET DEFINE OFF;
Insert into SYS.CONNECTION_TESTS$ (PREDEFINED,CONNECTION_TEST_TYPE,SQL_CONNECTION_TEST,SERVICE_NAME,ENABLED,SPARE1,SPARE2,SPARE3,SPARE4,SPARE5,SPARE6) values (1,0,'SELECT 1 FROM DUAL',null,1,null,null,null,null,null,null);
Insert into SYS.CONNECTION_TESTS$ (PREDEFINED,CONNECTION_TEST_TYPE,SQL_CONNECTION_TEST,SERVICE_NAME,ENABLED,SPARE1,SPARE2,SPARE3,SPARE4,SPARE5,SPARE6) values (1,0,'SELECT COUNT(*) FROM DUAL',null,1,null,null,null,null,null,null);
Insert into SYS.CONNECTION_TESTS$ (PREDEFINED,CONNECTION_TEST_TYPE,SQL_CONNECTION_TEST,SERVICE_NAME,ENABLED,SPARE1,SPARE2,SPARE3,SPARE4,SPARE5,SPARE6) values (1,0,'SELECT 1',null,1,null,null,null,null,null,null);
Insert into SYS.CONNECTION_TESTS$ (PREDEFINED,CONNECTION_TEST_TYPE,SQL_CONNECTION_TEST,SERVICE_NAME,ENABLED,SPARE1,SPARE2,SPARE3,SPARE4,SPARE5,SPARE6) values (1,0,'BEGIN NULL;END',null,1,null,null,null,null,null,null);
Insert into SYS.CONNECTION_TESTS$ (PREDEFINED,CONNECTION_TEST_TYPE,SQL_CONNECTION_TEST,SERVICE_NAME,ENABLED,SPARE1,SPARE2,SPARE3,SPARE4,SPARE5,SPARE6) values (1,1,'NA',null,0,null,null,null,null,null,null);
Insert into SYS.CONNECTION_TESTS$ (PREDEFINED,CONNECTION_TEST_TYPE,SQL_CONNECTION_TEST,SERVICE_NAME,ENABLED,SPARE1,SPARE2,SPARE3,SPARE4,SPARE5,SPARE6) values (1,2,'NA',null,0,null,null,null,null,null,null);
