--------------------------------------------------------
--  DDL for Table CONTAINER$
--------------------------------------------------------

  CREATE TABLE "SYS"."CONTAINER$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"CON_ID#" NUMBER, 
	"DBID" NUMBER, 
	"CON_UID" NUMBER, 
	"STATUS" NUMBER, 
	"CREATE_SCNWRP" NUMBER, 
	"CREATE_SCNBAS" NUMBER, 
	"CLNSCNWRP" NUMBER, 
	"CLNSCNBAS" NUMBER, 
	"RDBA" NUMBER, 
	"FLAGS" NUMBER, 
	"VSN" NUMBER, 
	"FED_ROOT_CON_ID#" NUMBER, 
	"SPARE3" VARCHAR2(128 BYTE), 
	"SPARE4" VARCHAR2(128 BYTE), 
	"SPARE5" NUMBER, 
	"SPARE6" NUMBER, 
	"UNDOSCN" NUMBER, 
	"SRCPDB" VARCHAR2(128 BYTE), 
	"LINKNAME" VARCHAR2(128 BYTE), 
	"UPGRADE_PRIORITY" NUMBER, 
	"RAFN#" NUMBER, 
	"CONTAINERS_PORT" NUMBER, 
	"CONTAINERS_HOST" VARCHAR2(128 BYTE), 
	"REMOTE_PORT" NUMBER, 
	"REMOTE_HOST" VARCHAR2(128 BYTE), 
	"REMOTE_SRVC" VARCHAR2(128 BYTE), 
	"SRCPDBUID" NUMBER, 
	"LASTRCVSCN" NUMBER, 
	"REMOTE_USER" VARCHAR2(128 BYTE), 
	"F_CDB_DBID" NUMBER, 
	"USCN" NUMBER, 
	"F_CON_ID#" NUMBER, 
	"UNDOTS" DATE, 
	"REFRESHINT" NUMBER, 
	"POSTPLUGSCN" NUMBER, 
	"POSTPLUGTIME" DATE, 
	"TENANT_ID" VARCHAR2(255 BYTE), 
	"SNAPINT" NUMBER, 
	"CREDNAME" VARCHAR2(262 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
