--------------------------------------------------------
--  Constraints for Table CONTAINER$
--------------------------------------------------------

  ALTER TABLE "SYS"."CONTAINER$" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CONTAINER$" MODIFY ("CON_ID#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CONTAINER$" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CONTAINER$" MODIFY ("CON_UID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CONTAINER$" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CONTAINER$" MODIFY ("CREATE_SCNWRP" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CONTAINER$" MODIFY ("CREATE_SCNBAS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CONTAINER$" MODIFY ("RDBA" NOT NULL ENABLE);
