REM INSERTING into SYS.CPOOL$
SET DEFINE OFF;
Insert into SYS.CPOOL$ (CONNECTION_POOL_NAME,STATUS,MINSIZE,MAXSIZE,INCRSIZE,SESSION_CACHED_CURSORS,INACTIVITY_TIMEOUT,MAX_THINK_TIME,MAX_USE_SESSION,MAX_LIFETIME_SESSION,NUM_CBROK,MAXCONN_CBROK,MAX_TXN_THINK_TIME) values ('SYS_DEFAULT_CONNECTION_POOL','INACTIVE',4,40,2,20,300,120,500000,86400,1,40000,0);
