--------------------------------------------------------
--  DDL for Table CPOOL$
--------------------------------------------------------

  CREATE TABLE "SYS"."CPOOL$" SHARING=DATA 
   (	"CONNECTION_POOL_NAME" VARCHAR2(128 BYTE), 
	"STATUS" VARCHAR2(16 BYTE), 
	"MINSIZE" NUMBER, 
	"MAXSIZE" NUMBER, 
	"INCRSIZE" NUMBER, 
	"SESSION_CACHED_CURSORS" NUMBER, 
	"INACTIVITY_TIMEOUT" NUMBER, 
	"MAX_THINK_TIME" NUMBER, 
	"MAX_USE_SESSION" NUMBER, 
	"MAX_LIFETIME_SESSION" NUMBER, 
	"NUM_CBROK" NUMBER, 
	"MAXCONN_CBROK" NUMBER, 
	"MAX_TXN_THINK_TIME" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
