--------------------------------------------------------
--  Constraints for Table DAM_CLEANUP_JOBS$
--------------------------------------------------------

  ALTER TABLE "SYS"."DAM_CLEANUP_JOBS$" MODIFY ("AUDIT_TRAIL_TYPE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DAM_CLEANUP_JOBS$" MODIFY ("JOB_INTERVAL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DAM_CLEANUP_JOBS$" ADD PRIMARY KEY ("JOB_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
