--------------------------------------------------------
--  Constraints for Table DAM_LAST_ARCH_TS$
--------------------------------------------------------

  ALTER TABLE "SYS"."DAM_LAST_ARCH_TS$" MODIFY ("AUDIT_TRAIL_TYPE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DAM_LAST_ARCH_TS$" MODIFY ("RAC_INSTANCE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DAM_LAST_ARCH_TS$" MODIFY ("LAST_ARCHIVE_TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DAM_LAST_ARCH_TS$" MODIFY ("DATABASE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DAM_LAST_ARCH_TS$" MODIFY ("CONTAINER_GUID" NOT NULL ENABLE);
