REM INSERTING into SYS.DAM_PARAM_TAB$
SET DEFINE OFF;
Insert into SYS.DAM_PARAM_TAB$ (PARAMETER#,PARAMETER_NAME) values (16,'AUDIT FILE MAX SIZE');
Insert into SYS.DAM_PARAM_TAB$ (PARAMETER#,PARAMETER_NAME) values (17,'AUDIT FILE MAX AGE');
Insert into SYS.DAM_PARAM_TAB$ (PARAMETER#,PARAMETER_NAME) values (21,'DEFAULT CLEAN UP INTERVAL');
Insert into SYS.DAM_PARAM_TAB$ (PARAMETER#,PARAMETER_NAME) values (22,'DB AUDIT TABLESPACE');
Insert into SYS.DAM_PARAM_TAB$ (PARAMETER#,PARAMETER_NAME) values (23,'DB AUDIT CLEAN BATCH SIZE');
Insert into SYS.DAM_PARAM_TAB$ (PARAMETER#,PARAMETER_NAME) values (24,'AUDIT MANAGEMENT TRACE LEVEL');
Insert into SYS.DAM_PARAM_TAB$ (PARAMETER#,PARAMETER_NAME) values (26,'OS FILE CLEAN BATCH SIZE');
Insert into SYS.DAM_PARAM_TAB$ (PARAMETER#,PARAMETER_NAME) values (33,'AUDIT WRITE MODE');
