REM INSERTING into SYS.DAM_CONFIG_PARAM$
SET DEFINE OFF;
Insert into SYS.DAM_CONFIG_PARAM$ (PARAM_ID,AUDIT_TRAIL_TYPE#,NUMBER_VALUE,STRING_VALUE) values (22,1,null,'SYSAUX');
Insert into SYS.DAM_CONFIG_PARAM$ (PARAM_ID,AUDIT_TRAIL_TYPE#,NUMBER_VALUE,STRING_VALUE) values (22,2,null,'SYSAUX');
Insert into SYS.DAM_CONFIG_PARAM$ (PARAM_ID,AUDIT_TRAIL_TYPE#,NUMBER_VALUE,STRING_VALUE) values (22,51,null,'SYSAUX');
Insert into SYS.DAM_CONFIG_PARAM$ (PARAM_ID,AUDIT_TRAIL_TYPE#,NUMBER_VALUE,STRING_VALUE) values (16,4,10000,null);
Insert into SYS.DAM_CONFIG_PARAM$ (PARAM_ID,AUDIT_TRAIL_TYPE#,NUMBER_VALUE,STRING_VALUE) values (16,8,10000,null);
Insert into SYS.DAM_CONFIG_PARAM$ (PARAM_ID,AUDIT_TRAIL_TYPE#,NUMBER_VALUE,STRING_VALUE) values (17,4,5,null);
Insert into SYS.DAM_CONFIG_PARAM$ (PARAM_ID,AUDIT_TRAIL_TYPE#,NUMBER_VALUE,STRING_VALUE) values (17,8,5,null);
Insert into SYS.DAM_CONFIG_PARAM$ (PARAM_ID,AUDIT_TRAIL_TYPE#,NUMBER_VALUE,STRING_VALUE) values (23,1,10000,null);
Insert into SYS.DAM_CONFIG_PARAM$ (PARAM_ID,AUDIT_TRAIL_TYPE#,NUMBER_VALUE,STRING_VALUE) values (23,2,10000,null);
Insert into SYS.DAM_CONFIG_PARAM$ (PARAM_ID,AUDIT_TRAIL_TYPE#,NUMBER_VALUE,STRING_VALUE) values (26,4,1000,null);
Insert into SYS.DAM_CONFIG_PARAM$ (PARAM_ID,AUDIT_TRAIL_TYPE#,NUMBER_VALUE,STRING_VALUE) values (26,8,1000,null);
Insert into SYS.DAM_CONFIG_PARAM$ (PARAM_ID,AUDIT_TRAIL_TYPE#,NUMBER_VALUE,STRING_VALUE) values (33,51,1,null);
Insert into SYS.DAM_CONFIG_PARAM$ (PARAM_ID,AUDIT_TRAIL_TYPE#,NUMBER_VALUE,STRING_VALUE) values (16,51,10000,null);
Insert into SYS.DAM_CONFIG_PARAM$ (PARAM_ID,AUDIT_TRAIL_TYPE#,NUMBER_VALUE,STRING_VALUE) values (17,51,5,null);
