--------------------------------------------------------
--  Constraints for Table DAM_CLEANUP_EVENTS$
--------------------------------------------------------

  ALTER TABLE "SYS"."DAM_CLEANUP_EVENTS$" MODIFY ("AUDIT_TRAIL_TYPE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DAM_CLEANUP_EVENTS$" MODIFY ("RAC_INSTANCE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DAM_CLEANUP_EVENTS$" MODIFY ("CLEANUP_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DAM_CLEANUP_EVENTS$" ADD PRIMARY KEY ("SERIAL#")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
