--------------------------------------------------------
--  Constraints for Table DBA_TSDP_POLICY_PROTECTION_TBL
--------------------------------------------------------

  ALTER TABLE "SYS"."DBA_TSDP_POLICY_PROTECTION_TBL" MODIFY ("SCHEMA_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBA_TSDP_POLICY_PROTECTION_TBL" MODIFY ("TABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBA_TSDP_POLICY_PROTECTION_TBL" MODIFY ("COLUMN_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBA_TSDP_POLICY_PROTECTION_TBL" MODIFY ("SUBPOLICY#" NOT NULL ENABLE);
