GRANT SELECT ON "SYS"."DBA_COMMON_AUDIT_TRAIL" TO "SELECT_CATALOG_ROLE";
  GRANT READ ON "SYS"."DBA_COMMON_AUDIT_TRAIL" TO "AUDIT_ADMIN";
  GRANT READ ON "SYS"."DBA_COMMON_AUDIT_TRAIL" TO "AUDIT_VIEWER";
