GRANT SELECT ON "SYS"."DBA_ROLE_PRIVS" TO "SELECT_CATALOG_ROLE";
  GRANT SELECT ON "SYS"."DBA_ROLE_PRIVS" TO "GSMADMIN_INTERNAL";
  GRANT SELECT ON "SYS"."DBA_ROLE_PRIVS" TO "CTXSYS";
  GRANT SELECT ON "SYS"."DBA_ROLE_PRIVS" TO "MDSYS";
  GRANT SELECT ON "SYS"."DBA_ROLE_PRIVS" TO "LBACSYS";
  GRANT READ ON "SYS"."DBA_ROLE_PRIVS" TO "DVSYS";
  GRANT READ ON "SYS"."DBA_ROLE_PRIVS" TO "DV_SECANALYST";
