--------------------------------------------------------
--  DDL for Table DBA_SENSITIVE_DATA_TBL
--------------------------------------------------------

  CREATE TABLE "SYS"."DBA_SENSITIVE_DATA_TBL" SHARING=METADATA 
   (	"SENSITIVE#" NUMBER, 
	"SCHEMA_NAME" VARCHAR2(128 BYTE), 
	"TABLE_NAME" VARCHAR2(128 BYTE), 
	"COLUMN_NAME" VARCHAR2(128 BYTE), 
	"SENSITIVE_TYPE" VARCHAR2(128 BYTE), 
	"SOURCE_NAME" VARCHAR2(128 BYTE), 
	"USER_COMMENT" VARCHAR2(4000 BYTE), 
	"TS" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
  GRANT SELECT ON "SYS"."DBA_SENSITIVE_DATA_TBL" TO "SELECT_CATALOG_ROLE";
