GRANT SELECT ON "SYS"."DBA_TABLES" TO "SELECT_CATALOG_ROLE";
  GRANT SELECT ON "SYS"."DBA_TABLES" TO "ORACLE_OCM";
  GRANT SELECT ON "SYS"."DBA_TABLES" TO "CTXSYS";
  GRANT SELECT ON "SYS"."DBA_TABLES" TO "MDSYS";
  GRANT SELECT ON "SYS"."DBA_TABLES" TO "ORDSYS";
  GRANT READ ON "SYS"."DBA_TABLES" TO "DV_SECANALYST";
