GRANT SELECT ON "SYS"."DBA_ROLES" TO "SELECT_CATALOG_ROLE";
  GRANT READ ON "SYS"."DBA_ROLES" TO "AUDIT_ADMIN";
  GRANT SELECT ON "SYS"."DBA_ROLES" TO "CTXSYS";
  GRANT SELECT ON "SYS"."DBA_ROLES" TO "OLAP_XS_ADMIN";
  GRANT READ ON "SYS"."DBA_ROLES" TO "DVSYS";
  GRANT READ ON "SYS"."DBA_ROLES" TO "DV_SECANALYST";
