GRANT SELECT ON "SYS"."DBA_TRIGGERS" TO "SELECT_CATALOG_ROLE";
  GRANT SELECT ON "SYS"."DBA_TRIGGERS" TO "CTXSYS";
  GRANT SELECT ON "SYS"."DBA_TRIGGERS" TO "MDSYS";
  GRANT READ ON "SYS"."DBA_TRIGGERS" TO "DV_SECANALYST";
