GRANT SELECT ON "SYS"."DBA_SYS_PRIVS" TO "SELECT_CATALOG_ROLE";
  GRANT SELECT ON "SYS"."DBA_SYS_PRIVS" TO "CTXSYS";
  GRANT READ ON "SYS"."DBA_SYS_PRIVS" TO "DVSYS";
  GRANT READ ON "SYS"."DBA_SYS_PRIVS" TO "DV_SECANALYST";
