GRANT SELECT ON "SYS"."DBA_AUDIT_TRAIL" TO "SELECT_CATALOG_ROLE";
  GRANT READ ON "SYS"."DBA_AUDIT_TRAIL" TO "AUDIT_ADMIN";
  GRANT READ ON "SYS"."DBA_AUDIT_TRAIL" TO "AUDIT_VIEWER";
  GRANT SELECT ON "SYS"."DBA_AUDIT_TRAIL" TO "ORACLE_OCM";
  GRANT READ ON "SYS"."DBA_AUDIT_TRAIL" TO "DV_SECANALYST";
  GRANT READ ON "SYS"."DBA_AUDIT_TRAIL" TO "DV_MONITOR";
