GRANT SELECT ON "SYS"."DBA_USERS" TO "SELECT_CATALOG_ROLE";
  GRANT READ ON "SYS"."DBA_USERS" TO "AUDIT_ADMIN";
  GRANT SELECT ON "SYS"."DBA_USERS" TO "ORACLE_OCM";
  GRANT SELECT ON "SYS"."DBA_USERS" TO "CTXSYS";
  GRANT SELECT ON "SYS"."DBA_USERS" TO "MDSYS";
  GRANT READ ON "SYS"."DBA_USERS" TO "DVSYS";
  GRANT READ ON "SYS"."DBA_USERS" TO "DV_ACCTMGR";
  GRANT READ ON "SYS"."DBA_USERS" TO "DV_SECANALYST";
