GRANT SELECT ON "SYS"."DBA_TAB_SUBPARTITIONS" TO "SELECT_CATALOG_ROLE";
  GRANT SELECT ON "SYS"."DBA_TAB_SUBPARTITIONS" TO "GSMADMIN_INTERNAL";
  GRANT SELECT ON "SYS"."DBA_TAB_SUBPARTITIONS" TO "CTXSYS";
