GRANT SELECT ON "SYS"."DBA_CONSTRAINTS" TO "SELECT_CATALOG_ROLE";
  GRANT SELECT ON "SYS"."DBA_CONSTRAINTS" TO "GSMADMIN_INTERNAL";
  GRANT SELECT ON "SYS"."DBA_CONSTRAINTS" TO "CTXSYS";
  GRANT SELECT ON "SYS"."DBA_CONSTRAINTS" TO "MDSYS";
