GRANT SELECT ON "SYS"."DBA_REGISTRY" TO "SELECT_CATALOG_ROLE";
  GRANT SELECT ON "SYS"."DBA_REGISTRY" TO "ORACLE_OCM";
  GRANT SELECT ON "SYS"."DBA_REGISTRY" TO "MDSYS";
  GRANT READ ON "SYS"."DBA_REGISTRY" TO "DATAPATCH_ROLE";
