GRANT SELECT ON "SYS"."DBA_VIEWS" TO "SELECT_CATALOG_ROLE";
  GRANT SELECT ON "SYS"."DBA_VIEWS" TO "MDSYS";
  GRANT SELECT ON "SYS"."DBA_VIEWS" TO "ORDSYS";
  GRANT READ ON "SYS"."DBA_VIEWS" TO "DV_SECANALYST";
