GRANT READ ON "SYS"."DBA_XS_AUDIT_POLICY_OPTIONS" TO "AUDIT_ADMIN";
  GRANT READ ON "SYS"."DBA_XS_AUDIT_POLICY_OPTIONS" TO "AUDIT_VIEWER";
  GRANT READ ON "SYS"."DBA_XS_AUDIT_POLICY_OPTIONS" TO "AUDSYS";
