GRANT SELECT ON "SYS"."DBA_OBJECTS" TO "SELECT_CATALOG_ROLE";
  GRANT READ ON "SYS"."DBA_OBJECTS" TO "AUDIT_ADMIN";
  GRANT SELECT ON "SYS"."DBA_OBJECTS" TO "ORACLE_OCM";
  GRANT SELECT ON "SYS"."DBA_OBJECTS" TO "CTXSYS";
  GRANT SELECT ON "SYS"."DBA_OBJECTS" TO "MDSYS";
  GRANT READ ON "SYS"."DBA_OBJECTS" TO "DVSYS";
  GRANT READ ON "SYS"."DBA_OBJECTS" TO "DV_SECANALYST";
