GRANT SELECT ON "SYS"."DBA_TAB_COLUMNS" TO "SELECT_CATALOG_ROLE";
  GRANT SELECT ON "SYS"."DBA_TAB_COLUMNS" TO "GSMADMIN_INTERNAL";
  GRANT SELECT ON "SYS"."DBA_TAB_COLUMNS" TO "CTXSYS";
  GRANT SELECT ON "SYS"."DBA_TAB_COLUMNS" TO "MDSYS";
  GRANT READ ON "SYS"."DBA_TAB_COLUMNS" TO "DV_SECANALYST";
