GRANT SELECT ON "SYS"."DBA_INDEXES" TO "SELECT_CATALOG_ROLE";
  GRANT SELECT ON "SYS"."DBA_INDEXES" TO "ORACLE_OCM";
  GRANT SELECT ON "SYS"."DBA_INDEXES" TO "GSMADMIN_INTERNAL";
  GRANT SELECT ON "SYS"."DBA_INDEXES" TO "CTXSYS";
  GRANT SELECT ON "SYS"."DBA_INDEXES" TO "MDSYS";
  GRANT SELECT ON "SYS"."DBA_INDEXES" TO "ORDSYS";
  GRANT READ ON "SYS"."DBA_INDEXES" TO "DV_SECANALYST";
