GRANT SELECT ON "SYS"."DBA_SYNONYMS" TO "SELECT_CATALOG_ROLE";
  GRANT SELECT ON "SYS"."DBA_SYNONYMS" TO "CTXSYS";
  GRANT SELECT ON "SYS"."DBA_SYNONYMS" TO "MDSYS";
  GRANT READ ON "SYS"."DBA_SYNONYMS" TO "DVSYS";
