--------------------------------------------------------
--  DDL for Table DBA_TSDP_POLICY_PROTECTION_TBL
--------------------------------------------------------

  CREATE TABLE "SYS"."DBA_TSDP_POLICY_PROTECTION_TBL" SHARING=METADATA 
   (	"SCHEMA_NAME" VARCHAR2(128 BYTE), 
	"TABLE_NAME" VARCHAR2(128 BYTE), 
	"COLUMN_NAME" VARCHAR2(128 BYTE), 
	"TSDP_POLICY" VARCHAR2(128 BYTE), 
	"SECURITY_FEATURE" VARCHAR2(12 BYTE), 
	"SECURITY_FEATURE_POLICY" VARCHAR2(128 BYTE), 
	"SUBPOLICY#" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
  GRANT SELECT ON "SYS"."DBA_TSDP_POLICY_PROTECTION_TBL" TO "SELECT_CATALOG_ROLE";
