GRANT SELECT ON "SYS"."DBA_TAB_PRIVS" TO "SELECT_CATALOG_ROLE";
  GRANT SELECT ON "SYS"."DBA_TAB_PRIVS" TO "CTXSYS";
  GRANT SELECT ON "SYS"."DBA_TAB_PRIVS" TO "MDSYS";
  GRANT READ ON "SYS"."DBA_TAB_PRIVS" TO "DVSYS";
  GRANT READ ON "SYS"."DBA_TAB_PRIVS" TO "DV_SECANALYST";
