GRANT SELECT ON "SYS"."DBA_TABLESPACES" TO "SELECT_CATALOG_ROLE";
  GRANT SELECT ON "SYS"."DBA_TABLESPACES" TO "ORACLE_OCM";
  GRANT READ ON "SYS"."DBA_TABLESPACES" TO "GSMUSER_ROLE";
  GRANT SELECT ON "SYS"."DBA_TABLESPACES" TO "GSMADMIN_INTERNAL";
  GRANT SELECT ON "SYS"."DBA_TABLESPACES" TO "MDSYS";
