--------------------------------------------------------
--  Constraints for Table DBFS_SFS$_FS
--------------------------------------------------------

  ALTER TABLE "SYS"."DBFS_SFS$_FS" MODIFY ("STORE_OWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_FS" MODIFY ("STORE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_FS" MODIFY ("TABID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_FS" MODIFY ("VOLID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_FS" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_FS" ADD UNIQUE ("STORE_OWNER", "STORE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYS"."DBFS_SFS$_FS" ADD UNIQUE ("STORE_OWNER", "TABID", "VOLID", "SNAP#")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
