--------------------------------------------------------
--  Constraints for Table DBFS_SFS$_FST
--------------------------------------------------------

  ALTER TABLE "SYS"."DBFS_SFS$_FST" MODIFY ("VOLID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_FST" MODIFY ("CSNAP#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_FST" MODIFY ("PATHNAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_FST" MODIFY ("ITEM" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_FST" MODIFY ("PATHTYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_FST" MODIFY ("STD_ACCESS_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_FST" MODIFY ("STD_CHANGE_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_FST" MODIFY ("STD_CREATION_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_FST" MODIFY ("STD_DELETED" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_FST" MODIFY ("STD_GUID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_FST" MODIFY ("STD_MODIFICATION_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_FST" MODIFY ("STD_PARENT_GUID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_FST" ADD CHECK (pathtype in (1, 2, 3, 4)) ENABLE;
  ALTER TABLE "SYS"."DBFS_SFS$_FST" ADD CHECK (posix_nlink > 0) ENABLE;
  ALTER TABLE "SYS"."DBFS_SFS$_FST" ADD CHECK (std_deleted in (0, 1)) ENABLE;
  ALTER TABLE "SYS"."DBFS_SFS$_FST" ADD PRIMARY KEY ("VOLID", "STD_GUID", "CSNAP#")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYS"."DBFS_SFS$_FST" ADD UNIQUE ("VOLID", "PATHNAME", "CSNAP#")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYS"."DBFS_SFS$_FST" ADD UNIQUE ("VOLID", "STD_PARENT_GUID", "STD_GUID", "CSNAP#")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
