--------------------------------------------------------
--  Constraints for Table DBFS_HS$_FS
--------------------------------------------------------

  ALTER TABLE "SYS"."DBFS_HS$_FS" MODIFY ("STORE_OWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_HS$_FS" MODIFY ("STORE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_HS$_FS" MODIFY ("VERSION#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_HS$_FS" ADD UNIQUE ("STORE_OWNER", "STORE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
