--------------------------------------------------------
--  DDL for Table DBFS$_MOUNTS
--------------------------------------------------------

  CREATE TABLE "SYS"."DBFS$_MOUNTS" SHARING=METADATA 
   (	"S_OWNER" VARCHAR2(128 BYTE), 
	"S_NAME" VARCHAR2(32 BYTE), 
	"S_MOUNT" VARCHAR2(32 BYTE), 
	"CREATED" TIMESTAMP (6), 
	"S_PROPS" "SYS"."DBMS_DBFS_CONTENT_PROPERTIES_T" 
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 NESTED TABLE "S_PROPS" STORE AS "S_PROPS_TAB"
 (PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
 NOCOMPRESS 
  TABLESPACE "SYSTEM" ) RETURN AS VALUE;
  GRANT SELECT ON "SYS"."DBFS$_MOUNTS" TO "DBFS_ROLE";
