--------------------------------------------------------
--  Constraints for Table DBFS_SFS$_SNAP
--------------------------------------------------------

  ALTER TABLE "SYS"."DBFS_SFS$_SNAP" MODIFY ("TABID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_SNAP" MODIFY ("VOLID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_SNAP" MODIFY ("SNAP#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_SNAP" MODIFY ("SNAPNAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_SNAP" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_SNAP" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_SNAP" ADD CHECK (deleted in (0, 1)) ENABLE;
  ALTER TABLE "SYS"."DBFS_SFS$_SNAP" ADD PRIMARY KEY ("TABID", "VOLID", "SNAP#")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
