--------------------------------------------------------
--  Constraints for Table DBFS$_STORES
--------------------------------------------------------

  ALTER TABLE "SYS"."DBFS$_STORES" MODIFY ("S_OWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS$_STORES" MODIFY ("S_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS$_STORES" MODIFY ("P_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS$_STORES" MODIFY ("P_PKG" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS$_STORES" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS$_STORES" ADD PRIMARY KEY ("S_OWNER", "S_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
