--------------------------------------------------------
--  DDL for Table DBFS_SFS$_TAB
--------------------------------------------------------

  CREATE TABLE "SYS"."DBFS_SFS$_TAB" SHARING=METADATA 
   (	"TABID" NUMBER, 
	"SCHEMA_NAME" VARCHAR2(128 BYTE), 
	"TABLE_NAME" VARCHAR2(128 BYTE), 
	"PTABLE_NAME" VARCHAR2(128 BYTE), 
	"VERSION#" VARCHAR2(32 BYTE), 
	"CREATED" TIMESTAMP (6), 
	"FORMATTED" TIMESTAMP (6), 
	"PROPERTIES" "SYS"."DBMS_DBFS_CONTENT_PROPERTIES_T" 
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 NESTED TABLE "PROPERTIES" STORE AS "PROPERTIES_TAB"
 (PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
 NOCOMPRESS 
  TABLESPACE "SYSTEM" ) RETURN AS VALUE;
  GRANT SELECT ON "SYS"."DBFS_SFS$_TAB" TO "DBFS_ROLE";
