--------------------------------------------------------
--  Constraints for Table DBFS_HS$_PROPERTY
--------------------------------------------------------

  ALTER TABLE "SYS"."DBFS_HS$_PROPERTY" MODIFY ("STORE_OWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_HS$_PROPERTY" MODIFY ("STORE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_HS$_PROPERTY" MODIFY ("PROP_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_HS$_PROPERTY" MODIFY ("PROP_VALUE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_HS$_PROPERTY" MODIFY ("PROP_TYPE" NOT NULL ENABLE);
