--------------------------------------------------------
--  Constraints for Table DBFS_SFS$_FSTP
--------------------------------------------------------

  ALTER TABLE "SYS"."DBFS_SFS$_FSTP" MODIFY ("VOLID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_FSTP" MODIFY ("CSNAP#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_FSTP" MODIFY ("STD_GUID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_FSTP" MODIFY ("PROPNAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_FSTP" MODIFY ("PROPVALUE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_FSTP" MODIFY ("TYPECODE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_FSTP" ADD UNIQUE ("VOLID", "STD_GUID", "CSNAP#", "PROPNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
