--------------------------------------------------------
--  DDL for Table DBFS_SFS$_FSTO
--------------------------------------------------------

  CREATE TABLE "SYS"."DBFS_SFS$_FSTO" SHARING=METADATA 
   (	"VOLID" NUMBER DEFAULT 0, 
	"CSNAP#" NUMBER DEFAULT 0, 
	"LSNAP#" NUMBER DEFAULT null
        /* basic fields for the DBFS-API */, 
	"PATHNAME" VARCHAR2(1024 BYTE), 
	"ITEM" VARCHAR2(256 BYTE), 
	"PATHTYPE" NUMBER(*,0), 
	"FILEDATA" BLOB, 
	"POSIX_NLINK" NUMBER(*,0) DEFAULT 1, 
	"POSIX_MODE" NUMBER(*,0) DEFAULT 0      /* ---------- */
   , 
	"POSIX_UID" NUMBER(*,0) DEFAULT 0          /* root=0 */, 
	"POSIX_GID" NUMBER(*,0) DEFAULT 0          /* root=0 */
        /* standard properties for the DBFS-API */, 
	"STD_ACCESS_TIME" TIMESTAMP (6), 
	"STD_ACL" VARCHAR2(1024 BYTE), 
	"STD_CHANGE_TIME" TIMESTAMP (6), 
	"STD_CONTENT_TYPE" VARCHAR2(1024 BYTE), 
	"STD_CREATION_TIME" TIMESTAMP (6), 
	"STD_DELETED" NUMBER(*,0), 
	"STD_GUID" NUMBER(*,0), 
	"STD_MODIFICATION_TIME" TIMESTAMP (6), 
	"STD_OWNER" VARCHAR2(32 BYTE), 
	"STD_PARENT_GUID" NUMBER(*,0), 
	"STD_REFERENT" VARCHAR2(1024 BYTE), 
	"OPT_HASH_TYPE" VARCHAR2(32 BYTE), 
	"OPT_HASH_VALUE" VARCHAR2(128 BYTE), 
	"OPT_LOCK_COUNT" NUMBER(*,0), 
	"OPT_LOCK_DATA" VARCHAR2(128 BYTE), 
	"OPT_LOCK_STATUS" NUMBER(*,0), 
	"USR_PROPERTIES" "SYS"."DBMS_DBFS_CONTENT_PROPERTIES_T" 
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 NESTED TABLE "USR_PROPERTIES" STORE AS "USR_PROPERTIES_TAB"
 (PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
 NOCOMPRESS 
  TABLESPACE "SYSTEM" ) RETURN AS VALUE
 LOB ("FILEDATA") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
  GRANT SELECT ON "SYS"."DBFS_SFS$_FSTO" TO "DBFS_ROLE";
