--------------------------------------------------------
--  Constraints for Table DBFS$_STATS
--------------------------------------------------------

  ALTER TABLE "SYS"."DBFS$_STATS" MODIFY ("S_OWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS$_STATS" MODIFY ("S_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS$_STATS" MODIFY ("OPCODE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS$_STATS" MODIFY ("COUNT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS$_STATS" MODIFY ("WTIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS$_STATS" MODIFY ("CTIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS$_STATS" ADD UNIQUE ("S_OWNER", "S_NAME", "S_MOUNT", "OPCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
