--------------------------------------------------------
--  Constraints for Table DBFS_SFS$_TAB
--------------------------------------------------------

  ALTER TABLE "SYS"."DBFS_SFS$_TAB" MODIFY ("TABID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_TAB" MODIFY ("SCHEMA_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_TAB" MODIFY ("TABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_TAB" MODIFY ("VERSION#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_TAB" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_TAB" MODIFY ("FORMATTED" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_TAB" ADD PRIMARY KEY ("TABID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYS"."DBFS_SFS$_TAB" ADD UNIQUE ("PROPERTIES") RELY
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYS"."DBFS_SFS$_TAB" ADD UNIQUE ("SCHEMA_NAME", "TABLE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
