--------------------------------------------------------
--  Constraints for Table DBFS_SFS$_VOL
--------------------------------------------------------

  ALTER TABLE "SYS"."DBFS_SFS$_VOL" MODIFY ("TABID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_VOL" MODIFY ("VOLID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_VOL" MODIFY ("VOLNAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_VOL" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_VOL" MODIFY ("CSNAP#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_VOL" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBFS_SFS$_VOL" ADD CHECK (deleted in (0, 1)) ENABLE;
  ALTER TABLE "SYS"."DBFS_SFS$_VOL" ADD PRIMARY KEY ("TABID", "VOLID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
