--------------------------------------------------------
--  DDL for Table DBFS_HS$_BACKUPFILETABLE
--------------------------------------------------------

  CREATE TABLE "SYS"."DBFS_HS$_BACKUPFILETABLE" SHARING=METADATA 
   (	"TARBALLID" NUMBER, 
	"STOREID" NUMBER, 
	"BACKUPFILENAME" VARCHAR2(256 BYTE), 
	"TARSTARTOFFSET" NUMBER, 
	"TARENDOFFSET" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
