--------------------------------------------------------
--  DDL for Package Body DBMS_REGISTRY
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE BODY "SYS"."DBMS_REGISTRY" 

/

  GRANT EXECUTE ON "SYS"."DBMS_REGISTRY" TO "EXECUTE_CATALOG_ROLE";
  GRANT EXECUTE ON "SYS"."DBMS_REGISTRY" TO "XDB";
  GRANT EXECUTE ON "SYS"."DBMS_REGISTRY" TO "WMSYS";
  GRANT EXECUTE ON "SYS"."DBMS_REGISTRY" TO "CTXSYS";
  GRANT EXECUTE ON "SYS"."DBMS_REGISTRY" TO "MDSYS";
  GRANT EXECUTE ON "SYS"."DBMS_REGISTRY" TO "LBACSYS";
  GRANT EXECUTE ON "SYS"."DBMS_REGISTRY" TO "DATAPATCH_ROLE";
