--------------------------------------------------------
--  DDL for Package DBMS_AUTO_TASK_EXPORT
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "SYS"."DBMS_AUTO_TASK_EXPORT" 

/

  GRANT EXECUTE ON "SYS"."DBMS_AUTO_TASK_EXPORT" TO "EXECUTE_CATALOG_ROLE";
  GRANT EXECUTE ON "SYS"."DBMS_AUTO_TASK_EXPORT" TO "EXP_FULL_DATABASE";
  GRANT EXECUTE ON "SYS"."DBMS_AUTO_TASK_EXPORT" TO "IMP_FULL_DATABASE";
