--------------------------------------------------------
--  DDL for Package Body DBMS_AQ
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE BODY "SYS"."DBMS_AQ" 

/

  GRANT EXECUTE ON "SYS"."DBMS_AQ" TO "AQ_ADMINISTRATOR_ROLE";
  GRANT EXECUTE ON "SYS"."DBMS_AQ" TO "AQ_USER_ROLE";
  GRANT EXECUTE ON "SYS"."DBMS_AQ" TO "SYSTEM";
  GRANT EXECUTE ON "SYS"."DBMS_AQ" TO "EXECUTE_CATALOG_ROLE";
  GRANT EXECUTE ON "SYS"."DBMS_AQ" TO "OEM_MONITOR";
  GRANT EXECUTE ON "SYS"."DBMS_AQ" TO "GSMADMIN_INTERNAL";
  GRANT EXECUTE ON "SYS"."DBMS_AQ" TO "GSMCATUSER";
  GRANT EXECUTE ON "SYS"."DBMS_AQ" TO "WMSYS";
  GRANT EXECUTE ON "SYS"."DBMS_AQ" TO "MDSYS";
