--------------------------------------------------------
--  DDL for Package Body DBMS_SERVER_ALERT
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE BODY "SYS"."DBMS_SERVER_ALERT" 

/

  GRANT EXECUTE ON "SYS"."DBMS_SERVER_ALERT" TO "DBA";
  GRANT EXECUTE ON "SYS"."DBMS_SERVER_ALERT" TO "IMP_FULL_DATABASE";
  GRANT EXECUTE ON "SYS"."DBMS_SERVER_ALERT" TO "GSMADMIN_INTERNAL";
  GRANT EXECUTE ON "SYS"."DBMS_SERVER_ALERT" TO "DATAPUMP_IMP_FULL_DATABASE";
  GRANT EXECUTE ON "SYS"."DBMS_SERVER_ALERT" TO "OEM_MONITOR";
  GRANT EXECUTE ON "SYS"."DBMS_SERVER_ALERT" TO "DBSNMP";
  GRANT EXECUTE ON "SYS"."DBMS_SERVER_ALERT" TO "SYSRAC";
