--------------------------------------------------------
--  DDL for Package DBMS_NETWORK_ACL_ADMIN
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "SYS"."DBMS_NETWORK_ACL_ADMIN" 

/

  GRANT EXECUTE ON "SYS"."DBMS_NETWORK_ACL_ADMIN" TO "DBA";
  GRANT EXECUTE ON "SYS"."DBMS_NETWORK_ACL_ADMIN" TO "EXECUTE_CATALOG_ROLE";
  GRANT EXECUTE ON "SYS"."DBMS_NETWORK_ACL_ADMIN" TO "GSMADMIN_INTERNAL";
  GRANT EXECUTE ON "SYS"."DBMS_NETWORK_ACL_ADMIN" TO "GGSYS";
  GRANT EXECUTE ON "SYS"."DBMS_NETWORK_ACL_ADMIN" TO "MDSYS";
