--------------------------------------------------------
--  DDL for Table DBMS_STATS_OBJ_LIST_TAB
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "SYS"."DBMS_STATS_OBJ_LIST_TAB" SHARING=METADATA 
   (	"ORIG_BASE_OBJECT_SCHEMA" VARCHAR2(128 BYTE), 
	"BASE_OBJECT_SCHEMA" VARCHAR2(128 BYTE), 
	"BASE_OBJECT_NAME" VARCHAR2(128 BYTE), 
	"PROCESSING_STATE" CHAR(1 BYTE), 
	"PROCESSING_STATUS" CHAR(1 BYTE), 
	"OBJECT_TYPE" VARCHAR2(128 BYTE), 
	"PROCESS_ORDER" NUMBER, 
	"DUPLICATE" NUMBER
   ) ON COMMIT PRESERVE ROWS ;
