--------------------------------------------------------
--  DDL for Package DBMS_GSM_FIXED
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "SYS"."DBMS_GSM_FIXED" 

/

  GRANT EXECUTE ON "SYS"."DBMS_GSM_FIXED" TO "SYSDG";
  GRANT EXECUTE ON "SYS"."DBMS_GSM_FIXED" TO "GGSYS";
  GRANT EXECUTE ON "SYS"."DBMS_GSM_FIXED" TO "GSMUSER_ROLE";
  GRANT EXECUTE ON "SYS"."DBMS_GSM_FIXED" TO "GSMROOTUSER_ROLE";
  GRANT EXECUTE ON "SYS"."DBMS_GSM_FIXED" TO "GSMADMIN_INTERNAL";
