--------------------------------------------------------
--  Constraints for Table DBMS_PARALLEL_EXECUTE_CHUNKS$
--------------------------------------------------------

  ALTER TABLE "SYS"."DBMS_PARALLEL_EXECUTE_CHUNKS$" MODIFY ("CHUNK_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBMS_PARALLEL_EXECUTE_CHUNKS$" MODIFY ("TASK_OWNER#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBMS_PARALLEL_EXECUTE_CHUNKS$" MODIFY ("TASK_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBMS_PARALLEL_EXECUTE_CHUNKS$" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBMS_PARALLEL_EXECUTE_CHUNKS$" ADD CONSTRAINT "I_DBMS_PARALLEL_EXECUTE_CHUNK1" PRIMARY KEY ("CHUNK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
