--------------------------------------------------------
--  DDL for Package Body DBMS_AUTO_TASK_ADMIN
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE BODY "SYS"."DBMS_AUTO_TASK_ADMIN" 

/

  GRANT EXECUTE ON "SYS"."DBMS_AUTO_TASK_ADMIN" TO "DBA";
  GRANT EXECUTE ON "SYS"."DBMS_AUTO_TASK_ADMIN" TO "IMP_FULL_DATABASE";
  GRANT EXECUTE ON "SYS"."DBMS_AUTO_TASK_ADMIN" TO "DATAPUMP_IMP_FULL_DATABASE";
  GRANT EXECUTE ON "SYS"."DBMS_AUTO_TASK_ADMIN" TO "EM_EXPRESS_ALL";
