--------------------------------------------------------
--  DDL for Package DBMS_UTILITY
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "SYS"."DBMS_UTILITY" 

/

  GRANT EXECUTE ON "SYS"."DBMS_UTILITY" TO PUBLIC;
  GRANT EXECUTE ON "SYS"."DBMS_UTILITY" TO "DBSFWUSER";
  GRANT EXECUTE ON "SYS"."DBMS_UTILITY" TO "GSMADMIN_INTERNAL";
  GRANT EXECUTE ON "SYS"."DBMS_UTILITY" TO "WMSYS";
  GRANT EXECUTE ON "SYS"."DBMS_UTILITY" TO "ORDSYS";
  GRANT EXECUTE ON "SYS"."DBMS_UTILITY" TO "DVSYS";
