--------------------------------------------------------
--  DDL for Package DBMS_WORKLOAD_REPOSITORY
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "SYS"."DBMS_WORKLOAD_REPOSITORY" 

/

  GRANT EXECUTE ON "SYS"."DBMS_WORKLOAD_REPOSITORY" TO "DBA";
  GRANT EXECUTE ON "SYS"."DBMS_WORKLOAD_REPOSITORY" TO "SYSUMF_ROLE";
  GRANT EXECUTE ON "SYS"."DBMS_WORKLOAD_REPOSITORY" TO "OEM_MONITOR";
  GRANT EXECUTE ON "SYS"."DBMS_WORKLOAD_REPOSITORY" TO "QPI_RBL_MISDB_PROD";
