--------------------------------------------------------
--  Constraints for Table DBMS_PARALLEL_EXECUTE_TASK$
--------------------------------------------------------

  ALTER TABLE "SYS"."DBMS_PARALLEL_EXECUTE_TASK$" MODIFY ("TASK_OWNER#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBMS_PARALLEL_EXECUTE_TASK$" MODIFY ("TASK_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBMS_PARALLEL_EXECUTE_TASK$" MODIFY ("CHUNK_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBMS_PARALLEL_EXECUTE_TASK$" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DBMS_PARALLEL_EXECUTE_TASK$" ADD CONSTRAINT "PK_DBMS_PARALLEL_EXECUTE_1" PRIMARY KEY ("TASK_OWNER#", "TASK_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
