--------------------------------------------------------
--  DDL for Package Body DBMS_AQ_IMPORT_INTERNAL
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE BODY "SYS"."DBMS_AQ_IMPORT_INTERNAL" 

/

  GRANT EXECUTE ON "SYS"."DBMS_AQ_IMPORT_INTERNAL" TO "AQ_ADMINISTRATOR_ROLE";
  GRANT EXECUTE ON "SYS"."DBMS_AQ_IMPORT_INTERNAL" TO "SYSTEM";
  GRANT EXECUTE ON "SYS"."DBMS_AQ_IMPORT_INTERNAL" TO "IMP_FULL_DATABASE";
  GRANT EXECUTE ON "SYS"."DBMS_AQ_IMPORT_INTERNAL" TO "EXP_FULL_DATABASE";
  GRANT EXECUTE ON "SYS"."DBMS_AQ_IMPORT_INTERNAL" TO "EXECUTE_CATALOG_ROLE";
