--------------------------------------------------------
--  DDL for Package Body DBMS_AQADM
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE BODY "SYS"."DBMS_AQADM" 

/

  GRANT EXECUTE ON "SYS"."DBMS_AQADM" TO "AQ_ADMINISTRATOR_ROLE";
  GRANT EXECUTE ON "SYS"."DBMS_AQADM" TO "SYSTEM";
  GRANT EXECUTE ON "SYS"."DBMS_AQADM" TO "EXECUTE_CATALOG_ROLE";
  GRANT EXECUTE ON "SYS"."DBMS_AQADM" TO "IMP_FULL_DATABASE";
  GRANT EXECUTE ON "SYS"."DBMS_AQADM" TO "OEM_MONITOR";
  GRANT EXECUTE ON "SYS"."DBMS_AQADM" TO "GSMADMIN_INTERNAL";
  GRANT EXECUTE ON "SYS"."DBMS_AQADM" TO "WMSYS";
  GRANT EXECUTE ON "SYS"."DBMS_AQADM" TO "MDSYS";
