--------------------------------------------------------
--  DDL for Package DBMS_RULE_EXIMP
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "SYS"."DBMS_RULE_EXIMP" 

/

  GRANT EXECUTE ON "SYS"."DBMS_RULE_EXIMP" TO "SYSTEM";
  GRANT EXECUTE ON "SYS"."DBMS_RULE_EXIMP" TO "IMP_FULL_DATABASE";
  GRANT EXECUTE ON "SYS"."DBMS_RULE_EXIMP" TO "EXP_FULL_DATABASE";
  GRANT EXECUTE ON "SYS"."DBMS_RULE_EXIMP" TO "EXECUTE_CATALOG_ROLE";
  GRANT EXECUTE ON "SYS"."DBMS_RULE_EXIMP" TO "AQ_ADMINISTRATOR_ROLE";
