--------------------------------------------------------
--  DDL for Package Body DBMS_TRANSFORM_EXIMP
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE BODY "SYS"."DBMS_TRANSFORM_EXIMP" 

/

  GRANT EXECUTE ON "SYS"."DBMS_TRANSFORM_EXIMP" TO PUBLIC;
  GRANT EXECUTE ON "SYS"."DBMS_TRANSFORM_EXIMP" TO "SYSTEM";
  GRANT EXECUTE ON "SYS"."DBMS_TRANSFORM_EXIMP" TO "IMP_FULL_DATABASE";
  GRANT EXECUTE ON "SYS"."DBMS_TRANSFORM_EXIMP" TO "EXP_FULL_DATABASE";
  GRANT EXECUTE ON "SYS"."DBMS_TRANSFORM_EXIMP" TO "EXECUTE_CATALOG_ROLE";
