--------------------------------------------------------
--  DDL for Table DBMS_PARALLEL_EXECUTE_CHUNKS$
--------------------------------------------------------

  CREATE TABLE "SYS"."DBMS_PARALLEL_EXECUTE_CHUNKS$" SHARING=METADATA 
   (	"CHUNK_ID" NUMBER, 
	"TASK_OWNER#" NUMBER, 
	"TASK_NAME" VARCHAR2(128 BYTE), 
	"STATUS" NUMBER, 
	"START_ROWID" ROWID, 
	"END_ROWID" ROWID, 
	"START_ID" NUMBER, 
	"END_ID" NUMBER, 
	"JOB_NAME" VARCHAR2(128 BYTE), 
	"START_TS" TIMESTAMP (6), 
	"END_TS" TIMESTAMP (6), 
	"ERROR_CODE" NUMBER, 
	"ERROR_MESSAGE" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
