--------------------------------------------------------
--  DDL for Table DBMS_SQLPATCH_STATE
--------------------------------------------------------

  CREATE TABLE "SYS"."DBMS_SQLPATCH_STATE" SHARING=METADATA 
   (	"ACTIVE" CHAR(1 BYTE), 
	"S_CURRENT_PATCH_ID" NUMBER, 
	"S_CURRENT_PATCH_UID" NUMBER, 
	"S_CURRENT_PATCH_TYPE" VARCHAR2(10 BYTE), 
	"S_CURRENT_PATCH_ACTION" VARCHAR2(15 BYTE), 
	"S_CURRENT_PATCH_DESCRIPTION" VARCHAR2(100 BYTE), 
	"S_CURRENT_PATCH_FLAGS" VARCHAR2(10 BYTE), 
	"S_CURRENT_PATCH_DESCRIPTOR" "SYS"."XMLTYPE" , 
	"S_CURRENT_PATCH_DIRECTORY" BLOB, 
	"S_CURRENT_SOURCE_VERSION" VARCHAR2(15 BYTE), 
	"S_CURRENT_SOURCE_BUILD_DESC" VARCHAR2(80 BYTE), 
	"S_CURRENT_SOURCE_BUILD_TS" TIMESTAMP (6), 
	"S_CURRENT_TARGET_VERSION" VARCHAR2(15 BYTE), 
	"S_CURRENT_TARGET_BUILD_DESC" VARCHAR2(80 BYTE), 
	"S_CURRENT_TARGET_BUILD_TS" TIMESTAMP (6), 
	"S_CURRENT_RU_LOGFILE" VARCHAR2(500 BYTE), 
	"S_CURRENT_REGISTRY_ROWID" ROWID, 
	"S_NOTHING_SQL" VARCHAR2(30 BYTE), 
	"S_DEBUG" CHAR(1 BYTE), 
	"S_FORCE" CHAR(1 BYTE), 
	"S_INIT_COMPLETE" CHAR(1 BYTE), 
	"S_CACHED_LSINVENTORY" "SYS"."XMLTYPE" , 
	"S_SESSION_INSTALL_ID" NUMBER, 
	"S_APP_MODE" CHAR(1 BYTE), 
	"S_CONTAINER_NAME" VARCHAR2(128 BYTE), 
	"S_CACHED_PENDING_ACTIVITY" "SYS"."XMLTYPE" , 
	"S_ATTEMPT" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 XMLTYPE COLUMN "S_CURRENT_PATCH_DESCRIPTOR" STORE AS BASICFILE BINARY XML (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ALLOW NONSCHEMA DISALLOW ANYSCHEMA 
 LOB ("S_CURRENT_PATCH_DIRECTORY") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 XMLTYPE COLUMN "S_CACHED_LSINVENTORY" STORE AS BASICFILE CLOB (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 XMLTYPE COLUMN "S_CACHED_PENDING_ACTIVITY" STORE AS BASICFILE CLOB (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
  GRANT READ ON "SYS"."DBMS_SQLPATCH_STATE" TO "DATAPATCH_ROLE";
