--------------------------------------------------------
--  DDL for Package DBMS_AUTO_TASK_ADMIN
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "SYS"."DBMS_AUTO_TASK_ADMIN" 

/

  GRANT EXECUTE ON "SYS"."DBMS_AUTO_TASK_ADMIN" TO "DBA";
  GRANT EXECUTE ON "SYS"."DBMS_AUTO_TASK_ADMIN" TO "IMP_FULL_DATABASE";
  GRANT EXECUTE ON "SYS"."DBMS_AUTO_TASK_ADMIN" TO "DATAPUMP_IMP_FULL_DATABASE";
  GRANT EXECUTE ON "SYS"."DBMS_AUTO_TASK_ADMIN" TO "EM_EXPRESS_ALL";
