--------------------------------------------------------
--  DDL for Table DBMS_PARALLEL_EXECUTE_TASK$
--------------------------------------------------------

  CREATE TABLE "SYS"."DBMS_PARALLEL_EXECUTE_TASK$" SHARING=METADATA 
   (	"TASK_OWNER#" NUMBER, 
	"TASK_NAME" VARCHAR2(128 BYTE), 
	"CHUNK_TYPE" NUMBER, 
	"STATUS" NUMBER, 
	"TABLE_OWNER" VARCHAR2(128 BYTE), 
	"TABLE_NAME" VARCHAR2(128 BYTE), 
	"NUMBER_COLUMN" VARCHAR2(128 BYTE), 
	"CMT" VARCHAR2(4000 BYTE), 
	"JOB_PREFIX" VARCHAR2(128 BYTE), 
	"STOP_FLAG" NUMBER, 
	"SQL_STMT" CLOB, 
	"LANGUAGE_FLAG" NUMBER, 
	"EDITION" VARCHAR2(130 BYTE), 
	"APPLY_CROSSEDITION_TRIGGER" VARCHAR2(130 BYTE), 
	"FIRE_APPLY_TRIGGER" VARCHAR2(10 BYTE), 
	"PARALLEL_LEVEL" NUMBER, 
	"JOB_CLASS" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("SQL_STMT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
