--------------------------------------------------------
--  DDL for Package DBMS_LOCK
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "SYS"."DBMS_LOCK" 

/

  GRANT EXECUTE ON "SYS"."DBMS_LOCK" TO "EXECUTE_CATALOG_ROLE";
  GRANT EXECUTE ON "SYS"."DBMS_LOCK" TO "RECOVERY_CATALOG_OWNER";
  GRANT EXECUTE ON "SYS"."DBMS_LOCK" TO "RECOVERY_CATALOG_USER";
  GRANT EXECUTE ON "SYS"."DBMS_LOCK" TO "RECOVERY_CATALOG_OWNER_VPD";
  GRANT EXECUTE ON "SYS"."DBMS_LOCK" TO "AUDSYS";
  GRANT EXECUTE ON "SYS"."DBMS_LOCK" TO "GSMADMIN_INTERNAL";
  GRANT EXECUTE ON "SYS"."DBMS_LOCK" TO "GGSYS";
  GRANT EXECUTE ON "SYS"."DBMS_LOCK" TO "WMSYS";
  GRANT EXECUTE ON "SYS"."DBMS_LOCK" TO "CTXSYS";
  GRANT EXECUTE ON "SYS"."DBMS_LOCK" TO "MDSYS";
  GRANT EXECUTE ON "SYS"."DBMS_LOCK" TO "ORDSYS";
  GRANT EXECUTE ON "SYS"."DBMS_LOCK" TO "DATAPATCH_ROLE";
