--------------------------------------------------------
--  DDL for Package Body DBMS_RLS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE BODY "SYS"."DBMS_RLS" 

/

  GRANT EXECUTE ON "SYS"."DBMS_RLS" TO "EXECUTE_CATALOG_ROLE";
  GRANT EXECUTE ON "SYS"."DBMS_RLS" TO "RECOVERY_CATALOG_OWNER_VPD";
  GRANT EXECUTE ON "SYS"."DBMS_RLS" TO "GSMADMIN_INTERNAL";
  GRANT EXECUTE ON "SYS"."DBMS_RLS" TO "XDB";
  GRANT EXECUTE ON "SYS"."DBMS_RLS" TO "WMSYS";
  GRANT EXECUTE ON "SYS"."DBMS_RLS" TO "MDSYS";
