--------------------------------------------------------
--  DDL for Table DBMS_LOCK_ALLOCATED
--------------------------------------------------------

  CREATE TABLE "SYS"."DBMS_LOCK_ALLOCATED" SHARING=METADATA 
   (	"NAME" VARCHAR2(128 BYTE), 
	"LOCKID" NUMBER(*,0), 
	"EXPIRATION" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  GRANT SELECT ON "SYS"."DBMS_LOCK_ALLOCATED" TO "GSMADMIN_INTERNAL";
