--------------------------------------------------------
--  Constraints for Table DDL_REQUESTS
--------------------------------------------------------

  ALTER TABLE "SYS"."DDL_REQUESTS" MODIFY ("DDL_TEXT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DDL_REQUESTS" MODIFY ("SCHEMA_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DDL_REQUESTS" MODIFY ("OPERATION_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DDL_REQUESTS" ADD PRIMARY KEY ("DDL_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
