--------------------------------------------------------
--  DDL for Table DDL_REQUESTS_PWD
--------------------------------------------------------

  CREATE TABLE "SYS"."DDL_REQUESTS_PWD" SHARING=METADATA 
   (	"DDL_NUM" NUMBER, 
	"PWD_BEGIN" NUMBER, 
	"ENC_PWD" RAW(128)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
  GRANT DELETE ON "SYS"."DDL_REQUESTS_PWD" TO "GSMADMIN_INTERNAL";
  GRANT INSERT ON "SYS"."DDL_REQUESTS_PWD" TO "GSMADMIN_INTERNAL";
  GRANT SELECT ON "SYS"."DDL_REQUESTS_PWD" TO "GSMADMIN_INTERNAL";
  GRANT UPDATE ON "SYS"."DDL_REQUESTS_PWD" TO "GSMADMIN_INTERNAL";
  GRANT SELECT ON "SYS"."DDL_REQUESTS_PWD" TO "GSMADMIN_ROLE";
  GRANT SELECT ON "SYS"."DDL_REQUESTS_PWD" TO "GDS_CATALOG_SELECT";
  GRANT SELECT ON "SYS"."DDL_REQUESTS_PWD" TO "GSM_POOLADMIN_ROLE";
  GRANT DELETE ON "SYS"."DDL_REQUESTS_PWD" TO "GGSYS";
  GRANT INSERT ON "SYS"."DDL_REQUESTS_PWD" TO "GGSYS";
  GRANT SELECT ON "SYS"."DDL_REQUESTS_PWD" TO "GGSYS";
  GRANT UPDATE ON "SYS"."DDL_REQUESTS_PWD" TO "GGSYS";
  GRANT REFERENCES ON "SYS"."DDL_REQUESTS_PWD" TO "GGSYS";
