--------------------------------------------------------
--  DDL for Table DDL_REQUESTS
--------------------------------------------------------

  CREATE TABLE "SYS"."DDL_REQUESTS" SHARING=METADATA 
   (	"DDL_NUM" NUMBER, 
	"DDL_TEXT" CLOB, 
	"PWD_COUNT" NUMBER, 
	"SCHEMA_NAME" VARCHAR2(128 BYTE), 
	"OBJECT_NAME" VARCHAR2(128 BYTE) DEFAULT NULL, 
	"OPERATION_TYPE" CHAR(1 BYTE), 
	"OBJECT_TYPE" NUMBER DEFAULT NULL, 
	"PARAMS" VARCHAR2(4000 BYTE) DEFAULT NULL, 
	"IGNORE_FLAG" NUMBER, 
	"SESS_INFO" CLOB DEFAULT NULL, 
	"SHARDSPACE" VARCHAR2(128 BYTE) DEFAULT NULL, 
	"OBJECT_OWNER" VARCHAR2(128 BYTE), 
	"OP_CODE" CHAR(1 BYTE) DEFAULT NULL, 
	"ORIG_DDL_TEXT" CLOB DEFAULT NULL, 
	"DDL_FLAG" NUMBER, 
	"DDL_INTCODE" NUMBER DEFAULT NULL
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("DDL_TEXT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("SESS_INFO") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("ORIG_DDL_TEXT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
  GRANT DELETE ON "SYS"."DDL_REQUESTS" TO "GSMADMIN_INTERNAL";
  GRANT INSERT ON "SYS"."DDL_REQUESTS" TO "GSMADMIN_INTERNAL";
  GRANT SELECT ON "SYS"."DDL_REQUESTS" TO "GSMADMIN_INTERNAL";
  GRANT UPDATE ON "SYS"."DDL_REQUESTS" TO "GSMADMIN_INTERNAL";
  GRANT SELECT ON "SYS"."DDL_REQUESTS" TO "GSMADMIN_ROLE";
  GRANT SELECT ON "SYS"."DDL_REQUESTS" TO "GDS_CATALOG_SELECT";
  GRANT SELECT ON "SYS"."DDL_REQUESTS" TO "GSM_POOLADMIN_ROLE";
  GRANT DELETE ON "SYS"."DDL_REQUESTS" TO "GGSYS";
  GRANT INSERT ON "SYS"."DDL_REQUESTS" TO "GGSYS";
  GRANT SELECT ON "SYS"."DDL_REQUESTS" TO "GGSYS";
  GRANT UPDATE ON "SYS"."DDL_REQUESTS" TO "GGSYS";
  GRANT REFERENCES ON "SYS"."DDL_REQUESTS" TO "GGSYS";
