--------------------------------------------------------
--  DDL for Table DEFAULT_PWD$
--------------------------------------------------------

  CREATE TABLE "SYS"."DEFAULT_PWD$" SHARING=DATA 
   (	"USER_NAME" VARCHAR2(128 BYTE), 
	"PWD_VERIFIER" VARCHAR2(512 BYTE), 
	"PV_TYPE" NUMBER DEFAULT 0, 
	"PRODUCT" VARCHAR2(4000 BYTE) DEFAULT NULL        /* product information */
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
