--------------------------------------------------------
--  DDL for Table DEFERRED_STG$
--------------------------------------------------------

  CREATE TABLE "SYS"."DEFERRED_STG$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"PCTFREE_STG" NUMBER, 
	"PCTUSED_STG" NUMBER, 
	"SIZE_STG" NUMBER, 
	"INITIAL_STG" NUMBER, 
	"NEXT_STG" NUMBER, 
	"MINEXT_STG" NUMBER, 
	"MAXEXT_STG" NUMBER, 
	"MAXSIZ_STG" NUMBER, 
	"LOBRET_STG" NUMBER, 
	"MINTIM_STG" NUMBER, 
	"PCTINC_STG" NUMBER, 
	"INITRA_STG" NUMBER, 
	"MAXTRA_STG" NUMBER, 
	"OPTIMAL_STG" NUMBER, 
	"MAXINS_STG" NUMBER, 
	"FRLINS_STG" NUMBER, 
	"FLAGS_STG" NUMBER, 
	"BFP_STG" NUMBER, 
	"ENC_STG" NUMBER, 
	"CMPFLAG_STG" NUMBER, 
	"CMPLVL_STG" NUMBER, 
	"IMCFLAG_STG" NUMBER, 
	"CCFLAG_STG" NUMBER, 
	"FLAGS2_STG" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
