--------------------------------------------------------
--  DDL for Table DEFSUBPART$
--------------------------------------------------------

  CREATE TABLE "SYS"."DEFSUBPART$" SHARING=METADATA 
   (	"BO#" NUMBER, 
	"SPART_POSITION" NUMBER, 
	"SPART_NAME" VARCHAR2(132 BYTE), 
	"TS#" NUMBER, 
	"FLAGS" NUMBER, 
	"HIBOUNDLEN" NUMBER, 
	"HIBOUNDVAL" LONG, 
	"BHIBOUNDVAL" BLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("BHIBOUNDVAL") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
