--------------------------------------------------------
--  DDL for Trigger DELETE_ENTRIES
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYS"."DELETE_ENTRIES" 
AFTER DROP ON DATABASE
BEGIN
  IF (ORA_DICT_OBJ_TYPE = 'USER') THEN
    DELETE FROM SYSTEM.SQLPLUS_PRODUCT_PROFILE
    WHERE USERID = ORA_DICT_OBJ_NAME;
  END IF;

 EXCEPTION WHEN OTHERS THEN
  IF (SQLCODE = -4043) OR (SQLCODE = -1031) THEN
     NULL;
  ELSE
     RAISE;
  END IF;
END;
/
ALTER TRIGGER "SYS"."DELETE_ENTRIES" ENABLE;
