--------------------------------------------------------
--  Constraints for Table DEPENDENCY$
--------------------------------------------------------

  ALTER TABLE "SYS"."DEPENDENCY$" MODIFY ("D_OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DEPENDENCY$" MODIFY ("D_TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DEPENDENCY$" MODIFY ("ORDER#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DEPENDENCY$" MODIFY ("P_OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DEPENDENCY$" MODIFY ("P_TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE "SYS"."DEPENDENCY$" MODIFY ("PROPERTY" NOT NULL ENABLE);
