--------------------------------------------------------
--  DDL for Table DEPENDENCY$
--------------------------------------------------------

  CREATE TABLE "SYS"."DEPENDENCY$" SHARING=METADATA 
   (	"D_OBJ#" NUMBER, 
	"D_TIMESTAMP" DATE, 
	"ORDER#" NUMBER, 
	"P_OBJ#" NUMBER, 
	"P_TIMESTAMP" DATE, 
	"D_OWNER#" NUMBER, 
	"PROPERTY" NUMBER, 
	"D_ATTRS" RAW(2000), 
	"D_REASON" RAW(2000)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16384 NEXT 106496 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
