--------------------------------------------------------
--  DDL for Table DIMJOINKEY$
--------------------------------------------------------

  CREATE TABLE "SYS"."DIMJOINKEY$" SHARING=METADATA 
   (	"DIMOBJ#" NUMBER, 
	"JOINKEYID#" NUMBER, 
	"KEYPOS#" NUMBER, 
	"HIERID#" NUMBER, 
	"LEVELID#" NUMBER, 
	"DETAILOBJ#" NUMBER, 
	"COL#" NUMBER, 
	"CHDLEVID#" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
