--------------------------------------------------------
--  DDL for Table DIR$SERVICE_ATTRIBUTES
--------------------------------------------------------

  CREATE TABLE "SYS"."DIR$SERVICE_ATTRIBUTES" SHARING=METADATA 
   (	"SERVICE_ID" NUMBER, 
	"ATTRIBUTE_NAME" VARCHAR2(128 BYTE), 
	"ATTRIBUTE_VALUE" VARCHAR2(4000 BYTE), 
	"SPAREN1" NUMBER, 
	"SPAREN2" NUMBER, 
	"SPAREN3" NUMBER, 
	"SPAREN4" NUMBER, 
	"SPAREN5" NUMBER, 
	"SPAREVC1" VARCHAR2(4000 BYTE), 
	"SPAREVC2" VARCHAR2(4000 BYTE), 
	"SPAREVC3" VARCHAR2(4000 BYTE), 
	"SPAREVC4" VARCHAR2(4000 BYTE), 
	"SPAREVC5" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
