--------------------------------------------------------
--  DDL for Table DIR$VICTIM_POLICY
--------------------------------------------------------

  CREATE TABLE "SYS"."DIR$VICTIM_POLICY" SHARING=METADATA 
   (	"USER_NAME" VARCHAR2(128 BYTE), 
	"POLICY_FUNCTION_NAME" VARCHAR2(98 BYTE), 
	"VERSION" NUMBER, 
	"SPAREN1" NUMBER, 
	"SPAREN2" NUMBER, 
	"SPAREN3" NUMBER, 
	"SPAREN4" NUMBER, 
	"SPAREN5" NUMBER, 
	"SPAREN6" NUMBER, 
	"SPAREN7" NUMBER, 
	"SPAREVC1" VARCHAR2(4000 BYTE), 
	"SPAREVC2" VARCHAR2(4000 BYTE), 
	"SPAREVC3" VARCHAR2(4000 BYTE), 
	"SPAREVC4" VARCHAR2(4000 BYTE), 
	"SPAREVC5" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
