--------------------------------------------------------
--  DDL for Table DIR$MIGRATE_OPERATIONS
--------------------------------------------------------

  CREATE TABLE "SYS"."DIR$MIGRATE_OPERATIONS" SHARING=METADATA 
   (	"JOB_NAME" VARCHAR2(100 BYTE), 
	"ALERT_SEQ_ID" NUMBER, 
	"INCARNATION_INFO" VARCHAR2(4000 BYTE), 
	"SERVICE_NAME" VARCHAR2(4000 BYTE), 
	"SOURCE_INSTANCE" VARCHAR2(4000 BYTE), 
	"DEST_INSTANCE" VARCHAR2(4000 BYTE), 
	"SESSION_COUNT" NUMBER, 
	"DIRECTOR_FACTOR" NUMBER, 
	"SUBMIT_TIME" DATE, 
	"STATUS" NUMBER, 
	"START_TIME" DATE, 
	"END_TIME" DATE, 
	"ACTUAL_COUNT" NUMBER, 
	"ERROR_MESSAGE" VARCHAR2(4000 BYTE), 
	"SPAREN1" NUMBER, 
	"SPAREN2" NUMBER, 
	"SPAREN3" NUMBER, 
	"SPAREN4" NUMBER, 
	"SPAREN5" NUMBER, 
	"SPAREVC1" VARCHAR2(4000 BYTE), 
	"SPAREVC2" VARCHAR2(4000 BYTE), 
	"SPAREVC3" VARCHAR2(4000 BYTE), 
	"SPAREVC4" VARCHAR2(4000 BYTE), 
	"SPAREVC5" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
