--------------------------------------------------------
--  DDL for Table DIR$INSTANCE_ACTIONS
--------------------------------------------------------

  CREATE TABLE "SYS"."DIR$INSTANCE_ACTIONS" SHARING=METADATA 
   (	"JOB_NAME" VARCHAR2(100 BYTE), 
	"ACTION_TYPE" NUMBER, 
	"INSTANCE_NAME" VARCHAR2(4000 BYTE), 
	"SUBMIT_TIME" DATE, 
	"START_TIME" DATE, 
	"END_TIME" DATE, 
	"ERROR_MESSAGE" VARCHAR2(4000 BYTE), 
	"SPAREN1" NUMBER, 
	"SPAREN2" NUMBER, 
	"SPAREN3" NUMBER, 
	"SPAREN4" NUMBER, 
	"SPAREN5" NUMBER, 
	"SPAREVC1" VARCHAR2(4000 BYTE), 
	"SPAREVC2" VARCHAR2(4000 BYTE), 
	"SPAREVC3" VARCHAR2(4000 BYTE), 
	"SPAREVC4" VARCHAR2(4000 BYTE), 
	"SPAREVC5" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
