--------------------------------------------------------
--  DDL for Table DIR$RESONATE_OPERATIONS
--------------------------------------------------------

  CREATE TABLE "SYS"."DIR$RESONATE_OPERATIONS" SHARING=METADATA 
   (	"JOB_NAME" VARCHAR2(100 BYTE), 
	"ALERT_NAME" VARCHAR2(200 BYTE), 
	"JOB_TYPE" NUMBER, 
	"INCARNATION_INFO" VARCHAR2(4000 BYTE), 
	"DATABASE_NAME" VARCHAR2(128 BYTE), 
	"INSTANCE_NAME" VARCHAR2(4000 BYTE), 
	"NODE_NAME" VARCHAR2(4000 BYTE), 
	"SUBMIT_TIME" DATE, 
	"STATUS" NUMBER, 
	"START_TIME" DATE, 
	"END_TIME" DATE, 
	"ERROR_MESSAGE" VARCHAR2(4000 BYTE), 
	"PRIORITY" NUMBER, 
	"SPAREN1" NUMBER, 
	"SPAREN2" NUMBER, 
	"SPAREN3" NUMBER, 
	"SPAREN4" NUMBER, 
	"SPAREN5" NUMBER, 
	"SPAREVC1" VARCHAR2(4000 BYTE), 
	"SPAREVC2" VARCHAR2(4000 BYTE), 
	"SPAREVC3" VARCHAR2(4000 BYTE), 
	"SPAREVC4" VARCHAR2(4000 BYTE), 
	"SPAREVC5" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
