--------------------------------------------------------
--  DDL for Table DUAL
--------------------------------------------------------

  CREATE TABLE "SYS"."DUAL" SHARING=METADATA 
   (	"DUMMY" VARCHAR2(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16384 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  GRANT SELECT ON "SYS"."DUAL" TO PUBLIC WITH GRANT OPTION;
  GRANT READ ON "SYS"."DUAL" TO "DVSYS";
