--------------------------------------------------------
--  DDL for Table DUC$
--------------------------------------------------------

  CREATE TABLE "SYS"."DUC$" SHARING=METADATA 
   (	"OWNER" VARCHAR2(128 BYTE), 
	"PACK" VARCHAR2(128 BYTE), 
	"PROC" VARCHAR2(128 BYTE), 
	"FIELD1" NUMBER DEFAULT 0, 
	"OPERATION#" NUMBER, 
	"SEQ" NUMBER, 
	"COM" VARCHAR2(80 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
