--------------------------------------------------------
--  DDL for Table EXP_HEAD$
--------------------------------------------------------

  CREATE TABLE "SYS"."EXP_HEAD$" SHARING=METADATA 
   (	"EXP_ID" NUMBER, 
	"OBJN" NUMBER, 
	"SUB_ID" NUMBER, 
	"FIXED_COST" NUMBER, 
	"TEXT" VARCHAR2(4000 BYTE), 
	"COL_LIST" VARCHAR2(4000 BYTE), 
	"FLAGS" NUMBER, 
	"CTIME" DATE
   ) PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE ROW MOVEMENT ;
