--------------------------------------------------------
--  Constraints for Table EXPACT$
--------------------------------------------------------

  ALTER TABLE "SYS"."EXPACT$" MODIFY ("OWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."EXPACT$" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."EXPACT$" MODIFY ("FUNC_SCHEMA" NOT NULL ENABLE);
  ALTER TABLE "SYS"."EXPACT$" MODIFY ("FUNC_PACKAGE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."EXPACT$" MODIFY ("FUNC_PROC" NOT NULL ENABLE);
  ALTER TABLE "SYS"."EXPACT$" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."EXPACT$" MODIFY ("OBJ_TYPE" NOT NULL ENABLE);
