--------------------------------------------------------
--  DDL for Table EXPACT$
--------------------------------------------------------

  CREATE TABLE "SYS"."EXPACT$" SHARING=METADATA 
   (	"OWNER" VARCHAR2(128 BYTE), 
	"NAME" VARCHAR2(128 BYTE), 
	"FUNC_SCHEMA" VARCHAR2(128 BYTE), 
	"FUNC_PACKAGE" VARCHAR2(128 BYTE), 
	"FUNC_PROC" VARCHAR2(128 BYTE), 
	"CODE" NUMBER, 
	"CALLORDER" NUMBER, 
	"CALLARG" VARCHAR2(1 BYTE), 
	"OBJ_TYPE" NUMBER, 
	"USER_ARG" VARCHAR2(2000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
