--------------------------------------------------------
--  DDL for Table EXPDEPOBJ$
--------------------------------------------------------

  CREATE TABLE "SYS"."EXPDEPOBJ$" SHARING=METADATA 
   (	"D_OBJ#" NUMBER, 
	"P_OBJ#" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  GRANT INSERT ON "SYS"."EXPDEPOBJ$" TO "ORDSYS";
  GRANT DELETE ON "SYS"."EXPDEPOBJ$" TO "ORDSYS";
