--------------------------------------------------------
--  DDL for Table EXPIMP_TTS_CT$
--------------------------------------------------------

  CREATE TABLE "SYS"."EXPIMP_TTS_CT$" SHARING=METADATA 
   (	"OWNER" VARCHAR2(128 BYTE), 
	"TABLENAME" VARCHAR2(128 BYTE), 
	"XMLINFO" CLOB, 
	"WHEN" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("XMLINFO") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
  GRANT DELETE ON "SYS"."EXPIMP_TTS_CT$" TO "IMP_FULL_DATABASE";
  GRANT INSERT ON "SYS"."EXPIMP_TTS_CT$" TO "IMP_FULL_DATABASE";
  GRANT SELECT ON "SYS"."EXPIMP_TTS_CT$" TO "IMP_FULL_DATABASE";
  GRANT UPDATE ON "SYS"."EXPIMP_TTS_CT$" TO "IMP_FULL_DATABASE";
