--------------------------------------------------------
--  DDL for Table EXPPKGACT$
--------------------------------------------------------

  CREATE TABLE "SYS"."EXPPKGACT$" SHARING=METADATA 
   (	"PACKAGE" VARCHAR2(128 BYTE), 
	"SCHEMA" VARCHAR2(128 BYTE), 
	"CLASS" NUMBER, 
	"LEVEL#" NUMBER DEFAULT 1000
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  GRANT INSERT ON "SYS"."EXPPKGACT$" TO "ORDSYS";
  GRANT DELETE ON "SYS"."EXPPKGACT$" TO "ORDSYS";
