REM INSERTING into SYS.EXTERNAL_TAB$
SET DEFINE OFF;
Insert into SYS.EXTERNAL_TAB$ (OBJ#,DEFAULT_DIR,TYPE$,NR_LOCATIONS,REJECT_LIMIT,PAR_TYPE,PROPERTY) values (10462,'OPATCH_SCRIPT_DIR','ORACLE_LOADER',1,2147483647,2,1);
