--------------------------------------------------------
--  Constraints for Table EXTERNAL_TAB$
--------------------------------------------------------

  ALTER TABLE "SYS"."EXTERNAL_TAB$" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."EXTERNAL_TAB$" MODIFY ("NR_LOCATIONS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."EXTERNAL_TAB$" MODIFY ("REJECT_LIMIT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."EXTERNAL_TAB$" MODIFY ("PAR_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."EXTERNAL_TAB$" MODIFY ("PROPERTY" NOT NULL ENABLE);
