--------------------------------------------------------
--  DDL for Table EXTERNAL_SCN_ACTIVITY$
--------------------------------------------------------

  CREATE TABLE "SYS"."EXTERNAL_SCN_ACTIVITY$" SHARING=METADATA 
   (	"OPERATION_TIMESTAMP" TIMESTAMP (6), 
	"SESSION_ID" NUMBER, 
	"SESSION_SERIAL#" NUMBER, 
	"AUDIT_SESSIONID" NUMBER, 
	"USERNAME" VARCHAR2(128 BYTE), 
	"INBOUND_DB_LINK_SOURCE_ID" NUMBER, 
	"OUTBOUND_DB_LINK_NAME" VARCHAR2(128 BYTE), 
	"OUTBOUND_DB_LINK_OWNER" VARCHAR2(128 BYTE), 
	"RESULT" VARCHAR2(64 BYTE), 
	"EXTERNAL_SCN" NUMBER, 
	"SCN_ADJUSTMENT" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
