--------------------------------------------------------
--  DDL for Table EXTERNAL_LOCATION$
--------------------------------------------------------

  CREATE TABLE "SYS"."EXTERNAL_LOCATION$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"POSITION" NUMBER, 
	"DIR" VARCHAR2(128 BYTE), 
	"NAME" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
