--------------------------------------------------------
--  DDL for Table FED$BINDS
--------------------------------------------------------

  CREATE TABLE "SYS"."FED$BINDS" SHARING=METADATA 
   (	"APPID#" NUMBER, 
	"SEQ#" NUMBER, 
	"INC#" NUMBER, 
	"BIND#" NUMBER, 
	"NAME" VARCHAR2(128 BYTE), 
	"DATATYPE#" NUMBER, 
	"VALUE" BLOB, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" VARCHAR2(1000 BYTE), 
	"SPARE5" VARCHAR2(1000 BYTE), 
	"SPARE6" DATE, 
	"SPARE7" BLOB, 
	"SPARE8" CLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("VALUE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("SPARE7") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("SPARE8") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
