--------------------------------------------------------
--  DDL for Table FED$EDITIONS
--------------------------------------------------------

  CREATE TABLE "SYS"."FED$EDITIONS" SHARING=METADATA 
   (	"APPID#" NUMBER, 
	"VER#" NUMBER, 
	"PATCH#" NUMBER, 
	"EDITION_NAME" VARCHAR2(128 BYTE), 
	"EDITION_SEQ" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" VARCHAR2(1000 BYTE), 
	"SPARE5" VARCHAR2(1000 BYTE), 
	"SPARE6" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
