--------------------------------------------------------
--  DDL for Table FED$APPS
--------------------------------------------------------

  CREATE TABLE "SYS"."FED$APPS" SHARING=METADATA 
   (	"APP_NAME" VARCHAR2(128 BYTE), 
	"APPID#" NUMBER, 
	"VER#" NUMBER, 
	"APP_STATUS" NUMBER, 
	"FLAG" NUMBER, 
	"SRVN" VARCHAR2(64 BYTE), 
	"MODN" VARCHAR2(64 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" VARCHAR2(1000 BYTE), 
	"SPARE5" VARCHAR2(1000 BYTE), 
	"SPARE6" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
