--------------------------------------------------------
--  DDL for Table FED$STATEMENT$ERRORS
--------------------------------------------------------

  CREATE TABLE "SYS"."FED$STATEMENT$ERRORS" SHARING=METADATA 
   (	"APPID#" NUMBER, 
	"SEQ#" NUMBER, 
	"ERRORNUM" NUMBER, 
	"ERRORMSG" VARCHAR2(4000 BYTE), 
	"STIME" DATE, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" VARCHAR2(1000 BYTE), 
	"SPARE5" VARCHAR2(1000 BYTE), 
	"SPARE6" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
