--------------------------------------------------------
--  DDL for Table FED$VERSIONS
--------------------------------------------------------

  CREATE TABLE "SYS"."FED$VERSIONS" SHARING=METADATA 
   (	"APPID#" NUMBER, 
	"VER#" NUMBER, 
	"TGTVER" VARCHAR2(30 BYTE), 
	"ROOT_CLONE_CON_UID#" NUMBER, 
	"CMNT" VARCHAR2(4000 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" VARCHAR2(1000 BYTE), 
	"SPARE5" VARCHAR2(1000 BYTE), 
	"SPARE6" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
