--------------------------------------------------------
--  DDL for Table FED$PATCHES
--------------------------------------------------------

  CREATE TABLE "SYS"."FED$PATCHES" SHARING=METADATA 
   (	"APPID#" NUMBER, 
	"PATCH#" NUMBER, 
	"MINVER#" NUMBER, 
	"STATUS" NUMBER, 
	"CMNT" VARCHAR2(4000 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" VARCHAR2(1000 BYTE), 
	"SPARE5" VARCHAR2(1000 BYTE), 
	"SPARE6" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
