--------------------------------------------------------
--  DDL for Table FGA$
--------------------------------------------------------

  CREATE TABLE "SYS"."FGA$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"PNAME" VARCHAR2(128 BYTE), 
	"PTXT" VARCHAR2(4000 BYTE), 
	"PFSCHMA" VARCHAR2(128 BYTE), 
	"PPNAME" VARCHAR2(128 BYTE), 
	"PFNAME" VARCHAR2(128 BYTE), 
	"PCOL" VARCHAR2(128 BYTE), 
	"ENABLE_FLAG" NUMBER, 
	"STMT_TYPE" NUMBER DEFAULT 1, 
	"POWNER#" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
