--------------------------------------------------------
--  DDL for Table FGA_LOG$
--------------------------------------------------------

  CREATE TABLE "SYS"."FGA_LOG$" SHARING=METADATA 
   (	"SESSIONID" NUMBER, 
	"TIMESTAMP#" DATE, 
	"DBUID" VARCHAR2(128 BYTE), 
	"OSUID" VARCHAR2(255 BYTE), 
	"OSHST" VARCHAR2(128 BYTE), 
	"CLIENTID" VARCHAR2(128 BYTE), 
	"EXTID" VARCHAR2(4000 BYTE), 
	"OBJ$SCHEMA" VARCHAR2(128 BYTE), 
	"OBJ$NAME" VARCHAR2(128 BYTE), 
	"POLICYNAME" VARCHAR2(128 BYTE), 
	"SCN" NUMBER, 
	"SQLTEXT" VARCHAR2(4000 BYTE), 
	"LSQLTEXT" CLOB, 
	"SQLBIND" VARCHAR2(4000 BYTE), 
	"COMMENT$TEXT" VARCHAR2(4000 BYTE), 
	"PLHOL" LONG, 
	"STMT_TYPE" NUMBER, 
	"NTIMESTAMP#" TIMESTAMP (6), 
	"PROXY$SID" NUMBER, 
	"USER$GUID" VARCHAR2(32 BYTE), 
	"INSTANCE#" NUMBER, 
	"PROCESS#" VARCHAR2(16 BYTE), 
	"XID" RAW(8), 
	"AUDITID" VARCHAR2(64 BYTE), 
	"STATEMENT" NUMBER, 
	"ENTRYID" NUMBER, 
	"DBID" NUMBER, 
	"LSQLBIND" CLOB, 
	"OBJ$EDITION" VARCHAR2(128 BYTE), 
	"RLS$INFO" CLOB, 
	"CURRENT_USER" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("LSQLTEXT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("LSQLBIND") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("RLS$INFO") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
