--------------------------------------------------------
--  Constraints for Table FGR$_FILE_GROUP_VERSIONS
--------------------------------------------------------

  ALTER TABLE "SYS"."FGR$_FILE_GROUP_VERSIONS" MODIFY ("VERSION_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."FGR$_FILE_GROUP_VERSIONS" MODIFY ("FILE_GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."FGR$_FILE_GROUP_VERSIONS" MODIFY ("CREATOR" NOT NULL ENABLE);
  ALTER TABLE "SYS"."FGR$_FILE_GROUP_VERSIONS" MODIFY ("CREATION_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."FGR$_FILE_GROUP_VERSIONS" MODIFY ("VERSION_GUID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."FGR$_FILE_GROUP_VERSIONS" MODIFY ("VERSION_NAME" NOT NULL ENABLE);
