--------------------------------------------------------
--  DDL for Table FGR$_FILE_GROUP_VERSIONS
--------------------------------------------------------

  CREATE TABLE "SYS"."FGR$_FILE_GROUP_VERSIONS" SHARING=METADATA 
   (	"VERSION_ID" NUMBER, 
	"FILE_GROUP_ID" NUMBER, 
	"CREATOR" VARCHAR2(128 BYTE), 
	"CREATION_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"VERSION_GUID" RAW(16), 
	"VERSION_NAME" VARCHAR2(128 BYTE), 
	"USER_COMMENT" VARCHAR2(4000 BYTE), 
	"DEFAULT_DIR_OBJ" VARCHAR2(128 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(128 BYTE), 
	"SPARE4" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
