--------------------------------------------------------
--  Constraints for Table FGR$_FILE_GROUP_EXPORT_INFO
--------------------------------------------------------

  ALTER TABLE "SYS"."FGR$_FILE_GROUP_EXPORT_INFO" MODIFY ("VERSION_GUID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."FGR$_FILE_GROUP_EXPORT_INFO" MODIFY ("EXPORT_VERSION" NOT NULL ENABLE);
  ALTER TABLE "SYS"."FGR$_FILE_GROUP_EXPORT_INFO" MODIFY ("EXPORT_PLATFORM" NOT NULL ENABLE);
  ALTER TABLE "SYS"."FGR$_FILE_GROUP_EXPORT_INFO" MODIFY ("EXPORT_TIME" NOT NULL ENABLE);
