--------------------------------------------------------
--  Constraints for Table FGR$_FILE_GROUP_FILES
--------------------------------------------------------

  ALTER TABLE "SYS"."FGR$_FILE_GROUP_FILES" MODIFY ("FILE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."FGR$_FILE_GROUP_FILES" MODIFY ("CREATOR" NOT NULL ENABLE);
  ALTER TABLE "SYS"."FGR$_FILE_GROUP_FILES" MODIFY ("CREATION_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."FGR$_FILE_GROUP_FILES" MODIFY ("FILE_DIR_OBJ" NOT NULL ENABLE);
  ALTER TABLE "SYS"."FGR$_FILE_GROUP_FILES" MODIFY ("VERSION_GUID" NOT NULL ENABLE);
