--------------------------------------------------------
--  Constraints for Table FGR$_FILE_GROUPS
--------------------------------------------------------

  ALTER TABLE "SYS"."FGR$_FILE_GROUPS" MODIFY ("FILE_GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."FGR$_FILE_GROUPS" MODIFY ("KEEP_FILES" NOT NULL ENABLE);
  ALTER TABLE "SYS"."FGR$_FILE_GROUPS" MODIFY ("MIN_VERSIONS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."FGR$_FILE_GROUPS" MODIFY ("MAX_VERSIONS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."FGR$_FILE_GROUPS" MODIFY ("RETENTION_DAYS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."FGR$_FILE_GROUPS" MODIFY ("CREATOR" NOT NULL ENABLE);
  ALTER TABLE "SYS"."FGR$_FILE_GROUPS" MODIFY ("CREATION_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."FGR$_FILE_GROUPS" MODIFY ("SEQUENCE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."FGR$_FILE_GROUPS" MODIFY ("AUDIT$" NOT NULL ENABLE);
