--------------------------------------------------------
--  DDL for Table FGR$_FILE_GROUP_FILES
--------------------------------------------------------

  CREATE TABLE "SYS"."FGR$_FILE_GROUP_FILES" SHARING=METADATA 
   (	"FILE_NAME" VARCHAR2(512 BYTE), 
	"CREATOR" VARCHAR2(128 BYTE), 
	"CREATION_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"FILE_DIR_OBJ" VARCHAR2(128 BYTE), 
	"VERSION_GUID" RAW(16), 
	"FILE_SIZE" NUMBER, 
	"FILE_BLOCKSIZE" NUMBER, 
	"FILE_TYPE" VARCHAR2(130 BYTE), 
	"USER_COMMENT" VARCHAR2(4000 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(128 BYTE), 
	"SPARE4" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
