--------------------------------------------------------
--  DDL for Table FGR$_TABLE_INFO
--------------------------------------------------------

  CREATE TABLE "SYS"."FGR$_TABLE_INFO" SHARING=METADATA 
   (	"VERSION_GUID" RAW(16), 
	"SCHEMA_NAME" VARCHAR2(128 BYTE), 
	"TABLE_NAME" VARCHAR2(128 BYTE), 
	"TABLESPACE_NAME" VARCHAR2(30 BYTE), 
	"SCN" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(128 BYTE), 
	"SPARE4" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
