--------------------------------------------------------
--  DDL for Table FGR$_FILE_GROUPS
--------------------------------------------------------

  CREATE TABLE "SYS"."FGR$_FILE_GROUPS" SHARING=METADATA 
   (	"FILE_GROUP_ID" NUMBER, 
	"KEEP_FILES" VARCHAR2(1 BYTE), 
	"MIN_VERSIONS" NUMBER, 
	"MAX_VERSIONS" NUMBER, 
	"RETENTION_DAYS" NUMBER, 
	"CREATOR" VARCHAR2(128 BYTE), 
	"CREATION_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"SEQUENCE_NAME" VARCHAR2(128 BYTE), 
	"AUDIT$" VARCHAR2(38 BYTE), 
	"USER_COMMENT" VARCHAR2(4000 BYTE), 
	"DEFAULT_DIR_OBJ" VARCHAR2(128 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(128 BYTE), 
	"SPARE4" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
