--------------------------------------------------------
--  DDL for Table FGR$_FILE_GROUP_EXPORT_INFO
--------------------------------------------------------

  CREATE TABLE "SYS"."FGR$_FILE_GROUP_EXPORT_INFO" SHARING=METADATA 
   (	"VERSION_GUID" RAW(16), 
	"EXPORT_VERSION" VARCHAR2(128 BYTE), 
	"EXPORT_PLATFORM" VARCHAR2(101 BYTE), 
	"EXPORT_TIME" DATE, 
	"EXPORT_SCN" NUMBER, 
	"SOURCE_DB_NAME" VARCHAR2(128 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(128 BYTE), 
	"SPARE4" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
