--------------------------------------------------------
--  DDL for Table FILE$
--------------------------------------------------------

  CREATE TABLE "SYS"."FILE$" SHARING=METADATA 
   (	"FILE#" NUMBER, 
	"STATUS$" NUMBER, 
	"BLOCKS" NUMBER, 
	"TS#" NUMBER, 
	"RELFILE#" NUMBER, 
	"MAXEXTEND" NUMBER, 
	"INC" NUMBER, 
	"CRSCNWRP" NUMBER, 
	"CRSCNBAS" NUMBER, 
	"OWNERINSTANCE" VARCHAR2(30 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  GRANT READ ON "SYS"."FILE$" TO "SYSUMF_ROLE";
