--------------------------------------------------------
--  Constraints for Table GG$_PACKAGE_MAPPING
--------------------------------------------------------

  ALTER TABLE "SYS"."GG$_PACKAGE_MAPPING" MODIFY ("EXT_PACKAGE_OWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."GG$_PACKAGE_MAPPING" MODIFY ("EXT_PACKAGE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."GG$_PACKAGE_MAPPING" MODIFY ("INT_PACKAGE_OWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."GG$_PACKAGE_MAPPING" MODIFY ("INT_PACKAGE_NAME" NOT NULL ENABLE);
