--------------------------------------------------------
--  DDL for Table GG$_PROC_OBJECT_EXCLUSION
--------------------------------------------------------

  CREATE TABLE "SYS"."GG$_PROC_OBJECT_EXCLUSION" SHARING=METADATA 
   (	"PACKAGE_OWNER" VARCHAR2(384 BYTE) DEFAULT '*', 
	"PACKAGE_NAME" VARCHAR2(384 BYTE) DEFAULT '*', 
	"PROCEDURE_NAME" VARCHAR2(384 BYTE) DEFAULT '*', 
	"OBJECT_OWNER" VARCHAR2(384 BYTE) DEFAULT '*', 
	"OBJECT_NAME" VARCHAR2(384 BYTE) DEFAULT '*', 
	"SPARE1" NUMBER DEFAULT NULL, 
	"SPARE2" NUMBER DEFAULT NULL, 
	"SPARE3" VARCHAR2(4000 BYTE) DEFAULT NULL, 
	"SPARE4" VARCHAR2(4000 BYTE) DEFAULT NULL, 
	"SPARE5" TIMESTAMP (6) DEFAULT NULL
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
