--------------------------------------------------------
--  Constraints for Table GG$_PROCEDURE_ANNOTATION
--------------------------------------------------------

  ALTER TABLE "SYS"."GG$_PROCEDURE_ANNOTATION" MODIFY ("PACKAGE_OWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."GG$_PROCEDURE_ANNOTATION" MODIFY ("PACKAGE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."GG$_PROCEDURE_ANNOTATION" MODIFY ("PROCEDURE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."GG$_PROCEDURE_ANNOTATION" MODIFY ("OBJECT_OWNER_ARGPOS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."GG$_PROCEDURE_ANNOTATION" MODIFY ("OBJECT_ARGPOS" NOT NULL ENABLE);
