REM INSERTING into SYS.GG$_PROC_OBJECT_EXCLUSION
SET DEFINE OFF;
Insert into SYS.GG$_PROC_OBJECT_EXCLUSION (PACKAGE_OWNER,PACKAGE_NAME,PROCEDURE_NAME,OBJECT_OWNER,OBJECT_NAME,SPARE1,SPARE2,SPARE3,SPARE4,SPARE5) values ('SYS','DBMS_REDEFINITION','*','SYS','*',null,null,null,null,null);
Insert into SYS.GG$_PROC_OBJECT_EXCLUSION (PACKAGE_OWNER,PACKAGE_NAME,PROCEDURE_NAME,OBJECT_OWNER,OBJECT_NAME,SPARE1,SPARE2,SPARE3,SPARE4,SPARE5) values ('SYS','DBMS_FGA','*','SYS','*',null,null,null,null,null);
Insert into SYS.GG$_PROC_OBJECT_EXCLUSION (PACKAGE_OWNER,PACKAGE_NAME,PROCEDURE_NAME,OBJECT_OWNER,OBJECT_NAME,SPARE1,SPARE2,SPARE3,SPARE4,SPARE5) values ('SYS','DBMS_RLS_INT','*','SYS','*',null,null,null,null,null);
Insert into SYS.GG$_PROC_OBJECT_EXCLUSION (PACKAGE_OWNER,PACKAGE_NAME,PROCEDURE_NAME,OBJECT_OWNER,OBJECT_NAME,SPARE1,SPARE2,SPARE3,SPARE4,SPARE5) values ('SYS','DBMS_REDACT','*','SYS','*',null,null,null,null,null);
Insert into SYS.GG$_PROC_OBJECT_EXCLUSION (PACKAGE_OWNER,PACKAGE_NAME,PROCEDURE_NAME,OBJECT_OWNER,OBJECT_NAME,SPARE1,SPARE2,SPARE3,SPARE4,SPARE5) values ('SYS','DBMS_DDL','*','SYS','*',null,null,null,null,null);
