--------------------------------------------------------
--  DDL for Table GG$_PACKAGE_MAPPING
--------------------------------------------------------

  CREATE TABLE "SYS"."GG$_PACKAGE_MAPPING" SHARING=METADATA 
   (	"EXT_PACKAGE_OWNER" VARCHAR2(384 BYTE), 
	"EXT_PACKAGE_NAME" VARCHAR2(384 BYTE), 
	"EXT_PROCEDURE_NAME" VARCHAR2(384 BYTE) DEFAULT NULL, 
	"INT_PACKAGE_OWNER" VARCHAR2(384 BYTE), 
	"INT_PACKAGE_NAME" VARCHAR2(384 BYTE), 
	"INT_PROCEDURE_NAME" VARCHAR2(384 BYTE) DEFAULT NULL, 
	"SPARE1" NUMBER DEFAULT NULL, 
	"SPARE2" NUMBER DEFAULT NULL, 
	"SPARE3" VARCHAR2(4000 BYTE) DEFAULT NULL, 
	"SPARE4" VARCHAR2(4000 BYTE) DEFAULT NULL, 
	"SPARE5" TIMESTAMP (6) DEFAULT NULL
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
