--------------------------------------------------------
--  DDL for Table GOLDENGATE$_CONTAINER_RULES
--------------------------------------------------------

  CREATE TABLE "SYS"."GOLDENGATE$_CONTAINER_RULES" SHARING=METADATA 
   (	"RULE#" NUMBER, 
	"CAPTURE_NAME" VARCHAR2(128 BYTE), 
	"FILTER_RULE" VARCHAR2(4000 BYTE), 
	"INCLUSION_RULE" NUMBER DEFAULT 1, 
	"ESCAPE_CHAR" VARCHAR2(1 BYTE) DEFAULT '\', 
	"FLAG" NUMBER DEFAULT 1, 
	"SPARE1" NUMBER DEFAULT null, 
	"SPARE2" VARCHAR2(2000 BYTE) DEFAULT null                 /* unused */
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
