--------------------------------------------------------
--  DDL for Table GOLDENGATE$_PRIVILEGES
--------------------------------------------------------

  CREATE TABLE "SYS"."GOLDENGATE$_PRIVILEGES" SHARING=METADATA 
   (	"USERNAME" VARCHAR2(128 BYTE), 
	"PRIVILEGE_TYPE" NUMBER, 
	"PRIVILEGE_LEVEL" NUMBER, 
	"CREATE_TIME" TIMESTAMP (6), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" TIMESTAMP (6), 
	"SPARE4" VARCHAR2(4000 BYTE), 
	"SPARE5" VARCHAR2(4000 BYTE), 
	"OPTIONAL_PRIV" VARCHAR2(4000 BYTE), 
	"ALLPDBS" NUMBER DEFAULT 0, 
	"C_INVOKER" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
