GRANT SELECT ON "SYS"."GV_$DG_BROKER_CONFIG" TO "SELECT_CATALOG_ROLE";
  GRANT SELECT ON "SYS"."GV_$DG_BROKER_CONFIG" TO "GSMUSER_ROLE";
  GRANT SELECT ON "SYS"."GV_$DG_BROKER_CONFIG" TO "GSMCATUSER";
