GRANT SELECT ON "SYS"."GV_$SESSION" TO "SELECT_CATALOG_ROLE";
  GRANT SELECT ON "SYS"."GV_$SESSION" TO "GSMUSER_ROLE";
  GRANT SELECT ON "SYS"."GV_$SESSION" TO "GSMADMIN_INTERNAL";
  GRANT SELECT ON "SYS"."GV_$SESSION" TO "LBACSYS";
  GRANT READ ON "SYS"."GV_$SESSION" TO "DVSYS";
  GRANT READ ON "SYS"."GV_$SESSION" TO "DV_SECANALYST";
