GRANT SELECT ON "SYS"."GV_$ACTIVE_SERVICES" TO "SELECT_CATALOG_ROLE";
  GRANT SELECT ON "SYS"."GV_$ACTIVE_SERVICES" TO "GSMUSER_ROLE";
  GRANT SELECT ON "SYS"."GV_$ACTIVE_SERVICES" TO "GSMADMIN_INTERNAL";
