--------------------------------------------------------
--  DDL for Table HCS_DIM$
--------------------------------------------------------

  CREATE TABLE "SYS"."HCS_DIM$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"DIM_TYPE" NUMBER(1,0), 
	"ALL_MEMBER_NAME" CLOB, 
	"ALL_MEMBER_CAPTION" CLOB, 
	"ALL_MEMBER_DESC" CLOB, 
	"AUDIT$" VARCHAR2(38 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("ALL_MEMBER_NAME") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("ALL_MEMBER_CAPTION") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("ALL_MEMBER_DESC") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
