--------------------------------------------------------
--  DDL for Table HCS_DIM_ATTR$
--------------------------------------------------------

  CREATE TABLE "SYS"."HCS_DIM_ATTR$" SHARING=METADATA 
   (	"DIM#" NUMBER, 
	"ATTR#" NUMBER, 
	"ATTR_NAME" VARCHAR2(128 BYTE), 
	"SRC_COL#" NUMBER, 
	"DATA_TYPE#" NUMBER, 
	"DATA_LENGTH" NUMBER, 
	"CHARSETFORM" NUMBER, 
	"CHARSETID" NUMBER, 
	"PRECISION#" NUMBER, 
	"SCALE" NUMBER, 
	"IS_NULL" NUMBER, 
	"PROPERTY" NUMBER, 
	"ORDER_NUM" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
