--------------------------------------------------------
--  Constraints for Table HCS_ANALYTIC_VIEW$
--------------------------------------------------------

  ALTER TABLE "SYS"."HCS_ANALYTIC_VIEW$" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_ANALYTIC_VIEW$" MODIFY ("DEFAULT_MEASURE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_ANALYTIC_VIEW$" MODIFY ("AUDIT$" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_ANALYTIC_VIEW$" MODIFY ("DEFAULT_AGGR" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_ANALYTIC_VIEW$" MODIFY ("VALIDATE_STATE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_ANALYTIC_VIEW$" MODIFY ("DYN_ALL_CACHE" NOT NULL ENABLE);
