--------------------------------------------------------
--  DDL for Table HCS_AV_MEAS$
--------------------------------------------------------

  CREATE TABLE "SYS"."HCS_AV_MEAS$" SHARING=METADATA 
   (	"AV#" NUMBER, 
	"MEAS#" NUMBER, 
	"MEAS_NAME" VARCHAR2(128 BYTE), 
	"MEAS_TYPE" NUMBER, 
	"SRC_COL#" NUMBER, 
	"AGGR" VARCHAR2(128 BYTE), 
	"EXPR" CLOB, 
	"ORDER_NUM" NUMBER, 
	"DATA_TYPE#" NUMBER, 
	"DATA_LENGTH" NUMBER, 
	"CHARSETFORM" NUMBER, 
	"CHARSETID" NUMBER, 
	"PRECISION#" NUMBER, 
	"SCALE" NUMBER, 
	"IS_NULL" NUMBER, 
	"PROPERTY" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("EXPR") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
