--------------------------------------------------------
--  DDL for Table HCS_CLSFCTN$
--------------------------------------------------------

  CREATE TABLE "SYS"."HCS_CLSFCTN$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"SUB_OBJ#" NUMBER, 
	"OBJ_TYPE" NUMBER, 
	"CLSFCTION_NAME" VARCHAR2(128 BYTE), 
	"CLSFCTION_LANG" VARCHAR2(64 BYTE), 
	"CLSFCTION_VALUE" CLOB, 
	"ORDER_NUM" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("CLSFCTION_VALUE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
