--------------------------------------------------------
--  DDL for Table HCS_HIER_COL$
--------------------------------------------------------

  CREATE TABLE "SYS"."HCS_HIER_COL$" SHARING=METADATA 
   (	"HIER#" NUMBER, 
	"COL_NAME" VARCHAR2(128 BYTE), 
	"ROLE" NUMBER, 
	"ORDER_NUM" NUMBER, 
	"DATA_TYPE#" NUMBER, 
	"DATA_LENGTH" NUMBER, 
	"CHARSETFORM" NUMBER, 
	"CHARSETID" NUMBER, 
	"PRECISION#" NUMBER, 
	"SCALE" NUMBER, 
	"IS_NULL" NUMBER, 
	"PROPERTY" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
