--------------------------------------------------------
--  DDL for Table HCS_DIM_JOIN_PATH$
--------------------------------------------------------

  CREATE TABLE "SYS"."HCS_DIM_JOIN_PATH$" SHARING=METADATA 
   (	"DIM#" NUMBER, 
	"JOINPATH#" NUMBER, 
	"JOIN_PATH_NAME" VARCHAR2(128 BYTE), 
	"ORDER_NUM" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
