--------------------------------------------------------
--  Constraints for Table HCS_AV_COL$
--------------------------------------------------------

  ALTER TABLE "SYS"."HCS_AV_COL$" MODIFY ("AV#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_AV_COL$" MODIFY ("SUB_OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_AV_COL$" MODIFY ("SUB_OBJ_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_AV_COL$" MODIFY ("COL_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_AV_COL$" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_AV_COL$" MODIFY ("ORDER_NUM" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_AV_COL$" MODIFY ("DATA_TYPE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_AV_COL$" MODIFY ("DATA_LENGTH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_AV_COL$" MODIFY ("IS_NULL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_AV_COL$" MODIFY ("PROPERTY" NOT NULL ENABLE);
