--------------------------------------------------------
--  Constraints for Table HCS_DIM_ATTR$
--------------------------------------------------------

  ALTER TABLE "SYS"."HCS_DIM_ATTR$" MODIFY ("DIM#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_DIM_ATTR$" MODIFY ("ATTR#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_DIM_ATTR$" MODIFY ("SRC_COL#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_DIM_ATTR$" MODIFY ("DATA_TYPE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_DIM_ATTR$" MODIFY ("DATA_LENGTH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_DIM_ATTR$" MODIFY ("IS_NULL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_DIM_ATTR$" MODIFY ("PROPERTY" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_DIM_ATTR$" MODIFY ("ORDER_NUM" NOT NULL ENABLE);
