--------------------------------------------------------
--  DDL for Table HCS_JOIN_COND_ELEM$
--------------------------------------------------------

  CREATE TABLE "SYS"."HCS_JOIN_COND_ELEM$" SHARING=METADATA 
   (	"DIM#" NUMBER, 
	"JOINPATH#" NUMBER, 
	"LHS_SRC_COL#" NUMBER, 
	"RHS_SRC_COL#" NUMBER, 
	"ORDER_NUM" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
