--------------------------------------------------------
--  Constraints for Table HCS_AV_DIM$
--------------------------------------------------------

  ALTER TABLE "SYS"."HCS_AV_DIM$" MODIFY ("AV#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_AV_DIM$" MODIFY ("AV_DIM#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_AV_DIM$" MODIFY ("DIM_OWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_AV_DIM$" MODIFY ("OWNER_IN_DDL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_AV_DIM$" MODIFY ("DIM_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_AV_DIM$" MODIFY ("ORDER_NUM" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_AV_DIM$" MODIFY ("REF_DISTINCT" NOT NULL ENABLE);
