--------------------------------------------------------
--  Constraints for Table HCS_HIER_ATTR$
--------------------------------------------------------

  ALTER TABLE "SYS"."HCS_HIER_ATTR$" MODIFY ("HIER#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_HIER_ATTR$" MODIFY ("ATTR#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_HIER_ATTR$" MODIFY ("DATA_TYPE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_HIER_ATTR$" MODIFY ("DATA_LENGTH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_HIER_ATTR$" MODIFY ("IS_NULL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_HIER_ATTR$" MODIFY ("PROPERTY" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_HIER_ATTR$" MODIFY ("IS_SYS_EXPR" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_HIER_ATTR$" MODIFY ("ORDER_NUM" NOT NULL ENABLE);
