--------------------------------------------------------
--  DDL for Table HCS_MEASLST_MEASURES$
--------------------------------------------------------

  CREATE TABLE "SYS"."HCS_MEASLST_MEASURES$" SHARING=METADATA 
   (	"AV#" NUMBER, 
	"MEASLST#" NUMBER, 
	"MEAS_NAME" VARCHAR2(128 BYTE), 
	"ORDER_NUM" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" VARCHAR2(1000 BYTE), 
	"SPARE5" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
