--------------------------------------------------------
--  DDL for Table HCS_DIM_LVL$
--------------------------------------------------------

  CREATE TABLE "SYS"."HCS_DIM_LVL$" SHARING=METADATA 
   (	"DIM#" NUMBER, 
	"LVL#" NUMBER, 
	"LVL_NAME" VARCHAR2(128 BYTE), 
	"MEMBER_NAME" CLOB, 
	"MEMBER_CAPTION" CLOB, 
	"MEMBER_DESC" CLOB, 
	"SKIP_WHEN_NULL" NUMBER(1,0), 
	"LVL_TYPE" NUMBER, 
	"ORDER_NUM" NUMBER, 
	"IS_PC" NUMBER(1,0), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("MEMBER_NAME") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("MEMBER_CAPTION") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("MEMBER_DESC") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
