--------------------------------------------------------
--  Constraints for Table HCS_DIM_LVL_KEY_ATTR$
--------------------------------------------------------

  ALTER TABLE "SYS"."HCS_DIM_LVL_KEY_ATTR$" MODIFY ("DIM#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_DIM_LVL_KEY_ATTR$" MODIFY ("LVL#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_DIM_LVL_KEY_ATTR$" MODIFY ("LVL_KEY#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_DIM_LVL_KEY_ATTR$" MODIFY ("ATTR#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_DIM_LVL_KEY_ATTR$" MODIFY ("ORDER_NUM" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_DIM_LVL_KEY_ATTR$" MODIFY ("IS_PC" NOT NULL ENABLE);
