--------------------------------------------------------
--  DDL for Table HCS_LVLGRP_LVLS$
--------------------------------------------------------

  CREATE TABLE "SYS"."HCS_LVLGRP_LVLS$" SHARING=METADATA 
   (	"AV#" NUMBER, 
	"LVLGRP#" NUMBER, 
	"DIM_ALIAS" VARCHAR2(128 BYTE), 
	"HIER_ALIAS" VARCHAR2(128 BYTE), 
	"LEVEL_NAME" VARCHAR2(128 BYTE), 
	"ORDER_NUM" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" VARCHAR2(1000 BYTE), 
	"SPARE5" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
