--------------------------------------------------------
--  Constraints for Table HCS_HIER_COL$
--------------------------------------------------------

  ALTER TABLE "SYS"."HCS_HIER_COL$" MODIFY ("HIER#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_HIER_COL$" MODIFY ("COL_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_HIER_COL$" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_HIER_COL$" MODIFY ("ORDER_NUM" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_HIER_COL$" MODIFY ("DATA_TYPE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_HIER_COL$" MODIFY ("DATA_LENGTH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_HIER_COL$" MODIFY ("IS_NULL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_HIER_COL$" MODIFY ("PROPERTY" NOT NULL ENABLE);
