--------------------------------------------------------
--  Constraints for Table HCS_HIERARCHY$
--------------------------------------------------------

  ALTER TABLE "SYS"."HCS_HIERARCHY$" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_HIERARCHY$" MODIFY ("DIM_OWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_HIERARCHY$" MODIFY ("OWNER_IN_DDL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_HIERARCHY$" MODIFY ("DIM_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_HIERARCHY$" MODIFY ("AUDIT$" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_HIERARCHY$" MODIFY ("VALIDATE_STATE" NOT NULL ENABLE);
