--------------------------------------------------------
--  DDL for Table HCS_ANALYTIC_VIEW$
--------------------------------------------------------

  CREATE TABLE "SYS"."HCS_ANALYTIC_VIEW$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"DEFAULT_MEASURE#" NUMBER, 
	"AUDIT$" VARCHAR2(38 BYTE), 
	"DEFAULT_AGGR" VARCHAR2(128 BYTE), 
	"VALIDATE_STATE" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" DATE, 
	"DYN_ALL_CACHE" NUMBER(1,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
