--------------------------------------------------------
--  DDL for Table HCS_HIERARCHY$
--------------------------------------------------------

  CREATE TABLE "SYS"."HCS_HIERARCHY$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"DIM_OWNER" VARCHAR2(128 BYTE), 
	"OWNER_IN_DDL" NUMBER(1,0), 
	"DIM_NAME" VARCHAR2(128 BYTE), 
	"AUDIT$" VARCHAR2(38 BYTE), 
	"PAR_ATTR_NAME" VARCHAR2(128 BYTE), 
	"MAX_DEPTH" NUMBER, 
	"VALIDATE_STATE" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
