--------------------------------------------------------
--  DDL for Table HCS_AV_HIER$
--------------------------------------------------------

  CREATE TABLE "SYS"."HCS_AV_HIER$" SHARING=METADATA 
   (	"AV#" NUMBER, 
	"AV_DIM#" NUMBER, 
	"HIER#" NUMBER, 
	"HIER_OWNER" VARCHAR2(128 BYTE), 
	"OWNER_IN_DDL" NUMBER(1,0), 
	"HIER_NAME" VARCHAR2(128 BYTE), 
	"HIER_ALIAS" VARCHAR2(128 BYTE), 
	"IS_DEFAULT" NUMBER(1,0), 
	"ORDER_NUM" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
