--------------------------------------------------------
--  Constraints for Table HCS_AV_HIER$
--------------------------------------------------------

  ALTER TABLE "SYS"."HCS_AV_HIER$" MODIFY ("AV#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_AV_HIER$" MODIFY ("AV_DIM#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_AV_HIER$" MODIFY ("HIER#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_AV_HIER$" MODIFY ("HIER_OWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_AV_HIER$" MODIFY ("OWNER_IN_DDL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_AV_HIER$" MODIFY ("HIER_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_AV_HIER$" MODIFY ("ORDER_NUM" NOT NULL ENABLE);
