--------------------------------------------------------
--  DDL for Table HCS_AV_DIM$
--------------------------------------------------------

  CREATE TABLE "SYS"."HCS_AV_DIM$" SHARING=METADATA 
   (	"AV#" NUMBER, 
	"AV_DIM#" NUMBER, 
	"DIM_OWNER" VARCHAR2(128 BYTE), 
	"OWNER_IN_DDL" NUMBER(1,0), 
	"DIM_NAME" VARCHAR2(128 BYTE), 
	"ALIAS" VARCHAR2(128 BYTE), 
	"DIM_TYPE" NUMBER(1,0), 
	"ALL_MEMBER_NAME" CLOB, 
	"ALL_MEMBER_CAPTION" CLOB, 
	"ALL_MEMBER_DESC" CLOB, 
	"ORDER_NUM" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" DATE, 
	"REF_DISTINCT" NUMBER(1,0) DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("ALL_MEMBER_NAME") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("ALL_MEMBER_CAPTION") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("ALL_MEMBER_DESC") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
