--------------------------------------------------------
--  Constraints for Table HCS_AV_MEAS$
--------------------------------------------------------

  ALTER TABLE "SYS"."HCS_AV_MEAS$" MODIFY ("AV#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_AV_MEAS$" MODIFY ("MEAS#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_AV_MEAS$" MODIFY ("ORDER_NUM" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_AV_MEAS$" MODIFY ("DATA_TYPE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_AV_MEAS$" MODIFY ("DATA_LENGTH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_AV_MEAS$" MODIFY ("IS_NULL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HCS_AV_MEAS$" MODIFY ("PROPERTY" NOT NULL ENABLE);
