--------------------------------------------------------
--  DDL for Table HCS_HIER_ATTR$
--------------------------------------------------------

  CREATE TABLE "SYS"."HCS_HIER_ATTR$" SHARING=METADATA 
   (	"HIER#" NUMBER, 
	"ATTR#" NUMBER, 
	"ATTR_NAME" VARCHAR2(128 BYTE), 
	"EXPR" CLOB, 
	"DATA_TYPE#" NUMBER, 
	"DATA_LENGTH" NUMBER, 
	"CHARSETFORM" NUMBER, 
	"CHARSETID" NUMBER, 
	"PRECISION#" NUMBER, 
	"SCALE" NUMBER, 
	"IS_NULL" NUMBER, 
	"PROPERTY" NUMBER, 
	"IS_SYS_EXPR" NUMBER(1,0), 
	"ORDER_NUM" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("EXPR") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
