REM INSERTING into SYS.HEAT_MAP_STAT$
SET DEFINE OFF;
Insert into SYS.HEAT_MAP_STAT$ (OBJ#,DATAOBJ#,TS#,TRACK_TIME,SEGMENT_ACCESS,FLAG,SPARE1,SPARE2,SPARE3,N_WRITE,N_FTS,N_LOOKUP,N_INSERT,N_UPDATE,N_DELETE,N_ROWSINS,N_ROWSUPD,N_ROWSDEL) values (-1,-1,-1,to_date('30-MAY-19','DD-MON-RR'),0,1,null,null,null,0,0,0,null,null,null,null,null,null);
