--------------------------------------------------------
--  Constraints for Table HS$_CLASS_CAPS
--------------------------------------------------------

  ALTER TABLE "SYS"."HS$_CLASS_CAPS" MODIFY ("FDS_CLASS_CAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HS$_CLASS_CAPS" MODIFY ("FDS_CLASS_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HS$_CLASS_CAPS" MODIFY ("CAP_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HS$_CLASS_CAPS" ADD CONSTRAINT "HS$_CLASS_CAPS_PK" PRIMARY KEY ("FDS_CLASS_CAP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYS"."HS$_CLASS_CAPS" ADD CONSTRAINT "HS$_CLASS_CAPS_UK1" UNIQUE ("FDS_CLASS_ID", "CAP_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
