--------------------------------------------------------
--  Constraints for Table HS$_FDS_CLASS_DATE
--------------------------------------------------------

  ALTER TABLE "SYS"."HS$_FDS_CLASS_DATE" MODIFY ("FDS_CLASS_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HS$_FDS_CLASS_DATE" ADD CONSTRAINT "HS$_FDS_CLASS_DATE_UK1" UNIQUE ("FDS_CLASS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
