--------------------------------------------------------
--  Constraints for Table HS$_BASE_DD
--------------------------------------------------------

  ALTER TABLE "SYS"."HS$_BASE_DD" MODIFY ("DD_TABLE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HS$_BASE_DD" MODIFY ("DD_TABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HS$_BASE_DD" ADD CONSTRAINT "HS$_BASE_DD_PK" PRIMARY KEY ("DD_TABLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYS"."HS$_BASE_DD" ADD CONSTRAINT "HS$_BASE_DD_UK1" UNIQUE ("DD_TABLE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
