--------------------------------------------------------
--  DDL for Table HS$_PARALLEL_METADATA
--------------------------------------------------------

  CREATE TABLE "SYS"."HS$_PARALLEL_METADATA" SHARING=METADATA 
   (	"DBLINK" VARCHAR2(128 BYTE), 
	"REMOTE_TABLE_NAME" VARCHAR2(128 BYTE), 
	"REMOTE_SCHEMA_NAME" VARCHAR2(128 BYTE), 
	"PARALLEL" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"PARALLEL_DEGREE" NUMBER(*,0) DEFAULT 4, 
	"RANGE_PARTITIONED" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"SAMPLED" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"HISTOGRAM" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"IND_AVAILABLE" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"SAMPLE_CAP" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"HIST_COLUMN" VARCHAR2(128 BYTE), 
	"HIST_COLUMN_TYPE" VARCHAR2(128 BYTE), 
	"SAMPLE_COLUMN" VARCHAR2(128 BYTE) DEFAULT null, 
	"SAMPLE_COLUMN_TYPE" VARCHAR2(128 BYTE), 
	"NUM_PARTITIONS" NUMBER(*,0) DEFAULT 0, 
	"NUM_PARTITION_COLUMNS" NUMBER(*,0) DEFAULT 0, 
	"PARTITION_COL_NAMES" "SYS"."HSBLKNAMLST"  DEFAULT null, 
	"PARTITION_COL_TYPES" "SYS"."HSBLKNAMLST" , 
	"NCOL_MIN_VAL" NUMBER DEFAULT null, 
	"NCOL_AVG_VAL" NUMBER DEFAULT null, 
	"NCOL_MAX_VAL" NUMBER DEFAULT null, 
	"NUM_BUCKETS" NUMBER(*,0) DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 NESTED TABLE "PARTITION_COL_NAMES" STORE AS "HS_PARTITION_COL_NAME"
 (PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
 NOCOMPRESS 
  TABLESPACE "SYSTEM" ) RETURN AS VALUE
 NESTED TABLE "PARTITION_COL_TYPES" STORE AS "HS_PARTITION_COL_TYPE"
 (PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
 NOCOMPRESS 
  TABLESPACE "SYSTEM" ) RETURN AS VALUE;
  GRANT READ ON "SYS"."HS$_PARALLEL_METADATA" TO PUBLIC;
