--------------------------------------------------------
--  Constraints for Table HS$_BASE_CAPS
--------------------------------------------------------

  ALTER TABLE "SYS"."HS$_BASE_CAPS" MODIFY ("CAP_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HS$_BASE_CAPS" ADD CONSTRAINT "HS$_BASE_CAPS_PK" PRIMARY KEY ("CAP_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
