--------------------------------------------------------
--  Ref Constraints for Table HS$_PARALLEL_HISTOGRAM_DATA
--------------------------------------------------------

  ALTER TABLE "SYS"."HS$_PARALLEL_HISTOGRAM_DATA" ADD CONSTRAINT "HS_PARALLEL_HISTOGRAM_DATA_FK" FOREIGN KEY ("DBLINK", "REMOTE_TABLE_NAME", "REMOTE_SCHEMA_NAME")
	  REFERENCES "SYS"."HS$_PARALLEL_METADATA" ("DBLINK", "REMOTE_TABLE_NAME", "REMOTE_SCHEMA_NAME") ON DELETE CASCADE ENABLE;
