--------------------------------------------------------
--  DDL for Table HS$_PARALLEL_PARTITION_DATA
--------------------------------------------------------

  CREATE TABLE "SYS"."HS$_PARALLEL_PARTITION_DATA" SHARING=METADATA 
   (	"DBLINK" VARCHAR2(128 BYTE), 
	"REMOTE_TABLE_NAME" VARCHAR2(128 BYTE), 
	"REMOTE_SCHEMA_NAME" VARCHAR2(128 BYTE), 
	"LOW_VALUE" "SYS"."HSBLKVALARY" , 
	"HIGH_VALUE" "SYS"."HSBLKVALARY" , 
	"PARTITION_POSITION" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
