--------------------------------------------------------
--  DDL for Table HS$_PARALLEL_HISTOGRAM_DATA
--------------------------------------------------------

  CREATE TABLE "SYS"."HS$_PARALLEL_HISTOGRAM_DATA" SHARING=METADATA 
   (	"DBLINK" VARCHAR2(128 BYTE), 
	"REMOTE_TABLE_NAME" VARCHAR2(128 BYTE), 
	"REMOTE_SCHEMA_NAME" VARCHAR2(128 BYTE), 
	"LOW_VALUE" NUMBER, 
	"HIGH_VALUE" NUMBER, 
	"BUCKET_NUM" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
