--------------------------------------------------------
--  Constraints for Table HS$_INST_DD
--------------------------------------------------------

  ALTER TABLE "SYS"."HS$_INST_DD" MODIFY ("FDS_INST_DD_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HS$_INST_DD" MODIFY ("FDS_INST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HS$_INST_DD" MODIFY ("DD_TABLE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HS$_INST_DD" MODIFY ("TRANSLATION_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HS$_INST_DD" ADD CONSTRAINT "HS$_INST_DD_C1" CHECK (translation_type in ('T','M','S')) ENABLE;
  ALTER TABLE "SYS"."HS$_INST_DD" ADD CONSTRAINT "HS$_INST_DD_C2" CHECK ((translation_type in ('T','S') and translation_text is not NULL) or
       (translation_type = 'M')) ENABLE;
  ALTER TABLE "SYS"."HS$_INST_DD" ADD CONSTRAINT "HS$_INST_DD_PK" PRIMARY KEY ("FDS_INST_DD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYS"."HS$_INST_DD" ADD CONSTRAINT "HS$_INST_DD_UK1" UNIQUE ("FDS_INST_ID", "DD_TABLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
