--------------------------------------------------------
--  Constraints for Table HS$_INST_CAPS
--------------------------------------------------------

  ALTER TABLE "SYS"."HS$_INST_CAPS" MODIFY ("FDS_INST_CAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HS$_INST_CAPS" MODIFY ("FDS_INST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HS$_INST_CAPS" MODIFY ("CAP_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HS$_INST_CAPS" ADD CONSTRAINT "HS$_INST_CAPS_PK" PRIMARY KEY ("FDS_INST_CAP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYS"."HS$_INST_CAPS" ADD CONSTRAINT "HS$_INST_CAPS_UK1" UNIQUE ("FDS_INST_ID", "CAP_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
