--------------------------------------------------------
--  Constraints for Table HS$_PARALLEL_METADATA
--------------------------------------------------------

  ALTER TABLE "SYS"."HS$_PARALLEL_METADATA" MODIFY ("PARALLEL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HS$_PARALLEL_METADATA" MODIFY ("PARALLEL_DEGREE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HS$_PARALLEL_METADATA" MODIFY ("RANGE_PARTITIONED" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HS$_PARALLEL_METADATA" MODIFY ("SAMPLED" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HS$_PARALLEL_METADATA" MODIFY ("HISTOGRAM" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HS$_PARALLEL_METADATA" MODIFY ("IND_AVAILABLE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HS$_PARALLEL_METADATA" MODIFY ("SAMPLE_CAP" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HS$_PARALLEL_METADATA" ADD CONSTRAINT "HS_PARALLEL_METADATA_PK" PRIMARY KEY ("DBLINK", "REMOTE_TABLE_NAME", "REMOTE_SCHEMA_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYS"."HS$_PARALLEL_METADATA" ADD UNIQUE ("PARTITION_COL_TYPES") RELY
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYS"."HS$_PARALLEL_METADATA" ADD UNIQUE ("PARTITION_COL_NAMES") RELY
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
