--------------------------------------------------------
--  Constraints for Table HS$_INST_INIT
--------------------------------------------------------

  ALTER TABLE "SYS"."HS$_INST_INIT" MODIFY ("FDS_INST_INIT_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HS$_INST_INIT" MODIFY ("FDS_INST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HS$_INST_INIT" MODIFY ("INIT_VALUE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HS$_INST_INIT" MODIFY ("INIT_VALUE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HS$_INST_INIT" MODIFY ("INIT_VALUE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HS$_INST_INIT" ADD CONSTRAINT "HS$_INST_INIT_C1" CHECK (init_value_type in ('F','T')) ENABLE;
  ALTER TABLE "SYS"."HS$_INST_INIT" ADD CONSTRAINT "HS$_INST_INIT_PK" PRIMARY KEY ("FDS_INST_INIT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYS"."HS$_INST_INIT" ADD CONSTRAINT "HS$_INST_INIT_UK1" UNIQUE ("FDS_INST_ID", "INIT_VALUE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
