--------------------------------------------------------
--  Constraints for Table HS$_FDS_INST
--------------------------------------------------------

  ALTER TABLE "SYS"."HS$_FDS_INST" MODIFY ("FDS_INST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HS$_FDS_INST" MODIFY ("FDS_CLASS_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HS$_FDS_INST" MODIFY ("FDS_INST_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HS$_FDS_INST" ADD CONSTRAINT "HS$_FDS_INST_PK" PRIMARY KEY ("FDS_INST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYS"."HS$_FDS_INST" ADD CONSTRAINT "HS$_FDS_INST_UK1" UNIQUE ("FDS_INST_NAME", "FDS_CLASS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
