--------------------------------------------------------
--  Constraints for Table HS$_FDS_CLASS
--------------------------------------------------------

  ALTER TABLE "SYS"."HS$_FDS_CLASS" MODIFY ("FDS_CLASS_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HS$_FDS_CLASS" MODIFY ("FDS_CLASS_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."HS$_FDS_CLASS" ADD CONSTRAINT "HS$_FDS_CLASS_PK" PRIMARY KEY ("FDS_CLASS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYS"."HS$_FDS_CLASS" ADD CONSTRAINT "HS$_FDS_CLASS_UK1" UNIQUE ("FDS_CLASS_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
