--------------------------------------------------------
--  DDL for Table HS$_PARALLEL_SAMPLE_DATA
--------------------------------------------------------

  CREATE TABLE "SYS"."HS$_PARALLEL_SAMPLE_DATA" SHARING=METADATA 
   (	"DBLINK" VARCHAR2(128 BYTE), 
	"REMOTE_TABLE_NAME" VARCHAR2(128 BYTE), 
	"REMOTE_SCHEMA_NAME" VARCHAR2(128 BYTE), 
	"LOW_VALUE" VARCHAR2(4000 BYTE), 
	"HIGH_VALUE" VARCHAR2(4000 BYTE), 
	"POSITION" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
