--------------------------------------------------------
--  DDL for Table HS$_BASE_DD
--------------------------------------------------------

  CREATE TABLE "SYS"."HS$_BASE_DD" SHARING=METADATA 
   (	"DD_TABLE_ID" NUMBER, 
	"DD_TABLE_NAME" VARCHAR2(128 BYTE), 
	"DD_TABLE_DESC" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
