--------------------------------------------------------
--  DDL for Table HS$_INST_CAPS
--------------------------------------------------------

  CREATE TABLE "SYS"."HS$_INST_CAPS" SHARING=METADATA 
   (	"FDS_INST_CAP_ID" NUMBER, 
	"FDS_INST_ID" NUMBER, 
	"CAP_NUMBER" NUMBER, 
	"CONTEXT" NUMBER, 
	"TRANSLATION" VARCHAR2(255 BYTE), 
	"ADDITIONAL_INFO" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
