--------------------------------------------------------
--  DDL for Index I1_QUEUE_TABLE_AFFINITIES
--------------------------------------------------------

  CREATE INDEX "SYS"."I1_QUEUE_TABLE_AFFINITIES" ON "SYS"."AQ$_QUEUE_TABLE_AFFINITIES" ("OWNER_INSTANCE", "TABLE_OBJNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
