--------------------------------------------------------
--  DDL for Index I3_RULE_SET_RE
--------------------------------------------------------

  CREATE INDEX "SYS"."I3_RULE_SET_RE" ON "SYS"."RULE_SET_RE$" ("RS_OBJ#", "R_OBJ#", "EC_OBJ#") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
