--------------------------------------------------------
--  DDL for Index I_APPLY_CHANGE_HANDLERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."I_APPLY_CHANGE_HANDLERS" ON "SYS"."APPLY$_CHANGE_HANDLERS" ("CHANGE_TABLE_OWNER", "CHANGE_TABLE_NAME", "SOURCE_TABLE_OWNER", "SOURCE_TABLE_NAME", "HANDLER_NAME", "APPLY_NAME", "OPERATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
