--------------------------------------------------------
--  DDL for Index I_COL3
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."I_COL3" ON "SYS"."COL$" ("OBJ#", "INTCOL#") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 32768 NEXT 106496 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
