--------------------------------------------------------
--  DDL for Index I_DAM_CONFIG_PARAM$
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."I_DAM_CONFIG_PARAM$" ON "SYS"."DAM_CONFIG_PARAM$" ("PARAM_ID", "AUDIT_TRAIL_TYPE#") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
