--------------------------------------------------------
--  DDL for Index I_GG_PROC_OBJECT_EXCLUSION
--------------------------------------------------------

  CREATE INDEX "SYS"."I_GG_PROC_OBJECT_EXCLUSION" ON "SYS"."GG$_PROC_OBJECT_EXCLUSION" ("PACKAGE_OWNER", "PACKAGE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
