--------------------------------------------------------
--  DDL for Index I_HH_OBJ#_COL#
--------------------------------------------------------

  CREATE INDEX "SYS"."I_HH_OBJ#_COL#" ON "SYS"."HIST_HEAD$" ("OBJ#", "COL#") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
