--------------------------------------------------------
--  DDL for Index I_LTXID_TRANS$PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."I_LTXID_TRANS$PK" ON "SYS"."LTXID_TRANS" ("INST_ID", "DB_ID", "SESSION_GUID", "TXN_UID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) LOCAL
 (PARTITION "LTXID_TRANS_PK_01" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ) ;
