--------------------------------------------------------
--  DDL for Index I_OLAP_DIMENSIONALITY$
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."I_OLAP_DIMENSIONALITY$" ON "SYS"."OLAP_DIMENSIONALITY$" ("DIMENSIONED_OBJECT_ID", "DIMENSIONED_OBJECT_TYPE", "ORDER_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
