--------------------------------------------------------
--  DDL for Index I_OLAP_METADATA_PROPERTIES
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."I_OLAP_METADATA_PROPERTIES" ON "SYS"."OLAP_METADATA_PROPERTIES$" ("OWNING_OBJECT_ID", "OWNING_TYPE", "OWNING_TYPE2", "OWNING_OBJECT_ID2", "PROPERTY_ORDER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
