--------------------------------------------------------
--  DDL for Index I_OPT_SQLSTAT_LGT
--------------------------------------------------------

  CREATE INDEX "SYS"."I_OPT_SQLSTAT_LGT" ON "SYS"."OPT_SQLSTAT$" ("LAST_GATHER_TIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
