--------------------------------------------------------
--  DDL for Index I_SOURCE1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."I_SOURCE1" ON "SYS"."SOURCE$" ("OBJ#", "LINE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 16384 NEXT 204800 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
