--------------------------------------------------------
--  DDL for Index I_STREAMS_APPLY_SPILL_MSGS_PT1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."I_STREAMS_APPLY_SPILL_MSGS_PT1" ON "SYS"."STREAMS$_APPLY_SPILL_MSGS_PART" ("SEQUENCE", "TXNKEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  LOCAL
 (PARTITION "P0" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ) ;
