--------------------------------------------------------
--  DDL for Index I_WRI$_OPTSTAT_OPR_TASKS_OPOBJ
--------------------------------------------------------

  CREATE INDEX "SYS"."I_WRI$_OPTSTAT_OPR_TASKS_OPOBJ" ON "SYS"."WRI$_OPTSTAT_OPR_TASKS" ("OP_ID", "TARGET_OBJN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
