--------------------------------------------------------
--  DDL for Index I_XSTREAM_REPERROR_HANDLER1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."I_XSTREAM_REPERROR_HANDLER1" ON "SYS"."XSTREAM$_REPERROR_HANDLER" ("APPLY_NAME", "SCHEMA_NAME", "TABLE_NAME", "SOURCE_SCHEMA_NAME", "SOURCE_TABLE_NAME", "ERROR_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
