--------------------------------------------------------
--  DDL for Index I_XSTREAM_HANDLE_COLLISIONS1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."I_XSTREAM_HANDLE_COLLISIONS1" ON "SYS"."XSTREAM$_HANDLE_COLLISIONS" ("APPLY_NAME", "SCHEMA_NAME", "TABLE_NAME", "SOURCE_SCHEMA_NAME", "SOURCE_TABLE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
