--------------------------------------------------------
--  Constraints for Table ICOL$
--------------------------------------------------------

  ALTER TABLE "SYS"."ICOL$" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."ICOL$" MODIFY ("BO#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."ICOL$" MODIFY ("COL#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."ICOL$" MODIFY ("POS#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."ICOL$" MODIFY ("SEGCOL#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."ICOL$" MODIFY ("SEGCOLLENGTH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."ICOL$" MODIFY ("OFFSET" NOT NULL ENABLE);
  ALTER TABLE "SYS"."ICOL$" MODIFY ("INTCOL#" NOT NULL ENABLE);
