--------------------------------------------------------
--  DDL for Table IDL_CHAR$
--------------------------------------------------------

  CREATE TABLE "SYS"."IDL_CHAR$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"PART" NUMBER, 
	"VERSION" NUMBER, 
	"PIECE#" NUMBER, 
	"LENGTH" NUMBER, 
	"PIECE" LONG
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16384 NEXT 106496 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
