--------------------------------------------------------
--  DDL for Table ILM_EXECUTION$
--------------------------------------------------------

  CREATE TABLE "SYS"."ILM_EXECUTION$" SHARING=METADATA 
   (	"EXECUTION_ID" NUMBER, 
	"OWNER" NUMBER, 
	"CREATION_TIME" TIMESTAMP (6), 
	"START_TIME" TIMESTAMP (6), 
	"COMPLETION_TIME" TIMESTAMP (6), 
	"EXECUTION_STATE" NUMBER, 
	"FLAG" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" VARCHAR2(4000 BYTE), 
	"SPARE5" VARCHAR2(4000 BYTE), 
	"SPARE6" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
