--------------------------------------------------------
--  DDL for Table ILM_EXECUTIONDETAILS$
--------------------------------------------------------

  CREATE TABLE "SYS"."ILM_EXECUTIONDETAILS$" SHARING=METADATA 
   (	"POLICY#" NUMBER, 
	"OBJ#" NUMBER, 
	"EXECUTION_ID" NUMBER, 
	"JOBSCHEDULED" NUMBER, 
	"JOBNAME" VARCHAR2(128 BYTE), 
	"COMMENTS" VARCHAR2(4000 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" VARCHAR2(4000 BYTE), 
	"SPARE5" VARCHAR2(4000 BYTE), 
	"SPARE6" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
