REM INSERTING into SYS.ILM_PARAM$
SET DEFINE OFF;
Insert into SYS.ILM_PARAM$ (PARAM#,PARAM_NAME,PARAM_VALUE) values (7,'ENABLED',1);
Insert into SYS.ILM_PARAM$ (PARAM#,PARAM_NAME,PARAM_VALUE) values (2,'RETENTION TIME',30);
Insert into SYS.ILM_PARAM$ (PARAM#,PARAM_NAME,PARAM_VALUE) values (5,'JOB LIMIT',2);
Insert into SYS.ILM_PARAM$ (PARAM#,PARAM_NAME,PARAM_VALUE) values (4,'EXECUTION MODE',2);
Insert into SYS.ILM_PARAM$ (PARAM#,PARAM_NAME,PARAM_VALUE) values (1,'EXECUTION INTERVAL',15);
Insert into SYS.ILM_PARAM$ (PARAM#,PARAM_NAME,PARAM_VALUE) values (8,'TBS PERCENT USED',85);
Insert into SYS.ILM_PARAM$ (PARAM#,PARAM_NAME,PARAM_VALUE) values (9,'TBS PERCENT FREE',25);
Insert into SYS.ILM_PARAM$ (PARAM#,PARAM_NAME,PARAM_VALUE) values (11,'POLICY TIME',0);
