--------------------------------------------------------
--  DDL for Table ILMOBJ$
--------------------------------------------------------

  CREATE TABLE "SYS"."ILMOBJ$" SHARING=METADATA 
   (	"POLICY#" NUMBER, 
	"OBJ#" NUMBER, 
	"DATAOBJ#" NUMBER, 
	"LAST_CHK_TIME" TIMESTAMP (6), 
	"LAST_EXE_TIME" TIMESTAMP (6), 
	"OBJ_TYP" NUMBER, 
	"OBJ_TYP_ORIG" NUMBER, 
	"POBJN_ORIG" NUMBER, 
	"FLAG" NUMBER, 
	"LAST_JOB_STATUS" NUMBER, 
	"N_FAIL" NUMBER DEFAULT 0, 
	"N_AFT_NOFILT" NUMBER DEFAULT 0, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" VARCHAR2(4000 BYTE), 
	"SPARE5" VARCHAR2(4000 BYTE), 
	"SPARE6" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
