--------------------------------------------------------
--  DDL for Table ILMPOLICY$
--------------------------------------------------------

  CREATE TABLE "SYS"."ILMPOLICY$" SHARING=METADATA 
   (	"POLICY#" NUMBER, 
	"ACTIONC" VARCHAR2(100 BYTE), 
	"CTYPE" NUMBER, 
	"CLEVEL" NUMBER, 
	"CINDEX" NUMBER, 
	"CPREFIX" NUMBER, 
	"CLEVLOB" NUMBER, 
	"TIER_TBS" VARCHAR2(128 BYTE), 
	"ACTION" NUMBER, 
	"TYPE" NUMBER, 
	"CONDITION" NUMBER, 
	"DAYS" NUMBER, 
	"SCOPE" NUMBER, 
	"CUSTFUNC" VARCHAR2(128 BYTE), 
	"FLAG" NUMBER, 
	"FLAG2" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" VARCHAR2(4000 BYTE), 
	"SPARE5" VARCHAR2(4000 BYTE), 
	"SPARE6" TIMESTAMP (6), 
	"POL_SUBTYPE" NUMBER, 
	"ACTIONC_CLOB" CLOB, 
	"TIER_TO" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" 
 LOB ("ACTIONC_CLOB") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
