--------------------------------------------------------
--  DDL for Table IM_IME$
--------------------------------------------------------

  CREATE TABLE "SYS"."IM_IME$" SHARING=METADATA 
   (	"ACTION_NAME" VARCHAR2(100 BYTE), 
	"ACTION_STATE" VARCHAR2(10 BYTE), 
	"LAST_MODIFIED" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
