REM INSERTING into SYS.IM_IME$
SET DEFINE OFF;
Insert into SYS.IM_IME$ (ACTION_NAME,ACTION_STATE,LAST_MODIFIED) values ('CAPTURE WINDOW','DEFAULT',to_timestamp('30-MAY-19 03.51.33.180000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
