--------------------------------------------------------
--  Constraints for Table IM_JOINGROUP$
--------------------------------------------------------

  ALTER TABLE "SYS"."IM_JOINGROUP$" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."IM_JOINGROUP$" MODIFY ("OWNER#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."IM_JOINGROUP$" MODIFY ("DOMAIN#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."IM_JOINGROUP$" ADD CONSTRAINT "IM_JOINGROUP_PK" PRIMARY KEY ("DOMAIN#")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYS"."IM_JOINGROUP$" ADD CONSTRAINT "IM_JOINGROUP_UK" UNIQUE ("NAME", "OWNER#")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
