--------------------------------------------------------
--  Constraints for Table IMPCALLOUTREG$
--------------------------------------------------------

  ALTER TABLE "SYS"."IMPCALLOUTREG$" MODIFY ("PACKAGE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."IMPCALLOUTREG$" MODIFY ("SCHEMA" NOT NULL ENABLE);
  ALTER TABLE "SYS"."IMPCALLOUTREG$" MODIFY ("TAG" NOT NULL ENABLE);
  ALTER TABLE "SYS"."IMPCALLOUTREG$" MODIFY ("CLASS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."IMPCALLOUTREG$" MODIFY ("LEVEL#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."IMPCALLOUTREG$" MODIFY ("FLAGS" NOT NULL ENABLE);
