--------------------------------------------------------
--  DDL for Table IMPDP_STATS
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "SYS"."IMPDP_STATS" SHARING=METADATA 
   (	"STATID" VARCHAR2(128 BYTE), 
	"TYPE" CHAR(1 BYTE), 
	"VERSION" NUMBER, 
	"FLAGS" NUMBER, 
	"C1" VARCHAR2(128 BYTE), 
	"C2" VARCHAR2(128 BYTE), 
	"C3" VARCHAR2(128 BYTE), 
	"C4" VARCHAR2(128 BYTE), 
	"C5" VARCHAR2(128 BYTE), 
	"C6" VARCHAR2(128 BYTE), 
	"N1" NUMBER, 
	"N2" NUMBER, 
	"N3" NUMBER, 
	"N4" NUMBER, 
	"N5" NUMBER, 
	"N6" NUMBER, 
	"N7" NUMBER, 
	"N8" NUMBER, 
	"N9" NUMBER, 
	"N10" NUMBER, 
	"N11" NUMBER, 
	"N12" NUMBER, 
	"N13" NUMBER, 
	"D1" DATE, 
	"T1" TIMESTAMP (6) WITH TIME ZONE, 
	"R1" RAW(1000), 
	"R2" RAW(1000), 
	"R3" RAW(1000), 
	"CH1" VARCHAR2(1000 BYTE), 
	"CL1" CLOB, 
	"BL1" BLOB
   ) ON COMMIT PRESERVE ROWS 
 LOB ("CL1") STORE AS BASICFILE (
  ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE ) 
 LOB ("BL1") STORE AS BASICFILE (
  ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE ) ;
  GRANT DELETE ON "SYS"."IMPDP_STATS" TO PUBLIC;
  GRANT INSERT ON "SYS"."IMPDP_STATS" TO PUBLIC;
  GRANT SELECT ON "SYS"."IMPDP_STATS" TO PUBLIC;
  GRANT UPDATE ON "SYS"."IMPDP_STATS" TO PUBLIC;
