--------------------------------------------------------
--  DDL for Table INCEXP
--------------------------------------------------------

  CREATE TABLE "SYS"."INCEXP" SHARING=METADATA 
   (	"OWNER#" NUMBER, 
	"NAME" VARCHAR2(128 BYTE), 
	"TYPE#" NUMBER, 
	"CTIME" DATE, 
	"ITIME" DATE, 
	"EXPID" NUMBER(3,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
  GRANT DELETE ON "SYS"."INCEXP" TO "EXP_FULL_DATABASE";
  GRANT INSERT ON "SYS"."INCEXP" TO "EXP_FULL_DATABASE";
  GRANT UPDATE ON "SYS"."INCEXP" TO "EXP_FULL_DATABASE";
