--------------------------------------------------------
--  DDL for Table INCFIL
--------------------------------------------------------

  CREATE TABLE "SYS"."INCFIL" SHARING=METADATA 
   (	"EXPID" NUMBER(3,0), 
	"EXPTYPE" VARCHAR2(1 BYTE), 
	"EXPFILE" VARCHAR2(100 BYTE), 
	"EXPDATE" DATE, 
	"EXPUSER" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
  GRANT DELETE ON "SYS"."INCFIL" TO "EXP_FULL_DATABASE";
  GRANT INSERT ON "SYS"."INCFIL" TO "EXP_FULL_DATABASE";
  GRANT UPDATE ON "SYS"."INCFIL" TO "EXP_FULL_DATABASE";
