--------------------------------------------------------
--  DDL for Table INCVID
--------------------------------------------------------

  CREATE TABLE "SYS"."INCVID" SHARING=METADATA 
   (	"EXPID" NUMBER(3,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  GRANT DELETE ON "SYS"."INCVID" TO "EXP_FULL_DATABASE";
  GRANT INSERT ON "SYS"."INCVID" TO "EXP_FULL_DATABASE";
  GRANT UPDATE ON "SYS"."INCVID" TO "EXP_FULL_DATABASE";
