--------------------------------------------------------
--  DDL for Table IND$
--------------------------------------------------------

  CREATE TABLE "SYS"."IND$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"DATAOBJ#" NUMBER, 
	"TS#" NUMBER, 
	"FILE#" NUMBER, 
	"BLOCK#" NUMBER, 
	"BO#" NUMBER, 
	"INDMETHOD#" NUMBER, 
	"COLS" NUMBER, 
	"PCTFREE$" NUMBER, 
	"INITRANS" NUMBER, 
	"MAXTRANS" NUMBER, 
	"PCTTHRES$" NUMBER, 
	"TYPE#" NUMBER, 
	"FLAGS" NUMBER, 
	"PROPERTY" NUMBER, 
	"BLEVEL" NUMBER, 
	"LEAFCNT" NUMBER, 
	"DISTKEY" NUMBER, 
	"LBLKKEY" NUMBER, 
	"DBLKKEY" NUMBER, 
	"CLUFAC" NUMBER, 
	"ANALYZETIME" DATE, 
	"SAMPLESIZE" NUMBER, 
	"ROWCNT" NUMBER, 
	"INTCOLS" NUMBER, 
	"DEGREE" NUMBER, 
	"INSTANCES" NUMBER, 
	"TRUNCCNT" NUMBER, 
	"EVALEDITION#" NUMBER, 
	"UNUSABLEBEFORE#" NUMBER, 
	"UNUSABLEBEGINNING#" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" VARCHAR2(1000 BYTE), 
	"SPARE5" VARCHAR2(1000 BYTE), 
	"SPARE6" DATE
   ) CLUSTER "SYS"."C_OBJ#" ("BO#");
  GRANT READ ON "SYS"."IND$" TO "SYSUMF_ROLE";
  GRANT READ ON "SYS"."IND$" TO "GSMUSER_ROLE";
  GRANT SELECT ON "SYS"."IND$" TO "CTXSYS";
