--------------------------------------------------------
--  Constraints for Table IND$
--------------------------------------------------------

  ALTER TABLE "SYS"."IND$" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."IND$" MODIFY ("TS#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."IND$" MODIFY ("FILE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."IND$" MODIFY ("BLOCK#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."IND$" MODIFY ("BO#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."IND$" MODIFY ("INDMETHOD#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."IND$" MODIFY ("COLS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."IND$" MODIFY ("PCTFREE$" NOT NULL ENABLE);
  ALTER TABLE "SYS"."IND$" MODIFY ("INITRANS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."IND$" MODIFY ("MAXTRANS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."IND$" MODIFY ("TYPE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."IND$" MODIFY ("FLAGS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."IND$" MODIFY ("PROPERTY" NOT NULL ENABLE);
  ALTER TABLE "SYS"."IND$" MODIFY ("INTCOLS" NOT NULL ENABLE);
