--------------------------------------------------------
--  DDL for Table INDCOMPART$
--------------------------------------------------------

  CREATE TABLE "SYS"."INDCOMPART$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"DATAOBJ#" NUMBER, 
	"BO#" NUMBER, 
	"PART#" NUMBER, 
	"HIBOUNDLEN" NUMBER, 
	"HIBOUNDVAL" LONG, 
	"SUBPARTCNT" NUMBER, 
	"FLAGS" NUMBER, 
	"DEFTS#" NUMBER, 
	"DEFPCTFREE" NUMBER, 
	"DEFINITRANS" NUMBER, 
	"DEFMAXTRANS" NUMBER, 
	"DEFINIEXTS" NUMBER, 
	"DEFEXTSIZE" NUMBER, 
	"DEFMINEXTS" NUMBER, 
	"DEFMAXEXTS" NUMBER, 
	"DEFEXTPCT" NUMBER, 
	"DEFLISTS" NUMBER, 
	"DEFGROUPS" NUMBER, 
	"DEFLOGGING" NUMBER, 
	"DEFBUFPOOL" NUMBER, 
	"ANALYZETIME" DATE, 
	"SAMPLESIZE" NUMBER, 
	"ROWCNT" NUMBER, 
	"BLEVEL" NUMBER, 
	"LEAFCNT" NUMBER, 
	"DISTKEY" NUMBER, 
	"LBLKKEY" NUMBER, 
	"DBLKKEY" NUMBER, 
	"CLUFAC" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"BHIBOUNDVAL" BLOB, 
	"DEFMAXSIZE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("BHIBOUNDVAL") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
