--------------------------------------------------------
--  Constraints for Table INDCOMPART$
--------------------------------------------------------

  ALTER TABLE "SYS"."INDCOMPART$" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."INDCOMPART$" MODIFY ("BO#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."INDCOMPART$" MODIFY ("PART#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."INDCOMPART$" MODIFY ("HIBOUNDLEN" NOT NULL ENABLE);
  ALTER TABLE "SYS"."INDCOMPART$" MODIFY ("SUBPARTCNT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."INDCOMPART$" MODIFY ("FLAGS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."INDCOMPART$" MODIFY ("DEFPCTFREE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."INDCOMPART$" MODIFY ("DEFINITRANS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."INDCOMPART$" MODIFY ("DEFMAXTRANS" NOT NULL ENABLE);
