--------------------------------------------------------
--  Constraints for Table INDPART$
--------------------------------------------------------

  ALTER TABLE "SYS"."INDPART$" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."INDPART$" MODIFY ("BO#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."INDPART$" MODIFY ("PART#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."INDPART$" MODIFY ("HIBOUNDLEN" NOT NULL ENABLE);
  ALTER TABLE "SYS"."INDPART$" MODIFY ("FLAGS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."INDPART$" MODIFY ("TS#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."INDPART$" MODIFY ("FILE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."INDPART$" MODIFY ("BLOCK#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."INDPART$" MODIFY ("PCTFREE$" NOT NULL ENABLE);
  ALTER TABLE "SYS"."INDPART$" MODIFY ("INITRANS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."INDPART$" MODIFY ("MAXTRANS" NOT NULL ENABLE);
