--------------------------------------------------------
--  Constraints for Table INDREBUILD$
--------------------------------------------------------

  ALTER TABLE "SYS"."INDREBUILD$" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."INDREBUILD$" MODIFY ("TS#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."INDREBUILD$" MODIFY ("FILE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."INDREBUILD$" MODIFY ("BLOCK#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."INDREBUILD$" MODIFY ("PCTFREE$" NOT NULL ENABLE);
  ALTER TABLE "SYS"."INDREBUILD$" MODIFY ("INITRANS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."INDREBUILD$" MODIFY ("MAXTRANS" NOT NULL ENABLE);
