--------------------------------------------------------
--  Constraints for Table INDSUBPART$
--------------------------------------------------------

  ALTER TABLE "SYS"."INDSUBPART$" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."INDSUBPART$" MODIFY ("POBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."INDSUBPART$" MODIFY ("SUBPART#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."INDSUBPART$" MODIFY ("FLAGS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."INDSUBPART$" MODIFY ("TS#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."INDSUBPART$" MODIFY ("FILE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."INDSUBPART$" MODIFY ("BLOCK#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."INDSUBPART$" MODIFY ("PCTFREE$" NOT NULL ENABLE);
  ALTER TABLE "SYS"."INDSUBPART$" MODIFY ("INITRANS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."INDSUBPART$" MODIFY ("MAXTRANS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."INDSUBPART$" MODIFY ("HIBOUNDLEN" NOT NULL ENABLE);
