--------------------------------------------------------
--  DDL for Table INVALIDATION_REGISTRY$
--------------------------------------------------------

  CREATE TABLE "SYS"."INVALIDATION_REGISTRY$" SHARING=METADATA 
   (	"REGID" NUMBER, 
	"REGFLAGS" NUMBER, 
	"NUMOBJS" NUMBER, 
	"OBJARRAY" RAW(512), 
	"PLSQLCALLBACK" VARCHAR2(257 BYTE), 
	"CHANGELAG" NUMBER, 
	"USERNAME" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
