--------------------------------------------------------
--  Constraints for Table JAVA$MC$
--------------------------------------------------------

  ALTER TABLE "SYS"."JAVA$MC$" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."JAVA$MC$" MODIFY ("METHOD#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."JAVA$MC$" MODIFY ("PIECE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."JAVA$MC$" MODIFY ("LENGTH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."JAVA$MC$" MODIFY ("PIECE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."JAVA$MC$" ADD CONSTRAINT "JAVA$MC$UNIQUE" PRIMARY KEY ("OBJ#", "METHOD#", "PIECE#")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
