--------------------------------------------------------
--  DDL for Table JAVA$JVM$RJBC
--------------------------------------------------------

  CREATE TABLE "SYS"."JAVA$JVM$RJBC" SHARING=METADATA 
   (	"ID" VARCHAR2(100 BYTE), 
	"PATH" VARCHAR2(4000 BYTE), 
	"LOB" BLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("LOB") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
