--------------------------------------------------------
--  DDL for Index JAVA$RMJVM$AUXI3
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."JAVA$RMJVM$AUXI3" ON "SYS"."JAVA$RMJVM$AUX3" ("OBJ#") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
