--------------------------------------------------------
--  Constraints for Table JAVA$METHOD$METADATA
--------------------------------------------------------

  ALTER TABLE "SYS"."JAVA$METHOD$METADATA" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."JAVA$METHOD$METADATA" MODIFY ("METHOD#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."JAVA$METHOD$METADATA" MODIFY ("PIECE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."JAVA$METHOD$METADATA" MODIFY ("LENGTH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."JAVA$METHOD$METADATA" MODIFY ("PIECE" NOT NULL ENABLE);
