--------------------------------------------------------
--  DDL for Table JAVA$POLICY$
--------------------------------------------------------

  CREATE TABLE "SYS"."JAVA$POLICY$" SHARING=METADATA 
   (	"KIND#" NUMBER, 
	"GRANTEE#" NUMBER, 
	"TYPE_SCHEMA#" NUMBER, 
	"TYPE_NAME" VARCHAR2(4000 BYTE), 
	"NAME" VARCHAR2(4000 BYTE), 
	"ACTION" VARCHAR2(4000 BYTE), 
	"STATUS#" NUMBER, 
	"KEY" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
