REM INSERTING into SYS.JAVA$POLICY$SHARED$TABLE
SET DEFINE OFF;
Insert into SYS.JAVA$POLICY$SHARED$TABLE (VERSION) values (18);
Insert into SYS.JAVA$POLICY$SHARED$TABLE (VERSION) values (19);
Insert into SYS.JAVA$POLICY$SHARED$TABLE (VERSION) values (20);
Insert into SYS.JAVA$POLICY$SHARED$TABLE (VERSION) values (21);
Insert into SYS.JAVA$POLICY$SHARED$TABLE (VERSION) values (22);
Insert into SYS.JAVA$POLICY$SHARED$TABLE (VERSION) values (15);
Insert into SYS.JAVA$POLICY$SHARED$TABLE (VERSION) values (16);
Insert into SYS.JAVA$POLICY$SHARED$TABLE (VERSION) values (17);
