--------------------------------------------------------
--  DDL for Table JAVA$JVM$STATUS
--------------------------------------------------------

  CREATE TABLE "SYS"."JAVA$JVM$STATUS" SHARING=METADATA 
   (	"ACTION" VARCHAR2(40 BYTE), 
	"INPROGRESS" VARCHAR2(1 BYTE), 
	"EXECID" VARCHAR2(40 BYTE), 
	"RMJVMTIME" DATE, 
	"PUNTING" VARCHAR2(5 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
