REM INSERTING into SYS.JAVANAMESTATUS$
SET DEFINE OFF;
Insert into SYS.JAVANAMESTATUS$ (PHASE,IDENTIFIER_LENGTH) values ('SYNONYMS',128);
Insert into SYS.JAVANAMESTATUS$ (PHASE,IDENTIFIER_LENGTH) values ('JAVA',128);
