--------------------------------------------------------
--  DDL for Table JIREFRESHSQL$
--------------------------------------------------------

  CREATE TABLE "SYS"."JIREFRESHSQL$" SHARING=METADATA 
   (	"IOBJ#" NUMBER, 
	"TOBJ#" NUMBER, 
	"SQLTEXT" CLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("SQLTEXT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
