--------------------------------------------------------
--  Constraints for Table JOB$
--------------------------------------------------------

  ALTER TABLE "SYS"."JOB$" MODIFY ("JOB" NOT NULL ENABLE);
  ALTER TABLE "SYS"."JOB$" MODIFY ("LOWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."JOB$" MODIFY ("POWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."JOB$" MODIFY ("COWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."JOB$" MODIFY ("NEXT_DATE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."JOB$" MODIFY ("TOTAL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."JOB$" MODIFY ("INTERVAL#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."JOB$" MODIFY ("FLAG" NOT NULL ENABLE);
