--------------------------------------------------------
--  DDL for Table JOB$
--------------------------------------------------------

  CREATE TABLE "SYS"."JOB$" SHARING=METADATA 
   (	"JOB" NUMBER, 
	"LOWNER" VARCHAR2(128 BYTE), 
	"POWNER" VARCHAR2(128 BYTE), 
	"COWNER" VARCHAR2(128 BYTE), 
	"LAST_DATE" DATE, 
	"THIS_DATE" DATE, 
	"NEXT_DATE" DATE, 
	"TOTAL" NUMBER DEFAULT 0, 
	"INTERVAL#" VARCHAR2(200 BYTE), 
	"FAILURES" NUMBER, 
	"FLAG" NUMBER DEFAULT 0, 
	"WHAT" VARCHAR2(4000 BYTE), 
	"NLSENV" VARCHAR2(4000 BYTE), 
	"ENV" RAW(32), 
	"CUR_SES_LABEL" RAW(255), 
	"CLEARANCE_HI" RAW(255), 
	"CLEARANCE_LO" RAW(255), 
	"CHARENV" VARCHAR2(4000 BYTE), 
	"FIELD1" NUMBER DEFAULT 0, 
	"SCHEDULER_FLAGS" NUMBER, 
	"XID" VARCHAR2(40 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
