REM INSERTING into SYS.KET$_CLIENT_CONFIG
SET DEFINE OFF;
Insert into SYS.KET$_CLIENT_CONFIG (CLIENT_ID,OPERATION_ID,STATUS,ATTRIBUTES,PRIORITY_OVERRIDE,LAST_CHANGE,SERVICE_NAME,GENERATOR_JOB_NAME,FIELD_1,FIELD_2,FIELD_3) values (0,0,2,0,0,null,null,null,null,null,null);
Insert into SYS.KET$_CLIENT_CONFIG (CLIENT_ID,OPERATION_ID,STATUS,ATTRIBUTES,PRIORITY_OVERRIDE,LAST_CHANGE,SERVICE_NAME,GENERATOR_JOB_NAME,FIELD_1,FIELD_2,FIELD_3) values (6,0,2,5,0,null,null,null,null,null,null);
Insert into SYS.KET$_CLIENT_CONFIG (CLIENT_ID,OPERATION_ID,STATUS,ATTRIBUTES,PRIORITY_OVERRIDE,LAST_CHANGE,SERVICE_NAME,GENERATOR_JOB_NAME,FIELD_1,FIELD_2,FIELD_3) values (1,0,2,1,0,null,null,null,null,null,null);
Insert into SYS.KET$_CLIENT_CONFIG (CLIENT_ID,OPERATION_ID,STATUS,ATTRIBUTES,PRIORITY_OVERRIDE,LAST_CHANGE,SERVICE_NAME,GENERATOR_JOB_NAME,FIELD_1,FIELD_2,FIELD_3) values (2,0,2,20,0,null,null,null,null,null,null);
Insert into SYS.KET$_CLIENT_CONFIG (CLIENT_ID,OPERATION_ID,STATUS,ATTRIBUTES,PRIORITY_OVERRIDE,LAST_CHANGE,SERVICE_NAME,GENERATOR_JOB_NAME,FIELD_1,FIELD_2,FIELD_3) values (4,0,2,5,0,null,null,null,null,null,null);
Insert into SYS.KET$_CLIENT_CONFIG (CLIENT_ID,OPERATION_ID,STATUS,ATTRIBUTES,PRIORITY_OVERRIDE,LAST_CHANGE,SERVICE_NAME,GENERATOR_JOB_NAME,FIELD_1,FIELD_2,FIELD_3) values (5,0,2,5,0,null,null,null,null,null,null);
Insert into SYS.KET$_CLIENT_CONFIG (CLIENT_ID,OPERATION_ID,STATUS,ATTRIBUTES,PRIORITY_OVERRIDE,LAST_CHANGE,SERVICE_NAME,GENERATOR_JOB_NAME,FIELD_1,FIELD_2,FIELD_3) values (3,0,2,34,0,null,null,null,null,null,null);
