--------------------------------------------------------
--  DDL for Table KET$_CLIENT_CONFIG
--------------------------------------------------------

  CREATE TABLE "SYS"."KET$_CLIENT_CONFIG" SHARING=METADATA 
   (	"CLIENT_ID" NUMBER, 
	"OPERATION_ID" NUMBER, 
	"STATUS" NUMBER DEFAULT 1, 
	"ATTRIBUTES" NUMBER DEFAULT 0, 
	"PRIORITY_OVERRIDE" NUMBER DEFAULT 0, 
	"LAST_CHANGE" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP, 
	"SERVICE_NAME" VARCHAR2(64 BYTE) DEFAULT NULL, 
	"GENERATOR_JOB_NAME" VARCHAR2(64 BYTE) DEFAULT NULL, 
	"FIELD_1" NUMBER, 
	"FIELD_2" TIMESTAMP (6) WITH TIME ZONE, 
	"FIELD_3" VARCHAR2(2000 BYTE) DEFAULT NULL
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
  GRANT SELECT ON "SYS"."KET$_CLIENT_CONFIG" TO "IMP_FULL_DATABASE";
  GRANT UPDATE ("FIELD_3") ON "SYS"."KET$_CLIENT_CONFIG" TO "IMP_FULL_DATABASE";
  GRANT UPDATE ("FIELD_2") ON "SYS"."KET$_CLIENT_CONFIG" TO "IMP_FULL_DATABASE";
  GRANT UPDATE ("FIELD_1") ON "SYS"."KET$_CLIENT_CONFIG" TO "IMP_FULL_DATABASE";
