--------------------------------------------------------
--  DDL for Table KET$_CLIENT_TASKS
--------------------------------------------------------

  CREATE TABLE "SYS"."KET$_CLIENT_TASKS" SHARING=METADATA 
   (	"CLIENT_ID" NUMBER, 
	"OPERATION_ID" NUMBER, 
	"TARGET_TYPE" NUMBER, 
	"TARGET_NAME" VARCHAR2(513 BYTE), 
	"ATTRIBUTES" NUMBER DEFAULT 0, 
	"ATTRIBUTES_OVERRIDE" NUMBER DEFAULT 0, 
	"TASK_PRIORITY" NUMBER DEFAULT 0, 
	"PRIORITY_OVERRIDE" NUMBER DEFAULT 0, 
	"STATUS" NUMBER DEFAULT 0, 
	"ARG_4" VARCHAR2(1024 BYTE), 
	"ARG_5" VARCHAR2(1024 BYTE), 
	"ARG_6" VARCHAR2(1024 BYTE), 
	"WINDOW_NAME" VARCHAR2(65 BYTE), 
	"CURR_JOB_NAME" VARCHAR2(65 BYTE), 
	"CURR_WIN_START" TIMESTAMP (6) WITH TIME ZONE, 
	"EST_TYPE" NUMBER DEFAULT 0, 
	"EST_WEIGHT" NUMBER, 
	"EST_DURATION" NUMBER, 
	"EST_CPU_TIME" NUMBER, 
	"EST_TEMP" NUMBER, 
	"EST_DOP" NUMBER, 
	"EST_IO_RATE" NUMBER, 
	"EST_UNDO_RATE" NUMBER, 
	"RETRY_COUNT" NUMBER DEFAULT 0, 
	"GOOD_COUNT" NUMBER DEFAULT 0, 
	"LG_JOB_LOG_ID" NUMBER DEFAULT 0, 
	"LG_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"LG_PRIORITY" NUMBER, 
	"LG_DURATION" NUMBER, 
	"LG_CPU_TIME" NUMBER, 
	"LG_TEMP" NUMBER, 
	"LG_DOP" NUMBER, 
	"LG_IO_RATE" NUMBER, 
	"LG_UNDO_RATE" NUMBER, 
	"LG_CPU_WAIT" NUMBER, 
	"LG_IO_WAIT" NUMBER, 
	"LG_UNDO_WAIT" NUMBER, 
	"LG_TEMP_WAIT" NUMBER, 
	"LG_CONCURRENCY" NUMBER, 
	"LG_CONTENTION" NUMBER, 
	"LT_JOB_LOG_ID" NUMBER DEFAULT 0, 
	"LT_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"LT_PRIORITY" NUMBER DEFAULT 0, 
	"LT_TERM_CODE" NUMBER DEFAULT 0, 
	"LT_ERROR" NUMBER DEFAULT 0, 
	"LT_DURATION" NUMBER, 
	"LT_CPU_TIME" NUMBER, 
	"LT_TEMP" NUMBER, 
	"LT_DOP" NUMBER, 
	"LT_IO_RATE" NUMBER, 
	"LT_UNDO_RATE" NUMBER, 
	"LT_CPU_WAIT" NUMBER, 
	"LT_IO_WAIT" NUMBER, 
	"LT_UNDO_WAIT" NUMBER, 
	"LT_TEMP_WAIT" NUMBER, 
	"LT_CONCURRENCY" NUMBER, 
	"LT_CONTENTION" NUMBER, 
	"MG_DURATION" NUMBER DEFAULT 0, 
	"MG_CPU_TIME" NUMBER DEFAULT 0, 
	"MG_TEMP" NUMBER DEFAULT 0, 
	"MG_DOP" NUMBER DEFAULT 0, 
	"MG_IO_RATE" NUMBER DEFAULT 0, 
	"MG_UNDO_RATE" NUMBER DEFAULT 0, 
	"MG_CPU_WAIT" NUMBER DEFAULT 0, 
	"MG_IO_WAIT" NUMBER DEFAULT 0, 
	"MG_UNDO_WAIT" NUMBER DEFAULT 0, 
	"MG_TEMP_WAIT" NUMBER DEFAULT 0, 
	"MG_CONCURRENCY" NUMBER DEFAULT 0, 
	"MG_CONTENTION" NUMBER DEFAULT 0, 
	"INFO_FIELD_1" VARCHAR2(4000 BYTE), 
	"INFO_FIELD_2" CLOB, 
	"INFO_FIELD_3" NUMBER, 
	"INFO_FIELD_4" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 LOB ("INFO_FIELD_2") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
