--------------------------------------------------------
--  DDL for Table KET$_AUTOTASK_STATUS
--------------------------------------------------------

  CREATE TABLE "SYS"."KET$_AUTOTASK_STATUS" SHARING=METADATA 
   (	"DUMMY_KEY" NUMBER, 
	"AUTOTASK_STATUS" NUMBER, 
	"ABA_STATE" NUMBER, 
	"ABA_STATE_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"ABA_OS_PID" VARCHAR2(64 BYTE), 
	"ABA_START_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"MW_NAME" VARCHAR2(64 BYTE), 
	"MW_START_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"MW_RECORD_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"INSTANCE_NAME" VARCHAR2(16 BYTE), 
	"RECONCILE_TIME" TIMESTAMP (6) WITH TIME ZONE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
