--------------------------------------------------------
--  DDL for Table KOPM$
--------------------------------------------------------

  CREATE TABLE "SYS"."KOPM$" SHARING=METADATA 
   (	"NAME" VARCHAR2(128 BYTE), 
	"LENGTH" NUMBER, 
	"METADATA" RAW(255)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  GRANT SELECT ON "SYS"."KOPM$" TO "MDSYS";
