--------------------------------------------------------
--  DDL for Table KU$_SHARD_DOMIDX_NAMEMAP
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "SYS"."KU$_SHARD_DOMIDX_NAMEMAP" SHARING=METADATA 
   (	"OWNER" VARCHAR2(128 BYTE) DEFAULT null, 
	"SOURCE_NAME" VARCHAR2(128 BYTE) DEFAULT null, 
	"TARGET_NAME" VARCHAR2(128 BYTE) DEFAULT null, 
	"TYPE_NAME" VARCHAR2(128 BYTE) DEFAULT null, 
	"PART_NAME" VARCHAR2(128 BYTE) DEFAULT null    -- partition name

   ) ON COMMIT PRESERVE ROWS ;
  GRANT INSERT ON "SYS"."KU$_SHARD_DOMIDX_NAMEMAP" TO PUBLIC;
  GRANT READ ON "SYS"."KU$_SHARD_DOMIDX_NAMEMAP" TO PUBLIC;
