--------------------------------------------------------
--  DDL for Table KU$_LIST_FILTER_TEMP_2
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "SYS"."KU$_LIST_FILTER_TEMP_2" SHARING=METADATA 
   (	"PROCESS_ORDER" NUMBER, 
	"DUPLICATE" NUMBER, 
	"OBJECT_SCHEMA" VARCHAR2(128 BYTE), 
	"OBJECT_NAME" VARCHAR2(500 BYTE), 
	"BASE_PROCESS_ORDER" NUMBER, 
	"PARENT_PROCESS_ORDER" NUMBER
   ) ON COMMIT PRESERVE ROWS ;
  GRANT DELETE ON "SYS"."KU$_LIST_FILTER_TEMP_2" TO PUBLIC;
  GRANT INSERT ON "SYS"."KU$_LIST_FILTER_TEMP_2" TO PUBLIC;
  GRANT SELECT ON "SYS"."KU$_LIST_FILTER_TEMP_2" TO PUBLIC;
