--------------------------------------------------------
--  DDL for Table KU_UTLUSE
--------------------------------------------------------

  CREATE TABLE "SYS"."KU_UTLUSE" SHARING=METADATA 
   (	"UTLNAME" VARCHAR2(50 BYTE), 
	"USECNT" NUMBER, 
	"ENCRYPTCNT" NUMBER, 
	"ENCRYPT128" NUMBER, 
	"ENCRYPT192" NUMBER, 
	"ENCRYPT256" NUMBER, 
	"ENCRYPTPWD" NUMBER, 
	"ENCRYPTDUAL" NUMBER, 
	"ENCRYPTTRAN" NUMBER, 
	"COMPRESSCNT" NUMBER, 
	"COMPRESSBAS" NUMBER, 
	"COMPRESSLOW" NUMBER, 
	"COMPRESSMED" NUMBER, 
	"COMPRESSHGH" NUMBER, 
	"PARALLELCNT" NUMBER, 
	"LAST_USED" TIMESTAMP (6), 
	"FULLTTSCNT" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
