--------------------------------------------------------
--  DDL for Type LCR_EXTRA_ATTRIBUTE_VALUES_T
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "SYS"."LCR_EXTRA_ATTRIBUTE_VALUES_T" 

/

  GRANT EXECUTE ON "SYS"."LCR_EXTRA_ATTRIBUTE_VALUES_T" TO "XDB";
  GRANT EXECUTE ON "SYS"."LCR_EXTRA_ATTRIBUTE_VALUES_T" TO PUBLIC WITH GRANT OPTION;
