--------------------------------------------------------
--  Constraints for Table LINK_SOURCES$
--------------------------------------------------------

  ALTER TABLE "SYS"."LINK_SOURCES$" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LINK_SOURCES$" MODIFY ("USER#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LINK_SOURCES$" MODIFY ("FIRST_LOGON_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LINK_SOURCES$" MODIFY ("LAST_LOGON_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LINK_SOURCES$" MODIFY ("LOGON_COUNT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LINK_SOURCES$" MODIFY ("DB_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LINK_SOURCES$" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LINK_SOURCES$" ADD PRIMARY KEY ("SOURCE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
