--------------------------------------------------------
--  DDL for Table LINK_SOURCES$
--------------------------------------------------------

  CREATE TABLE "SYS"."LINK_SOURCES$" SHARING=METADATA 
   (	"SOURCE_ID" NUMBER, 
	"USERNAME" VARCHAR2(128 BYTE), 
	"USER#" NUMBER, 
	"FIRST_LOGON_TIME" TIMESTAMP (6), 
	"LAST_LOGON_TIME" TIMESTAMP (6), 
	"LOGON_COUNT" NUMBER, 
	"DB_NAME" VARCHAR2(256 BYTE), 
	"DBID" NUMBER, 
	"HOST_NAME" VARCHAR2(256 BYTE), 
	"IP_ADDRESS" VARCHAR2(128 BYTE), 
	"PROTOCOL" VARCHAR2(64 BYTE), 
	"DB_UNIQUE_NAME" VARCHAR2(256 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
