REM INSERTING into SYS.LINK$
SET DEFINE OFF;
Insert into SYS.LINK$ (OWNER#,NAME,CTIME,HOST,USERID,PASSWORD,FLAG,AUTHUSR,AUTHPWD,PASSWORDX,AUTHPWDX) values (0,'SYS_HUB',to_date('30-MAY-19','DD-MON-RR'),'SEEDDATA',null,null,0,null,null,null,null);
Insert into SYS.LINK$ (OWNER#,NAME,CTIME,HOST,USERID,PASSWORD,FLAG,AUTHUSR,AUTHPWD,PASSWORDX,AUTHPWDX) values (1,'DBMS_CLRDBLINK',to_date('25-NOV-24','DD-MON-RR'),'ORACLR_CONNECTION_DATA',null,null,0,null,null,null,null);
