--------------------------------------------------------
--  DDL for Table LINK$
--------------------------------------------------------

  CREATE TABLE "SYS"."LINK$" SHARING=METADATA 
   (	"OWNER#" NUMBER, 
	"NAME" VARCHAR2(128 BYTE), 
	"CTIME" DATE, 
	"HOST" VARCHAR2(2000 BYTE), 
	"USERID" VARCHAR2(128 BYTE), 
	"PASSWORD" VARCHAR2(128 BYTE), 
	"FLAG" NUMBER, 
	"AUTHUSR" VARCHAR2(128 BYTE), 
	"AUTHPWD" VARCHAR2(128 BYTE), 
	"PASSWORDX" RAW(128), 
	"AUTHPWDX" RAW(128)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
