--------------------------------------------------------
--  Constraints for Table LOB$
--------------------------------------------------------

  ALTER TABLE "SYS"."LOB$" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOB$" MODIFY ("COL#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOB$" MODIFY ("INTCOL#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOB$" MODIFY ("LOBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOB$" MODIFY ("PART#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOB$" MODIFY ("IND#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOB$" MODIFY ("TS#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOB$" MODIFY ("FILE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOB$" MODIFY ("BLOCK#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOB$" MODIFY ("CHUNK" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOB$" MODIFY ("PCTVERSION$" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOB$" MODIFY ("FLAGS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOB$" MODIFY ("PROPERTY" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOB$" MODIFY ("RETENTION" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOB$" MODIFY ("FREEPOOLS" NOT NULL ENABLE);
