--------------------------------------------------------
--  Constraints for Table LOBCOMPPART$
--------------------------------------------------------

  ALTER TABLE "SYS"."LOBCOMPPART$" MODIFY ("PARTOBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOBCOMPPART$" MODIFY ("LOBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOBCOMPPART$" MODIFY ("TABPARTOBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOBCOMPPART$" MODIFY ("INDPARTOBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOBCOMPPART$" MODIFY ("PART#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOBCOMPPART$" MODIFY ("DEFCHUNK" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOBCOMPPART$" MODIFY ("DEFPCTVER$" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOBCOMPPART$" MODIFY ("DEFFLAGS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOBCOMPPART$" MODIFY ("DEFPRO" NOT NULL ENABLE);
