--------------------------------------------------------
--  DDL for Table LOBCOMPPART$
--------------------------------------------------------

  CREATE TABLE "SYS"."LOBCOMPPART$" SHARING=METADATA 
   (	"PARTOBJ#" NUMBER, 
	"LOBJ#" NUMBER, 
	"TABPARTOBJ#" NUMBER, 
	"INDPARTOBJ#" NUMBER, 
	"PART#" NUMBER, 
	"DEFTS#" NUMBER, 
	"DEFCHUNK" NUMBER, 
	"DEFPCTVER$" NUMBER, 
	"DEFFLAGS" NUMBER, 
	"DEFPRO" NUMBER, 
	"DEFINIEXTS" NUMBER, 
	"DEFEXTSIZE" NUMBER, 
	"DEFMINEXTS" NUMBER, 
	"DEFMAXEXTS" NUMBER, 
	"DEFEXTPCT" NUMBER, 
	"DEFLISTS" NUMBER, 
	"DEFGROUPS" NUMBER, 
	"DEFBUFPOOL" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"DEFMAXSIZE" NUMBER, 
	"DEFRETENTION" NUMBER, 
	"DEFMINTIME" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
