--------------------------------------------------------
--  Constraints for Table LOBFRAG$
--------------------------------------------------------

  ALTER TABLE "SYS"."LOBFRAG$" MODIFY ("FRAGOBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOBFRAG$" MODIFY ("PARENTOBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOBFRAG$" MODIFY ("TABFRAGOBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOBFRAG$" MODIFY ("INDFRAGOBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOBFRAG$" MODIFY ("FRAG#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOBFRAG$" MODIFY ("TS#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOBFRAG$" MODIFY ("FILE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOBFRAG$" MODIFY ("BLOCK#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOBFRAG$" MODIFY ("CHUNK" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOBFRAG$" MODIFY ("PCTVERSION$" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOBFRAG$" MODIFY ("FRAGFLAGS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOBFRAG$" MODIFY ("FRAGPRO" NOT NULL ENABLE);
