--------------------------------------------------------
--  DDL for Table LOCKDOWN_PROF$
--------------------------------------------------------

  CREATE TABLE "SYS"."LOCKDOWN_PROF$" SHARING=METADATA 
   (	"PROF#" NUMBER, 
	"RULETYP" VARCHAR2(128 BYTE), 
	"RULETYP#" NUMBER, 
	"RULEVAL" VARCHAR2(128 BYTE), 
	"RULEVAL#" NUMBER, 
	"CLAUSE" VARCHAR2(128 BYTE), 
	"OPTION$" VARCHAR2(128 BYTE), 
	"STATUS" NUMBER, 
	"LEVEL#" NUMBER, 
	"VALUE$" VARCHAR2(4000 BYTE), 
	"LTIME" TIMESTAMP (6), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" NUMBER, 
	"SPARE5" TIMESTAMP (6), 
	"SPARE6" VARCHAR2(128 BYTE), 
	"SPARE7" VARCHAR2(128 BYTE), 
	"SPARE8" VARCHAR2(4000 BYTE), 
	"SPARE9" VARCHAR2(4000 BYTE), 
	"MINVAL$" VARCHAR2(4000 BYTE), 
	"MAXVAL$" VARCHAR2(4000 BYTE), 
	"LIST$" VARCHAR2(4000 BYTE), 
	"CON_UID" NUMBER, 
	"USERTYP$" NUMBER, 
	"EXUSERLIST" CLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("EXUSERLIST") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
