--------------------------------------------------------
--  DDL for Table LOGMNRG_LOGMNR_BUILDLOG
--------------------------------------------------------

  CREATE TABLE "SYS"."LOGMNRG_LOGMNR_BUILDLOG" SHARING=METADATA 
   (	"BUILD_DATE" VARCHAR2(20 BYTE), 
	"DB_TXN_SCNBAS" NUMBER, 
	"DB_TXN_SCNWRP" NUMBER, 
	"CURRENT_BUILD_STATE" NUMBER, 
	"COMPLETION_STATUS" NUMBER, 
	"MARKED_LOG_FILE_LOW_SCN" NUMBER, 
	"CDB_XID" VARCHAR2(22 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" VARCHAR2(4000 BYTE), 
	"INITIAL_XID" VARCHAR2(22 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
