--------------------------------------------------------
--  Constraints for Table LOGMNRG_SUBCOLTYPE$
--------------------------------------------------------

  ALTER TABLE "SYS"."LOGMNRG_SUBCOLTYPE$" MODIFY ("INTCOL#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOGMNRG_SUBCOLTYPE$" MODIFY ("TOID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOGMNRG_SUBCOLTYPE$" MODIFY ("VERSION#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOGMNRG_SUBCOLTYPE$" MODIFY ("OBJ#" NOT NULL ENABLE);
