--------------------------------------------------------
--  Constraints for Table LOGMNRG_CONTAINER$
--------------------------------------------------------

  ALTER TABLE "SYS"."LOGMNRG_CONTAINER$" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOGMNRG_CONTAINER$" MODIFY ("CON_ID#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOGMNRG_CONTAINER$" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOGMNRG_CONTAINER$" MODIFY ("CON_UID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOGMNRG_CONTAINER$" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOGMNRG_CONTAINER$" MODIFY ("CREATE_SCNWRP" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LOGMNRG_CONTAINER$" MODIFY ("CREATE_SCNBAS" NOT NULL ENABLE);
