--------------------------------------------------------
--  DDL for Table LOGMNRG_SHARD_TS
--------------------------------------------------------

  CREATE TABLE "SYS"."LOGMNRG_SHARD_TS" SHARING=METADATA 
   (	"TABLESPACE_NAME" VARCHAR2(30 BYTE), 
	"CHUNK_NUMBER" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
