--------------------------------------------------------
--  Constraints for Table LTXID_TRANS
--------------------------------------------------------

  ALTER TABLE "SYS"."LTXID_TRANS" MODIFY ("MAJ_VERSION" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LTXID_TRANS" MODIFY ("MIN_VERSION" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LTXID_TRANS" MODIFY ("INST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LTXID_TRANS" MODIFY ("DB_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LTXID_TRANS" MODIFY ("SESSION_GUID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LTXID_TRANS" MODIFY ("TXN_UID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LTXID_TRANS" MODIFY ("COMMIT_NO" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LTXID_TRANS" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LTXID_TRANS" MODIFY ("SERVICE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LTXID_TRANS" MODIFY ("STATE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LTXID_TRANS" MODIFY ("FLAGS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LTXID_TRANS" MODIFY ("REQ_FLAGS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LTXID_TRANS" MODIFY ("ERROR_CODE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."LTXID_TRANS" ADD CONSTRAINT "LTXID_TRANS$PK" PRIMARY KEY ("INST_ID", "DB_ID", "SESSION_GUID", "TXN_UID")
  USING INDEX (CREATE UNIQUE INDEX "SYS"."I_LTXID_TRANS$PK" ON "SYS"."LTXID_TRANS" ("INST_ID", "DB_ID", "SESSION_GUID", "TXN_UID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) LOCAL
 (PARTITION "LTXID_TRANS_PK_01" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ) )  ENABLE;
