--------------------------------------------------------
--  DDL for Table LTXID_TRANS
--------------------------------------------------------

  CREATE TABLE "SYS"."LTXID_TRANS" SHARING=METADATA 
   (	"MAJ_VERSION" NUMBER, 
	"MIN_VERSION" NUMBER, 
	"INST_ID" NUMBER, 
	"DB_ID" NUMBER, 
	"SESSION_GUID" RAW(64), 
	"TXN_UID" NUMBER, 
	"COMMIT_NO" NUMBER, 
	"START_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"SERVICE_ID" NUMBER, 
	"STATE" NUMBER, 
	"FLAGS" NUMBER, 
	"REQ_FLAGS" NUMBER, 
	"ERROR_CODE" NUMBER
   ) PCTFREE 40 PCTUSED 40 INITRANS 20 MAXTRANS 255 
  STORAGE(INITIAL 1048576 NEXT 1048576
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARTITION BY LIST ("INST_ID") 
 (PARTITION "LTXID_TRANS_1"  VALUES (1) 
  PCTFREE 40 PCTUSED 40 INITRANS 20 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 1048576 NEXT 1048576
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ) ;
