--------------------------------------------------------
--  DDL for Table MAP_COMPLIST$
--------------------------------------------------------

  CREATE TABLE "SYS"."MAP_COMPLIST$" SHARING=METADATA 
   (	"ELEM_IDX" NUMBER, 
	"NUM_COMP" NUMBER, 
	"COMP1_NAME" VARCHAR2(128 BYTE), 
	"COMP1_VAL" VARCHAR2(2000 BYTE), 
	"COMP2_NAME" VARCHAR2(128 BYTE), 
	"COMP2_VAL" VARCHAR2(2000 BYTE), 
	"COMP3_NAME" VARCHAR2(128 BYTE), 
	"COMP3_VAL" VARCHAR2(2000 BYTE), 
	"COMP4_NAME" VARCHAR2(128 BYTE), 
	"COMP4_VAL" VARCHAR2(2000 BYTE), 
	"COMP5_NAME" VARCHAR2(128 BYTE), 
	"COMP5_VAL" VARCHAR2(2000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
