--------------------------------------------------------
--  DDL for Table MAP_EXTELEMENT$
--------------------------------------------------------

  CREATE TABLE "SYS"."MAP_EXTELEMENT$" SHARING=METADATA 
   (	"ELEM_IDX" NUMBER, 
	"NUM_ATTRB" NUMBER, 
	"ATTRB1_NAME" VARCHAR2(128 BYTE), 
	"ATTRB1_VAL" VARCHAR2(128 BYTE), 
	"ATTRB2_NAME" VARCHAR2(128 BYTE), 
	"ATTRB2_VAL" VARCHAR2(128 BYTE), 
	"ATTRB3_NAME" VARCHAR2(128 BYTE), 
	"ATTRB3_VAL" VARCHAR2(128 BYTE), 
	"ATTRB4_NAME" VARCHAR2(128 BYTE), 
	"ATTRB4_VAL" VARCHAR2(128 BYTE), 
	"ATTRB5_NAME" VARCHAR2(128 BYTE), 
	"ATTRB5_VAL" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
