--------------------------------------------------------
--  DDL for Table MAP_ELEMENT$
--------------------------------------------------------

  CREATE TABLE "SYS"."MAP_ELEMENT$" SHARING=METADATA 
   (	"ELEM_NAME" VARCHAR2(2000 BYTE), 
	"ELEM_CFGID" VARCHAR2(2000 BYTE), 
	"ELEM_TYPE" NUMBER, 
	"ELEM_IDX" NUMBER, 
	"ELEM_SIZE" NUMBER, 
	"ELEM_NSUBELEM" NUMBER, 
	"ELEM_DESCR" VARCHAR2(2000 BYTE), 
	"STRIPE_SIZE" NUMBER, 
	"ELEM_FLAGS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
