--------------------------------------------------------
--  DDL for Table MAP_OBJECT
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "SYS"."MAP_OBJECT" SHARING=METADATA 
   (	"OBJECT_NAME" VARCHAR2(2000 BYTE), 
	"OBJECT_OWNER" VARCHAR2(2000 BYTE), 
	"OBJECT_TYPE" VARCHAR2(2000 BYTE), 
	"FILE_MAP_IDX" NUMBER, 
	"DEPTH" NUMBER, 
	"ELEM_IDX" NUMBER, 
	"CU_SIZE" NUMBER, 
	"STRIDE" NUMBER, 
	"NUM_CU" NUMBER, 
	"ELEM_OFFSET" NUMBER, 
	"FILE_OFFSET" NUMBER, 
	"DATA_TYPE" VARCHAR2(2000 BYTE), 
	"PARITY_POS" NUMBER, 
	"PARITY_PERIOD" NUMBER
   ) ON COMMIT PRESERVE ROWS ;
  GRANT SELECT ON "SYS"."MAP_OBJECT" TO "SELECT_CATALOG_ROLE";
  GRANT DELETE ON "SYS"."MAP_OBJECT" TO "DBA";
  GRANT INSERT ON "SYS"."MAP_OBJECT" TO "DBA";
  GRANT SELECT ON "SYS"."MAP_OBJECT" TO "DBA";
  GRANT UPDATE ON "SYS"."MAP_OBJECT" TO "DBA";
