--------------------------------------------------------
--  DDL for Table MD_TARGET_ALL_ERRORS
--------------------------------------------------------

  CREATE TABLE "SYS"."MD_TARGET_ALL_ERRORS" 
   (	"OWNER" VARCHAR2(128 BYTE), 
	"NAME" VARCHAR2(128 BYTE), 
	"TYPE" VARCHAR2(12 BYTE), 
	"SEQUENCE" NUMBER, 
	"LINE" NUMBER, 
	"POSITION" NUMBER, 
	"TEXT" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE" VARCHAR2(9 BYTE), 
	"MESSAGE_NUMBER" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
