--------------------------------------------------------
--  Constraints for Table METANAMETRANS$
--------------------------------------------------------

  ALTER TABLE "SYS"."METANAMETRANS$" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."METANAMETRANS$" MODIFY ("HTYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."METANAMETRANS$" MODIFY ("PTYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."METANAMETRANS$" MODIFY ("SEQ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."METANAMETRANS$" MODIFY ("PROPERTIES" NOT NULL ENABLE);
  ALTER TABLE "SYS"."METANAMETRANS$" MODIFY ("MODEL" NOT NULL ENABLE);
