--------------------------------------------------------
--  DDL for Table METAAUDIT$
--------------------------------------------------------

  CREATE TABLE "SYS"."METAAUDIT$" SHARING=DATA 
   (	"VERSION" VARCHAR2(20 BYTE), 
	"OPTION#" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
