--------------------------------------------------------
--  Constraints for Table METASCRIPT$
--------------------------------------------------------

  ALTER TABLE "SYS"."METASCRIPT$" MODIFY ("HTYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."METASCRIPT$" MODIFY ("PTYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."METASCRIPT$" MODIFY ("SEQ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."METASCRIPT$" MODIFY ("RSEQ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."METASCRIPT$" MODIFY ("LTYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."METASCRIPT$" MODIFY ("PROPERTIES" NOT NULL ENABLE);
  ALTER TABLE "SYS"."METASCRIPT$" MODIFY ("MODEL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."METASCRIPT$" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "SYS"."METASCRIPT$" MODIFY ("SOSEQ#" NOT NULL ENABLE);
