--------------------------------------------------------
--  DDL for Table METANAMETRANS$
--------------------------------------------------------

  CREATE TABLE "SYS"."METANAMETRANS$" SHARING=DATA 
   (	"NAME" VARCHAR2(200 BYTE), 
	"HTYPE" VARCHAR2(128 BYTE), 
	"PTYPE" VARCHAR2(128 BYTE), 
	"SEQ#" NUMBER, 
	"PROPERTIES" NUMBER, 
	"MODEL" VARCHAR2(128 BYTE), 
	"DESCRIP" VARCHAR2(2000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
