--------------------------------------------------------
--  DDL for Table METAFILTER$
--------------------------------------------------------

  CREATE TABLE "SYS"."METAFILTER$" SHARING=DATA 
   (	"FILTER" VARCHAR2(128 BYTE), 
	"TYPE" VARCHAR2(128 BYTE), 
	"MODEL" VARCHAR2(128 BYTE), 
	"PROPERTIES" NUMBER, 
	"VIEW_ATTR" NUMBER, 
	"ATTRNAME" VARCHAR2(2000 BYTE), 
	"DEFAULT_VAL" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
