--------------------------------------------------------
--  DDL for Table METASCRIPT$
--------------------------------------------------------

  CREATE TABLE "SYS"."METASCRIPT$" SHARING=DATA 
   (	"HTYPE" VARCHAR2(128 BYTE), 
	"PTYPE" VARCHAR2(128 BYTE), 
	"SEQ#" NUMBER, 
	"RSEQ#" NUMBER, 
	"LTYPE" VARCHAR2(128 BYTE), 
	"PROPERTIES" NUMBER, 
	"MODEL" VARCHAR2(128 BYTE), 
	"VERSION" NUMBER, 
	"SOSEQ#" NUMBER, 
	"R1SEQ#" NUMBER, 
	"R2SEQ#" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
