--------------------------------------------------------
--  DDL for Table METASCRIPTFILTER$
--------------------------------------------------------

  CREATE TABLE "SYS"."METASCRIPTFILTER$" SHARING=DATA 
   (	"HTYPE" VARCHAR2(128 BYTE), 
	"PTYPE" VARCHAR2(128 BYTE), 
	"SEQ#" NUMBER, 
	"LTYPE" VARCHAR2(128 BYTE), 
	"FILTER" VARCHAR2(128 BYTE), 
	"PFILTER" VARCHAR2(128 BYTE), 
	"VCVAL" VARCHAR2(2000 BYTE), 
	"BVAL" NUMBER, 
	"NVAL" NUMBER, 
	"PROPERTIES" NUMBER DEFAULT 0, 
	"MODEL" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
