--------------------------------------------------------
--  Constraints for Table METAFILTER$
--------------------------------------------------------

  ALTER TABLE "SYS"."METAFILTER$" MODIFY ("FILTER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."METAFILTER$" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."METAFILTER$" MODIFY ("MODEL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."METAFILTER$" MODIFY ("PROPERTIES" NOT NULL ENABLE);
  ALTER TABLE "SYS"."METAFILTER$" MODIFY ("VIEW_ATTR" NOT NULL ENABLE);
