--------------------------------------------------------
--  DDL for Table METAXSLPARAM$
--------------------------------------------------------

  CREATE TABLE "SYS"."METAXSLPARAM$" SHARING=DATA 
   (	"MODEL" VARCHAR2(128 BYTE), 
	"TRANSFORM" VARCHAR2(128 BYTE), 
	"TYPE" VARCHAR2(128 BYTE), 
	"PARAM" VARCHAR2(128 BYTE), 
	"DEFAULT_VAL" VARCHAR2(2000 BYTE), 
	"PROPERTIES" NUMBER DEFAULT 0, 
	"PARSE_ATTR" VARCHAR2(2000 BYTE), 
	"DATATYPE" NUMBER, 
	"LOWER_BOUND" NUMBER, 
	"UPPER_BOUND" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
