--------------------------------------------------------
--  Constraints for Table METAXSLPARAM$
--------------------------------------------------------

  ALTER TABLE "SYS"."METAXSLPARAM$" MODIFY ("MODEL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."METAXSLPARAM$" MODIFY ("TRANSFORM" NOT NULL ENABLE);
  ALTER TABLE "SYS"."METAXSLPARAM$" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."METAXSLPARAM$" MODIFY ("PARAM" NOT NULL ENABLE);
  ALTER TABLE "SYS"."METAXSLPARAM$" MODIFY ("PROPERTIES" NOT NULL ENABLE);
