--------------------------------------------------------
--  Constraints for Table METASCRIPTFILTER$
--------------------------------------------------------

  ALTER TABLE "SYS"."METASCRIPTFILTER$" MODIFY ("HTYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."METASCRIPTFILTER$" MODIFY ("PTYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."METASCRIPTFILTER$" MODIFY ("SEQ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."METASCRIPTFILTER$" MODIFY ("LTYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."METASCRIPTFILTER$" MODIFY ("FILTER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."METASCRIPTFILTER$" MODIFY ("PROPERTIES" NOT NULL ENABLE);
  ALTER TABLE "SYS"."METASCRIPTFILTER$" MODIFY ("MODEL" NOT NULL ENABLE);
