--------------------------------------------------------
--  Constraints for Table METHOD$
--------------------------------------------------------

  ALTER TABLE "SYS"."METHOD$" MODIFY ("TOID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."METHOD$" MODIFY ("VERSION#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."METHOD$" MODIFY ("METHOD#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."METHOD$" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."METHOD$" MODIFY ("PROPERTIES" NOT NULL ENABLE);
  ALTER TABLE "SYS"."METHOD$" MODIFY ("PARAMETERS#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."METHOD$" MODIFY ("RESULTS" NOT NULL ENABLE);
