--------------------------------------------------------
--  DDL for Table MLOG$
--------------------------------------------------------

  CREATE TABLE "SYS"."MLOG$" SHARING=METADATA 
   (	"MOWNER" VARCHAR2(128 BYTE), 
	"MASTER" VARCHAR2(128 BYTE), 
	"OLDEST" DATE, 
	"OLDEST_PK" DATE, 
	"OLDEST_SEQ" DATE, 
	"OSCN" NUMBER, 
	"YOUNGEST" DATE, 
	"YSCN" NUMBER, 
	"LOG" VARCHAR2(128 BYTE), 
	"TRIG" VARCHAR2(128 BYTE), 
	"FLAG" NUMBER, 
	"MTIME" DATE, 
	"TEMP_LOG" VARCHAR2(128 BYTE), 
	"OLDEST_OID" DATE, 
	"OLDEST_NEW" DATE, 
	"PURGE_START" DATE, 
	"PURGE_NEXT" VARCHAR2(200 BYTE), 
	"PURGE_JOB" VARCHAR2(128 BYTE), 
	"LAST_PURGE_DATE" DATE, 
	"LAST_PURGE_STATUS" NUMBER, 
	"ROWS_PURGED" NUMBER, 
	"OSCN_PK" NUMBER, 
	"OSCN_SEQ" NUMBER, 
	"OSCN_OID" NUMBER, 
	"OSCN_NEW" NUMBER, 
	"PARTDOBJ#" VARCHAR2(4000 BYTE)
   ) CLUSTER "SYS"."C_MLOG#" ("MASTER", "MOWNER");
