--------------------------------------------------------
--  DDL for Table MODELPART$
--------------------------------------------------------

  CREATE TABLE "SYS"."MODELPART$" SHARING=METADATA 
   (	"MOD#" NUMBER, 
	"OBJ#" NUMBER, 
	"PART#" NUMBER, 
	"POS#" NUMBER, 
	"BHIBOUNDVAL" BLOB, 
	"HIBOUNDLEN" NUMBER, 
	"HIBOUNDVAL" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( MAXEXTENTS 2147483645)
  TABLESPACE "SYSTEM" 
 LOB ("BHIBOUNDVAL") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
