--------------------------------------------------------
--  DDL for Table MODELXFM$
--------------------------------------------------------

  CREATE TABLE "SYS"."MODELXFM$" SHARING=METADATA 
   (	"MOD#" NUMBER, 
	"ATTR" VARCHAR2(128 BYTE), 
	"SUBN" VARCHAR2(4000 BYTE), 
	"PROPERTIES" NUMBER, 
	"IDTY" NUMBER, 
	"IBFL" NUMBER, 
	"DTYP" NUMBER, 
	"BUFL" NUMBER, 
	"ATTRSPEC" VARCHAR2(4000 BYTE), 
	"EXPR" CLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( MAXEXTENTS 2147483645)
  TABLESPACE "SYSTEM" 
 LOB ("EXPR") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
