--------------------------------------------------------
--  DDL for Table MODELGTTRAW$
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "SYS"."MODELGTTRAW$" SHARING=METADATA 
   (	"PARTNUMBER" NUMBER, 
	"CONTROLVAL" NUMBER, 
	"SLAVENUMBER" NUMBER, 
	"ROWNUMBER" NUMBER, 
	"CHUNKNUMBER" NUMBER, 
	"CHUNKDATA" RAW(2000)
   ) ON COMMIT PRESERVE ROWS ;
  GRANT SELECT ON "SYS"."MODELGTTRAW$" TO PUBLIC;
  GRANT INSERT ON "SYS"."MODELGTTRAW$" TO PUBLIC;
