--------------------------------------------------------
--  DDL for Table MON_MODS$
--------------------------------------------------------

  CREATE TABLE "SYS"."MON_MODS$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"INSERTS" NUMBER, 
	"UPDATES" NUMBER, 
	"DELETES" NUMBER, 
	"TIMESTAMP" DATE, 
	"FLAGS" NUMBER, 
	"DROP_SEGMENTS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 204800 NEXT 106496 MAXEXTENTS 2147483645
  PCTINCREASE 0)
  TABLESPACE "SYSTEM" ;
