--------------------------------------------------------
--  DDL for Table MON_MODS_ALL$
--------------------------------------------------------

  CREATE TABLE "SYS"."MON_MODS_ALL$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"INSERTS" NUMBER, 
	"UPDATES" NUMBER, 
	"DELETES" NUMBER, 
	"TIMESTAMP" DATE, 
	"FLAGS" NUMBER, 
	"DROP_SEGMENTS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 204800 NEXT 106496 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
