--------------------------------------------------------
--  DDL for Table MV_REFRESH_USAGE_STATS$
--------------------------------------------------------

  CREATE TABLE "SYS"."MV_REFRESH_USAGE_STATS$" SHARING=METADATA 
   (	"MV_TYPE#" VARCHAR2(10 BYTE), 
	"REFRESH_METHOD#" VARCHAR2(10 BYTE), 
	"REFRESH_MODE#" VARCHAR2(10 BYTE), 
	"OUT_OF_PLACE#" VARCHAR2(3 BYTE), 
	"ATOMIC#" VARCHAR2(3 BYTE), 
	"COUNT#" NUMBER, 
	"SEQ#" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
