--------------------------------------------------------
--  DDL for Table MVREF$_RUN_STATS
--------------------------------------------------------

  CREATE TABLE "SYS"."MVREF$_RUN_STATS" SHARING=METADATA 
   (	"RUN_OWNER_USER#" NUMBER, 
	"REFRESH_ID" NUMBER, 
	"NUM_MVS_TOTAL" NUMBER, 
	"NUM_MVS_CURRENT" NUMBER, 
	"MVIEWS" VARCHAR2(4000 BYTE), 
	"BASE_TABLES" VARCHAR2(4000 BYTE), 
	"METHOD" VARCHAR2(4000 BYTE), 
	"ROLLBACK_SEG" VARCHAR2(4000 BYTE), 
	"PUSH_DEFERRED_RPC" CHAR(1 BYTE), 
	"REFRESH_AFTER_ERRORS" CHAR(1 BYTE), 
	"PURGE_OPTION" NUMBER, 
	"PARALLELISM" NUMBER, 
	"HEAP_SIZE" NUMBER, 
	"ATOMIC_REFRESH" CHAR(1 BYTE), 
	"NESTED" CHAR(1 BYTE), 
	"OUT_OF_PLACE" CHAR(1 BYTE), 
	"NUMBER_OF_FAILURES" NUMBER, 
	"START_TIME" TIMESTAMP (6), 
	"END_TIME" TIMESTAMP (6), 
	"ELAPSED_TIME" NUMBER, 
	"LOG_SETUP_TIME" NUMBER, 
	"LOG_PURGE_TIME" NUMBER, 
	"COMPLETE_STATS_AVAILABLE" CHAR(1 BYTE), 
	"TXNFLAG" NUMBER, 
	"ON_COMMIT_FLAG" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
