--------------------------------------------------------
--  DDL for Table MVREF$_STATS
--------------------------------------------------------

  CREATE TABLE "SYS"."MVREF$_STATS" SHARING=METADATA 
   (	"MV_OBJ#" NUMBER, 
	"REFRESH_ID" NUMBER, 
	"ATOMIC_REFRESH" CHAR(1 BYTE), 
	"REFRESH_METHOD" VARCHAR2(30 BYTE), 
	"REFRESH_OPTIMIZATIONS" VARCHAR2(4000 BYTE), 
	"ADDITIONAL_EXECUTIONS" VARCHAR2(4000 BYTE), 
	"START_TIME" TIMESTAMP (6), 
	"END_TIME" TIMESTAMP (6), 
	"ELAPSED_TIME" NUMBER, 
	"LOG_SETUP_TIME" NUMBER, 
	"LOG_PURGE_TIME" NUMBER, 
	"INITIAL_NUM_ROWS" NUMBER, 
	"FINAL_NUM_ROWS" NUMBER, 
	"NUM_STEPS" NUMBER, 
	"REFMET" NUMBER, 
	"REFFLG" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
