--------------------------------------------------------
--  DDL for Table MVREF$_CHANGE_STATS
--------------------------------------------------------

  CREATE TABLE "SYS"."MVREF$_CHANGE_STATS" SHARING=METADATA 
   (	"TBL_OBJ#" NUMBER, 
	"MV_OBJ#" NUMBER, 
	"REFRESH_ID" NUMBER, 
	"NUM_ROWS_INS" NUMBER, 
	"NUM_ROWS_UPD" NUMBER, 
	"NUM_ROWS_DEL" NUMBER, 
	"NUM_ROWS_DL_INS" NUMBER, 
	"PMOPS_OCCURRED" CHAR(1 BYTE), 
	"PMOP_DETAILS" VARCHAR2(4000 BYTE), 
	"NUM_ROWS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
