--------------------------------------------------------
--  DDL for Table MVREF$_STMT_STATS
--------------------------------------------------------

  CREATE TABLE "SYS"."MVREF$_STMT_STATS" SHARING=METADATA 
   (	"MV_OBJ#" NUMBER, 
	"REFRESH_ID" NUMBER, 
	"STEP" NUMBER, 
	"SQLID" VARCHAR2(14 BYTE), 
	"STMT" CLOB, 
	"EXECUTION_TIME" NUMBER, 
	"EXECUTION_PLAN" "SYS"."XMLTYPE" 
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("STMT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 XMLTYPE COLUMN "EXECUTION_PLAN" STORE AS BASICFILE BINARY XML (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ALLOW NONSCHEMA DISALLOW ANYSCHEMA ;
