--------------------------------------------------------
--  Constraints for Table MVREF$_STMT_STATS
--------------------------------------------------------

  ALTER TABLE "SYS"."MVREF$_STMT_STATS" MODIFY ("MV_OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."MVREF$_STMT_STATS" MODIFY ("REFRESH_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."MVREF$_STMT_STATS" MODIFY ("STEP" NOT NULL ENABLE);
  ALTER TABLE "SYS"."MVREF$_STMT_STATS" MODIFY ("SQLID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."MVREF$_STMT_STATS" MODIFY ("STMT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."MVREF$_STMT_STATS" MODIFY ("EXECUTION_TIME" NOT NULL ENABLE);
