--------------------------------------------------------
--  DDL for Table NACL$_ACE_EXP_TBL
--------------------------------------------------------

  CREATE TABLE "SYS"."NACL$_ACE_EXP_TBL" SHARING=METADATA 
   (	"ACL" VARCHAR2(128 BYTE), 
	"OWNER" VARCHAR2(128 BYTE), 
	"ACE_ORDER" NUMBER, 
	"START_DATE" TIMESTAMP (6), 
	"END_DATE" TIMESTAMP (6), 
	"GRANT_TYPE" VARCHAR2(5 BYTE), 
	"INVERTED_PRINCIPAL" VARCHAR2(3 BYTE), 
	"PRINCIPAL" VARCHAR2(128 BYTE), 
	"PRINCIPAL_TYPE" VARCHAR2(16 BYTE), 
	"PRIVILEGE" VARCHAR2(128 BYTE), 
	"SECURITY_CLASS" VARCHAR2(128 BYTE), 
	"SECURITY_CLASS_OWNER" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
  GRANT SELECT ON "SYS"."NACL$_ACE_EXP_TBL" TO "SELECT_CATALOG_ROLE";
