--------------------------------------------------------
--  DDL for Index NACL$_HOST_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."NACL$_HOST_UK" ON "SYS"."NACL$_HOST" ("HOST", "LOWER_PORT", "UPPER_PORT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
