--------------------------------------------------------
--  DDL for Table NACL$_HOST_EXP_TBL
--------------------------------------------------------

  CREATE TABLE "SYS"."NACL$_HOST_EXP_TBL" SHARING=METADATA 
   (	"HOST" VARCHAR2(1000 BYTE), 
	"LOWER_PORT" NUMBER(5,0), 
	"UPPER_PORT" NUMBER(5,0), 
	"ACL_NAME" VARCHAR2(128 BYTE), 
	"ACL_OWNER" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
  GRANT SELECT ON "SYS"."NACL$_HOST_EXP_TBL" TO "SELECT_CATALOG_ROLE";
