--------------------------------------------------------
--  Constraints for Table NACL$_HOST
--------------------------------------------------------

  ALTER TABLE "SYS"."NACL$_HOST" MODIFY ("HOST" NOT NULL ENABLE);
  ALTER TABLE "SYS"."NACL$_HOST" MODIFY ("ACL#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."NACL$_HOST" ADD CONSTRAINT "NACL$_HOST_UK" UNIQUE ("HOST", "LOWER_PORT", "UPPER_PORT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
