--------------------------------------------------------
--  Constraints for Table NACL$_NAME_MAP
--------------------------------------------------------

  ALTER TABLE "SYS"."NACL$_NAME_MAP" MODIFY ("XNAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."NACL$_NAME_MAP" MODIFY ("ACL#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."NACL$_NAME_MAP" ADD CONSTRAINT "NACL$_NAME_MAP_PK" PRIMARY KEY ("ACL#")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
