--------------------------------------------------------
--  DDL for Table NCOMP_DLL$
--------------------------------------------------------

  CREATE TABLE "SYS"."NCOMP_DLL$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"VERSION" NUMBER, 
	"DLL" BLOB, 
	"DLLNAME" RAW(1024)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 16384 NEXT 106496 MAXEXTENTS 2147483645
  PCTINCREASE 0)
  TABLESPACE "SYSTEM" 
 LOB ("DLL") STORE AS BASICFILE "NATIVE_COMP_SHARED_OBJECTS"(
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE( INITIAL 1048576 NEXT 1048576 MAXEXTENTS 2147483645
  PCTINCREASE 0)) ;
