--------------------------------------------------------
--  DDL for Table NEW_LOST_WRITE_SHADOWS$
--------------------------------------------------------

  CREATE TABLE "SYS"."NEW_LOST_WRITE_SHADOWS$" SHARING=METADATA 
   (	"SHADOW_DATAFILE_RFN" NUMBER, 
	"SHADOW_DATAFILE_TSID" NUMBER, 
	"SHADOW_NUMBER_BLOCKS_ALLOC" NUMBER, 
	"SHADOW_FIRST_FREE_BLOCK" NUMBER, 
	"SHADOW_BLOCK_SIZE_BYTES" NUMBER, 
	"SHADOW_RECS_PER_BLOCK" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
