--------------------------------------------------------
--  DDL for Table NEW_LOST_WRITE_DATAFILES$
--------------------------------------------------------

  CREATE TABLE "SYS"."NEW_LOST_WRITE_DATAFILES$" SHARING=METADATA 
   (	"DATAFILE_TSID_TRACKED" NUMBER, 
	"DATAFILE_RFN_TRACKED" NUMBER, 
	"SHADOW_DATAFILE_TSID" NUMBER, 
	"SHADOW_DATAFILE_RFN" NUMBER, 
	"SHADOW_DATAFILE_OFFSET" NUMBER, 
	"NUMBER_OF_BLOCKS_ALLOCATED" NUMBER, 
	"DATAFILE_CURRENT_STATUS" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
