--------------------------------------------------------
--  DDL for Table NEW_LOST_WRITE_EXTENTS$
--------------------------------------------------------

  CREATE TABLE "SYS"."NEW_LOST_WRITE_EXTENTS$" SHARING=METADATA 
   (	"EXTENT_DATAFILE_RFN" NUMBER, 
	"EXTENT_DATAFILE_TSID" NUMBER, 
	"EXTENT_START" NUMBER, 
	"EXTENT_LENGTH_BLOCKS_2K" NUMBER, 
	"EXTENT_NEXT_BLOCK" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
