--------------------------------------------------------
--  DDL for Table NOEXP$
--------------------------------------------------------

  CREATE TABLE "SYS"."NOEXP$" SHARING=METADATA 
   (	"OWNER" VARCHAR2(128 BYTE), 
	"NAME" VARCHAR2(128 BYTE), 
	"OBJ_TYPE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  GRANT INSERT ON "SYS"."NOEXP$" TO "WMSYS";
  GRANT DELETE ON "SYS"."NOEXP$" TO "WMSYS";
