--------------------------------------------------------
--  Constraints for Table OBJ$
--------------------------------------------------------

  ALTER TABLE "SYS"."OBJ$" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OBJ$" MODIFY ("OWNER#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OBJ$" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OBJ$" MODIFY ("NAMESPACE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OBJ$" MODIFY ("TYPE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OBJ$" MODIFY ("CTIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OBJ$" MODIFY ("MTIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OBJ$" MODIFY ("STIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OBJ$" MODIFY ("STATUS" NOT NULL ENABLE);
