--------------------------------------------------------
--  DDL for Table OBJAUTH$
--------------------------------------------------------

  CREATE TABLE "SYS"."OBJAUTH$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"GRANTOR#" NUMBER, 
	"GRANTEE#" NUMBER, 
	"PRIVILEGE#" NUMBER, 
	"SEQUENCE#" NUMBER, 
	"PARENT" ROWID, 
	"OPTION$" NUMBER, 
	"COL#" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  GRANT READ ON "SYS"."OBJAUTH$" TO "DVSYS";
  GRANT READ ON "SYS"."OBJAUTH$" TO "DV_SECANALYST";
