--------------------------------------------------------
--  DDL for Table OBJECT_USAGE
--------------------------------------------------------

  CREATE TABLE "SYS"."OBJECT_USAGE" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"FLAGS" NUMBER, 
	"START_MONITORING" VARCHAR2(19 BYTE), 
	"END_MONITORING" VARCHAR2(19 BYTE)
   ) PCTFREE 10 PCTUSED 50 INITRANS 30 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
