--------------------------------------------------------
--  DDL for Table ODCI_SECOBJ$
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "SYS"."ODCI_SECOBJ$" SHARING=METADATA 
   (	"IDXSCHEMA" VARCHAR2(130 BYTE), 
	"IDXNAME" VARCHAR2(130 BYTE), 
	"SECOBJSCHEMA" VARCHAR2(130 BYTE), 
	"SECOBJNAME" VARCHAR2(130 BYTE)
   ) ON COMMIT PRESERVE ROWS ;
  GRANT INSERT ON "SYS"."ODCI_SECOBJ$" TO PUBLIC;
  GRANT SELECT ON "SYS"."ODCI_SECOBJ$" TO PUBLIC;
