--------------------------------------------------------
--  DDL for Table OFSFTAB$
--------------------------------------------------------

  CREATE TABLE "SYS"."OFSFTAB$" SHARING=METADATA 
   (	"FSTYPE" VARCHAR2(64 BYTE), 
	"FSNAME" VARCHAR2(64 BYTE), 
	"FS_METADATA_TABLE_OWNER" VARCHAR2(30 BYTE) DEFAULT 'SYS', 
	"FS_METADATA_TABLE_NAME" VARCHAR2(30 BYTE), 
	"FS_DATA_TABLE_OWNER" VARCHAR2(30 BYTE) DEFAULT 'SYS', 
	"FS_DATA_TABLE_NAME" VARCHAR2(30 BYTE), 
	"FS_CREATION_TIME" DATE DEFAULT sysdate
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
