--------------------------------------------------------
--  Constraints for Table OLAP_METADATA_PROPERTIES$
--------------------------------------------------------

  ALTER TABLE "SYS"."OLAP_METADATA_PROPERTIES$" MODIFY ("TOP_OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_METADATA_PROPERTIES$" MODIFY ("OWNING_OBJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_METADATA_PROPERTIES$" MODIFY ("OWNING_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_METADATA_PROPERTIES$" MODIFY ("PROPERTY_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_METADATA_PROPERTIES$" MODIFY ("PROPERTY_KEY" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_METADATA_PROPERTIES$" MODIFY ("PROPERTY_ORDER" NOT NULL ENABLE);
