--------------------------------------------------------
--  Constraints for Table OLAP_MEASURES$
--------------------------------------------------------

  ALTER TABLE "SYS"."OLAP_MEASURES$" MODIFY ("CUBE_OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_MEASURES$" MODIFY ("MEASURE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_MEASURES$" MODIFY ("MEASURE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_MEASURES$" MODIFY ("MEASURE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_MEASURES$" MODIFY ("TYPE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_MEASURES$" MODIFY ("LENGTH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_MEASURES$" MODIFY ("IS_STALE" NOT NULL ENABLE);
