--------------------------------------------------------
--  DDL for Table OLAP_IMPL_OPTIONS$
--------------------------------------------------------

  CREATE TABLE "SYS"."OLAP_IMPL_OPTIONS$" SHARING=METADATA 
   (	"OWNING_OBJECTID" NUMBER, 
	"OBJECT_TYPE" NUMBER, 
	"OPTION_TYPE" NUMBER, 
	"OPTION_VALUE" VARCHAR2(200 BYTE), 
	"OPTION_NUM_VALUE" NUMBER, 
	"OPTION_LONG_VALUE" VARCHAR2(1000 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" VARCHAR2(1000 BYTE), 
	"SPARE5" VARCHAR2(1000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
