--------------------------------------------------------
--  Constraints for Table OLAP_MAPPINGS$
--------------------------------------------------------

  ALTER TABLE "SYS"."OLAP_MAPPINGS$" MODIFY ("MAP_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_MAPPINGS$" MODIFY ("MAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_MAPPINGS$" MODIFY ("MAP_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_MAPPINGS$" MODIFY ("MAPPING_OWNER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_MAPPINGS$" MODIFY ("MAPPING_OWNER_TYPE" NOT NULL ENABLE);
