--------------------------------------------------------
--  Constraints for Table OLAP_METADATA_DEPENDENCIES$
--------------------------------------------------------

  ALTER TABLE "SYS"."OLAP_METADATA_DEPENDENCIES$" MODIFY ("D_TOP_OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_METADATA_DEPENDENCIES$" MODIFY ("D_OBJ_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_METADATA_DEPENDENCIES$" MODIFY ("P_OWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_METADATA_DEPENDENCIES$" MODIFY ("P_TOP_OBJ_NAME" NOT NULL ENABLE);
