--------------------------------------------------------
--  DDL for Table OLAP_CUBE_BUILD_PROCESSES$
--------------------------------------------------------

  CREATE TABLE "SYS"."OLAP_CUBE_BUILD_PROCESSES$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"AUDIT$" VARCHAR2(38 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" VARCHAR2(1000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
