--------------------------------------------------------
--  DDL for Table OLAP_CALCULATED_MEMBERS$
--------------------------------------------------------

  CREATE TABLE "SYS"."OLAP_CALCULATED_MEMBERS$" SHARING=METADATA 
   (	"DIM_OBJ#" NUMBER, 
	"MEMBER_NAME" VARCHAR2(128 BYTE), 
	"MEMBER_ID" NUMBER, 
	"CONTAINER_DIM_ID" NUMBER, 
	"CONTAINER_DIM_TYPE" NUMBER, 
	"PARENT_MEMBER_NAME" VARCHAR2(100 BYTE), 
	"PARENT_CONTAINER_ID" NUMBER, 
	"IS_CUSTOMAGGREGATE" NUMBER(1,0), 
	"STORAGE_TYPE" NUMBER(2,0), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" VARCHAR2(1000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
