--------------------------------------------------------
--  DDL for Table OLAP_MODEL_ASSIGNMENTS$
--------------------------------------------------------

  CREATE TABLE "SYS"."OLAP_MODEL_ASSIGNMENTS$" SHARING=METADATA 
   (	"MODEL_ID" NUMBER, 
	"ASSIGNMENT_ID" NUMBER, 
	"PRECEDENCE" NUMBER, 
	"ORDER_NUM" NUMBER, 
	"CALCULATED_MEMBER_ID" NUMBER, 
	"MEMBER_NAME" VARCHAR2(128 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" VARCHAR2(1000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
