--------------------------------------------------------
--  Constraints for Table OLAP_DESCRIPTIONS$
--------------------------------------------------------

  ALTER TABLE "SYS"."OLAP_DESCRIPTIONS$" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_DESCRIPTIONS$" MODIFY ("OWNING_OBJECT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_DESCRIPTIONS$" MODIFY ("OWNING_OBJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_DESCRIPTIONS$" MODIFY ("LANGUAGE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_DESCRIPTIONS$" MODIFY ("DESCRIPTION_TYPE" NOT NULL ENABLE);
