--------------------------------------------------------
--  Constraints for Table OLAP_MULTI_OPTIONS$
--------------------------------------------------------

  ALTER TABLE "SYS"."OLAP_MULTI_OPTIONS$" MODIFY ("OWNING_OBJECTID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_MULTI_OPTIONS$" MODIFY ("OBJECT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_MULTI_OPTIONS$" MODIFY ("OPTION_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_MULTI_OPTIONS$" MODIFY ("OPTION_ORDER" NOT NULL ENABLE);
