--------------------------------------------------------
--  Constraints for Table OLAP_MODELS$
--------------------------------------------------------

  ALTER TABLE "SYS"."OLAP_MODELS$" MODIFY ("OWNING_OBJ_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_MODELS$" MODIFY ("OWNING_OBJ_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_MODELS$" MODIFY ("MODEL_ROLE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_MODELS$" MODIFY ("MODEL_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_MODELS$" MODIFY ("DEFAULT_PRECEDENCE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_MODELS$" MODIFY ("MODEL_NAME" NOT NULL ENABLE);
