--------------------------------------------------------
--  DDL for Table OLAP_SYNTAX$
--------------------------------------------------------

  CREATE TABLE "SYS"."OLAP_SYNTAX$" SHARING=METADATA 
   (	"REF_ROLE" NUMBER, 
	"OWNER_ID" NUMBER, 
	"OWNER_TYPE" NUMBER, 
	"ORDER_NUM" NUMBER, 
	"SYNTAX_CLOB" CLOB, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" VARCHAR2(1000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("SYNTAX_CLOB") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
