--------------------------------------------------------
--  DDL for Table OLAP_METADATA_PROPERTIES$
--------------------------------------------------------

  CREATE TABLE "SYS"."OLAP_METADATA_PROPERTIES$" SHARING=METADATA 
   (	"TOP_OBJ#" NUMBER, 
	"OWNING_OBJECT_ID" NUMBER, 
	"OWNING_TYPE" NUMBER, 
	"PROPERTY_ID" NUMBER, 
	"PROPERTY_KEY" VARCHAR2(128 BYTE), 
	"PROPERTY_VALUE" CLOB, 
	"PROPERTY_ORDER" NUMBER, 
	"OWNING_TYPE2" NUMBER, 
	"OWNING_OBJECT_ID2" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" VARCHAR2(1000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("PROPERTY_VALUE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
