--------------------------------------------------------
--  DDL for Table OLAP_ATTRIBUTES$
--------------------------------------------------------

  CREATE TABLE "SYS"."OLAP_ATTRIBUTES$" SHARING=METADATA 
   (	"DIM_OBJ#" NUMBER, 
	"ATTRIBUTE_NAME" VARCHAR2(128 BYTE), 
	"ATTRIBUTE_ID" NUMBER, 
	"TARGET_DIM#" NUMBER, 
	"TARGET_ATTRIBUTE#" NUMBER, 
	"ATTRIBUTE_ROLE_MASK" NUMBER, 
	"TYPE#" NUMBER, 
	"LENGTH" NUMBER, 
	"CHARSETFORM" NUMBER, 
	"PRECISION#" NUMBER, 
	"SCALE" NUMBER, 
	"TYPE_PROPERTY" NUMBER, 
	"ATTRIBUTE_ORDER" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" VARCHAR2(1000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
