--------------------------------------------------------
--  DDL for Table OLAP_MULTI_OPTIONS$
--------------------------------------------------------

  CREATE TABLE "SYS"."OLAP_MULTI_OPTIONS$" SHARING=METADATA 
   (	"OWNING_OBJECTID" NUMBER, 
	"OBJECT_TYPE" NUMBER, 
	"OPTION_TYPE" NUMBER, 
	"OPTION_ORDER" NUMBER(20,0), 
	"OPTION_VALUE" VARCHAR2(80 BYTE), 
	"OPTION_NUM_VALUE" NUMBER, 
	"OPTION_REF_OBJ_TYPE" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" VARCHAR2(1000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
