--------------------------------------------------------
--  DDL for Table OLAP_DIMENSIONALITY$
--------------------------------------------------------

  CREATE TABLE "SYS"."OLAP_DIMENSIONALITY$" SHARING=METADATA 
   (	"DIMENSIONED_OBJECT_ID" NUMBER, 
	"DIMENSIONED_OBJECT_TYPE" NUMBER, 
	"DIMENSIONALITY_ID" NUMBER, 
	"ORDER_NUM" NUMBER, 
	"DIMENSION_ID" NUMBER, 
	"DIMENSION_TYPE" NUMBER, 
	"OWNING_DIML_ID" NUMBER, 
	"ATTRIBUTE_ID" NUMBER, 
	"BREAKOUT_FLAGS" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" VARCHAR2(1000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
