--------------------------------------------------------
--  DDL for Table OLAP_MAPPINGS$
--------------------------------------------------------

  CREATE TABLE "SYS"."OLAP_MAPPINGS$" SHARING=METADATA 
   (	"MAP_NAME" VARCHAR2(128 BYTE), 
	"MAP_ID" NUMBER, 
	"MAP_TYPE" NUMBER(2,0), 
	"MAPPING_OWNER_ID" NUMBER, 
	"MAPPING_OWNER_TYPE" NUMBER, 
	"MAPPED_OBJECT_ID" NUMBER, 
	"MAPPED_DIM_TYPE" NUMBER, 
	"MAPPED_DIM_ID" NUMBER, 
	"MAP_ORDER" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" VARCHAR2(1000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
