--------------------------------------------------------
--  DDL for Table OLAP_MEAS_FOLDER_CONTENTS$
--------------------------------------------------------

  CREATE TABLE "SYS"."OLAP_MEAS_FOLDER_CONTENTS$" SHARING=METADATA 
   (	"MEASURE_FOLDER_OBJ#" NUMBER, 
	"OBJECT_TYPE" NUMBER, 
	"OBJECT_ID" NUMBER, 
	"ORDER_NUM" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" VARCHAR2(1000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
