--------------------------------------------------------
--  Constraints for Table OLAP_CALCULATED_MEMBERS$
--------------------------------------------------------

  ALTER TABLE "SYS"."OLAP_CALCULATED_MEMBERS$" MODIFY ("DIM_OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_CALCULATED_MEMBERS$" MODIFY ("MEMBER_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_CALCULATED_MEMBERS$" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_CALCULATED_MEMBERS$" MODIFY ("CONTAINER_DIM_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_CALCULATED_MEMBERS$" MODIFY ("CONTAINER_DIM_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_CALCULATED_MEMBERS$" MODIFY ("STORAGE_TYPE" NOT NULL ENABLE);
