--------------------------------------------------------
--  Constraints for Table OLAP_DIMENSIONALITY$
--------------------------------------------------------

  ALTER TABLE "SYS"."OLAP_DIMENSIONALITY$" MODIFY ("DIMENSIONED_OBJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_DIMENSIONALITY$" MODIFY ("DIMENSIONED_OBJECT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_DIMENSIONALITY$" MODIFY ("DIMENSIONALITY_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_DIMENSIONALITY$" MODIFY ("ORDER_NUM" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_DIMENSIONALITY$" MODIFY ("DIMENSION_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_DIMENSIONALITY$" MODIFY ("DIMENSION_TYPE" NOT NULL ENABLE);
