--------------------------------------------------------
--  DDL for Table OLAP_MEASURES$
--------------------------------------------------------

  CREATE TABLE "SYS"."OLAP_MEASURES$" SHARING=METADATA 
   (	"CUBE_OBJ#" NUMBER, 
	"MEASURE_NAME" VARCHAR2(128 BYTE), 
	"MEASURE_ID" NUMBER, 
	"MEASURE_TYPE" NUMBER(2,0), 
	"TYPE#" NUMBER, 
	"LENGTH" NUMBER, 
	"CHARSETFORM" NUMBER, 
	"PRECISION#" NUMBER, 
	"SCALE" NUMBER, 
	"TYPE_PROPERTY" NUMBER, 
	"IS_STALE" NUMBER(1,0), 
	"IS_HIDDEN" NUMBER(1,0), 
	"MEASURE_ORDER" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" VARCHAR2(1000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
