--------------------------------------------------------
--  DDL for Table OLAP_CUBE_DIMENSIONS$
--------------------------------------------------------

  CREATE TABLE "SYS"."OLAP_CUBE_DIMENSIONS$" SHARING=METADATA 
   (	"AWSEQ#" NUMBER, 
	"OBJ#" NUMBER, 
	"DIMENSION_TYPE" NUMBER, 
	"AUDIT$" VARCHAR2(38 BYTE), 
	"IS_STALE" NUMBER(1,0), 
	"DEFAULT_HIERARCHY_ID" NUMBER, 
	"TYPE#" NUMBER, 
	"LENGTH" NUMBER, 
	"CHARSETFORM" NUMBER, 
	"PRECISION#" NUMBER, 
	"SCALE" NUMBER, 
	"TYPE_PROPERTY" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" VARCHAR2(1000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
