--------------------------------------------------------
--  Constraints for Table OLAP_MEAS_FOLDER_CONTENTS$
--------------------------------------------------------

  ALTER TABLE "SYS"."OLAP_MEAS_FOLDER_CONTENTS$" MODIFY ("MEASURE_FOLDER_OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_MEAS_FOLDER_CONTENTS$" MODIFY ("OBJECT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_MEAS_FOLDER_CONTENTS$" MODIFY ("OBJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_MEAS_FOLDER_CONTENTS$" MODIFY ("ORDER_NUM" NOT NULL ENABLE);
