--------------------------------------------------------
--  DDL for Table OLAP_METADATA_DEPENDENCIES$
--------------------------------------------------------

  CREATE TABLE "SYS"."OLAP_METADATA_DEPENDENCIES$" SHARING=METADATA 
   (	"D_TOP_OBJ#" NUMBER, 
	"D_SUB_OBJ#" NUMBER, 
	"D_OBJ_TYPE" NUMBER, 
	"P_OBJ#" NUMBER, 
	"P_OBJ_TYPE" NUMBER, 
	"P_OWNER" VARCHAR2(128 BYTE), 
	"P_TOP_OBJ_NAME" VARCHAR2(128 BYTE), 
	"P_SUB_OBJ_NAME1" VARCHAR2(128 BYTE), 
	"P_SUB_OBJ_NAME2" VARCHAR2(128 BYTE), 
	"P_SUB_OBJ_NAME3" VARCHAR2(128 BYTE), 
	"P_SUB_OBJ_NAME4" VARCHAR2(128 BYTE), 
	"DEP_TYPE" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" VARCHAR2(1000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
