--------------------------------------------------------
--  Constraints for Table OLAP_ATTRIBUTES$
--------------------------------------------------------

  ALTER TABLE "SYS"."OLAP_ATTRIBUTES$" MODIFY ("DIM_OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_ATTRIBUTES$" MODIFY ("ATTRIBUTE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_ATTRIBUTES$" MODIFY ("ATTRIBUTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_ATTRIBUTES$" MODIFY ("TYPE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OLAP_ATTRIBUTES$" MODIFY ("LENGTH" NOT NULL ENABLE);
