--------------------------------------------------------
--  DDL for Table OLAP_DESCRIPTIONS$
--------------------------------------------------------

  CREATE TABLE "SYS"."OLAP_DESCRIPTIONS$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"OWNING_OBJECT_TYPE" NUMBER, 
	"OWNING_OBJECT_ID" NUMBER, 
	"LANGUAGE" VARCHAR2(80 BYTE), 
	"DESCRIPTION_TYPE" VARCHAR2(128 BYTE), 
	"DESCRIPTION_VALUE" NVARCHAR2(300), 
	"DESCRIPTION_CLASS" NUMBER, 
	"DESCRIPTION_ORDER" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" VARCHAR2(1000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
