--------------------------------------------------------
--  DDL for Table OLAP_AW_VIEW_COLUMNS$
--------------------------------------------------------

  CREATE TABLE "SYS"."OLAP_AW_VIEW_COLUMNS$" SHARING=METADATA 
   (	"VIEW_OBJ#" NUMBER, 
	"COLUMN_OBJ#" NUMBER, 
	"REFERENCED_OBJECT_TYPE" NUMBER, 
	"REFERENCED_OBJECT_ID" NUMBER, 
	"LEVEL_ID" NUMBER, 
	"COLUMN_TYPE" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" VARCHAR2(1000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
