--------------------------------------------------------
--  DDL for Table OLAP_MODELS$
--------------------------------------------------------

  CREATE TABLE "SYS"."OLAP_MODELS$" SHARING=METADATA 
   (	"OWNING_OBJ_TYPE" NUMBER, 
	"OWNING_OBJ_ID" NUMBER, 
	"MODEL_ROLE" NUMBER, 
	"MODEL_ID" NUMBER, 
	"DEFAULT_PRECEDENCE" NUMBER, 
	"MODEL_NAME" VARCHAR2(128 BYTE), 
	"EXPLICIT_DIM_ID" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" VARCHAR2(1000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
