--------------------------------------------------------
--  DDL for Table OLAP_HIERARCHIES$
--------------------------------------------------------

  CREATE TABLE "SYS"."OLAP_HIERARCHIES$" SHARING=METADATA 
   (	"DIM_OBJ#" NUMBER, 
	"HIERARCHY_NAME" VARCHAR2(128 BYTE), 
	"HIERARCHY_TYPE" NUMBER, 
	"HIERARCHY_ID" NUMBER, 
	"HIERARCHY_ORDER" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" VARCHAR2(1000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
