--------------------------------------------------------
--  DDL for Table OPARG$
--------------------------------------------------------

  CREATE TABLE "SYS"."OPARG$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"BIND#" NUMBER, 
	"POSITION" NUMBER, 
	"TYPE" VARCHAR2(61 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
