--------------------------------------------------------
--  Constraints for Table OPATCH_INST_JOB
--------------------------------------------------------

  ALTER TABLE "SYS"."OPATCH_INST_JOB" MODIFY ("NODE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OPATCH_INST_JOB" MODIFY ("INST_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OPATCH_INST_JOB" MODIFY ("INST_JOB" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OPATCH_INST_JOB" ADD PRIMARY KEY ("INST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
