--------------------------------------------------------
--  DDL for Table OPBINDING$
--------------------------------------------------------

  CREATE TABLE "SYS"."OPBINDING$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"BIND#" NUMBER, 
	"FUNCTIONNAME" VARCHAR2(386 BYTE), 
	"RETURNSCHEMA" VARCHAR2(128 BYTE), 
	"RETURNTYPE" VARCHAR2(128 BYTE), 
	"IMPSCHEMA" VARCHAR2(128 BYTE), 
	"IMPTYPE" VARCHAR2(128 BYTE), 
	"PROPERTY" NUMBER, 
	"SPARE1" VARCHAR2(128 BYTE), 
	"SPARE2" VARCHAR2(128 BYTE), 
	"SPARE3" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
