--------------------------------------------------------
--  DDL for Table OPT_FINDING$
--------------------------------------------------------

  CREATE TABLE "SYS"."OPT_FINDING$" SHARING=METADATA 
   (	"F_OWN#" NUMBER, 
	"F_ID" NUMBER, 
	"TYPE" NUMBER, 
	"REASON" NUMBER, 
	"CTIME" DATE, 
	"TAB_CNT" NUMBER
   ) PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE ROW MOVEMENT ;
