--------------------------------------------------------
--  DDL for Table OPT_FINDING_OBJ$
--------------------------------------------------------

  CREATE TABLE "SYS"."OPT_FINDING_OBJ$" SHARING=METADATA 
   (	"F_ID" NUMBER, 
	"F_OBJ#" NUMBER, 
	"OBJ_TYPE" NUMBER, 
	"COL_LIST" RAW(128), 
	"CVEC_SIZE" NUMBER, 
	"FLAGS" NUMBER, 
	"NROWS" NUMBER
   ) PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE ROW MOVEMENT ;
