--------------------------------------------------------
--  DDL for Table OPT_SQLSTAT$
--------------------------------------------------------

  CREATE TABLE "SYS"."OPT_SQLSTAT$" SHARING=METADATA 
   (	"SQL_ID" VARCHAR2(13 BYTE), 
	"PARSING_SCHEMA_NAME" VARCHAR2(128 BYTE), 
	"EXECUTIONS" NUMBER, 
	"END_OF_FETCH_COUNT" NUMBER, 
	"ELAPSED_TIME" NUMBER, 
	"CPU_TIME" NUMBER, 
	"BUFFER_GETS" NUMBER, 
	"LAST_GATHER_TIME" DATE, 
	"PX_SERVERS_EXECUTIONS" NUMBER, 
	 CONSTRAINT "PK_OPT_SQLSTAT" PRIMARY KEY ("SQL_ID", "PARSING_SCHEMA_NAME") ENABLE
   ) ORGANIZATION INDEX NOCOMPRESS PCTFREE 1 INITRANS 2 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 PCTTHRESHOLD 50;
