--------------------------------------------------------
--  Constraints for Table OPT_DIRECTIVE$
--------------------------------------------------------

  ALTER TABLE "SYS"."OPT_DIRECTIVE$" MODIFY ("DIR_OWN#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OPT_DIRECTIVE$" MODIFY ("DIR_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OPT_DIRECTIVE$" MODIFY ("F_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OPT_DIRECTIVE$" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OPT_DIRECTIVE$" MODIFY ("STATE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OPT_DIRECTIVE$" MODIFY ("FLAGS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OPT_DIRECTIVE$" MODIFY ("CREATED" NOT NULL ENABLE);
