--------------------------------------------------------
--  Constraints for Table OPT_SQLSTAT$
--------------------------------------------------------

  ALTER TABLE "SYS"."OPT_SQLSTAT$" MODIFY ("SQL_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OPT_SQLSTAT$" MODIFY ("PARSING_SCHEMA_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."OPT_SQLSTAT$" ADD CONSTRAINT "PK_OPT_SQLSTAT" PRIMARY KEY ("SQL_ID", "PARSING_SCHEMA_NAME")
  USING INDEX PCTFREE 1 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE;
