--------------------------------------------------------
--  DDL for Table OPT_DIRECTIVE$
--------------------------------------------------------

  CREATE TABLE "SYS"."OPT_DIRECTIVE$" SHARING=METADATA 
   (	"DIR_OWN#" NUMBER, 
	"DIR_ID" NUMBER, 
	"F_ID" NUMBER, 
	"TYPE" NUMBER, 
	"STATE" NUMBER, 
	"FLAGS" NUMBER, 
	"CREATED" DATE, 
	"LAST_MODIFIED" DATE, 
	"LAST_USED" DATE, 
	"NUM_ONE" NUMBER, 
	"NUM_TWO" NUMBER, 
	"NUM_THREE" NUMBER, 
	"VC_ONE" VARCHAR2(4000 BYTE), 
	"VC_TWO" VARCHAR2(4000 BYTE), 
	"VC_THREE" VARCHAR2(4000 BYTE), 
	"CL_ONE" CLOB
   ) PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 LOB ("CL_ONE") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT))  ENABLE ROW MOVEMENT ;
