--------------------------------------------------------
--  DDL for Table OPT_CALIBRATION_STATS$
--------------------------------------------------------

  CREATE TABLE "SYS"."OPT_CALIBRATION_STATS$" SHARING=METADATA 
   (	"STATID#" NUMBER, 
	"STATVALUE" FLOAT(126), 
	"TIMESTAMP" DATE, 
	"ORIGIN" NUMBER, 
	"PROPERTIES" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
  GRANT DELETE ON "SYS"."OPT_CALIBRATION_STATS$" TO "OPTIMIZER_PROCESSING_RATE";
  GRANT INSERT ON "SYS"."OPT_CALIBRATION_STATS$" TO "OPTIMIZER_PROCESSING_RATE";
  GRANT SELECT ON "SYS"."OPT_CALIBRATION_STATS$" TO "OPTIMIZER_PROCESSING_RATE";
  GRANT UPDATE ON "SYS"."OPT_CALIBRATION_STATS$" TO "OPTIMIZER_PROCESSING_RATE";
