--------------------------------------------------------
--  DDL for Table OPTSTAT_SNAPSHOT$
--------------------------------------------------------

  CREATE TABLE "SYS"."OPTSTAT_SNAPSHOT$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"INSERTS" NUMBER, 
	"UPDATES" NUMBER, 
	"DELETES" NUMBER, 
	"FLAGS" NUMBER, 
	"TIMESTAMP" TIMESTAMP (6) WITH TIME ZONE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 204800 NEXT 106496 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
