--------------------------------------------------------
--  DDL for Type ORATSDP_SD_SENSITIVE_INFO_OTV
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "SYS"."ORATSDP_SD_SENSITIVE_INFO_OTV" 

/

  GRANT EXECUTE ON "SYS"."ORATSDP_SD_SENSITIVE_INFO_OTV" TO "XDB";
  GRANT EXECUTE ON "SYS"."ORATSDP_SD_SENSITIVE_INFO_OTV" TO PUBLIC WITH GRANT OPTION;
