--------------------------------------------------------
--  DDL for Package ORDIMDPCALLOUTS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "SYS"."ORDIMDPCALLOUTS" 

/

  GRANT EXECUTE ON "SYS"."ORDIMDPCALLOUTS" TO "SELECT_CATALOG_ROLE";
  GRANT EXECUTE ON "SYS"."ORDIMDPCALLOUTS" TO "EXECUTE_CATALOG_ROLE";
  GRANT EXECUTE ON "SYS"."ORDIMDPCALLOUTS" TO "DATAPUMP_IMP_FULL_DATABASE";
