--------------------------------------------------------
--  Constraints for Table PARAMETER$
--------------------------------------------------------

  ALTER TABLE "SYS"."PARAMETER$" MODIFY ("TOID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PARAMETER$" MODIFY ("VERSION#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PARAMETER$" MODIFY ("METHOD#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PARAMETER$" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PARAMETER$" MODIFY ("PARAMETER#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PARAMETER$" MODIFY ("PARAM_TOID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PARAMETER$" MODIFY ("PARAM_VERSION#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PARAMETER$" MODIFY ("PROPERTIES" NOT NULL ENABLE);
