--------------------------------------------------------
--  Constraints for Table PARTOBJ$
--------------------------------------------------------

  ALTER TABLE "SYS"."PARTOBJ$" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PARTOBJ$" MODIFY ("PARTTYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PARTOBJ$" MODIFY ("PARTCNT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PARTOBJ$" MODIFY ("PARTKEYCOLS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PARTOBJ$" MODIFY ("DEFPCTFREE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PARTOBJ$" MODIFY ("DEFPCTUSED" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PARTOBJ$" MODIFY ("DEFINITRANS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PARTOBJ$" MODIFY ("DEFMAXTRANS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PARTOBJ$" MODIFY ("DEFLISTS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PARTOBJ$" MODIFY ("DEFGROUPS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PARTOBJ$" MODIFY ("DEFLOGGING" NOT NULL ENABLE);
