--------------------------------------------------------
--  Constraints for Table PARTLOB$
--------------------------------------------------------

  ALTER TABLE "SYS"."PARTLOB$" MODIFY ("LOBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PARTLOB$" MODIFY ("TABOBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PARTLOB$" MODIFY ("INTCOL#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PARTLOB$" MODIFY ("DEFCHUNK" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PARTLOB$" MODIFY ("DEFPCTVER$" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PARTLOB$" MODIFY ("DEFFLAGS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PARTLOB$" MODIFY ("DEFPRO" NOT NULL ENABLE);
