--------------------------------------------------------
--  DDL for Table PARTOBJ$
--------------------------------------------------------

  CREATE TABLE "SYS"."PARTOBJ$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"PARTTYPE" NUMBER, 
	"PARTCNT" NUMBER, 
	"PARTKEYCOLS" NUMBER, 
	"FLAGS" NUMBER, 
	"DEFTS#" NUMBER, 
	"DEFPCTFREE" NUMBER, 
	"DEFPCTUSED" NUMBER, 
	"DEFPCTTHRES" NUMBER, 
	"DEFINITRANS" NUMBER, 
	"DEFMAXTRANS" NUMBER, 
	"DEFTINIEXTS" NUMBER, 
	"DEFEXTSIZE" NUMBER, 
	"DEFMINEXTS" NUMBER, 
	"DEFMAXEXTS" NUMBER, 
	"DEFEXTPCT" NUMBER, 
	"DEFLISTS" NUMBER, 
	"DEFGROUPS" NUMBER, 
	"DEFLOGGING" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"DEFINCLCOL" NUMBER, 
	"PARAMETERS" VARCHAR2(1000 BYTE), 
	"INTERVAL_STR" VARCHAR2(1000 BYTE), 
	"INTERVAL_BIVAL" RAW(200), 
	"DEFMAXSIZE" NUMBER, 
	"SUBPTN_INTERVAL_STR" VARCHAR2(1000 BYTE), 
	"SUBPTN_INTERVAL_BIVAL" RAW(200)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  GRANT READ ON "SYS"."PARTOBJ$" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."PARTOBJ$" TO "CTXSYS";
