--------------------------------------------------------
--  DDL for Table PARTLOB$
--------------------------------------------------------

  CREATE TABLE "SYS"."PARTLOB$" SHARING=METADATA 
   (	"LOBJ#" NUMBER, 
	"TABOBJ#" NUMBER, 
	"INTCOL#" NUMBER, 
	"DEFTS#" NUMBER, 
	"DEFCHUNK" NUMBER, 
	"DEFPCTVER$" NUMBER, 
	"DEFFLAGS" NUMBER, 
	"DEFPRO" NUMBER, 
	"DEFINIEXTS" NUMBER, 
	"DEFEXTSIZE" NUMBER, 
	"DEFMINEXTS" NUMBER, 
	"DEFMAXEXTS" NUMBER, 
	"DEFEXTPCT" NUMBER, 
	"DEFLISTS" NUMBER, 
	"DEFGROUPS" NUMBER, 
	"DEFBUFPOOL" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"DEFMAXSIZE" NUMBER, 
	"DEFRETENTION" NUMBER, 
	"DEFMINTIME" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
