--------------------------------------------------------
--  Constraints for Table PDB_HISTORY$
--------------------------------------------------------

  ALTER TABLE "SYS"."PDB_HISTORY$" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PDB_HISTORY$" MODIFY ("CON_ID#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PDB_HISTORY$" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PDB_HISTORY$" MODIFY ("GUID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PDB_HISTORY$" MODIFY ("SCNBAS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PDB_HISTORY$" MODIFY ("SCNWRP" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PDB_HISTORY$" MODIFY ("TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PDB_HISTORY$" MODIFY ("OPERATION" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PDB_HISTORY$" MODIFY ("DB_VERSION" NOT NULL ENABLE);
