--------------------------------------------------------
--  DDL for Table PDB_SYNC$
--------------------------------------------------------

  CREATE TABLE "SYS"."PDB_SYNC$" SHARING=METADATA 
   (	"SCNWRP" NUMBER, 
	"SCNBAS" NUMBER, 
	"CTIME" DATE, 
	"SQLSTMT" VARCHAR2(4000 BYTE), 
	"NAME" VARCHAR2(128 BYTE), 
	"AUXNAME1" VARCHAR2(128 BYTE), 
	"AUXNAME2" VARCHAR2(128 BYTE), 
	"OPCODE" NUMBER, 
	"FLAGS" NUMBER, 
	"LONGSQLTXT" CLOB, 
	"REPLAY#" NUMBER, 
	"CREATION#" NUMBER, 
	"SPARE3" VARCHAR2(128 BYTE), 
	"SPARE4" VARCHAR2(128 BYTE), 
	"SPARE5" VARCHAR2(4000 BYTE), 
	"SPARE6" NUMBER, 
	"SPARE7" NUMBER, 
	"SPARE8" NUMBER, 
	"SQLID" VARCHAR2(13 BYTE), 
	"APPID#" NUMBER, 
	"VER#" NUMBER, 
	"PATCH#" NUMBER, 
	"APP_STATUS" NUMBER, 
	"SESSSERIAL#" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("LONGSQLTXT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
