--------------------------------------------------------
--  DDL for Table PDB_HISTORY$
--------------------------------------------------------

  CREATE TABLE "SYS"."PDB_HISTORY$" SHARING=METADATA 
   (	"NAME" VARCHAR2(128 BYTE), 
	"CON_ID#" NUMBER, 
	"DBID" NUMBER, 
	"GUID" RAW(16), 
	"SCNBAS" NUMBER, 
	"SCNWRP" NUMBER, 
	"TIME" DATE, 
	"OPERATION" VARCHAR2(16 BYTE), 
	"DB_VERSION" NUMBER, 
	"C_PDB_NAME" VARCHAR2(128 BYTE), 
	"C_PDB_DBID" NUMBER, 
	"C_PDB_GUID" RAW(16), 
	"C_DB_NAME" VARCHAR2(128 BYTE), 
	"C_DB_UNAME" VARCHAR2(128 BYTE), 
	"C_DB_DBID" NUMBER, 
	"CLONETAG" VARCHAR2(128 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(128 BYTE), 
	"SPARE4" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
