--------------------------------------------------------
--  DDL for Table PDB_STAT$
--------------------------------------------------------

  CREATE TABLE "SYS"."PDB_STAT$" SHARING=METADATA 
   (	"CON_UID#" NUMBER, 
	"INST_ID" NUMBER, 
	"INST_NAME" VARCHAR2(128 BYTE), 
	"STAT_NAME" VARCHAR2(128 BYTE), 
	"STAT_VALUE" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" NUMBER, 
	"SPARE5" VARCHAR2(4000 BYTE), 
	"SPARE6" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
