--------------------------------------------------------
--  DDL for Table PDB_SNAPSHOTFILE$
--------------------------------------------------------

  CREATE TABLE "SYS"."PDB_SNAPSHOTFILE$" SHARING=METADATA 
   (	"CON_ID#" NUMBER, 
	"SNAPSCN" NUMBER, 
	"SNAPFILENAME" VARCHAR2(513 BYTE), 
	"SNAPFILETYPE" VARCHAR2(8 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" VARCHAR2(1000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
