--------------------------------------------------------
--  Constraints for Table PDB_SNAPSHOT$
--------------------------------------------------------

  ALTER TABLE "SYS"."PDB_SNAPSHOT$" MODIFY ("CON_ID#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PDB_SNAPSHOT$" MODIFY ("CON_UID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PDB_SNAPSHOT$" MODIFY ("SNAPNAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PDB_SNAPSHOT$" MODIFY ("SNAPSCN" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PDB_SNAPSHOT$" MODIFY ("PREVSNAPSCN" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PDB_SNAPSHOT$" MODIFY ("SNAPTIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PDB_SNAPSHOT$" MODIFY ("PREVSNAPTIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PDB_SNAPSHOT$" MODIFY ("ARCHIVEPATH" NOT NULL ENABLE);
