REM INSERTING into SYS.PDB_SYNC$
SET DEFINE OFF;
Insert into SYS.PDB_SYNC$ (SCNWRP,SCNBAS,CTIME,SQLSTMT,NAME,AUXNAME1,AUXNAME2,OPCODE,FLAGS,REPLAY#,CREATION#,SPARE3,SPARE4,SPARE5,SPARE6,SPARE7,SPARE8,SQLID,APPID#,VER#,PATCH#,APP_STATUS,SESSSERIAL#) values (0,0,to_date('30-MAY-19','DD-MON-RR'),null,'PDB$LASTREPLAY',null,null,-1,0,57,null,null,null,null,null,null,null,null,null,null,null,null,null);
