--------------------------------------------------------
--  DDL for Table PDB_SYNC_STMT$
--------------------------------------------------------

  CREATE TABLE "SYS"."PDB_SYNC_STMT$" SHARING=METADATA 
   (	"APPID#" NUMBER, 
	"SQLID" VARCHAR2(13 BYTE), 
	"SQLTEXT" CLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("SQLTEXT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
