--------------------------------------------------------
--  DDL for Table PENDING_TRANS$
--------------------------------------------------------

  CREATE TABLE "SYS"."PENDING_TRANS$" SHARING=METADATA 
   (	"LOCAL_TRAN_ID" VARCHAR2(22 BYTE), 
	"GLOBAL_TRAN_FMT" NUMBER(*,0), 
	"GLOBAL_ORACLE_ID" VARCHAR2(64 BYTE), 
	"GLOBAL_FOREIGN_ID" RAW(64), 
	"TRAN_COMMENT" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(16 BYTE), 
	"STATUS" VARCHAR2(1 BYTE), 
	"HEURISTIC_DFLT" VARCHAR2(1 BYTE), 
	"SESSION_VECTOR" RAW(4), 
	"RECO_VECTOR" RAW(4), 
	"TYPE#" NUMBER, 
	"FAIL_TIME" DATE, 
	"HEURISTIC_TIME" DATE, 
	"RECO_TIME" DATE, 
	"TOP_DB_USER" VARCHAR2(128 BYTE), 
	"TOP_OS_USER" VARCHAR2(64 BYTE), 
	"TOP_OS_HOST" VARCHAR2(128 BYTE), 
	"TOP_OS_TERMINAL" VARCHAR2(255 BYTE), 
	"GLOBAL_COMMIT#" VARCHAR2(16 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" VARCHAR2(128 BYTE), 
	"SPARE3" NUMBER, 
	"SPARE4" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
