--------------------------------------------------------
--  DDL for Table PENDING_SUB_SESSIONS$
--------------------------------------------------------

  CREATE TABLE "SYS"."PENDING_SUB_SESSIONS$" SHARING=METADATA 
   (	"LOCAL_TRAN_ID" VARCHAR2(22 BYTE), 
	"SESSION_ID" NUMBER(*,0), 
	"SUB_SESSION_ID" NUMBER(*,0), 
	"INTERFACE" VARCHAR2(1 BYTE), 
	"DBID" VARCHAR2(16 BYTE), 
	"LINK_OWNER" NUMBER(*,0), 
	"DBLINK" VARCHAR2(128 BYTE), 
	"BRANCH_ID" RAW(64), 
	"SPARE" RAW(64)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
