--------------------------------------------------------
--  Constraints for Table PENDING_SESSIONS$
--------------------------------------------------------

  ALTER TABLE "SYS"."PENDING_SESSIONS$" MODIFY ("LOCAL_TRAN_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PENDING_SESSIONS$" MODIFY ("SESSION_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PENDING_SESSIONS$" MODIFY ("BRANCH_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PENDING_SESSIONS$" MODIFY ("INTERFACE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PENDING_SESSIONS$" MODIFY ("DB_USERID" NOT NULL ENABLE);
