--------------------------------------------------------
--  Constraints for Table PENDING_TRANS$
--------------------------------------------------------

  ALTER TABLE "SYS"."PENDING_TRANS$" MODIFY ("LOCAL_TRAN_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PENDING_TRANS$" MODIFY ("GLOBAL_TRAN_FMT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PENDING_TRANS$" MODIFY ("STATE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PENDING_TRANS$" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PENDING_TRANS$" MODIFY ("SESSION_VECTOR" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PENDING_TRANS$" MODIFY ("RECO_VECTOR" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PENDING_TRANS$" MODIFY ("FAIL_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PENDING_TRANS$" MODIFY ("RECO_TIME" NOT NULL ENABLE);
