--------------------------------------------------------
--  Constraints for Table PENDING_SUB_SESSIONS$
--------------------------------------------------------

  ALTER TABLE "SYS"."PENDING_SUB_SESSIONS$" MODIFY ("LOCAL_TRAN_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PENDING_SUB_SESSIONS$" MODIFY ("SESSION_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PENDING_SUB_SESSIONS$" MODIFY ("SUB_SESSION_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PENDING_SUB_SESSIONS$" MODIFY ("INTERFACE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PENDING_SUB_SESSIONS$" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PENDING_SUB_SESSIONS$" MODIFY ("LINK_OWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PENDING_SUB_SESSIONS$" MODIFY ("DBLINK" NOT NULL ENABLE);
