--------------------------------------------------------
--  DDL for Index PK_OPT_SQLSTAT
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."PK_OPT_SQLSTAT" ON "SYS"."OPT_SQLSTAT$" ("SQL_ID", "PARSING_SCHEMA_NAME") 
  PCTFREE 1 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
