--------------------------------------------------------
--  DDL for Table PLSCOPE_ACTION$
--------------------------------------------------------

  CREATE TABLE "SYS"."PLSCOPE_ACTION$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"ACTION#" NUMBER, 
	"SIGNATURE" VARCHAR2(32 BYTE), 
	"ACTION" NUMBER, 
	"LINE" NUMBER, 
	"COL" NUMBER, 
	"CONTEXT#" NUMBER, 
	"FLAGS" NUMBER, 
	"EXP1" NUMBER, 
	"EXP2" NUMBER, 
	"DECL_OBJ#" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
