--------------------------------------------------------
--  DDL for Sequence PLSQL_CODE_COVERAGE_RUNNUMBER
--------------------------------------------------------

   CREATE SEQUENCE  "SYS"."PLSQL_CODE_COVERAGE_RUNNUMBER"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "SYS"."PLSQL_CODE_COVERAGE_RUNNUMBER" TO PUBLIC;
