--------------------------------------------------------
--  DDL for Table PRIV_USED_PATH$
--------------------------------------------------------

  CREATE TABLE "SYS"."PRIV_USED_PATH$" SHARING=METADATA 
   (	"ID#" NUMBER, 
	"CAPTURE" NUMBER, 
	"PATH" "SYS"."GRANT_PATH" , 
	"RUN_SEQ#" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" 
 VARRAY "PATH" STORE AS SECUREFILE LOB 
  ( TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES ) ;
