--------------------------------------------------------
--  DDL for Table PRIV_CAPTURE$
--------------------------------------------------------

  CREATE TABLE "SYS"."PRIV_CAPTURE$" SHARING=METADATA 
   (	"ID#" NUMBER, 
	"NAME" VARCHAR2(128 BYTE), 
	"DESCRIPTION" VARCHAR2(1024 BYTE) DEFAULT NULL, 
	"TYPE" NUMBER DEFAULT 1, 
	"ENABLED" NUMBER DEFAULT 0, 
	"ROLES" "SYS"."ROLE_ID_LIST" , 
	"CONTEXT" VARCHAR2(4000 BYTE) DEFAULT NULL, 
	"RUN_SEQ#" NUMBER DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
  GRANT SELECT ON "SYS"."PRIV_CAPTURE$" TO "CAPTURE_ADMIN";
