--------------------------------------------------------
--  DDL for Table PRIV_UNUSED$
--------------------------------------------------------

  CREATE TABLE "SYS"."PRIV_UNUSED$" SHARING=METADATA 
   (	"ID#" NUMBER, 
	"CAPTURE" NUMBER, 
	"USER#" NUMBER, 
	"SYSPRIV#" NUMBER DEFAULT NULL, 
	"OBJPRIV#" NUMBER DEFAULT NULL, 
	"USERPRIV#" NUMBER DEFAULT NULL, 
	"OBJ#" NUMBER DEFAULT NULL, 
	"COL#" NUMBER DEFAULT NULL, 
	"OPTION$" NUMBER DEFAULT NULL, 
	"RUN_SEQ#" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
