--------------------------------------------------------
--  DDL for Table PROCEDUREINFO$
--------------------------------------------------------

  CREATE TABLE "SYS"."PROCEDUREINFO$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"PROCEDURE#" NUMBER, 
	"OVERLOAD#" NUMBER, 
	"PROCEDURENAME" VARCHAR2(128 BYTE), 
	"PROPERTIES" NUMBER, 
	"ITYPEOBJ#" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" NUMBER, 
	"PROPERTIES2" NUMBER DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
