--------------------------------------------------------
--  Constraints for Table PROCEDUREINFO$
--------------------------------------------------------

  ALTER TABLE "SYS"."PROCEDUREINFO$" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PROCEDUREINFO$" MODIFY ("PROCEDURE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PROCEDUREINFO$" MODIFY ("OVERLOAD#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PROCEDUREINFO$" MODIFY ("PROPERTIES" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PROCEDUREINFO$" MODIFY ("PROPERTIES2" NOT NULL ENABLE);
