--------------------------------------------------------
--  Constraints for Table PROCEDUREJAVA$
--------------------------------------------------------

  ALTER TABLE "SYS"."PROCEDUREJAVA$" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PROCEDUREJAVA$" MODIFY ("PROCEDURE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PROCEDUREJAVA$" MODIFY ("OWNERNAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PROCEDUREJAVA$" MODIFY ("OWNERLENGTH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PROCEDUREJAVA$" MODIFY ("CLASSNAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PROCEDUREJAVA$" MODIFY ("CLASSLENGTH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PROCEDUREJAVA$" MODIFY ("METHODNAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PROCEDUREJAVA$" MODIFY ("METHODLENGTH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PROCEDUREJAVA$" MODIFY ("SIGNATURE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PROCEDUREJAVA$" MODIFY ("SIGLENGTH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PROCEDUREJAVA$" MODIFY ("FLAGS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PROCEDUREJAVA$" MODIFY ("FLAGSLENGTH" NOT NULL ENABLE);
