--------------------------------------------------------
--  DDL for Table PROFNAME$
--------------------------------------------------------

  CREATE TABLE "SYS"."PROFNAME$" SHARING=METADATA 
   (	"PROFILE#" NUMBER, 
	"NAME" VARCHAR2(128 BYTE), 
	"FLAGS" NUMBER DEFAULT 0, 
	"CREAPPID" NUMBER, 
	"CREVERID" NUMBER, 
	"CREPATCHID" NUMBER, 
	"MODAPPID" NUMBER, 
	"MODVERID" NUMBER, 
	"MODPATCHID" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" VARCHAR2(1000 BYTE), 
	"SPARE5" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
