REM INSERTING into SYS.PROFNAME$
SET DEFINE OFF;
Insert into SYS.PROFNAME$ (PROFILE#,NAME,FLAGS,CREAPPID,CREVERID,CREPATCHID,MODAPPID,MODVERID,MODPATCHID,SPARE1,SPARE2,SPARE3,SPARE4,SPARE5) values (0,'DEFAULT',8,null,1,null,null,1,null,null,null,null,null,null);
Insert into SYS.PROFNAME$ (PROFILE#,NAME,FLAGS,CREAPPID,CREVERID,CREPATCHID,MODAPPID,MODVERID,MODPATCHID,SPARE1,SPARE2,SPARE3,SPARE4,SPARE5) values (1,'ORA_STIG_PROFILE',8,null,1,null,null,null,null,null,null,null,null,null);
