REM INSERTING into SYS.PROPS$
SET DEFINE OFF;
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('DICT.BASE','2','dictionary base tables version #');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('DEFAULT_TEMP_TABLESPACE','TEMP','Name of default temporary tablespace');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('DEFAULT_PERMANENT_TABLESPACE','USERS','Name of default permanent tablespace');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('DEFAULT_EDITION','ORA$BASE','Name of the database default edition');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('Flashback Timestamp TimeZone','GMT','Flashback timestamp created in GMT');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('TDE_MASTER_KEY_ID',null,null);
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('DEFAULT_TBS_TYPE','SMALLFILE','Default tablespace type');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('DICTIONARY_ENDIAN_TYPE','LITTLE','Endian type of the data dictionary');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('GLOBAL_DB_NAME','ORCLPDB','Global database name');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('NLS_RDBMS_VERSION','19.0.0.0.0','RDBMS version for NLS parameters');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('NLS_NCHAR_CHARACTERSET','AL16UTF16','NCHAR Character set');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('NLS_NCHAR_CONV_EXCP','FALSE','NLS conversion exception');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('NLS_LENGTH_SEMANTICS','BYTE','NLS length semantics');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('NLS_COMP','BINARY','NLS comparison');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('NLS_DUAL_CURRENCY','$','Dual currency symbol');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('NLS_TIMESTAMP_TZ_FORMAT','DD-MON-RR HH.MI.SSXFF AM TZR','Timestamp with timezone format');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('NLS_TIME_TZ_FORMAT','HH.MI.SSXFF AM TZR','Time with timezone format');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('NLS_TIMESTAMP_FORMAT','DD-MON-RR HH.MI.SSXFF AM','Time stamp format');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('NLS_TIME_FORMAT','HH.MI.SSXFF AM','Time format');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('NLS_SORT','BINARY','Linguistic definition');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('NLS_DATE_LANGUAGE','AMERICAN','Date language');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('NLS_DATE_FORMAT','DD-MON-RR','Date format');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('NLS_CALENDAR','GREGORIAN','Calendar system');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('NLS_CHARACTERSET','AL32UTF8','Character set');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('NLS_NUMERIC_CHARACTERS','.,','Numeric characters');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('NLS_ISO_CURRENCY','AMERICA','ISO currency');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('NLS_CURRENCY','$','Local currency');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('NLS_TERRITORY','AMERICA','Territory');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('NLS_LANGUAGE','AMERICAN','Language');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('DST_SECONDARY_TT_VERSION','0','Version of secondary timezone data file');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('DST_PRIMARY_TT_VERSION','32','Version of primary timezone data file');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('DST_UPGRADE_STATE','NONE','State of Day Light Saving Time Upgrade');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('MAX_STRING_SIZE','STANDARD','MAX_STRING_SIZE parameter used for dictionary metadata');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('EXPORT_VIEWS_VERSION','8','Export views revision #');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('WORKLOAD_CAPTURE_MODE',null,'CAPTURE implies workload capture is in progress');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('WORKLOAD_REPLAY_MODE',null,'PREPARE implies external replay clients can connect; REPLAY implies workload replay is in progress');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('NO_USERID_VERIFIER_SALT','66165B235C36F5B881CABE486835CDCE',null);
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('OLS_OID_STATUS','0','OLS OID Status used for Label Security');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('MAX_PDB_SNAPSHOTS','8','maximum number of snapshots for a given PDB');
Insert into SYS.PROPS$ (NAME,VALUE$,COMMENT$) values ('DBTIMEZONE','+00:00','DB time zone');
