--------------------------------------------------------
--  DDL for Table PROXY_REMOTE$
--------------------------------------------------------

  CREATE TABLE "SYS"."PROXY_REMOTE$" SHARING=METADATA 
   (	"CON_ID#" NUMBER, 
	"NAME" VARCHAR2(128 BYTE), 
	"FLAG" NUMBER, 
	"REMOTE_PORT" NUMBER, 
	"REMOTE_HOST" VARCHAR2(128 BYTE), 
	"REMOTE_SRVC" VARCHAR2(128 BYTE), 
	"REMOTE_USER" VARCHAR2(128 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" VARCHAR2(1000 BYTE), 
	"SPARE5" VARCHAR2(1000 BYTE), 
	"SPARE6" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
