--------------------------------------------------------
--  DDL for Table PS$
--------------------------------------------------------

  CREATE TABLE "SYS"."PS$" SHARING=METADATA 
   (	"AWSEQ#" NUMBER, 
	"PSNUMBER" NUMBER(10,0), 
	"PSGEN" NUMBER(10,0), 
	"MAPOFFSET" NUMBER, 
	"MAXPAGES" NUMBER, 
	"ALMAP" RAW(8), 
	"HEADER" RAW(200), 
	"GELOB" BLOB, 
	"GELREC" NUMBER DEFAULT null, 
	"MAPREC" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 4 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 LOB ("GELOB") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" DISABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
