REM INSERTING into SYS.PTT_FEATURE$
SET DEFINE OFF;
Insert into SYS.PTT_FEATURE$ (TRACK_TIME,STATUS,PREFIX_VALUE,SPARE1,SPARE2) values (to_timestamp('30-MAY-19 03.11.10.779000000 AM','DD-MON-RR HH.MI.SSXFF AM'),1,'ORA$PTT_',null,null);
