--------------------------------------------------------
--  DDL for Table RADM_MC$
--------------------------------------------------------

  CREATE TABLE "SYS"."RADM_MC$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"INTCOL#" NUMBER, 
	"MFUNC" NUMBER, 
	"MPARAMS" VARCHAR2(1000 BYTE), 
	"REGEXP_PATTERN" VARCHAR2(512 BYTE), 
	"REGEXP_REPLACE_STRING" VARCHAR2(4000 BYTE), 
	"REGEXP_POSITION" NUMBER, 
	"REGEXP_OCCURRENCE" NUMBER, 
	"REGEXP_MATCH_PARAMETER" VARCHAR2(10 BYTE), 
	"MP_IFORMAT_START_BYTE" NUMBER(*,0), 
	"MP_IFORMAT_END_BYTE" NUMBER(*,0), 
	"MP_OFORMAT_START_BYTE" NUMBER(*,0), 
	"MP_OFORMAT_END_BYTE" NUMBER(*,0), 
	"MP_MASKCHAR_START_BYTE" NUMBER(*,0), 
	"MP_MASKCHAR_END_BYTE" NUMBER(*,0), 
	"MP_MASKFROM" NUMBER(*,0), 
	"MP_MASKTO" NUMBER(*,0), 
	"MP_DATMASK_MO" NUMBER(*,0), 
	"MP_DATMASK_D" NUMBER(*,0), 
	"MP_DATMASK_Y" NUMBER(*,0), 
	"MP_DATMASK_H" NUMBER(*,0), 
	"MP_DATMASK_MI" NUMBER(*,0), 
	"MP_DATMASK_S" NUMBER(*,0), 
	"PE#" NUMBER, 
	"REGEXP_CHARSET" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
