--------------------------------------------------------
--  DDL for Table RADM_PE$
--------------------------------------------------------

  CREATE TABLE "SYS"."RADM_PE$" SHARING=METADATA 
   (	"PE#" NUMBER, 
	"PE_OBJ#" NUMBER, 
	"PE_NAME" VARCHAR2(256 BYTE), 
	"PE_PEXPR" VARCHAR2(4000 BYTE), 
	"PE_VERSION" VARCHAR2(30 BYTE), 
	"PE_DESCRIP" VARCHAR2(4000 BYTE), 
	"PE_COMPAT" VARCHAR2(30 BYTE), 
	"PE_SPARE1" VARCHAR2(1000 BYTE), 
	"PE_SPARE2" DATE, 
	"PE_SPARE3" TIMESTAMP (6), 
	"PE_SPARE4" NUMBER, 
	"PE_SPARE5" NUMBER, 
	"PE_SPARE6" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
