--------------------------------------------------------
--  Constraints for Table RADM_FPTM$
--------------------------------------------------------

  ALTER TABLE "SYS"."RADM_FPTM$" MODIFY ("NUMBERCOL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."RADM_FPTM$" MODIFY ("BINFLOATCOL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."RADM_FPTM$" MODIFY ("BINDOUBLECOL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."RADM_FPTM$" MODIFY ("DATECOL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."RADM_FPTM$" MODIFY ("TS_COL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."RADM_FPTM$" MODIFY ("TSWTZ_COL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."RADM_FPTM$" MODIFY ("FPVER" NOT NULL ENABLE);
