--------------------------------------------------------
--  DDL for Table RADM_FPTM$
--------------------------------------------------------

  CREATE TABLE "SYS"."RADM_FPTM$" SHARING=METADATA 
   (	"NUMBERCOL" NUMBER, 
	"BINFLOATCOL" BINARY_FLOAT, 
	"BINDOUBLECOL" BINARY_DOUBLE, 
	"CHARCOL" VARCHAR2(1 BYTE), 
	"VARCHARCOL" VARCHAR2(1 BYTE), 
	"NCHARCOL" NCHAR(1), 
	"NVARCHARCOL" NVARCHAR2(1), 
	"DATECOL" DATE, 
	"TS_COL" TIMESTAMP (6), 
	"TSWTZ_COL" TIMESTAMP (6) WITH TIME ZONE, 
	"FPVER" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  GRANT DELETE ON "SYS"."RADM_FPTM$" TO "IMP_FULL_DATABASE";
  GRANT INSERT ON "SYS"."RADM_FPTM$" TO "IMP_FULL_DATABASE";
  GRANT SELECT ON "SYS"."RADM_FPTM$" TO "IMP_FULL_DATABASE";
