--------------------------------------------------------
--  DDL for Table REC_VAR$
--------------------------------------------------------

  CREATE TABLE "SYS"."REC_VAR$" SHARING=METADATA 
   (	"EC_OBJ#" NUMBER, 
	"VAR_NAME" VARCHAR2(128 BYTE), 
	"VAR_TYPE" VARCHAR2(4000 BYTE), 
	"VAR_VAL_FUNC" VARCHAR2(4000 BYTE), 
	"VAR_MTHD_FUNC" VARCHAR2(515 BYTE), 
	"PROPERTY" NUMBER, 
	"VAR_ID" NUMBER, 
	"VAR_DTY" NUMBER, 
	"PRECISION#" NUMBER, 
	"SCALE" NUMBER, 
	"MAXLEN" NUMBER, 
	"CHARSETID" NUMBER, 
	"CHARSETFORM" NUMBER, 
	"TOID" RAW(16), 
	"VERSION" NUMBER, 
	"NUM_ATTRS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
