REM INSERTING into SYS.REC_TAB$
SET DEFINE OFF;
Insert into SYS.REC_TAB$ (EC_OBJ#,TAB_ALIAS,TAB_NAME,PROPERTY,TAB_ID,TAB_OBJ#) values (19651,'TAB','"SYS"."SCHEDULER$_EVENT_QTAB"',0,0,19643);
Insert into SYS.REC_TAB$ (EC_OBJ#,TAB_ALIAS,TAB_NAME,PROPERTY,TAB_ID,TAB_OBJ#) values (19685,'TAB','"SYS"."SCHEDULER$_REMDB_JOBQTAB"',0,0,19670);
Insert into SYS.REC_TAB$ (EC_OBJ#,TAB_ALIAS,TAB_NAME,PROPERTY,TAB_ID,TAB_OBJ#) values (19715,'TAB','"SYS"."SCHEDULER_FILEWATCHER_QT"',0,0,19704);
Insert into SYS.REC_TAB$ (EC_OBJ#,TAB_ALIAS,TAB_NAME,PROPERTY,TAB_ID,TAB_OBJ#) values (19770,'TAB','"SYS"."ALERT_QT"',0,0,19762);
Insert into SYS.REC_TAB$ (EC_OBJ#,TAB_ALIAS,TAB_NAME,PROPERTY,TAB_ID,TAB_OBJ#) values (20071,'TAB','"SYS"."ORA$PREPLUGIN_BACKUP_QTB"',0,0,20063);
Insert into SYS.REC_TAB$ (EC_OBJ#,TAB_ALIAS,TAB_NAME,PROPERTY,TAB_ID,TAB_OBJ#) values (20290,'TAB','"SYS"."AQ$_MEM_MC"',0,0,20280);
Insert into SYS.REC_TAB$ (EC_OBJ#,TAB_ALIAS,TAB_NAME,PROPERTY,TAB_ID,TAB_OBJ#) values (20326,'TAB','"SYS"."AQ_PROP_TABLE"',0,0,20318);
Insert into SYS.REC_TAB$ (EC_OBJ#,TAB_ALIAS,TAB_NAME,PROPERTY,TAB_ID,TAB_OBJ#) values (20485,'TAB','"SYS"."SYS$SERVICE_METRICS_TAB"',0,0,20477);
Insert into SYS.REC_TAB$ (EC_OBJ#,TAB_ALIAS,TAB_NAME,PROPERTY,TAB_ID,TAB_OBJ#) values (20650,'TAB','"SYS"."PDB_MON_EVENT_QTABLE$"',0,0,20640);
Insert into SYS.REC_TAB$ (EC_OBJ#,TAB_ALIAS,TAB_NAME,PROPERTY,TAB_ID,TAB_OBJ#) values (20792,'TAB','"GSMADMIN_INTERNAL"."CHANGE_LOG_QUEUE_TABLE"',0,0,20784);
Insert into SYS.REC_TAB$ (EC_OBJ#,TAB_ALIAS,TAB_NAME,PROPERTY,TAB_ID,TAB_OBJ#) values (22528,'TAB','"WMSYS"."WM$EVENT_QUEUE_TABLE"',0,0,22515);
