--------------------------------------------------------
--  Constraints for Table RECENT_RESOURCE_INCARNATIONS$
--------------------------------------------------------

  ALTER TABLE "SYS"."RECENT_RESOURCE_INCARNATIONS$" ADD CONSTRAINT "RECENT_RESOURCE_INCARNATIONS$P" PRIMARY KEY ("RESOURCE_TYPE", "DB_DOMAIN", "DB_UNIQUE_NAME", "INSTANCE_NAME", "INCARNATION", "STARTUP_TIME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
