--------------------------------------------------------
--  DDL for Index RECENT_RESOURCE_INCARNATIONS$P
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."RECENT_RESOURCE_INCARNATIONS$P" ON "SYS"."RECENT_RESOURCE_INCARNATIONS$" ("RESOURCE_TYPE", "DB_DOMAIN", "DB_UNIQUE_NAME", "INSTANCE_NAME", "INCARNATION", "STARTUP_TIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
