--------------------------------------------------------
--  DDL for Table RECO_SCRIPT$
--------------------------------------------------------

  CREATE TABLE "SYS"."RECO_SCRIPT$" SHARING=METADATA 
   (	"OID" RAW(16), 
	"INVOKING_PACKAGE_OWNER" VARCHAR2(128 BYTE), 
	"INVOKING_PACKAGE" VARCHAR2(128 BYTE), 
	"INVOKING_PROCEDURE" VARCHAR2(128 BYTE), 
	"INVOKING_USER" VARCHAR2(128 BYTE), 
	"TOTAL_BLOCKS" NUMBER, 
	"CONTEXT" CLOB, 
	"STATUS" NUMBER, 
	"DONE_BLOCK_NUM" NUMBER, 
	"SCRIPT_COMMENT" VARCHAR2(4000 BYTE), 
	"CTIME" DATE DEFAULT SYSDATE, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" VARCHAR2(1000 BYTE), 
	"SPARE5" VARCHAR2(1000 BYTE), 
	"SPARE6" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" 
 LOB ("CONTEXT") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
