--------------------------------------------------------
--  DDL for Table RECO_SCRIPT_ERROR$
--------------------------------------------------------

  CREATE TABLE "SYS"."RECO_SCRIPT_ERROR$" SHARING=METADATA 
   (	"OID" RAW(16), 
	"BLOCK_NUM" NUMBER, 
	"ERROR_NUMBER" NUMBER, 
	"ERROR_MESSAGE" VARCHAR2(4000 BYTE), 
	"ERROR_CREATION_TIME" DATE DEFAULT SYSDATE, 
	"SPARE1" NUMBER, 
	"SPARE2" VARCHAR2(1000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
