--------------------------------------------------------
--  DDL for Table RECO_SCRIPT_PARAMS$
--------------------------------------------------------

  CREATE TABLE "SYS"."RECO_SCRIPT_PARAMS$" SHARING=METADATA 
   (	"OID" RAW(16), 
	"PARAM_INDEX" NUMBER, 
	"NAME" VARCHAR2(128 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"VALUE" CLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" 
 LOB ("VALUE") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
