--------------------------------------------------------
--  DDL for Table RECO_SCRIPT_BLOCK$
--------------------------------------------------------

  CREATE TABLE "SYS"."RECO_SCRIPT_BLOCK$" SHARING=METADATA 
   (	"OID" RAW(16), 
	"BLOCK_NUM" NUMBER, 
	"FORWARD_BLOCK" CLOB, 
	"FORWARD_BLOCK_DBLINK" VARCHAR2(128 BYTE), 
	"UNDO_BLOCK" CLOB, 
	"UNDO_BLOCK_DBLINK" VARCHAR2(128 BYTE), 
	"STATE_BLOCK" CLOB, 
	"STATUS" NUMBER, 
	"CONTEXT" CLOB, 
	"BLOCK_COMMENT" VARCHAR2(4000 BYTE), 
	"CTIME" DATE DEFAULT SYSDATE, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" VARCHAR2(1000 BYTE), 
	"SPARE5" VARCHAR2(1000 BYTE), 
	"SPARE6" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" 
 LOB ("FORWARD_BLOCK") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("UNDO_BLOCK") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("STATE_BLOCK") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("CONTEXT") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
