--------------------------------------------------------
--  DDL for Table RECYCLEBIN$
--------------------------------------------------------

  CREATE TABLE "SYS"."RECYCLEBIN$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"OWNER#" NUMBER, 
	"ORIGINAL_NAME" VARCHAR2(128 BYTE), 
	"OPERATION" NUMBER, 
	"TYPE#" NUMBER, 
	"TS#" NUMBER, 
	"FILE#" NUMBER, 
	"BLOCK#" NUMBER, 
	"DROPTIME" DATE, 
	"DROPSCN" NUMBER, 
	"PARTITION_NAME" VARCHAR2(128 BYTE), 
	"FLAGS" NUMBER, 
	"RELATED" NUMBER, 
	"BO" NUMBER, 
	"PURGEOBJ" NUMBER, 
	"BASE_TS#" NUMBER, 
	"BASE_OWNER#" NUMBER, 
	"SPACE" NUMBER, 
	"CON#" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
