--------------------------------------------------------
--  Constraints for Table RECYCLEBIN$
--------------------------------------------------------

  ALTER TABLE "SYS"."RECYCLEBIN$" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."RECYCLEBIN$" MODIFY ("OWNER#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."RECYCLEBIN$" MODIFY ("OPERATION" NOT NULL ENABLE);
  ALTER TABLE "SYS"."RECYCLEBIN$" MODIFY ("TYPE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."RECYCLEBIN$" MODIFY ("RELATED" NOT NULL ENABLE);
  ALTER TABLE "SYS"."RECYCLEBIN$" MODIFY ("BO" NOT NULL ENABLE);
  ALTER TABLE "SYS"."RECYCLEBIN$" MODIFY ("PURGEOBJ" NOT NULL ENABLE);
