--------------------------------------------------------
--  DDL for Table REDEF_OBJECT$
--------------------------------------------------------

  CREATE TABLE "SYS"."REDEF_OBJECT$" SHARING=METADATA 
   (	"REDEF_ID" NUMBER(*,0), 
	"OBJ_TYPE" NUMBER(*,0), 
	"OBJ_OWNER" VARCHAR2(128 BYTE), 
	"OBJ_NAME" VARCHAR2(128 BYTE), 
	"INT_OBJ_OWNER" VARCHAR2(128 BYTE), 
	"INT_OBJ_NAME" VARCHAR2(128 BYTE), 
	"BT_OWNER" VARCHAR2(128 BYTE), 
	"BT_NAME" VARCHAR2(128 BYTE), 
	"GENFLAG" NUMBER(*,0), 
	"TYPFLAG" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
