REM INSERTING into SYS.REDEF_TRACK$
SET DEFINE OFF;
Insert into SYS.REDEF_TRACK$ (REDEF#,FINISH_REDEF#,ABORT_REDEF#,PK_REDEF#,ROWID_REDEF#,PART_REDEF#,BATCH_REDEF#,VPD_AUTO#,VPD_MANUAL#,LAST_REDEF_TIME) values (0,0,0,0,0,0,0,0,0,null);
