--------------------------------------------------------
--  Constraints for Table REDEF_OBJECT_BACKUP$
--------------------------------------------------------

  ALTER TABLE "SYS"."REDEF_OBJECT_BACKUP$" MODIFY ("REDEF_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."REDEF_OBJECT_BACKUP$" MODIFY ("OBJ_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."REDEF_OBJECT_BACKUP$" MODIFY ("OBJ_OWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."REDEF_OBJECT_BACKUP$" MODIFY ("OBJ_NAME" NOT NULL ENABLE);
