--------------------------------------------------------
--  DDL for Table REDEF_STATUS$
--------------------------------------------------------

  CREATE TABLE "SYS"."REDEF_STATUS$" SHARING=METADATA 
   (	"REDEF_ID" NUMBER(*,0), 
	"PREV_OPERATION" VARCHAR2(128 BYTE), 
	"OBJ_OWNER" VARCHAR2(128 BYTE), 
	"OBJ_NAME" VARCHAR2(128 BYTE), 
	"STATUS" VARCHAR2(128 BYTE), 
	"RESTARTABLE" VARCHAR2(1 BYTE), 
	"ERR_NO" NUMBER(*,0), 
	"ERR_TXT" VARCHAR2(1000 BYTE), 
	"ACTION" VARCHAR2(400 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
