--------------------------------------------------------
--  DDL for Table REDEF_DEP_ERROR$
--------------------------------------------------------

  CREATE TABLE "SYS"."REDEF_DEP_ERROR$" SHARING=METADATA 
   (	"REDEF_ID" NUMBER(*,0), 
	"OBJ_TYPE" NUMBER(*,0), 
	"OBJ_OWNER" VARCHAR2(128 BYTE), 
	"OBJ_NAME" VARCHAR2(128 BYTE), 
	"BT_OWNER" VARCHAR2(128 BYTE), 
	"BT_NAME" VARCHAR2(128 BYTE), 
	"DDL_TXT" CLOB, 
	"ERR_NO" NUMBER(*,0), 
	"ERR_TXT" VARCHAR2(1000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("DDL_TXT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
