--------------------------------------------------------
--  DDL for Table REG_SNAP$
--------------------------------------------------------

  CREATE TABLE "SYS"."REG_SNAP$" SHARING=METADATA 
   (	"SOWNER" VARCHAR2(128 BYTE), 
	"SNAPNAME" VARCHAR2(128 BYTE), 
	"SNAPSITE" VARCHAR2(128 BYTE), 
	"SNAPSHOT_ID" NUMBER(*,0), 
	"FLAG" NUMBER, 
	"REP_TYPE" NUMBER, 
	"COMMENT$" VARCHAR2(4000 BYTE), 
	"QUERY_TXT" LONG
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
