REM INSERTING into SYS.REG_SNAP$
SET DEFINE OFF;
Insert into SYS.REG_SNAP$ (SOWNER,SNAPNAME,SNAPSITE,SNAPSHOT_ID,FLAG,REP_TYPE,COMMENT$,QUERY_TXT) values ('SYSTEM','MD_REGEX_MVIEW','ORCLPDB',1,2105413,2,null,'SELECT  pr.PROJECT_NAME, pr.ID "PROJECT_ID", c.ID "CONNECTION_ID", c.NAME "CONNECTION_NAME", mc.ID "CATALOG_ID",
        mc.CATALOG_NAME,s.id "SCHEMA_ID",s.NAME "SCHEMA_NAME", p.ID "PROGRAM_ID", p.name "PROGRAM_NAME",
        rg.DESCRIPTION "ITEM", regexp_count(p.native_sql,rg.REGEX,1,''ix'') "VALUE"
FROM MD_STORED_PROGRAMS p,
  md_projects pr,
  md_connections c,
  md_schemas s,
  MD_CATALOGS mc,
  MD_CODE_REGEX rg
WHERE c.TYPE          IS NULL --Shows captured
AND mc.CONNECTION_ID_FK=c.id
AND mc.id              =s.CATALOG_ID_FK
AND pr.PROJECT_NAME LIKE ''SS%''
and pr.id=c.PROJECT_ID_FK
and p.SCHEMA_ID_FK=s.ID
and regexp_count(p.native_sql,rg.REGEX,1,''ix'')>0');
Insert into SYS.REG_SNAP$ (SOWNER,SNAPNAME,SNAPSITE,SNAPSHOT_ID,FLAG,REP_TYPE,COMMENT$,QUERY_TXT) values ('SYSTEM','MD_REGEX_SCHEMA_MVIEW','ORCLPDB',0,2097476,2,null,'SELECT "MD_REGEX_MVIEW"."PROJECT_ID" "PROJECT_ID","MD_REGEX_MVIEW"."CONNECTION_ID" "CONNECTION_ID","MD_REGEX_MVIEW"."CONNECTION_NAME" "CONNECTION_NAME","MD_REGEX_MVIEW"."CATALOG_ID" "CATALOG_ID","MD_REGEX_MVIEW"."CATALOG_NAME" "CATALOG_NAME","MD_REGEX_MVIEW"."SCHEMA_ID" "SCHEMA_ID","MD_REGEX_MVIEW"."SCHEMA_NAME" "SCHEMA_NAME","MD_REGEX_MVIEW"."ITEM" "ITEM",SUM("MD_REGEX_MVIEW"."VALUE") "VALUE" FROM "MD_REGEX_MVIEW" "MD_REGEX_MVIEW" GROUP BY "MD_REGEX_MVIEW"."PROJECT_NAME","MD_REGEX_MVIEW"."PROJECT_ID","MD_REGEX_MVIEW"."CONNECTION_ID","MD_REGEX_MVIEW"."CONNECTION_NAME","MD_REGEX_MVIEW"."CATALOG_ID","MD_REGEX_MVIEW"."CATALOG_NAME","MD_REGEX_MVIEW"."SCHEMA_ID","MD_REGEX_MVIEW"."SCHEMA_NAME","MD_REGEX_MVIEW"."ITEM"');
Insert into SYS.REG_SNAP$ (SOWNER,SNAPNAME,SNAPSITE,SNAPSHOT_ID,FLAG,REP_TYPE,COMMENT$,QUERY_TXT) values ('SYSTEM','MD_REGEX_CATALOG_MVIEW','ORCLPDB',0,69206340,2,null,'SELECT "MD_REGEX_SCHEMA_MVIEW"."PROJECT_ID" "PROJECT_ID","MD_REGEX_SCHEMA_MVIEW"."CONNECTION_ID" "CONNECTION_ID","MD_REGEX_SCHEMA_MVIEW"."CONNECTION_NAME" "CONNECTION_NAME","MD_REGEX_SCHEMA_MVIEW"."CATALOG_ID" "CATALOG_ID","MD_REGEX_SCHEMA_MVIEW"."CATALOG_NAME" "CATALOG_NAME","MD_REGEX_SCHEMA_MVIEW"."ITEM" "ITEM",SUM("MD_REGEX_SCHEMA_MVIEW"."VALUE") "VALUE" FROM "MD_REGEX_SCHEMA_MVIEW" "MD_REGEX_SCHEMA_MVIEW" GROUP BY "MD_REGEX_SCHEMA_MVIEW"."PROJECT_ID","MD_REGEX_SCHEMA_MVIEW"."CONNECTION_ID","MD_REGEX_SCHEMA_MVIEW"."CONNECTION_NAME","MD_REGEX_SCHEMA_MVIEW"."CATALOG_ID","MD_REGEX_SCHEMA_MVIEW"."CATALOG_NAME","MD_REGEX_SCHEMA_MVIEW"."ITEM"');
Insert into SYS.REG_SNAP$ (SOWNER,SNAPNAME,SNAPSITE,SNAPSHOT_ID,FLAG,REP_TYPE,COMMENT$,QUERY_TXT) values ('SYS','MD_REGEX_MVIEW','ORCLPDB',21,2105413,2,null,'SELECT  pr.PROJECT_NAME, pr.ID "PROJECT_ID", c.ID "CONNECTION_ID", c.NAME "CONNECTION_NAME", mc.ID "CATALOG_ID",
        mc.CATALOG_NAME,s.id "SCHEMA_ID",s.NAME "SCHEMA_NAME", p.ID "PROGRAM_ID", p.name "PROGRAM_NAME",
        rg.DESCRIPTION "ITEM", regexp_count(p.native_sql,rg.REGEX,1,''ix'') "VALUE"
FROM MD_STORED_PROGRAMS p,
  md_projects pr,
  md_connections c,
  md_schemas s,
  MD_CATALOGS mc,
  MD_CODE_REGEX rg
WHERE c.TYPE          IS NULL --Shows captured
AND mc.CONNECTION_ID_FK=c.id
AND mc.id              =s.CATALOG_ID_FK
AND pr.PROJECT_NAME LIKE ''SS%''
and pr.id=c.PROJECT_ID_FK
and p.SCHEMA_ID_FK=s.ID
and regexp_count(p.native_sql,rg.REGEX,1,''ix'')>0');
Insert into SYS.REG_SNAP$ (SOWNER,SNAPNAME,SNAPSITE,SNAPSHOT_ID,FLAG,REP_TYPE,COMMENT$,QUERY_TXT) values ('SYS','MD_REGEX_SCHEMA_MVIEW','ORCLPDB',0,2097476,2,null,'SELECT "MD_REGEX_MVIEW"."PROJECT_ID" "PROJECT_ID","MD_REGEX_MVIEW"."CONNECTION_ID" "CONNECTION_ID","MD_REGEX_MVIEW"."CONNECTION_NAME" "CONNECTION_NAME","MD_REGEX_MVIEW"."CATALOG_ID" "CATALOG_ID","MD_REGEX_MVIEW"."CATALOG_NAME" "CATALOG_NAME","MD_REGEX_MVIEW"."SCHEMA_ID" "SCHEMA_ID","MD_REGEX_MVIEW"."SCHEMA_NAME" "SCHEMA_NAME","MD_REGEX_MVIEW"."ITEM" "ITEM",SUM("MD_REGEX_MVIEW"."VALUE") "VALUE" FROM "MD_REGEX_MVIEW" "MD_REGEX_MVIEW" GROUP BY "MD_REGEX_MVIEW"."PROJECT_NAME","MD_REGEX_MVIEW"."PROJECT_ID","MD_REGEX_MVIEW"."CONNECTION_ID","MD_REGEX_MVIEW"."CONNECTION_NAME","MD_REGEX_MVIEW"."CATALOG_ID","MD_REGEX_MVIEW"."CATALOG_NAME","MD_REGEX_MVIEW"."SCHEMA_ID","MD_REGEX_MVIEW"."SCHEMA_NAME","MD_REGEX_MVIEW"."ITEM"');
Insert into SYS.REG_SNAP$ (SOWNER,SNAPNAME,SNAPSITE,SNAPSHOT_ID,FLAG,REP_TYPE,COMMENT$,QUERY_TXT) values ('SYS','MD_REGEX_CATALOG_MVIEW','ORCLPDB',0,69206340,2,null,'SELECT "MD_REGEX_SCHEMA_MVIEW"."PROJECT_ID" "PROJECT_ID","MD_REGEX_SCHEMA_MVIEW"."CONNECTION_ID" "CONNECTION_ID","MD_REGEX_SCHEMA_MVIEW"."CONNECTION_NAME" "CONNECTION_NAME","MD_REGEX_SCHEMA_MVIEW"."CATALOG_ID" "CATALOG_ID","MD_REGEX_SCHEMA_MVIEW"."CATALOG_NAME" "CATALOG_NAME","MD_REGEX_SCHEMA_MVIEW"."ITEM" "ITEM",SUM("MD_REGEX_SCHEMA_MVIEW"."VALUE") "VALUE" FROM "MD_REGEX_SCHEMA_MVIEW" "MD_REGEX_SCHEMA_MVIEW" GROUP BY "MD_REGEX_SCHEMA_MVIEW"."PROJECT_ID","MD_REGEX_SCHEMA_MVIEW"."CONNECTION_ID","MD_REGEX_SCHEMA_MVIEW"."CONNECTION_NAME","MD_REGEX_SCHEMA_MVIEW"."CATALOG_ID","MD_REGEX_SCHEMA_MVIEW"."CATALOG_NAME","MD_REGEX_SCHEMA_MVIEW"."ITEM"');
Insert into SYS.REG_SNAP$ (SOWNER,SNAPNAME,SNAPSITE,SNAPSHOT_ID,FLAG,REP_TYPE,COMMENT$,QUERY_TXT) values ('RBL_MISDB_PROD','MD_REGEX_MVIEW','ORCLPDB',24,2105413,2,null,'SELECT  pr.PROJECT_NAME, pr.ID "PROJECT_ID", c.ID "CONNECTION_ID", c.NAME "CONNECTION_NAME", mc.ID "CATALOG_ID",
        mc.CATALOG_NAME,s.id "SCHEMA_ID",s.NAME "SCHEMA_NAME", p.ID "PROGRAM_ID", p.name "PROGRAM_NAME",
        rg.DESCRIPTION "ITEM", regexp_count(p.native_sql,rg.REGEX,1,''ix'') "VALUE"
FROM MD_STORED_PROGRAMS p,
  md_projects pr,
  md_connections c,
  md_schemas s,
  MD_CATALOGS mc,
  MD_CODE_REGEX rg
WHERE c.TYPE          IS NULL --Shows captured
AND mc.CONNECTION_ID_FK=c.id
AND mc.id              =s.CATALOG_ID_FK
AND pr.PROJECT_NAME LIKE ''SS%''
and pr.id=c.PROJECT_ID_FK
and p.SCHEMA_ID_FK=s.ID
and regexp_count(p.native_sql,rg.REGEX,1,''ix'')>0');
Insert into SYS.REG_SNAP$ (SOWNER,SNAPNAME,SNAPSITE,SNAPSHOT_ID,FLAG,REP_TYPE,COMMENT$,QUERY_TXT) values ('RBL_MISDB_PROD','MD_REGEX_SCHEMA_MVIEW','ORCLPDB',0,2097476,2,null,'SELECT "MD_REGEX_MVIEW"."PROJECT_ID" "PROJECT_ID","MD_REGEX_MVIEW"."CONNECTION_ID" "CONNECTION_ID","MD_REGEX_MVIEW"."CONNECTION_NAME" "CONNECTION_NAME","MD_REGEX_MVIEW"."CATALOG_ID" "CATALOG_ID","MD_REGEX_MVIEW"."CATALOG_NAME" "CATALOG_NAME","MD_REGEX_MVIEW"."SCHEMA_ID" "SCHEMA_ID","MD_REGEX_MVIEW"."SCHEMA_NAME" "SCHEMA_NAME","MD_REGEX_MVIEW"."ITEM" "ITEM",SUM("MD_REGEX_MVIEW"."VALUE") "VALUE" FROM "MD_REGEX_MVIEW" "MD_REGEX_MVIEW" GROUP BY "MD_REGEX_MVIEW"."PROJECT_NAME","MD_REGEX_MVIEW"."PROJECT_ID","MD_REGEX_MVIEW"."CONNECTION_ID","MD_REGEX_MVIEW"."CONNECTION_NAME","MD_REGEX_MVIEW"."CATALOG_ID","MD_REGEX_MVIEW"."CATALOG_NAME","MD_REGEX_MVIEW"."SCHEMA_ID","MD_REGEX_MVIEW"."SCHEMA_NAME","MD_REGEX_MVIEW"."ITEM"');
Insert into SYS.REG_SNAP$ (SOWNER,SNAPNAME,SNAPSITE,SNAPSHOT_ID,FLAG,REP_TYPE,COMMENT$,QUERY_TXT) values ('RBL_MISDB_PROD','MD_REGEX_CATALOG_MVIEW','ORCLPDB',0,69206340,2,null,'SELECT "MD_REGEX_SCHEMA_MVIEW"."PROJECT_ID" "PROJECT_ID","MD_REGEX_SCHEMA_MVIEW"."CONNECTION_ID" "CONNECTION_ID","MD_REGEX_SCHEMA_MVIEW"."CONNECTION_NAME" "CONNECTION_NAME","MD_REGEX_SCHEMA_MVIEW"."CATALOG_ID" "CATALOG_ID","MD_REGEX_SCHEMA_MVIEW"."CATALOG_NAME" "CATALOG_NAME","MD_REGEX_SCHEMA_MVIEW"."ITEM" "ITEM",SUM("MD_REGEX_SCHEMA_MVIEW"."VALUE") "VALUE" FROM "MD_REGEX_SCHEMA_MVIEW" "MD_REGEX_SCHEMA_MVIEW" GROUP BY "MD_REGEX_SCHEMA_MVIEW"."PROJECT_ID","MD_REGEX_SCHEMA_MVIEW"."CONNECTION_ID","MD_REGEX_SCHEMA_MVIEW"."CONNECTION_NAME","MD_REGEX_SCHEMA_MVIEW"."CATALOG_ID","MD_REGEX_SCHEMA_MVIEW"."CATALOG_NAME","MD_REGEX_SCHEMA_MVIEW"."ITEM"');
Insert into SYS.REG_SNAP$ (SOWNER,SNAPNAME,SNAPSITE,SNAPSHOT_ID,FLAG,REP_TYPE,COMMENT$,QUERY_TXT) values ('ACL_RBL_MISDB_PROD','MD_REGEX_MVIEW','ORCLPDB',41,2105413,2,null,'SELECT  pr.PROJECT_NAME, pr.ID "PROJECT_ID", c.ID "CONNECTION_ID", c.NAME "CONNECTION_NAME", mc.ID "CATALOG_ID",
        mc.CATALOG_NAME,s.id "SCHEMA_ID",s.NAME "SCHEMA_NAME", p.ID "PROGRAM_ID", p.name "PROGRAM_NAME",
        rg.DESCRIPTION "ITEM", regexp_count(p.native_sql,rg.REGEX,1,''ix'') "VALUE"
FROM MD_STORED_PROGRAMS p,
  md_projects pr,
  md_connections c,
  md_schemas s,
  MD_CATALOGS mc,
  MD_CODE_REGEX rg
WHERE c.TYPE          IS NULL --Shows captured
AND mc.CONNECTION_ID_FK=c.id
AND mc.id              =s.CATALOG_ID_FK
AND pr.PROJECT_NAME LIKE ''SS%''
and pr.id=c.PROJECT_ID_FK
and p.SCHEMA_ID_FK=s.ID
and regexp_count(p.native_sql,rg.REGEX,1,''ix'')>0');
Insert into SYS.REG_SNAP$ (SOWNER,SNAPNAME,SNAPSITE,SNAPSHOT_ID,FLAG,REP_TYPE,COMMENT$,QUERY_TXT) values ('ACL_RBL_MISDB_PROD','MD_REGEX_SCHEMA_MVIEW','ORCLPDB',0,2097476,2,null,'SELECT "MD_REGEX_MVIEW"."PROJECT_ID" "PROJECT_ID","MD_REGEX_MVIEW"."CONNECTION_ID" "CONNECTION_ID","MD_REGEX_MVIEW"."CONNECTION_NAME" "CONNECTION_NAME","MD_REGEX_MVIEW"."CATALOG_ID" "CATALOG_ID","MD_REGEX_MVIEW"."CATALOG_NAME" "CATALOG_NAME","MD_REGEX_MVIEW"."SCHEMA_ID" "SCHEMA_ID","MD_REGEX_MVIEW"."SCHEMA_NAME" "SCHEMA_NAME","MD_REGEX_MVIEW"."ITEM" "ITEM",SUM("MD_REGEX_MVIEW"."VALUE") "VALUE" FROM "MD_REGEX_MVIEW" "MD_REGEX_MVIEW" GROUP BY "MD_REGEX_MVIEW"."PROJECT_NAME","MD_REGEX_MVIEW"."PROJECT_ID","MD_REGEX_MVIEW"."CONNECTION_ID","MD_REGEX_MVIEW"."CONNECTION_NAME","MD_REGEX_MVIEW"."CATALOG_ID","MD_REGEX_MVIEW"."CATALOG_NAME","MD_REGEX_MVIEW"."SCHEMA_ID","MD_REGEX_MVIEW"."SCHEMA_NAME","MD_REGEX_MVIEW"."ITEM"');
Insert into SYS.REG_SNAP$ (SOWNER,SNAPNAME,SNAPSITE,SNAPSHOT_ID,FLAG,REP_TYPE,COMMENT$,QUERY_TXT) values ('ACL_RBL_MISDB_PROD','MD_REGEX_CATALOG_MVIEW','ORCLPDB',0,69206340,2,null,'SELECT "MD_REGEX_SCHEMA_MVIEW"."PROJECT_ID" "PROJECT_ID","MD_REGEX_SCHEMA_MVIEW"."CONNECTION_ID" "CONNECTION_ID","MD_REGEX_SCHEMA_MVIEW"."CONNECTION_NAME" "CONNECTION_NAME","MD_REGEX_SCHEMA_MVIEW"."CATALOG_ID" "CATALOG_ID","MD_REGEX_SCHEMA_MVIEW"."CATALOG_NAME" "CATALOG_NAME","MD_REGEX_SCHEMA_MVIEW"."ITEM" "ITEM",SUM("MD_REGEX_SCHEMA_MVIEW"."VALUE") "VALUE" FROM "MD_REGEX_SCHEMA_MVIEW" "MD_REGEX_SCHEMA_MVIEW" GROUP BY "MD_REGEX_SCHEMA_MVIEW"."PROJECT_ID","MD_REGEX_SCHEMA_MVIEW"."CONNECTION_ID","MD_REGEX_SCHEMA_MVIEW"."CONNECTION_NAME","MD_REGEX_SCHEMA_MVIEW"."CATALOG_ID","MD_REGEX_SCHEMA_MVIEW"."CATALOG_NAME","MD_REGEX_SCHEMA_MVIEW"."ITEM"');
Insert into SYS.REG_SNAP$ (SOWNER,SNAPNAME,SNAPSITE,SNAPSHOT_ID,FLAG,REP_TYPE,COMMENT$,QUERY_TXT) values ('RBL_TEMPDB','MD_REGEX_MVIEW','ORCLPDB',44,2105413,2,null,'SELECT  pr.PROJECT_NAME, pr.ID "PROJECT_ID", c.ID "CONNECTION_ID", c.NAME "CONNECTION_NAME", mc.ID "CATALOG_ID",
        mc.CATALOG_NAME,s.id "SCHEMA_ID",s.NAME "SCHEMA_NAME", p.ID "PROGRAM_ID", p.name "PROGRAM_NAME",
        rg.DESCRIPTION "ITEM", regexp_count(p.native_sql,rg.REGEX,1,''ix'') "VALUE"
FROM MD_STORED_PROGRAMS p,
  md_projects pr,
  md_connections c,
  md_schemas s,
  MD_CATALOGS mc,
  MD_CODE_REGEX rg
WHERE c.TYPE          IS NULL --Shows captured
AND mc.CONNECTION_ID_FK=c.id
AND mc.id              =s.CATALOG_ID_FK
AND pr.PROJECT_NAME LIKE ''SS%''
and pr.id=c.PROJECT_ID_FK
and p.SCHEMA_ID_FK=s.ID
and regexp_count(p.native_sql,rg.REGEX,1,''ix'')>0');
Insert into SYS.REG_SNAP$ (SOWNER,SNAPNAME,SNAPSITE,SNAPSHOT_ID,FLAG,REP_TYPE,COMMENT$,QUERY_TXT) values ('RBL_TEMPDB','MD_REGEX_SCHEMA_MVIEW','ORCLPDB',0,2097476,2,null,'SELECT "MD_REGEX_MVIEW"."PROJECT_ID" "PROJECT_ID","MD_REGEX_MVIEW"."CONNECTION_ID" "CONNECTION_ID","MD_REGEX_MVIEW"."CONNECTION_NAME" "CONNECTION_NAME","MD_REGEX_MVIEW"."CATALOG_ID" "CATALOG_ID","MD_REGEX_MVIEW"."CATALOG_NAME" "CATALOG_NAME","MD_REGEX_MVIEW"."SCHEMA_ID" "SCHEMA_ID","MD_REGEX_MVIEW"."SCHEMA_NAME" "SCHEMA_NAME","MD_REGEX_MVIEW"."ITEM" "ITEM",SUM("MD_REGEX_MVIEW"."VALUE") "VALUE" FROM "MD_REGEX_MVIEW" "MD_REGEX_MVIEW" GROUP BY "MD_REGEX_MVIEW"."PROJECT_NAME","MD_REGEX_MVIEW"."PROJECT_ID","MD_REGEX_MVIEW"."CONNECTION_ID","MD_REGEX_MVIEW"."CONNECTION_NAME","MD_REGEX_MVIEW"."CATALOG_ID","MD_REGEX_MVIEW"."CATALOG_NAME","MD_REGEX_MVIEW"."SCHEMA_ID","MD_REGEX_MVIEW"."SCHEMA_NAME","MD_REGEX_MVIEW"."ITEM"');
Insert into SYS.REG_SNAP$ (SOWNER,SNAPNAME,SNAPSITE,SNAPSHOT_ID,FLAG,REP_TYPE,COMMENT$,QUERY_TXT) values ('RBL_TEMPDB','MD_REGEX_CATALOG_MVIEW','ORCLPDB',0,69206340,2,null,'SELECT "MD_REGEX_SCHEMA_MVIEW"."PROJECT_ID" "PROJECT_ID","MD_REGEX_SCHEMA_MVIEW"."CONNECTION_ID" "CONNECTION_ID","MD_REGEX_SCHEMA_MVIEW"."CONNECTION_NAME" "CONNECTION_NAME","MD_REGEX_SCHEMA_MVIEW"."CATALOG_ID" "CATALOG_ID","MD_REGEX_SCHEMA_MVIEW"."CATALOG_NAME" "CATALOG_NAME","MD_REGEX_SCHEMA_MVIEW"."ITEM" "ITEM",SUM("MD_REGEX_SCHEMA_MVIEW"."VALUE") "VALUE" FROM "MD_REGEX_SCHEMA_MVIEW" "MD_REGEX_SCHEMA_MVIEW" GROUP BY "MD_REGEX_SCHEMA_MVIEW"."PROJECT_ID","MD_REGEX_SCHEMA_MVIEW"."CONNECTION_ID","MD_REGEX_SCHEMA_MVIEW"."CONNECTION_NAME","MD_REGEX_SCHEMA_MVIEW"."CATALOG_ID","MD_REGEX_SCHEMA_MVIEW"."CATALOG_NAME","MD_REGEX_SCHEMA_MVIEW"."ITEM"');
