--------------------------------------------------------
--  DDL for Table REGISTRY$DATABASE
--------------------------------------------------------

  CREATE TABLE "SYS"."REGISTRY$DATABASE" SHARING=METADATA 
   (	"PLATFORM_ID" NUMBER, 
	"PLATFORM_NAME" VARCHAR2(101 BYTE), 
	"EDITION" VARCHAR2(30 BYTE), 
	"TZ_VERSION" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
