--------------------------------------------------------
--  DDL for Table REGISTRY$BACKPORTS
--------------------------------------------------------

  CREATE TABLE "SYS"."REGISTRY$BACKPORTS" SHARING=METADATA 
   (	"BUGNO" NUMBER, 
	"VERSION_FULL" VARCHAR2(30 BYTE), 
	"CID" VARCHAR2(30 BYTE) DEFAULT 'CATPROC', 
	"NAMESPACE" VARCHAR2(30 BYTE) DEFAULT 'SERVER', 
	"BACKPORT_TYPE" VARCHAR2(30 BYTE) DEFAULT 'DICTIONARY', 
	"BACKPORT_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
