--------------------------------------------------------
--  Constraints for Table REGISTRY$
--------------------------------------------------------

  ALTER TABLE "SYS"."REGISTRY$" MODIFY ("SCHEMA#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."REGISTRY$" MODIFY ("INVOKER#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."REGISTRY$" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."REGISTRY$" MODIFY ("FLAGS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."REGISTRY$" ADD CONSTRAINT "REGISTRY_PK" PRIMARY KEY ("NAMESPACE", "CID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
