--------------------------------------------------------
--  DDL for Table REGISTRY$LOG
--------------------------------------------------------

  CREATE TABLE "SYS"."REGISTRY$LOG" SHARING=METADATA 
   (	"CID" VARCHAR2(30 BYTE), 
	"NAMESPACE" VARCHAR2(30 BYTE), 
	"OPERATION" NUMBER, 
	"OPTIME" TIMESTAMP (6), 
	"ERRMSG" VARCHAR2(1000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
