REM INSERTING into SYS.REGISTRY$HISTORY
SET DEFINE OFF;
Insert into SYS.REGISTRY$HISTORY (ACTION_TIME,ACTION,NAMESPACE,VERSION,ID,COMMENTS,BUNDLE_SERIES) values (null,'BOOTSTRAP','DATAPATCH','19',null,'RDBMS_19.3.0.0.0DBRU_WINDOWS.X64_190528',null);
