REM INSERTING into SYS.REGISTRY$DEPENDENCIES
SET DEFINE OFF;
Insert into SYS.REGISTRY$DEPENDENCIES (CID,NAMESPACE,REQ_CID,REQ_NAMESPACE) values ('ORDIM','SERVER','JAVAVM','SERVER');
Insert into SYS.REGISTRY$DEPENDENCIES (CID,NAMESPACE,REQ_CID,REQ_NAMESPACE) values ('ORDIM','SERVER','XDB','SERVER');
Insert into SYS.REGISTRY$DEPENDENCIES (CID,NAMESPACE,REQ_CID,REQ_NAMESPACE) values ('ORDIM','SERVER','XML','SERVER');
Insert into SYS.REGISTRY$DEPENDENCIES (CID,NAMESPACE,REQ_CID,REQ_NAMESPACE) values ('SDO','SERVER','JAVAVM','SERVER');
Insert into SYS.REGISTRY$DEPENDENCIES (CID,NAMESPACE,REQ_CID,REQ_NAMESPACE) values ('SDO','SERVER','XDB','SERVER');
