--------------------------------------------------------
--  DDL for Table REGISTRY$UPG_SUMMARY
--------------------------------------------------------

  CREATE TABLE "SYS"."REGISTRY$UPG_SUMMARY" SHARING=METADATA 
   (	"CON_ID" NUMBER, 
	"CON_NAME" VARCHAR2(128 BYTE), 
	"CID" VARCHAR2(30 BYTE), 
	"PROGRESS" VARCHAR2(1024 BYTE), 
	"ERRCNT" NUMBER, 
	"STARTTIME" TIMESTAMP (6), 
	"ENDTIME" TIMESTAMP (6), 
	"REPORTNAME" VARCHAR2(2000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
