--------------------------------------------------------
--  Ref Constraints for Table REGISTRY$DEPENDENCIES
--------------------------------------------------------

  ALTER TABLE "SYS"."REGISTRY$DEPENDENCIES" ADD CONSTRAINT "DEPENDENCIES_FK" FOREIGN KEY ("NAMESPACE", "CID")
	  REFERENCES "SYS"."REGISTRY$" ("NAMESPACE", "CID") ON DELETE CASCADE DISABLE;
  ALTER TABLE "SYS"."REGISTRY$DEPENDENCIES" ADD CONSTRAINT "DEPENDENCIES_REQ_FK" FOREIGN KEY ("REQ_NAMESPACE", "REQ_CID")
	  REFERENCES "SYS"."REGISTRY$" ("NAMESPACE", "CID") ON DELETE CASCADE DISABLE;
