--------------------------------------------------------
--  DDL for Table REGISTRY$HISTORY
--------------------------------------------------------

  CREATE TABLE "SYS"."REGISTRY$HISTORY" SHARING=METADATA 
   (	"ACTION_TIME" TIMESTAMP (6), 
	"ACTION" VARCHAR2(30 BYTE), 
	"NAMESPACE" VARCHAR2(30 BYTE), 
	"VERSION" VARCHAR2(30 BYTE), 
	"ID" NUMBER, 
	"COMMENTS" VARCHAR2(255 BYTE), 
	"BUNDLE_SERIES" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  GRANT READ ON "SYS"."REGISTRY$HISTORY" TO "DATAPATCH_ROLE";
