--------------------------------------------------------
--  DDL for Table REGISTRY$ERROR
--------------------------------------------------------

  CREATE TABLE "SYS"."REGISTRY$ERROR" SHARING=METADATA 
   (	"USERNAME" VARCHAR2(256 BYTE), 
	"TIMESTAMP" TIMESTAMP (6), 
	"SCRIPT" VARCHAR2(1024 BYTE), 
	"IDENTIFIER" VARCHAR2(256 BYTE), 
	"MESSAGE" CLOB, 
	"STATEMENT" CLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("MESSAGE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("STATEMENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
