--------------------------------------------------------
--  Constraints for Table REGISTRY$SQLPATCH
--------------------------------------------------------

  ALTER TABLE "SYS"."REGISTRY$SQLPATCH" MODIFY ("PATCH_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."REGISTRY$SQLPATCH" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."REGISTRY$SQLPATCH" MODIFY ("ACTION_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."REGISTRY$SQLPATCH" MODIFY ("LOGFILE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."REGISTRY$SQLPATCH" MODIFY ("PATCH_DESCRIPTOR" NOT NULL ENABLE);
  ALTER TABLE "SYS"."REGISTRY$SQLPATCH" ADD CONSTRAINT "REGISTRY$SQLPATCH_PK" PRIMARY KEY ("INSTALL_ID", "PATCH_ID", "PATCH_UID", "ACTION", "ACTION_TIME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
