--------------------------------------------------------
--  Constraints for Table REGISTRY$BACKPORTS
--------------------------------------------------------

  ALTER TABLE "SYS"."REGISTRY$BACKPORTS" MODIFY ("CID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."REGISTRY$BACKPORTS" MODIFY ("NAMESPACE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."REGISTRY$BACKPORTS" MODIFY ("BACKPORT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."REGISTRY$BACKPORTS" MODIFY ("BACKPORT_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."REGISTRY$BACKPORTS" ADD CONSTRAINT "REGISTRY_BACKPORTS_PK" PRIMARY KEY ("BUGNO", "VERSION_FULL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
