--------------------------------------------------------
--  DDL for Table REGISTRY$SQLPATCH
--------------------------------------------------------

  CREATE TABLE "SYS"."REGISTRY$SQLPATCH" SHARING=METADATA 
   (	"INSTALL_ID" NUMBER, 
	"PATCH_ID" NUMBER, 
	"PATCH_UID" NUMBER, 
	"PATCH_TYPE" VARCHAR2(10 BYTE), 
	"ACTION" VARCHAR2(15 BYTE), 
	"STATUS" VARCHAR2(25 BYTE), 
	"ACTION_TIME" TIMESTAMP (6), 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	"LOGFILE" VARCHAR2(500 BYTE), 
	"RU_LOGFILE" VARCHAR2(500 BYTE), 
	"FLAGS" VARCHAR2(10 BYTE), 
	"PATCH_DESCRIPTOR" "SYS"."XMLTYPE" , 
	"PATCH_DIRECTORY" BLOB, 
	"SOURCE_VERSION" VARCHAR2(15 BYTE), 
	"SOURCE_BUILD_DESCRIPTION" VARCHAR2(80 BYTE), 
	"SOURCE_BUILD_TIMESTAMP" TIMESTAMP (6), 
	"TARGET_VERSION" VARCHAR2(15 BYTE), 
	"TARGET_BUILD_DESCRIPTION" VARCHAR2(80 BYTE), 
	"TARGET_BUILD_TIMESTAMP" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 XMLTYPE COLUMN "PATCH_DESCRIPTOR" STORE AS BASICFILE CLOB (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("PATCH_DIRECTORY") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
