--------------------------------------------------------
--  DDL for Table REGISTRY$
--------------------------------------------------------

  CREATE TABLE "SYS"."REGISTRY$" SHARING=METADATA 
   (	"CID" VARCHAR2(30 BYTE), 
	"CNAME" VARCHAR2(255 BYTE), 
	"SCHEMA#" NUMBER, 
	"INVOKER#" NUMBER, 
	"VERSION" VARCHAR2(30 BYTE), 
	"EDITION" VARCHAR2(30 BYTE), 
	"STATUS" NUMBER, 
	"FLAGS" NUMBER, 
	"MODIFIED" DATE, 
	"PID" VARCHAR2(30 BYTE), 
	"BANNER" VARCHAR2(80 BYTE), 
	"VPROC" VARCHAR2(128 BYTE), 
	"DATE_INVALID" DATE, 
	"DATE_VALID" DATE, 
	"DATE_LOADING" DATE, 
	"DATE_LOADED" DATE, 
	"DATE_UPGRADING" DATE, 
	"DATE_UPGRADED" DATE, 
	"DATE_DOWNGRADING" DATE, 
	"DATE_DOWNGRADED" DATE, 
	"DATE_REMOVING" DATE, 
	"DATE_REMOVED" DATE, 
	"DATE_OPTIONOFF" DATE, 
	"NAMESPACE" VARCHAR2(30 BYTE), 
	"ORG_VERSION" VARCHAR2(30 BYTE), 
	"PRV_VERSION" VARCHAR2(30 BYTE), 
	"SIGNATURE" RAW(20), 
	"VERSION_FULL" VARCHAR2(30 BYTE), 
	"ORG_VERSION_FULL" VARCHAR2(30 BYTE), 
	"PRV_VERSION_FULL" VARCHAR2(30 BYTE), 
	"BANNER_FULL" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
