--------------------------------------------------------
--  DDL for Table REPL$_PROCESS_EVENTS
--------------------------------------------------------

  CREATE TABLE "SYS"."REPL$_PROCESS_EVENTS" SHARING=METADATA 
   (	"STREAMS_TYPE" NUMBER, 
	"PROCESS_TYPE" NUMBER, 
	"STREAMS_NAME" VARCHAR2(128 BYTE), 
	"EVENT_NAME" VARCHAR2(128 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"EVENT_TIME" TIMESTAMP (6), 
	"ERROR_NUMBER" NUMBER, 
	"ERROR_MESSAGE" VARCHAR2(2000 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" VARCHAR2(2000 BYTE), 
	"SPARE5" VARCHAR2(2000 BYTE), 
	"SPARE6" TIMESTAMP (6), 
	"SPARE7" RAW(2000)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
