--------------------------------------------------------
--  DDL for Table REPL$_DBNAME_MAPPING
--------------------------------------------------------

  CREATE TABLE "SYS"."REPL$_DBNAME_MAPPING" SHARING=METADATA 
   (	"SOURCE_ROOT_NAME" VARCHAR2(128 BYTE), 
	"SOURCE_DATABASE_NAME" VARCHAR2(128 BYTE), 
	"SOURCE_CONTAINER_NAME" VARCHAR2(128 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" TIMESTAMP (6), 
	"SPARE4" VARCHAR2(4000 BYTE), 
	"SPARE5" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
