REM INSERTING into SYS.RESOURCE_MAP
SET DEFINE OFF;
Insert into SYS.RESOURCE_MAP (RESOURCE#,TYPE#,NAME) values (0,0,'COMPOSITE_LIMIT');
Insert into SYS.RESOURCE_MAP (RESOURCE#,TYPE#,NAME) values (1,0,'SESSIONS_PER_USER');
Insert into SYS.RESOURCE_MAP (RESOURCE#,TYPE#,NAME) values (2,0,'CPU_PER_SESSION');
Insert into SYS.RESOURCE_MAP (RESOURCE#,TYPE#,NAME) values (3,0,'CPU_PER_CALL');
Insert into SYS.RESOURCE_MAP (RESOURCE#,TYPE#,NAME) values (4,0,'LOGICAL_READS_PER_SESSION');
Insert into SYS.RESOURCE_MAP (RESOURCE#,TYPE#,NAME) values (5,0,'LOGICAL_READS_PER_CALL');
Insert into SYS.RESOURCE_MAP (RESOURCE#,TYPE#,NAME) values (6,0,'IDLE_TIME');
Insert into SYS.RESOURCE_MAP (RESOURCE#,TYPE#,NAME) values (7,0,'CONNECT_TIME');
Insert into SYS.RESOURCE_MAP (RESOURCE#,TYPE#,NAME) values (8,0,'PRIVATE_SGA');
Insert into SYS.RESOURCE_MAP (RESOURCE#,TYPE#,NAME) values (0,1,'FAILED_LOGIN_ATTEMPTS');
Insert into SYS.RESOURCE_MAP (RESOURCE#,TYPE#,NAME) values (1,1,'PASSWORD_LIFE_TIME');
Insert into SYS.RESOURCE_MAP (RESOURCE#,TYPE#,NAME) values (2,1,'PASSWORD_REUSE_TIME');
Insert into SYS.RESOURCE_MAP (RESOURCE#,TYPE#,NAME) values (3,1,'PASSWORD_REUSE_MAX');
Insert into SYS.RESOURCE_MAP (RESOURCE#,TYPE#,NAME) values (4,1,'PASSWORD_VERIFY_FUNCTION');
Insert into SYS.RESOURCE_MAP (RESOURCE#,TYPE#,NAME) values (5,1,'PASSWORD_LOCK_TIME');
Insert into SYS.RESOURCE_MAP (RESOURCE#,TYPE#,NAME) values (6,1,'PASSWORD_GRACE_TIME');
Insert into SYS.RESOURCE_MAP (RESOURCE#,TYPE#,NAME) values (7,1,'INACTIVE_ACCOUNT_TIME');
