--------------------------------------------------------
--  DDL for Table RESOURCE_PLAN_DIRECTIVE$
--------------------------------------------------------

  CREATE TABLE "SYS"."RESOURCE_PLAN_DIRECTIVE$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"PLAN" VARCHAR2(128 BYTE), 
	"GROUP_OR_SUBPLAN" VARCHAR2(128 BYTE), 
	"IS_SUBPLAN" NUMBER, 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"MANDATORY" NUMBER, 
	"MGMT_P1" NUMBER, 
	"MGMT_P2" NUMBER, 
	"MGMT_P3" NUMBER, 
	"MGMT_P4" NUMBER, 
	"MGMT_P5" NUMBER, 
	"MGMT_P6" NUMBER, 
	"MGMT_P7" NUMBER, 
	"MGMT_P8" NUMBER, 
	"MAX_ACTIVE_SESS_TARGET_P1" NUMBER, 
	"PARALLEL_DEGREE_LIMIT_P1" NUMBER, 
	"STATUS" VARCHAR2(128 BYTE), 
	"ACTIVE_SESS_POOL_P1" NUMBER, 
	"QUEUEING_P1" NUMBER, 
	"SWITCH_GROUP" VARCHAR2(128 BYTE), 
	"SWITCH_TIME" NUMBER, 
	"SWITCH_ESTIMATE" NUMBER, 
	"MAX_EST_EXEC_TIME" NUMBER, 
	"UNDO_POOL" NUMBER, 
	"MAX_IDLE_TIME" NUMBER, 
	"MAX_IDLE_BLOCKER_TIME" NUMBER, 
	"SWITCH_FOR_CALL" NUMBER, 
	"SWITCH_IO_MEGABYTES" NUMBER, 
	"SWITCH_IO_REQS" NUMBER, 
	"MAX_UTILIZATION_LIMIT" NUMBER, 
	"PARALLEL_QUEUE_TIMEOUT" NUMBER, 
	"PARALLEL_SERVER_LIMIT" NUMBER, 
	"SWITCH_IO_LOGICAL" NUMBER, 
	"SWITCH_ELAPSED_TIME" NUMBER, 
	"PARALLEL_STMT_CRITICAL" NUMBER, 
	"SESSION_PGA_LIMIT" NUMBER, 
	"PQ_TIMEOUT_ACTION" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
