REM INSERTING into SYS.RESOURCE_STORAGE_POOL_MAPPING$
SET DEFINE OFF;
Insert into SYS.RESOURCE_STORAGE_POOL_MAPPING$ (ATTRIBUTE,VALUE,POOL_NAME,STATUS) values ('LOG_FILES',null,'MANAGED_FILES','ACTIVE');
Insert into SYS.RESOURCE_STORAGE_POOL_MAPPING$ (ATTRIBUTE,VALUE,POOL_NAME,STATUS) values ('TEMP_FILES',null,'MANAGED_FILES','ACTIVE');
Insert into SYS.RESOURCE_STORAGE_POOL_MAPPING$ (ATTRIBUTE,VALUE,POOL_NAME,STATUS) values ('RECOVERY_AREA',null,'MANAGED_FILES','ACTIVE');
