--------------------------------------------------------
--  DDL for Table RESOURCE_IO_CALIBRATE$
--------------------------------------------------------

  CREATE TABLE "SYS"."RESOURCE_IO_CALIBRATE$" SHARING=METADATA 
   (	"START_TIME" TIMESTAMP (6), 
	"END_TIME" TIMESTAMP (6), 
	"MAX_IOPS" NUMBER, 
	"MAX_MBPS" NUMBER, 
	"MAX_PMBPS" NUMBER, 
	"LATENCY" NUMBER(*,3), 
	"NUM_DISKS" NUMBER, 
	"ADDITIONAL_INFO" VARCHAR2(1024 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
