REM INSERTING into SYS.RESOURCE_GROUP_MAPPING$
SET DEFINE OFF;
Insert into SYS.RESOURCE_GROUP_MAPPING$ (ATTRIBUTE,VALUE,CONSUMER_GROUP,STATUS) values ('ORACLE_USER','SYS','SYS_GROUP','ACTIVE');
Insert into SYS.RESOURCE_GROUP_MAPPING$ (ATTRIBUTE,VALUE,CONSUMER_GROUP,STATUS) values ('ORACLE_USER','SYSTEM','SYS_GROUP','ACTIVE');
Insert into SYS.RESOURCE_GROUP_MAPPING$ (ATTRIBUTE,VALUE,CONSUMER_GROUP,STATUS) values ('ORACLE_FUNCTION','BACKUP','BATCH_GROUP','ACTIVE');
Insert into SYS.RESOURCE_GROUP_MAPPING$ (ATTRIBUTE,VALUE,CONSUMER_GROUP,STATUS) values ('ORACLE_FUNCTION','COPY','BATCH_GROUP','ACTIVE');
Insert into SYS.RESOURCE_GROUP_MAPPING$ (ATTRIBUTE,VALUE,CONSUMER_GROUP,STATUS) values ('ORACLE_FUNCTION','DATALOAD','ETL_GROUP','ACTIVE');
Insert into SYS.RESOURCE_GROUP_MAPPING$ (ATTRIBUTE,VALUE,CONSUMER_GROUP,STATUS) values ('ORACLE_FUNCTION','INMEMORY','ORA$AUTOTASK','ACTIVE');
