REM INSERTING into SYS.RESOURCE_MAPPING_PRIORITY$
SET DEFINE OFF;
Insert into SYS.RESOURCE_MAPPING_PRIORITY$ (ATTRIBUTE,PRIORITY,STATUS) values ('EXPLICIT',1,'ACTIVE');
Insert into SYS.RESOURCE_MAPPING_PRIORITY$ (ATTRIBUTE,PRIORITY,STATUS) values ('ORACLE_USER',7,'ACTIVE');
Insert into SYS.RESOURCE_MAPPING_PRIORITY$ (ATTRIBUTE,PRIORITY,STATUS) values ('SERVICE_NAME',6,'ACTIVE');
Insert into SYS.RESOURCE_MAPPING_PRIORITY$ (ATTRIBUTE,PRIORITY,STATUS) values ('CLIENT_OS_USER',9,'ACTIVE');
Insert into SYS.RESOURCE_MAPPING_PRIORITY$ (ATTRIBUTE,PRIORITY,STATUS) values ('CLIENT_PROGRAM',8,'ACTIVE');
Insert into SYS.RESOURCE_MAPPING_PRIORITY$ (ATTRIBUTE,PRIORITY,STATUS) values ('CLIENT_MACHINE',10,'ACTIVE');
Insert into SYS.RESOURCE_MAPPING_PRIORITY$ (ATTRIBUTE,PRIORITY,STATUS) values ('MODULE_NAME',5,'ACTIVE');
Insert into SYS.RESOURCE_MAPPING_PRIORITY$ (ATTRIBUTE,PRIORITY,STATUS) values ('MODULE_NAME_ACTION',4,'ACTIVE');
Insert into SYS.RESOURCE_MAPPING_PRIORITY$ (ATTRIBUTE,PRIORITY,STATUS) values ('SERVICE_MODULE',3,'ACTIVE');
Insert into SYS.RESOURCE_MAPPING_PRIORITY$ (ATTRIBUTE,PRIORITY,STATUS) values ('SERVICE_MODULE_ACTION',2,'ACTIVE');
Insert into SYS.RESOURCE_MAPPING_PRIORITY$ (ATTRIBUTE,PRIORITY,STATUS) values ('CLIENT_ID',11,'ACTIVE');
