--------------------------------------------------------
--  DDL for Table RESOURCE_PLAN$
--------------------------------------------------------

  CREATE TABLE "SYS"."RESOURCE_PLAN$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"NAME" VARCHAR2(128 BYTE), 
	"MANDATORY" NUMBER, 
	"SUB_PLAN" NUMBER, 
	"MGMT_METHOD" VARCHAR2(128 BYTE), 
	"MAST_METHOD" VARCHAR2(128 BYTE), 
	"PDL_METHOD" VARCHAR2(128 BYTE), 
	"NUM_PLAN_DIRECTIVES" NUMBER, 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"STATUS" VARCHAR2(128 BYTE), 
	"QUE_METHOD" VARCHAR2(128 BYTE), 
	"MAX_IOPS" NUMBER, 
	"MAX_MBPS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
