REM INSERTING into SYS.RESOURCE_CATEGORY$
SET DEFINE OFF;
Insert into SYS.RESOURCE_CATEGORY$ (NAME,MANDATORY,DESCRIPTION,STATUS) values ('ADMINISTRATIVE',0,'Administrative Consumer Groups','ACTIVE');
Insert into SYS.RESOURCE_CATEGORY$ (NAME,MANDATORY,DESCRIPTION,STATUS) values ('INTERACTIVE',0,'Interactive, OLTP Consumer Groups','ACTIVE');
Insert into SYS.RESOURCE_CATEGORY$ (NAME,MANDATORY,DESCRIPTION,STATUS) values ('BATCH',0,'Batch, Non-Interactive Consumer Groups','ACTIVE');
Insert into SYS.RESOURCE_CATEGORY$ (NAME,MANDATORY,DESCRIPTION,STATUS) values ('MAINTENANCE',0,'Maintenance Consumer Groups','ACTIVE');
Insert into SYS.RESOURCE_CATEGORY$ (NAME,MANDATORY,DESCRIPTION,STATUS) values ('OTHER',1,'Unclassified Consumer Groups','ACTIVE');
