--------------------------------------------------------
--  Constraints for Table RLS$
--------------------------------------------------------

  ALTER TABLE "SYS"."RLS$" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."RLS$" MODIFY ("GNAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."RLS$" MODIFY ("PNAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."RLS$" MODIFY ("STMT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."RLS$" MODIFY ("CHECK_OPT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."RLS$" MODIFY ("ENABLE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "SYS"."RLS$" MODIFY ("PFSCHMA" NOT NULL ENABLE);
  ALTER TABLE "SYS"."RLS$" MODIFY ("PFNAME" NOT NULL ENABLE);
