--------------------------------------------------------
--  DDL for Table RLS$
--------------------------------------------------------

  CREATE TABLE "SYS"."RLS$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"GNAME" VARCHAR2(128 BYTE), 
	"PNAME" VARCHAR2(128 BYTE), 
	"STMT_TYPE" NUMBER, 
	"CHECK_OPT" NUMBER, 
	"ENABLE_FLAG" NUMBER, 
	"PFSCHMA" VARCHAR2(128 BYTE), 
	"PPNAME" VARCHAR2(128 BYTE), 
	"PFNAME" VARCHAR2(128 BYTE), 
	"PTYPE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
