REM INSERTING into SYS.RLS$
SET DEFINE OFF;
Insert into SYS.RLS$ (OBJ#,GNAME,PNAME,STMT_TYPE,CHECK_OPT,ENABLE_FLAG,PFSCHMA,PPNAME,PFNAME,PTYPE) values (21810,'SYS_DEFAULT','XDB$ACL$xd_sp',513,0,1,'XDB','DBMS_XDBZ0','CHECKPRIVRLS_SELECTPF',null);
Insert into SYS.RLS$ (OBJ#,GNAME,PNAME,STMT_TYPE,CHECK_OPT,ENABLE_FLAG,PFSCHMA,PPNAME,PFNAME,PTYPE) values (21810,'SYS_DEFAULT','XDB$ACL$xd_up',516,0,1,'XDB','DBMS_XDBZ0','CHECKPRIVRLS_UPDATEPF',null);
Insert into SYS.RLS$ (OBJ#,GNAME,PNAME,STMT_TYPE,CHECK_OPT,ENABLE_FLAG,PFSCHMA,PPNAME,PFNAME,PTYPE) values (21810,'SYS_DEFAULT','XDB$ACL$xd_dp',520,0,1,'XDB','DBMS_XDBZ0','CHECKPRIVRLS_DELETEPF',null);
Insert into SYS.RLS$ (OBJ#,GNAME,PNAME,STMT_TYPE,CHECK_OPT,ENABLE_FLAG,PFSCHMA,PPNAME,PFNAME,PTYPE) values (21822,'SYS_DEFAULT','XDB$RESCONFIG$xd_sp',513,0,1,'XDB','DBMS_XDBZ0','CHECKPRIVRLS_SELECTPF',null);
Insert into SYS.RLS$ (OBJ#,GNAME,PNAME,STMT_TYPE,CHECK_OPT,ENABLE_FLAG,PFSCHMA,PPNAME,PFNAME,PTYPE) values (21822,'SYS_DEFAULT','XDB$RESCONFIG$xd_up',516,0,1,'XDB','DBMS_XDBZ0','CHECKPRIVRLS_UPDATEPF',null);
Insert into SYS.RLS$ (OBJ#,GNAME,PNAME,STMT_TYPE,CHECK_OPT,ENABLE_FLAG,PFSCHMA,PPNAME,PFNAME,PTYPE) values (21822,'SYS_DEFAULT','XDB$RESCONFIG$xd_dp',520,0,1,'XDB','DBMS_XDBZ0','CHECKPRIVRLS_DELETEPF',null);
Insert into SYS.RLS$ (OBJ#,GNAME,PNAME,STMT_TYPE,CHECK_OPT,ENABLE_FLAG,PFSCHMA,PPNAME,PFNAME,PTYPE) values (21908,'SYS_DEFAULT','XDB$STATS$xd_sp',513,0,1,'XDB','DBMS_XDBZ0','CHECKPRIVRLS_SELECTPF',null);
Insert into SYS.RLS$ (OBJ#,GNAME,PNAME,STMT_TYPE,CHECK_OPT,ENABLE_FLAG,PFSCHMA,PPNAME,PFNAME,PTYPE) values (21908,'SYS_DEFAULT','XDB$STATS$xd_up',516,0,1,'XDB','DBMS_XDBZ0','CHECKPRIVRLS_UPDATEPF',null);
Insert into SYS.RLS$ (OBJ#,GNAME,PNAME,STMT_TYPE,CHECK_OPT,ENABLE_FLAG,PFSCHMA,PPNAME,PFNAME,PTYPE) values (21908,'SYS_DEFAULT','XDB$STATS$xd_dp',520,0,1,'XDB','DBMS_XDBZ0','CHECKPRIVRLS_DELETEPF',null);
Insert into SYS.RLS$ (OBJ#,GNAME,PNAME,STMT_TYPE,CHECK_OPT,ENABLE_FLAG,PFSCHMA,PPNAME,PFNAME,PTYPE) values (21922,'SYS_DEFAULT','XDB$CONFIG$xd_sp',513,0,1,'XDB','DBMS_XDBZ0','CHECKPRIVRLS_SELECTPF',null);
Insert into SYS.RLS$ (OBJ#,GNAME,PNAME,STMT_TYPE,CHECK_OPT,ENABLE_FLAG,PFSCHMA,PPNAME,PFNAME,PTYPE) values (21922,'SYS_DEFAULT','XDB$CONFIG$xd_up',516,0,1,'XDB','DBMS_XDBZ0','CHECKPRIVRLS_UPDATEPF',null);
Insert into SYS.RLS$ (OBJ#,GNAME,PNAME,STMT_TYPE,CHECK_OPT,ENABLE_FLAG,PFSCHMA,PPNAME,PFNAME,PTYPE) values (21922,'SYS_DEFAULT','XDB$CONFIG$xd_dp',520,0,1,'XDB','DBMS_XDBZ0','CHECKPRIVRLS_DELETEPF',null);
