--------------------------------------------------------
--  DDL for Table ROPP$X$KCCTKH
--------------------------------------------------------

  CREATE TABLE "SYS"."ROPP$X$KCCTKH" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"CON_ID" NUMBER, 
	"TKHRID" NUMBER, 
	"TKHTSN" NUMBER, 
	"TKHVRS" NUMBER, 
	"TKHFLG" NUMBER, 
	"TKHSTM" NUMBER, 
	"TKHPREKEY" NUMBER, 
	"TKHKOD_ENA" NUMBER, 
	"TKHKOD_KEY" RAW(48), 
	"TKHKOD_MKEYID" RAW(16), 
	"TKHKOD_MKLOC" NUMBER, 
	"TKHKOD_FLAG" NUMBER, 
	"INST_ID" NUMBER DEFAULT 1, 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
  PARTITION BY LIST ("CON_ID") 
 (PARTITION "P0"  VALUES (0) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ) ;
  GRANT SELECT ON "SYS"."ROPP$X$KCCTKH" TO "SELECT_CATALOG_ROLE";
