--------------------------------------------------------
--  DDL for Table ROPP$X$KCVFHTMP
--------------------------------------------------------

  CREATE TABLE "SYS"."ROPP$X$KCVFHTMP" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"CON_ID" NUMBER, 
	"HTMPXFIL" NUMBER, 
	"HTMPXONS" NUMBER, 
	"HTMPXERR" NUMBER, 
	"HTMPXVER" NUMBER, 
	"FHTMPSWV" NUMBER, 
	"FHTMPCVN" NUMBER, 
	"FHTMPDBI" NUMBER, 
	"FHTMPDBN" VARCHAR2(9 BYTE), 
	"FHTMPCSQ" NUMBER, 
	"FHTMPFSZ" NUMBER, 
	"FHTMPBSZ" NUMBER, 
	"FHTMPFNO" NUMBER, 
	"FHTMPTYP" NUMBER, 
	"FHTMPCRS" VARCHAR2(20 BYTE), 
	"FHTMPCRT" VARCHAR2(20 BYTE), 
	"FHTMPSTA" NUMBER, 
	"FHTMPCCC" NUMBER, 
	"FHTMPXCD" RAW(16), 
	"FHTMPTSN" NUMBER, 
	"FHTMPTNM" VARCHAR2(30 BYTE), 
	"FHTMPRFN" NUMBER, 
	"HTMPXFNM" VARCHAR2(513 BYTE), 
	"INST_ID" NUMBER DEFAULT 1
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
  PARTITION BY LIST ("CON_ID") 
 (PARTITION "P0"  VALUES (0) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ) ;
  GRANT SELECT ON "SYS"."ROPP$X$KCVFHTMP" TO "SELECT_CATALOG_ROLE";
