--------------------------------------------------------
--  DDL for Table ROPP$X$KCCTS
--------------------------------------------------------

  CREATE TABLE "SYS"."ROPP$X$KCCTS" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"CON_ID" NUMBER, 
	"TSRNO" NUMBER, 
	"TSTSN" NUMBER, 
	"TSNAM" VARCHAR2(30 BYTE), 
	"TSFLG" NUMBER, 
	"TSDFP" NUMBER, 
	"TSPSS" VARCHAR2(20 BYTE), 
	"TSPST" VARCHAR2(20 BYTE), 
	"TSPCS" VARCHAR2(20 BYTE), 
	"TSPCT" VARCHAR2(20 BYTE), 
	"TSKRI" NUMBER, 
	"INST_ID" NUMBER DEFAULT 1, 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
  PARTITION BY LIST ("CON_ID") 
 (PARTITION "P0"  VALUES (0) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ) ;
  GRANT SELECT ON "SYS"."ROPP$X$KCCTS" TO "SELECT_CATALOG_ROLE";
