--------------------------------------------------------
--  DDL for Table ROPP$X$KCCBL
--------------------------------------------------------

  CREATE TABLE "SYS"."ROPP$X$KCCBL" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"CON_ID" NUMBER, 
	"BLRID" NUMBER, 
	"BLTSM" VARCHAR2(20 BYTE), 
	"BLSTM" NUMBER, 
	"BLBSS" NUMBER, 
	"BLBSC" NUMBER, 
	"BLTHP" NUMBER, 
	"BLSEQ" NUMBER, 
	"BLRLS" VARCHAR2(20 BYTE), 
	"BLRLC" VARCHAR2(20 BYTE), 
	"BLLOS" VARCHAR2(20 BYTE), 
	"BLLOT" VARCHAR2(20 BYTE), 
	"BLNXS" VARCHAR2(20 BYTE), 
	"BLNXT" VARCHAR2(20 BYTE), 
	"BLBCT" NUMBER, 
	"BLBSZ" NUMBER, 
	"BLSIX" NUMBER, 
	"BLFLG" NUMBER, 
	"INST_ID" NUMBER DEFAULT 1, 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
  PARTITION BY LIST ("CON_ID") 
 (PARTITION "P0"  VALUES (0) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ) ;
  GRANT SELECT ON "SYS"."ROPP$X$KCCBL" TO "SELECT_CATALOG_ROLE";
