--------------------------------------------------------
--  DDL for Table ROPP$X$KCCOR
--------------------------------------------------------

  CREATE TABLE "SYS"."ROPP$X$KCCOR" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"CON_ID" NUMBER, 
	"ORRID" NUMBER, 
	"ORTSM" VARCHAR2(20 BYTE), 
	"ORSTM" NUMBER, 
	"ORDFP" NUMBER, 
	"ORFNP" NUMBER, 
	"OROFS" VARCHAR2(20 BYTE), 
	"ORONS" VARCHAR2(20 BYTE), 
	"ORONT" VARCHAR2(20 BYTE), 
	"ORRLS" VARCHAR2(20 BYTE), 
	"ORRLC" VARCHAR2(20 BYTE), 
	"ORIC" NUMBER, 
	"ORONC_THR" NUMBER, 
	"ORONC_RBA_SEQ" NUMBER, 
	"ORONC_RBA_BNO" NUMBER, 
	"ORONC_RBA_BOF" NUMBER, 
	"ORONC_ETB" VARCHAR2(264 BYTE), 
	"INST_ID" NUMBER DEFAULT 1, 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
  PARTITION BY LIST ("CON_ID") 
 (PARTITION "P0"  VALUES (0) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ) ;
  GRANT SELECT ON "SYS"."ROPP$X$KCCOR" TO "SELECT_CATALOG_ROLE";
