--------------------------------------------------------
--  DDL for Table ROPP$X$KCCFC
--------------------------------------------------------

  CREATE TABLE "SYS"."ROPP$X$KCCFC" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"CON_ID" NUMBER, 
	"FCRID" NUMBER, 
	"FCTSM" VARCHAR2(20 BYTE), 
	"FCSTM" NUMBER, 
	"FCBSS" NUMBER, 
	"FCBSC" NUMBER, 
	"FCFLG" NUMBER, 
	"FCDFP" NUMBER, 
	"FCPNO" NUMBER, 
	"FCBLK" NUMBER, 
	"FCCNT" NUMBER, 
	"FCSCN" VARCHAR2(20 BYTE), 
	"INST_ID" NUMBER DEFAULT 1, 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
  PARTITION BY LIST ("CON_ID") 
 (PARTITION "P0"  VALUES (0) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ) ;
  GRANT SELECT ON "SYS"."ROPP$X$KCCFC" TO "SELECT_CATALOG_ROLE";
