--------------------------------------------------------
--  DDL for Table ROPP$X$PDBHISTORY
--------------------------------------------------------

  CREATE TABLE "SYS"."ROPP$X$PDBHISTORY" SHARING=METADATA 
   (	"ORIGINAL_PDBDBID" NUMBER, 
	"LOCAL_PDBID" NUMBER, 
	"CDBDBID" NUMBER, 
	"TIMESTAMP" NUMBER, 
	"PDBID" NUMBER, 
	"PDBDBID" NUMBER, 
	"PDBGUID" NUMBER, 
	"TRANSTYPE" NUMBER, 
	"PREV_PDBID" NUMBER, 
	"PREV_CDBDBID" NUMBER, 
	"PREV_TIMESTAMP" NUMBER, 
	"PDB_BR_SCN" NUMBER, 
	"PDB_BR_TIM" NUMBER, 
	"PDB_BEGIN_CKPT" RAW(156), 
	"PDB_ER_SCN" NUMBER, 
	"PDB_ER_TIM" NUMBER, 
	"PDBENDSCN" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
