--------------------------------------------------------
--  DDL for Table ROPP$X$KCCCC
--------------------------------------------------------

  CREATE TABLE "SYS"."ROPP$X$KCCCC" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"CON_ID" NUMBER, 
	"CCRID" NUMBER, 
	"CCTSM" VARCHAR2(20 BYTE), 
	"CCSTM" NUMBER, 
	"CCFLG" NUMBER, 
	"CCDCP" NUMBER, 
	"CCDCS" NUMBER, 
	"CCDFP" NUMBER, 
	"CCBLK" NUMBER, 
	"CCCNT" NUMBER, 
	"CCSCN" VARCHAR2(20 BYTE), 
	"INST_ID" NUMBER DEFAULT 1, 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
  PARTITION BY LIST ("CON_ID") 
 (PARTITION "P0"  VALUES (0) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ) ;
  GRANT SELECT ON "SYS"."ROPP$X$KCCCC" TO "SELECT_CATALOG_ROLE";
