--------------------------------------------------------
--  DDL for Table ROPP$X$KCCSL
--------------------------------------------------------

  CREATE TABLE "SYS"."ROPP$X$KCCSL" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"CON_ID" NUMBER, 
	"SLNUM" NUMBER, 
	"SLPDB" NUMBER, 
	"SLTHR" NUMBER, 
	"SLSEQ" NUMBER, 
	"SLSIZ" NUMBER, 
	"SLBSZ" NUMBER, 
	"SLNAB" NUMBER, 
	"SLFLG" NUMBER, 
	"SLLOS" VARCHAR2(20 BYTE), 
	"SLLOT" VARCHAR2(20 BYTE), 
	"SLNXS" VARCHAR2(20 BYTE), 
	"SLNXT" VARCHAR2(20 BYTE), 
	"SLRLC" NUMBER, 
	"SLRLS" VARCHAR2(20 BYTE), 
	"SLLASTSCN" VARCHAR2(20 BYTE), 
	"SLLASTTIM" VARCHAR2(20 BYTE), 
	"INST_ID" NUMBER DEFAULT 1, 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
  PARTITION BY LIST ("CON_ID") 
 (PARTITION "P0"  VALUES (0) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ) ;
  GRANT SELECT ON "SYS"."ROPP$X$KCCSL" TO "SELECT_CATALOG_ROLE";
