--------------------------------------------------------
--  DDL for Table ROPP$X$KCCIC
--------------------------------------------------------

  CREATE TABLE "SYS"."ROPP$X$KCCIC" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"CON_ID" NUMBER, 
	"ICRID" NUMBER, 
	"ICRLS" VARCHAR2(20 BYTE), 
	"ICRLC" VARCHAR2(20 BYTE), 
	"ICRLC_I" NUMBER, 
	"ICPRS" VARCHAR2(20 BYTE), 
	"ICPRC" VARCHAR2(20 BYTE), 
	"ICPRC_I" NUMBER, 
	"ICLLH" NUMBER, 
	"ICLOR" NUMBER, 
	"ICHLH" NUMBER, 
	"ICHOR" NUMBER, 
	"ICPINC" NUMBER, 
	"ICFLG" NUMBER, 
	"ICALW" VARCHAR2(26 BYTE), 
	"INST_ID" NUMBER DEFAULT 1, 
	"ICSTM" NUMBER, 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
  PARTITION BY LIST ("CON_ID") 
 (PARTITION "P0"  VALUES (0) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ) ;
  GRANT SELECT ON "SYS"."ROPP$X$KCCIC" TO "SELECT_CATALOG_ROLE";
