--------------------------------------------------------
--  DDL for Table ROPP$X$KCCBS
--------------------------------------------------------

  CREATE TABLE "SYS"."ROPP$X$KCCBS" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"CON_ID" NUMBER, 
	"BSRID" NUMBER, 
	"BSTSM" VARCHAR2(20 BYTE), 
	"BSSTM" NUMBER, 
	"BSBSS" NUMBER, 
	"BSBST" VARCHAR2(20 BYTE), 
	"BSBSC" NUMBER, 
	"BSPCT" NUMBER, 
	"BSTYP" NUMBER, 
	"BSLVL" NUMBER, 
	"BSBSZ" NUMBER, 
	"BSKPT" VARCHAR2(20 BYTE), 
	"BSPFW" NUMBER, 
	"BSPLW" NUMBER, 
	"BSCAL" NUMBER, 
	"BSFLG2" NUMBER, 
	"BSGUID" RAW(16), 
	"INST_ID" NUMBER DEFAULT 1, 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
  PARTITION BY LIST ("CON_ID") 
 (PARTITION "P0"  VALUES (0) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ) ;
  GRANT SELECT ON "SYS"."ROPP$X$KCCBS" TO "SELECT_CATALOG_ROLE";
