--------------------------------------------------------
--  DDL for Table ROPP$X$KCCBI
--------------------------------------------------------

  CREATE TABLE "SYS"."ROPP$X$KCCBI" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"CON_ID" NUMBER, 
	"BIRID" NUMBER, 
	"BITSM" VARCHAR2(20 BYTE), 
	"BISTM" NUMBER, 
	"BIBSS" NUMBER, 
	"BIBSC" NUMBER, 
	"BIMDT" VARCHAR2(20 BYTE), 
	"BIFSZ" NUMBER, 
	"BISIX" NUMBER, 
	"BIDUN" VARCHAR2(30 BYTE), 
	"BIFLG" NUMBER, 
	"BIGUID" RAW(16), 
	"INST_ID" NUMBER DEFAULT 1, 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
  PARTITION BY LIST ("CON_ID") 
 (PARTITION "P0"  VALUES (0) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ) ;
  GRANT SELECT ON "SYS"."ROPP$X$KCCBI" TO "SELECT_CATALOG_ROLE";
