--------------------------------------------------------
--  DDL for Table ROPP$X$KCCBLKCOR
--------------------------------------------------------

  CREATE TABLE "SYS"."ROPP$X$KCCBLKCOR" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"CON_ID" NUMBER, 
	"BLKRID" NUMBER, 
	"BLKSTM" NUMBER, 
	"BLKTYPE" NUMBER, 
	"BLKFNO" NUMBER, 
	"BLKCRS" NUMBER, 
	"BLKCRT" DATE, 
	"BLKTOT" NUMBER, 
	"BLKSBLK" NUMBER, 
	"BLKSCN" NUMBER, 
	"BLKESCN" NUMBER, 
	"BLKBTM" DATE, 
	"BLKETM" DATE, 
	"BLKICRID" NUMBER, 
	"BLKOBJID" NUMBER, 
	"INST_ID" NUMBER DEFAULT 1, 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
  PARTITION BY LIST ("CON_ID") 
 (PARTITION "P0"  VALUES (0) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ) ;
  GRANT SELECT ON "SYS"."ROPP$X$KCCBLKCOR" TO "SELECT_CATALOG_ROLE";
