--------------------------------------------------------
--  DDL for Table ROPP$X$KCCBP
--------------------------------------------------------

  CREATE TABLE "SYS"."ROPP$X$KCCBP" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"CON_ID" NUMBER, 
	"BPRID" NUMBER, 
	"BPTSM" VARCHAR2(20 BYTE), 
	"BPSTM" NUMBER, 
	"BPBSS" NUMBER, 
	"BPBSC" NUMBER, 
	"BPFLG" NUMBER, 
	"BPNUM" NUMBER, 
	"BPEXT" NUMBER, 
	"BPTIM" VARCHAR2(20 BYTE), 
	"BPDEV" VARCHAR2(17 BYTE), 
	"BPHDL" VARCHAR2(513 BYTE), 
	"BPMDH" VARCHAR2(65 BYTE), 
	"BPCMT" VARCHAR2(64 BYTE), 
	"BPRSI" NUMBER, 
	"BPRST" NUMBER, 
	"BPTAG" VARCHAR2(32 BYTE), 
	"BPSZ1" NUMBER, 
	"BPFLG2" NUMBER, 
	"BPGUID" RAW(16), 
	"INST_ID" NUMBER DEFAULT 1, 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
  PARTITION BY LIST ("CON_ID") 
 (PARTITION "P0"  VALUES (0) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ) ;
  GRANT SELECT ON "SYS"."ROPP$X$KCCBP" TO "SELECT_CATALOG_ROLE";
