--------------------------------------------------------
--  DDL for Table ROPP$X$KCCFHXCP
--------------------------------------------------------

  CREATE TABLE "SYS"."ROPP$X$KCCFHXCP" SHARING=METADATA 
   (	"PDBID" NUMBER, 
	"CDBDBID" NUMBER, 
	"TIMESTAMP" NUMBER, 
	"META_SPARE1" NUMBER, 
	"META_SPARE2" NUMBER, 
	"FHXCP_SCN" NUMBER, 
	"FHXCP_TIM" NUMBER, 
	"FHXCP_THR" NUMBER, 
	"FHXCP_RBA_SEQ" NUMBER, 
	"FHXCP_RBA_BNO" NUMBER, 
	"FHXCP_RBA_BOF" NUMBER, 
	"FHXCP_ETB" RAW(132)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
