--------------------------------------------------------
--  DDL for Table ROPP$X$KCCSDM
--------------------------------------------------------

  CREATE TABLE "SYS"."ROPP$X$KCCSDM" SHARING=METADATA 
   (	"CDBDBID" NUMBER, 
	"TIMESTAMP" NUMBER, 
	"META_SPARE1" NUMBER, 
	"META_SPARE2" NUMBER, 
	"INDX" NUMBER, 
	"INST_ID" NUMBER DEFAULT 1, 
	"CON_ID" NUMBER, 
	"SDMID" NUMBER, 
	"SDMGAP" RAW(132), 
	"SDMDCON" RAW(132), 
	"SDMFLAG" NUMBER, 
	"SDMASCN" VARCHAR2(128 BYTE), 
	"SDMRLS" VARCHAR2(128 BYTE), 
	"SDMRLC" NUMBER, 
	"SDMSTATUS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
