--------------------------------------------------------
--  DDL for Table ROPP$X$KCPDBINC
--------------------------------------------------------

  CREATE TABLE "SYS"."ROPP$X$KCPDBINC" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"CON_ID" NUMBER, 
	"DBINC" NUMBER, 
	"DBRLS" NUMBER, 
	"DBRLC" DATE, 
	"PDBINC" NUMBER, 
	"STATUS" NUMBER, 
	"PR_CNFRM" NUMBER, 
	"INCSCN" NUMBER, 
	"INCTIME" DATE, 
	"BRSCN" NUMBER, 
	"BRTIME" DATE, 
	"ERSCN" NUMBER, 
	"ERTIME" DATE, 
	"PR_DBINC" NUMBER, 
	"PR_DBRLS" NUMBER, 
	"PR_DBRLC" DATE, 
	"PR_PDBINC" NUMBER, 
	"PR_PDBINC_NULL" NUMBER, 
	"PR_INCSCN" NUMBER, 
	"PR_ERSCN" NUMBER, 
	"FB_ALLOWED" NUMBER, 
	"INST_ID" NUMBER DEFAULT 1, 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
  PARTITION BY LIST ("CON_ID") 
 (PARTITION "P0"  VALUES (0) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ) ;
  GRANT SELECT ON "SYS"."ROPP$X$KCPDBINC" TO "SELECT_CATALOG_ROLE";
