--------------------------------------------------------
--  DDL for Table ROPP$X$KCCPIC
--------------------------------------------------------

  CREATE TABLE "SYS"."ROPP$X$KCCPIC" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"CON_ID" NUMBER, 
	"PICRNO" NUMBER, 
	"PICSTA" NUMBER, 
	"PICDBINC" VARCHAR2(128 BYTE), 
	"PICDBRLS" VARCHAR2(128 BYTE), 
	"PICDBRLC" NUMBER, 
	"PICID" NUMBER, 
	"PICINCS" VARCHAR2(128 BYTE), 
	"PICINCT" VARCHAR2(128 BYTE), 
	"PICBRLS" VARCHAR2(128 BYTE), 
	"PICBRLT" VARCHAR2(128 BYTE), 
	"PICERLS" VARCHAR2(128 BYTE), 
	"PICERLT" VARCHAR2(128 BYTE), 
	"PICPRIDBINC" NUMBER, 
	"PICPRIDBRLS" VARCHAR2(128 BYTE), 
	"PICPRIDBRLC" NUMBER, 
	"PICPRIPDBINC" NUMBER, 
	"PICPRIPDBINCS" VARCHAR2(128 BYTE), 
	"PICPRIPDBINCT" VARCHAR2(128 BYTE), 
	"PICPRIPDBBRLS" VARCHAR2(128 BYTE), 
	"PICPRIPDBBRLT" VARCHAR2(128 BYTE), 
	"PICPRIPDBERLS" VARCHAR2(128 BYTE), 
	"PICPRIPDBERLT" VARCHAR2(128 BYTE), 
	"INST_ID" NUMBER DEFAULT 1, 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
  PARTITION BY LIST ("CON_ID") 
 (PARTITION "P0"  VALUES (0) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ) ;
  GRANT SELECT ON "SYS"."ROPP$X$KCCPIC" TO "SELECT_CATALOG_ROLE";
