--------------------------------------------------------
--  DDL for Table ROPP$X$KCCFN
--------------------------------------------------------

  CREATE TABLE "SYS"."ROPP$X$KCCFN" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"CON_ID" NUMBER, 
	"FNNUM" NUMBER, 
	"FNTYP" NUMBER, 
	"FNFNO" NUMBER, 
	"FNFWD" NUMBER, 
	"FNBWD" NUMBER, 
	"FNFLG" NUMBER, 
	"FNNAM" VARCHAR2(513 BYTE), 
	"FNONM" VARCHAR2(513 BYTE), 
	"FNBOF" NUMBER, 
	"FNUNN" NUMBER, 
	"BYTES" NUMBER, 
	"INST_ID" NUMBER DEFAULT 1, 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
  PARTITION BY LIST ("CON_ID") 
 (PARTITION "P0"  VALUES (0) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ) ;
  GRANT SELECT ON "SYS"."ROPP$X$KCCFN" TO "SELECT_CATALOG_ROLE";
