--------------------------------------------------------
--  DDL for Table ROPP$X$KCCDI
--------------------------------------------------------

  CREATE TABLE "SYS"."ROPP$X$KCCDI" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"CON_ID" NUMBER, 
	"DICTS" VARCHAR2(20 BYTE), 
	"DIDBN" VARCHAR2(9 BYTE), 
	"DIRDB" NUMBER, 
	"DICCT" VARCHAR2(20 BYTE), 
	"DIFLG" NUMBER, 
	"DIIRS" VARCHAR2(20 BYTE), 
	"DIRLS" VARCHAR2(20 BYTE), 
	"DIRLC" VARCHAR2(20 BYTE), 
	"DIRLC_I" NUMBER, 
	"DIPRS" VARCHAR2(20 BYTE), 
	"DIPRC" VARCHAR2(20 BYTE), 
	"DIPRC_I" NUMBER, 
	"DIRDC" NUMBER, 
	"DINDF" NUMBER, 
	"DINTF" NUMBER, 
	"DINOF" NUMBER, 
	"DICPT" NUMBER, 
	"DISCN" VARCHAR2(20 BYTE), 
	"DINET" NUMBER, 
	"DINOT" NUMBER, 
	"DIOTH" NUMBER, 
	"DIOTT" NUMBER, 
	"DIETB" RAW(132), 
	"DIMLM" NUMBER, 
	"DIMDM" NUMBER, 
	"DIARH" NUMBER, 
	"DIART" NUMBER, 
	"DIPRT" NUMBER, 
	"DIFAS" VARCHAR2(20 BYTE), 
	"DICKP_SCN" VARCHAR2(20 BYTE), 
	"DICKP_TIM" VARCHAR2(20 BYTE), 
	"DICSQ" NUMBER, 
	"DIDBI" NUMBER, 
	"DISSC_SCN" VARCHAR2(20 BYTE), 
	"DISSC_TIM" VARCHAR2(20 BYTE), 
	"DISFP" NUMBER, 
	"DIBSC" NUMBER, 
	"DIPOFB" NUMBER, 
	"DIPNFB" NUMBER, 
	"DICOFB" NUMBER, 
	"DICNFB" NUMBER, 
	"DIVTS" VARCHAR2(20 BYTE), 
	"DICID" NUMBER, 
	"DIDOR" NUMBER, 
	"DISLH" NUMBER, 
	"DISLT" NUMBER, 
	"DIRAE" NUMBER, 
	"DIACID" NUMBER, 
	"DIARS" VARCHAR2(20 BYTE), 
	"DISOS" NUMBER, 
	"DIDGD" NUMBER, 
	"DIMLA" NUMBER, 
	"DIPDB" NUMBER, 
	"DIFL2" NUMBER, 
	"DIPLID" NUMBER, 
	"DIPLN" VARCHAR2(101 BYTE), 
	"DICUR_SCN" VARCHAR2(20 BYTE), 
	"DIDBUN" VARCHAR2(30 BYTE), 
	"DIFSTS" NUMBER, 
	"DIFOPR" NUMBER, 
	"DIFTHS" NUMBER, 
	"DIFTGT" VARCHAR2(30 BYTE), 
	"DIFOBS" VARCHAR2(512 BYTE), 
	"DIDBOP" NUMBER, 
	"DIBFN" NUMBER, 
	"DIBSQ" NUMBER, 
	"DIFL3" NUMBER, 
	"DIPRCT" VARCHAR2(512 BYTE), 
	"INST_ID" NUMBER DEFAULT 1, 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER, 
	"DIFMOD" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
  PARTITION BY LIST ("CON_ID") 
 (PARTITION "P0"  VALUES (0) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ) ;
  GRANT SELECT ON "SYS"."ROPP$X$KCCDI" TO "SELECT_CATALOG_ROLE";
