--------------------------------------------------------
--  DDL for Table ROPP$X$KCCTF
--------------------------------------------------------

  CREATE TABLE "SYS"."ROPP$X$KCCTF" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"CON_ID" NUMBER, 
	"TFNUM" NUMBER, 
	"TFAFN" NUMBER, 
	"TFCSZ" NUMBER, 
	"TFBSZ" NUMBER, 
	"TFSTA" NUMBER, 
	"TFCRC_SCN" VARCHAR2(20 BYTE), 
	"TFCRC_TIM" VARCHAR2(20 BYTE), 
	"TFFNH" NUMBER, 
	"TFFNT" NUMBER, 
	"TFDUP" NUMBER, 
	"TFTSN" NUMBER, 
	"TFTSI" NUMBER, 
	"TFRFN" NUMBER, 
	"TFPFT" NUMBER, 
	"TFMSZ" NUMBER, 
	"TFNSZ" NUMBER, 
	"TFPFP" NUMBER, 
	"INST_ID" NUMBER DEFAULT 1, 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
  PARTITION BY LIST ("CON_ID") 
 (PARTITION "P0"  VALUES (0) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ) ;
  GRANT SELECT ON "SYS"."ROPP$X$KCCTF" TO "SELECT_CATALOG_ROLE";
