--------------------------------------------------------
--  DDL for Table RPP$X$KCCLE
--------------------------------------------------------

  CREATE TABLE "SYS"."RPP$X$KCCLE" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"INST_ID" NUMBER DEFAULT 1, 
	"UNPLUG_CON_ID" NUMBER, 
	"LENUM" NUMBER, 
	"LESIZ" NUMBER, 
	"LESEQ" NUMBER, 
	"LEHWS" NUMBER, 
	"LEBSZ" NUMBER, 
	"LENAB" NUMBER, 
	"LEFLG" NUMBER, 
	"LETHR" NUMBER, 
	"LELFF" NUMBER, 
	"LELFB" NUMBER, 
	"LELOS" VARCHAR2(20 BYTE), 
	"LELOT" VARCHAR2(20 BYTE), 
	"LENXS" VARCHAR2(20 BYTE), 
	"LENXT" VARCHAR2(20 BYTE), 
	"LEPVS" VARCHAR2(20 BYTE), 
	"LEARF" NUMBER, 
	"LEARB" NUMBER, 
	"LEFNH" NUMBER, 
	"LEFNT" NUMBER, 
	"LEDUP" NUMBER, 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT SELECT ON "SYS"."RPP$X$KCCLE" TO "SELECT_CATALOG_ROLE";
