--------------------------------------------------------
--  DDL for Table RPP$X$KCCFC
--------------------------------------------------------

  CREATE TABLE "SYS"."RPP$X$KCCFC" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"INST_ID" NUMBER DEFAULT 1, 
	"UNPLUG_CON_ID" NUMBER, 
	"FCRID" NUMBER, 
	"FCTSM" VARCHAR2(20 BYTE), 
	"FCSTM" NUMBER, 
	"FCBSS" NUMBER, 
	"FCBSC" NUMBER, 
	"FCFLG" NUMBER, 
	"FCDFP" NUMBER, 
	"FCPNO" NUMBER, 
	"FCBLK" NUMBER, 
	"FCCNT" NUMBER, 
	"FCSCN" VARCHAR2(20 BYTE), 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT SELECT ON "SYS"."RPP$X$KCCFC" TO "SELECT_CATALOG_ROLE";
