--------------------------------------------------------
--  DDL for Table RPP$X$KCCFN
--------------------------------------------------------

  CREATE TABLE "SYS"."RPP$X$KCCFN" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"INST_ID" NUMBER DEFAULT 1, 
	"UNPLUG_CON_ID" NUMBER, 
	"FNNUM" NUMBER, 
	"FNTYP" NUMBER, 
	"FNFNO" NUMBER, 
	"FNFWD" NUMBER, 
	"FNBWD" NUMBER, 
	"FNFLG" NUMBER, 
	"FNNAM" VARCHAR2(513 BYTE), 
	"FNONM" VARCHAR2(513 BYTE), 
	"FNBOF" NUMBER, 
	"FNUNN" NUMBER, 
	"BYTES" NUMBER, 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT SELECT ON "SYS"."RPP$X$KCCFN" TO "SELECT_CATALOG_ROLE";
