--------------------------------------------------------
--  DDL for Table RPP$X$KCCBLKCOR
--------------------------------------------------------

  CREATE TABLE "SYS"."RPP$X$KCCBLKCOR" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"INST_ID" NUMBER DEFAULT 1, 
	"UNPLUG_CON_ID" NUMBER, 
	"BLKRID" NUMBER, 
	"BLKSTM" NUMBER, 
	"BLKTYPE" NUMBER, 
	"BLKFNO" NUMBER, 
	"BLKCRS" NUMBER, 
	"BLKCRT" DATE, 
	"BLKTOT" NUMBER, 
	"BLKSBLK" NUMBER, 
	"BLKSCN" NUMBER, 
	"BLKESCN" NUMBER, 
	"BLKBTM" DATE, 
	"BLKETM" DATE, 
	"BLKICRID" NUMBER, 
	"BLKOBJID" NUMBER, 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT SELECT ON "SYS"."RPP$X$KCCBLKCOR" TO "SELECT_CATALOG_ROLE";
