--------------------------------------------------------
--  DDL for Table RPP$X$KCCTKH
--------------------------------------------------------

  CREATE TABLE "SYS"."RPP$X$KCCTKH" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"INST_ID" NUMBER DEFAULT 1, 
	"UNPLUG_CON_ID" NUMBER, 
	"TKHRID" NUMBER, 
	"TKHTSN" NUMBER, 
	"TKHVRS" NUMBER, 
	"TKHFLG" NUMBER, 
	"TKHSTM" NUMBER, 
	"TKHPREKEY" NUMBER, 
	"TKHKOD_ENA" NUMBER, 
	"TKHKOD_KEY" RAW(48), 
	"TKHKOD_MKEYID" RAW(16), 
	"TKHKOD_MKLOC" NUMBER, 
	"TKHKOD_FLAG" NUMBER, 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT SELECT ON "SYS"."RPP$X$KCCTKH" TO "SELECT_CATALOG_ROLE";
