--------------------------------------------------------
--  DDL for Table RPP$X$KCCTS
--------------------------------------------------------

  CREATE TABLE "SYS"."RPP$X$KCCTS" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"INST_ID" NUMBER DEFAULT 1, 
	"UNPLUG_CON_ID" NUMBER, 
	"TSRNO" NUMBER, 
	"TSTSN" NUMBER, 
	"TSNAM" VARCHAR2(30 BYTE), 
	"TSFLG" NUMBER, 
	"TSDFP" NUMBER, 
	"TSPSS" VARCHAR2(20 BYTE), 
	"TSPST" VARCHAR2(20 BYTE), 
	"TSPCS" VARCHAR2(20 BYTE), 
	"TSPCT" VARCHAR2(20 BYTE), 
	"TSKRI" NUMBER, 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT SELECT ON "SYS"."RPP$X$KCCTS" TO "SELECT_CATALOG_ROLE";
