--------------------------------------------------------
--  DDL for Table RPP$X$KCVFHTMP
--------------------------------------------------------

  CREATE TABLE "SYS"."RPP$X$KCVFHTMP" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"INST_ID" NUMBER DEFAULT 1, 
	"UNPLUG_CON_ID" NUMBER, 
	"HTMPXFIL" NUMBER, 
	"HTMPXONS" NUMBER, 
	"HTMPXERR" NUMBER, 
	"HTMPXVER" NUMBER, 
	"FHTMPSWV" NUMBER, 
	"FHTMPCVN" NUMBER, 
	"FHTMPDBI" NUMBER, 
	"FHTMPDBN" VARCHAR2(9 BYTE), 
	"FHTMPCSQ" NUMBER, 
	"FHTMPFSZ" NUMBER, 
	"FHTMPBSZ" NUMBER, 
	"FHTMPFNO" NUMBER, 
	"FHTMPTYP" NUMBER, 
	"FHTMPCRS" VARCHAR2(20 BYTE), 
	"FHTMPCRT" VARCHAR2(20 BYTE), 
	"FHTMPSTA" NUMBER, 
	"FHTMPCCC" NUMBER, 
	"FHTMPXCD" RAW(16), 
	"FHTMPTSN" NUMBER, 
	"FHTMPTNM" VARCHAR2(30 BYTE), 
	"FHTMPRFN" NUMBER, 
	"HTMPXFNM" VARCHAR2(513 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT SELECT ON "SYS"."RPP$X$KCVFHTMP" TO "SELECT_CATALOG_ROLE";
