--------------------------------------------------------
--  DDL for Table RPP$X$KCCCC
--------------------------------------------------------

  CREATE TABLE "SYS"."RPP$X$KCCCC" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"INST_ID" NUMBER DEFAULT 1, 
	"UNPLUG_CON_ID" NUMBER, 
	"CCRID" NUMBER, 
	"CCTSM" VARCHAR2(20 BYTE), 
	"CCSTM" NUMBER, 
	"CCFLG" NUMBER, 
	"CCDCP" NUMBER, 
	"CCDCS" NUMBER, 
	"CCDFP" NUMBER, 
	"CCBLK" NUMBER, 
	"CCCNT" NUMBER, 
	"CCSCN" VARCHAR2(20 BYTE), 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT SELECT ON "SYS"."RPP$X$KCCCC" TO "SELECT_CATALOG_ROLE";
