--------------------------------------------------------
--  DDL for Table RPP$X$KCCIC
--------------------------------------------------------

  CREATE TABLE "SYS"."RPP$X$KCCIC" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"INST_ID" NUMBER DEFAULT 1, 
	"UNPLUG_CON_ID" NUMBER, 
	"ICRID" NUMBER, 
	"ICRLS" VARCHAR2(20 BYTE), 
	"ICRLC" VARCHAR2(20 BYTE), 
	"ICRLC_I" NUMBER, 
	"ICPRS" VARCHAR2(20 BYTE), 
	"ICPRC" VARCHAR2(20 BYTE), 
	"ICPRC_I" NUMBER, 
	"ICLLH" NUMBER, 
	"ICLOR" NUMBER, 
	"ICHLH" NUMBER, 
	"ICHOR" NUMBER, 
	"ICPINC" NUMBER, 
	"ICFLG" NUMBER, 
	"ICALW" VARCHAR2(26 BYTE), 
	"ICSTM" NUMBER, 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT SELECT ON "SYS"."RPP$X$KCCIC" TO "SELECT_CATALOG_ROLE";
