--------------------------------------------------------
--  DDL for Table RPP$X$KCCOR
--------------------------------------------------------

  CREATE TABLE "SYS"."RPP$X$KCCOR" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"INST_ID" NUMBER DEFAULT 1, 
	"UNPLUG_CON_ID" NUMBER, 
	"ORRID" NUMBER, 
	"ORTSM" VARCHAR2(20 BYTE), 
	"ORSTM" NUMBER, 
	"ORDFP" NUMBER, 
	"ORFNP" NUMBER, 
	"OROFS" VARCHAR2(20 BYTE), 
	"ORONS" VARCHAR2(20 BYTE), 
	"ORONT" VARCHAR2(20 BYTE), 
	"ORRLS" VARCHAR2(20 BYTE), 
	"ORRLC" VARCHAR2(20 BYTE), 
	"ORIC" NUMBER, 
	"ORONC_THR" NUMBER, 
	"ORONC_RBA_SEQ" NUMBER, 
	"ORONC_RBA_BNO" NUMBER, 
	"ORONC_RBA_BOF" NUMBER, 
	"ORONC_ETB" VARCHAR2(264 BYTE), 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT SELECT ON "SYS"."RPP$X$KCCOR" TO "SELECT_CATALOG_ROLE";
