--------------------------------------------------------
--  DDL for Table RPP$X$KCCLH
--------------------------------------------------------

  CREATE TABLE "SYS"."RPP$X$KCCLH" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"INST_ID" NUMBER DEFAULT 1, 
	"UNPLUG_CON_ID" NUMBER, 
	"LHRID" NUMBER, 
	"LHTSM" VARCHAR2(20 BYTE), 
	"LHSTM" NUMBER, 
	"LHTHP" NUMBER, 
	"LHTNP" NUMBER, 
	"LHSEQ" NUMBER, 
	"LHLOS" VARCHAR2(20 BYTE), 
	"LHLOT" VARCHAR2(20 BYTE), 
	"LHNXS" VARCHAR2(20 BYTE), 
	"LHNAM" VARCHAR2(513 BYTE), 
	"LHRLS" VARCHAR2(20 BYTE), 
	"LHRLC" VARCHAR2(20 BYTE), 
	"LHIC" NUMBER, 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT SELECT ON "SYS"."RPP$X$KCCLH" TO "SELECT_CATALOG_ROLE";
