--------------------------------------------------------
--  DDL for Table RPP$X$KCCBP
--------------------------------------------------------

  CREATE TABLE "SYS"."RPP$X$KCCBP" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"INST_ID" NUMBER DEFAULT 1, 
	"UNPLUG_CON_ID" NUMBER, 
	"BPRID" NUMBER, 
	"BPTSM" VARCHAR2(20 BYTE), 
	"BPSTM" NUMBER, 
	"BPBSS" NUMBER, 
	"BPBSC" NUMBER, 
	"BPFLG" NUMBER, 
	"BPNUM" NUMBER, 
	"BPEXT" NUMBER, 
	"BPTIM" VARCHAR2(20 BYTE), 
	"BPDEV" VARCHAR2(17 BYTE), 
	"BPHDL" VARCHAR2(513 BYTE), 
	"BPMDH" VARCHAR2(65 BYTE), 
	"BPCMT" VARCHAR2(64 BYTE), 
	"BPRSI" NUMBER, 
	"BPRST" NUMBER, 
	"BPTAG" VARCHAR2(32 BYTE), 
	"BPSZ1" NUMBER, 
	"BPFLG2" NUMBER, 
	"BPGUID" RAW(16), 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT SELECT ON "SYS"."RPP$X$KCCBP" TO "SELECT_CATALOG_ROLE";
