--------------------------------------------------------
--  DDL for Table RPP$X$KCPDBINC
--------------------------------------------------------

  CREATE TABLE "SYS"."RPP$X$KCPDBINC" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"INST_ID" NUMBER DEFAULT 1, 
	"UNPLUG_CON_ID" NUMBER, 
	"DBINC" NUMBER, 
	"DBRLS" NUMBER, 
	"DBRLC" DATE, 
	"PDBINC" NUMBER, 
	"STATUS" NUMBER, 
	"PR_CNFRM" NUMBER, 
	"INCSCN" NUMBER, 
	"INCTIME" DATE, 
	"BRSCN" NUMBER, 
	"BRTIME" DATE, 
	"ERSCN" NUMBER, 
	"ERTIME" DATE, 
	"PR_DBINC" NUMBER, 
	"PR_DBRLS" NUMBER, 
	"PR_DBRLC" DATE, 
	"PR_PDBINC" NUMBER, 
	"PR_PDBINC_NULL" NUMBER, 
	"PR_INCSCN" NUMBER, 
	"PR_ERSCN" NUMBER, 
	"FB_ALLOWED" NUMBER, 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT SELECT ON "SYS"."RPP$X$KCPDBINC" TO "SELECT_CATALOG_ROLE";
