--------------------------------------------------------
--  DDL for Table RPP$X$KCCRSR
--------------------------------------------------------

  CREATE TABLE "SYS"."RPP$X$KCCRSR" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"INST_ID" NUMBER DEFAULT 1, 
	"UNPLUG_CON_ID" NUMBER, 
	"RSRRID" NUMBER, 
	"RSRTST" NUMBER, 
	"RSRIS" NUMBER, 
	"RSRCI" VARCHAR2(33 BYTE), 
	"RSROP" VARCHAR2(33 BYTE), 
	"RSRES" NUMBER, 
	"RSRLV" NUMBER, 
	"RSRMP" NUMBER, 
	"RSRPI" NUMBER, 
	"RSRPS" NUMBER, 
	"RSR0I" NUMBER, 
	"RSR0S" NUMBER, 
	"RSRST" VARCHAR2(20 BYTE), 
	"RSRET" VARCHAR2(20 BYTE), 
	"RSRIM" NUMBER, 
	"RSROM" NUMBER, 
	"RSRFL" NUMBER, 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT SELECT ON "SYS"."RPP$X$KCCRSR" TO "SELECT_CATALOG_ROLE";
