--------------------------------------------------------
--  DDL for Table RPP$X$KCCPIC
--------------------------------------------------------

  CREATE TABLE "SYS"."RPP$X$KCCPIC" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"INST_ID" NUMBER DEFAULT 1, 
	"UNPLUG_CON_ID" NUMBER, 
	"PICRNO" NUMBER, 
	"PICSTA" NUMBER, 
	"PICDBINC" VARCHAR2(128 BYTE), 
	"PICDBRLS" VARCHAR2(128 BYTE), 
	"PICDBRLC" NUMBER, 
	"PICID" NUMBER, 
	"PICINCS" VARCHAR2(128 BYTE), 
	"PICINCT" VARCHAR2(128 BYTE), 
	"PICBRLS" VARCHAR2(128 BYTE), 
	"PICBRLT" VARCHAR2(128 BYTE), 
	"PICERLS" VARCHAR2(128 BYTE), 
	"PICERLT" VARCHAR2(128 BYTE), 
	"PICPRIDBINC" NUMBER, 
	"PICPRIDBRLS" VARCHAR2(128 BYTE), 
	"PICPRIDBRLC" NUMBER, 
	"PICPRIPDBINC" NUMBER, 
	"PICPRIPDBINCS" VARCHAR2(128 BYTE), 
	"PICPRIPDBINCT" VARCHAR2(128 BYTE), 
	"PICPRIPDBBRLS" VARCHAR2(128 BYTE), 
	"PICPRIPDBBRLT" VARCHAR2(128 BYTE), 
	"PICPRIPDBERLS" VARCHAR2(128 BYTE), 
	"PICPRIPDBERLT" VARCHAR2(128 BYTE), 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT SELECT ON "SYS"."RPP$X$KCCPIC" TO "SELECT_CATALOG_ROLE";
