--------------------------------------------------------
--  DDL for Table RPP$X$KCCPD
--------------------------------------------------------

  CREATE TABLE "SYS"."RPP$X$KCCPD" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"INST_ID" NUMBER DEFAULT 1, 
	"UNPLUG_CON_ID" NUMBER, 
	"PCRID" NUMBER, 
	"PCTSM" VARCHAR2(20 BYTE), 
	"PCSTM" NUMBER, 
	"PCFLG" NUMBER, 
	"PCMPL" NUMBER, 
	"PCTYP" NUMBER, 
	"PCTIM" VARCHAR2(20 BYTE), 
	"PCDEV" VARCHAR2(17 BYTE), 
	"PCHDL" VARCHAR2(513 BYTE), 
	"PCMDH" VARCHAR2(65 BYTE), 
	"PCCMT" VARCHAR2(81 BYTE), 
	"PCTAG" VARCHAR2(32 BYTE), 
	"PDFLG" NUMBER, 
	"PDDFP" NUMBER, 
	"PDCRS" VARCHAR2(20 BYTE), 
	"PDCRT" VARCHAR2(20 BYTE), 
	"PDCPS" VARCHAR2(20 BYTE), 
	"PDCPT" VARCHAR2(20 BYTE), 
	"PDRLS" VARCHAR2(20 BYTE), 
	"PDRLC" VARCHAR2(20 BYTE), 
	"PDRFS" VARCHAR2(20 BYTE), 
	"PDRFT" VARCHAR2(20 BYTE), 
	"PDAFS" VARCHAR2(20 BYTE), 
	"PDFSZ" NUMBER, 
	"PDBSZ" NUMBER, 
	"PDLOR" NUMBER, 
	"PDKPT" VARCHAR2(20 BYTE), 
	"PCRSI" NUMBER, 
	"PCRST" NUMBER, 
	"PCFDI" NUMBER, 
	"PCPLUS" NUMBER, 
	"PCPRLS" NUMBER, 
	"PCPRLT" DATE, 
	"PCPTSN" NUMBER, 
	"PCGUID" RAW(16), 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT SELECT ON "SYS"."RPP$X$KCCPD" TO "SELECT_CATALOG_ROLE";
