--------------------------------------------------------
--  DDL for Table RPP$X$KCCRT
--------------------------------------------------------

  CREATE TABLE "SYS"."RPP$X$KCCRT" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"INST_ID" NUMBER DEFAULT 1, 
	"UNPLUG_CON_ID" NUMBER, 
	"RTNUM" NUMBER, 
	"RTSTA" NUMBER, 
	"RTCKP_SCN" VARCHAR2(20 BYTE), 
	"RTCKP_TIM" VARCHAR2(20 BYTE), 
	"RTCKP_THR" NUMBER, 
	"RTCKP_RBA_SEQ" NUMBER, 
	"RTCKP_RBA_BNO" NUMBER, 
	"RTCKP_RBA_BOF" NUMBER, 
	"RTCKP_ETB" RAW(132), 
	"RTOTF" NUMBER, 
	"RTOTB" NUMBER, 
	"RTNLF" NUMBER, 
	"RTLFH" NUMBER, 
	"RTLFT" NUMBER, 
	"RTCLN" NUMBER, 
	"RTSEQ" NUMBER, 
	"RTENB" VARCHAR2(20 BYTE), 
	"RTETS" VARCHAR2(20 BYTE), 
	"RTDIS" VARCHAR2(20 BYTE), 
	"RTDIT" VARCHAR2(20 BYTE), 
	"RTLHP" NUMBER, 
	"RTSID" VARCHAR2(16 BYTE), 
	"RTOTS" VARCHAR2(20 BYTE), 
	"RTFBCU" NUMBER, 
	"RTFBRS" NUMBER, 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT SELECT ON "SYS"."RPP$X$KCCRT" TO "SELECT_CATALOG_ROLE";
