--------------------------------------------------------
--  DDL for Table RPP$X$KCCTIR
--------------------------------------------------------

  CREATE TABLE "SYS"."RPP$X$KCCTIR" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"INST_ID" NUMBER DEFAULT 1, 
	"UNPLUG_CON_ID" NUMBER, 
	"TIRNUM" NUMBER, 
	"TIRSID" VARCHAR2(80 BYTE), 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT SELECT ON "SYS"."RPP$X$KCCTIR" TO "SELECT_CATALOG_ROLE";
