--------------------------------------------------------
--  DDL for Table RPP$X$KCCBL
--------------------------------------------------------

  CREATE TABLE "SYS"."RPP$X$KCCBL" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"INST_ID" NUMBER DEFAULT 1, 
	"UNPLUG_CON_ID" NUMBER, 
	"BLRID" NUMBER, 
	"BLTSM" VARCHAR2(20 BYTE), 
	"BLSTM" NUMBER, 
	"BLBSS" NUMBER, 
	"BLBSC" NUMBER, 
	"BLTHP" NUMBER, 
	"BLSEQ" NUMBER, 
	"BLRLS" VARCHAR2(20 BYTE), 
	"BLRLC" VARCHAR2(20 BYTE), 
	"BLLOS" VARCHAR2(20 BYTE), 
	"BLLOT" VARCHAR2(20 BYTE), 
	"BLNXS" VARCHAR2(20 BYTE), 
	"BLNXT" VARCHAR2(20 BYTE), 
	"BLBCT" NUMBER, 
	"BLBSZ" NUMBER, 
	"BLSIX" NUMBER, 
	"BLFLG" NUMBER, 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT SELECT ON "SYS"."RPP$X$KCCBL" TO "SELECT_CATALOG_ROLE";
