--------------------------------------------------------
--  DDL for Table RPP$X$KCCTF
--------------------------------------------------------

  CREATE TABLE "SYS"."RPP$X$KCCTF" SHARING=METADATA 
   (	"INDX" NUMBER, 
	"INST_ID" NUMBER DEFAULT 1, 
	"UNPLUG_CON_ID" NUMBER, 
	"TFNUM" NUMBER, 
	"TFAFN" NUMBER, 
	"TFCSZ" NUMBER, 
	"TFBSZ" NUMBER, 
	"TFSTA" NUMBER, 
	"TFCRC_SCN" VARCHAR2(20 BYTE), 
	"TFCRC_TIM" VARCHAR2(20 BYTE), 
	"TFFNH" NUMBER, 
	"TFFNT" NUMBER, 
	"TFDUP" NUMBER, 
	"TFTSN" NUMBER, 
	"TFTSI" NUMBER, 
	"TFRFN" NUMBER, 
	"TFPFT" NUMBER, 
	"TFMSZ" NUMBER, 
	"TFNSZ" NUMBER, 
	"TFPFP" NUMBER, 
	"RPP_CDBDBID" NUMBER, 
	"RPP_TIMESTAMP" NUMBER, 
	"RPP_META_SPARE1" NUMBER, 
	"RPP_META_SPARE2" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT SELECT ON "SYS"."RPP$X$KCCTF" TO "SELECT_CATALOG_ROLE";
