--------------------------------------------------------
--  DDL for Table RULE_SET$
--------------------------------------------------------

  CREATE TABLE "SYS"."RULE_SET$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"ECTX#" NUMBER, 
	"PROPERTY" NUMBER, 
	"RS_COMMENT" VARCHAR2(4000 BYTE), 
	"NUM_RULES" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
