REM INSERTING into SYS.RULE_EC$
SET DEFINE OFF;
Insert into SYS.RULE_EC$ (OBJ#,EVAL_FUNC,PROPERTY,EC_COMMENT,NUM_TABS,NUM_VARS) values (19651,null,1,null,1,0);
Insert into SYS.RULE_EC$ (OBJ#,EVAL_FUNC,PROPERTY,EC_COMMENT,NUM_TABS,NUM_VARS) values (19685,null,1,null,1,0);
Insert into SYS.RULE_EC$ (OBJ#,EVAL_FUNC,PROPERTY,EC_COMMENT,NUM_TABS,NUM_VARS) values (19715,null,1,null,1,0);
Insert into SYS.RULE_EC$ (OBJ#,EVAL_FUNC,PROPERTY,EC_COMMENT,NUM_TABS,NUM_VARS) values (19770,null,1,null,1,0);
Insert into SYS.RULE_EC$ (OBJ#,EVAL_FUNC,PROPERTY,EC_COMMENT,NUM_TABS,NUM_VARS) values (20071,null,1,null,1,0);
Insert into SYS.RULE_EC$ (OBJ#,EVAL_FUNC,PROPERTY,EC_COMMENT,NUM_TABS,NUM_VARS) values (20290,null,1,null,1,0);
Insert into SYS.RULE_EC$ (OBJ#,EVAL_FUNC,PROPERTY,EC_COMMENT,NUM_TABS,NUM_VARS) values (20326,null,1,null,1,0);
Insert into SYS.RULE_EC$ (OBJ#,EVAL_FUNC,PROPERTY,EC_COMMENT,NUM_TABS,NUM_VARS) values (20472,'SYS.DBMS_STREAMS_INTERNAL.EVALUATION_CONTEXT_FUNCTION',0,null,0,4);
Insert into SYS.RULE_EC$ (OBJ#,EVAL_FUNC,PROPERTY,EC_COMMENT,NUM_TABS,NUM_VARS) values (20485,null,1,null,1,0);
Insert into SYS.RULE_EC$ (OBJ#,EVAL_FUNC,PROPERTY,EC_COMMENT,NUM_TABS,NUM_VARS) values (20650,null,1,null,1,0);
Insert into SYS.RULE_EC$ (OBJ#,EVAL_FUNC,PROPERTY,EC_COMMENT,NUM_TABS,NUM_VARS) values (20792,null,1,null,1,0);
Insert into SYS.RULE_EC$ (OBJ#,EVAL_FUNC,PROPERTY,EC_COMMENT,NUM_TABS,NUM_VARS) values (22528,null,1,null,1,0);
Insert into SYS.RULE_EC$ (OBJ#,EVAL_FUNC,PROPERTY,EC_COMMENT,NUM_TABS,NUM_VARS) values (72182,null,0,null,0,1);
