--------------------------------------------------------
--  DDL for Table RULE$
--------------------------------------------------------

  CREATE TABLE "SYS"."RULE$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"CONDITION" CLOB, 
	"ECTX#" NUMBER, 
	"R_ACTION" "SYS"."RE$NV_LIST" , 
	"PROPERTY" NUMBER, 
	"R_COMMENT" VARCHAR2(4000 BYTE), 
	"UACTX_CLIENT" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CONDITION") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
