REM INSERTING into SYS.RULE_SET_ROP$
SET DEFINE OFF;
Insert into SYS.RULE_SET_ROP$ (RS_OBJ#,EC_OBJ#,RULE_ID,RULE_OR_PIECE,ROP_ID,PAROP_ID,AROP_ID,EVAL_ID,BOX_ID,USESFP,NOPSFP,VARSFP,PRNUM) values (19786,19770,0,0,0,0,0,0,1,0,null,null,0);
Insert into SYS.RULE_SET_ROP$ (RS_OBJ#,EC_OBJ#,RULE_ID,RULE_OR_PIECE,ROP_ID,PAROP_ID,AROP_ID,EVAL_ID,BOX_ID,USESFP,NOPSFP,VARSFP,PRNUM) values (19786,19770,0,0,1,0,0,0,3,0,null,null,0);
Insert into SYS.RULE_SET_ROP$ (RS_OBJ#,EC_OBJ#,RULE_ID,RULE_OR_PIECE,ROP_ID,PAROP_ID,AROP_ID,EVAL_ID,BOX_ID,USESFP,NOPSFP,VARSFP,PRNUM) values (20398,19770,0,0,0,0,0,0,1,0,null,null,0);
Insert into SYS.RULE_SET_ROP$ (RS_OBJ#,EC_OBJ#,RULE_ID,RULE_OR_PIECE,ROP_ID,PAROP_ID,AROP_ID,EVAL_ID,BOX_ID,USESFP,NOPSFP,VARSFP,PRNUM) values (20398,19770,0,0,1,0,0,0,3,0,null,null,0);
