--------------------------------------------------------
--  DDL for Table RULE_SET_EE$
--------------------------------------------------------

  CREATE TABLE "SYS"."RULE_SET_EE$" SHARING=METADATA 
   (	"RS_OBJ#" NUMBER, 
	"ECTX#" NUMBER, 
	"NUM_RULES" NUMBER, 
	"NUM_BOXES" NUMBER, 
	"COMPLEX_OPERATORS" NUMBER, 
	"EE_FLAGS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
