--------------------------------------------------------
--  DDL for Table RULE_SET_NL$
--------------------------------------------------------

  CREATE TABLE "SYS"."RULE_SET_NL$" SHARING=METADATA 
   (	"RS_OBJ#" NUMBER, 
	"EC_OBJ#" NUMBER, 
	"BOX_ID" NUMBER, 
	"NE_ID" NUMBER, 
	"NAME" VARCHAR2(128 BYTE), 
	"ATTR_ID" NUMBER, 
	"TOID" RAW(16), 
	"VERSION" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
