--------------------------------------------------------
--  DDL for Table RULE_SET_RE$
--------------------------------------------------------

  CREATE TABLE "SYS"."RULE_SET_RE$" SHARING=METADATA 
   (	"RS_OBJ#" NUMBER, 
	"EC_OBJ#" NUMBER, 
	"RULE_ID" NUMBER, 
	"R_OBJ#" NUMBER, 
	"R_ORCOUNT" NUMBER, 
	"R_LOWBOX" NUMBER, 
	"TABS_USED" RAW(2000), 
	"VARS_USED" RAW(2000), 
	"PROPERTY" NUMBER, 
	"ENT_USED" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
