--------------------------------------------------------
--  DDL for Table RULE_SET_ROR$
--------------------------------------------------------

  CREATE TABLE "SYS"."RULE_SET_ROR$" SHARING=METADATA 
   (	"RS_OBJ#" NUMBER, 
	"EC_OBJ#" NUMBER, 
	"RULE_ID" NUMBER, 
	"RULE_OR_PIECE" NUMBER, 
	"NUM_ROPS" NUMBER, 
	"BOX_ID" NUMBER, 
	"PROPERTY" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
