--------------------------------------------------------
--  Constraints for Table RULE_SET_ROP$
--------------------------------------------------------

  ALTER TABLE "SYS"."RULE_SET_ROP$" ADD PRIMARY KEY ("RS_OBJ#", "EC_OBJ#", "RULE_ID", "RULE_OR_PIECE", "ROP_ID", "PAROP_ID", "AROP_ID", "EVAL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE;
