--------------------------------------------------------
--  DDL for Table RULE_EC$
--------------------------------------------------------

  CREATE TABLE "SYS"."RULE_EC$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"EVAL_FUNC" VARCHAR2(4000 BYTE), 
	"PROPERTY" NUMBER, 
	"EC_COMMENT" VARCHAR2(4000 BYTE), 
	"NUM_TABS" NUMBER, 
	"NUM_VARS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
