REM INSERTING into SYS.RULE_SET_EE$
SET DEFINE OFF;
Insert into SYS.RULE_SET_EE$ (RS_OBJ#,ECTX#,NUM_RULES,NUM_BOXES,COMPLEX_OPERATORS,EE_FLAGS) values (20398,19770,1,4,null,4);
Insert into SYS.RULE_SET_EE$ (RS_OBJ#,ECTX#,NUM_RULES,NUM_BOXES,COMPLEX_OPERATORS,EE_FLAGS) values (19786,19770,1,4,null,4);
