REM INSERTING into SYS.RULE_SET_ROR$
SET DEFINE OFF;
Insert into SYS.RULE_SET_ROR$ (RS_OBJ#,EC_OBJ#,RULE_ID,RULE_OR_PIECE,NUM_ROPS,BOX_ID,PROPERTY) values (20398,19770,0,0,2,2,1);
Insert into SYS.RULE_SET_ROR$ (RS_OBJ#,EC_OBJ#,RULE_ID,RULE_OR_PIECE,NUM_ROPS,BOX_ID,PROPERTY) values (19786,19770,0,0,2,2,1);
