--------------------------------------------------------
--  DDL for Table RULE_SET_ROP$
--------------------------------------------------------

  CREATE TABLE "SYS"."RULE_SET_ROP$" SHARING=METADATA 
   (	"RS_OBJ#" NUMBER, 
	"EC_OBJ#" NUMBER, 
	"RULE_ID" NUMBER, 
	"RULE_OR_PIECE" NUMBER, 
	"ROP_ID" NUMBER, 
	"PAROP_ID" NUMBER, 
	"AROP_ID" NUMBER, 
	"EVAL_ID" NUMBER, 
	"BOX_ID" NUMBER, 
	"USESFP" NUMBER, 
	"NOPSFP" NUMBER, 
	"VARSFP" RAW(2000), 
	"PRNUM" NUMBER, 
	 PRIMARY KEY ("RS_OBJ#", "EC_OBJ#", "RULE_ID", "RULE_OR_PIECE", "ROP_ID", "PAROP_ID", "AROP_ID", "EVAL_ID") ENABLE
   ) ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 PCTTHRESHOLD 50 OVERFLOW
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
