--------------------------------------------------------
--  DDL for Table RULE_SET_FOB$
--------------------------------------------------------

  CREATE TABLE "SYS"."RULE_SET_FOB$" SHARING=METADATA 
   (	"RS_OBJ#" NUMBER, 
	"EC_OBJ#" NUMBER, 
	"BOX_ID" NUMBER, 
	"BOX_TYPE" NUMBER, 
	"OPR_TYPE" NUMBER, 
	"OET_TYPE" NUMBER, 
	"OEFLAGS" NUMBER, 
	"NUM_EXPRS" NUMBER, 
	"OPEXPR_N1" NUMBER, 
	"OPEXPR_N2" NUMBER, 
	"OPEXPR_N3" NUMBER, 
	"OPEXPR_C1" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
