--------------------------------------------------------
--  DDL for Table RXS$SESSION_APPNS
--------------------------------------------------------

  CREATE TABLE "SYS"."RXS$SESSION_APPNS" SHARING=METADATA 
   (	"SID" RAW(16), 
	"NSNAME" VARCHAR2(128 BYTE), 
	"ATTRNAME" VARCHAR2(4000 BYTE), 
	"NSACLID" NUMBER(10,0), 
	"NSHANDLER" VARCHAR2(400 BYTE), 
	"NSAUDIT" NUMBER(10,0), 
	"FLAGS" NUMBER(10,0), 
	"ATTRVALUE" VARCHAR2(4000 BYTE), 
	"MODTIME" TIMESTAMP (6), 
	"ATTR_DEFAULT_VALUE" VARCHAR2(4000 BYTE), 
	"WSPACE" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
