--------------------------------------------------------
--  Constraints for Table RXS$SESSION_ROLES
--------------------------------------------------------

  ALTER TABLE "SYS"."RXS$SESSION_ROLES" MODIFY ("SID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."RXS$SESSION_ROLES" MODIFY ("ROLEID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."RXS$SESSION_ROLES" MODIFY ("ROLEGUID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."RXS$SESSION_ROLES" MODIFY ("ROLENAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."RXS$SESSION_ROLES" MODIFY ("ROLEFLAGS" NOT NULL ENABLE);
