--------------------------------------------------------
--  DDL for Table RXS$SESSION_ROLES
--------------------------------------------------------

  CREATE TABLE "SYS"."RXS$SESSION_ROLES" SHARING=METADATA 
   (	"SID" RAW(16), 
	"ROLEID" NUMBER(10,0), 
	"ROLEGUID" RAW(16), 
	"ROLENAME" VARCHAR2(128 BYTE), 
	"ROLEFLAGS" NUMBER(10,0), 
	"EFFSTARTDATE" TIMESTAMP (6), 
	"EFFENDDATE" TIMESTAMP (6), 
	"PARENTID" NUMBER(10,0), 
	"REFCOUNT" NUMBER(10,0), 
	"WSPACE" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
