--------------------------------------------------------
--  Constraints for Table RXS$SESSIONS
--------------------------------------------------------

  ALTER TABLE "SYS"."RXS$SESSIONS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."RXS$SESSIONS" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."RXS$SESSIONS" MODIFY ("SID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."RXS$SESSIONS" MODIFY ("CREATORID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."RXS$SESSIONS" MODIFY ("UPDATORID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."RXS$SESSIONS" MODIFY ("CREATETIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."RXS$SESSIONS" MODIFY ("AUTHTIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."RXS$SESSIONS" MODIFY ("ACCESSTIME" NOT NULL ENABLE);
