--------------------------------------------------------
--  DDL for Table RXS$SESSIONS
--------------------------------------------------------

  CREATE TABLE "SYS"."RXS$SESSIONS" SHARING=METADATA 
   (	"USERNAME" VARCHAR2(128 BYTE), 
	"USERID" NUMBER(10,0), 
	"USERGUID" RAW(16), 
	"ACLOID" NUMBER, 
	"SID" RAW(16), 
	"COOKIE" VARCHAR2(1024 BYTE), 
	"PROXYGUID" RAW(16), 
	"CREATORID" NUMBER(10,0), 
	"UPDATORID" NUMBER(10,0), 
	"CREATETIME" TIMESTAMP (6), 
	"AUTHTIME" TIMESTAMP (6), 
	"ACCESSTIME" TIMESTAMP (6), 
	"INACTIVETIMEOUT" NUMBER(6,0), 
	"SESSIZE" NUMBER, 
	"FLAG" NUMBER, 
	"PROXYID" NUMBER(10,0), 
	"EFFSTARTDATE" TIMESTAMP (6), 
	"EFFENDDATE" TIMESTAMP (6), 
	"RGVERSION" NUMBER(10,0), 
	"ATTACHVERSION" NUMBER(10,0), 
	"WSPACE" VARCHAR2(128 BYTE), 
	"SCVERSION" NUMBER(10,0), 
	"SCINSID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
  GRANT SELECT ON "SYS"."RXS$SESSIONS" TO "XS_CACHE_ADMIN";
