--------------------------------------------------------
--  DDL for Table SAM_SPARSITY_ADVICE
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "SYS"."SAM_SPARSITY_ADVICE" SHARING=METADATA 
   (	"CUBENAME" VARCHAR2(600 BYTE), 
	"FACT" VARCHAR2(4000 BYTE), 
	"DIMENSION" VARCHAR2(300 BYTE), 
	"DIMCOLUMN" VARCHAR2(300 BYTE), 
	"DIMSOURCE" VARCHAR2(4000 BYTE), 
	"MEMBERCOUNT" NUMBER(12,0), 
	"LEAFCOUNT" NUMBER(12,0), 
	"ADVICE" VARCHAR2(10 BYTE), 
	"POSITION" NUMBER(4,0), 
	"DENSITY" NUMBER(11,8), 
	"PARTNUM" NUMBER(6,0), 
	"PARTBY" CLOB, 
	"PARTTOPS" CLOB, 
	"PARTLEVEL" VARCHAR2(600 BYTE)
   ) ON COMMIT DELETE ROWS 
 LOB ("PARTBY") STORE AS BASICFILE (
  ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE ) 
 LOB ("PARTTOPS") STORE AS BASICFILE (
  ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE ) ;
  GRANT DELETE ON "SYS"."SAM_SPARSITY_ADVICE" TO PUBLIC;
  GRANT INSERT ON "SYS"."SAM_SPARSITY_ADVICE" TO PUBLIC;
  GRANT SELECT ON "SYS"."SAM_SPARSITY_ADVICE" TO PUBLIC;
  GRANT UPDATE ON "SYS"."SAM_SPARSITY_ADVICE" TO PUBLIC;
