--------------------------------------------------------
--  Constraints for Table SAM_SPARSITY_ADVICE
--------------------------------------------------------

  ALTER TABLE "SYS"."SAM_SPARSITY_ADVICE" MODIFY ("CUBENAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SAM_SPARSITY_ADVICE" MODIFY ("FACT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SAM_SPARSITY_ADVICE" MODIFY ("DIMENSION" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SAM_SPARSITY_ADVICE" MODIFY ("ADVICE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SAM_SPARSITY_ADVICE" MODIFY ("POSITION" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SAM_SPARSITY_ADVICE" MODIFY ("PARTNUM" NOT NULL ENABLE);
