--------------------------------------------------------
--  DDL for Table SCHEDULER$_LIGHTWEIGHT_JOB
--------------------------------------------------------

  CREATE TABLE "SYS"."SCHEDULER$_LIGHTWEIGHT_JOB" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"PROGRAM_OID" NUMBER, 
	"START_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"END_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"SCHEDULE_EXPR" VARCHAR2(4000 BYTE), 
	"QUEUE_OWNER" VARCHAR2(128 BYTE), 
	"QUEUE_NAME" VARCHAR2(128 BYTE), 
	"QUEUE_AGENT" VARCHAR2(523 BYTE), 
	"EVENT_RULE" VARCHAR2(261 BYTE), 
	"SCHEDULE_ID" NUMBER, 
	"LAST_ENABLED_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"CLASS_OID" NUMBER, 
	"MXDUR_MSGID" RAW(16), 
	"FLAGS" NUMBER, 
	"CREATOR" VARCHAR2(128 BYTE), 
	"CLIENT_ID" VARCHAR2(64 BYTE), 
	"GUID" VARCHAR2(32 BYTE), 
	"CHAR_ENV" VARCHAR2(4000 BYTE), 
	"FW_NAME" VARCHAR2(261 BYTE), 
	"FW_OID" NUMBER, 
	"JOB_STATUS" NUMBER, 
	"NEXT_RUN_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"LAST_START_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"LAST_END_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"RETRY_COUNT" NUMBER, 
	"RUN_COUNT" NUMBER, 
	"FAILURE_COUNT" NUMBER, 
	"RUNNING_INSTANCE" NUMBER, 
	"RUNNING_SLAVE" NUMBER, 
	"INSTANCE_ID" NUMBER, 
	"DEST_OID" NUMBER, 
	"DESTINATION" VARCHAR2(261 BYTE), 
	"CREDENTIAL_NAME" VARCHAR2(128 BYTE), 
	"CREDENTIAL_OWNER" VARCHAR2(128 BYTE), 
	"CREDENTIAL_OID" NUMBER, 
	"JOB_DEST_ID" NUMBER, 
	"RUN_INVOKER" NUMBER, 
	"CONNECT_CREDENTIAL_NAME" VARCHAR2(128 BYTE), 
	"CONNECT_CREDENTIAL_OWNER" VARCHAR2(128 BYTE), 
	"CONNECT_CREDENTIAL_OID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
