--------------------------------------------------------
--  DDL for Table SCHEDULER$_FILE_WATCHER
--------------------------------------------------------

  CREATE TABLE "SYS"."SCHEDULER$_FILE_WATCHER" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"DIRECTORY_PATH" VARCHAR2(4000 BYTE), 
	"FILE_NAME" VARCHAR2(512 BYTE), 
	"DESTINATION" VARCHAR2(261 BYTE), 
	"DESTOID" NUMBER, 
	"CREDOID" NUMBER, 
	"MIN_FILE_SIZE" NUMBER, 
	"STEADY_STATE_DURATION" INTERVAL DAY (3) TO SECOND (0), 
	"COMMENTS" VARCHAR2(4000 BYTE), 
	"LAST_MODIFIED_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"FLAGS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
