--------------------------------------------------------
--  DDL for Table SCHEDULER$_SCHEDULE
--------------------------------------------------------

  CREATE TABLE "SYS"."SCHEDULER$_SCHEDULE" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"RECURRENCE_EXPR" VARCHAR2(4000 BYTE), 
	"QUEUE_OWNER" VARCHAR2(128 BYTE), 
	"QUEUE_NAME" VARCHAR2(128 BYTE), 
	"QUEUE_AGENT" VARCHAR2(523 BYTE), 
	"REFERENCE_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"END_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"COMMENTS" VARCHAR2(4000 BYTE), 
	"FLAGS" NUMBER, 
	"MAX_COUNT" NUMBER, 
	"FW_NAME" VARCHAR2(261 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
