--------------------------------------------------------
--  Constraints for Table SCHEDULER$_LIGHTWEIGHT_JOB
--------------------------------------------------------

  ALTER TABLE "SYS"."SCHEDULER$_LIGHTWEIGHT_JOB" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_LIGHTWEIGHT_JOB" ADD CONSTRAINT "SCHEDULER$_LWJOB_PK" PRIMARY KEY ("OBJ#")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
