--------------------------------------------------------
--  DDL for Table SCHEDULER$_GLOBAL_ATTRIBUTE
--------------------------------------------------------

  CREATE TABLE "SYS"."SCHEDULER$_GLOBAL_ATTRIBUTE" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"VALUE" VARCHAR2(256 BYTE), 
	"FLAGS" NUMBER, 
	"MODIFIED_INST" NUMBER, 
	"ADDITIONAL_INFO" VARCHAR2(128 BYTE), 
	"ATTR_TSTAMP" TIMESTAMP (6) WITH TIME ZONE, 
	"ATTR_INTV" INTERVAL DAY (3) TO SECOND (0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
