--------------------------------------------------------
--  DDL for Table SCHEDULER$_FILEWATCHER_RESEND
--------------------------------------------------------

  CREATE TABLE "SYS"."SCHEDULER$_FILEWATCHER_RESEND" SHARING=METADATA 
   (	"DESTINATION" VARCHAR2(261 BYTE), 
	"FW_OWNER" VARCHAR2(128 BYTE), 
	"FW_NAME" VARCHAR2(128 BYTE), 
	"INS_TSTAMP" TIMESTAMP (6) WITH TIME ZONE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
