--------------------------------------------------------
--  Constraints for Table SCHEDULER$_FILE_WATCHER
--------------------------------------------------------

  ALTER TABLE "SYS"."SCHEDULER$_FILE_WATCHER" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_FILE_WATCHER" MODIFY ("DIRECTORY_PATH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_FILE_WATCHER" MODIFY ("FILE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_FILE_WATCHER" MODIFY ("MIN_FILE_SIZE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_FILE_WATCHER" ADD CONSTRAINT "SCHEDULER$_FW_PK" PRIMARY KEY ("OBJ#")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
