--------------------------------------------------------
--  Constraints for Table SCHEDULER$_DBMSJOB_MAP
--------------------------------------------------------

  ALTER TABLE "SYS"."SCHEDULER$_DBMSJOB_MAP" MODIFY ("DBMS_JOB_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_DBMSJOB_MAP" MODIFY ("JOB_OWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_DBMSJOB_MAP" MODIFY ("JOB_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_DBMSJOB_MAP" ADD CONSTRAINT "SCHEDULER$_DBMSJOB_MAP_PK" PRIMARY KEY ("DBMS_JOB_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
