--------------------------------------------------------
--  Constraints for Table SCHEDULER$_CREDENTIAL
--------------------------------------------------------

  ALTER TABLE "SYS"."SCHEDULER$_CREDENTIAL" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_CREDENTIAL" ADD CONSTRAINT "SCHEDULER$_CREDENTIAL_PK" PRIMARY KEY ("OBJ#")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
