--------------------------------------------------------
--  DDL for Table SCHEDULER$_PROGRAM
--------------------------------------------------------

  CREATE TABLE "SYS"."SCHEDULER$_PROGRAM" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"ACTION" VARCHAR2(4000 BYTE), 
	"NUMBER_OF_ARGS" NUMBER, 
	"COMMENTS" VARCHAR2(4000 BYTE), 
	"FLAGS" NUMBER, 
	"SCHEDULE_LIMIT" INTERVAL DAY (3) TO SECOND (0), 
	"PRIORITY" NUMBER, 
	"JOB_WEIGHT" NUMBER, 
	"MAX_RUNS" NUMBER, 
	"MAX_FAILURES" NUMBER, 
	"MAX_RUN_DURATION" INTERVAL DAY (3) TO SECOND (0), 
	"NLS_ENV" VARCHAR2(4000 BYTE), 
	"ENV" RAW(32), 
	"RUN_COUNT" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
