--------------------------------------------------------
--  DDL for Table SCHEDULER$_WINDOW
--------------------------------------------------------

  CREATE TABLE "SYS"."SCHEDULER$_WINDOW" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"RES_PLAN" VARCHAR2(128 BYTE), 
	"NEXT_START_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"MANUAL_OPEN_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"DURATION" INTERVAL DAY (3) TO SECOND (0), 
	"MANUAL_DURATION" INTERVAL DAY (3) TO SECOND (0), 
	"SCHEDULE_EXPR" VARCHAR2(4000 BYTE), 
	"START_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"END_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"LAST_START_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"ACTUAL_START_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"SCALING_FACTOR" NUMBER, 
	"CREATOR" VARCHAR2(128 BYTE), 
	"UNUSED_SLAVE_POLICY" NUMBER, 
	"MIN_SLAVE_PERCENT" NUMBER, 
	"MAX_SLAVE_PERCENT" NUMBER, 
	"SCHEDULE_ID" NUMBER, 
	"FLAGS" NUMBER, 
	"MAX_CONC_JOBS" NUMBER, 
	"PRIORITY" NUMBER, 
	"COMMENTS" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
