--------------------------------------------------------
--  Constraints for Table SCHEDULER$_JOB_RUN_DETAILS
--------------------------------------------------------

  ALTER TABLE "SYS"."SCHEDULER$_JOB_RUN_DETAILS" ADD CONSTRAINT "SCHEDULER$_JOB_RUN_DETAILS_PK" PRIMARY KEY ("LOG_ID")
  USING INDEX (CREATE INDEX "SYS"."I_SCHEDULER_JOB_RUN_DETAILS" ON "SYS"."SCHEDULER$_JOB_RUN_DETAILS" ("LOG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" )  ENABLE;
