--------------------------------------------------------
--  DDL for Table SCHEDULER$_EVENT_LOG
--------------------------------------------------------

  CREATE TABLE "SYS"."SCHEDULER$_EVENT_LOG" SHARING=METADATA 
   (	"LOG_ID" NUMBER, 
	"LOG_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"TYPE#" NUMBER, 
	"NAME" VARCHAR2(261 BYTE), 
	"OWNER" VARCHAR2(128 BYTE), 
	"CLASS_ID" NUMBER, 
	"OPERATION" VARCHAR2(30 BYTE), 
	"STATUS" VARCHAR2(30 BYTE), 
	"USER_NAME" VARCHAR2(128 BYTE), 
	"CLIENT_ID" VARCHAR2(64 BYTE), 
	"GUID" VARCHAR2(32 BYTE), 
	"DBID" NUMBER, 
	"FLAGS" NUMBER, 
	"CREDENTIAL" VARCHAR2(261 BYTE), 
	"DESTINATION" VARCHAR2(261 BYTE), 
	"ADDITIONAL_INFO" CLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 LOB ("ADDITIONAL_INFO") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
