--------------------------------------------------------
--  DDL for Table SCHEDULER$_JOB_ARGUMENT
--------------------------------------------------------

  CREATE TABLE "SYS"."SCHEDULER$_JOB_ARGUMENT" SHARING=METADATA 
   (	"OID" NUMBER, 
	"NAME" VARCHAR2(128 BYTE), 
	"POSITION" NUMBER, 
	"TYPE_NUMBER" NUMBER, 
	"USER_TYPE_NUM" NUMBER, 
	"VALUE" "SYS"."ANYDATA" , 
	"FLAGS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 OPAQUE TYPE ("VALUE") STORE AS BASICFILE LOB (
  ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  CACHE 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
