REM INSERTING into SYS.SCHEDULER$_DESTINATIONS
SET DEFINE OFF;
Insert into SYS.SCHEDULER$_DESTINATIONS (OBJ#,CONNECT_INFO,HOSTNAME,IP_ADDRESS,PORT,SHARED_KEY,EXPIRY_DATE,ADDITIONAL_INFO1,ADDITIONAL_INFO2,FLAGS,AGTDESTOID,COMMENTS) values (19621,null,'pseudo_host',null,null,null,null,null,null,11,null,'Place holder for synonym LOCAL dest');
Insert into SYS.SCHEDULER$_DESTINATIONS (OBJ#,CONNECT_INFO,HOSTNAME,IP_ADDRESS,PORT,SHARED_KEY,EXPIRY_DATE,ADDITIONAL_INFO1,ADDITIONAL_INFO2,FLAGS,AGTDESTOID,COMMENTS) values (19622,'pseudo_inst',null,null,null,null,null,null,null,13,19621,'Place holder for synonym LOCAL_DB dest');
