--------------------------------------------------------
--  DDL for Table SCHEDULER$_FILEWATCHER_HISTORY
--------------------------------------------------------

  CREATE TABLE "SYS"."SCHEDULER$_FILEWATCHER_HISTORY" SHARING=METADATA 
   (	"DIRECTORY_PATH" VARCHAR2(4000 BYTE), 
	"LAST_CHECK_TIME" TIMESTAMP (6) WITH TIME ZONE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
