--------------------------------------------------------
--  DDL for Table SCHEDULER$_LISTENERADDRESSES
--------------------------------------------------------

  CREATE TABLE "SYS"."SCHEDULER$_LISTENERADDRESSES" SHARING=METADATA 
   (	"ADDRESS" VARCHAR2(2000 BYTE), 
	"SERVICE" VARCHAR2(256 BYTE), 
	"INSTANCE" VARCHAR2(128 BYTE), 
	"PROTOCOL" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
