--------------------------------------------------------
--  DDL for Table SCHEDULER$_REMOTE_JOB_STATE
--------------------------------------------------------

  CREATE TABLE "SYS"."SCHEDULER$_REMOTE_JOB_STATE" SHARING=METADATA 
   (	"JOBOID" NUMBER, 
	"DESTINATION" VARCHAR2(512 BYTE), 
	"NEXT_START_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"RUN_COUNT" NUMBER, 
	"FAILURE_COUNT" NUMBER, 
	"RETRY_COUNT" NUMBER, 
	"LAST_START_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"LAST_END_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"JOB_STATUS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
