--------------------------------------------------------
--  Constraints for Table SCHEDULER$_REMOTE_DBS
--------------------------------------------------------

  ALTER TABLE "SYS"."SCHEDULER$_REMOTE_DBS" MODIFY ("DATABASE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_REMOTE_DBS" MODIFY ("REG_STATUS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_REMOTE_DBS" MODIFY ("DB_INDEX" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_REMOTE_DBS" MODIFY ("DATABASE_LINK" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_REMOTE_DBS" ADD CONSTRAINT "SCHEDULER$_RDB_PK" PRIMARY KEY ("DATABASE_NAME", "REG_STATUS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
