REM INSERTING into SYS.SCHEDULER$_JOB_ARGUMENT
SET DEFINE OFF;
Insert into SYS.SCHEDULER$_JOB_ARGUMENT (OID,NAME,POSITION,TYPE_NUMBER,USER_TYPE_NUM,VALUE,FLAGS) values (19761,null,1,null,null,'(OPAQUE)',0);
Insert into SYS.SCHEDULER$_JOB_ARGUMENT (OID,NAME,POSITION,TYPE_NUMBER,USER_TYPE_NUM,VALUE,FLAGS) values (19761,null,2,null,null,'(OPAQUE)',0);
Insert into SYS.SCHEDULER$_JOB_ARGUMENT (OID,NAME,POSITION,TYPE_NUMBER,USER_TYPE_NUM,VALUE,FLAGS) values (19761,null,3,null,null,'(OPAQUE)',0);
Insert into SYS.SCHEDULER$_JOB_ARGUMENT (OID,NAME,POSITION,TYPE_NUMBER,USER_TYPE_NUM,VALUE,FLAGS) values (19761,null,4,null,null,'(OPAQUE)',0);
