REM INSERTING into SYS.SCHEDULER$_GLOBAL_ATTRIBUTE
SET DEFINE OFF;
Insert into SYS.SCHEDULER$_GLOBAL_ATTRIBUTE (OBJ#,VALUE,FLAGS,MODIFIED_INST,ADDITIONAL_INFO,ATTR_TSTAMP,ATTR_INTV) values (19614,null,0,1,null,null,null);
Insert into SYS.SCHEDULER$_GLOBAL_ATTRIBUTE (OBJ#,VALUE,FLAGS,MODIFIED_INST,ADDITIONAL_INFO,ATTR_TSTAMP,ATTR_INTV) values (19615,'30',0,1,null,null,null);
Insert into SYS.SCHEDULER$_GLOBAL_ATTRIBUTE (OBJ#,VALUE,FLAGS,MODIFIED_INST,ADDITIONAL_INFO,ATTR_TSTAMP,ATTR_INTV) values (19616,'US/Mountain',0,1,null,null,null);
Insert into SYS.SCHEDULER$_GLOBAL_ATTRIBUTE (OBJ#,VALUE,FLAGS,MODIFIED_INST,ADDITIONAL_INFO,ATTR_TSTAMP,ATTR_INTV) values (19617,null,0,1,null,null,null);
Insert into SYS.SCHEDULER$_GLOBAL_ATTRIBUTE (OBJ#,VALUE,FLAGS,MODIFIED_INST,ADDITIONAL_INFO,ATTR_TSTAMP,ATTR_INTV) values (19618,'NONE',0,1,null,null,null);
Insert into SYS.SCHEDULER$_GLOBAL_ATTRIBUTE (OBJ#,VALUE,FLAGS,MODIFIED_INST,ADDITIONAL_INFO,ATTR_TSTAMP,ATTR_INTV) values (19619,null,0,1,null,null,null);
Insert into SYS.SCHEDULER$_GLOBAL_ATTRIBUTE (OBJ#,VALUE,FLAGS,MODIFIED_INST,ADDITIONAL_INFO,ATTR_TSTAMP,ATTR_INTV) values (19620,null,0,1,null,null,null);
Insert into SYS.SCHEDULER$_GLOBAL_ATTRIBUTE (OBJ#,VALUE,FLAGS,MODIFIED_INST,ADDITIONAL_INFO,ATTR_TSTAMP,ATTR_INTV) values (19629,null,0,1,null,null,null);
Insert into SYS.SCHEDULER$_GLOBAL_ATTRIBUTE (OBJ#,VALUE,FLAGS,MODIFIED_INST,ADDITIONAL_INFO,ATTR_TSTAMP,ATTR_INTV) values (19630,null,0,1,null,null,null);
Insert into SYS.SCHEDULER$_GLOBAL_ATTRIBUTE (OBJ#,VALUE,FLAGS,MODIFIED_INST,ADDITIONAL_INFO,ATTR_TSTAMP,ATTR_INTV) values (19631,'0',0,1,null,null,null);
Insert into SYS.SCHEDULER$_GLOBAL_ATTRIBUTE (OBJ#,VALUE,FLAGS,MODIFIED_INST,ADDITIONAL_INFO,ATTR_TSTAMP,ATTR_INTV) values (19642,null,0,1,null,null,null);
