--------------------------------------------------------
--  DDL for Table SCHEDULER$_NOTIFICATION
--------------------------------------------------------

  CREATE TABLE "SYS"."SCHEDULER$_NOTIFICATION" SHARING=METADATA 
   (	"JOB_NAME" VARCHAR2(128 BYTE), 
	"JOB_SUBNAME" VARCHAR2(128 BYTE), 
	"OWNER" VARCHAR2(128 BYTE), 
	"RECIPIENT" VARCHAR2(4000 BYTE), 
	"SENDER" VARCHAR2(4000 BYTE), 
	"SUBJECT" VARCHAR2(4000 BYTE), 
	"BODY" VARCHAR2(4000 BYTE), 
	"EVENT_FLAG" NUMBER, 
	"FILTER_CONDITION" VARCHAR2(4000 BYTE), 
	"FLAGS" NUMBER, 
	"NOTIFICATION_OWNER" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
