--------------------------------------------------------
--  DDL for Table SCHEDULER$_CLASS
--------------------------------------------------------

  CREATE TABLE "SYS"."SCHEDULER$_CLASS" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"RES_GRP_NAME" VARCHAR2(128 BYTE), 
	"DEFAULT_PRIORITY" NUMBER, 
	"AFFINITY" VARCHAR2(64 BYTE), 
	"LOG_HISTORY" NUMBER, 
	"FLAGS" NUMBER, 
	"COMMENTS" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
