--------------------------------------------------------
--  Constraints for Table SCHEDULER$_LWJOB_OBJ
--------------------------------------------------------

  ALTER TABLE "SYS"."SCHEDULER$_LWJOB_OBJ" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_LWJOB_OBJ" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_LWJOB_OBJ" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_LWJOB_OBJ" MODIFY ("PRGOID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_LWJOB_OBJ" MODIFY ("CREATION_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_LWJOB_OBJ" MODIFY ("MOD_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_LWJOB_OBJ" MODIFY ("SPEC_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_LWJOB_OBJ" ADD CONSTRAINT "SCHEDULER$_LOBJ_PK" PRIMARY KEY ("OBJ#")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYS"."SCHEDULER$_LWJOB_OBJ" ADD CONSTRAINT "SCHEDULER$_LOBJ_UK" UNIQUE ("USERID", "NAME", "SUBNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
