--------------------------------------------------------
--  Constraints for Table SCHEDULER$_EVENT_LOG
--------------------------------------------------------

  ALTER TABLE "SYS"."SCHEDULER$_EVENT_LOG" MODIFY ("LOG_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_EVENT_LOG" ADD CONSTRAINT "SCHEDULER$_INSTANCE_PK" UNIQUE ("LOG_ID", "DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE;
