--------------------------------------------------------
--  DDL for Table SCHEDULER$_JOB_OUT_ARGS
--------------------------------------------------------

  CREATE TABLE "SYS"."SCHEDULER$_JOB_OUT_ARGS" SHARING=METADATA 
   (	"LOG_ID" NUMBER, 
	"LOG_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"ARGUMENT_POSITION" NUMBER, 
	"ARGUMENT_NAME" VARCHAR2(128 BYTE), 
	"ARGUMENT_VALUE" "SYS"."ANYDATA" , 
	"ARGUMENT_TYPE_NAME" VARCHAR2(128 BYTE), 
	"ARGUMENT_TYPE_OWNER" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" 
 OPAQUE TYPE ("ARGUMENT_VALUE") STORE AS SECUREFILE LOB (
  ENABLE STORAGE IN ROW CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES ) ;
