--------------------------------------------------------
--  DDL for Index SCHEDULER$_WINGRP_MEMBER_UQ
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."SCHEDULER$_WINGRP_MEMBER_UQ" ON "SYS"."SCHEDULER$_WINGRP_MEMBER" ("OID", "MEMBER_OID", "MEMBER_OID2") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
