--------------------------------------------------------
--  Constraints for Table SCHEDULER$_JOB_ARGUMENT
--------------------------------------------------------

  ALTER TABLE "SYS"."SCHEDULER$_JOB_ARGUMENT" MODIFY ("OID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_JOB_ARGUMENT" MODIFY ("POSITION" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_JOB_ARGUMENT" ADD CONSTRAINT "SCHEDULER$_JOB_ARG_PK" PRIMARY KEY ("OID", "POSITION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
