--------------------------------------------------------
--  DDL for Sequence SCHEDULER$_JOBSUFFIX_S
--------------------------------------------------------

   CREATE SEQUENCE  "SYS"."SCHEDULER$_JOBSUFFIX_S"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 481 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "SYS"."SCHEDULER$_JOBSUFFIX_S" TO PUBLIC WITH GRANT OPTION;
