--------------------------------------------------------
--  Constraints for Table SCHEDULER$_WINDOW_GROUP
--------------------------------------------------------

  ALTER TABLE "SYS"."SCHEDULER$_WINDOW_GROUP" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_WINDOW_GROUP" ADD CONSTRAINT "SCHEDULER$_WINDOW_GROUP_PK" PRIMARY KEY ("OBJ#")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
