--------------------------------------------------------
--  Constraints for Table SCHEDULER$_RJOB_SRC_DB_INFO
--------------------------------------------------------

  ALTER TABLE "SYS"."SCHEDULER$_RJOB_SRC_DB_INFO" MODIFY ("JOBOID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_RJOB_SRC_DB_INFO" MODIFY ("SOURCE_DB" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_RJOB_SRC_DB_INFO" MODIFY ("SOURCE_SCHEMA" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_RJOB_SRC_DB_INFO" ADD CONSTRAINT "SCHEDULER$_RDBI_PK" PRIMARY KEY ("JOBOID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
