REM INSERTING into SYS.SCHEDULER$_PROGRAM_ARGUMENT
SET DEFINE OFF;
Insert into SYS.SCHEDULER$_PROGRAM_ARGUMENT (OID,NAME,POSITION,TYPE_NUMBER,USER_TYPE_NUM,VALUE,FLAGS) values (19633,'PARALLEL',1,1,null,'(OPAQUE)',0);
Insert into SYS.SCHEDULER$_PROGRAM_ARGUMENT (OID,NAME,POSITION,TYPE_NUMBER,USER_TYPE_NUM,VALUE,FLAGS) values (19633,'OPTIONS',2,1,null,'(OPAQUE)',0);
Insert into SYS.SCHEDULER$_PROGRAM_ARGUMENT (OID,NAME,POSITION,TYPE_NUMBER,USER_TYPE_NUM,VALUE,FLAGS) values (20090,'P_CON_ID',1,0,null,null,2048);
Insert into SYS.SCHEDULER$_PROGRAM_ARGUMENT (OID,NAME,POSITION,TYPE_NUMBER,USER_TYPE_NUM,VALUE,FLAGS) values (20345,null,1,0,null,null,4);
Insert into SYS.SCHEDULER$_PROGRAM_ARGUMENT (OID,NAME,POSITION,TYPE_NUMBER,USER_TYPE_NUM,VALUE,FLAGS) values (20345,null,2,0,null,null,2);
Insert into SYS.SCHEDULER$_PROGRAM_ARGUMENT (OID,NAME,POSITION,TYPE_NUMBER,USER_TYPE_NUM,VALUE,FLAGS) values (20345,'SOURCE_QUEUE',3,1,null,null,0);
Insert into SYS.SCHEDULER$_PROGRAM_ARGUMENT (OID,NAME,POSITION,TYPE_NUMBER,USER_TYPE_NUM,VALUE,FLAGS) values (20345,'DESTINATION',4,1,null,null,0);
Insert into SYS.SCHEDULER$_PROGRAM_ARGUMENT (OID,NAME,POSITION,TYPE_NUMBER,USER_TYPE_NUM,VALUE,FLAGS) values (20345,'DURATION',5,2,null,null,0);
Insert into SYS.SCHEDULER$_PROGRAM_ARGUMENT (OID,NAME,POSITION,TYPE_NUMBER,USER_TYPE_NUM,VALUE,FLAGS) values (20345,'LATENCY',6,2,null,null,0);
Insert into SYS.SCHEDULER$_PROGRAM_ARGUMENT (OID,NAME,POSITION,TYPE_NUMBER,USER_TYPE_NUM,VALUE,FLAGS) values (20345,'HTTP_BATCH_SIZE',7,2,null,null,0);
Insert into SYS.SCHEDULER$_PROGRAM_ARGUMENT (OID,NAME,POSITION,TYPE_NUMBER,USER_TYPE_NUM,VALUE,FLAGS) values (20345,'IDLE_TIMEOUT',8,2,null,'(OPAQUE)',0);
Insert into SYS.SCHEDULER$_PROGRAM_ARGUMENT (OID,NAME,POSITION,TYPE_NUMBER,USER_TYPE_NUM,VALUE,FLAGS) values (20345,'DEQUEUE_TIMEOUT',9,2,null,'(OPAQUE)',0);
Insert into SYS.SCHEDULER$_PROGRAM_ARGUMENT (OID,NAME,POSITION,TYPE_NUMBER,USER_TYPE_NUM,VALUE,FLAGS) values (20345,'TRACE_LEVEL',10,2,null,'(OPAQUE)',0);
