--------------------------------------------------------
--  DDL for Table SCHEDULER$_DESTINATIONS
--------------------------------------------------------

  CREATE TABLE "SYS"."SCHEDULER$_DESTINATIONS" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"CONNECT_INFO" VARCHAR2(4000 BYTE), 
	"HOSTNAME" VARCHAR2(256 BYTE), 
	"IP_ADDRESS" VARCHAR2(64 BYTE), 
	"PORT" NUMBER, 
	"SHARED_KEY" RAW(64), 
	"EXPIRY_DATE" TIMESTAMP (6), 
	"ADDITIONAL_INFO1" NUMBER, 
	"ADDITIONAL_INFO2" VARCHAR2(4000 BYTE), 
	"FLAGS" NUMBER, 
	"AGTDESTOID" NUMBER, 
	"COMMENTS" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
