--------------------------------------------------------
--  DDL for Table SCHEDULER$_JOB_RUN_DETAILS
--------------------------------------------------------

  CREATE TABLE "SYS"."SCHEDULER$_JOB_RUN_DETAILS" SHARING=METADATA 
   (	"LOG_ID" NUMBER, 
	"LOG_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"REQ_START_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"START_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"RUN_DURATION" INTERVAL DAY (3) TO SECOND (0), 
	"INSTANCE_ID" NUMBER, 
	"SESSION_ID" VARCHAR2(128 BYTE), 
	"SLAVE_PID" VARCHAR2(30 BYTE), 
	"CPU_USED" INTERVAL DAY (3) TO SECOND (2), 
	"ERROR#" NUMBER, 
	"ADDITIONAL_INFO" VARCHAR2(4000 BYTE), 
	"CREDENTIAL" VARCHAR2(261 BYTE), 
	"DESTINATION" VARCHAR2(261 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
