--------------------------------------------------------
--  Constraints for Table SCHEDULER$_SRCQ_MAP
--------------------------------------------------------

  ALTER TABLE "SYS"."SCHEDULER$_SRCQ_MAP" MODIFY ("OID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_SRCQ_MAP" MODIFY ("RULE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_SRCQ_MAP" MODIFY ("JOBOID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_SRCQ_MAP" ADD CONSTRAINT "SCHEDULER$_SRCQ_MAP_PK" PRIMARY KEY ("OID", "RULE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
