--------------------------------------------------------
--  Constraints for Table SCHEDULER$_EVTQ_SUB
--------------------------------------------------------

  ALTER TABLE "SYS"."SCHEDULER$_EVTQ_SUB" MODIFY ("AGT_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_EVTQ_SUB" MODIFY ("UNAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_EVTQ_SUB" ADD CONSTRAINT "SCHEDULER$_EVTQ_SUB_PK" PRIMARY KEY ("AGT_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
