--------------------------------------------------------
--  DDL for Table SCHEDULER$_STEP
--------------------------------------------------------

  CREATE TABLE "SYS"."SCHEDULER$_STEP" SHARING=METADATA 
   (	"OID" NUMBER, 
	"VAR_NAME" VARCHAR2(128 BYTE), 
	"OBJECT_NAME" VARCHAR2(392 BYTE), 
	"TIMEOUT" INTERVAL DAY (3) TO SECOND (0), 
	"QUEUE_OWNER" VARCHAR2(128 BYTE), 
	"QUEUE_NAME" VARCHAR2(128 BYTE), 
	"QUEUE_AGENT" VARCHAR2(523 BYTE), 
	"CONDITION" VARCHAR2(4000 BYTE), 
	"CREDENTIAL_OWNER" VARCHAR2(128 BYTE), 
	"CREDENTIAL_NAME" VARCHAR2(128 BYTE), 
	"DESTINATION" VARCHAR2(261 BYTE), 
	"FLAGS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
