--------------------------------------------------------
--  DDL for Table SCHEDULER$_RESOURCES
--------------------------------------------------------

  CREATE TABLE "SYS"."SCHEDULER$_RESOURCES" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"RESOURCE_COUNT" NUMBER, 
	"QUERY_RESERVE_CALLBACK" VARCHAR2(261 BYTE), 
	"STATUS" NUMBER, 
	"FLAGS" NUMBER, 
	"COMMENTS" VARCHAR2(256 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
