--------------------------------------------------------
--  Constraints for Table SCHEDULER$_NOTIFICATION
--------------------------------------------------------

  ALTER TABLE "SYS"."SCHEDULER$_NOTIFICATION" MODIFY ("JOB_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_NOTIFICATION" MODIFY ("OWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_NOTIFICATION" MODIFY ("RECIPIENT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_NOTIFICATION" MODIFY ("EVENT_FLAG" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_NOTIFICATION" MODIFY ("FLAGS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_NOTIFICATION" MODIFY ("NOTIFICATION_OWNER" NOT NULL ENABLE);
