REM INSERTING into SYS.SCHEDULER$_CLASS
SET DEFINE OFF;
Insert into SYS.SCHEDULER$_CLASS (OBJ#,RES_GRP_NAME,DEFAULT_PRIORITY,AFFINITY,LOG_HISTORY,FLAGS,COMMENTS) values (19610,null,null,null,null,68,'This is the default job class.');
Insert into SYS.SCHEDULER$_CLASS (OBJ#,RES_GRP_NAME,DEFAULT_PRIORITY,AFFINITY,LOG_HISTORY,FLAGS,COMMENTS) values (19611,null,null,null,null,132,'This is the default job class if you want minimal logging.');
Insert into SYS.SCHEDULER$_CLASS (OBJ#,RES_GRP_NAME,DEFAULT_PRIORITY,AFFINITY,LOG_HISTORY,FLAGS,COMMENTS) values (19612,null,null,null,null,132,'This is the default job class for in-memory jobs.');
Insert into SYS.SCHEDULER$_CLASS (OBJ#,RES_GRP_NAME,DEFAULT_PRIORITY,AFFINITY,LOG_HISTORY,FLAGS,COMMENTS) values (19613,null,null,null,null,36,'This is the job class for jobs created through DBMS_JOB.');
Insert into SYS.SCHEDULER$_CLASS (OBJ#,RES_GRP_NAME,DEFAULT_PRIORITY,AFFINITY,LOG_HISTORY,FLAGS,COMMENTS) values (19742,'ORA$AUTOTASK',null,null,1000000,260,'auto optimizer stats collection');
Insert into SYS.SCHEDULER$_CLASS (OBJ#,RES_GRP_NAME,DEFAULT_PRIORITY,AFFINITY,LOG_HISTORY,FLAGS,COMMENTS) values (19743,'ORA$AUTOTASK',null,null,1000000,260,'auto optimizer stats collection');
Insert into SYS.SCHEDULER$_CLASS (OBJ#,RES_GRP_NAME,DEFAULT_PRIORITY,AFFINITY,LOG_HISTORY,FLAGS,COMMENTS) values (19744,'ORA$AUTOTASK',null,null,1000000,260,'auto optimizer stats collection');
Insert into SYS.SCHEDULER$_CLASS (OBJ#,RES_GRP_NAME,DEFAULT_PRIORITY,AFFINITY,LOG_HISTORY,FLAGS,COMMENTS) values (19746,'ORA$AUTOTASK',null,null,1000000,260,'auto space advisor');
Insert into SYS.SCHEDULER$_CLASS (OBJ#,RES_GRP_NAME,DEFAULT_PRIORITY,AFFINITY,LOG_HISTORY,FLAGS,COMMENTS) values (19747,'ORA$AUTOTASK',null,null,1000000,260,'auto space advisor');
Insert into SYS.SCHEDULER$_CLASS (OBJ#,RES_GRP_NAME,DEFAULT_PRIORITY,AFFINITY,LOG_HISTORY,FLAGS,COMMENTS) values (19748,'ORA$AUTOTASK',null,null,1000000,260,'auto space advisor');
Insert into SYS.SCHEDULER$_CLASS (OBJ#,RES_GRP_NAME,DEFAULT_PRIORITY,AFFINITY,LOG_HISTORY,FLAGS,COMMENTS) values (19750,'ORA$AUTOTASK',null,null,1000000,260,'sql tuning advisor');
Insert into SYS.SCHEDULER$_CLASS (OBJ#,RES_GRP_NAME,DEFAULT_PRIORITY,AFFINITY,LOG_HISTORY,FLAGS,COMMENTS) values (19751,'ORA$AUTOTASK',null,null,1000000,260,'sql tuning advisor');
Insert into SYS.SCHEDULER$_CLASS (OBJ#,RES_GRP_NAME,DEFAULT_PRIORITY,AFFINITY,LOG_HISTORY,FLAGS,COMMENTS) values (19752,'ORA$AUTOTASK',null,null,1000000,260,'sql tuning advisor');
Insert into SYS.SCHEDULER$_CLASS (OBJ#,RES_GRP_NAME,DEFAULT_PRIORITY,AFFINITY,LOG_HISTORY,FLAGS,COMMENTS) values (20346,null,null,null,null,64,'Default job class for AQ propagation jobs');
Insert into SYS.SCHEDULER$_CLASS (OBJ#,RES_GRP_NAME,DEFAULT_PRIORITY,AFFINITY,LOG_HISTORY,FLAGS,COMMENTS) values (22155,null,null,null,null,128,null);
