--------------------------------------------------------
--  Constraints for Table SCHEDULER$_STEP_STATE
--------------------------------------------------------

  ALTER TABLE "SYS"."SCHEDULER$_STEP_STATE" MODIFY ("JOB_OID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_STEP_STATE" MODIFY ("STEP_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SCHEDULER$_STEP_STATE" ADD CONSTRAINT "SCHEDULER$_STEP_STATE_PK" PRIMARY KEY ("JOB_OID", "STEP_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
