--------------------------------------------------------
--  DDL for Table SCHEDULER$_CREDENTIAL
--------------------------------------------------------

  CREATE TABLE "SYS"."SCHEDULER$_CREDENTIAL" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"USERNAME" VARCHAR2(128 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE), 
	"DOMAIN" VARCHAR2(30 BYTE), 
	"COMMENTS" VARCHAR2(4000 BYTE), 
	"FLAGS" NUMBER, 
	"KEY" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
