--------------------------------------------------------
--  Constraints for Table SEG$
--------------------------------------------------------

  ALTER TABLE "SYS"."SEG$" MODIFY ("FILE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SEG$" MODIFY ("BLOCK#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SEG$" MODIFY ("TYPE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SEG$" MODIFY ("TS#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SEG$" MODIFY ("BLOCKS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SEG$" MODIFY ("EXTENTS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SEG$" MODIFY ("INIEXTS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SEG$" MODIFY ("MINEXTS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SEG$" MODIFY ("MAXEXTS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SEG$" MODIFY ("EXTSIZE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SEG$" MODIFY ("EXTPCT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SEG$" MODIFY ("USER#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SEG$" MODIFY ("BITMAPRANGES" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SEG$" MODIFY ("CACHEHINT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SEG$" MODIFY ("SCANHINT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SEG$" MODIFY ("HWMINCR" NOT NULL ENABLE);
