--------------------------------------------------------
--  Constraints for Table SEQ$
--------------------------------------------------------

  ALTER TABLE "SYS"."SEQ$" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SEQ$" MODIFY ("INCREMENT$" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SEQ$" MODIFY ("CYCLE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SEQ$" MODIFY ("ORDER$" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SEQ$" MODIFY ("CACHE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SEQ$" MODIFY ("HIGHWATER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SEQ$" MODIFY ("AUDIT$" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SEQ$" ADD SUPPLEMENTAL LOG GROUP "SEQ$_LOG_GRP" ("OBJ#") ALWAYS;
