--------------------------------------------------------
--  DDL for Table SEQ$
--------------------------------------------------------

  CREATE TABLE "SYS"."SEQ$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"INCREMENT$" NUMBER, 
	"MINVALUE" NUMBER, 
	"MAXVALUE" NUMBER, 
	"CYCLE#" NUMBER, 
	"ORDER$" NUMBER, 
	"CACHE" NUMBER, 
	"HIGHWATER" NUMBER, 
	"AUDIT$" VARCHAR2(38 BYTE), 
	"FLAGS" NUMBER, 
	"PARTCOUNT" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
