--------------------------------------------------------
--  DDL for Table SERVICE$
--------------------------------------------------------

  CREATE TABLE "SYS"."SERVICE$" SHARING=METADATA 
   (	"SERVICE_ID" NUMBER, 
	"NAME" VARCHAR2(64 BYTE), 
	"NAME_HASH" NUMBER, 
	"NETWORK_NAME" VARCHAR2(512 BYTE), 
	"CREATION_DATE" DATE, 
	"CREATION_DATE_HASH" NUMBER, 
	"DELETION_DATE" DATE, 
	"FAILOVER_METHOD" VARCHAR2(64 BYTE), 
	"FAILOVER_TYPE" VARCHAR2(64 BYTE), 
	"FAILOVER_RETRIES" NUMBER(10,0), 
	"FAILOVER_DELAY" NUMBER(10,0), 
	"MIN_CARDINALITY" NUMBER, 
	"MAX_CARDINALITY" NUMBER, 
	"GOAL" NUMBER, 
	"FLAGS" NUMBER, 
	"EDITION" VARCHAR2(128 BYTE), 
	"PDB" VARCHAR2(128 BYTE), 
	"RETENTION_TIMEOUT" NUMBER, 
	"REPLAY_INITIATION_TIMEOUT" NUMBER, 
	"SESSION_STATE_CONSISTENCY" VARCHAR2(128 BYTE), 
	"SQL_TRANSLATION_PROFILE" VARCHAR2(261 BYTE), 
	"MAX_LAG_TIME" VARCHAR2(128 BYTE), 
	"GSM_FLAGS" NUMBER, 
	"PQ_SVC" VARCHAR2(64 BYTE), 
	"STOP_OPTION" NUMBER, 
	"FAILOVER_RESTORE" NUMBER, 
	"DRAIN_TIMEOUT" NUMBER, 
	"TABLE_FAMILY_ID" NUMBER, 
	"PLACEMENT_POLICY" NUMBER, 
	"RESET_STATE" NUMBER, 
	"VCSPARE1" VARCHAR2(1024 BYTE), 
	"NSPARE1" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  GRANT SELECT ON "SYS"."SERVICE$" TO "DBSFWUSER";
