--------------------------------------------------------
--  DDL for Table SNAP_REFTIME$
--------------------------------------------------------

  CREATE TABLE "SYS"."SNAP_REFTIME$" SHARING=METADATA 
   (	"SOWNER" VARCHAR2(128 BYTE), 
	"VNAME" VARCHAR2(128 BYTE), 
	"TABLENUM" NUMBER(*,0), 
	"SNAPTIME" DATE, 
	"MOWNER" VARCHAR2(128 BYTE), 
	"MASTER" VARCHAR2(128 BYTE), 
	"MASFLAG" NUMBER, 
	"MASOBJ#" NUMBER, 
	"LOADERTIME" DATE, 
	"REFSCN" NUMBER, 
	"INSTSITE" NUMBER(*,0) DEFAULT 0, 
	"LASTSUCCESS" DATE, 
	"FCMASKVEC" RAW(255), 
	"EJMASKVEC" RAW(255), 
	"SUB_HANDLE" NUMBER, 
	"CHANGE_VIEW" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
