--------------------------------------------------------
--  DDL for Table SNAP$
--------------------------------------------------------

  CREATE TABLE "SYS"."SNAP$" SHARING=METADATA 
   (	"SOWNER" VARCHAR2(128 BYTE), 
	"VNAME" VARCHAR2(128 BYTE), 
	"TNAME" VARCHAR2(128 BYTE), 
	"MVIEW" VARCHAR2(128 BYTE), 
	"MOWNER" VARCHAR2(128 BYTE), 
	"MASTER" VARCHAR2(128 BYTE), 
	"MLINK" VARCHAR2(128 BYTE), 
	"CAN_USE_LOG" VARCHAR2(1 BYTE), 
	"SNAPSHOT" DATE, 
	"SNAPID" NUMBER(*,0), 
	"SSCN" NUMBER, 
	"SNAPTIME" DATE, 
	"TSCN" NUMBER, 
	"ERROR#" NUMBER, 
	"AUTO_FAST" VARCHAR2(1 BYTE), 
	"AUTO_FUN" VARCHAR2(200 BYTE), 
	"AUTO_DATE" DATE, 
	"REFGROUP" NUMBER, 
	"USTRG" VARCHAR2(128 BYTE), 
	"USLOG" VARCHAR2(128 BYTE), 
	"STATUS" NUMBER(*,0), 
	"MASTER_VERSION" NUMBER(*,0), 
	"TABLES" NUMBER(*,0), 
	"FIELD1" NUMBER, 
	"FIELD2" VARCHAR2(128 BYTE), 
	"FLAG" NUMBER, 
	"FLAG2" NUMBER, 
	"QUERY_TXT" LONG, 
	"LOBMASKVEC" RAW(255), 
	"MTIME" DATE, 
	"MAS_ROLL_SEG" VARCHAR2(128 BYTE), 
	"RSCN" NUMBER, 
	"REFHNT" NUMBER, 
	"QUERY_LEN" NUMBER(*,0), 
	"INSTSITE" NUMBER(*,0) DEFAULT 0, 
	"FLAVOR_ID" NUMBER, 
	"OBJFLAG" NUMBER, 
	"SNA_TYPE_OID" RAW(16), 
	"SNA_TYPE_HASHCODE" RAW(17), 
	"SNA_TYPE_OWNER" VARCHAR2(128 BYTE), 
	"SNA_TYPE_NAME" VARCHAR2(128 BYTE), 
	"MAS_TYPE_OID" RAW(16), 
	"MAS_TYPE_HASHCODE" RAW(17), 
	"MAS_TYPE_OWNER" VARCHAR2(128 BYTE), 
	"MAS_TYPE_NAME" VARCHAR2(128 BYTE), 
	"PARENT_SOWNER" VARCHAR2(128 BYTE), 
	"PARENT_VNAME" VARCHAR2(128 BYTE), 
	"REL_QUERY" CLOB, 
	"ALIAS_TXT" CLOB, 
	"SYN_COUNT" NUMBER(*,0), 
	"FLAG3" NUMBER, 
	"EVAL_EDITION" VARCHAR2(128 BYTE), 
	"FLAG4" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("REL_QUERY") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ALIAS_TXT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  GRANT SELECT ON "SYS"."SNAP$" TO "CTXSYS";
