REM INSERTING into SYS.SNAP$
SET DEFINE OFF;
Insert into SYS.SNAP$ (SOWNER,VNAME,TNAME,MVIEW,MOWNER,MASTER,MLINK,CAN_USE_LOG,SNAPSHOT,SNAPID,SSCN,SNAPTIME,TSCN,ERROR#,AUTO_FAST,AUTO_FUN,AUTO_DATE,REFGROUP,USTRG,USLOG,STATUS,MASTER_VERSION,TABLES,FIELD1,FIELD2,FLAG,FLAG2,QUERY_TXT,LOBMASKVEC,MTIME,MAS_ROLL_SEG,RSCN,REFHNT,QUERY_LEN,INSTSITE,FLAVOR_ID,OBJFLAG,SNA_TYPE_OID,SNA_TYPE_HASHCODE,SNA_TYPE_OWNER,SNA_TYPE_NAME,MAS_TYPE_OID,MAS_TYPE_HASHCODE,MAS_TYPE_OWNER,MAS_TYPE_NAME,PARENT_SOWNER,PARENT_VNAME,SYN_COUNT,FLAG3,EVAL_EDITION,FLAG4) values ('SYSTEM','MD_REGEX_MVIEW','MD_REGEX_MVIEW',null,'SYSTEM','MD_CODE_REGEX',null,'X',to_date('01-JAN-50','DD-MON-RR'),1,null,null,null,0,'?',null,null,null,null,null,8194,10,6,0,null,2105409,1075838976,'SELECT  pr.PROJECT_NAME, pr.ID "PROJECT_ID", c.ID "CONNECTION_ID", c.NAME "CONNECTION_NAME", mc.ID "CATALOG_ID",
        mc.CATALOG_NAME,s.id "SCHEMA_ID",s.NAME "SCHEMA_NAME", p.ID "PROGRAM_ID", p.name "PROGRAM_NAME",
        rg.DESCRIPTION "ITEM", regexp_count(p.native_sql,rg.REGEX,1,''ix'') "VALUE"
FROM MD_STORED_PROGRAMS p,
  md_projects pr,
  md_connections c,
  md_schemas s,
  MD_CATALOGS mc,
  MD_CODE_REGEX rg
WHERE c.TYPE          IS NULL --Shows captured
AND mc.CONNECTION_ID_FK=c.id
AND mc.id              =s.CATALOG_ID_FK
AND pr.PROJECT_NAME LIKE ''SS%''
and pr.id=c.PROJECT_ID_FK
and p.SCHEMA_ID_FK=s.ID
and regexp_count(p.native_sql,rg.REGEX,1,''ix'')>0',null,to_date('25-NOV-24','DD-MON-RR'),null,1988102,0,663,0,null,0,null,null,null,null,null,null,null,null,null,null,0,4194304,null,0);
Insert into SYS.SNAP$ (SOWNER,VNAME,TNAME,MVIEW,MOWNER,MASTER,MLINK,CAN_USE_LOG,SNAPSHOT,SNAPID,SSCN,SNAPTIME,TSCN,ERROR#,AUTO_FAST,AUTO_FUN,AUTO_DATE,REFGROUP,USTRG,USLOG,STATUS,MASTER_VERSION,TABLES,FIELD1,FIELD2,FLAG,FLAG2,QUERY_TXT,LOBMASKVEC,MTIME,MAS_ROLL_SEG,RSCN,REFHNT,QUERY_LEN,INSTSITE,FLAVOR_ID,OBJFLAG,SNA_TYPE_OID,SNA_TYPE_HASHCODE,SNA_TYPE_OWNER,SNA_TYPE_NAME,MAS_TYPE_OID,MAS_TYPE_HASHCODE,MAS_TYPE_OWNER,MAS_TYPE_NAME,PARENT_SOWNER,PARENT_VNAME,SYN_COUNT,FLAG3,EVAL_EDITION,FLAG4) values ('SYSTEM','MD_REGEX_SCHEMA_MVIEW','MD_REGEX_SCHEMA_MVIEW',null,'SYSTEM','MD_REGEX_MVIEW',null,null,to_date('25-NOV-24','DD-MON-RR'),2,null,null,null,0,'?',null,null,null,null,null,2,10,1,0,null,2097472,2097152,'SELECT  PROJECT_ID, CONNECTION_ID, CONNECTION_NAME,CATALOG_ID,
        CATALOG_NAME,SCHEMA_ID,SCHEMA_NAME, ITEM, SUM(VALUE) "VALUE" from MD_REGEX_MVIEW
        group by PROJECT_NAME, PROJECT_ID, CONNECTION_ID, CONNECTION_NAME,CATALOG_ID,
        CATALOG_NAME,SCHEMA_ID,SCHEMA_NAME, ITEM',null,to_date('25-NOV-24','DD-MON-RR'),null,1988310,0,286,0,null,0,null,null,null,null,null,null,null,null,null,null,0,4194304,null,0);
Insert into SYS.SNAP$ (SOWNER,VNAME,TNAME,MVIEW,MOWNER,MASTER,MLINK,CAN_USE_LOG,SNAPSHOT,SNAPID,SSCN,SNAPTIME,TSCN,ERROR#,AUTO_FAST,AUTO_FUN,AUTO_DATE,REFGROUP,USTRG,USLOG,STATUS,MASTER_VERSION,TABLES,FIELD1,FIELD2,FLAG,FLAG2,QUERY_TXT,LOBMASKVEC,MTIME,MAS_ROLL_SEG,RSCN,REFHNT,QUERY_LEN,INSTSITE,FLAVOR_ID,OBJFLAG,SNA_TYPE_OID,SNA_TYPE_HASHCODE,SNA_TYPE_OWNER,SNA_TYPE_NAME,MAS_TYPE_OID,MAS_TYPE_HASHCODE,MAS_TYPE_OWNER,MAS_TYPE_NAME,PARENT_SOWNER,PARENT_VNAME,SYN_COUNT,FLAG3,EVAL_EDITION,FLAG4) values ('SYSTEM','MD_REGEX_CATALOG_MVIEW','MD_REGEX_CATALOG_MVIEW',null,'SYSTEM','MD_REGEX_SCHEMA_MVIEW',null,null,to_date('25-NOV-24','DD-MON-RR'),3,null,null,null,0,'?',null,null,null,null,null,2,10,1,0,null,69206336,2097152,'SELECT  PROJECT_ID, CONNECTION_ID, CONNECTION_NAME,CATALOG_ID,
        CATALOG_NAME, ITEM, SUM(VALUE) "VALUE" from MD_REGEX_SCHEMA_MVIEW
        group by  PROJECT_ID, CONNECTION_ID, CONNECTION_NAME,CATALOG_ID,
        CATALOG_NAME, ITEM',null,to_date('25-NOV-24','DD-MON-RR'),null,1988349,0,236,0,null,0,null,null,null,null,null,null,null,null,null,null,0,4194304,null,0);
Insert into SYS.SNAP$ (SOWNER,VNAME,TNAME,MVIEW,MOWNER,MASTER,MLINK,CAN_USE_LOG,SNAPSHOT,SNAPID,SSCN,SNAPTIME,TSCN,ERROR#,AUTO_FAST,AUTO_FUN,AUTO_DATE,REFGROUP,USTRG,USLOG,STATUS,MASTER_VERSION,TABLES,FIELD1,FIELD2,FLAG,FLAG2,QUERY_TXT,LOBMASKVEC,MTIME,MAS_ROLL_SEG,RSCN,REFHNT,QUERY_LEN,INSTSITE,FLAVOR_ID,OBJFLAG,SNA_TYPE_OID,SNA_TYPE_HASHCODE,SNA_TYPE_OWNER,SNA_TYPE_NAME,MAS_TYPE_OID,MAS_TYPE_HASHCODE,MAS_TYPE_OWNER,MAS_TYPE_NAME,PARENT_SOWNER,PARENT_VNAME,SYN_COUNT,FLAG3,EVAL_EDITION,FLAG4) values ('SYS','MD_REGEX_MVIEW','MD_REGEX_MVIEW',null,'SYS','MD_CODE_REGEX',null,'X',to_date('01-JAN-50','DD-MON-RR'),21,null,null,null,0,'?',null,null,null,null,null,8194,10,6,0,null,2105409,1075838976,'SELECT  pr.PROJECT_NAME, pr.ID "PROJECT_ID", c.ID "CONNECTION_ID", c.NAME "CONNECTION_NAME", mc.ID "CATALOG_ID",
        mc.CATALOG_NAME,s.id "SCHEMA_ID",s.NAME "SCHEMA_NAME", p.ID "PROGRAM_ID", p.name "PROGRAM_NAME",
        rg.DESCRIPTION "ITEM", regexp_count(p.native_sql,rg.REGEX,1,''ix'') "VALUE"
FROM MD_STORED_PROGRAMS p,
  md_projects pr,
  md_connections c,
  md_schemas s,
  MD_CATALOGS mc,
  MD_CODE_REGEX rg
WHERE c.TYPE          IS NULL --Shows captured
AND mc.CONNECTION_ID_FK=c.id
AND mc.id              =s.CATALOG_ID_FK
AND pr.PROJECT_NAME LIKE ''SS%''
and pr.id=c.PROJECT_ID_FK
and p.SCHEMA_ID_FK=s.ID
and regexp_count(p.native_sql,rg.REGEX,1,''ix'')>0',null,to_date('29-NOV-24','DD-MON-RR'),null,6076358,0,663,0,null,0,null,null,null,null,null,null,null,null,null,null,0,4194304,null,0);
Insert into SYS.SNAP$ (SOWNER,VNAME,TNAME,MVIEW,MOWNER,MASTER,MLINK,CAN_USE_LOG,SNAPSHOT,SNAPID,SSCN,SNAPTIME,TSCN,ERROR#,AUTO_FAST,AUTO_FUN,AUTO_DATE,REFGROUP,USTRG,USLOG,STATUS,MASTER_VERSION,TABLES,FIELD1,FIELD2,FLAG,FLAG2,QUERY_TXT,LOBMASKVEC,MTIME,MAS_ROLL_SEG,RSCN,REFHNT,QUERY_LEN,INSTSITE,FLAVOR_ID,OBJFLAG,SNA_TYPE_OID,SNA_TYPE_HASHCODE,SNA_TYPE_OWNER,SNA_TYPE_NAME,MAS_TYPE_OID,MAS_TYPE_HASHCODE,MAS_TYPE_OWNER,MAS_TYPE_NAME,PARENT_SOWNER,PARENT_VNAME,SYN_COUNT,FLAG3,EVAL_EDITION,FLAG4) values ('SYS','MD_REGEX_SCHEMA_MVIEW','MD_REGEX_SCHEMA_MVIEW',null,'SYS','MD_REGEX_MVIEW',null,null,to_date('29-NOV-24','DD-MON-RR'),22,null,null,null,0,'?',null,null,null,null,null,2,10,1,0,null,2097472,2097152,'SELECT  PROJECT_ID, CONNECTION_ID, CONNECTION_NAME,CATALOG_ID,
        CATALOG_NAME,SCHEMA_ID,SCHEMA_NAME, ITEM, SUM(VALUE) "VALUE" from MD_REGEX_MVIEW
        group by PROJECT_NAME, PROJECT_ID, CONNECTION_ID, CONNECTION_NAME,CATALOG_ID,
        CATALOG_NAME,SCHEMA_ID,SCHEMA_NAME, ITEM',null,to_date('29-NOV-24','DD-MON-RR'),null,0,0,286,0,null,0,null,null,null,null,null,null,null,null,null,null,0,4194304,null,0);
Insert into SYS.SNAP$ (SOWNER,VNAME,TNAME,MVIEW,MOWNER,MASTER,MLINK,CAN_USE_LOG,SNAPSHOT,SNAPID,SSCN,SNAPTIME,TSCN,ERROR#,AUTO_FAST,AUTO_FUN,AUTO_DATE,REFGROUP,USTRG,USLOG,STATUS,MASTER_VERSION,TABLES,FIELD1,FIELD2,FLAG,FLAG2,QUERY_TXT,LOBMASKVEC,MTIME,MAS_ROLL_SEG,RSCN,REFHNT,QUERY_LEN,INSTSITE,FLAVOR_ID,OBJFLAG,SNA_TYPE_OID,SNA_TYPE_HASHCODE,SNA_TYPE_OWNER,SNA_TYPE_NAME,MAS_TYPE_OID,MAS_TYPE_HASHCODE,MAS_TYPE_OWNER,MAS_TYPE_NAME,PARENT_SOWNER,PARENT_VNAME,SYN_COUNT,FLAG3,EVAL_EDITION,FLAG4) values ('SYS','MD_REGEX_CATALOG_MVIEW','MD_REGEX_CATALOG_MVIEW',null,'SYS','MD_REGEX_SCHEMA_MVIEW',null,null,to_date('29-NOV-24','DD-MON-RR'),23,null,null,null,0,'?',null,null,null,null,null,2,10,1,0,null,69206336,2097152,'SELECT  PROJECT_ID, CONNECTION_ID, CONNECTION_NAME,CATALOG_ID,
        CATALOG_NAME, ITEM, SUM(VALUE) "VALUE" from MD_REGEX_SCHEMA_MVIEW
        group by  PROJECT_ID, CONNECTION_ID, CONNECTION_NAME,CATALOG_ID,
        CATALOG_NAME, ITEM',null,to_date('29-NOV-24','DD-MON-RR'),null,0,0,236,0,null,0,null,null,null,null,null,null,null,null,null,null,0,4194304,null,0);
Insert into SYS.SNAP$ (SOWNER,VNAME,TNAME,MVIEW,MOWNER,MASTER,MLINK,CAN_USE_LOG,SNAPSHOT,SNAPID,SSCN,SNAPTIME,TSCN,ERROR#,AUTO_FAST,AUTO_FUN,AUTO_DATE,REFGROUP,USTRG,USLOG,STATUS,MASTER_VERSION,TABLES,FIELD1,FIELD2,FLAG,FLAG2,QUERY_TXT,LOBMASKVEC,MTIME,MAS_ROLL_SEG,RSCN,REFHNT,QUERY_LEN,INSTSITE,FLAVOR_ID,OBJFLAG,SNA_TYPE_OID,SNA_TYPE_HASHCODE,SNA_TYPE_OWNER,SNA_TYPE_NAME,MAS_TYPE_OID,MAS_TYPE_HASHCODE,MAS_TYPE_OWNER,MAS_TYPE_NAME,PARENT_SOWNER,PARENT_VNAME,SYN_COUNT,FLAG3,EVAL_EDITION,FLAG4) values ('RBL_MISDB_PROD','MD_REGEX_MVIEW','MD_REGEX_MVIEW',null,'RBL_MISDB_PROD','MD_CODE_REGEX',null,'X',to_date('01-JAN-50','DD-MON-RR'),24,null,null,null,0,'?',null,null,null,null,null,8194,10,6,0,null,2105409,1075838976,'SELECT  pr.PROJECT_NAME, pr.ID "PROJECT_ID", c.ID "CONNECTION_ID", c.NAME "CONNECTION_NAME", mc.ID "CATALOG_ID",
        mc.CATALOG_NAME,s.id "SCHEMA_ID",s.NAME "SCHEMA_NAME", p.ID "PROGRAM_ID", p.name "PROGRAM_NAME",
        rg.DESCRIPTION "ITEM", regexp_count(p.native_sql,rg.REGEX,1,''ix'') "VALUE"
FROM MD_STORED_PROGRAMS p,
  md_projects pr,
  md_connections c,
  md_schemas s,
  MD_CATALOGS mc,
  MD_CODE_REGEX rg
WHERE c.TYPE          IS NULL --Shows captured
AND mc.CONNECTION_ID_FK=c.id
AND mc.id              =s.CATALOG_ID_FK
AND pr.PROJECT_NAME LIKE ''SS%''
and pr.id=c.PROJECT_ID_FK
and p.SCHEMA_ID_FK=s.ID
and regexp_count(p.native_sql,rg.REGEX,1,''ix'')>0',null,to_date('29-NOV-24','DD-MON-RR'),null,6127609,0,663,0,null,0,null,null,null,null,null,null,null,null,null,null,0,4194304,null,0);
Insert into SYS.SNAP$ (SOWNER,VNAME,TNAME,MVIEW,MOWNER,MASTER,MLINK,CAN_USE_LOG,SNAPSHOT,SNAPID,SSCN,SNAPTIME,TSCN,ERROR#,AUTO_FAST,AUTO_FUN,AUTO_DATE,REFGROUP,USTRG,USLOG,STATUS,MASTER_VERSION,TABLES,FIELD1,FIELD2,FLAG,FLAG2,QUERY_TXT,LOBMASKVEC,MTIME,MAS_ROLL_SEG,RSCN,REFHNT,QUERY_LEN,INSTSITE,FLAVOR_ID,OBJFLAG,SNA_TYPE_OID,SNA_TYPE_HASHCODE,SNA_TYPE_OWNER,SNA_TYPE_NAME,MAS_TYPE_OID,MAS_TYPE_HASHCODE,MAS_TYPE_OWNER,MAS_TYPE_NAME,PARENT_SOWNER,PARENT_VNAME,SYN_COUNT,FLAG3,EVAL_EDITION,FLAG4) values ('RBL_MISDB_PROD','MD_REGEX_SCHEMA_MVIEW','MD_REGEX_SCHEMA_MVIEW',null,'RBL_MISDB_PROD','MD_REGEX_MVIEW',null,null,to_date('29-NOV-24','DD-MON-RR'),25,null,null,null,0,'?',null,null,null,null,null,2,10,1,0,null,2097472,2097152,'SELECT  PROJECT_ID, CONNECTION_ID, CONNECTION_NAME,CATALOG_ID,
        CATALOG_NAME,SCHEMA_ID,SCHEMA_NAME, ITEM, SUM(VALUE) "VALUE" from MD_REGEX_MVIEW
        group by PROJECT_NAME, PROJECT_ID, CONNECTION_ID, CONNECTION_NAME,CATALOG_ID,
        CATALOG_NAME,SCHEMA_ID,SCHEMA_NAME, ITEM',null,to_date('29-NOV-24','DD-MON-RR'),null,6127671,0,286,0,null,0,null,null,null,null,null,null,null,null,null,null,0,4194304,null,0);
Insert into SYS.SNAP$ (SOWNER,VNAME,TNAME,MVIEW,MOWNER,MASTER,MLINK,CAN_USE_LOG,SNAPSHOT,SNAPID,SSCN,SNAPTIME,TSCN,ERROR#,AUTO_FAST,AUTO_FUN,AUTO_DATE,REFGROUP,USTRG,USLOG,STATUS,MASTER_VERSION,TABLES,FIELD1,FIELD2,FLAG,FLAG2,QUERY_TXT,LOBMASKVEC,MTIME,MAS_ROLL_SEG,RSCN,REFHNT,QUERY_LEN,INSTSITE,FLAVOR_ID,OBJFLAG,SNA_TYPE_OID,SNA_TYPE_HASHCODE,SNA_TYPE_OWNER,SNA_TYPE_NAME,MAS_TYPE_OID,MAS_TYPE_HASHCODE,MAS_TYPE_OWNER,MAS_TYPE_NAME,PARENT_SOWNER,PARENT_VNAME,SYN_COUNT,FLAG3,EVAL_EDITION,FLAG4) values ('RBL_MISDB_PROD','MD_REGEX_CATALOG_MVIEW','MD_REGEX_CATALOG_MVIEW',null,'RBL_MISDB_PROD','MD_REGEX_SCHEMA_MVIEW',null,null,to_date('29-NOV-24','DD-MON-RR'),26,null,null,null,0,'?',null,null,null,null,null,2,10,1,0,null,69206336,2097152,'SELECT  PROJECT_ID, CONNECTION_ID, CONNECTION_NAME,CATALOG_ID,
        CATALOG_NAME, ITEM, SUM(VALUE) "VALUE" from MD_REGEX_SCHEMA_MVIEW
        group by  PROJECT_ID, CONNECTION_ID, CONNECTION_NAME,CATALOG_ID,
        CATALOG_NAME, ITEM',null,to_date('29-NOV-24','DD-MON-RR'),null,6127697,0,236,0,null,0,null,null,null,null,null,null,null,null,null,null,0,4194304,null,0);
Insert into SYS.SNAP$ (SOWNER,VNAME,TNAME,MVIEW,MOWNER,MASTER,MLINK,CAN_USE_LOG,SNAPSHOT,SNAPID,SSCN,SNAPTIME,TSCN,ERROR#,AUTO_FAST,AUTO_FUN,AUTO_DATE,REFGROUP,USTRG,USLOG,STATUS,MASTER_VERSION,TABLES,FIELD1,FIELD2,FLAG,FLAG2,QUERY_TXT,LOBMASKVEC,MTIME,MAS_ROLL_SEG,RSCN,REFHNT,QUERY_LEN,INSTSITE,FLAVOR_ID,OBJFLAG,SNA_TYPE_OID,SNA_TYPE_HASHCODE,SNA_TYPE_OWNER,SNA_TYPE_NAME,MAS_TYPE_OID,MAS_TYPE_HASHCODE,MAS_TYPE_OWNER,MAS_TYPE_NAME,PARENT_SOWNER,PARENT_VNAME,SYN_COUNT,FLAG3,EVAL_EDITION,FLAG4) values ('ACL_RBL_MISDB_PROD','MD_REGEX_MVIEW','MD_REGEX_MVIEW',null,'ACL_RBL_MISDB_PROD','MD_CODE_REGEX',null,'X',to_date('01-JAN-50','DD-MON-RR'),41,null,null,null,0,'?',null,null,null,null,null,8194,10,6,0,null,2105409,1075838976,'SELECT  pr.PROJECT_NAME, pr.ID "PROJECT_ID", c.ID "CONNECTION_ID", c.NAME "CONNECTION_NAME", mc.ID "CATALOG_ID",
        mc.CATALOG_NAME,s.id "SCHEMA_ID",s.NAME "SCHEMA_NAME", p.ID "PROGRAM_ID", p.name "PROGRAM_NAME",
        rg.DESCRIPTION "ITEM", regexp_count(p.native_sql,rg.REGEX,1,''ix'') "VALUE"
FROM MD_STORED_PROGRAMS p,
  md_projects pr,
  md_connections c,
  md_schemas s,
  MD_CATALOGS mc,
  MD_CODE_REGEX rg
WHERE c.TYPE          IS NULL --Shows captured
AND mc.CONNECTION_ID_FK=c.id
AND mc.id              =s.CATALOG_ID_FK
AND pr.PROJECT_NAME LIKE ''SS%''
and pr.id=c.PROJECT_ID_FK
and p.SCHEMA_ID_FK=s.ID
and regexp_count(p.native_sql,rg.REGEX,1,''ix'')>0',null,to_date('18-DEC-24','DD-MON-RR'),null,9542659,0,663,0,null,0,null,null,null,null,null,null,null,null,null,null,0,4194304,null,0);
Insert into SYS.SNAP$ (SOWNER,VNAME,TNAME,MVIEW,MOWNER,MASTER,MLINK,CAN_USE_LOG,SNAPSHOT,SNAPID,SSCN,SNAPTIME,TSCN,ERROR#,AUTO_FAST,AUTO_FUN,AUTO_DATE,REFGROUP,USTRG,USLOG,STATUS,MASTER_VERSION,TABLES,FIELD1,FIELD2,FLAG,FLAG2,QUERY_TXT,LOBMASKVEC,MTIME,MAS_ROLL_SEG,RSCN,REFHNT,QUERY_LEN,INSTSITE,FLAVOR_ID,OBJFLAG,SNA_TYPE_OID,SNA_TYPE_HASHCODE,SNA_TYPE_OWNER,SNA_TYPE_NAME,MAS_TYPE_OID,MAS_TYPE_HASHCODE,MAS_TYPE_OWNER,MAS_TYPE_NAME,PARENT_SOWNER,PARENT_VNAME,SYN_COUNT,FLAG3,EVAL_EDITION,FLAG4) values ('ACL_RBL_MISDB_PROD','MD_REGEX_SCHEMA_MVIEW','MD_REGEX_SCHEMA_MVIEW',null,'ACL_RBL_MISDB_PROD','MD_REGEX_MVIEW',null,null,to_date('18-DEC-24','DD-MON-RR'),42,null,null,null,0,'?',null,null,null,null,null,2,10,1,0,null,2097472,2097152,'SELECT  PROJECT_ID, CONNECTION_ID, CONNECTION_NAME,CATALOG_ID,
        CATALOG_NAME,SCHEMA_ID,SCHEMA_NAME, ITEM, SUM(VALUE) "VALUE" from MD_REGEX_MVIEW
        group by PROJECT_NAME, PROJECT_ID, CONNECTION_ID, CONNECTION_NAME,CATALOG_ID,
        CATALOG_NAME,SCHEMA_ID,SCHEMA_NAME, ITEM',null,to_date('18-DEC-24','DD-MON-RR'),null,9542724,0,286,0,null,0,null,null,null,null,null,null,null,null,null,null,0,4194304,null,0);
Insert into SYS.SNAP$ (SOWNER,VNAME,TNAME,MVIEW,MOWNER,MASTER,MLINK,CAN_USE_LOG,SNAPSHOT,SNAPID,SSCN,SNAPTIME,TSCN,ERROR#,AUTO_FAST,AUTO_FUN,AUTO_DATE,REFGROUP,USTRG,USLOG,STATUS,MASTER_VERSION,TABLES,FIELD1,FIELD2,FLAG,FLAG2,QUERY_TXT,LOBMASKVEC,MTIME,MAS_ROLL_SEG,RSCN,REFHNT,QUERY_LEN,INSTSITE,FLAVOR_ID,OBJFLAG,SNA_TYPE_OID,SNA_TYPE_HASHCODE,SNA_TYPE_OWNER,SNA_TYPE_NAME,MAS_TYPE_OID,MAS_TYPE_HASHCODE,MAS_TYPE_OWNER,MAS_TYPE_NAME,PARENT_SOWNER,PARENT_VNAME,SYN_COUNT,FLAG3,EVAL_EDITION,FLAG4) values ('ACL_RBL_MISDB_PROD','MD_REGEX_CATALOG_MVIEW','MD_REGEX_CATALOG_MVIEW',null,'ACL_RBL_MISDB_PROD','MD_REGEX_SCHEMA_MVIEW',null,null,to_date('18-DEC-24','DD-MON-RR'),43,null,null,null,0,'?',null,null,null,null,null,2,10,1,0,null,69206336,2097152,'SELECT  PROJECT_ID, CONNECTION_ID, CONNECTION_NAME,CATALOG_ID,
        CATALOG_NAME, ITEM, SUM(VALUE) "VALUE" from MD_REGEX_SCHEMA_MVIEW
        group by  PROJECT_ID, CONNECTION_ID, CONNECTION_NAME,CATALOG_ID,
        CATALOG_NAME, ITEM',null,to_date('18-DEC-24','DD-MON-RR'),null,9542751,0,236,0,null,0,null,null,null,null,null,null,null,null,null,null,0,4194304,null,0);
Insert into SYS.SNAP$ (SOWNER,VNAME,TNAME,MVIEW,MOWNER,MASTER,MLINK,CAN_USE_LOG,SNAPSHOT,SNAPID,SSCN,SNAPTIME,TSCN,ERROR#,AUTO_FAST,AUTO_FUN,AUTO_DATE,REFGROUP,USTRG,USLOG,STATUS,MASTER_VERSION,TABLES,FIELD1,FIELD2,FLAG,FLAG2,QUERY_TXT,LOBMASKVEC,MTIME,MAS_ROLL_SEG,RSCN,REFHNT,QUERY_LEN,INSTSITE,FLAVOR_ID,OBJFLAG,SNA_TYPE_OID,SNA_TYPE_HASHCODE,SNA_TYPE_OWNER,SNA_TYPE_NAME,MAS_TYPE_OID,MAS_TYPE_HASHCODE,MAS_TYPE_OWNER,MAS_TYPE_NAME,PARENT_SOWNER,PARENT_VNAME,SYN_COUNT,FLAG3,EVAL_EDITION,FLAG4) values ('RBL_TEMPDB','MD_REGEX_MVIEW','MD_REGEX_MVIEW',null,'RBL_TEMPDB','MD_CODE_REGEX',null,'X',to_date('01-JAN-50','DD-MON-RR'),44,null,null,null,0,'?',null,null,null,null,null,8194,10,6,0,null,2105409,1075838976,'SELECT  pr.PROJECT_NAME, pr.ID "PROJECT_ID", c.ID "CONNECTION_ID", c.NAME "CONNECTION_NAME", mc.ID "CATALOG_ID",
        mc.CATALOG_NAME,s.id "SCHEMA_ID",s.NAME "SCHEMA_NAME", p.ID "PROGRAM_ID", p.name "PROGRAM_NAME",
        rg.DESCRIPTION "ITEM", regexp_count(p.native_sql,rg.REGEX,1,''ix'') "VALUE"
FROM MD_STORED_PROGRAMS p,
  md_projects pr,
  md_connections c,
  md_schemas s,
  MD_CATALOGS mc,
  MD_CODE_REGEX rg
WHERE c.TYPE          IS NULL --Shows captured
AND mc.CONNECTION_ID_FK=c.id
AND mc.id              =s.CATALOG_ID_FK
AND pr.PROJECT_NAME LIKE ''SS%''
and pr.id=c.PROJECT_ID_FK
and p.SCHEMA_ID_FK=s.ID
and regexp_count(p.native_sql,rg.REGEX,1,''ix'')>0',null,to_date('18-DEC-24','DD-MON-RR'),null,9560609,0,663,0,null,0,null,null,null,null,null,null,null,null,null,null,0,4194304,null,0);
Insert into SYS.SNAP$ (SOWNER,VNAME,TNAME,MVIEW,MOWNER,MASTER,MLINK,CAN_USE_LOG,SNAPSHOT,SNAPID,SSCN,SNAPTIME,TSCN,ERROR#,AUTO_FAST,AUTO_FUN,AUTO_DATE,REFGROUP,USTRG,USLOG,STATUS,MASTER_VERSION,TABLES,FIELD1,FIELD2,FLAG,FLAG2,QUERY_TXT,LOBMASKVEC,MTIME,MAS_ROLL_SEG,RSCN,REFHNT,QUERY_LEN,INSTSITE,FLAVOR_ID,OBJFLAG,SNA_TYPE_OID,SNA_TYPE_HASHCODE,SNA_TYPE_OWNER,SNA_TYPE_NAME,MAS_TYPE_OID,MAS_TYPE_HASHCODE,MAS_TYPE_OWNER,MAS_TYPE_NAME,PARENT_SOWNER,PARENT_VNAME,SYN_COUNT,FLAG3,EVAL_EDITION,FLAG4) values ('RBL_TEMPDB','MD_REGEX_SCHEMA_MVIEW','MD_REGEX_SCHEMA_MVIEW',null,'RBL_TEMPDB','MD_REGEX_MVIEW',null,null,to_date('18-DEC-24','DD-MON-RR'),45,null,null,null,0,'?',null,null,null,null,null,2,10,1,0,null,2097472,2097152,'SELECT  PROJECT_ID, CONNECTION_ID, CONNECTION_NAME,CATALOG_ID,
        CATALOG_NAME,SCHEMA_ID,SCHEMA_NAME, ITEM, SUM(VALUE) "VALUE" from MD_REGEX_MVIEW
        group by PROJECT_NAME, PROJECT_ID, CONNECTION_ID, CONNECTION_NAME,CATALOG_ID,
        CATALOG_NAME,SCHEMA_ID,SCHEMA_NAME, ITEM',null,to_date('18-DEC-24','DD-MON-RR'),null,9560671,0,286,0,null,0,null,null,null,null,null,null,null,null,null,null,0,4194304,null,0);
Insert into SYS.SNAP$ (SOWNER,VNAME,TNAME,MVIEW,MOWNER,MASTER,MLINK,CAN_USE_LOG,SNAPSHOT,SNAPID,SSCN,SNAPTIME,TSCN,ERROR#,AUTO_FAST,AUTO_FUN,AUTO_DATE,REFGROUP,USTRG,USLOG,STATUS,MASTER_VERSION,TABLES,FIELD1,FIELD2,FLAG,FLAG2,QUERY_TXT,LOBMASKVEC,MTIME,MAS_ROLL_SEG,RSCN,REFHNT,QUERY_LEN,INSTSITE,FLAVOR_ID,OBJFLAG,SNA_TYPE_OID,SNA_TYPE_HASHCODE,SNA_TYPE_OWNER,SNA_TYPE_NAME,MAS_TYPE_OID,MAS_TYPE_HASHCODE,MAS_TYPE_OWNER,MAS_TYPE_NAME,PARENT_SOWNER,PARENT_VNAME,SYN_COUNT,FLAG3,EVAL_EDITION,FLAG4) values ('RBL_TEMPDB','MD_REGEX_CATALOG_MVIEW','MD_REGEX_CATALOG_MVIEW',null,'RBL_TEMPDB','MD_REGEX_SCHEMA_MVIEW',null,null,to_date('18-DEC-24','DD-MON-RR'),46,null,null,null,0,'?',null,null,null,null,null,2,10,1,0,null,69206336,2097152,'SELECT  PROJECT_ID, CONNECTION_ID, CONNECTION_NAME,CATALOG_ID,
        CATALOG_NAME, ITEM, SUM(VALUE) "VALUE" from MD_REGEX_SCHEMA_MVIEW
        group by  PROJECT_ID, CONNECTION_ID, CONNECTION_NAME,CATALOG_ID,
        CATALOG_NAME, ITEM',null,to_date('18-DEC-24','DD-MON-RR'),null,9560698,0,236,0,null,0,null,null,null,null,null,null,null,null,null,null,0,4194304,null,0);
