--------------------------------------------------------
--  DDL for Table SNAP_REFOP$
--------------------------------------------------------

  CREATE TABLE "SYS"."SNAP_REFOP$" SHARING=METADATA 
   (	"SOWNER" VARCHAR2(128 BYTE), 
	"VNAME" VARCHAR2(128 BYTE), 
	"TABNUM" NUMBER(*,0), 
	"SETNUM" NUMBER(*,0) DEFAULT 0, 
	"OPERATION#" NUMBER(*,0), 
	"COLS" NUMBER, 
	"FCMASKVEC" RAW(255), 
	"EJMASKVEC" RAW(255), 
	"SQL_TXT" LONG, 
	"INSTSITE" NUMBER(*,0) DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
