REM INSERTING into SYS.SQL_TK_REF_CHK$
SET DEFINE OFF;
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('TAB$',3,'file#','file$','relfile#','file# != 0 and file# != 1024','foreign key relfile# not found in file$');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('TAB$',4,'ts#','ts$','ts#','ts# != 2147483647','foreign key ts# not found in ts$');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('TAB$',5,'ts#, file#, block#','seg$','ts#, file#,block#','file# != 0 and block# != 0','foreign key (file#, block#) not found in seg$');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('TAB$',6,'obj#','obj$','obj#',null,'foreign key (obj#) not found in obj$');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('CLU$',16,'file#','file$','relfile#','file# != 1024','Foreign Key - clu$.file# not found in file$.relfile#');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('CLU$',17,'ts#','ts$','ts#','ts# != 2147483647','Foreign Key - clu$.ts# not found in ts$.ts#');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('CLU$',18,'ts#, file#, block#','seg$','ts#, file#,block#','file# != 0 and block# != 0','Foreign Key - clu$.(file#,block#) not found in seg$');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('FET$',24,'ts#','ts$','ts#',null,'fet$.ts# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('UET$',26,'ts#','ts$','ts#',null,'uet.ts# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('UET$',28,'ts#,segfile#,segblock#','seg$','ts#,file#,block#',null,'uet$ seg$ fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('SEG$',30,'ts#','ts$','ts#',null,'seg.ts# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('SEG$',32,'user#','user$','user#',null,'seg$.user# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('UNDO$',34,'ts#,file#,block#','seg$','ts#,file#,block#','status$ != 1','undo$ seg fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('UNDO$',37,'ts#','ts$','ts#',null,'undo$.ts# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('TS$',39,'owner#','user$','user#',null,'ts$.owner# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('OBJ$',45,'owner#','user$','user#',null,'obj$.owner# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('OBJ$',49,'obj#','tab$','obj#','obj$.type# = 2 and remoteowner is null and linkname is null','obj$ ref to tab$');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('IND$',53,'ts#','ts$','ts#','ts# != 2147483647','ind$.ts# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('IND$',54,'ts#,file#,block#','seg$','ts#,file#,block#','file# != 0 and block# != 0','ind$.ts,file,block fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('IND$',55,'obj#','obj$','obj#',null,'ind$.obj# fk_obj$');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('ICOL$',60,'obj#','obj$','obj#',null,'icol$.obj# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('ICOL$',61,'bo#','obj$','obj#',null,'icol$.bo# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('ICOL$',62,'bo#, col#','col$','obj#, col#',null,'icol$.col# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('ICOL$',63,'obj#','ind$','obj#',null,'icol$.bo# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('COL$',64,'obj#','obj$','obj#',null,'col$.obj# fk(obj$)');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('USER$',68,'datats#','ts$','ts#',null,'user$.datats# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('USER$',69,'tempts#','ts$','ts#',null,'user$.tempts# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('CON$',73,'owner#','user$','owner#',null,'con$.owner# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('CDEF$',75,'con#','con$','con#',null,'cdef$.con# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('CDEF$',76,'obj#','obj$','obj#',null,'cdef$.obj# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('CCOL$',79,'obj#','obj$','obj#',null,'ccol$.obj# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('CCOL$',80,'con#','con$','con#',null,'ccol$.con# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('CCOL$',81,'obj#,col#','col$','obj#,col#',null,'ccol$.obj#,col# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('BOOTSTRAP$',83,'obj#','obj$','obj#','obj# > 0','bootstrap$.obj# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('OBJAUTH$',85,'obj#','obj$','obj#',null,'objauth$.obj# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('OBJAUTH$',86,'grantor#','user$','user#',null,'objauth$.grantor# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('OBJAUTH$',87,'grantee#','user$','user#',null,'objauth$.grantee# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('TSQ$',90,'ts#','ts$','ts#',null,'tsq$.ts# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('TSQ$',91,'user#','user$','user#',null,'tsq$.user# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('TSQ$',92,'grantor#','user$','user#',null,'tsq$.grantor# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('VIEW$',95,'obj#','obj$','obj#',null,'view$.obj# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('TYPED_VIEW$',97,'obj#','obj$','obj#',null,'view$.obj# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('TYPED_VIEW$',98,'typeowner','user$','name',null,'typed_view$.typeowner fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('SUPEROBJ$',99,'subobj#','obj$','obj#',null,'superobj$.subobj# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('SUPEROBJ$',100,'superobj#','obj$','obj#',null,'superobj$.superobj# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('SEQ$',103,'obj#','obj$','obj#',null,'seq$.obj# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('LOB$',106,'obj#','obj$','obj#',null,'lob$.obj# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('LOB$',107,'obj#,col#','col$','obj#,col#',null,'lob$.obj#,col# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('LOB$',108,'lobj#','obj$','obj#',null,'lob$.lobj# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('LOB$',109,'ind#','ind$','obj#',null,'lob$.ind# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('LOB$',110,'ts#,file#,block#','seg$','ts#,file#,block#','block# != 0','lob$.ts#,file#,block# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('COLTYPE$',111,'obj#','obj$','obj#',null,'coltype$.obj# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('COLTYPE$',112,'obj#,col#','col$','obj#,col#',null,'coltype$.obj#,col# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('SUBCOLTYPE$',113,'obj#','obj$','obj#',null,'subcoltype$.obj# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('SUBCOLTYPE$',114,'obj#,intcol#','col$','obj#,intcol#',null,'subcoltype$.obj#,intcol# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('NTAB$',116,'obj#','obj$','obj#',null,'ntab$.obj# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('NTAB$',117,'obj#,intcol#','col$','obj#,intcol#',null,'ntab$.obj#,intcol# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('NTAB$',118,'ntab#','obj$','obj#','ntab# != 0','ntab$.ntab$ fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('REFCON$',119,'obj#','obj$','obj#',null,'refcon$.obj# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('REFCON$',120,'obj#,col#','col$','obj#,col#',null,'refcont$.obj#,col# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('OPQTYPE$',122,'obj#','obj$','obj#',null,'opqtype$.obj# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('OPQTYPE$',123,'obj#,intcol#','col$','obj#,intcol#',null,'opqtype$.obj#,intcol# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('ACCESS$',127,'d_obj#','dependency$','d_obj#','types != 12','access$.dobj# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('VIEWCON$',129,'obj#','view$','obj#',null,'viewcon$.obj# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('VIEWCON$',130,'con#','cdef$','con#',null,'viewcon$.con# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('VIEWCON$',132,'robj#','obj$','obj#',null,'viewcon$.robj# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('ICOLDEP$',133,'obj#','ind$','obj#',null,'icoldep$.obj# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('SYSAUTH$',136,'grantee#','user$','user#','grantee# < (select user# from user$ where name = ''_NEXT_USER'')','sysauth$.grantee# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('OBJPRIV$',139,'obj#','obj$','obj#',null,'objpriv$.obj# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('DEFROLE$',141,'user#','user$','user#',null,'defrole$.user# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('ECOL$',143,'tabobj#','tab$','obj#',null,'ecol$.tabobj# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('ECOL$',144,'tabobj#,colnum','col$','obj#,intcol#',null,'ecol$.tabobj#,colnum fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('DEFERRED_STG$',146,'obj#','obj$','obj#',null,'deferred_stg$.obj# fk');
Insert into SYS.SQL_TK_REF_CHK$ (TABLE_NAME,CHK_ID,FK_COL_LIST,PK_TABLE_NAME,PK_COL_LIST,FK_FILTER,CHECK_DESCRIPTION) values ('TRANSIENT_IOT$',148,'obj#','tab$','obj#',null,'transient_iot$.obj# fk');
