--------------------------------------------------------
--  DDL for Table SQL$_DATAPUMP_TBL
--------------------------------------------------------

  CREATE TABLE "SYS"."SQL$_DATAPUMP_TBL" SHARING=METADATA 
   (	"SIGNATURE" NUMBER, 
	"INUSE_FEATURES" NUMBER, 
	"FLAGS" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" CLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("SPARE2") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
  GRANT SELECT ON "SYS"."SQL$_DATAPUMP_TBL" TO "SELECT_CATALOG_ROLE";
