--------------------------------------------------------
--  Constraints for Table SQL_TK_REF_CHK$
--------------------------------------------------------

  ALTER TABLE "SYS"."SQL_TK_REF_CHK$" MODIFY ("TABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SQL_TK_REF_CHK$" MODIFY ("CHK_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SQL_TK_REF_CHK$" MODIFY ("FK_COL_LIST" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SQL_TK_REF_CHK$" MODIFY ("PK_TABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SQL_TK_REF_CHK$" MODIFY ("PK_COL_LIST" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SQL_TK_REF_CHK$" MODIFY ("CHECK_DESCRIPTION" NOT NULL ENABLE);
