--------------------------------------------------------
--  DDL for Table SQL$TEXT
--------------------------------------------------------

  CREATE TABLE "SYS"."SQL$TEXT" SHARING=METADATA 
   (	"SIGNATURE" NUMBER, 
	"SQL_HANDLE" VARCHAR2(30 BYTE), 
	"SQL_TEXT" CLOB, 
	"SPARE1" NUMBER, 
	"SPARE2" CLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" 
 LOB ("SQL_TEXT") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("SPARE2") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
