--------------------------------------------------------
--  DDL for Table SQL$
--------------------------------------------------------

  CREATE TABLE "SYS"."SQL$" SHARING=METADATA 
   (	"SIGNATURE" NUMBER, 
	"INUSE_FEATURES" NUMBER, 
	"FLAGS" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" CLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" 
 LOB ("SPARE2") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
