REM INSERTING into SYS.SQL_TK_COLL_CHK$
SET DEFINE OFF;
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('TAB$',2,'obj#','< 0','Obj# invalid - < 0');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('TAB$',7,'tab#','is not null and tab# not between 1 and 31','tab# out of range for a clustered table');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('TAB$',8,'cols','>1000','invalid column number');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('TAB$',9,'clucols','is not null and clucols not between 1 and 33','invalid cluster column number found');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('TAB$',10,'pctfree$','not between 0 and 99 and bitand(flags, 268435456) != 268435456','invalid pctfree found');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('TAB$',11,'pctused$','not between 0 and 99 and dataobj# != 0 and dataobj#  is not null','invalid pctused$ found');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('TAB$',12,'analyzetime','>SYSDATE','analyzetime for object new than sysdate');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('CLU$',14,'obj#','< 0','obj# invalid - < 0');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('CLU$',15,'dataobj#','< obj#','dataobj# invalid - must be >= obj#');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('CLU$',19,'pctfree$','not between 0 and 99','Invalid pctfree$');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('CLU$',20,'pctused$','not between 1 and 99','Invalid pctused$');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('CLU$',21,'cols','>33','Invalid cols in clu$ - cols > 33');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('CLU$',22,'func','not in (0,2,3)','Invalid function found - not in (0,2,3)');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('SEG$',31,'type#','not between 1 and 10','seg$.type#');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('SEG$',33,'extents','!=(select count(*) from sys.uet$ u where u.ts# = seg$.ts# and u.segfile# = seg$.file# and u.segblock# = seg$.block#) and seg$.ts# in (select ts$.ts# from ts$ where flags=0)','seg$.extents');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('UNDO$',36,'status$','not between 1 and 6','undo$.status$');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('TS$',41,'online$','not between 1 and 4','ts$.online$');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('FILE$',42,'ts#','is not null and ts# not in (select ts# from ts$)','file$.status$');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('FILE$',43,'status$','not between 1 and 2','file$.status$');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('OBJ$',46,'namespace','not between 1 and 114','obj$.namespace');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('OBJ$',47,'type#','not between 0 and 137','obj$.type#');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('OBJ$',48,'status','not between 0 and 7','obj$.status');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('IND$',51,'obj#','<0','ind$.obj#');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('IND$',56,'type#','not between 1 and 9','ind$.type#');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('IND$',57,'pctfree$','not between 0 and 99','ind$.pctfree$');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('IND$',58,'analyzetime','> SYSDATE','ind$.analyzetime <= SYSDATE');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('COL$',65,'col#','not between 0 and 1000','col$.col#');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('COL$',66,'segcol#','not between 0 and 1000','col$,segcol#');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('USER$',70,'ctime','>=SYSDATE','user$.ctime');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('USER$',71,'astatus','not in (select status# from sys.user_astatus_map) and (mod(astatus, 16) not in (select status# from sys.user_astatus_map))','user$.astatus');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('CDEF$',77,'type#','not between 1 and 17','cdef$.type#');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('CDEF$',78,'mtime','>SYSDATE','cdef$.mtime');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('SEQ$',104,'partcount','is not null and partcount not between 0 and 100000000','check seq$.partcount range');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('DEPENDENCY$',125,'d_timestamp','>SYSDATE and d_timestamp != to_date(''12/31/4712 23:59:59'', ''mm/dd/yyyy hh24:mi:ss'')','dependency$.d_timestamp');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('DEPENDENCY$',126,'p_timestamp','>SYSDATE and p_timestamp != to_date(''12/31/4712 23:59:59'', ''mm/dd/yyyy hh24:mi:ss'')','dependency$.p_timestamp');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('VIEWCON$',131,'type#','not in (2,3,4)','viewcon$.type#');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('DUAL',134,'rownum','>1','dual row count');
Insert into SYS.SQL_TK_COLL_CHK$ (TABLE_NAME,CHK_ID,COL_LIST,EXPR,CHECK_DESCRIPTION) values ('SYSAUTH$',137,'option$','not in (null, 1)','sysauth$.option$');
