--------------------------------------------------------
--  DDL for Table SQL$TEXT_DATAPUMP_TBL
--------------------------------------------------------

  CREATE TABLE "SYS"."SQL$TEXT_DATAPUMP_TBL" SHARING=METADATA 
   (	"SIGNATURE" NUMBER, 
	"SQL_HANDLE" VARCHAR2(30 BYTE), 
	"SQL_TEXT" CLOB, 
	"SPARE1" NUMBER, 
	"SPARE2" CLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("SQL_TEXT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("SPARE2") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
  GRANT SELECT ON "SYS"."SQL$TEXT_DATAPUMP_TBL" TO "SELECT_CATALOG_ROLE";
