--------------------------------------------------------
--  DDL for Table SQL_TK_REF_CHK$
--------------------------------------------------------

  CREATE TABLE "SYS"."SQL_TK_REF_CHK$" SHARING=METADATA 
   (	"TABLE_NAME" VARCHAR2(128 BYTE), 
	"CHK_ID" NUMBER, 
	"FK_COL_LIST" VARCHAR2(4000 BYTE), 
	"PK_TABLE_NAME" VARCHAR2(128 BYTE), 
	"PK_COL_LIST" VARCHAR2(4000 BYTE), 
	"FK_FILTER" VARCHAR2(4000 BYTE), 
	"CHECK_DESCRIPTION" VARCHAR2(256 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
