--------------------------------------------------------
--  Constraints for Table SQLERROR$
--------------------------------------------------------

  ALTER TABLE "SYS"."SQLERROR$" MODIFY ("SQLHASH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SQLERROR$" MODIFY ("ERROR#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SQLERROR$" MODIFY ("ERRPOS#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SQLERROR$" MODIFY ("FLAGS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SQLERROR$" MODIFY ("SPARE1" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SQLERROR$" MODIFY ("SPARE2" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SQLERROR$" MODIFY ("SPARE3" NOT NULL ENABLE);
