--------------------------------------------------------
--  DDL for Table SQLOBJ$_DATAPUMP_TBL
--------------------------------------------------------

  CREATE TABLE "SYS"."SQLOBJ$_DATAPUMP_TBL" SHARING=METADATA 
   (	"SIGNATURE" NUMBER, 
	"CATEGORY" VARCHAR2(128 BYTE), 
	"OBJ_TYPE" NUMBER, 
	"PLAN_ID" NUMBER, 
	"NAME" VARCHAR2(128 BYTE), 
	"FLAGS" NUMBER, 
	"LAST_EXECUTED" TIMESTAMP (6), 
	"SPARE1" NUMBER, 
	"SPARE2" CLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("SPARE2") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
  GRANT SELECT ON "SYS"."SQLOBJ$_DATAPUMP_TBL" TO "SELECT_CATALOG_ROLE";
