--------------------------------------------------------
--  DDL for Table SQLOBJ$DATA
--------------------------------------------------------

  CREATE TABLE "SYS"."SQLOBJ$DATA" SHARING=METADATA 
   (	"SIGNATURE" NUMBER, 
	"CATEGORY" VARCHAR2(128 BYTE), 
	"OBJ_TYPE" NUMBER, 
	"PLAN_ID" NUMBER, 
	"COMP_DATA" CLOB, 
	"SPARE1" NUMBER, 
	"SPARE2" CLOB, 
	 CONSTRAINT "SQLOBJ$DATA_PKEY" PRIMARY KEY ("SIGNATURE", "CATEGORY", "OBJ_TYPE", "PLAN_ID") ENABLE
   ) ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 PCTTHRESHOLD 50
 LOB ("COMP_DATA") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" DISABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("SPARE2") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" DISABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
