--------------------------------------------------------
--  Constraints for Table SQLOBJ$AUXDATA_DATAPUMP_TBL
--------------------------------------------------------

  ALTER TABLE "SYS"."SQLOBJ$AUXDATA_DATAPUMP_TBL" MODIFY ("SIGNATURE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SQLOBJ$AUXDATA_DATAPUMP_TBL" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SQLOBJ$AUXDATA_DATAPUMP_TBL" MODIFY ("OBJ_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SQLOBJ$AUXDATA_DATAPUMP_TBL" MODIFY ("PLAN_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SQLOBJ$AUXDATA_DATAPUMP_TBL" MODIFY ("ORIGIN" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SQLOBJ$AUXDATA_DATAPUMP_TBL" MODIFY ("CREATED" NOT NULL ENABLE);
