--------------------------------------------------------
--  DDL for Table SQLOBJ$PLAN_DATAPUMP_TBL
--------------------------------------------------------

  CREATE TABLE "SYS"."SQLOBJ$PLAN_DATAPUMP_TBL" SHARING=METADATA 
   (	"SIGNATURE" NUMBER, 
	"CATEGORY" VARCHAR2(128 BYTE), 
	"OBJ_TYPE" NUMBER, 
	"PLAN_ID" NUMBER, 
	"STATEMENT_ID" VARCHAR2(30 BYTE), 
	"XPL_PLAN_ID" NUMBER, 
	"TIMESTAMP" DATE, 
	"REMARKS" VARCHAR2(4000 BYTE), 
	"OPERATION" VARCHAR2(30 BYTE), 
	"OPTIONS" VARCHAR2(255 BYTE), 
	"OBJECT_NODE" VARCHAR2(128 BYTE), 
	"OBJECT_OWNER" VARCHAR2(128 BYTE), 
	"OBJECT_NAME" VARCHAR2(128 BYTE), 
	"OBJECT_ALIAS" VARCHAR2(261 BYTE), 
	"OBJECT_INSTANCE" NUMBER, 
	"OBJECT_TYPE" VARCHAR2(30 BYTE), 
	"OPTIMIZER" VARCHAR2(255 BYTE), 
	"SEARCH_COLUMNS" NUMBER, 
	"ID" NUMBER, 
	"PARENT_ID" NUMBER, 
	"DEPTH" NUMBER, 
	"POSITION" NUMBER, 
	"COST" NUMBER, 
	"CARDINALITY" NUMBER, 
	"BYTES" NUMBER, 
	"OTHER_TAG" VARCHAR2(255 BYTE), 
	"PARTITION_START" VARCHAR2(255 BYTE), 
	"PARTITION_STOP" VARCHAR2(255 BYTE), 
	"PARTITION_ID" NUMBER, 
	"DISTRIBUTION" VARCHAR2(30 BYTE), 
	"CPU_COST" NUMBER, 
	"IO_COST" NUMBER, 
	"TEMP_SPACE" NUMBER, 
	"ACCESS_PREDICATES" VARCHAR2(4000 BYTE), 
	"FILTER_PREDICATES" VARCHAR2(4000 BYTE), 
	"PROJECTION" VARCHAR2(4000 BYTE), 
	"TIME" NUMBER, 
	"QBLOCK_NAME" VARCHAR2(128 BYTE), 
	"OTHER_XML" CLOB, 
	"OTHER" VARCHAR2(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("OTHER_XML") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
  GRANT SELECT ON "SYS"."SQLOBJ$PLAN_DATAPUMP_TBL" TO "SELECT_CATALOG_ROLE";
