--------------------------------------------------------
--  DDL for Table SQLOBJ$AUXDATA_DATAPUMP_TBL
--------------------------------------------------------

  CREATE TABLE "SYS"."SQLOBJ$AUXDATA_DATAPUMP_TBL" SHARING=METADATA 
   (	"SIGNATURE" NUMBER, 
	"CATEGORY" VARCHAR2(128 BYTE), 
	"OBJ_TYPE" NUMBER, 
	"PLAN_ID" NUMBER, 
	"DESCRIPTION" VARCHAR2(500 BYTE), 
	"CREATOR" VARCHAR2(128 BYTE), 
	"ORIGIN" NUMBER, 
	"VERSION" VARCHAR2(64 BYTE), 
	"CREATED" TIMESTAMP (6), 
	"LAST_MODIFIED" TIMESTAMP (6), 
	"LAST_VERIFIED" TIMESTAMP (6), 
	"PARSE_CPU_TIME" NUMBER, 
	"OPTIMIZER_COST" NUMBER, 
	"MODULE" VARCHAR2(64 BYTE), 
	"ACTION" VARCHAR2(64 BYTE), 
	"PRIORITY" NUMBER, 
	"OPTIMIZER_ENV" RAW(2000), 
	"BIND_DATA" RAW(2000), 
	"PARSING_SCHEMA_NAME" VARCHAR2(128 BYTE), 
	"EXECUTIONS" NUMBER, 
	"ELAPSED_TIME" NUMBER, 
	"CPU_TIME" NUMBER, 
	"BUFFER_GETS" NUMBER, 
	"DISK_READS" NUMBER, 
	"DIRECT_WRITES" NUMBER, 
	"ROWS_PROCESSED" NUMBER, 
	"FETCHES" NUMBER, 
	"END_OF_FETCH_COUNT" NUMBER, 
	"TASK_ID" NUMBER, 
	"TASK_EXEC_NAME" VARCHAR2(128 BYTE), 
	"TASK_OBJ_ID" NUMBER, 
	"TASK_FND_ID" NUMBER, 
	"TASK_REC_ID" NUMBER, 
	"FLAGS" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" CLOB, 
	"TASK_CON_DBID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("SPARE2") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
  GRANT SELECT ON "SYS"."SQLOBJ$AUXDATA_DATAPUMP_TBL" TO "SELECT_CATALOG_ROLE";
