--------------------------------------------------------
--  Constraints for Table SQLOBJ$AUXDATA
--------------------------------------------------------

  ALTER TABLE "SYS"."SQLOBJ$AUXDATA" MODIFY ("SIGNATURE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SQLOBJ$AUXDATA" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SQLOBJ$AUXDATA" MODIFY ("OBJ_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SQLOBJ$AUXDATA" MODIFY ("PLAN_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SQLOBJ$AUXDATA" MODIFY ("ORIGIN" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SQLOBJ$AUXDATA" MODIFY ("CREATED" NOT NULL ENABLE);
