--------------------------------------------------------
--  DDL for Table SQLOBJ$DATA_DATAPUMP_TBL
--------------------------------------------------------

  CREATE TABLE "SYS"."SQLOBJ$DATA_DATAPUMP_TBL" SHARING=METADATA 
   (	"SIGNATURE" NUMBER, 
	"CATEGORY" VARCHAR2(128 BYTE), 
	"OBJ_TYPE" NUMBER, 
	"PLAN_ID" NUMBER, 
	"COMP_DATA" CLOB, 
	"SPARE1" NUMBER, 
	"SPARE2" CLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("COMP_DATA") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("SPARE2") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
  GRANT SELECT ON "SYS"."SQLOBJ$DATA_DATAPUMP_TBL" TO "SELECT_CATALOG_ROLE";
