--------------------------------------------------------
--  DDL for Table STATS_TARGET$
--------------------------------------------------------

  CREATE TABLE "SYS"."STATS_TARGET$" SHARING=METADATA 
   (	"START_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"END_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"STALENESS" NUMBER, 
	"OSIZE" NUMBER, 
	"OBJ#" NUMBER, 
	"TYPE#" NUMBER, 
	"FLAGS" NUMBER, 
	"STATUS" NUMBER, 
	"SID" NUMBER, 
	"SERIAL#" NUMBER, 
	"PART#" NUMBER, 
	"BO#" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
