--------------------------------------------------------
--  DDL for Table STREAMS$_CAPTURE_PROCESS
--------------------------------------------------------

  CREATE TABLE "SYS"."STREAMS$_CAPTURE_PROCESS" SHARING=METADATA 
   (	"QUEUE_OID" RAW(16), 
	"QUEUE_OWNER" VARCHAR2(128 BYTE), 
	"QUEUE_NAME" VARCHAR2(128 BYTE), 
	"CAPTURE#" NUMBER, 
	"CAPTURE_NAME" VARCHAR2(128 BYTE), 
	"STATUS" NUMBER, 
	"RULESET_OWNER" VARCHAR2(128 BYTE), 
	"RULESET_NAME" VARCHAR2(128 BYTE), 
	"LOGMNR_SID" NUMBER, 
	"PREDUMPSCN" NUMBER, 
	"DUMPSEQBEG" NUMBER, 
	"DUMPSEQEND" NUMBER, 
	"POSTDUMPSCN" NUMBER, 
	"FLAGS" NUMBER, 
	"START_SCN" NUMBER, 
	"START_SCN_TIME" TIMESTAMP (6), 
	"CAPTURE_USERID" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"USE_DBLINK" NUMBER, 
	"FIRST_SCN" NUMBER, 
	"FIRST_SCN_TIME" TIMESTAMP (6), 
	"SOURCE_DBNAME" VARCHAR2(128 BYTE), 
	"NEGATIVE_RULESET_OWNER" VARCHAR2(128 BYTE), 
	"NEGATIVE_RULESET_NAME" VARCHAR2(128 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"ERROR_NUMBER" NUMBER, 
	"ERROR_MESSAGE" VARCHAR2(4000 BYTE), 
	"STATUS_CHANGE_TIME" DATE, 
	"VERSION" VARCHAR2(64 BYTE), 
	"SPARE4" NUMBER, 
	"SPARE5" NUMBER, 
	"SPARE6" NUMBER, 
	"SPARE7" VARCHAR2(1000 BYTE), 
	"SOURCE_ROOT_NAME" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
