--------------------------------------------------------
--  DDL for Table STREAMS$_COMPONENT_EVENT_IN
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "SYS"."STREAMS$_COMPONENT_EVENT_IN" SHARING=METADATA 
   (	"COMPONENT_NAME" VARCHAR2(4000 BYTE), 
	"COMPONENT_DB" VARCHAR2(128 BYTE), 
	"COMPONENT_TYPE" NUMBER, 
	"SUB_COMPONENT_TYPE" NUMBER DEFAULT null, 
	"STAT_TIME" DATE, 
	"SESSION_ID" NUMBER, 
	"SESSION_SERIAL#" NUMBER, 
	"EVENT" VARCHAR2(128 BYTE), 
	"EVENT_TYPE" NUMBER, 
	"EVENT_COUNT" NUMBER, 
	"TOTAL_COUNT" NUMBER, 
	"MODULE_NAME" VARCHAR2(64 BYTE), 
	"ACTION_NAME" VARCHAR2(64 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(4000 BYTE), 
	"SPARE4" DATE
   ) ON COMMIT PRESERVE ROWS ;
