--------------------------------------------------------
--  DDL for Table STREAMS$_RULES
--------------------------------------------------------

  CREATE TABLE "SYS"."STREAMS$_RULES" SHARING=METADATA 
   (	"STREAMS_NAME" VARCHAR2(128 BYTE), 
	"STREAMS_TYPE" NUMBER, 
	"RULE_TYPE" NUMBER, 
	"INCLUDE_TAGGED_LCR" NUMBER, 
	"SOURCE_DATABASE" VARCHAR2(128 BYTE), 
	"RULE_OWNER" VARCHAR2(128 BYTE), 
	"RULE_NAME" VARCHAR2(128 BYTE), 
	"RULE_CONDITION" VARCHAR2(4000 BYTE), 
	"DML_CONDITION" VARCHAR2(4000 BYTE), 
	"SUBSETTING_OPERATION" NUMBER, 
	"SCHEMA_NAME" VARCHAR2(384 BYTE), 
	"OBJECT_NAME" VARCHAR2(384 BYTE), 
	"OBJECT_TYPE" NUMBER, 
	"AND_CONDITION" VARCHAR2(4000 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SOURCE_ROOT_NAME" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
