--------------------------------------------------------
--  DDL for Table STREAMS$_MESSAGE_RULES
--------------------------------------------------------

  CREATE TABLE "SYS"."STREAMS$_MESSAGE_RULES" SHARING=METADATA 
   (	"STREAMS_NAME" VARCHAR2(128 BYTE), 
	"STREAMS_TYPE" NUMBER, 
	"MSG_TYPE_OWNER" VARCHAR2(128 BYTE), 
	"MSG_TYPE_NAME" VARCHAR2(128 BYTE), 
	"MSG_RULE_VAR" VARCHAR2(128 BYTE), 
	"RULE_OWNER" VARCHAR2(128 BYTE), 
	"RULE_NAME" VARCHAR2(128 BYTE), 
	"RULE_CONDITION" VARCHAR2(4000 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" VARCHAR2(128 BYTE), 
	"SPARE5" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
