--------------------------------------------------------
--  DDL for Table STREAMS$_PATH_STAT_OUT
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "SYS"."STREAMS$_PATH_STAT_OUT" SHARING=METADATA 
   (	"PATH_ID" NUMBER, 
	"STATISTIC_TIME" DATE, 
	"STATISTIC_NAME" VARCHAR2(64 BYTE), 
	"STATISTIC_VALUE" NUMBER, 
	"STATISTIC_UNIT" VARCHAR2(64 BYTE), 
	"ADVISOR_RUN_ID" NUMBER, 
	"ADVISOR_RUN_TIME" DATE, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(4000 BYTE), 
	"SPARE4" DATE
   ) ON COMMIT PRESERVE ROWS ;
