--------------------------------------------------------
--  DDL for Table STREAMS$_SPLIT_MERGE
--------------------------------------------------------

  CREATE TABLE "SYS"."STREAMS$_SPLIT_MERGE" SHARING=METADATA 
   (	"ORIGINAL_CAPTURE_NAME" VARCHAR2(128 BYTE), 
	"CLONED_CAPTURE_NAME" VARCHAR2(128 BYTE) DEFAULT NULL, 
	"ORIGINAL_QUEUE_OWNER" VARCHAR2(128 BYTE) DEFAULT NULL, 
	"ORIGINAL_QUEUE_NAME" VARCHAR2(128 BYTE) DEFAULT NULL, 
	"CLONED_QUEUE_OWNER" VARCHAR2(128 BYTE) DEFAULT NULL, 
	"CLONED_QUEUE_NAME" VARCHAR2(128 BYTE) DEFAULT NULL, 
	"STREAMS_TYPE" NUMBER DEFAULT NULL, 
	"ORIGINAL_STREAMS_NAME" VARCHAR2(128 BYTE) DEFAULT NULL, 
	"CLONED_STREAMS_NAME" VARCHAR2(128 BYTE) DEFAULT NULL, 
	"RECOVERABLE_SCRIPT_ID" RAW(16) DEFAULT NULL, 
	"ACTION_TYPE" NUMBER DEFAULT NULL, 
	"ACTION_THRESHOLD" NUMBER DEFAULT NULL, 
	"ACTIVE" NUMBER DEFAULT NULL, 
	"STATUS" NUMBER DEFAULT NULL, 
	"STATUS_UPDATE_TIME" TIMESTAMP (6) DEFAULT NULL, 
	"CREATION_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"JOB_OWNER" VARCHAR2(128 BYTE) DEFAULT NULL, 
	"JOB_NAME" VARCHAR2(128 BYTE) DEFAULT NULL, 
	"SCHEDULE_OWNER" VARCHAR2(128 BYTE) DEFAULT NULL, 
	"SCHEDULE_NAME" VARCHAR2(128 BYTE) DEFAULT NULL, 
	"LAG" NUMBER DEFAULT NULL, 
	"ERROR_NUMBER" NUMBER DEFAULT NULL, 
	"ERROR_MESSAGE" VARCHAR2(4000 BYTE) DEFAULT NULL, 
	"SPARE1" NUMBER DEFAULT NULL, 
	"SPARE2" NUMBER DEFAULT NULL, 
	"SPARE3" NUMBER DEFAULT NULL, 
	"SPARE4" NUMBER DEFAULT NULL, 
	"SPARE5" VARCHAR2(4000 BYTE) DEFAULT NULL, 
	"SPARE6" VARCHAR2(4000 BYTE) DEFAULT NULL, 
	"SPARE7" VARCHAR2(4000 BYTE) DEFAULT NULL, 
	"SPARE8" VARCHAR2(4000 BYTE) DEFAULT NULL, 
	"SPARE9" DATE DEFAULT NULL, 
	"SPARE10" DATE DEFAULT NULL, 
	"SPARE11" DATE DEFAULT NULL, 
	"SPARE12" DATE DEFAULT NULL, 
	"SPARE13" TIMESTAMP (6) DEFAULT NULL, 
	"SPARE14" TIMESTAMP (6) DEFAULT NULL, 
	"SPARE15" TIMESTAMP (6) DEFAULT NULL, 
	"SPARE16" TIMESTAMP (6) DEFAULT NULL               /* unused */
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
