--------------------------------------------------------
--  Constraints for Table STREAMS$_APPLY_MILESTONE
--------------------------------------------------------

  ALTER TABLE "SYS"."STREAMS$_APPLY_MILESTONE" MODIFY ("APPLY#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."STREAMS$_APPLY_MILESTONE" MODIFY ("OLDEST_SCN" NOT NULL ENABLE);
  ALTER TABLE "SYS"."STREAMS$_APPLY_MILESTONE" MODIFY ("COMMIT_SCN" NOT NULL ENABLE);
  ALTER TABLE "SYS"."STREAMS$_APPLY_MILESTONE" MODIFY ("SYNCH_SCN" NOT NULL ENABLE);
  ALTER TABLE "SYS"."STREAMS$_APPLY_MILESTONE" MODIFY ("EPOCH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."STREAMS$_APPLY_MILESTONE" MODIFY ("PROCESSED_SCN" NOT NULL ENABLE);
