--------------------------------------------------------
--  DDL for Table STREAMS$_COMPONENT_PROP
--------------------------------------------------------

  CREATE TABLE "SYS"."STREAMS$_COMPONENT_PROP" SHARING=METADATA 
   (	"COMPONENT_ID" NUMBER, 
	"PROP_NAME" VARCHAR2(128 BYTE), 
	"PROP_VALUE" VARCHAR2(4000 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(4000 BYTE), 
	"SPARE4" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
