--------------------------------------------------------
--  DDL for Table STREAMS$_PROPAGATION_PROCESS
--------------------------------------------------------

  CREATE TABLE "SYS"."STREAMS$_PROPAGATION_PROCESS" SHARING=METADATA 
   (	"PROPAGATION_NAME" VARCHAR2(128 BYTE), 
	"SOURCE_QUEUE_SCHEMA" VARCHAR2(128 BYTE), 
	"SOURCE_QUEUE" VARCHAR2(128 BYTE), 
	"DESTINATION_QUEUE_SCHEMA" VARCHAR2(128 BYTE), 
	"DESTINATION_QUEUE" VARCHAR2(128 BYTE), 
	"DESTINATION_DBLINK" VARCHAR2(128 BYTE), 
	"RULESET_SCHEMA" VARCHAR2(128 BYTE), 
	"RULESET" VARCHAR2(128 BYTE), 
	"NEGATIVE_RULESET_SCHEMA" VARCHAR2(128 BYTE), 
	"NEGATIVE_RULESET" VARCHAR2(128 BYTE), 
	"ORIGINAL_PROPAGATION_NAME" VARCHAR2(128 BYTE), 
	"ORIGINAL_SOURCE_QUEUE_SCHEMA" VARCHAR2(128 BYTE), 
	"ORIGINAL_SOURCE_QUEUE" VARCHAR2(128 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" VARCHAR2(128 BYTE), 
	"ACKED_SCN" NUMBER, 
	"AUTO_MERGE_THRESHOLD" NUMBER, 
	"CREATION_TIME" DATE DEFAULT SYSDATE, 
	"ERROR_DATE" DATE, 
	"ERROR_MSG" VARCHAR2(4000 BYTE), 
	"UNSCHEDULE_TIME" DATE DEFAULT NULL, 
	"SEQNUM" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" NUMBER, 
	"SPARE5" DATE, 
	"SPARE6" DATE, 
	"SPARE7" VARCHAR2(4000 BYTE), 
	"SPARE8" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
