--------------------------------------------------------
--  DDL for Table STREAMS$_CAPTURE_SERVER
--------------------------------------------------------

  CREATE TABLE "SYS"."STREAMS$_CAPTURE_SERVER" SHARING=METADATA 
   (	"QUEUE_SCHEMA" VARCHAR2(128 BYTE), 
	"QUEUE_NAME" VARCHAR2(128 BYTE), 
	"DST_QUEUE_SCHEMA" VARCHAR2(128 BYTE), 
	"DST_QUEUE_NAME" VARCHAR2(128 BYTE), 
	"STARTUP_TIME" DATE, 
	"DBLINK" VARCHAR2(128 BYTE), 
	"STATUS" VARCHAR2(128 BYTE), 
	"TOTAL_MSGS" NUMBER, 
	"TOTAL_BYTES" NUMBER, 
	"LAST_LCR_CREATION_TIME" DATE DEFAULT NULL, 
	"LAST_LCR_PROPAGATION_TIME" DATE, 
	"DST_DATABASE_NAME" VARCHAR2(128 BYTE), 
	"SESSION_ID" NUMBER, 
	"SERIAL#" NUMBER, 
	"SPID" VARCHAR2(128 BYTE), 
	"PROPAGATION_NAME" VARCHAR2(128 BYTE) DEFAULT NULL, 
	"CAPTURE_NAME" VARCHAR2(128 BYTE) DEFAULT NULL, 
	"APPLY_NAME" VARCHAR2(128 BYTE) DEFAULT NULL, 
	"APPLY_OBJ#" NUMBER DEFAULT 0, 
	"FIRST_APPLIED_SCN" NUMBER DEFAULT 0, 
	"INACTIVE_TIME" DATE DEFAULT NULL, 
	"SUB_NUM" NUMBER DEFAULT 0, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(4000 BYTE), 
	"SPARE4" VARCHAR2(4000 BYTE), 
	"SPARE5" DATE, 
	"SPARE6" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
