--------------------------------------------------------
--  DDL for Table STREAMS$_COMPONENT_PROP_IN
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "SYS"."STREAMS$_COMPONENT_PROP_IN" SHARING=METADATA 
   (	"COMPONENT_NAME" VARCHAR2(4000 BYTE), 
	"COMPONENT_DB" VARCHAR2(128 BYTE), 
	"COMPONENT_TYPE" NUMBER, 
	"PROP_NAME" VARCHAR2(128 BYTE), 
	"PROP_VALUE" VARCHAR2(4000 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(4000 BYTE), 
	"SPARE4" DATE
   ) ON COMMIT PRESERVE ROWS ;
