--------------------------------------------------------
--  DDL for Table STREAMS$_APPLY_SPILL_TXN
--------------------------------------------------------

  CREATE TABLE "SYS"."STREAMS$_APPLY_SPILL_TXN" SHARING=METADATA 
   (	"APPLYNAME" VARCHAR2(128 BYTE), 
	"XIDUSN" NUMBER, 
	"XIDSLT" NUMBER, 
	"XIDSQN" NUMBER, 
	"FIRST_SCN" NUMBER, 
	"LAST_SCN" NUMBER, 
	"LAST_SCN_SEQ" NUMBER, 
	"LAST_CAP_INSTNO" NUMBER, 
	"COMMIT_SCN" NUMBER, 
	"SPILLCOUNT" NUMBER, 
	"ERR_NUM" NUMBER, 
	"ERR_IDX" NUMBER, 
	"SENDER" VARCHAR2(128 BYTE), 
	"FLAGS" NUMBER, 
	"PRIV_STATE" NUMBER, 
	"DISTRIB_CSCN" NUMBER, 
	"SRC_COMMIT_TIME" NUMBER, 
	"DEP_FLAG" NUMBER, 
	"SPILL_FLAGS" NUMBER, 
	"FIRST_MESSAGE_CREATE_TIME" DATE, 
	"SPILL_CREATION_TIME" DATE DEFAULT SYSDATE, 
	"TXNKEY" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" NUMBER, 
	"SPARE5" VARCHAR2(4000 BYTE), 
	"SPARE6" VARCHAR2(4000 BYTE), 
	"SPARE7" VARCHAR2(4000 BYTE), 
	"FIRST_POSITION" RAW(64), 
	"LAST_POSITION" RAW(64), 
	"COMMIT_POSITION" RAW(64), 
	"LAST_MESSAGE_CREATE_TIME" DATE, 
	"TRANSACTION_ID" VARCHAR2(128 BYTE), 
	"PARENT_TRANSACTION_ID" VARCHAR2(128 BYTE), 
	"SPARE8" DATE, 
	"SPARE9" RAW(100), 
	"PDB_ID" NUMBER DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
