--------------------------------------------------------
--  DDL for Table STREAMS$_DEST_OBJS
--------------------------------------------------------

  CREATE TABLE "SYS"."STREAMS$_DEST_OBJS" SHARING=METADATA 
   (	"OBJECT_NUMBER" NUMBER, 
	"PROPERTY" NUMBER, 
	"DBLINK" VARCHAR2(128 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" VARCHAR2(1000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
