--------------------------------------------------------
--  DDL for Table STREAMS$_PROCESS_PARAMS
--------------------------------------------------------

  CREATE TABLE "SYS"."STREAMS$_PROCESS_PARAMS" SHARING=METADATA 
   (	"PROCESS_TYPE" NUMBER, 
	"PROCESS#" NUMBER, 
	"NAME" VARCHAR2(128 BYTE), 
	"VALUE" VARCHAR2(4000 BYTE), 
	"USER_CHANGED_FLAG" NUMBER, 
	"INTERNAL_FLAG" NUMBER, 
	"SPARE1" NUMBER, 
	"SOURCE_DATABASE" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
