--------------------------------------------------------
--  DDL for Table STREAMS$_STMT_HANDLERS
--------------------------------------------------------

  CREATE TABLE "SYS"."STREAMS$_STMT_HANDLERS" SHARING=METADATA 
   (	"HANDLER_ID" NUMBER, 
	"HANDLER_NAME" VARCHAR2(128 BYTE), 
	"HANDLER_COMMENT" VARCHAR2(4000 BYTE) DEFAULT null, 
	"HANDLER_FLAG" RAW(4) DEFAULT '00000000', 
	"CREATION_TIME" TIMESTAMP (6), 
	"MODIFICATION_TIME" TIMESTAMP (6), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(4000 BYTE), 
	"SPARE4" TIMESTAMP (6), 
	"SPARE5" RAW(2000)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
