--------------------------------------------------------
--  DDL for Table STREAMS$_APPLY_PROCESS
--------------------------------------------------------

  CREATE TABLE "SYS"."STREAMS$_APPLY_PROCESS" SHARING=METADATA 
   (	"APPLY#" NUMBER, 
	"APPLY_NAME" VARCHAR2(128 BYTE), 
	"QUEUE_OID" RAW(16), 
	"QUEUE_OWNER" VARCHAR2(128 BYTE), 
	"QUEUE_NAME" VARCHAR2(128 BYTE), 
	"STATUS" NUMBER, 
	"FLAGS" NUMBER, 
	"RULESET_OWNER" VARCHAR2(128 BYTE), 
	"RULESET_NAME" VARCHAR2(128 BYTE), 
	"MESSAGE_HANDLER" VARCHAR2(392 BYTE), 
	"DDL_HANDLER" VARCHAR2(392 BYTE), 
	"PRECOMMIT_HANDLER" VARCHAR2(392 BYTE), 
	"APPLY_USERID" NUMBER, 
	"APPLY_DBLINK" VARCHAR2(128 BYTE), 
	"APPLY_TAG" RAW(2000), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"NEGATIVE_RULESET_OWNER" VARCHAR2(128 BYTE), 
	"NEGATIVE_RULESET_NAME" VARCHAR2(128 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"ERROR_NUMBER" NUMBER, 
	"ERROR_MESSAGE" VARCHAR2(4000 BYTE), 
	"STATUS_CHANGE_TIME" DATE, 
	"UA_NOTIFICATION_HANDLER" VARCHAR2(392 BYTE), 
	"UA_RULESET_OWNER" VARCHAR2(128 BYTE), 
	"UA_RULESET_NAME" VARCHAR2(128 BYTE), 
	"SPARE4" NUMBER, 
	"SPARE5" NUMBER, 
	"SPARE6" VARCHAR2(4000 BYTE), 
	"SPARE7" VARCHAR2(4000 BYTE), 
	"SPARE8" DATE, 
	"SPARE9" DATE, 
	"SOURCE_ROOT_NAME" VARCHAR2(128 BYTE), 
	"LCRID_VERSION" NUMBER DEFAULT 1                  /* lcrid version */
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
