--------------------------------------------------------
--  DDL for Table STREAMS$_LOCAL_FINDINGS_IN
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "SYS"."STREAMS$_LOCAL_FINDINGS_IN" SHARING=METADATA 
   (	"MESSAGE_ID" NUMBER, 
	"MESSAGE_ARG1" VARCHAR2(4000 BYTE), 
	"MESSAGE_ARG2" VARCHAR2(4000 BYTE), 
	"MESSAGE_ARG3" VARCHAR2(4000 BYTE), 
	"MESSAGE_ARG4" VARCHAR2(4000 BYTE), 
	"MESSAGE_ARG5" VARCHAR2(4000 BYTE), 
	"TYPE" NUMBER, 
	"MORE_INFO_ID" NUMBER, 
	"INFO_ARG1" VARCHAR2(4000 BYTE), 
	"INFO_ARG2" VARCHAR2(4000 BYTE), 
	"INFO_ARG3" VARCHAR2(4000 BYTE), 
	"INFO_ARG4" VARCHAR2(4000 BYTE), 
	"INFO_ARG5" VARCHAR2(4000 BYTE), 
	"ADVISOR_TYPE" VARCHAR2(30 BYTE), 
	"RUN_TIME" DATE, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(4000 BYTE), 
	"SPARE4" DATE
   ) ON COMMIT PRESERVE ROWS ;
