--------------------------------------------------------
--  DDL for Table STREAMS$_DATABASE
--------------------------------------------------------

  CREATE TABLE "SYS"."STREAMS$_DATABASE" SHARING=METADATA 
   (	"GLOBAL_NAME" VARCHAR2(128 BYTE), 
	"LAST_QUERIED" DATE, 
	"VERSION" VARCHAR2(128 BYTE), 
	"COMPATIBILITY" VARCHAR2(128 BYTE), 
	"MANAGEMENT_PACK_ACCESS" VARCHAR2(128 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(4000 BYTE), 
	"SPARE4" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
