--------------------------------------------------------
--  Constraints for Table STREAMS$_MESSAGE_CONSUMERS
--------------------------------------------------------

  ALTER TABLE "SYS"."STREAMS$_MESSAGE_CONSUMERS" MODIFY ("STREAMS_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."STREAMS$_MESSAGE_CONSUMERS" MODIFY ("QUEUE_OID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."STREAMS$_MESSAGE_CONSUMERS" MODIFY ("QUEUE_OWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."STREAMS$_MESSAGE_CONSUMERS" MODIFY ("QUEUE_NAME" NOT NULL ENABLE);
