--------------------------------------------------------
--  DDL for Table STREAMS$_COMPONENT
--------------------------------------------------------

  CREATE TABLE "SYS"."STREAMS$_COMPONENT" SHARING=METADATA 
   (	"COMPONENT_ID" NUMBER, 
	"COMPONENT_NAME" VARCHAR2(390 BYTE), 
	"COMPONENT_DB" VARCHAR2(128 BYTE), 
	"COMPONENT_TYPE" NUMBER, 
	"COMPONENT_PROPERTY" NUMBER, 
	"COMPONENT_CHANGED_TIME" DATE, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(4000 BYTE), 
	"SPARE4" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
