--------------------------------------------------------
--  DDL for Table STREAMS$_KEY_COLUMNS
--------------------------------------------------------

  CREATE TABLE "SYS"."STREAMS$_KEY_COLUMNS" SHARING=METADATA 
   (	"SNAME" VARCHAR2(128 BYTE), 
	"ONAME" VARCHAR2(128 BYTE), 
	"TYPE" NUMBER, 
	"CNAME" VARCHAR2(128 BYTE), 
	"DBLINK" VARCHAR2(128 BYTE), 
	"LONG_CNAME" VARCHAR2(4000 BYTE), 
	"SPARE1" NUMBER, 
	"APPLY_NAME" VARCHAR2(128 BYTE), 
	"SPARE2" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
