--------------------------------------------------------
--  DDL for Table STREAMS$_EXTRA_ATTRS
--------------------------------------------------------

  CREATE TABLE "SYS"."STREAMS$_EXTRA_ATTRS" SHARING=METADATA 
   (	"PROCESS#" NUMBER, 
	"NAME" VARCHAR2(128 BYTE), 
	"INCLUDE" VARCHAR2(128 BYTE), 
	"FLAG" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" VARCHAR2(1000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
