--------------------------------------------------------
--  DDL for Table STREAMS$_PREPARE_DDL
--------------------------------------------------------

  CREATE TABLE "SYS"."STREAMS$_PREPARE_DDL" SHARING=METADATA 
   (	"GLOBAL_FLAG" NUMBER, 
	"USRID" NUMBER, 
	"SCN" NUMBER, 
	"TIMESTAMP" DATE, 
	"FLAGS" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" VARCHAR2(1000 BYTE), 
	"ALLPDBS" NUMBER DEFAULT 0, 
	"C_INVOKER" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
