--------------------------------------------------------
--  DDL for Table STREAMS$_LOCAL_RECS_IN
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "SYS"."STREAMS$_LOCAL_RECS_IN" SHARING=METADATA 
   (	"BENEFIT_ID" NUMBER, 
	"BENEFIT_ARG1" VARCHAR2(4000 BYTE), 
	"BENEFIT_ARG2" VARCHAR2(4000 BYTE), 
	"BENEFIT_ARG3" VARCHAR2(4000 BYTE), 
	"BENEFIT_ARG4" VARCHAR2(4000 BYTE), 
	"BENEFIT_ARG5" VARCHAR2(4000 BYTE), 
	"ADVISOR_TYPE" VARCHAR2(30 BYTE), 
	"RUN_TIME" DATE, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(4000 BYTE), 
	"SPARE4" DATE
   ) ON COMMIT PRESERVE ROWS ;
