--------------------------------------------------------
--  DDL for Table STREAMS$_PATH_BOTTLENECK_OUT
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "SYS"."STREAMS$_PATH_BOTTLENECK_OUT" SHARING=METADATA 
   (	"PATH_ID" NUMBER, 
	"COMPONENT_ID" NUMBER, 
	"TOP_SESSION_ID" NUMBER, 
	"TOP_SESSION_SERIAL#" NUMBER, 
	"MODULE_NAME" VARCHAR2(64 BYTE), 
	"ACTION_NAME" VARCHAR2(64 BYTE), 
	"BOTTLENECK_IDENTIFIED" VARCHAR2(30 BYTE), 
	"ADVISOR_RUN_ID" NUMBER, 
	"ADVISOR_RUN_TIME" DATE, 
	"ADVISOR_RUN_REASON" VARCHAR2(4000 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(4000 BYTE), 
	"SPARE4" DATE
   ) ON COMMIT PRESERVE ROWS ;
