--------------------------------------------------------
--  DDL for Table STREAMS$_MESSAGE_CONSUMERS
--------------------------------------------------------

  CREATE TABLE "SYS"."STREAMS$_MESSAGE_CONSUMERS" SHARING=METADATA 
   (	"STREAMS_NAME" VARCHAR2(128 BYTE), 
	"QUEUE_OID" RAW(16), 
	"QUEUE_OWNER" VARCHAR2(128 BYTE), 
	"QUEUE_NAME" VARCHAR2(128 BYTE), 
	"RSET_OWNER" VARCHAR2(128 BYTE), 
	"RSET_NAME" VARCHAR2(128 BYTE), 
	"NEG_RSET_OWNER" VARCHAR2(128 BYTE), 
	"NEG_RSET_NAME" VARCHAR2(128 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" VARCHAR2(128 BYTE), 
	"SPARE5" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
