--------------------------------------------------------
--  Constraints for Table STREAMS$_APPLY_PROCESS
--------------------------------------------------------

  ALTER TABLE "SYS"."STREAMS$_APPLY_PROCESS" MODIFY ("APPLY#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."STREAMS$_APPLY_PROCESS" MODIFY ("APPLY_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."STREAMS$_APPLY_PROCESS" MODIFY ("QUEUE_OID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."STREAMS$_APPLY_PROCESS" MODIFY ("QUEUE_OWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."STREAMS$_APPLY_PROCESS" MODIFY ("QUEUE_NAME" NOT NULL ENABLE);
