--------------------------------------------------------
--  DDL for Table STREAMS$_COMPONENT_LINK_IN
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "SYS"."STREAMS$_COMPONENT_LINK_IN" SHARING=METADATA 
   (	"SOURCE_COMPONENT_ID" NUMBER, 
	"SOURCE_COMPONENT_NAME" VARCHAR2(4000 BYTE), 
	"SOURCE_COMPONENT_DB" VARCHAR2(128 BYTE), 
	"SOURCE_COMPONENT_TYPE" NUMBER, 
	"DEST_COMPONENT_ID" NUMBER, 
	"DEST_COMPONENT_NAME" VARCHAR2(4000 BYTE), 
	"DEST_COMPONENT_DB" VARCHAR2(128 BYTE), 
	"DEST_COMPONENT_TYPE" NUMBER, 
	"PATH_ID" NUMBER, 
	"POSITION" NUMBER, 
	"PATH_FLAG" RAW(4) DEFAULT '00000000', 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(4000 BYTE), 
	"SPARE4" DATE
   ) ON COMMIT PRESERVE ROWS ;
