--------------------------------------------------------
--  DDL for Table STREAMS$_APPLY_MILESTONE
--------------------------------------------------------

  CREATE TABLE "SYS"."STREAMS$_APPLY_MILESTONE" SHARING=METADATA 
   (	"APPLY#" NUMBER, 
	"SOURCE_DB_NAME" VARCHAR2(128 BYTE), 
	"OLDEST_SCN" NUMBER, 
	"COMMIT_SCN" NUMBER, 
	"SYNCH_SCN" NUMBER, 
	"EPOCH" NUMBER, 
	"PROCESSED_SCN" NUMBER, 
	"APPLY_TIME" DATE, 
	"APPLIED_MESSAGE_CREATE_TIME" DATE, 
	"SPARE1" NUMBER, 
	"START_SCN" NUMBER, 
	"OLDEST_TRANSACTION_ID" VARCHAR2(128 BYTE), 
	"SPILL_LWM_SCN" NUMBER, 
	"LWM_EXTERNAL_POS" RAW(64), 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(4000 BYTE), 
	"OLDEST_POSITION" RAW(64), 
	"SPILL_LWM_POSITION" RAW(64), 
	"PROCESSED_POSITION" RAW(64), 
	"START_POSITION" RAW(64), 
	"XOUT_PROCESSED_POSITION" RAW(64), 
	"XOUT_PROCESSED_CREATE_TIME" DATE, 
	"XOUT_PROCESSED_TID" VARCHAR2(128 BYTE), 
	"XOUT_PROCESSED_TIME" DATE, 
	"APPLIED_HIGH_POSITION" RAW(64), 
	"OLDEST_CREATE_TIME" DATE, 
	"SPILL_LWM_CREATE_TIME" DATE, 
	"SPARE4" RAW(64), 
	"SPARE5" RAW(64), 
	"SPARE6" DATE, 
	"SPARE7" DATE, 
	"SPARE8" NUMBER, 
	"SPARE9" NUMBER, 
	"SPARE10" TIMESTAMP (6), 
	"SPARE11" TIMESTAMP (6), 
	"FLAGS" NUMBER, 
	"EAGER_ERROR_RETRY" NUMBER, 
	"SOURCE_ROOT_NAME" VARCHAR2(128 BYTE), 
	"PTO_RECOVERY_SCN" NUMBER, 
	"PTO_RECOVERY_INCARNATION" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
