--------------------------------------------------------
--  Constraints for Table STREAMS$_MESSAGE_RULES
--------------------------------------------------------

  ALTER TABLE "SYS"."STREAMS$_MESSAGE_RULES" MODIFY ("STREAMS_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."STREAMS$_MESSAGE_RULES" MODIFY ("STREAMS_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."STREAMS$_MESSAGE_RULES" MODIFY ("RULE_OWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."STREAMS$_MESSAGE_RULES" MODIFY ("RULE_NAME" NOT NULL ENABLE);
