--------------------------------------------------------
--  DDL for Table STREAMS$_APPLY_PROGRESS
--------------------------------------------------------

  CREATE TABLE "SYS"."STREAMS$_APPLY_PROGRESS" SHARING=METADATA 
   (	"APPLY#" NUMBER, 
	"SOURCE_DB_NAME" VARCHAR2(128 BYTE), 
	"XIDUSN" NUMBER, 
	"XIDSLT" NUMBER, 
	"XIDSQN" NUMBER, 
	"COMMIT_SCN" NUMBER, 
	"SPARE1" NUMBER, 
	"COMMIT_POSITION" RAW(64), 
	"TRANSACTION_ID" VARCHAR2(128 BYTE)
   ) PCTFREE 0 PCTUSED 40 INITRANS 120 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
