--------------------------------------------------------
--  DDL for Sequence STREAMS$_PROPAGATION_SEQNUM
--------------------------------------------------------

   CREATE SEQUENCE  "SYS"."STREAMS$_PROPAGATION_SEQNUM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
