--------------------------------------------------------
--  DDL for Table STREAMS$_DEF_PROC
--------------------------------------------------------

  CREATE TABLE "SYS"."STREAMS$_DEF_PROC" SHARING=METADATA 
   (	"BASE_OBJ_NUM" NUMBER, 
	"FLAGS" NUMBER, 
	"OWNER" VARCHAR2(128 BYTE), 
	"PACKAGE_NAME" VARCHAR2(128 BYTE), 
	"PROCEDURE_NAME" VARCHAR2(128 BYTE), 
	"PARAM_NAME" VARCHAR2(128 BYTE), 
	"PARAM_TYPE" NUMBER, 
	"RAW_VALUE" RAW(2000), 
	"NUMBER_VALUE" NUMBER, 
	"DATE_VALUE" DATE, 
	"VARCHAR2_VALUE" VARCHAR2(4000 BYTE), 
	"NVARCHAR2_VALUE" NVARCHAR2(1000), 
	"CLOB_VALUE" CLOB, 
	"BLOB_VALUE" BLOB, 
	"NCLOB_VALUE" NCLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("CLOB_VALUE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("BLOB_VALUE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("NCLOB_VALUE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
