--------------------------------------------------------
--  DDL for Table STREAMS$_STMT_HANDLER_STMTS
--------------------------------------------------------

  CREATE TABLE "SYS"."STREAMS$_STMT_HANDLER_STMTS" SHARING=METADATA 
   (	"HANDLER_ID" NUMBER, 
	"STATEMENT" CLOB, 
	"STATEMENT_TYPE" NUMBER, 
	"EXECUTION_SEQUENCE" NUMBER, 
	"CREATION_TIME" TIMESTAMP (6), 
	"MODIFICATION_TIME" TIMESTAMP (6), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(4000 BYTE), 
	"SPARE4" VARCHAR2(4000 BYTE), 
	"SPARE5" TIMESTAMP (6), 
	"SPARE6" RAW(2000)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("STATEMENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
