--------------------------------------------------------
--  DDL for Table STREAMS$_COMPONENT_LINK
--------------------------------------------------------

  CREATE TABLE "SYS"."STREAMS$_COMPONENT_LINK" SHARING=METADATA 
   (	"SOURCE_COMPONENT_ID" NUMBER, 
	"DEST_COMPONENT_ID" NUMBER, 
	"PATH_ID" NUMBER, 
	"POSITION" NUMBER, 
	"PATH_FLAG" RAW(4) DEFAULT '00000000', 
	"ORIGINAL_PATH_ID" NUMBER DEFAULT null, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(4000 BYTE), 
	"SPARE4" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
