--------------------------------------------------------
--  DDL for Table STREAMS$_COMPONENT_STAT_IN
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "SYS"."STREAMS$_COMPONENT_STAT_IN" SHARING=METADATA 
   (	"COMPONENT_NAME" VARCHAR2(4000 BYTE), 
	"COMPONENT_DB" VARCHAR2(128 BYTE), 
	"COMPONENT_TYPE" NUMBER, 
	"STAT_TIME" DATE, 
	"COUNT1" NUMBER, 
	"COUNT2" NUMBER, 
	"COUNT3" NUMBER, 
	"COUNT4" NUMBER, 
	"LATENCY" NUMBER, 
	"STATUS" NUMBER, 
	"SNAPSHOT" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(4000 BYTE), 
	"SPARE4" DATE
   ) ON COMMIT PRESERVE ROWS ;
