--------------------------------------------------------
--  DDL for Table SUM$
--------------------------------------------------------

  CREATE TABLE "SYS"."SUM$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"CONTAINEROBJ#" NUMBER, 
	"CONTAINERTYPE" NUMBER, 
	"CONTAINERNAM" VARCHAR2(128 BYTE), 
	"FULLREFRESHTIM" NUMBER, 
	"INCREFRESHTIM" NUMBER, 
	"LASTREFRESHSCN" NUMBER, 
	"LASTREFRESHDATE" DATE, 
	"REFRESHMODE" NUMBER, 
	"PFLAGS" NUMBER, 
	"XPFLAGS" NUMBER, 
	"MFLAGS" NUMBER, 
	"NUMDETAILTAB" NUMBER(*,0), 
	"NUMAGGREGATES" NUMBER(*,0), 
	"NUMKEYCOLUMNS" NUMBER(*,0), 
	"NUMJOINS" NUMBER(*,0), 
	"NUMINLINES" NUMBER(*,0), 
	"NUMWHRNODES" NUMBER(*,0), 
	"NUMHAVNODES" NUMBER(*,0), 
	"NUMQBNODES" NUMBER(*,0), 
	"QBCMARKER" NUMBER(*,0), 
	"SUMTEXTLEN" NUMBER, 
	"SUMTEXT" LONG, 
	"FROMOFFSET" NUMBER, 
	"FROMLEN" NUMBER, 
	"METAVERSION" NUMBER, 
	"OBJCOUNT" NUMBER, 
	"MARKERDTY" NUMBER(*,0), 
	"RW_NAME" VARCHAR2(128 BYTE), 
	"SRC_STMT" CLOB, 
	"DEST_STMT" CLOB, 
	"RW_MODE" NUMBER(*,0), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" DATE, 
	"ZMAPSCALE" NUMBER, 
	"EVALEDITION#" NUMBER, 
	"UNUSABLEBEFORE#" NUMBER, 
	"UNUSABLEBEGINNING#" NUMBER, 
	"LASTREFRESHDATE_XP" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("SRC_STMT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("DEST_STMT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
