--------------------------------------------------------
--  Constraints for Table SUM$
--------------------------------------------------------

  ALTER TABLE "SYS"."SUM$" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SUM$" MODIFY ("CONTAINEROBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SUM$" MODIFY ("CONTAINERTYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SUM$" MODIFY ("FROMOFFSET" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SUM$" MODIFY ("FROMLEN" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SUM$" MODIFY ("METAVERSION" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SUM$" MODIFY ("OBJCOUNT" NOT NULL ENABLE);
