--------------------------------------------------------
--  DDL for Table SUMAGG$
--------------------------------------------------------

  CREATE TABLE "SYS"."SUMAGG$" SHARING=METADATA 
   (	"SUMOBJ#" NUMBER, 
	"SUMCOLPOS#" NUMBER, 
	"CONTAINERCOL#" NUMBER, 
	"QBCID" NUMBER, 
	"AGGFUNCTION" NUMBER(*,0), 
	"FLAGS" NUMBER, 
	"EXPRLEN" NUMBER, 
	"EXPRESSION" VARCHAR2(4000 BYTE), 
	"TEXTLEN" NUMBER, 
	"AGGTEXT" LONG, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" DATE, 
	"AGGINFO" VARCHAR2(4000 BYTE), 
	"AGGINFOLEN" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
