--------------------------------------------------------
--  Constraints for Table SUMDELTA$
--------------------------------------------------------

  ALTER TABLE "SYS"."SUMDELTA$" MODIFY ("TABLEOBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SUMDELTA$" MODIFY ("PARTITIONOBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SUMDELTA$" MODIFY ("SCN" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SUMDELTA$" MODIFY ("TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SUMDELTA$" MODIFY ("LOWROWID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SUMDELTA$" MODIFY ("HIGHROWID" NOT NULL ENABLE);
