--------------------------------------------------------
--  DDL for Table SUMDETAIL$
--------------------------------------------------------

  CREATE TABLE "SYS"."SUMDETAIL$" SHARING=METADATA 
   (	"SUMOBJ#" NUMBER, 
	"DETAILOBJ#" NUMBER, 
	"QBCID" NUMBER, 
	"DETAILOBJTYPE" NUMBER, 
	"DETAILALIAS" VARCHAR2(128 BYTE), 
	"REFRESHSCN" NUMBER, 
	"DETAILEUT" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" DATE, 
	"INLINE#" NUMBER, 
	"INSTANCE#" NUMBER, 
	"DATALESS" NUMBER, 
	"TABSCNCTR" NUMBER, 
	"FLAGS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
