--------------------------------------------------------
--  DDL for Table SUMDELTA$
--------------------------------------------------------

  CREATE TABLE "SYS"."SUMDELTA$" SHARING=METADATA 
   (	"TABLEOBJ#" NUMBER, 
	"PARTITIONOBJ#" NUMBER, 
	"DMLOPERATION" VARCHAR2(1 BYTE), 
	"SCN" NUMBER, 
	"TIMESTAMP" DATE, 
	"LOWROWID" ROWID, 
	"HIGHROWID" ROWID, 
	"SEQUENCE" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" DATE, 
	"XID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
