--------------------------------------------------------
--  DDL for Table SUMDEP$
--------------------------------------------------------

  CREATE TABLE "SYS"."SUMDEP$" SHARING=METADATA 
   (	"SUMOBJ#" NUMBER, 
	"ORDER#" NUMBER, 
	"P_OBJ#" NUMBER, 
	"P_TYPE" NUMBER, 
	"QBCID" NUMBER, 
	"P_REF_TIME" DATE, 
	"P_REF_SCN" NUMBER, 
	"FLAGS" NUMBER, 
	"INLINE#" NUMBER, 
	"INSTANCE#" NUMBER, 
	"SYN_OWN" VARCHAR2(128 BYTE), 
	"SYN_NAME" VARCHAR2(128 BYTE), 
	"SYN_MASTER" NUMBER, 
	"VW_QUERY" LONG, 
	"VW_QUERY_LEN" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
