--------------------------------------------------------
--  Constraints for Table SUMINLINE$
--------------------------------------------------------

  ALTER TABLE "SYS"."SUMINLINE$" MODIFY ("SUMOBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SUMINLINE$" MODIFY ("INLINE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SUMINLINE$" MODIFY ("TEXTSPOS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SUMINLINE$" MODIFY ("TEXTLEN" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SUMINLINE$" MODIFY ("TEXT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SUMINLINE$" MODIFY ("HASHVAL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SUMINLINE$" MODIFY ("QBCID" NOT NULL ENABLE);
