--------------------------------------------------------
--  DDL for Table SUMJOIN$
--------------------------------------------------------

  CREATE TABLE "SYS"."SUMJOIN$" SHARING=METADATA 
   (	"SUMOBJ#" NUMBER, 
	"TAB1OBJ#" NUMBER, 
	"TAB1COL#" NUMBER, 
	"TAB2OBJ#" NUMBER, 
	"TAB2COL#" NUMBER, 
	"QBCID" NUMBER, 
	"JOINOP" NUMBER(*,0), 
	"FLAGS" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" DATE, 
	"INLINE1#" NUMBER, 
	"INLINE2#" NUMBER, 
	"INSTANCE1#" NUMBER, 
	"INSTANCE2#" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
