--------------------------------------------------------
--  DDL for Table SUMPRED$
--------------------------------------------------------

  CREATE TABLE "SYS"."SUMPRED$" SHARING=METADATA 
   (	"SUMOBJ#" NUMBER, 
	"NODEID" NUMBER, 
	"PNODEID" NUMBER, 
	"CLAUSEID" NUMBER(*,0), 
	"NODETYPE" NUMBER(*,0), 
	"QBCID" NUMBER, 
	"NUMCHILD" NUMBER(*,0), 
	"RELOP" NUMBER(*,0), 
	"LOPTYPE" NUMBER(*,0), 
	"ROPTYPE" NUMBER(*,0), 
	"LDOBJ#" NUMBER, 
	"RDOBJ#" NUMBER, 
	"LCOLID" NUMBER, 
	"RCOLID" NUMBER, 
	"LAGGTYPE" NUMBER(*,0), 
	"RAGGTYPE" NUMBER(*,0), 
	"LCANOTXT" VARCHAR2(4000 BYTE), 
	"RCANOTXT" VARCHAR2(4000 BYTE), 
	"LCANOTXTLEN" NUMBER(*,0), 
	"RCANOTXTLEN" NUMBER(*,0), 
	"LTXT" VARCHAR2(4000 BYTE), 
	"RTXT" VARCHAR2(4000 BYTE), 
	"LTXTLEN" NUMBER(*,0), 
	"RTXTLEN" NUMBER(*,0), 
	"VALUE" LONG, 
	"VALUELEN" NUMBER(*,0), 
	"NUMVAL" NUMBER(*,0), 
	"COLPOS" NUMBER(*,0), 
	"LFLAGS" NUMBER, 
	"RFLAGS" NUMBER, 
	"LINLINE#" NUMBER, 
	"RINLINE#" NUMBER, 
	"LINSTANCE#" NUMBER, 
	"RINSTANCE#" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
