--------------------------------------------------------
--  Constraints for Table SUMPARTLOG$
--------------------------------------------------------

  ALTER TABLE "SYS"."SUMPARTLOG$" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SUMPARTLOG$" MODIFY ("BO#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SUMPARTLOG$" MODIFY ("HIBOUNDLEN" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SUMPARTLOG$" MODIFY ("LOBOUNDLEN" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SUMPARTLOG$" MODIFY ("TIMESTAMP" NOT NULL ENABLE);
