--------------------------------------------------------
--  DDL for Table SUMQB$
--------------------------------------------------------

  CREATE TABLE "SYS"."SUMQB$" SHARING=METADATA 
   (	"SUMOBJ#" NUMBER, 
	"NODEID" NUMBER, 
	"PFLAGS" NUMBER, 
	"XPFLAGS" NUMBER, 
	"SFLAGS" NUMBER, 
	"STATE" NUMBER, 
	"TEXT" LONG, 
	"TEXTLEN" NUMBER, 
	"MARKER" VARCHAR2(4000 BYTE), 
	"MARKERLEN" NUMBER, 
	"HASHVAL" NUMBER, 
	"HASHVAL2" NUMBER, 
	"RORDER" NUMBER, 
	"SORDER" NUMBER, 
	"LEAFCNT" NUMBER, 
	"ORIGNODE" NUMBER, 
	"PARENT" NUMBER, 
	"OPTTYP" NUMBER, 
	"SELCNT" NUMBER, 
	"FROMPO" NUMBER, 
	"FLAGS" NUMBER, 
	"NUMDETAILTAB" NUMBER(*,0), 
	"NUMAGGREGATES" NUMBER(*,0), 
	"NUMKEYCOLUMNS" NUMBER(*,0), 
	"NUMJOINS" NUMBER(*,0), 
	"NUMINLINES" NUMBER(*,0), 
	"NUMWHRNODES" NUMBER(*,0), 
	"NUMHAVNODES" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
