--------------------------------------------------------
--  Constraints for Table SVCOBJ_ACCESS$
--------------------------------------------------------

  ALTER TABLE "SYS"."SVCOBJ_ACCESS$" ADD CONSTRAINT "IDX1_SVCOBJ_ACCESS$" PRIMARY KEY ("NAME", "PDB", "TSN", "OBJID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE;
