--------------------------------------------------------
--  DDL for Table SYNCREF$_PARTN_OPS
--------------------------------------------------------

  CREATE TABLE "SYS"."SYNCREF$_PARTN_OPS" SHARING=METADATA 
   (	"TABLE_OBJ#" NUMBER, 
	"PARTITION_OP" VARCHAR2(128 BYTE), 
	"PARTITION_NAME" VARCHAR2(128 BYTE), 
	"OUTSIDE_TABLE_SCHEMA_NAME" VARCHAR2(128 BYTE), 
	"OUTSIDE_TABLE_NAME" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
