--------------------------------------------------------
--  Constraints for Table SYNCREF$_GROUP_STATUS
--------------------------------------------------------

  ALTER TABLE "SYS"."SYNCREF$_GROUP_STATUS" MODIFY ("GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYNCREF$_GROUP_STATUS" MODIFY ("CUR_RUN_FLAG" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYNCREF$_GROUP_STATUS" MODIFY ("CUR_RUN_OPN" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYNCREF$_GROUP_STATUS" MODIFY ("CUR_RUN_STATUS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYNCREF$_GROUP_STATUS" MODIFY ("NUM_PREPARE_STEPS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYNCREF$_GROUP_STATUS" MODIFY ("NUM_EXECUTE_STEPS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYNCREF$_GROUP_STATUS" MODIFY ("CURRENT_STEP" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYNCREF$_GROUP_STATUS" MODIFY ("NUM_ABORTPR_STEPS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYNCREF$_GROUP_STATUS" MODIFY ("NUM_TBLS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYNCREF$_GROUP_STATUS" MODIFY ("NUM_MVS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYNCREF$_GROUP_STATUS" MODIFY ("BASE_TBLS_REFR_STATUS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYNCREF$_GROUP_STATUS" MODIFY ("OWNER#" NOT NULL ENABLE);
