--------------------------------------------------------
--  Constraints for Table SYNCREF$_TABLE_INFO
--------------------------------------------------------

  ALTER TABLE "SYS"."SYNCREF$_TABLE_INFO" MODIFY ("TABLE_OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYNCREF$_TABLE_INFO" MODIFY ("STAGING_LOG_OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYNCREF$_TABLE_INFO" ADD PRIMARY KEY ("TABLE_OBJ#")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
