--------------------------------------------------------
--  Constraints for Table SYNCREF$_STLOG_STATS
--------------------------------------------------------

  ALTER TABLE "SYS"."SYNCREF$_STLOG_STATS" MODIFY ("TABLE_OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYNCREF$_STLOG_STATS" MODIFY ("NUM_INSERTS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYNCREF$_STLOG_STATS" MODIFY ("NUM_DELETES" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYNCREF$_STLOG_STATS" MODIFY ("NUM_UPDATES" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYNCREF$_STLOG_STATS" MODIFY ("PSL_MODE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYNCREF$_STLOG_STATS" ADD PRIMARY KEY ("TABLE_OBJ#")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
