--------------------------------------------------------
--  Constraints for Table SYNCREF$_ER_REFGRPS
--------------------------------------------------------

  ALTER TABLE "SYS"."SYNCREF$_ER_REFGRPS" MODIFY ("GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYNCREF$_ER_REFGRPS" MODIFY ("REF_GRP_NUM" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYNCREF$_ER_REFGRPS" MODIFY ("MV_OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYNCREF$_ER_REFGRPS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYNCREF$_ER_REFGRPS" MODIFY ("FIRST_STMT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYNCREF$_ER_REFGRPS" MODIFY ("LAST_STMT" NOT NULL ENABLE);
