--------------------------------------------------------
--  Constraints for Table SYNCREF$_STEP_STATUS
--------------------------------------------------------

  ALTER TABLE "SYS"."SYNCREF$_STEP_STATUS" MODIFY ("GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYNCREF$_STEP_STATUS" MODIFY ("OPERATION" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYNCREF$_STEP_STATUS" MODIFY ("STEP_SEQ_NUM" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYNCREF$_STEP_STATUS" MODIFY ("STMT_GRP_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYNCREF$_STEP_STATUS" MODIFY ("STMT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYNCREF$_STEP_STATUS" MODIFY ("STMT_STEP" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYNCREF$_STEP_STATUS" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYNCREF$_STEP_STATUS" MODIFY ("STATUS" NOT NULL ENABLE);
