--------------------------------------------------------
--  DDL for Table SYNCREF$_PARAMETERS
--------------------------------------------------------

  CREATE TABLE "SYS"."SYNCREF$_PARAMETERS" SHARING=METADATA 
   (	"PARAMETER_NAME" VARCHAR2(256 BYTE), 
	"NUM_VALUE" NUMBER, 
	"STR_VALUE" VARCHAR2(4000 BYTE), 
	"FLAGS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
