--------------------------------------------------------
--  DDL for Table SYNCREF$_GROUP_STATUS
--------------------------------------------------------

  CREATE TABLE "SYS"."SYNCREF$_GROUP_STATUS" SHARING=METADATA 
   (	"GROUP_ID" NUMBER, 
	"CUR_RUN_FLAG" NUMBER, 
	"CUR_RUN_OPN" NUMBER, 
	"CUR_RUN_STATUS" NUMBER, 
	"NUM_PREPARE_STEPS" NUMBER, 
	"NUM_EXECUTE_STEPS" NUMBER, 
	"CURRENT_STEP" NUMBER, 
	"NUM_ABORTPR_STEPS" NUMBER, 
	"NUM_TBLS" NUMBER, 
	"NUM_MVS" NUMBER, 
	"BASE_TBLS_REFR_STATUS" NUMBER, 
	"NUM_MVS_COMPLETED" NUMBER, 
	"NUM_MVS_ABORTED" NUMBER, 
	"ERROR_NUMBER" NUMBER, 
	"ERROR_MESSAGE" VARCHAR2(4000 BYTE), 
	"PREPARE_START_TIME" DATE, 
	"PREPARE_END_TIME" DATE, 
	"EXECUTE_START_TIME" DATE, 
	"EXECUTE_END_TIME" DATE, 
	"OWNER#" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
