--------------------------------------------------------
--  Constraints for Table SYS_FBA_TSFA
--------------------------------------------------------

  ALTER TABLE "SYS"."SYS_FBA_TSFA" MODIFY ("FA#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYS_FBA_TSFA" MODIFY ("TS#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYS_FBA_TSFA" MODIFY ("QUOTA" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYS_FBA_TSFA" MODIFY ("FLAGS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYS_FBA_TSFA" ADD PRIMARY KEY ("FA#", "TS#")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
