--------------------------------------------------------
--  Constraints for Table SYS_FBA_FA
--------------------------------------------------------

  ALTER TABLE "SYS"."SYS_FBA_FA" MODIFY ("FANAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYS_FBA_FA" MODIFY ("RETENTION" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYS_FBA_FA" MODIFY ("FLAGS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYS_FBA_FA" ADD PRIMARY KEY ("FA#")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYS"."SYS_FBA_FA" ADD UNIQUE ("FANAME") DISABLE;
