--------------------------------------------------------
--  DDL for Table SYS_FBA_CONTEXT_LIST
--------------------------------------------------------

  CREATE TABLE "SYS"."SYS_FBA_CONTEXT_LIST" SHARING=METADATA 
   (	"NAMESPACE" VARCHAR2(255 BYTE), 
	"PARAMETER" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
