--------------------------------------------------------
--  DDL for Table SYS_FBA_CONTEXT_AUD
--------------------------------------------------------

  CREATE TABLE "SYS"."SYS_FBA_CONTEXT_AUD" SHARING=METADATA 
   (	"XID" RAW(8), 
	"ACTION" VARCHAR2(256 BYTE), 
	"AUTHENTICATED_IDENTITY" VARCHAR2(256 BYTE), 
	"CLIENT_IDENTIFIER" VARCHAR2(256 BYTE), 
	"CLIENT_INFO" VARCHAR2(256 BYTE), 
	"CURRENT_EDITION_NAME" VARCHAR2(256 BYTE), 
	"CURRENT_SCHEMA" VARCHAR2(256 BYTE), 
	"CURRENT_USER" VARCHAR2(256 BYTE), 
	"DATABASE_ROLE" VARCHAR2(256 BYTE), 
	"DB_NAME" VARCHAR2(256 BYTE), 
	"GLOBAL_UID" VARCHAR2(256 BYTE), 
	"HOST" VARCHAR2(256 BYTE), 
	"IDENTIFICATION_TYPE" VARCHAR2(256 BYTE), 
	"INSTANCE_NAME" VARCHAR2(256 BYTE), 
	"IP_ADDRESS" VARCHAR2(256 BYTE), 
	"MODULE" VARCHAR2(256 BYTE), 
	"OS_USER" VARCHAR2(256 BYTE), 
	"SERVER_HOST" VARCHAR2(256 BYTE), 
	"SERVICE_NAME" VARCHAR2(256 BYTE), 
	"SESSION_EDITION_NAME" VARCHAR2(256 BYTE), 
	"SESSION_USER" VARCHAR2(256 BYTE), 
	"SESSION_USERID" VARCHAR2(256 BYTE), 
	"SESSIONID" VARCHAR2(256 BYTE), 
	"TERMINAL" VARCHAR2(256 BYTE), 
	"SPARE" VARCHAR2(256 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
