--------------------------------------------------------
--  Constraints for Table SYS_FBA_BARRIERSCN
--------------------------------------------------------

  ALTER TABLE "SYS"."SYS_FBA_BARRIERSCN" MODIFY ("INST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYS_FBA_BARRIERSCN" MODIFY ("BARRIERSCN" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYS_FBA_BARRIERSCN" MODIFY ("ACTIVESCN" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYS_FBA_BARRIERSCN" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."SYS_FBA_BARRIERSCN" ADD UNIQUE ("INST_ID") DISABLE;
