--------------------------------------------------------
--  DDL for Table SYSAUTH$
--------------------------------------------------------

  CREATE TABLE "SYS"."SYSAUTH$" SHARING=METADATA 
   (	"GRANTEE#" NUMBER, 
	"PRIVILEGE#" NUMBER, 
	"SEQUENCE#" NUMBER, 
	"OPTION$" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  GRANT SELECT ON "SYS"."SYSAUTH$" TO "CTXSYS";
  GRANT READ ON "SYS"."SYSAUTH$" TO "DVSYS";
  GRANT READ ON "SYS"."SYSAUTH$" TO "DV_SECANALYST";
