REM INSERTING into SYS.SYSDBIMFS_METADATA$
SET DEFINE OFF;
Insert into SYS.SYSDBIMFS_METADATA$ (KEY,VALUE) values ('STATUS','DISABLE');
Insert into SYS.SYSDBIMFS_METADATA$ (KEY,VALUE) values ('TSN','-1');
Insert into SYS.SYSDBIMFS_METADATA$ (KEY,VALUE) values ('SCHEMA_VER','2');
