--------------------------------------------------------
--  Ref Constraints for Table SYSDBIMFSDBA$
--------------------------------------------------------

  ALTER TABLE "SYS"."SYSDBIMFSDBA$" ADD CONSTRAINT "SYSDBIMFSDBA_CUID_REF$" FOREIGN KEY ("CUID")
	  REFERENCES "SYS"."SYSDBIMFS$" ("CUID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SYS"."SYSDBIMFSDBA$" ADD CONSTRAINT "SYSDBIMFSDBA_SEGID_REF$" FOREIGN KEY ("SEGID")
	  REFERENCES "SYS"."SYSDBIMFSSEG$" ("SEGID") ON DELETE CASCADE ENABLE;
