--------------------------------------------------------
--  DDL for Table SYSDBIMFS$
--------------------------------------------------------

  CREATE TABLE "SYS"."SYSDBIMFS$" SHARING=METADATA 
   (	"CUID" NUMBER, 
	"SEGID" NUMBER, 
	"STARTDBA" NUMBER, 
	"SCN" NUMBER, 
	"VALID" CHAR(1 BYTE) DEFAULT 'T', 
	"VER" NUMBER, 
	"ALN" NUMBER, 
	"EPAD" NUMBER, 
	"FLGS" NUMBER DEFAULT 0, 
	"ENDNESS" CHAR(1 BYTE), 
	"CREATED" TIMESTAMP (6) DEFAULT systimestamp, 
	"LASTREAD" TIMESTAMP (6) DEFAULT systimestamp, 
	"RSCN" NUMBER, 
	"LSCN" NUMBER, 
	"IMCUFLGS" NUMBER DEFAULT 0, 
	"SPARE1" NUMBER DEFAULT 0, 
	"SPARE2" NUMBER DEFAULT 0, 
	"SPARE3" NUMBER DEFAULT 0, 
	"SPARE4" NUMBER DEFAULT 0, 
	"SPARE5" NUMBER DEFAULT 0, 
	"VERSION" NUMBER DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
