--------------------------------------------------------
--  DDL for Table TAB_STATS$
--------------------------------------------------------

  CREATE TABLE "SYS"."TAB_STATS$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"CACHEDBLK" NUMBER, 
	"CACHEHIT" NUMBER, 
	"LOGICALREAD" NUMBER, 
	"ROWCNT" NUMBER, 
	"BLKCNT" NUMBER, 
	"EMPCNT" NUMBER, 
	"AVGSPC" NUMBER, 
	"CHNCNT" NUMBER, 
	"AVGRLN" NUMBER, 
	"AVGSPC_FLB" NUMBER, 
	"FLBCNT" NUMBER, 
	"ANALYZETIME" DATE, 
	"SAMPLESIZE" NUMBER, 
	"FLAGS" NUMBER, 
	"IM_IMCU_COUNT" NUMBER, 
	"IM_BLOCK_COUNT" NUMBER, 
	"IM_SYS_INCARNATION" NUMBER, 
	"IM_STAT_UPDATE_TIME" TIMESTAMP (6), 
	"SCANRATE" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" VARCHAR2(1000 BYTE), 
	"SPARE5" VARCHAR2(1000 BYTE), 
	"SPARE6" TIMESTAMP (6) WITH TIME ZONE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 32768 NEXT 106496 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
