--------------------------------------------------------
--  DDL for Table TAB$
--------------------------------------------------------

  CREATE TABLE "SYS"."TAB$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"DATAOBJ#" NUMBER, 
	"TS#" NUMBER, 
	"FILE#" NUMBER, 
	"BLOCK#" NUMBER, 
	"BOBJ#" NUMBER, 
	"TAB#" NUMBER, 
	"COLS" NUMBER, 
	"CLUCOLS" NUMBER, 
	"PCTFREE$" NUMBER, 
	"PCTUSED$" NUMBER, 
	"INITRANS" NUMBER, 
	"MAXTRANS" NUMBER, 
	"FLAGS" NUMBER, 
	"AUDIT$" VARCHAR2(38 BYTE), 
	"ROWCNT" NUMBER, 
	"BLKCNT" NUMBER, 
	"EMPCNT" NUMBER, 
	"AVGSPC" NUMBER, 
	"CHNCNT" NUMBER, 
	"AVGRLN" NUMBER, 
	"AVGSPC_FLB" NUMBER, 
	"FLBCNT" NUMBER, 
	"ANALYZETIME" DATE, 
	"SAMPLESIZE" NUMBER, 
	"DEGREE" NUMBER, 
	"INSTANCES" NUMBER, 
	"INTCOLS" NUMBER, 
	"KERNELCOLS" NUMBER, 
	"PROPERTY" NUMBER, 
	"TRIGFLAG" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" VARCHAR2(1000 BYTE), 
	"SPARE5" VARCHAR2(1000 BYTE), 
	"SPARE6" DATE, 
	"SPARE7" NUMBER, 
	"SPARE8" NUMBER, 
	"SPARE9" VARCHAR2(1000 BYTE), 
	"SPARE10" VARCHAR2(1000 BYTE), 
	"ACDRFLAGS" NUMBER, 
	"ACDRTSOBJ#" NUMBER, 
	"ACDRDEFAULTTIME" TIMESTAMP (6), 
	"ACDRROWTSINTCOL#" NUMBER
   ) CLUSTER "SYS"."C_OBJ#" ("OBJ#");
  GRANT SELECT ON "SYS"."TAB$" TO "CTXSYS";
  GRANT READ ON "SYS"."TAB$" TO "DVSYS";
  GRANT READ ON "SYS"."TAB$" TO "DV_SECANALYST";
