--------------------------------------------------------
--  Constraints for Table TAB$
--------------------------------------------------------

  ALTER TABLE "SYS"."TAB$" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TAB$" MODIFY ("TS#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TAB$" MODIFY ("FILE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TAB$" MODIFY ("BLOCK#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TAB$" MODIFY ("COLS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TAB$" MODIFY ("PCTFREE$" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TAB$" MODIFY ("PCTUSED$" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TAB$" MODIFY ("INITRANS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TAB$" MODIFY ("MAXTRANS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TAB$" MODIFY ("FLAGS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TAB$" MODIFY ("AUDIT$" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TAB$" MODIFY ("INTCOLS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TAB$" MODIFY ("KERNELCOLS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TAB$" MODIFY ("PROPERTY" NOT NULL ENABLE);
