--------------------------------------------------------
--  Constraints for Table TABCOMPART$
--------------------------------------------------------

  ALTER TABLE "SYS"."TABCOMPART$" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TABCOMPART$" MODIFY ("BO#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TABCOMPART$" MODIFY ("PART#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TABCOMPART$" MODIFY ("HIBOUNDLEN" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TABCOMPART$" MODIFY ("SUBPARTCNT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TABCOMPART$" MODIFY ("FLAGS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TABCOMPART$" MODIFY ("DEFPCTFREE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TABCOMPART$" MODIFY ("DEFPCTUSED" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TABCOMPART$" MODIFY ("DEFINITRANS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TABCOMPART$" MODIFY ("DEFMAXTRANS" NOT NULL ENABLE);
