REM INSERTING into SYS.TABCOMPART$
SET DEFINE OFF;
Insert into SYS.TABCOMPART$ (OBJ#,DATAOBJ#,BO#,PART#,HIBOUNDLEN,HIBOUNDVAL,SUBPARTCNT,FLAGS,DEFTS#,DEFPCTFREE,DEFPCTUSED,DEFINITRANS,DEFMAXTRANS,DEFINIEXTS,DEFEXTSIZE,DEFMINEXTS,DEFMAXEXTS,DEFEXTPCT,DEFLISTS,DEFGROUPS,DEFLOGGING,DEFBUFPOOL,ANALYZETIME,SAMPLESIZE,ROWCNT,BLKCNT,EMPCNT,AVGSPC,CHNCNT,AVGRLN,SPARE1,SPARE2,SPARE3,DEFMAXSIZE) values (14821,null,14820,10,1,'0',32,18,1,1,40,1,255,null,null,null,null,null,null,null,0,0,to_date('30-MAY-19','DD-MON-RR'),null,0,0,0,0,0,0,null,0,null,null);
