--------------------------------------------------------
--  Constraints for Table TABPART$
--------------------------------------------------------

  ALTER TABLE "SYS"."TABPART$" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TABPART$" MODIFY ("BO#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TABPART$" MODIFY ("PART#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TABPART$" MODIFY ("HIBOUNDLEN" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TABPART$" MODIFY ("PCTFREE$" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TABPART$" MODIFY ("PCTUSED$" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TABPART$" MODIFY ("INITRANS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TABPART$" MODIFY ("MAXTRANS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TABPART$" MODIFY ("FLAGS" NOT NULL ENABLE);
