--------------------------------------------------------
--  DDL for Table TABPART$
--------------------------------------------------------

  CREATE TABLE "SYS"."TABPART$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"DATAOBJ#" NUMBER, 
	"BO#" NUMBER, 
	"PART#" NUMBER, 
	"HIBOUNDLEN" NUMBER, 
	"HIBOUNDVAL" LONG, 
	"TS#" NUMBER, 
	"FILE#" NUMBER, 
	"BLOCK#" NUMBER, 
	"PCTFREE$" NUMBER, 
	"PCTUSED$" NUMBER, 
	"INITRANS" NUMBER, 
	"MAXTRANS" NUMBER, 
	"FLAGS" NUMBER, 
	"ANALYZETIME" DATE, 
	"SAMPLESIZE" NUMBER, 
	"ROWCNT" NUMBER, 
	"BLKCNT" NUMBER, 
	"EMPCNT" NUMBER, 
	"AVGSPC" NUMBER, 
	"CHNCNT" NUMBER, 
	"AVGRLN" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"BHIBOUNDVAL" BLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("BHIBOUNDVAL") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  GRANT READ ON "SYS"."TABPART$" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."TABPART$" TO "GSMADMIN_INTERNAL";
  GRANT SELECT ON "SYS"."TABPART$" TO "CTXSYS";
