--------------------------------------------------------
--  Constraints for Table TABSUBPART$
--------------------------------------------------------

  ALTER TABLE "SYS"."TABSUBPART$" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TABSUBPART$" MODIFY ("POBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TABSUBPART$" MODIFY ("SUBPART#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TABSUBPART$" MODIFY ("FLAGS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TABSUBPART$" MODIFY ("TS#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TABSUBPART$" MODIFY ("FILE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TABSUBPART$" MODIFY ("BLOCK#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TABSUBPART$" MODIFY ("PCTFREE$" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TABSUBPART$" MODIFY ("PCTUSED$" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TABSUBPART$" MODIFY ("INITRANS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TABSUBPART$" MODIFY ("MAXTRANS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TABSUBPART$" MODIFY ("HIBOUNDLEN" NOT NULL ENABLE);
