--------------------------------------------------------
--  DDL for Table TRANSFORMATIONS$
--------------------------------------------------------

  CREATE TABLE "SYS"."TRANSFORMATIONS$" SHARING=METADATA 
   (	"TRANSFORMATION_ID" NUMBER, 
	"OWNER" VARCHAR2(128 BYTE), 
	"NAME" VARCHAR2(128 BYTE), 
	"FROM_SCHEMA" VARCHAR2(128 BYTE), 
	"FROM_TYPE" VARCHAR2(128 BYTE), 
	"FROM_TOID" RAW(16), 
	"FROM_VERSION" NUMBER, 
	"TO_SCHEMA" VARCHAR2(128 BYTE), 
	"TO_TYPE" VARCHAR2(256 BYTE), 
	"TO_TOID" RAW(16), 
	"TO_VERSION" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
