--------------------------------------------------------
--  DDL for Table TRANSACTION_BACKOUT_REPORT$
--------------------------------------------------------

  CREATE TABLE "SYS"."TRANSACTION_BACKOUT_REPORT$" SHARING=METADATA 
   (	"COMPENSATING_XID" RAW(8), 
	"COMPENSATING_TXN_NAME" VARCHAR2(256 BYTE), 
	"COMMIT_TIME" DATE, 
	"XID_REPORT" CLOB, 
	"USER#" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" 
 LOB ("XID_REPORT") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
