--------------------------------------------------------
--  Constraints for Table TRANSFORMATIONS$
--------------------------------------------------------

  ALTER TABLE "SYS"."TRANSFORMATIONS$" MODIFY ("TRANSFORMATION_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TRANSFORMATIONS$" MODIFY ("OWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TRANSFORMATIONS$" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TRANSFORMATIONS$" MODIFY ("FROM_TOID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TRANSFORMATIONS$" MODIFY ("FROM_VERSION" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TRANSFORMATIONS$" MODIFY ("TO_TOID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TRANSFORMATIONS$" MODIFY ("TO_VERSION" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TRANSFORMATIONS$" ADD PRIMARY KEY ("TRANSFORMATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
