--------------------------------------------------------
--  Constraints for Table TRIGGERJAVAC$
--------------------------------------------------------

  ALTER TABLE "SYS"."TRIGGERJAVAC$" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TRIGGERJAVAC$" MODIFY ("OWNERNAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TRIGGERJAVAC$" MODIFY ("OWNERLENGTH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TRIGGERJAVAC$" MODIFY ("CLASSNAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TRIGGERJAVAC$" MODIFY ("CLASSLENGTH" NOT NULL ENABLE);
