--------------------------------------------------------
--  DDL for Table TRIGGER$
--------------------------------------------------------

  CREATE TABLE "SYS"."TRIGGER$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"TYPE#" NUMBER, 
	"UPDATE$" NUMBER, 
	"INSERT$" NUMBER, 
	"DELETE$" NUMBER, 
	"BASEOBJECT" NUMBER, 
	"REFOLDNAME" VARCHAR2(128 BYTE), 
	"REFNEWNAME" VARCHAR2(128 BYTE), 
	"DEFINITION" VARCHAR2(4000 BYTE), 
	"WHENCLAUSE" VARCHAR2(4000 BYTE), 
	"ACTION#" LONG, 
	"ACTIONSIZE" NUMBER, 
	"ENABLED" NUMBER, 
	"PROPERTY" NUMBER, 
	"SYS_EVTS" NUMBER, 
	"NTTRIGCOL" NUMBER, 
	"NTTRIGATT" NUMBER, 
	"REFPRTNAME" VARCHAR2(128 BYTE), 
	"ACTIONLINENO" NUMBER, 
	"TRIGNAMELINE" NUMBER, 
	"TRIGNAMECOL" NUMBER, 
	"TRIGNAMECOLOFS" NUMBER, 
	"ACTIONCOLNO" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
