--------------------------------------------------------
--  Constraints for Table TRIGGER$
--------------------------------------------------------

  ALTER TABLE "SYS"."TRIGGER$" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TRIGGER$" MODIFY ("TYPE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TRIGGER$" MODIFY ("UPDATE$" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TRIGGER$" MODIFY ("INSERT$" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TRIGGER$" MODIFY ("DELETE$" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TRIGGER$" MODIFY ("BASEOBJECT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TRIGGER$" MODIFY ("PROPERTY" NOT NULL ENABLE);
