--------------------------------------------------------
--  DDL for Table TS$
--------------------------------------------------------

  CREATE TABLE "SYS"."TS$" SHARING=METADATA 
   (	"TS#" NUMBER, 
	"NAME" VARCHAR2(30 BYTE), 
	"OWNER#" NUMBER, 
	"ONLINE$" NUMBER, 
	"CONTENTS$" NUMBER, 
	"UNDOFILE#" NUMBER, 
	"UNDOBLOCK#" NUMBER, 
	"BLOCKSIZE" NUMBER, 
	"INC#" NUMBER, 
	"SCNWRP" NUMBER, 
	"SCNBAS" NUMBER, 
	"DFLMINEXT" NUMBER, 
	"DFLMAXEXT" NUMBER, 
	"DFLINIT" NUMBER, 
	"DFLINCR" NUMBER, 
	"DFLMINLEN" NUMBER, 
	"DFLEXTPCT" NUMBER, 
	"DFLOGGING" NUMBER, 
	"AFFSTRENGTH" NUMBER, 
	"BITMAPPED" NUMBER, 
	"PLUGGED" NUMBER, 
	"DIRECTALLOWED" NUMBER, 
	"FLAGS" NUMBER, 
	"PITRSCNWRP" NUMBER, 
	"PITRSCNBAS" NUMBER, 
	"OWNERINSTANCE" VARCHAR2(30 BYTE), 
	"BACKUPOWNER" VARCHAR2(30 BYTE), 
	"GROUPNAME" VARCHAR2(30 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(1000 BYTE), 
	"SPARE4" DATE
   ) CLUSTER "SYS"."C_TS#" ("TS#");
  GRANT SELECT ON "SYS"."TS$" TO "ORACLE_OCM";
  GRANT READ ON "SYS"."TS$" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."TS$" TO "CTXSYS";
