--------------------------------------------------------
--  Constraints for Table TS$
--------------------------------------------------------

  ALTER TABLE "SYS"."TS$" MODIFY ("TS#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TS$" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TS$" MODIFY ("OWNER#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TS$" MODIFY ("ONLINE$" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TS$" MODIFY ("CONTENTS$" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TS$" MODIFY ("BLOCKSIZE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TS$" MODIFY ("INC#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TS$" MODIFY ("DFLMINEXT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TS$" MODIFY ("DFLMAXEXT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TS$" MODIFY ("DFLINIT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TS$" MODIFY ("DFLINCR" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TS$" MODIFY ("DFLMINLEN" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TS$" MODIFY ("DFLEXTPCT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TS$" MODIFY ("DFLOGGING" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TS$" MODIFY ("AFFSTRENGTH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TS$" MODIFY ("BITMAPPED" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TS$" MODIFY ("PLUGGED" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TS$" MODIFY ("DIRECTALLOWED" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TS$" MODIFY ("FLAGS" NOT NULL ENABLE);
