--------------------------------------------------------
--  Ref Constraints for Table TSDP_PROTECTION$
--------------------------------------------------------

  ALTER TABLE "SYS"."TSDP_PROTECTION$" ADD CONSTRAINT "TSDP_PROTECTION$FKSD" FOREIGN KEY ("SENSITIVE#")
	  REFERENCES "SYS"."TSDP_SENSITIVE_DATA$" ("SENSITIVE#") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SYS"."TSDP_PROTECTION$" ADD CONSTRAINT "TSDP_PROTECTION$FKPC" FOREIGN KEY ("SUBPOL#")
	  REFERENCES "SYS"."TSDP_SUBPOL$" ("SUBPOL#") ON DELETE CASCADE ENABLE;
