--------------------------------------------------------
--  Constraints for Table TSDP_SENSITIVE_DATA$
--------------------------------------------------------

  ALTER TABLE "SYS"."TSDP_SENSITIVE_DATA$" MODIFY ("SENSITIVE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TSDP_SENSITIVE_DATA$" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TSDP_SENSITIVE_DATA$" MODIFY ("COL_ARGUMENT#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TSDP_SENSITIVE_DATA$" ADD CONSTRAINT "TSDP_SENSITIVE_DATA$PK" PRIMARY KEY ("SENSITIVE#")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYS"."TSDP_SENSITIVE_DATA$" ADD CONSTRAINT "TSDP_SENSITIVE_DATA$UK" UNIQUE ("OBJ#", "COL_ARGUMENT#", "PROCEDURE#") DISABLE;
