--------------------------------------------------------
--  Ref Constraints for Table TSDP_ASSOCIATION$
--------------------------------------------------------

  ALTER TABLE "SYS"."TSDP_ASSOCIATION$" ADD CONSTRAINT "TSDP_ASSOCIATION$FKST" FOREIGN KEY ("SENSITIVE_TYPE#")
	  REFERENCES "SYS"."TSDP_SENSITIVE_TYPE$" ("TYPE#") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SYS"."TSDP_ASSOCIATION$" ADD CONSTRAINT "TSDP_ASSOCIATION$FKPO" FOREIGN KEY ("POLICY#")
	  REFERENCES "SYS"."TSDP_POLICY$" ("POLICY#") ON DELETE CASCADE ENABLE;
