--------------------------------------------------------
--  Constraints for Table TSDP_SENSITIVE_TYPE$
--------------------------------------------------------

  ALTER TABLE "SYS"."TSDP_SENSITIVE_TYPE$" MODIFY ("TYPE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TSDP_SENSITIVE_TYPE$" ADD CONSTRAINT "TSDP_SENSITIVE_TYPE$PK" PRIMARY KEY ("TYPE#")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYS"."TSDP_SENSITIVE_TYPE$" ADD CONSTRAINT "TSDP_SENSITIVE_TYPE$UK" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
