--------------------------------------------------------
--  Constraints for Table TSDP_FEATURE_POLICY$
--------------------------------------------------------

  ALTER TABLE "SYS"."TSDP_FEATURE_POLICY$" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TSDP_FEATURE_POLICY$" MODIFY ("SEC_FEATURE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TSDP_FEATURE_POLICY$" ADD CONSTRAINT "TSDP_FEATURE_POLICY$PK" PRIMARY KEY ("OBJ#", "FEATURE_POLNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
