--------------------------------------------------------
--  Constraints for Table TSDP_PROTECTION$
--------------------------------------------------------

  ALTER TABLE "SYS"."TSDP_PROTECTION$" MODIFY ("PROTECTION#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TSDP_PROTECTION$" MODIFY ("SENSITIVE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TSDP_PROTECTION$" MODIFY ("SUBPOL#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TSDP_PROTECTION$" ADD CONSTRAINT "TSDP_PROTECTION$PK" PRIMARY KEY ("PROTECTION#")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
