--------------------------------------------------------
--  Constraints for Table TSDP_SOURCE$
--------------------------------------------------------

  ALTER TABLE "SYS"."TSDP_SOURCE$" MODIFY ("SOURCE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TSDP_SOURCE$" ADD CONSTRAINT "TSDP_SOURCE$PK" PRIMARY KEY ("SOURCE#")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYS"."TSDP_SOURCE$" ADD CONSTRAINT "TSDP_SOURCE$UK" UNIQUE ("NAME", "TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
