--------------------------------------------------------
--  DDL for Table TSDP_SENSITIVE_DATA$
--------------------------------------------------------

  CREATE TABLE "SYS"."TSDP_SENSITIVE_DATA$" SHARING=METADATA 
   (	"SENSITIVE#" NUMBER, 
	"OBJ#" NUMBER, 
	"COL_ARGUMENT#" NUMBER, 
	"PROCEDURE#" NUMBER, 
	"SENSITIVE_TYPE" VARCHAR2(128 BYTE), 
	"USER_COMMENT" VARCHAR2(4000 BYTE), 
	"SOURCE#" NUMBER, 
	"TS" TIMESTAMP (6), 
	"PROPERTY" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
  GRANT SELECT ON "SYS"."TSDP_SENSITIVE_DATA$" TO "SELECT_CATALOG_ROLE";
