--------------------------------------------------------
--  Constraints for Table TSDP_ASSOCIATION$
--------------------------------------------------------

  ALTER TABLE "SYS"."TSDP_ASSOCIATION$" MODIFY ("ASSOCIATION#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TSDP_ASSOCIATION$" MODIFY ("POLICY#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TSDP_ASSOCIATION$" MODIFY ("SENSITIVE_TYPE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TSDP_ASSOCIATION$" ADD CONSTRAINT "TSDP_ASSOCIATION$PK" PRIMARY KEY ("ASSOCIATION#")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
