--------------------------------------------------------
--  Constraints for Table TSDP_SUBPOL$
--------------------------------------------------------

  ALTER TABLE "SYS"."TSDP_SUBPOL$" MODIFY ("SUBPOL#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TSDP_SUBPOL$" MODIFY ("POLICY#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TSDP_SUBPOL$" MODIFY ("SUBPOLNUM" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TSDP_SUBPOL$" ADD CONSTRAINT "TSDP_SUBPOL$PK" PRIMARY KEY ("SUBPOL#")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
