--------------------------------------------------------
--  DDL for Table TSM_SRC$
--------------------------------------------------------

  CREATE TABLE "SYS"."TSM_SRC$" SHARING=METADATA 
   (	"SRC_DB_NAME" VARCHAR2(4000 BYTE), 
	"SRC_INST_NAME" VARCHAR2(4000 BYTE), 
	"SRC_INST_ID" VARCHAR2(4000 BYTE), 
	"SRC_INST_START_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"SEQUENCE#" NUMBER, 
	"SRC_SID" NUMBER, 
	"SRC_SERIAL#" NUMBER, 
	"SRC_STATE" NUMBER, 
	"CONNECT_STRING" VARCHAR2(4000 BYTE), 
	"SRC_START_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"COST" NUMBER, 
	"FAILURE_REASON" NUMBER, 
	"SRC_END_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"ROUNDTRIPS" NUMBER, 
	"SRC_USERID" NUMBER, 
	"SRC_SCHEMAID" NUMBER, 
	"DST_DB_NAME" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
