--------------------------------------------------------
--  DDL for Table TSM_DST$
--------------------------------------------------------

  CREATE TABLE "SYS"."TSM_DST$" SHARING=METADATA 
   (	"SRC_DB_NAME" VARCHAR2(4000 BYTE), 
	"DST_DB_NAME" VARCHAR2(4000 BYTE), 
	"DST_INST_NAME" VARCHAR2(4000 BYTE), 
	"DST_INST_ID" VARCHAR2(4000 BYTE), 
	"DST_INST_START_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"SEQUENCE#" NUMBER, 
	"DST_SID" NUMBER, 
	"DST_SERIAL#" NUMBER, 
	"DST_START_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"DST_END_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"DST_USERID" NUMBER, 
	"DST_SCHEMAID" NUMBER, 
	"DST_STATE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
