--------------------------------------------------------
--  DDL for Table TYPE$
--------------------------------------------------------

  CREATE TABLE "SYS"."TYPE$" SHARING=METADATA 
   (	"TOID" RAW(16), 
	"VERSION#" NUMBER, 
	"VERSION" VARCHAR2(128 BYTE), 
	"TVOID" RAW(16), 
	"TYPECODE" NUMBER, 
	"PROPERTIES" NUMBER, 
	"ATTRIBUTES" NUMBER, 
	"METHODS" NUMBER, 
	"HIDDENMETHODS" NUMBER, 
	"SUPERTYPES" NUMBER, 
	"SUBTYPES" NUMBER, 
	"EXTERNTYPE" NUMBER, 
	"EXTERNNAME" VARCHAR2(4000 BYTE), 
	"HELPERCLASSNAME" VARCHAR2(4000 BYTE), 
	"LOCAL_ATTRS" NUMBER, 
	"LOCAL_METHODS" NUMBER, 
	"TYPEID" RAW(16), 
	"ROOTTOID" RAW(16), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SUPERTOID" RAW(16), 
	"HASHCODE" RAW(17), 
	"TYP_NAME" VARCHAR2(128 BYTE), 
	"PACKAGE_OBJ#" NUMBER
   ) CLUSTER "SYS"."C_TOID_VERSION#" ("TOID", "VERSION#");
