--------------------------------------------------------
--  DDL for Table TYPED_VIEW$
--------------------------------------------------------

  CREATE TABLE "SYS"."TYPED_VIEW$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"TYPEOWNER" VARCHAR2(128 BYTE), 
	"TYPENAME" VARCHAR2(128 BYTE), 
	"TYPETEXTLENGTH" NUMBER, 
	"TYPETEXT" VARCHAR2(4000 BYTE), 
	"OIDTEXTLENGTH" NUMBER, 
	"OIDTEXT" VARCHAR2(4000 BYTE), 
	"TRANSTEXTLENGTH" NUMBER, 
	"TRANSTEXT" LONG, 
	"UNDERTEXTLENGTH" NUMBER, 
	"UNDERTEXT" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
