--------------------------------------------------------
--  Constraints for Table UMF$_REGISTRATION
--------------------------------------------------------

  ALTER TABLE "SYS"."UMF$_REGISTRATION" MODIFY ("TOPOLOGY_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."UMF$_REGISTRATION" MODIFY ("NODE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."UMF$_REGISTRATION" MODIFY ("NODE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."UMF$_REGISTRATION" MODIFY ("NODE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."UMF$_REGISTRATION" MODIFY ("AS_SOURCE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."UMF$_REGISTRATION" MODIFY ("AS_CANDIDATE_TARGET" NOT NULL ENABLE);
  ALTER TABLE "SYS"."UMF$_REGISTRATION" MODIFY ("STATE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."UMF$_REGISTRATION" ADD CONSTRAINT "UMF$_REGISTRATION_PK" PRIMARY KEY ("TOPOLOGY_NAME", "NODE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
  ALTER TABLE "SYS"."UMF$_REGISTRATION" ADD CONSTRAINT "UMF$_REGISTRATION_UNIQUE" UNIQUE ("NODE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
