--------------------------------------------------------
--  DDL for Table UMF$_SERVICE
--------------------------------------------------------

  CREATE TABLE "SYS"."UMF$_SERVICE" SHARING=METADATA 
   (	"TOPOLOGY_NAME" VARCHAR2(128 BYTE), 
	"NODE_ID" NUMBER, 
	"SERVICE_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."UMF$_SERVICE" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."UMF$_SERVICE" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."UMF$_SERVICE" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."UMF$_SERVICE" TO "SYSUMF_ROLE";
