--------------------------------------------------------
--  DDL for Table UMF$_REGISTRATION
--------------------------------------------------------

  CREATE TABLE "SYS"."UMF$_REGISTRATION" SHARING=METADATA 
   (	"TOPOLOGY_NAME" VARCHAR2(128 BYTE), 
	"NODE_NAME" VARCHAR2(128 BYTE), 
	"NODE_ID" NUMBER, 
	"NODE_TYPE" NUMBER, 
	"AS_SOURCE" NUMBER, 
	"AS_CANDIDATE_TARGET" NUMBER, 
	"STATE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."UMF$_REGISTRATION" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."UMF$_REGISTRATION" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."UMF$_REGISTRATION" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."UMF$_REGISTRATION" TO "SYSUMF_ROLE";
