--------------------------------------------------------
--  Constraints for Table UMF$_LINK
--------------------------------------------------------

  ALTER TABLE "SYS"."UMF$_LINK" MODIFY ("TOPOLOGY_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."UMF$_LINK" MODIFY ("FROM_NODE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."UMF$_LINK" MODIFY ("TO_NODE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."UMF$_LINK" MODIFY ("LINK_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."UMF$_LINK" ADD CONSTRAINT "UMF$_LINK_PK" PRIMARY KEY ("TOPOLOGY_NAME", "FROM_NODE_ID", "TO_NODE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
