GRANT DELETE ON "SYS"."UMF$_LINK_XML" TO "SYS$UMF";
  GRANT INSERT ON "SYS"."UMF$_LINK_XML" TO "SYS$UMF";
  GRANT SELECT ON "SYS"."UMF$_LINK_XML" TO "SYS$UMF";
  GRANT UPDATE ON "SYS"."UMF$_LINK_XML" TO "SYS$UMF";
  GRANT SELECT ON "SYS"."UMF$_LINK_XML" TO "SELECT_CATALOG_ROLE";
