--------------------------------------------------------
--  DDL for Table UMF$_LINK
--------------------------------------------------------

  CREATE TABLE "SYS"."UMF$_LINK" SHARING=METADATA 
   (	"TOPOLOGY_NAME" VARCHAR2(128 BYTE), 
	"FROM_NODE_ID" NUMBER, 
	"TO_NODE_ID" NUMBER, 
	"LINK_NAME" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."UMF$_LINK" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."UMF$_LINK" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."UMF$_LINK" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."UMF$_LINK" TO "SYSUMF_ROLE";
