GRANT SELECT ON "SYS"."UMF_SCHEMA_XMLTYPE" TO "SELECT_CATALOG_ROLE";
  GRANT DELETE ON "SYS"."UMF_SCHEMA_XMLTYPE" TO "SYS$UMF";
  GRANT INSERT ON "SYS"."UMF_SCHEMA_XMLTYPE" TO "SYS$UMF";
  GRANT SELECT ON "SYS"."UMF_SCHEMA_XMLTYPE" TO "SYS$UMF";
  GRANT UPDATE ON "SYS"."UMF_SCHEMA_XMLTYPE" TO "SYS$UMF";
