--------------------------------------------------------
--  DDL for Table UMF$_TOPOLOGY
--------------------------------------------------------

  CREATE TABLE "SYS"."UMF$_TOPOLOGY" SHARING=METADATA 
   (	"TOPOLOGY_NAME" VARCHAR2(128 BYTE), 
	"TARGET_ID" NUMBER, 
	"TOPOLOGY_VERSION" NUMBER, 
	"TOPOLOGY_STATE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."UMF$_TOPOLOGY" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."UMF$_TOPOLOGY" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."UMF$_TOPOLOGY" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."UMF$_TOPOLOGY" TO "SYSUMF_ROLE";
