--------------------------------------------------------
--  DDL for Table UNDOHIST$
--------------------------------------------------------

  CREATE TABLE "SYS"."UNDOHIST$" SHARING=METADATA 
   (	"US#" NUMBER, 
	"INC#" NUMBER, 
	"TSN" NUMBER, 
	"FILE#" NUMBER, 
	"BLOCK#" NUMBER, 
	"CRSCNWRP" NUMBER, 
	"CRSCNBAS" NUMBER, 
	"DRSCNWRP" NUMBER, 
	"DRSCNBAS" NUMBER, 
	"CRTTIME" NUMBER, 
	"DRPTIME" NUMBER, 
	"NAME" VARCHAR2(30 BYTE), 
	"USER#" NUMBER, 
	"SCNWRP" NUMBER, 
	"SCNBAS" NUMBER, 
	"XACTSQN" NUMBER, 
	"UNDOSQN" NUMBER, 
	"INST#" NUMBER, 
	"FLAGS1" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" NUMBER, 
	"SPARE5" NUMBER, 
	"SPARE6" NUMBER, 
	"SPARE7" NUMBER, 
	"SPARE8" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
