--------------------------------------------------------
--  Constraints for Table UNDOHIST$
--------------------------------------------------------

  ALTER TABLE "SYS"."UNDOHIST$" MODIFY ("US#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."UNDOHIST$" MODIFY ("INC#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."UNDOHIST$" MODIFY ("TSN" NOT NULL ENABLE);
  ALTER TABLE "SYS"."UNDOHIST$" MODIFY ("FILE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."UNDOHIST$" MODIFY ("BLOCK#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."UNDOHIST$" MODIFY ("CRSCNWRP" NOT NULL ENABLE);
  ALTER TABLE "SYS"."UNDOHIST$" MODIFY ("CRSCNBAS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."UNDOHIST$" MODIFY ("DRSCNWRP" NOT NULL ENABLE);
  ALTER TABLE "SYS"."UNDOHIST$" MODIFY ("DRSCNBAS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."UNDOHIST$" MODIFY ("CRTTIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."UNDOHIST$" MODIFY ("DRPTIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."UNDOHIST$" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."UNDOHIST$" MODIFY ("USER#" NOT NULL ENABLE);
