--------------------------------------------------------
--  DDL for Table UNDO$
--------------------------------------------------------

  CREATE TABLE "SYS"."UNDO$" SHARING=METADATA 
   (	"US#" NUMBER, 
	"NAME" VARCHAR2(30 BYTE), 
	"USER#" NUMBER, 
	"FILE#" NUMBER, 
	"BLOCK#" NUMBER, 
	"SCNBAS" NUMBER, 
	"SCNWRP" NUMBER, 
	"XACTSQN" NUMBER, 
	"UNDOSQN" NUMBER, 
	"INST#" NUMBER, 
	"STATUS$" NUMBER, 
	"TS#" NUMBER, 
	"UGRP#" NUMBER, 
	"KEEP" NUMBER, 
	"OPTIMAL" NUMBER, 
	"FLAGS" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" VARCHAR2(1000 BYTE), 
	"SPARE5" VARCHAR2(1000 BYTE), 
	"SPARE6" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
