--------------------------------------------------------
--  DDL for Table UNUSED_GRANT$
--------------------------------------------------------

  CREATE TABLE "SYS"."UNUSED_GRANT$" SHARING=METADATA 
   (	"CAPTURE#" NUMBER, 
	"RUN_SEQ#" NUMBER, 
	"GRANTEE#" NUMBER, 
	"ROLE#" NUMBER DEFAULT NULL, 
	"SYSPRIV#" NUMBER DEFAULT NULL, 
	"OBJPRIV#" NUMBER DEFAULT NULL, 
	"USERPRIV#" NUMBER DEFAULT NULL, 
	"OBJ#" NUMBER DEFAULT NULL, 
	"COL#" NUMBER DEFAULT NULL, 
	"OPTION$" NUMBER DEFAULT NULL
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
