--------------------------------------------------------
--  DDL for Table USER$
--------------------------------------------------------

  CREATE TABLE "SYS"."USER$" SHARING=METADATA 
   (	"USER#" NUMBER, 
	"NAME" VARCHAR2(128 BYTE), 
	"TYPE#" NUMBER, 
	"PASSWORD" VARCHAR2(4000 BYTE), 
	"DATATS#" NUMBER, 
	"TEMPTS#" NUMBER, 
	"CTIME" DATE, 
	"PTIME" DATE, 
	"EXPTIME" DATE, 
	"LTIME" DATE, 
	"RESOURCE$" NUMBER, 
	"AUDIT$" VARCHAR2(38 BYTE), 
	"DEFROLE" NUMBER, 
	"DEFGRP#" NUMBER, 
	"DEFGRP_SEQ#" NUMBER, 
	"ASTATUS" NUMBER DEFAULT 0, 
	"LCOUNT" NUMBER DEFAULT 0, 
	"DEFSCHCLASS" VARCHAR2(128 BYTE), 
	"EXT_USERNAME" VARCHAR2(4000 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" VARCHAR2(1000 BYTE), 
	"SPARE5" VARCHAR2(1000 BYTE), 
	"SPARE6" DATE, 
	"SPARE7" VARCHAR2(4000 BYTE), 
	"SPARE8" VARCHAR2(4000 BYTE), 
	"SPARE9" NUMBER, 
	"SPARE10" NUMBER, 
	"SPARE11" TIMESTAMP (6)
   ) CLUSTER "SYS"."C_USER#" ("USER#");
