--------------------------------------------------------
--  Constraints for Table USER$
--------------------------------------------------------

  ALTER TABLE "SYS"."USER$" MODIFY ("USER#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."USER$" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."USER$" MODIFY ("TYPE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."USER$" MODIFY ("DATATS#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."USER$" MODIFY ("TEMPTS#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."USER$" MODIFY ("CTIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."USER$" MODIFY ("RESOURCE$" NOT NULL ENABLE);
  ALTER TABLE "SYS"."USER$" MODIFY ("DEFROLE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."USER$" MODIFY ("ASTATUS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."USER$" MODIFY ("LCOUNT" NOT NULL ENABLE);
