REM INSERTING into SYS.USER_PRIVILEGE_MAP
SET DEFINE OFF;
Insert into SYS.USER_PRIVILEGE_MAP (PRIVILEGE,NAME) values (0,'INHERIT PRIVILEGES');
Insert into SYS.USER_PRIVILEGE_MAP (PRIVILEGE,NAME) values (1,'TRANSLATE SQL');
Insert into SYS.USER_PRIVILEGE_MAP (PRIVILEGE,NAME) values (2,'INHERIT REMOTE PRIVILEGES');
Insert into SYS.USER_PRIVILEGE_MAP (PRIVILEGE,NAME) values (3,'DEBUG CONNECT');
