REM INSERTING into SYS.USER_ASTATUS_MAP
SET DEFINE OFF;
Insert into SYS.USER_ASTATUS_MAP (STATUS#,STATUS) values (0,'OPEN');
Insert into SYS.USER_ASTATUS_MAP (STATUS#,STATUS) values (1,'EXPIRED');
Insert into SYS.USER_ASTATUS_MAP (STATUS#,STATUS) values (2,'EXPIRED(GRACE)');
Insert into SYS.USER_ASTATUS_MAP (STATUS#,STATUS) values (4,'LOCKED(TIMED)');
Insert into SYS.USER_ASTATUS_MAP (STATUS#,STATUS) values (8,'LOCKED');
Insert into SYS.USER_ASTATUS_MAP (STATUS#,STATUS) values (5,'EXPIRED & LOCKED(TIMED)');
Insert into SYS.USER_ASTATUS_MAP (STATUS#,STATUS) values (6,'EXPIRED(GRACE) & LOCKED(TIMED)');
Insert into SYS.USER_ASTATUS_MAP (STATUS#,STATUS) values (9,'EXPIRED & LOCKED');
Insert into SYS.USER_ASTATUS_MAP (STATUS#,STATUS) values (10,'EXPIRED(GRACE) & LOCKED');
