--------------------------------------------------------
--  DDL for Table UTL_RECOMP_COMPILED
--------------------------------------------------------

  CREATE TABLE "SYS"."UTL_RECOMP_COMPILED" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"BATCH#" NUMBER, 
	"COMPILED_AT" TIMESTAMP (6), 
	"COMPLETED_AT" TIMESTAMP (6), 
	"COMPILED_BY" VARCHAR2(64 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
