--------------------------------------------------------
--  DDL for Table UTL_RECOMP_ERRORS
--------------------------------------------------------

  CREATE TABLE "SYS"."UTL_RECOMP_ERRORS" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"ERROR_AT" TIMESTAMP (6), 
	"COMPILE_ERR" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
