GRANT SELECT ON "SYS"."V_$CONTAINERS" TO "SELECT_CATALOG_ROLE";
  GRANT READ ON "SYS"."V_$CONTAINERS" TO "AUDSYS";
  GRANT SELECT ON "SYS"."V_$CONTAINERS" TO "APPQOSSYS";
  GRANT READ ON "SYS"."V_$CONTAINERS" TO "DATAPATCH_ROLE";
