GRANT SELECT ON "SYS"."V_$DG_BROKER_CONFIG" TO "SELECT_CATALOG_ROLE";
  GRANT SELECT ON "SYS"."V_$DG_BROKER_CONFIG" TO "GSMUSER_ROLE";
  GRANT SELECT ON "SYS"."V_$DG_BROKER_CONFIG" TO "GSMADMIN_INTERNAL";
