GRANT SELECT ON "SYS"."V_$PARAMETER" TO "SELECT_CATALOG_ROLE";
  GRANT SELECT ON "SYS"."V_$PARAMETER" TO "DBSFWUSER";
  GRANT SELECT ON "SYS"."V_$PARAMETER" TO "ORACLE_OCM";
  GRANT SELECT ON "SYS"."V_$PARAMETER" TO "APPQOSSYS";
  GRANT SELECT ON "SYS"."V_$PARAMETER" TO "GSMADMIN_INTERNAL";
  GRANT SELECT ON "SYS"."V_$PARAMETER" TO "CTXSYS";
  GRANT READ ON "SYS"."V_$PARAMETER" TO "DVSYS";
  GRANT READ ON "SYS"."V_$PARAMETER" TO "DV_SECANALYST";
