GRANT READ ON "SYS"."V_$VERSION" TO PUBLIC;
  GRANT READ ON "SYS"."V_$VERSION" TO "AUDSYS";
  GRANT SELECT ON "SYS"."V_$VERSION" TO "GSMADMIN_INTERNAL";
  GRANT READ ON "SYS"."V_$VERSION" TO "DVSYS";
