--------------------------------------------------------
--  DDL for Table VIEWCON$
--------------------------------------------------------

  CREATE TABLE "SYS"."VIEWCON$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"CON#" NUMBER, 
	"CONNAME" VARCHAR2(128 BYTE), 
	"TYPE#" NUMBER, 
	"CON_TEXT" CLOB, 
	"ROBJ#" NUMBER, 
	"PROPERTY" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("CON_TEXT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
