--------------------------------------------------------
--  DDL for Table VTABLE$
--------------------------------------------------------

  CREATE TABLE "SYS"."VTABLE$" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"VINDEX" NUMBER, 
	"ITYPETOID" RAW(16), 
	"ITYPEOWNER" VARCHAR2(128 BYTE), 
	"ITYPENAME" VARCHAR2(128 BYTE), 
	"IMETHOD#" NUMBER, 
	"IFLAGS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
