--------------------------------------------------------
--  Constraints for Table WI$_FREQUENT_PATTERN_ITEM
--------------------------------------------------------

  ALTER TABLE "SYS"."WI$_FREQUENT_PATTERN_ITEM" MODIFY ("JOBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WI$_FREQUENT_PATTERN_ITEM" MODIFY ("PATTERNID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WI$_FREQUENT_PATTERN_ITEM" MODIFY ("RANK" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WI$_FREQUENT_PATTERN_ITEM" MODIFY ("TEMPLATEID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WI$_FREQUENT_PATTERN_ITEM" MODIFY ("ISFIRSTINLOOP" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WI$_FREQUENT_PATTERN_ITEM" MODIFY ("ISLASTINLOOP" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WI$_FREQUENT_PATTERN_ITEM" ADD CONSTRAINT "WI$_FREQUENT_PATTERN_ITEM_PK" PRIMARY KEY ("JOBID", "PATTERNID", "RANK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
