--------------------------------------------------------
--  Constraints for Table WI$_CAPTURE_FILE
--------------------------------------------------------

  ALTER TABLE "SYS"."WI$_CAPTURE_FILE" MODIFY ("JOBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WI$_CAPTURE_FILE" MODIFY ("FILEID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WI$_CAPTURE_FILE" MODIFY ("PATH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WI$_CAPTURE_FILE" ADD CONSTRAINT "WI$_CAPTURE_FILE_PK" PRIMARY KEY ("JOBID", "FILEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
