--------------------------------------------------------
--  DDL for Table WI$_STATEMENT
--------------------------------------------------------

  CREATE TABLE "SYS"."WI$_STATEMENT" SHARING=METADATA 
   (	"JOBID" NUMBER, 
	"TEMPLATEID" NUMBER, 
	"SQLTEXT" CLOB, 
	"RANK" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" 
 LOB ("SQLTEXT") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
