--------------------------------------------------------
--  Constraints for Table WI$_OBJECT
--------------------------------------------------------

  ALTER TABLE "SYS"."WI$_OBJECT" MODIFY ("JOBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WI$_OBJECT" MODIFY ("TEMPLATEID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WI$_OBJECT" MODIFY ("OBJECTID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WI$_OBJECT" MODIFY ("ACCESSTYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WI$_OBJECT" ADD CONSTRAINT "WI$_OBJECT_PK" PRIMARY KEY ("JOBID", "TEMPLATEID", "OBJECTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
