--------------------------------------------------------
--  Ref Constraints for Table WI$_EXECUTION_ORDER
--------------------------------------------------------

  ALTER TABLE "SYS"."WI$_EXECUTION_ORDER" ADD CONSTRAINT "WI$_EXECUTION_ORDER_FK1" FOREIGN KEY ("JOBID", "FILEID")
	  REFERENCES "SYS"."WI$_CAPTURE_FILE" ("JOBID", "FILEID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SYS"."WI$_EXECUTION_ORDER" ADD CONSTRAINT "WI$_EXECUTION_ORDER_FK2" FOREIGN KEY ("JOBID", "TEMPLATEID")
	  REFERENCES "SYS"."WI$_TEMPLATE" ("JOBID", "TEMPLATEID") ON DELETE CASCADE ENABLE;
