--------------------------------------------------------
--  Constraints for Table WI$_FREQUENT_PATTERN
--------------------------------------------------------

  ALTER TABLE "SYS"."WI$_FREQUENT_PATTERN" MODIFY ("JOBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WI$_FREQUENT_PATTERN" MODIFY ("PATTERNID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WI$_FREQUENT_PATTERN" MODIFY ("LENGTH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WI$_FREQUENT_PATTERN" MODIFY ("NUMBEROFEXECUTIONS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WI$_FREQUENT_PATTERN" MODIFY ("DBTIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WI$_FREQUENT_PATTERN" ADD CONSTRAINT "WI$_FREQUENT_PATTERN_PK" PRIMARY KEY ("JOBID", "PATTERNID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
