--------------------------------------------------------
--  Constraints for Table WI$_EXECUTION_ORDER
--------------------------------------------------------

  ALTER TABLE "SYS"."WI$_EXECUTION_ORDER" MODIFY ("JOBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WI$_EXECUTION_ORDER" MODIFY ("FILEID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WI$_EXECUTION_ORDER" MODIFY ("RANK" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WI$_EXECUTION_ORDER" MODIFY ("TEMPLATEID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WI$_EXECUTION_ORDER" MODIFY ("DBTIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WI$_EXECUTION_ORDER" ADD CONSTRAINT "WI$_EXECUTION_ORDER_PK" PRIMARY KEY ("JOBID", "FILEID", "RANK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
