--------------------------------------------------------
--  Constraints for Table WI$_TEMPLATE
--------------------------------------------------------

  ALTER TABLE "SYS"."WI$_TEMPLATE" MODIFY ("JOBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WI$_TEMPLATE" MODIFY ("TEMPLATEID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WI$_TEMPLATE" MODIFY ("ISTRANSACTION" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WI$_TEMPLATE" ADD CONSTRAINT "WI$_TEMPLATE_PK" PRIMARY KEY ("JOBID", "TEMPLATEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
