--------------------------------------------------------
--  Constraints for Table WI$_FREQUENT_PATTERN_METADATA
--------------------------------------------------------

  ALTER TABLE "SYS"."WI$_FREQUENT_PATTERN_METADATA" MODIFY ("JOBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WI$_FREQUENT_PATTERN_METADATA" MODIFY ("MODELORDER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WI$_FREQUENT_PATTERN_METADATA" MODIFY ("THRESHOLD" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WI$_FREQUENT_PATTERN_METADATA" ADD CONSTRAINT "WI$_FREQ_PATTERN_METADATA_PK" PRIMARY KEY ("JOBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
