--------------------------------------------------------
--  Constraints for Table WI$_STATEMENT
--------------------------------------------------------

  ALTER TABLE "SYS"."WI$_STATEMENT" MODIFY ("JOBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WI$_STATEMENT" MODIFY ("TEMPLATEID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WI$_STATEMENT" MODIFY ("SQLTEXT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WI$_STATEMENT" MODIFY ("RANK" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WI$_STATEMENT" ADD CONSTRAINT "WI$_STATEMENT_PK" PRIMARY KEY ("JOBID", "TEMPLATEID", "RANK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
