--------------------------------------------------------
--  Constraints for Table WRH$_AWR_TEST_1
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_AWR_TEST_1" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_AWR_TEST_1" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_AWR_TEST_1" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_AWR_TEST_1" MODIFY ("STEP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_AWR_TEST_1" ADD CONSTRAINT "WRH$_AWR_TEST_1_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "STEP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  LOCAL
 (PARTITION "WRH$_AWR_TEST_1_692950692_0" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRH$_AWR_TEST_1_MXDB_MXSN" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" )  ENABLE;
