--------------------------------------------------------
--  DDL for Table WRH$_BUFFER_POOL_STATISTICS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_BUFFER_POOL_STATISTICS" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE), 
	"BLOCK_SIZE" NUMBER, 
	"SET_MSIZE" NUMBER, 
	"CNUM_REPL" NUMBER, 
	"CNUM_WRITE" NUMBER, 
	"CNUM_SET" NUMBER, 
	"BUF_GOT" NUMBER, 
	"SUM_WRITE" NUMBER, 
	"SUM_SCAN" NUMBER, 
	"FREE_BUFFER_WAIT" NUMBER, 
	"WRITE_COMPLETE_WAIT" NUMBER, 
	"BUFFER_BUSY_WAIT" NUMBER, 
	"FREE_BUFFER_INSPECTED" NUMBER, 
	"DIRTY_BUFFERS_INSPECTED" NUMBER, 
	"DB_BLOCK_CHANGE" NUMBER, 
	"DB_BLOCK_GETS" NUMBER, 
	"CONSISTENT_GETS" NUMBER, 
	"PHYSICAL_READS" NUMBER, 
	"PHYSICAL_WRITES" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_BUFFER_POOL_STATISTICS" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_BUFFER_POOL_STATISTICS" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_BUFFER_POOL_STATISTICS" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_BUFFER_POOL_STATISTICS" TO "SYSUMF_ROLE";
