--------------------------------------------------------
--  Constraints for Table WRH$_METRIC_NAME
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_METRIC_NAME" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_METRIC_NAME" MODIFY ("GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_METRIC_NAME" MODIFY ("METRIC_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_METRIC_NAME" MODIFY ("METRIC_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_METRIC_NAME" MODIFY ("METRIC_UNIT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_METRIC_NAME" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_METRIC_NAME" ADD CONSTRAINT "WRH$_METRIC_NAME_PK" PRIMARY KEY ("DBID", "GROUP_ID", "METRIC_ID", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
