--------------------------------------------------------
--  DDL for Table WRH$_RULE_SET
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_RULE_SET" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"OWNER" VARCHAR2(128 BYTE), 
	"NAME" VARCHAR2(128 BYTE), 
	"STARTUP_TIME" DATE, 
	"CPU_TIME" NUMBER, 
	"ELAPSED_TIME" NUMBER, 
	"EVALUATIONS" NUMBER, 
	"SQL_FREE_EVALUATIONS" NUMBER, 
	"SQL_EXECUTIONS" NUMBER, 
	"RELOADS" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_RULE_SET" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_RULE_SET" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_RULE_SET" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_RULE_SET" TO "SYSUMF_ROLE";
