--------------------------------------------------------
--  Constraints for Table WRH$_FILEMETRIC_HISTORY
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_FILEMETRIC_HISTORY" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_FILEMETRIC_HISTORY" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_FILEMETRIC_HISTORY" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_FILEMETRIC_HISTORY" MODIFY ("FILEID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_FILEMETRIC_HISTORY" MODIFY ("CREATIONTIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_FILEMETRIC_HISTORY" MODIFY ("BEGIN_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_FILEMETRIC_HISTORY" MODIFY ("END_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_FILEMETRIC_HISTORY" MODIFY ("INTSIZE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_FILEMETRIC_HISTORY" MODIFY ("GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_FILEMETRIC_HISTORY" MODIFY ("AVGREADTIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_FILEMETRIC_HISTORY" MODIFY ("AVGWRITETIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_FILEMETRIC_HISTORY" MODIFY ("PHYSICALREAD" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_FILEMETRIC_HISTORY" MODIFY ("PHYSICALWRITE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_FILEMETRIC_HISTORY" MODIFY ("PHYBLKREAD" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_FILEMETRIC_HISTORY" MODIFY ("PHYBLKWRITE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_FILEMETRIC_HISTORY" MODIFY ("CON_DBID" NOT NULL ENABLE);
