--------------------------------------------------------
--  DDL for Table WRH$_CELL_GLOBAL_SUMMARY_BL
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_CELL_GLOBAL_SUMMARY_BL" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"CELL_HASH" NUMBER, 
	"INCARNATION_NUM" NUMBER, 
	"CON_DBID" NUMBER, 
	"NUM_SAMPLES" NUMBER, 
	"CPU_USAGE_SUM" NUMBER, 
	"SYS_USAGE_SUM" NUMBER, 
	"USER_USAGE_SUM" NUMBER, 
	"NETWORK_BYTES_RECD_SUM" NUMBER, 
	"NETWORK_BYTES_SENT_SUM" NUMBER, 
	"CPU_USAGE_SUMX2" NUMBER, 
	"SYS_USAGE_SUMX2" NUMBER, 
	"USER_USAGE_SUMX2" NUMBER, 
	"NETWORK_BYTES_RECD_SUMX2" NUMBER, 
	"NETWORK_BYTES_SENT_SUMX2" NUMBER, 
	"PER_PDB" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
