--------------------------------------------------------
--  DDL for Table WRH$_INST_CACHE_TRANSFER
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_INST_CACHE_TRANSFER" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"INSTANCE" NUMBER, 
	"CLASS" VARCHAR2(18 BYTE), 
	"CR_BLOCK" NUMBER, 
	"CR_BUSY" NUMBER, 
	"CR_CONGESTED" NUMBER, 
	"CURRENT_BLOCK" NUMBER, 
	"CURRENT_BUSY" NUMBER, 
	"CURRENT_CONGESTED" NUMBER, 
	"LOST" NUMBER, 
	"CR_2HOP" NUMBER, 
	"CR_3HOP" NUMBER, 
	"CURRENT_2HOP" NUMBER, 
	"CURRENT_3HOP" NUMBER, 
	"CR_BLOCK_TIME" NUMBER, 
	"CR_BUSY_TIME" NUMBER, 
	"CR_CONGESTED_TIME" NUMBER, 
	"CURRENT_BLOCK_TIME" NUMBER, 
	"CURRENT_BUSY_TIME" NUMBER, 
	"CURRENT_CONGESTED_TIME" NUMBER, 
	"LOST_TIME" NUMBER, 
	"CR_2HOP_TIME" NUMBER, 
	"CR_3HOP_TIME" NUMBER, 
	"CURRENT_2HOP_TIME" NUMBER, 
	"CURRENT_3HOP_TIME" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARTITION BY RANGE ("DBID","SNAP_ID") 
 (PARTITION "WRH$_INST_CACHE_TRANSFER_692950692_0"  VALUES LESS THAN (692950692, MAXVALUE) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRH$_INST_CACHE_MXDB_MXSN"  VALUES LESS THAN (MAXVALUE, MAXVALUE) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" )  ENABLE ROW MOVEMENT ;
  GRANT DELETE ON "SYS"."WRH$_INST_CACHE_TRANSFER" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_INST_CACHE_TRANSFER" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_INST_CACHE_TRANSFER" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_INST_CACHE_TRANSFER" TO "SYSUMF_ROLE";
