--------------------------------------------------------
--  DDL for Table WRH$_SYS_TIME_MODEL
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_SYS_TIME_MODEL" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"STAT_ID" NUMBER, 
	"VALUE" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARTITION BY RANGE ("DBID","SNAP_ID") 
 (PARTITION "WRH$_SYS_TIME_MODEL_692950692_0"  VALUES LESS THAN (692950692, MAXVALUE) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRH$_SYS_TIME_MO_MXDB_MXSN"  VALUES LESS THAN (MAXVALUE, MAXVALUE) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" )  ENABLE ROW MOVEMENT ;
  GRANT DELETE ON "SYS"."WRH$_SYS_TIME_MODEL" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_SYS_TIME_MODEL" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_SYS_TIME_MODEL" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_SYS_TIME_MODEL" TO "SYSUMF_ROLE";
