--------------------------------------------------------
--  DDL for Index WRH$_EVENT_HISTOGRAM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."WRH$_EVENT_HISTOGRAM_PK" ON "SYS"."WRH$_EVENT_HISTOGRAM" ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "EVENT_ID", "WAIT_TIME_MILLI", "CON_DBID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  LOCAL
 (PARTITION "WRH$_EVENT_HISTOGRAM_692950692_0" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRH$_EVENT_HISTO_MXDB_MXSN" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ) ;
