--------------------------------------------------------
--  DDL for Table WRH$_PERSISTENT_QMN_CACHE
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_PERSISTENT_QMN_CACHE" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"QUEUE_TABLE_ID" NUMBER, 
	"TYPE" VARCHAR2(32 BYTE), 
	"STATUS" NUMBER, 
	"NEXT_SERVICE_TIME" TIMESTAMP (3), 
	"WINDOW_END_TIME" TIMESTAMP (3), 
	"TOTAL_RUNS" NUMBER, 
	"TOTAL_LATENCY" NUMBER, 
	"TOTAL_ELAPSED_TIME" NUMBER, 
	"TOTAL_CPU_TIME" NUMBER, 
	"TMGR_ROWS_PROCESSED" NUMBER, 
	"TMGR_ELAPSED_TIME" NUMBER, 
	"TMGR_CPU_TIME" NUMBER, 
	"LAST_TMGR_PROCESSING_TIME" TIMESTAMP (3), 
	"DEQLOG_ROWS_PROCESSED" NUMBER, 
	"DEQLOG_PROCESSING_ELAPSED_TIME" NUMBER, 
	"DEQLOG_PROCESSING_CPU_TIME" NUMBER, 
	"LAST_DEQLOG_PROCESSING_TIME" TIMESTAMP (3), 
	"DEQUEUE_INDEX_BLOCKS_FREED" NUMBER, 
	"HISTORY_INDEX_BLOCKS_FREED" NUMBER, 
	"TIME_INDEX_BLOCKS_FREED" NUMBER, 
	"INDEX_CLEANUP_COUNT" NUMBER, 
	"INDEX_CLEANUP_ELAPSED_TIME" NUMBER, 
	"INDEX_CLEANUP_CPU_TIME" NUMBER, 
	"LAST_INDEX_CLEANUP_TIME" TIMESTAMP (3), 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_PERSISTENT_QMN_CACHE" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_PERSISTENT_QMN_CACHE" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_PERSISTENT_QMN_CACHE" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_PERSISTENT_QMN_CACHE" TO "SYSUMF_ROLE";
