--------------------------------------------------------
--  Constraints for Table WRH$_TEMPSTATXS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_TEMPSTATXS" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_TEMPSTATXS" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_TEMPSTATXS" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_TEMPSTATXS" MODIFY ("FILE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_TEMPSTATXS" MODIFY ("CREATION_CHANGE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_TEMPSTATXS" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_TEMPSTATXS" ADD CONSTRAINT "WRH$_TEMPSTATXS_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "FILE#", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
