--------------------------------------------------------
--  DDL for Table WRH$_PROCESS_WAITTIME_BL
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_PROCESS_WAITTIME_BL" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"PROCESS_TYPE" VARCHAR2(5 BYTE), 
	"DESCRIPTION" VARCHAR2(64 BYTE), 
	"WAIT_CLASS_TYPE" VARCHAR2(64 BYTE), 
	"VALUE" NUMBER, 
	"CON_DBID" NUMBER, 
	"PER_PDB" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
