--------------------------------------------------------
--  DDL for Table WRH$_PARAMETER_BL
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_PARAMETER_BL" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"PARAMETER_HASH" NUMBER, 
	"VALUE" VARCHAR2(512 BYTE), 
	"ISDEFAULT" VARCHAR2(9 BYTE), 
	"ISMODIFIED" VARCHAR2(10 BYTE), 
	"CON_DBID" NUMBER, 
	"PER_PDB" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
