--------------------------------------------------------
--  DDL for Index WRH$_SESS_NETWORK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."WRH$_SESS_NETWORK_PK" ON "SYS"."WRH$_SESS_NETWORK" ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "CON_DBID", "SESSION_ID", "SERIAL#", "CHANNEL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  LOCAL
 (PARTITION "WRH$_SESS_NETWORK_692950692_0" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRH$_SESS_NETWORK_MXDB_MXSN" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ) ;
