--------------------------------------------------------
--  DDL for Table WRH$_CON_SYSMETRIC_HISTORY_BL
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_CON_SYSMETRIC_HISTORY_BL" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"BEGIN_TIME" DATE, 
	"END_TIME" DATE, 
	"INTSIZE" NUMBER, 
	"GROUP_ID" NUMBER, 
	"METRIC_ID" NUMBER, 
	"VALUE" NUMBER, 
	"CON_DBID" NUMBER, 
	"PER_PDB" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
