--------------------------------------------------------
--  DDL for Table WRH$_ASM_DISK_STAT_SUMMARY_BL
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_ASM_DISK_STAT_SUMMARY_BL" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"GROUP_NUMBER" NUMBER, 
	"READS" NUMBER, 
	"WRITES" NUMBER, 
	"READ_ERRS" NUMBER, 
	"WRITE_ERRS" NUMBER, 
	"READ_TIMEOUT" NUMBER, 
	"WRITE_TIMEOUT" NUMBER, 
	"READ_TIME" NUMBER, 
	"WRITE_TIME" NUMBER, 
	"BYTES_READ" NUMBER, 
	"BYTES_WRITTEN" NUMBER, 
	"CON_DBID" NUMBER, 
	"PER_PDB" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
