--------------------------------------------------------
--  Constraints for Table WRH$_ACTIVE_SESSION_HISTORY_BL
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_ACTIVE_SESSION_HISTORY_BL" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_ACTIVE_SESSION_HISTORY_BL" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_ACTIVE_SESSION_HISTORY_BL" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_ACTIVE_SESSION_HISTORY_BL" MODIFY ("SAMPLE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_ACTIVE_SESSION_HISTORY_BL" MODIFY ("SAMPLE_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_ACTIVE_SESSION_HISTORY_BL" MODIFY ("SESSION_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_ACTIVE_SESSION_HISTORY_BL" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_ACTIVE_SESSION_HISTORY_BL" ADD CONSTRAINT "WRH$_ASH_BL_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "SAMPLE_ID", "SESSION_ID", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
