--------------------------------------------------------
--  DDL for Table WRH$_PERSISTENT_SUBSCRIBERS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_PERSISTENT_SUBSCRIBERS" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"QUEUE_SCHEMA" VARCHAR2(128 BYTE), 
	"QUEUE_NAME" VARCHAR2(128 BYTE), 
	"SUBSCRIBER_ID" NUMBER, 
	"SUBSCRIBER_NAME" VARCHAR2(128 BYTE), 
	"SUBSCRIBER_ADDRESS" VARCHAR2(1024 BYTE), 
	"SUBSCRIBER_TYPE" VARCHAR2(128 BYTE), 
	"FIRST_ACTIVITY_TIME" TIMESTAMP (6), 
	"ENQUEUED_MSGS" NUMBER, 
	"DEQUEUED_MSGS" NUMBER, 
	"EXPIRED_MSGS" NUMBER, 
	"DEQUEUED_MSG_LATENCY" NUMBER, 
	"LAST_ENQUEUE_TIME" TIMESTAMP (6), 
	"LAST_DEQUEUE_TIME" TIMESTAMP (6), 
	"AVG_MSG_AGE" NUMBER, 
	"BROWSED_MSGS" NUMBER, 
	"ELAPSED_DEQUEUE_TIME" NUMBER, 
	"DEQUEUE_CPU_TIME" NUMBER, 
	"DEQUEUE_TRANSACTIONS" NUMBER, 
	"EXECUTION_COUNT" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_PERSISTENT_SUBSCRIBERS" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_PERSISTENT_SUBSCRIBERS" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_PERSISTENT_SUBSCRIBERS" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_PERSISTENT_SUBSCRIBERS" TO "SYSUMF_ROLE";
