--------------------------------------------------------
--  Constraints for Table WRH$_TEMPFILE
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_TEMPFILE" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_TEMPFILE" MODIFY ("FILE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_TEMPFILE" MODIFY ("CREATION_CHANGE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_TEMPFILE" MODIFY ("FILENAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_TEMPFILE" MODIFY ("TS#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_TEMPFILE" MODIFY ("TSNAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_TEMPFILE" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_TEMPFILE" ADD CONSTRAINT "WRH$_TEMPFILE_PK" PRIMARY KEY ("DBID", "FILE#", "CREATION_CHANGE#", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
