--------------------------------------------------------
--  Constraints for Table WRH$_INTERCONNECT_PINGS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_INTERCONNECT_PINGS" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_INTERCONNECT_PINGS" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_INTERCONNECT_PINGS" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_INTERCONNECT_PINGS" MODIFY ("TARGET_INSTANCE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_INTERCONNECT_PINGS" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_INTERCONNECT_PINGS" ADD CONSTRAINT "WRH$_INTERCONNECT_PINGS_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "TARGET_INSTANCE", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  LOCAL
 (PARTITION "WRH$_INTERCONNECT_PINGS_692950692_0" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRH$_IC_PINGS_MXDB_MXSN" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" )  ENABLE;
