--------------------------------------------------------
--  Constraints for Table WRH$_MVPARAMETER_BL
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_MVPARAMETER_BL" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_MVPARAMETER_BL" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_MVPARAMETER_BL" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_MVPARAMETER_BL" MODIFY ("PARAMETER_HASH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_MVPARAMETER_BL" MODIFY ("ORDINAL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_MVPARAMETER_BL" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_MVPARAMETER_BL" ADD CONSTRAINT "WRH$_MVPARAMETER_BL_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "PARAMETER_HASH", "ORDINAL", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
