--------------------------------------------------------
--  DDL for Table WRH$_SQL_SUMMARY
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_SQL_SUMMARY" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"TOTAL_SQL" NUMBER, 
	"TOTAL_SQL_MEM" NUMBER, 
	"SINGLE_USE_SQL" NUMBER, 
	"SINGLE_USE_SQL_MEM" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_SQL_SUMMARY" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_SQL_SUMMARY" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_SQL_SUMMARY" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_SQL_SUMMARY" TO "SYSUMF_ROLE";
