--------------------------------------------------------
--  Constraints for Table WRH$_LATCH_NAME
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_LATCH_NAME" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LATCH_NAME" MODIFY ("LATCH_HASH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LATCH_NAME" MODIFY ("LATCH_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LATCH_NAME" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LATCH_NAME" ADD CONSTRAINT "WRH$_LATCH_NAME_PK" PRIMARY KEY ("DBID", "LATCH_HASH", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
