--------------------------------------------------------
--  Constraints for Table WRH$_RSRC_CONSUMER_GROUP
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("SEQUENCE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("CONSUMER_GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("CONSUMER_GROUP_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("REQUESTS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("CPU_WAIT_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("CPU_WAITS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("CONSUMED_CPU_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("YIELDS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("ACTIVE_SESS_LIMIT_HIT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("UNDO_LIMIT_HIT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("SWITCHES_IN_CPU_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("SWITCHES_OUT_CPU_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("SWITCHES_IN_IO_MEGABYTES" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("SWITCHES_OUT_IO_MEGABYTES" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("SWITCHES_IN_IO_REQUESTS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("SWITCHES_OUT_IO_REQUESTS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("SQL_CANCELED" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("ACTIVE_SESS_KILLED" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("IDLE_SESS_KILLED" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("IDLE_BLKR_SESS_KILLED" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("QUEUED_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("QUEUE_TIME_OUTS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("IO_SERVICE_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("IO_SERVICE_WAITS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("SMALL_READ_MEGABYTES" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("SMALL_WRITE_MEGABYTES" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("LARGE_READ_MEGABYTES" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("LARGE_WRITE_MEGABYTES" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("SMALL_READ_REQUESTS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("SMALL_WRITE_REQUESTS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("LARGE_READ_REQUESTS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("LARGE_WRITE_REQUESTS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("SWITCHES_IN_IO_LOGICAL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("SWITCHES_OUT_IO_LOGICAL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("SWITCHES_IN_ELAPSED_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("SWITCHES_OUT_ELAPSED_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" MODIFY ("PGA_LIMIT_SESSIONS_KILLED" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" ADD CONSTRAINT "WRH$_RSRC_CONSUMER_GROUP_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "SEQUENCE#", "CONSUMER_GROUP_ID", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
