--------------------------------------------------------
--  DDL for Index WRH$_CHANNEL_WAITS
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."WRH$_CHANNEL_WAITS" ON "SYS"."WRH$_CHANNEL_WAITS" ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "CHANNEL", "CON_DBID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
  GRANT DELETE ON "SYS"."WRH$_CHANNEL_WAITS" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_CHANNEL_WAITS" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_CHANNEL_WAITS" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_CHANNEL_WAITS" TO "SYSUMF_ROLE";
