--------------------------------------------------------
--  DDL for Table WRH$_SYSMETRIC_HISTORY
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_SYSMETRIC_HISTORY" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"BEGIN_TIME" DATE, 
	"END_TIME" DATE, 
	"INTSIZE" NUMBER, 
	"GROUP_ID" NUMBER, 
	"METRIC_ID" NUMBER, 
	"VALUE" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARTITION BY RANGE ("DBID","SNAP_ID") 
 (PARTITION "WRH$_SYSMETRIC_HISTORY_692950692_0"  VALUES LESS THAN (692950692, MAXVALUE) 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRH$_SYSME_HIST_MXDB_MXSN"  VALUES LESS THAN (MAXVALUE, MAXVALUE) 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" )  ENABLE ROW MOVEMENT ;
  GRANT DELETE ON "SYS"."WRH$_SYSMETRIC_HISTORY" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_SYSMETRIC_HISTORY" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_SYSMETRIC_HISTORY" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_SYSMETRIC_HISTORY" TO "SYSUMF_ROLE";
