--------------------------------------------------------
--  Constraints for Table WRH$_PLAN_OPERATION_NAME
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_PLAN_OPERATION_NAME" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_PLAN_OPERATION_NAME" MODIFY ("OPERATION_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_PLAN_OPERATION_NAME" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_PLAN_OPERATION_NAME" ADD CONSTRAINT "WRH$_PLAN_OPERATION_NAME_PK" PRIMARY KEY ("DBID", "OPERATION_ID", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
