--------------------------------------------------------
--  DDL for Table WRH$_IM_SEG_STAT
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_IM_SEG_STAT" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"TS#" NUMBER, 
	"OBJ#" NUMBER, 
	"DATAOBJ#" NUMBER, 
	"MEMBYTES" NUMBER, 
	"SCANS" NUMBER, 
	"SCANS_DELTA" NUMBER, 
	"DB_BLOCK_CHANGES" NUMBER, 
	"DB_BLOCK_CHANGES_DELTA" NUMBER, 
	"POPULATE_CUS" NUMBER, 
	"POPULATE_CUS_DELTA" NUMBER, 
	"REPOPULATE_CUS" NUMBER, 
	"REPOPULATE_CUS_DELTA" NUMBER, 
	"CON_DBID" NUMBER, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARTITION BY RANGE ("DBID","SNAP_ID") 
 (PARTITION "WRH$_IM_SEG_STAT_692950692_0"  VALUES LESS THAN (692950692, MAXVALUE) 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRH$_IM_SEG_STAT_MXDB_MXSN"  VALUES LESS THAN (MAXVALUE, MAXVALUE) 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" )  ENABLE ROW MOVEMENT ;
  GRANT DELETE ON "SYS"."WRH$_IM_SEG_STAT" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_IM_SEG_STAT" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_IM_SEG_STAT" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_IM_SEG_STAT" TO "SYSUMF_ROLE";
