--------------------------------------------------------
--  DDL for Table WRH$_DB_CACHE_ADVICE
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_DB_CACHE_ADVICE" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"BPID" NUMBER, 
	"BUFFERS_FOR_ESTIMATE" NUMBER, 
	"NAME" VARCHAR2(20 BYTE), 
	"BLOCK_SIZE" NUMBER, 
	"ADVICE_STATUS" VARCHAR2(3 BYTE), 
	"SIZE_FOR_ESTIMATE" NUMBER, 
	"SIZE_FACTOR" NUMBER, 
	"PHYSICAL_READS" NUMBER, 
	"BASE_PHYSICAL_READS" NUMBER, 
	"ACTUAL_PHYSICAL_READS" NUMBER, 
	"ESTD_PHYSICAL_READ_TIME" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARTITION BY RANGE ("DBID","SNAP_ID") 
 (PARTITION "WRH$_DB_CACHE_ADVICE_692950692_0"  VALUES LESS THAN (692950692, MAXVALUE) 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRH$_DB_CACHE_AD_MXDB_MXSN"  VALUES LESS THAN (MAXVALUE, MAXVALUE) 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" )  ENABLE ROW MOVEMENT ;
  GRANT DELETE ON "SYS"."WRH$_DB_CACHE_ADVICE" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_DB_CACHE_ADVICE" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_DB_CACHE_ADVICE" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_DB_CACHE_ADVICE" TO "SYSUMF_ROLE";
