--------------------------------------------------------
--  DDL for Table WRH$_REPLICATION_TBL_STATS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_REPLICATION_TBL_STATS" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"APPLY_NAME" VARCHAR2(128 BYTE), 
	"TABLE_NAME" VARCHAR2(128 BYTE), 
	"TABLE_OWNER" VARCHAR2(128 BYTE), 
	"SESSION_MODULE" VARCHAR2(64 BYTE), 
	"TOTAL_INSERTS" NUMBER, 
	"TOTAL_UPDATES" NUMBER, 
	"TOTAL_DELETES" NUMBER, 
	"CDR_SUCCESSFUL" NUMBER, 
	"CDR_FAILED" NUMBER, 
	"REPERR_CNT" NUMBER, 
	"HANDLE_COLLISIONS" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_REPLICATION_TBL_STATS" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_REPLICATION_TBL_STATS" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_REPLICATION_TBL_STATS" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_REPLICATION_TBL_STATS" TO "SYSUMF_ROLE";
