--------------------------------------------------------
--  DDL for Table WRH$_ASM_DISKGROUP
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_ASM_DISKGROUP" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"CON_DBID" NUMBER, 
	"CURRENT_SNAP_ID" NUMBER, 
	"GROUP_NUMBER" NUMBER, 
	"NAME" VARCHAR2(128 BYTE), 
	"TYPE" VARCHAR2(6 BYTE), 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_ASM_DISKGROUP" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_ASM_DISKGROUP" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_ASM_DISKGROUP" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_ASM_DISKGROUP" TO "SYSUMF_ROLE";
