--------------------------------------------------------
--  DDL for Table WRH$_CELL_DB_BL
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_CELL_DB_BL" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"CELL_HASH" NUMBER, 
	"INCARNATION_NUM" NUMBER, 
	"CON_DBID" NUMBER, 
	"SRC_DBID" NUMBER, 
	"SRC_DBNAME" VARCHAR2(256 BYTE), 
	"DISK_REQUESTS" NUMBER, 
	"DISK_BYTES" NUMBER, 
	"FLASH_REQUESTS" NUMBER, 
	"FLASH_BYTES" NUMBER, 
	"DISK_SMALL_IO_REQS" NUMBER, 
	"DISK_LARGE_IO_REQS" NUMBER, 
	"FLASH_SMALL_IO_REQS" NUMBER, 
	"FLASH_LARGE_IO_REQS" NUMBER, 
	"DISK_SMALL_IO_SERVICE_TIME" NUMBER, 
	"DISK_SMALL_IO_QUEUE_TIME" NUMBER, 
	"DISK_LARGE_IO_SERVICE_TIME" NUMBER, 
	"DISK_LARGE_IO_QUEUE_TIME" NUMBER, 
	"FLASH_SMALL_IO_SERVICE_TIME" NUMBER, 
	"FLASH_SMALL_IO_QUEUE_TIME" NUMBER, 
	"FLASH_LARGE_IO_SERVICE_TIME" NUMBER, 
	"FLASH_LARGE_IO_QUEUE_TIME" NUMBER, 
	"PER_PDB" NUMBER, 
	"IS_CURRENT_SRC_DB" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
