--------------------------------------------------------
--  DDL for Table WRH$_SESSMETRIC_HISTORY
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_SESSMETRIC_HISTORY" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"BEGIN_TIME" DATE, 
	"END_TIME" DATE, 
	"SESSID" NUMBER, 
	"SERIAL#" NUMBER, 
	"INTSIZE" NUMBER, 
	"GROUP_ID" NUMBER, 
	"METRIC_ID" NUMBER, 
	"VALUE" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_SESSMETRIC_HISTORY" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_SESSMETRIC_HISTORY" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_SESSMETRIC_HISTORY" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_SESSMETRIC_HISTORY" TO "SYSUMF_ROLE";
