--------------------------------------------------------
--  Constraints for Table WRH$_RESOURCE_LIMIT
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_RESOURCE_LIMIT" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RESOURCE_LIMIT" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RESOURCE_LIMIT" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RESOURCE_LIMIT" MODIFY ("RESOURCE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RESOURCE_LIMIT" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RESOURCE_LIMIT" ADD CONSTRAINT "WRH$_RESOURCE_LIMIT_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "RESOURCE_NAME", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
