--------------------------------------------------------
--  Constraints for Table WRH$_CURRENT_BLOCK_SERVER
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_CURRENT_BLOCK_SERVER" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CURRENT_BLOCK_SERVER" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CURRENT_BLOCK_SERVER" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CURRENT_BLOCK_SERVER" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CURRENT_BLOCK_SERVER" ADD CONSTRAINT "WRH$_CURRENT_BLOCK_SERVER_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
