--------------------------------------------------------
--  Constraints for Table WRH$_IOSTAT_FILETYPE
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_IOSTAT_FILETYPE" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_FILETYPE" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_FILETYPE" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_FILETYPE" MODIFY ("FILETYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_FILETYPE" MODIFY ("SMALL_READ_MEGABYTES" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_FILETYPE" MODIFY ("SMALL_WRITE_MEGABYTES" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_FILETYPE" MODIFY ("LARGE_READ_MEGABYTES" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_FILETYPE" MODIFY ("LARGE_WRITE_MEGABYTES" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_FILETYPE" MODIFY ("SMALL_READ_REQS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_FILETYPE" MODIFY ("SMALL_WRITE_REQS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_FILETYPE" MODIFY ("SMALL_SYNC_READ_REQS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_FILETYPE" MODIFY ("LARGE_READ_REQS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_FILETYPE" MODIFY ("LARGE_WRITE_REQS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_FILETYPE" MODIFY ("SMALL_READ_SERVICETIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_FILETYPE" MODIFY ("SMALL_WRITE_SERVICETIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_FILETYPE" MODIFY ("SMALL_SYNC_READ_LATENCY" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_FILETYPE" MODIFY ("LARGE_READ_SERVICETIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_FILETYPE" MODIFY ("LARGE_WRITE_SERVICETIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_FILETYPE" MODIFY ("RETRIES_ON_ERROR" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_FILETYPE" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_FILETYPE" ADD CONSTRAINT "WRH$_IOSTAT_FILETYPE_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "FILETYPE_ID", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
