--------------------------------------------------------
--  Constraints for Table WRH$_DLM_MISC_BL
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_DLM_MISC_BL" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_DLM_MISC_BL" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_DLM_MISC_BL" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_DLM_MISC_BL" MODIFY ("STATISTIC#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_DLM_MISC_BL" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_DLM_MISC_BL" ADD CONSTRAINT "WRH$_DLM_MISC_BL_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "STATISTIC#", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
