--------------------------------------------------------
--  DDL for Table WRH$_INTERCONNECT_PINGS_BL
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_INTERCONNECT_PINGS_BL" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"TARGET_INSTANCE" NUMBER, 
	"CNT_500B" NUMBER, 
	"WAIT_500B" NUMBER, 
	"WAITSQ_500B" NUMBER, 
	"CNT_8K" NUMBER, 
	"WAIT_8K" NUMBER, 
	"WAITSQ_8K" NUMBER, 
	"CON_DBID" NUMBER, 
	"PER_PDB" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
