--------------------------------------------------------
--  Constraints for Table WRH$_ASM_DISKGROUP_STAT
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_ASM_DISKGROUP_STAT" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_ASM_DISKGROUP_STAT" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_ASM_DISKGROUP_STAT" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_ASM_DISKGROUP_STAT" MODIFY ("GROUP_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_ASM_DISKGROUP_STAT" ADD CONSTRAINT "WRH$_ASM_DISKGROUP_STAT_PK" PRIMARY KEY ("SNAP_ID", "DBID", "GROUP_NUMBER", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
