--------------------------------------------------------
--  Constraints for Table WRH$_PROCESS_MEMORY_SUMMARY
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_PROCESS_MEMORY_SUMMARY" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_PROCESS_MEMORY_SUMMARY" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_PROCESS_MEMORY_SUMMARY" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_PROCESS_MEMORY_SUMMARY" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_PROCESS_MEMORY_SUMMARY" MODIFY ("PER_PDB_NN" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_PROCESS_MEMORY_SUMMARY" ADD CONSTRAINT "WRH$_PROCESS_MEM_SUMMARY_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "CATEGORY", "CON_DBID", "PER_PDB_NN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
