--------------------------------------------------------
--  DDL for Index WRH$_CON_SYSTEM_EVENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."WRH$_CON_SYSTEM_EVENT_PK" ON "SYS"."WRH$_CON_SYSTEM_EVENT" ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "EVENT_ID", "CON_DBID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  LOCAL
 (PARTITION "WRH$_CON_SYSTEM_EVENT_692950692_0" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRH$_CON_SYSTEM_EVEN_MXDB_MXSN" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ) ;
