--------------------------------------------------------
--  DDL for Table WRH$_INSTANCE_RECOVERY
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_INSTANCE_RECOVERY" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"RECOVERY_ESTIMATED_IOS" NUMBER, 
	"ACTUAL_REDO_BLKS" NUMBER, 
	"TARGET_REDO_BLKS" NUMBER, 
	"LOG_FILE_SIZE_REDO_BLKS" NUMBER, 
	"LOG_CHKPT_TIMEOUT_REDO_BLKS" NUMBER, 
	"LOG_CHKPT_INTERVAL_REDO_BLKS" NUMBER, 
	"FAST_START_IO_TARGET_REDO_BLKS" NUMBER, 
	"TARGET_MTTR" NUMBER, 
	"ESTIMATED_MTTR" NUMBER, 
	"CKPT_BLOCK_WRITES" NUMBER, 
	"OPTIMAL_LOGFILE_SIZE" NUMBER, 
	"ESTD_CLUSTER_AVAILABLE_TIME" NUMBER, 
	"WRITES_MTTR" NUMBER, 
	"WRITES_LOGFILE_SIZE" NUMBER, 
	"WRITES_LOG_CHECKPOINT_SETTINGS" NUMBER, 
	"WRITES_OTHER_SETTINGS" NUMBER, 
	"WRITES_AUTOTUNE" NUMBER, 
	"WRITES_FULL_THREAD_CKPT" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_INSTANCE_RECOVERY" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_INSTANCE_RECOVERY" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_INSTANCE_RECOVERY" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_INSTANCE_RECOVERY" TO "SYSUMF_ROLE";
