--------------------------------------------------------
--  DDL for Table WRH$_SESS_TIME_STATS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_SESS_TIME_STATS" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"SESSION_TYPE" VARCHAR2(64 BYTE), 
	"MIN_LOGON_TIME" DATE, 
	"SUM_CPU_TIME" NUMBER, 
	"SUM_SYS_IO_WAIT" NUMBER, 
	"SUM_USER_IO_WAIT" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"SESSION_MODULE" VARCHAR2(64 BYTE) DEFAULT 'Streams', 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_SESS_TIME_STATS" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_SESS_TIME_STATS" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_SESS_TIME_STATS" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_SESS_TIME_STATS" TO "SYSUMF_ROLE";
