--------------------------------------------------------
--  DDL for Table WRH$_DB_CACHE_ADVICE_BL
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_DB_CACHE_ADVICE_BL" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"BPID" NUMBER, 
	"BUFFERS_FOR_ESTIMATE" NUMBER, 
	"NAME" VARCHAR2(20 BYTE), 
	"BLOCK_SIZE" NUMBER, 
	"ADVICE_STATUS" VARCHAR2(3 BYTE), 
	"SIZE_FOR_ESTIMATE" NUMBER, 
	"SIZE_FACTOR" NUMBER, 
	"PHYSICAL_READS" NUMBER, 
	"BASE_PHYSICAL_READS" NUMBER, 
	"ACTUAL_PHYSICAL_READS" NUMBER, 
	"ESTD_PHYSICAL_READ_TIME" NUMBER, 
	"CON_DBID" NUMBER, 
	"PER_PDB" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
