--------------------------------------------------------
--  DDL for Table WRH$_SERVICE_WAIT_CLASS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_SERVICE_WAIT_CLASS" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"SERVICE_NAME_HASH" NUMBER, 
	"WAIT_CLASS_ID" NUMBER, 
	"WAIT_CLASS" VARCHAR2(64 BYTE), 
	"TOTAL_WAITS" NUMBER, 
	"TIME_WAITED" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARTITION BY RANGE ("DBID","SNAP_ID") 
 (PARTITION "WRH$_SERVICE_WAIT_CLASS_692950692_0"  VALUES LESS THAN (692950692, MAXVALUE) 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRH$_SERVICE_WAIT_MXDB_MXSN"  VALUES LESS THAN (MAXVALUE, MAXVALUE) 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" )  ENABLE ROW MOVEMENT ;
  GRANT DELETE ON "SYS"."WRH$_SERVICE_WAIT_CLASS" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_SERVICE_WAIT_CLASS" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_SERVICE_WAIT_CLASS" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_SERVICE_WAIT_CLASS" TO "SYSUMF_ROLE";
