--------------------------------------------------------
--  DDL for Index WRH$_PROCESS_WAITTIME_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."WRH$_PROCESS_WAITTIME_PK" ON "SYS"."WRH$_PROCESS_WAITTIME" ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "CON_DBID", "PROCESS_TYPE", "DESCRIPTION", "WAIT_CLASS_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  LOCAL
 (PARTITION "WRH$_PROCESS_WAITTIME_692950692_0" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRH$_PROCESS_WAITTIM_MXDB_MXSN" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ) ;
