--------------------------------------------------------
--  Constraints for Table WRH$_SQL_WORKAREA_HISTOGRAM
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_SQL_WORKAREA_HISTOGRAM" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SQL_WORKAREA_HISTOGRAM" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SQL_WORKAREA_HISTOGRAM" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SQL_WORKAREA_HISTOGRAM" MODIFY ("LOW_OPTIMAL_SIZE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SQL_WORKAREA_HISTOGRAM" MODIFY ("HIGH_OPTIMAL_SIZE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SQL_WORKAREA_HISTOGRAM" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SQL_WORKAREA_HISTOGRAM" ADD CONSTRAINT "WRH$_SQL_WORKAREA_HIST_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "LOW_OPTIMAL_SIZE", "HIGH_OPTIMAL_SIZE", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
