--------------------------------------------------------
--  Constraints for Table WRH$_IOSTAT_FUNCTION_NAME
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_IOSTAT_FUNCTION_NAME" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_FUNCTION_NAME" MODIFY ("FUNCTION_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_FUNCTION_NAME" MODIFY ("FUNCTION_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_FUNCTION_NAME" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_FUNCTION_NAME" ADD CONSTRAINT "WRH$_IOSTAT_FUNCTION_NAME_PK" PRIMARY KEY ("DBID", "FUNCTION_ID", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
