--------------------------------------------------------
--  Constraints for Table WRH$_MVPARAMETER
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_MVPARAMETER" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_MVPARAMETER" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_MVPARAMETER" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_MVPARAMETER" MODIFY ("PARAMETER_HASH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_MVPARAMETER" MODIFY ("ORDINAL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_MVPARAMETER" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_MVPARAMETER" ADD CONSTRAINT "WRH$_MVPARAMETER_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "PARAMETER_HASH", "ORDINAL", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  LOCAL
 (PARTITION "WRH$_MVPARAMETER_692950692_0" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRH$_MVPARAMETER_MXDB_MXSN" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" )  ENABLE;
