--------------------------------------------------------
--  DDL for Table WRH$_LATCH
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_LATCH" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"LATCH_HASH" NUMBER, 
	"LEVEL#" NUMBER, 
	"GETS" NUMBER, 
	"MISSES" NUMBER, 
	"SLEEPS" NUMBER, 
	"IMMEDIATE_GETS" NUMBER, 
	"IMMEDIATE_MISSES" NUMBER, 
	"SPIN_GETS" NUMBER, 
	"SLEEP1" NUMBER, 
	"SLEEP2" NUMBER, 
	"SLEEP3" NUMBER, 
	"SLEEP4" NUMBER, 
	"WAIT_TIME" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARTITION BY RANGE ("DBID","SNAP_ID") 
 (PARTITION "WRH$_LATCH_692950692_0"  VALUES LESS THAN (692950692, MAXVALUE) 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRH$_LATCH_MXDB_MXSN"  VALUES LESS THAN (MAXVALUE, MAXVALUE) 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" )  ENABLE ROW MOVEMENT ;
  GRANT DELETE ON "SYS"."WRH$_LATCH" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_LATCH" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_LATCH" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_LATCH" TO "SYSUMF_ROLE";
