--------------------------------------------------------
--  Constraints for Table WRH$_ASM_BAD_DISK
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_ASM_BAD_DISK" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_ASM_BAD_DISK" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_ASM_BAD_DISK" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_ASM_BAD_DISK" MODIFY ("GROUP_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_ASM_BAD_DISK" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_ASM_BAD_DISK" ADD CONSTRAINT "WRH$_ASM_BAD_DISK_PK" PRIMARY KEY ("SNAP_ID", "DBID", "GROUP_NUMBER", "NAME", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
