--------------------------------------------------------
--  Constraints for Table WRH$_CLUSTER_INTERCON
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_CLUSTER_INTERCON" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CLUSTER_INTERCON" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CLUSTER_INTERCON" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CLUSTER_INTERCON" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CLUSTER_INTERCON" MODIFY ("IP_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CLUSTER_INTERCON" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CLUSTER_INTERCON" ADD CONSTRAINT "WRH$_CLUSTER_INTERCON_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "NAME", "IP_ADDRESS", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
