--------------------------------------------------------
--  DDL for Table WRH$_TEMPFILE
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_TEMPFILE" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"FILE#" NUMBER, 
	"CREATION_CHANGE#" NUMBER, 
	"FILENAME" VARCHAR2(513 BYTE), 
	"TS#" NUMBER, 
	"TSNAME" VARCHAR2(30 BYTE), 
	"BLOCK_SIZE" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_TEMPFILE" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_TEMPFILE" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_TEMPFILE" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_TEMPFILE" TO "SYSUMF_ROLE";
