--------------------------------------------------------
--  Constraints for Table WRH$_SERVICE_NAME
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_SERVICE_NAME" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SERVICE_NAME" MODIFY ("SERVICE_NAME_HASH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SERVICE_NAME" MODIFY ("SERVICE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SERVICE_NAME" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SERVICE_NAME" ADD CONSTRAINT "WRH$_SERVICE_NAME_PK" PRIMARY KEY ("DBID", "SERVICE_NAME_HASH", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
