--------------------------------------------------------
--  DDL for Table WRH$_BUFFERED_SUBSCRIBERS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_BUFFERED_SUBSCRIBERS" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"QUEUE_SCHEMA" VARCHAR2(128 BYTE), 
	"QUEUE_NAME" VARCHAR2(128 BYTE), 
	"SUBSCRIBER_ID" NUMBER, 
	"SUBSCRIBER_NAME" VARCHAR2(128 BYTE), 
	"SUBSCRIBER_ADDRESS" VARCHAR2(1024 BYTE), 
	"SUBSCRIBER_TYPE" VARCHAR2(128 BYTE), 
	"STARTUP_TIME" DATE, 
	"NUM_MSGS" NUMBER, 
	"CNUM_MSGS" NUMBER, 
	"TOTAL_SPILLED_MSG" NUMBER, 
	"LAST_BROWSED_SEQ" NUMBER, 
	"LAST_BROWSED_NUM" NUMBER, 
	"LAST_DEQUEUED_SEQ" NUMBER, 
	"LAST_DEQUEUED_NUM" NUMBER, 
	"CURRENT_ENQ_SEQ" NUMBER, 
	"TOTAL_DEQUEUED_MSG" NUMBER, 
	"EXPIRED_MSGS" NUMBER, 
	"MESSAGE_LAG" NUMBER, 
	"ELAPSED_DEQUEUE_TIME" NUMBER, 
	"DEQUEUE_CPU_TIME" NUMBER, 
	"LAST_DEQUEUE_TIME" TIMESTAMP (3), 
	"OLDEST_MSGID" RAW(16), 
	"OLDEST_MSG_ENQTM" TIMESTAMP (3), 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_BUFFERED_SUBSCRIBERS" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_BUFFERED_SUBSCRIBERS" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_BUFFERED_SUBSCRIBERS" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_BUFFERED_SUBSCRIBERS" TO "SYSUMF_ROLE";
