--------------------------------------------------------
--  DDL for Table WRH$_OPTIMIZER_ENV
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_OPTIMIZER_ENV" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"OPTIMIZER_ENV_HASH_VALUE" NUMBER, 
	"OPTIMIZER_ENV" RAW(2000), 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_OPTIMIZER_ENV" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_OPTIMIZER_ENV" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_OPTIMIZER_ENV" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_OPTIMIZER_ENV" TO "SYSUMF_ROLE";
