--------------------------------------------------------
--  Constraints for Table WRH$_IOSTAT_FILETYPE_NAME
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_IOSTAT_FILETYPE_NAME" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_FILETYPE_NAME" MODIFY ("FILETYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_FILETYPE_NAME" MODIFY ("FILETYPE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_FILETYPE_NAME" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_FILETYPE_NAME" ADD CONSTRAINT "WRH$_IOSTAT_FILETYPE_NAME_PK" PRIMARY KEY ("DBID", "FILETYPE_ID", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
