--------------------------------------------------------
--  Constraints for Table WRH$_PARAMETER_NAME
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_PARAMETER_NAME" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_PARAMETER_NAME" MODIFY ("PARAMETER_HASH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_PARAMETER_NAME" MODIFY ("PARAMETER_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_PARAMETER_NAME" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_PARAMETER_NAME" ADD CONSTRAINT "WRH$_PARAMETER_NAME_PK" PRIMARY KEY ("DBID", "PARAMETER_HASH", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
