--------------------------------------------------------
--  Constraints for Table WRH$_INTERCONNECT_PINGS_BL
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_INTERCONNECT_PINGS_BL" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_INTERCONNECT_PINGS_BL" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_INTERCONNECT_PINGS_BL" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_INTERCONNECT_PINGS_BL" MODIFY ("TARGET_INSTANCE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_INTERCONNECT_PINGS_BL" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_INTERCONNECT_PINGS_BL" ADD CONSTRAINT "WRH$_INTERCONNECT_PINGS_BL_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "TARGET_INSTANCE", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
