--------------------------------------------------------
--  Constraints for Table WRH$_SQLTEXT
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_SQLTEXT" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SQLTEXT" MODIFY ("SQL_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SQLTEXT" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SQLTEXT" ADD CONSTRAINT "WRH$_SQLTEXT_PK" PRIMARY KEY ("DBID", "SQL_ID", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
