--------------------------------------------------------
--  DDL for Table WRH$_CR_BLOCK_SERVER
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_CR_BLOCK_SERVER" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"CR_REQUESTS" NUMBER, 
	"CURRENT_REQUESTS" NUMBER, 
	"DATA_REQUESTS" NUMBER, 
	"UNDO_REQUESTS" NUMBER, 
	"TX_REQUESTS" NUMBER, 
	"CURRENT_RESULTS" NUMBER, 
	"PRIVATE_RESULTS" NUMBER, 
	"ZERO_RESULTS" NUMBER, 
	"DISK_READ_RESULTS" NUMBER, 
	"FAIL_RESULTS" NUMBER, 
	"FAIRNESS_DOWN_CONVERTS" NUMBER, 
	"FAIRNESS_CLEARS" NUMBER, 
	"FREE_GC_ELEMENTS" NUMBER, 
	"FLUSHES" NUMBER, 
	"FLUSHES_QUEUED" NUMBER, 
	"FLUSH_QUEUE_FULL" NUMBER, 
	"FLUSH_MAX_TIME" NUMBER, 
	"LIGHT_WORKS" NUMBER, 
	"ERRORS" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"BUILDS" NUMBER, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_CR_BLOCK_SERVER" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_CR_BLOCK_SERVER" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_CR_BLOCK_SERVER" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_CR_BLOCK_SERVER" TO "SYSUMF_ROLE";
