--------------------------------------------------------
--  Constraints for Table WRH$_MEM_DYNAMIC_COMP
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_MEM_DYNAMIC_COMP" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_MEM_DYNAMIC_COMP" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_MEM_DYNAMIC_COMP" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_MEM_DYNAMIC_COMP" MODIFY ("COMPONENT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_MEM_DYNAMIC_COMP" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_MEM_DYNAMIC_COMP" ADD CONSTRAINT "WRH$_MEM_DYNAMIC_COMP_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "COMPONENT", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
