--------------------------------------------------------
--  DDL for Table WRH$_IM_SEG_STAT_BL
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_IM_SEG_STAT_BL" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"TS#" NUMBER, 
	"OBJ#" NUMBER, 
	"DATAOBJ#" NUMBER, 
	"MEMBYTES" NUMBER, 
	"SCANS" NUMBER, 
	"SCANS_DELTA" NUMBER, 
	"DB_BLOCK_CHANGES" NUMBER, 
	"DB_BLOCK_CHANGES_DELTA" NUMBER, 
	"POPULATE_CUS" NUMBER, 
	"POPULATE_CUS_DELTA" NUMBER, 
	"REPOPULATE_CUS" NUMBER, 
	"REPOPULATE_CUS_DELTA" NUMBER, 
	"CON_DBID" NUMBER, 
	"PER_PDB" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
