--------------------------------------------------------
--  DDL for Table WRH$_CELL_OPEN_ALERTS_BL
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_CELL_OPEN_ALERTS_BL" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"CELL_HASH" NUMBER, 
	"CON_DBID" NUMBER, 
	"BEGIN_TIME" DATE, 
	"SEQ_NO" NUMBER, 
	"MESSAGE" VARCHAR2(1024 BYTE), 
	"STATEFUL" NUMBER, 
	"SEVERITY" VARCHAR2(32 BYTE), 
	"CELL_ALERT_SUMMARY" VARCHAR2(64 BYTE), 
	"PER_PDB" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
