--------------------------------------------------------
--  DDL for Table WRH$_BG_EVENT_SUMMARY
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_BG_EVENT_SUMMARY" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"EVENT_ID" NUMBER, 
	"TOTAL_WAITS" NUMBER, 
	"TOTAL_TIMEOUTS" NUMBER, 
	"TIME_WAITED_MICRO" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_BG_EVENT_SUMMARY" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_BG_EVENT_SUMMARY" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_BG_EVENT_SUMMARY" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_BG_EVENT_SUMMARY" TO "SYSUMF_ROLE";
