--------------------------------------------------------
--  Constraints for Table WRH$_IOSTAT_DETAIL
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_IOSTAT_DETAIL" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_DETAIL" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_DETAIL" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_DETAIL" MODIFY ("FUNCTION_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_DETAIL" MODIFY ("FILETYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_DETAIL" MODIFY ("SMALL_READ_MEGABYTES" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_DETAIL" MODIFY ("SMALL_WRITE_MEGABYTES" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_DETAIL" MODIFY ("LARGE_READ_MEGABYTES" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_DETAIL" MODIFY ("LARGE_WRITE_MEGABYTES" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_DETAIL" MODIFY ("SMALL_READ_REQS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_DETAIL" MODIFY ("SMALL_WRITE_REQS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_DETAIL" MODIFY ("LARGE_READ_REQS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_DETAIL" MODIFY ("LARGE_WRITE_REQS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_DETAIL" MODIFY ("NUMBER_OF_WAITS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_DETAIL" MODIFY ("WAIT_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_DETAIL" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IOSTAT_DETAIL" ADD CONSTRAINT "WRH$_IOSTAT_DETAIL_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "FUNCTION_ID", "FILETYPE_ID", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
