--------------------------------------------------------
--  DDL for Table WRH$_PERSISTENT_QUEUES
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_PERSISTENT_QUEUES" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"QUEUE_SCHEMA" VARCHAR2(128 BYTE), 
	"QUEUE_NAME" VARCHAR2(128 BYTE), 
	"QUEUE_ID" NUMBER, 
	"FIRST_ACTIVITY_TIME" TIMESTAMP (6), 
	"ENQUEUED_MSGS" NUMBER, 
	"DEQUEUED_MSGS" NUMBER, 
	"ELAPSED_ENQUEUE_TIME" NUMBER, 
	"ELAPSED_DEQUEUE_TIME" NUMBER, 
	"ELAPSED_TRANSFORMATION_TIME" NUMBER, 
	"ELAPSED_RULE_EVALUATION_TIME" NUMBER, 
	"ENQUEUED_EXPIRY_MSGS" NUMBER, 
	"ENQUEUED_DELAY_MSGS" NUMBER, 
	"MSGS_MADE_EXPIRED" NUMBER, 
	"MSGS_MADE_READY" NUMBER, 
	"LAST_ENQUEUE_TIME" TIMESTAMP (6), 
	"LAST_DEQUEUE_TIME" TIMESTAMP (6), 
	"LAST_TM_EXPIRY_TIME" TIMESTAMP (6), 
	"LAST_TM_READY_TIME" TIMESTAMP (6), 
	"BROWSED_MSGS" NUMBER, 
	"ENQUEUE_CPU_TIME" NUMBER, 
	"DEQUEUE_CPU_TIME" NUMBER, 
	"AVG_MSG_AGE" NUMBER, 
	"DEQUEUED_MSG_LATENCY" NUMBER, 
	"ENQUEUE_TRANSACTIONS" NUMBER, 
	"DEQUEUE_TRANSACTIONS" NUMBER, 
	"EXECUTION_COUNT" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_PERSISTENT_QUEUES" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_PERSISTENT_QUEUES" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_PERSISTENT_QUEUES" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_PERSISTENT_QUEUES" TO "SYSUMF_ROLE";
