--------------------------------------------------------
--  DDL for Table WRH$_LOG
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_LOG" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"GROUP#" NUMBER, 
	"THREAD#" NUMBER, 
	"SEQUENCE#" NUMBER, 
	"BYTES" NUMBER, 
	"MEMBERS" NUMBER, 
	"ARCHIVED" VARCHAR2(3 BYTE), 
	"STATUS" VARCHAR2(16 BYTE), 
	"FIRST_CHANGE#" NUMBER, 
	"FIRST_TIME" DATE, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_LOG" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_LOG" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_LOG" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_LOG" TO "SYSUMF_ROLE";
