--------------------------------------------------------
--  Constraints for Table WRH$_FILESTATXS_BL
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_FILESTATXS_BL" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_FILESTATXS_BL" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_FILESTATXS_BL" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_FILESTATXS_BL" MODIFY ("FILE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_FILESTATXS_BL" MODIFY ("CREATION_CHANGE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_FILESTATXS_BL" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_FILESTATXS_BL" ADD CONSTRAINT "WRH$_FILESTATXS_BL_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "FILE#", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
