--------------------------------------------------------
--  Constraints for Table WRH$_RECOVERY_PROGRESS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_RECOVERY_PROGRESS" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RECOVERY_PROGRESS" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RECOVERY_PROGRESS" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RECOVERY_PROGRESS" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RECOVERY_PROGRESS" ADD CONSTRAINT "WRH$_RECOVERY_PROGRESS_PK" PRIMARY KEY ("SNAP_ID", "DBID", "INSTANCE_NUMBER", "TYPE", "ITEM", "START_TIME", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
