--------------------------------------------------------
--  DDL for Table WRH$_SESS_NETWORK
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_SESS_NETWORK" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"SESSION_ID" NUMBER, 
	"SERIAL#" NUMBER, 
	"CHANNEL_ID" NUMBER, 
	"BUSY_TIME" NUMBER, 
	"BUSY_TIME_DELTA" NUMBER, 
	"RECV_WIN_LIMITED" NUMBER, 
	"RECV_WIN_LIMITED_DELTA" NUMBER, 
	"SEND_BUF_LIMITED" NUMBER, 
	"SEND_BUF_LIMITED_DELTA" NUMBER, 
	"CONGESTION_TIME" NUMBER, 
	"CONGESTION_TIME_DELTA" NUMBER, 
	"LOST_PACKET" NUMBER, 
	"NUM_RETRANSMIT_PACKET" NUMBER, 
	"BYTES_ACKED" NUMBER, 
	"BYTES_RECEIVED" NUMBER, 
	"SEGMENTS_IN" NUMBER, 
	"SEGMENTS_OUT" NUMBER, 
	"ROUND_TRIP_TIME" NUMBER, 
	"ROUND_TRIP_VAR" NUMBER, 
	"SEND_CONGESTION_WIN" NUMBER, 
	"ADVERTISED_SEND_WIN" NUMBER, 
	"ADVERTISED_RECV_WIN" NUMBER, 
	"LAST_DATA_SENT_TIME" NUMBER, 
	"LAST_DATA_RECV_TIME" NUMBER, 
	"LAST_ACK_SENT_TIME" NUMBER, 
	"LAST_ACK_RECV_TIME" NUMBER, 
	"PATH_MAX_TRANSMISSION_UNIT" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARTITION BY RANGE ("DBID","SNAP_ID") 
 (PARTITION "WRH$_SESS_NETWORK_692950692_0"  VALUES LESS THAN (692950692, MAXVALUE) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRH$_SESS_NETWORK_MXDB_MXSN"  VALUES LESS THAN (MAXVALUE, MAXVALUE) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ) ;
  GRANT DELETE ON "SYS"."WRH$_SESS_NETWORK" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_SESS_NETWORK" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_SESS_NETWORK" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_SESS_NETWORK" TO "SYSUMF_ROLE";
