--------------------------------------------------------
--  Constraints for Table WRH$_ASM_DISK_STAT_SUMMARY_BL
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_ASM_DISK_STAT_SUMMARY_BL" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_ASM_DISK_STAT_SUMMARY_BL" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_ASM_DISK_STAT_SUMMARY_BL" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_ASM_DISK_STAT_SUMMARY_BL" MODIFY ("GROUP_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_ASM_DISK_STAT_SUMMARY_BL" ADD CONSTRAINT "WRH$_ASM_DISK_STAT_SUMM_BL_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "GROUP_NUMBER", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
