--------------------------------------------------------
--  Constraints for Table WRH$_REPLICATION_TXN_STATS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_REPLICATION_TXN_STATS" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_REPLICATION_TXN_STATS" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_REPLICATION_TXN_STATS" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_REPLICATION_TXN_STATS" MODIFY ("OBJECT_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_REPLICATION_TXN_STATS" MODIFY ("SESSION_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_REPLICATION_TXN_STATS" MODIFY ("SESSION_MODULE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_REPLICATION_TXN_STATS" MODIFY ("SOURCE_TXN_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_REPLICATION_TXN_STATS" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_REPLICATION_TXN_STATS" ADD CONSTRAINT "WRH$_REPLICATION_TXN_STATS_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "OBJECT_NAME", "SESSION_TYPE", "SESSION_MODULE", "SOURCE_TXN_ID", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
