--------------------------------------------------------
--  Constraints for Table WRH$_THREAD
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_THREAD" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_THREAD" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_THREAD" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_THREAD" MODIFY ("THREAD#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_THREAD" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_THREAD" ADD CONSTRAINT "WRH$_THREAD_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "THREAD#", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
