--------------------------------------------------------
--  DDL for Table WRH$_THREAD
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_THREAD" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"THREAD#" NUMBER, 
	"THREAD_INSTANCE_NUMBER" NUMBER, 
	"STATUS" VARCHAR2(6 BYTE), 
	"OPEN_TIME" DATE, 
	"CURRENT_GROUP#" NUMBER, 
	"SEQUENCE#" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_THREAD" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_THREAD" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_THREAD" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_THREAD" TO "SYSUMF_ROLE";
