--------------------------------------------------------
--  Constraints for Table WRH$_STREAMS_APPLY_SUM
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_STREAMS_APPLY_SUM" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_STREAMS_APPLY_SUM" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_STREAMS_APPLY_SUM" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_STREAMS_APPLY_SUM" MODIFY ("APPLY_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_STREAMS_APPLY_SUM" MODIFY ("STARTUP_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_STREAMS_APPLY_SUM" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_STREAMS_APPLY_SUM" MODIFY ("SESSION_MODULE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_STREAMS_APPLY_SUM" ADD CONSTRAINT "WRH$_STREAMS_APPLY_SUM_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "APPLY_NAME", "SESSION_MODULE", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
