--------------------------------------------------------
--  Constraints for Table WRH$_TABLESPACE
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_TABLESPACE" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_TABLESPACE" MODIFY ("TS#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_TABLESPACE" MODIFY ("TSNAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_TABLESPACE" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_TABLESPACE" ADD CONSTRAINT "WRH$_TABLESPACE_PK" PRIMARY KEY ("DBID", "TS#", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
