--------------------------------------------------------
--  DDL for Table WRH$_SESS_SGA_STATS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_SESS_SGA_STATS" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"OBJECT_NAME" VARCHAR2(128 BYTE), 
	"SESSION_TYPE" VARCHAR2(64 BYTE), 
	"SESSION_MODULE" VARCHAR2(64 BYTE), 
	"SGA_USED" NUMBER, 
	"SGA_ALLOCATED" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_SESS_SGA_STATS" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_SESS_SGA_STATS" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_SESS_SGA_STATS" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_SESS_SGA_STATS" TO "SYSUMF_ROLE";
