--------------------------------------------------------
--  Constraints for Table WRH$_SEG_STAT_OBJ
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_SEG_STAT_OBJ" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SEG_STAT_OBJ" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SEG_STAT_OBJ" MODIFY ("OWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SEG_STAT_OBJ" MODIFY ("OBJECT_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SEG_STAT_OBJ" MODIFY ("TABLESPACE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SEG_STAT_OBJ" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SEG_STAT_OBJ" ADD CONSTRAINT "WRH$_SEG_STAT_OBJ_PK" PRIMARY KEY ("DBID", "TS#", "OBJ#", "DATAOBJ#", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
