--------------------------------------------------------
--  DDL for Table WRH$_IM_SEG_STAT_OBJ
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_IM_SEG_STAT_OBJ" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"TS#" NUMBER, 
	"OBJ#" NUMBER, 
	"DATAOBJ#" NUMBER, 
	"OWNER" VARCHAR2(128 BYTE), 
	"OBJECT_NAME" VARCHAR2(128 BYTE), 
	"SUBOBJECT_NAME" VARCHAR2(128 BYTE), 
	"OBJECT_TYPE" VARCHAR2(128 BYTE), 
	"TABLESPACE_NAME" VARCHAR2(128 BYTE), 
	"CON_DBID" NUMBER, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_IM_SEG_STAT_OBJ" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_IM_SEG_STAT_OBJ" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_IM_SEG_STAT_OBJ" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_IM_SEG_STAT_OBJ" TO "SYSUMF_ROLE";
