--------------------------------------------------------
--  DDL for Table WRH$_FILESTATXS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_FILESTATXS" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"FILE#" NUMBER, 
	"CREATION_CHANGE#" NUMBER, 
	"PHYRDS" NUMBER, 
	"PHYWRTS" NUMBER, 
	"SINGLEBLKRDS" NUMBER, 
	"READTIM" NUMBER, 
	"WRITETIM" NUMBER, 
	"SINGLEBLKRDTIM" NUMBER, 
	"PHYBLKRD" NUMBER, 
	"PHYBLKWRT" NUMBER, 
	"WAIT_COUNT" NUMBER, 
	"TIME" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"OPTIMIZED_PHYBLKRD" NUMBER, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARTITION BY RANGE ("DBID","SNAP_ID") 
 (PARTITION "WRH$_FILESTATXS_692950692_0"  VALUES LESS THAN (692950692, MAXVALUE) 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRH$_FILESTATXS_MXDB_MXSN"  VALUES LESS THAN (MAXVALUE, MAXVALUE) 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" )  ENABLE ROW MOVEMENT ;
  GRANT DELETE ON "SYS"."WRH$_FILESTATXS" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_FILESTATXS" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_FILESTATXS" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_FILESTATXS" TO "SYSUMF_ROLE";
