--------------------------------------------------------
--  DDL for Table WRH$_JAVA_POOL_ADVICE
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_JAVA_POOL_ADVICE" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"JAVA_POOL_SIZE_FOR_ESTIMATE" NUMBER, 
	"JAVA_POOL_SIZE_FACTOR" NUMBER, 
	"ESTD_LC_SIZE" NUMBER, 
	"ESTD_LC_MEMORY_OBJECTS" NUMBER, 
	"ESTD_LC_TIME_SAVED" NUMBER, 
	"ESTD_LC_TIME_SAVED_FACTOR" NUMBER, 
	"ESTD_LC_LOAD_TIME" NUMBER, 
	"ESTD_LC_LOAD_TIME_FACTOR" NUMBER, 
	"ESTD_LC_MEMORY_OBJECT_HITS" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_JAVA_POOL_ADVICE" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_JAVA_POOL_ADVICE" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_JAVA_POOL_ADVICE" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_JAVA_POOL_ADVICE" TO "SYSUMF_ROLE";
