--------------------------------------------------------
--  DDL for Table WRH$_TEMPSTATXS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_TEMPSTATXS" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"FILE#" NUMBER, 
	"CREATION_CHANGE#" NUMBER, 
	"PHYRDS" NUMBER, 
	"PHYWRTS" NUMBER, 
	"SINGLEBLKRDS" NUMBER, 
	"READTIM" NUMBER, 
	"WRITETIM" NUMBER, 
	"SINGLEBLKRDTIM" NUMBER, 
	"PHYBLKRD" NUMBER, 
	"PHYBLKWRT" NUMBER, 
	"WAIT_COUNT" NUMBER, 
	"TIME" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_TEMPSTATXS" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_TEMPSTATXS" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_TEMPSTATXS" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_TEMPSTATXS" TO "SYSUMF_ROLE";
