--------------------------------------------------------
--  DDL for Table WRH$_CELL_CONFIG
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_CELL_CONFIG" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"CON_DBID" NUMBER, 
	"CURRENT_SNAP_ID" NUMBER, 
	"CELLNAME" VARCHAR2(256 BYTE), 
	"CELLHASH" NUMBER, 
	"CONFTYPE" VARCHAR2(15 BYTE), 
	"CONFVAL_HASH" NUMBER, 
	"CONFVAL" CLOB, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" 
 LOB ("CONFVAL") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
  GRANT DELETE ON "SYS"."WRH$_CELL_CONFIG" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_CELL_CONFIG" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_CELL_CONFIG" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_CELL_CONFIG" TO "SYSUMF_ROLE";
