--------------------------------------------------------
--  DDL for Table WRH$_PROCESS_MEMORY_SUMMARY
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_PROCESS_MEMORY_SUMMARY" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"CATEGORY" VARCHAR2(15 BYTE), 
	"NUM_PROCESSES" NUMBER, 
	"NON_ZERO_ALLOCS" NUMBER, 
	"USED_TOTAL" NUMBER, 
	"ALLOCATED_TOTAL" NUMBER, 
	"ALLOCATED_STDDEV" NUMBER, 
	"ALLOCATED_MAX" NUMBER, 
	"MAX_ALLOCATED_MAX" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null, 
	"PER_PDB_NN" NUMBER DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_PROCESS_MEMORY_SUMMARY" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_PROCESS_MEMORY_SUMMARY" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_PROCESS_MEMORY_SUMMARY" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_PROCESS_MEMORY_SUMMARY" TO "SYSUMF_ROLE";
