--------------------------------------------------------
--  DDL for Table WRH$_LATCH_MISSES_SUMMARY_BL
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_LATCH_MISSES_SUMMARY_BL" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"PARENT_NAME" VARCHAR2(50 BYTE), 
	"WHERE_IN_CODE" VARCHAR2(64 BYTE), 
	"NWFAIL_COUNT" NUMBER, 
	"SLEEP_COUNT" NUMBER, 
	"WTR_SLP_COUNT" NUMBER, 
	"CON_DBID" NUMBER, 
	"PER_PDB" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
