--------------------------------------------------------
--  DDL for Table WRH$_SYSMETRIC_SUMMARY
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_SYSMETRIC_SUMMARY" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"BEGIN_TIME" DATE, 
	"END_TIME" DATE, 
	"INTSIZE" NUMBER, 
	"GROUP_ID" NUMBER, 
	"METRIC_ID" NUMBER, 
	"NUM_INTERVAL" NUMBER, 
	"MAXVAL" NUMBER, 
	"MINVAL" NUMBER, 
	"AVERAGE" NUMBER, 
	"STANDARD_DEVIATION" NUMBER, 
	"SUM_SQUARES" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_SYSMETRIC_SUMMARY" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_SYSMETRIC_SUMMARY" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_SYSMETRIC_SUMMARY" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_SYSMETRIC_SUMMARY" TO "SYSUMF_ROLE";
