--------------------------------------------------------
--  DDL for Index WRH$_ROWCACHE_SUMMARY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."WRH$_ROWCACHE_SUMMARY_PK" ON "SYS"."WRH$_ROWCACHE_SUMMARY" ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "PARAMETER", "CON_DBID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  LOCAL
 (PARTITION "WRH$_ROWCACHE_SUMMARY_692950692_0" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRH$_ROWCACHE_SU_MXDB_MXSN" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ) ;
