--------------------------------------------------------
--  Constraints for Table WRH$_ENQUEUE_STAT
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_ENQUEUE_STAT" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_ENQUEUE_STAT" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_ENQUEUE_STAT" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_ENQUEUE_STAT" MODIFY ("EQ_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_ENQUEUE_STAT" MODIFY ("REQ_REASON" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_ENQUEUE_STAT" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_ENQUEUE_STAT" ADD CONSTRAINT "WRH$_ENQUEUE_STAT_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "EQ_TYPE", "REQ_REASON", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
