--------------------------------------------------------
--  Constraints for Table WRH$_CELL_CONFIG_DETAIL
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_CELL_CONFIG_DETAIL" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CELL_CONFIG_DETAIL" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CELL_CONFIG_DETAIL" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CELL_CONFIG_DETAIL" MODIFY ("CELLHASH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CELL_CONFIG_DETAIL" MODIFY ("CONFVAL_HASH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CELL_CONFIG_DETAIL" ADD CONSTRAINT "WRH$_CELL_CONFIG_DETAIL_PK" PRIMARY KEY ("DBID", "SNAP_ID", "CELLHASH", "CONFTYPE", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
