--------------------------------------------------------
--  Constraints for Table WRH$_SEG_STAT_BL
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_SEG_STAT_BL" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SEG_STAT_BL" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SEG_STAT_BL" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SEG_STAT_BL" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SEG_STAT_BL" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SEG_STAT_BL" ADD CONSTRAINT "WRH$_SEG_STAT_BL_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "TS#", "OBJ#", "DATAOBJ#", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
