--------------------------------------------------------
--  Constraints for Table WRH$_DISPATCHER
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_DISPATCHER" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_DISPATCHER" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_DISPATCHER" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_DISPATCHER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_DISPATCHER" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_DISPATCHER" ADD CONSTRAINT "WRH$_DISPATCHER_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "NAME", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
