--------------------------------------------------------
--  Constraints for Table WRH$_LIBRARYCACHE
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_LIBRARYCACHE" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LIBRARYCACHE" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LIBRARYCACHE" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LIBRARYCACHE" MODIFY ("NAMESPACE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LIBRARYCACHE" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LIBRARYCACHE" ADD CONSTRAINT "WRH$_LIBRARYCACHE_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "NAMESPACE", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
