--------------------------------------------------------
--  DDL for Table WRH$_LATCH_NAME
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_LATCH_NAME" SHARING=METADATA 
   (	"DBID" NUMBER, 
	"LATCH_HASH" NUMBER, 
	"LATCH_NAME" VARCHAR2(64 BYTE), 
	"LATCH#" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_LATCH_NAME" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_LATCH_NAME" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_LATCH_NAME" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_LATCH_NAME" TO "SYSUMF_ROLE";
