--------------------------------------------------------
--  Constraints for Table WRH$_SESSMETRIC_HISTORY
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_SESSMETRIC_HISTORY" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SESSMETRIC_HISTORY" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SESSMETRIC_HISTORY" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SESSMETRIC_HISTORY" MODIFY ("BEGIN_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SESSMETRIC_HISTORY" MODIFY ("END_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SESSMETRIC_HISTORY" MODIFY ("SESSID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SESSMETRIC_HISTORY" MODIFY ("SERIAL#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SESSMETRIC_HISTORY" MODIFY ("INTSIZE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SESSMETRIC_HISTORY" MODIFY ("GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SESSMETRIC_HISTORY" MODIFY ("METRIC_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SESSMETRIC_HISTORY" MODIFY ("VALUE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SESSMETRIC_HISTORY" MODIFY ("CON_DBID" NOT NULL ENABLE);
