--------------------------------------------------------
--  DDL for Table WRH$_CHANNEL_WAITS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_CHANNEL_WAITS" SHARING=METADATA 
   (	"DBID" NUMBER, 
	"SNAP_ID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"CHANNEL" VARCHAR2(64 BYTE), 
	"MESSAGES_PUBLISHED" NUMBER, 
	"WAIT_COUNT" NUMBER, 
	"WAIT_TIME_USEC" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
  GRANT DELETE ON "SYS"."WRH$_CHANNEL_WAITS" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_CHANNEL_WAITS" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_CHANNEL_WAITS" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_CHANNEL_WAITS" TO "SYSUMF_ROLE";
