--------------------------------------------------------
--  Constraints for Table WRH$_IC_CLIENT_STATS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_IC_CLIENT_STATS" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IC_CLIENT_STATS" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IC_CLIENT_STATS" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IC_CLIENT_STATS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IC_CLIENT_STATS" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IC_CLIENT_STATS" ADD CONSTRAINT "WRH$_IC_CLIENT_STATS_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "NAME", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
