--------------------------------------------------------
--  DDL for Table WRH$_STREAMS_APPLY_SUM
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_STREAMS_APPLY_SUM" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"APPLY_NAME" VARCHAR2(128 BYTE), 
	"STARTUP_TIME" DATE, 
	"READER_TOTAL_MESSAGES_DEQUEUED" NUMBER, 
	"READER_LAG" NUMBER, 
	"COORD_TOTAL_RECEIVED" NUMBER, 
	"COORD_TOTAL_APPLIED" NUMBER, 
	"COORD_TOTAL_ROLLBACKS" NUMBER, 
	"COORD_TOTAL_WAIT_DEPS" NUMBER, 
	"COORD_TOTAL_WAIT_CMTS" NUMBER, 
	"COORD_LWM_LAG" NUMBER, 
	"SERVER_TOTAL_MESSAGES_APPLIED" NUMBER, 
	"SERVER_ELAPSED_DEQUEUE_TIME" NUMBER, 
	"SERVER_ELAPSED_APPLY_TIME" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"REPLICAT_NAME" VARCHAR2(128 BYTE), 
	"UNASSIGNED_COMPLETE_TXN" NUMBER, 
	"TOTAL_LCRS_RETRIED" NUMBER, 
	"TOTAL_TRANSACTIONS_RETRIED" NUMBER, 
	"TOTAL_ERRORS" NUMBER, 
	"SESSION_MODULE" VARCHAR2(64 BYTE) DEFAULT 'Streams', 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_STREAMS_APPLY_SUM" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_STREAMS_APPLY_SUM" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_STREAMS_APPLY_SUM" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_STREAMS_APPLY_SUM" TO "SYSUMF_ROLE";
