--------------------------------------------------------
--  DDL for Table WRH$_STREAMS_POOL_ADVICE
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_STREAMS_POOL_ADVICE" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"SIZE_FOR_ESTIMATE" NUMBER, 
	"SIZE_FACTOR" NUMBER, 
	"ESTD_SPILL_COUNT" NUMBER, 
	"ESTD_SPILL_TIME" NUMBER, 
	"ESTD_UNSPILL_COUNT" NUMBER, 
	"ESTD_UNSPILL_TIME" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_STREAMS_POOL_ADVICE" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_STREAMS_POOL_ADVICE" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_STREAMS_POOL_ADVICE" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_STREAMS_POOL_ADVICE" TO "SYSUMF_ROLE";
