--------------------------------------------------------
--  DDL for Table WRH$_BUFFERED_QUEUES
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_BUFFERED_QUEUES" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"QUEUE_SCHEMA" VARCHAR2(128 BYTE), 
	"QUEUE_NAME" VARCHAR2(128 BYTE), 
	"STARTUP_TIME" DATE, 
	"QUEUE_ID" NUMBER, 
	"NUM_MSGS" NUMBER, 
	"SPILL_MSGS" NUMBER, 
	"CNUM_MSGS" NUMBER, 
	"CSPILL_MSGS" NUMBER, 
	"EXPIRED_MSGS" NUMBER, 
	"OLDEST_MSGID" RAW(16), 
	"OLDEST_MSG_ENQTM" TIMESTAMP (3), 
	"QUEUE_STATE" VARCHAR2(25 BYTE), 
	"ELAPSED_ENQUEUE_TIME" NUMBER, 
	"ELAPSED_DEQUEUE_TIME" NUMBER, 
	"ELAPSED_TRANSFORMATION_TIME" NUMBER, 
	"ELAPSED_RULE_EVALUATION_TIME" NUMBER, 
	"ENQUEUE_CPU_TIME" NUMBER, 
	"DEQUEUE_CPU_TIME" NUMBER, 
	"LAST_ENQUEUE_TIME" TIMESTAMP (3), 
	"LAST_DEQUEUE_TIME" TIMESTAMP (3), 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_BUFFERED_QUEUES" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_BUFFERED_QUEUES" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_BUFFERED_QUEUES" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_BUFFERED_QUEUES" TO "SYSUMF_ROLE";
