--------------------------------------------------------
--  Constraints for Table WRH$_EVENT_HISTOGRAM_BL
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_EVENT_HISTOGRAM_BL" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_EVENT_HISTOGRAM_BL" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_EVENT_HISTOGRAM_BL" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_EVENT_HISTOGRAM_BL" MODIFY ("EVENT_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_EVENT_HISTOGRAM_BL" MODIFY ("WAIT_TIME_MILLI" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_EVENT_HISTOGRAM_BL" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_EVENT_HISTOGRAM_BL" ADD CONSTRAINT "WRH$_EVENT_HISTOGRAM_BL_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "EVENT_ID", "WAIT_TIME_MILLI", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
