--------------------------------------------------------
--  DDL for Table WRH$_METRIC_NAME
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_METRIC_NAME" SHARING=METADATA 
   (	"DBID" NUMBER, 
	"GROUP_ID" NUMBER, 
	"GROUP_NAME" VARCHAR2(64 BYTE), 
	"METRIC_ID" NUMBER, 
	"METRIC_NAME" VARCHAR2(64 BYTE), 
	"METRIC_UNIT" VARCHAR2(64 BYTE), 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_METRIC_NAME" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_METRIC_NAME" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_METRIC_NAME" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_METRIC_NAME" TO "SYSUMF_ROLE";
