--------------------------------------------------------
--  DDL for Table WRH$_LATCH_BL
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_LATCH_BL" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"LATCH_HASH" NUMBER, 
	"LEVEL#" NUMBER, 
	"GETS" NUMBER, 
	"MISSES" NUMBER, 
	"SLEEPS" NUMBER, 
	"IMMEDIATE_GETS" NUMBER, 
	"IMMEDIATE_MISSES" NUMBER, 
	"SPIN_GETS" NUMBER, 
	"SLEEP1" NUMBER, 
	"SLEEP2" NUMBER, 
	"SLEEP3" NUMBER, 
	"SLEEP4" NUMBER, 
	"WAIT_TIME" NUMBER, 
	"CON_DBID" NUMBER, 
	"PER_PDB" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
