--------------------------------------------------------
--  Constraints for Table WRH$_PLAN_OPTION_NAME
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_PLAN_OPTION_NAME" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_PLAN_OPTION_NAME" MODIFY ("OPTION_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_PLAN_OPTION_NAME" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_PLAN_OPTION_NAME" ADD CONSTRAINT "WRH$_PLAN_OPTION_NAME_PK" PRIMARY KEY ("DBID", "OPTION_ID", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
