--------------------------------------------------------
--  Constraints for Table WRH$_SESS_NETWORK_BL
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_SESS_NETWORK_BL" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SESS_NETWORK_BL" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SESS_NETWORK_BL" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SESS_NETWORK_BL" MODIFY ("SESSION_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SESS_NETWORK_BL" MODIFY ("SERIAL#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SESS_NETWORK_BL" MODIFY ("CHANNEL_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SESS_NETWORK_BL" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SESS_NETWORK_BL" ADD CONSTRAINT "WRH$_SESS_NETWORK_BL_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "CON_DBID", "SESSION_ID", "SERIAL#", "CHANNEL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
