--------------------------------------------------------
--  DDL for Table WRH$_SHARED_SERVER_SUMMARY
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_SHARED_SERVER_SUMMARY" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"NUM_SAMPLES" NUMBER, 
	"SAMPLE_TIME" NUMBER, 
	"SAMPLED_TOTAL_CONN" NUMBER, 
	"SAMPLED_ACTIVE_CONN" NUMBER, 
	"SAMPLED_TOTAL_SRV" NUMBER, 
	"SAMPLED_ACTIVE_SRV" NUMBER, 
	"SAMPLED_TOTAL_DISP" NUMBER, 
	"SAMPLED_ACTIVE_DISP" NUMBER, 
	"SRV_BUSY" NUMBER, 
	"SRV_IDLE" NUMBER, 
	"SRV_IN_NET" NUMBER, 
	"SRV_OUT_NET" NUMBER, 
	"SRV_MESSAGES" NUMBER, 
	"SRV_BYTES" NUMBER, 
	"CQ_WAIT" NUMBER, 
	"CQ_TOTALQ" NUMBER, 
	"DQ_TOTALQ" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_SHARED_SERVER_SUMMARY" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_SHARED_SERVER_SUMMARY" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_SHARED_SERVER_SUMMARY" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_SHARED_SERVER_SUMMARY" TO "SYSUMF_ROLE";
