--------------------------------------------------------
--  DDL for Table WRH$_TABLESPACE_STAT
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_TABLESPACE_STAT" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"TS#" NUMBER, 
	"TSNAME" VARCHAR2(30 BYTE), 
	"CONTENTS" VARCHAR2(9 BYTE), 
	"STATUS" VARCHAR2(9 BYTE), 
	"SEGMENT_SPACE_MANAGEMENT" VARCHAR2(6 BYTE), 
	"EXTENT_MANAGEMENT" VARCHAR2(10 BYTE), 
	"IS_BACKUP" VARCHAR2(5 BYTE), 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARTITION BY RANGE ("DBID","SNAP_ID") 
 (PARTITION "WRH$_TABLESPACE_STAT_692950692_0"  VALUES LESS THAN (692950692, MAXVALUE) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRH$_TABLESPACE_MXDB_MXSN"  VALUES LESS THAN (MAXVALUE, MAXVALUE) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" )  ENABLE ROW MOVEMENT ;
  GRANT DELETE ON "SYS"."WRH$_TABLESPACE_STAT" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_TABLESPACE_STAT" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_TABLESPACE_STAT" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_TABLESPACE_STAT" TO "SYSUMF_ROLE";
