--------------------------------------------------------
--  Constraints for Table WRH$_INSTANCE_RECOVERY
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_INSTANCE_RECOVERY" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_INSTANCE_RECOVERY" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_INSTANCE_RECOVERY" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_INSTANCE_RECOVERY" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_INSTANCE_RECOVERY" ADD CONSTRAINT "WRH$_INSTANCE_RECOVERY_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
