--------------------------------------------------------
--  Constraints for Table WRH$_PGASTAT
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_PGASTAT" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_PGASTAT" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_PGASTAT" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_PGASTAT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_PGASTAT" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_PGASTAT" ADD CONSTRAINT "WRH$_PGASTAT_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "NAME", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
