--------------------------------------------------------
--  Constraints for Table WRH$_COMP_IOSTAT
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_COMP_IOSTAT" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_COMP_IOSTAT" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_COMP_IOSTAT" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_COMP_IOSTAT" MODIFY ("COMPONENT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_COMP_IOSTAT" MODIFY ("FILE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_COMP_IOSTAT" MODIFY ("IO_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_COMP_IOSTAT" MODIFY ("OPERATION" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_COMP_IOSTAT" MODIFY ("BYTES" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_COMP_IOSTAT" MODIFY ("IO_COUNT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_COMP_IOSTAT" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_COMP_IOSTAT" ADD CONSTRAINT "WRH$_COMP_IOSTAT_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "COMPONENT", "FILE_TYPE", "IO_TYPE", "OPERATION", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
