--------------------------------------------------------
--  DDL for Table WRH$_DYN_REMASTER_STATS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_DYN_REMASTER_STATS" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"REMASTER_OPS" NUMBER, 
	"REMASTER_TIME" NUMBER, 
	"REMASTERED_OBJECTS" NUMBER, 
	"QUIESCE_TIME" NUMBER, 
	"FREEZE_TIME" NUMBER, 
	"CLEANUP_TIME" NUMBER, 
	"REPLAY_TIME" NUMBER, 
	"FIXWRITE_TIME" NUMBER, 
	"SYNC_TIME" NUMBER, 
	"RESOURCES_CLEANED" NUMBER, 
	"REPLAYED_LOCKS_SENT" NUMBER, 
	"REPLAYED_LOCKS_RECEIVED" NUMBER, 
	"CURRENT_OBJECTS" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"REMASTER_TYPE" VARCHAR2(11 BYTE) DEFAULT 'AFFINITY', 
	"PER_PDB" NUMBER DEFAULT null, 
	"PERSISTENT_OBJECTS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_DYN_REMASTER_STATS" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_DYN_REMASTER_STATS" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_DYN_REMASTER_STATS" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_DYN_REMASTER_STATS" TO "SYSUMF_ROLE";
