--------------------------------------------------------
--  DDL for Table WRH$_ASM_DISKGROUP_STAT
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_ASM_DISKGROUP_STAT" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"CON_DBID" NUMBER, 
	"GROUP_NUMBER" NUMBER, 
	"TOTAL_MB" NUMBER, 
	"FREE_MB" NUMBER, 
	"NUM_DISK" NUMBER, 
	"PER_PDB" NUMBER DEFAULT null, 
	"NUM_FAILGROUP" NUMBER, 
	"STATE" VARCHAR2(32 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_ASM_DISKGROUP_STAT" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_ASM_DISKGROUP_STAT" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_ASM_DISKGROUP_STAT" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_ASM_DISKGROUP_STAT" TO "SYSUMF_ROLE";
