--------------------------------------------------------
--  DDL for Table WRH$_SEG_STAT
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_SEG_STAT" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"TS#" NUMBER, 
	"OBJ#" NUMBER, 
	"DATAOBJ#" NUMBER, 
	"LOGICAL_READS_TOTAL" NUMBER, 
	"LOGICAL_READS_DELTA" NUMBER, 
	"BUFFER_BUSY_WAITS_TOTAL" NUMBER, 
	"BUFFER_BUSY_WAITS_DELTA" NUMBER, 
	"DB_BLOCK_CHANGES_TOTAL" NUMBER, 
	"DB_BLOCK_CHANGES_DELTA" NUMBER, 
	"PHYSICAL_READS_TOTAL" NUMBER, 
	"PHYSICAL_READS_DELTA" NUMBER, 
	"PHYSICAL_WRITES_TOTAL" NUMBER, 
	"PHYSICAL_WRITES_DELTA" NUMBER, 
	"PHYSICAL_READS_DIRECT_TOTAL" NUMBER, 
	"PHYSICAL_READS_DIRECT_DELTA" NUMBER, 
	"PHYSICAL_WRITES_DIRECT_TOTAL" NUMBER, 
	"PHYSICAL_WRITES_DIRECT_DELTA" NUMBER, 
	"ITL_WAITS_TOTAL" NUMBER, 
	"ITL_WAITS_DELTA" NUMBER, 
	"ROW_LOCK_WAITS_TOTAL" NUMBER, 
	"ROW_LOCK_WAITS_DELTA" NUMBER, 
	"GC_BUFFER_BUSY_TOTAL" NUMBER, 
	"GC_BUFFER_BUSY_DELTA" NUMBER, 
	"GC_CR_BLOCKS_RECEIVED_TOTAL" NUMBER, 
	"GC_CR_BLOCKS_RECEIVED_DELTA" NUMBER, 
	"GC_CU_BLOCKS_RECEIVED_TOTAL" NUMBER, 
	"GC_CU_BLOCKS_RECEIVED_DELTA" NUMBER, 
	"SPACE_USED_TOTAL" NUMBER, 
	"SPACE_USED_DELTA" NUMBER, 
	"SPACE_ALLOCATED_TOTAL" NUMBER, 
	"SPACE_ALLOCATED_DELTA" NUMBER, 
	"TABLE_SCANS_TOTAL" NUMBER, 
	"TABLE_SCANS_DELTA" NUMBER, 
	"CHAIN_ROW_EXCESS_TOTAL" NUMBER, 
	"CHAIN_ROW_EXCESS_DELTA" NUMBER, 
	"PHYSICAL_READ_REQUESTS_TOTAL" NUMBER, 
	"PHYSICAL_READ_REQUESTS_DELTA" NUMBER, 
	"PHYSICAL_WRITE_REQUESTS_TOTAL" NUMBER, 
	"PHYSICAL_WRITE_REQUESTS_DELTA" NUMBER, 
	"OPTIMIZED_PHYSICAL_READS_TOTAL" NUMBER, 
	"OPTIMIZED_PHYSICAL_READS_DELTA" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null, 
	"GC_REMOTE_GRANTS_TOTAL" NUMBER, 
	"GC_REMOTE_GRANTS_DELTA" NUMBER, 
	"IM_SCANS_TOTAL" NUMBER DEFAULT 0, 
	"IM_SCANS_DELTA" NUMBER DEFAULT 0, 
	"POPULATE_CUS_TOTAL" NUMBER DEFAULT 0, 
	"POPULATE_CUS_DELTA" NUMBER DEFAULT 0, 
	"REPOPULATE_CUS_TOTAL" NUMBER DEFAULT 0, 
	"REPOPULATE_CUS_DELTA" NUMBER DEFAULT 0, 
	"IM_DB_BLOCK_CHANGES_TOTAL" NUMBER DEFAULT 0, 
	"IM_DB_BLOCK_CHANGES_DELTA" NUMBER DEFAULT 0, 
	"IM_MEMBYTES" NUMBER DEFAULT 0
   ) PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARTITION BY RANGE ("DBID","SNAP_ID") 
 (PARTITION "WRH$_SEG_STAT_692950692_0"  VALUES LESS THAN (692950692, MAXVALUE) 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRH$_SEG_STAT_MXDB_MXSN"  VALUES LESS THAN (MAXVALUE, MAXVALUE) 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" )  ENABLE ROW MOVEMENT ;
  GRANT DELETE ON "SYS"."WRH$_SEG_STAT" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_SEG_STAT" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_SEG_STAT" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_SEG_STAT" TO "SYSUMF_ROLE";
