--------------------------------------------------------
--  DDL for Table WRH$_CELL_IOREASON
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_CELL_IOREASON" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"CELL_HASH" NUMBER, 
	"INCARNATION_NUM" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"REASON_ID" NUMBER, 
	"REQUESTS" NUMBER, 
	"BYTES" NUMBER, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARTITION BY RANGE ("DBID","SNAP_ID") 
 (PARTITION "WRH$_CELL_IOREASON_692950692_0"  VALUES LESS THAN (692950692, MAXVALUE) 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRH$_CELL_IOREASON_MXDB_MXSN"  VALUES LESS THAN (MAXVALUE, MAXVALUE) 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" )  ENABLE ROW MOVEMENT ;
  GRANT DELETE ON "SYS"."WRH$_CELL_IOREASON" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_CELL_IOREASON" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_CELL_IOREASON" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_CELL_IOREASON" TO "SYSUMF_ROLE";
