--------------------------------------------------------
--  DDL for Table WRH$_WAITCLASSMETRIC_HISTORY
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_WAITCLASSMETRIC_HISTORY" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"WAIT_CLASS_ID" NUMBER, 
	"BEGIN_TIME" DATE, 
	"END_TIME" DATE, 
	"INTSIZE" NUMBER, 
	"GROUP_ID" NUMBER, 
	"AVERAGE_WAITER_COUNT" NUMBER, 
	"DBTIME_IN_WAIT" NUMBER, 
	"TIME_WAITED" NUMBER, 
	"WAIT_COUNT" NUMBER, 
	"TIME_WAITED_FG" NUMBER, 
	"WAIT_COUNT_FG" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_WAITCLASSMETRIC_HISTORY" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_WAITCLASSMETRIC_HISTORY" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_WAITCLASSMETRIC_HISTORY" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_WAITCLASSMETRIC_HISTORY" TO "SYSUMF_ROLE";
