--------------------------------------------------------
--  DDL for Table WRH$_RESOURCE_LIMIT
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_RESOURCE_LIMIT" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"RESOURCE_NAME" VARCHAR2(30 BYTE), 
	"CURRENT_UTILIZATION" NUMBER, 
	"MAX_UTILIZATION" NUMBER, 
	"INITIAL_ALLOCATION" VARCHAR2(10 BYTE), 
	"LIMIT_VALUE" VARCHAR2(10 BYTE), 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_RESOURCE_LIMIT" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_RESOURCE_LIMIT" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_RESOURCE_LIMIT" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_RESOURCE_LIMIT" TO "SYSUMF_ROLE";
