--------------------------------------------------------
--  DDL for Table WRH$_PGA_TARGET_ADVICE
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_PGA_TARGET_ADVICE" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"PGA_TARGET_FOR_ESTIMATE" NUMBER, 
	"PGA_TARGET_FACTOR" NUMBER, 
	"ADVICE_STATUS" VARCHAR2(3 BYTE), 
	"BYTES_PROCESSED" NUMBER, 
	"ESTD_EXTRA_BYTES_RW" NUMBER, 
	"ESTD_PGA_CACHE_HIT_PERCENTAGE" NUMBER, 
	"ESTD_OVERALLOC_COUNT" NUMBER, 
	"ESTD_TIME" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_PGA_TARGET_ADVICE" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_PGA_TARGET_ADVICE" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_PGA_TARGET_ADVICE" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_PGA_TARGET_ADVICE" TO "SYSUMF_ROLE";
