--------------------------------------------------------
--  Constraints for Table WRH$_CON_SYSMETRIC_HISTORY_BL
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_CON_SYSMETRIC_HISTORY_BL" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CON_SYSMETRIC_HISTORY_BL" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CON_SYSMETRIC_HISTORY_BL" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CON_SYSMETRIC_HISTORY_BL" MODIFY ("BEGIN_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CON_SYSMETRIC_HISTORY_BL" MODIFY ("END_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CON_SYSMETRIC_HISTORY_BL" MODIFY ("INTSIZE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CON_SYSMETRIC_HISTORY_BL" MODIFY ("GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CON_SYSMETRIC_HISTORY_BL" MODIFY ("METRIC_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CON_SYSMETRIC_HISTORY_BL" MODIFY ("VALUE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CON_SYSMETRIC_HISTORY_BL" MODIFY ("CON_DBID" NOT NULL ENABLE);
