--------------------------------------------------------
--  DDL for Table WRH$_SQLTEXT
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_SQLTEXT" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"SQL_ID" VARCHAR2(13 BYTE), 
	"SQL_TEXT" CLOB, 
	"COMMAND_TYPE" NUMBER, 
	"REF_COUNT" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" 
 LOB ("SQL_TEXT") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
  GRANT DELETE ON "SYS"."WRH$_SQLTEXT" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_SQLTEXT" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_SQLTEXT" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_SQLTEXT" TO "SYSUMF_ROLE";
