--------------------------------------------------------
--  Constraints for Table WRH$_SERVICE_WAIT_CLASS_BL
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_SERVICE_WAIT_CLASS_BL" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SERVICE_WAIT_CLASS_BL" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SERVICE_WAIT_CLASS_BL" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SERVICE_WAIT_CLASS_BL" MODIFY ("SERVICE_NAME_HASH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SERVICE_WAIT_CLASS_BL" MODIFY ("WAIT_CLASS_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SERVICE_WAIT_CLASS_BL" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SERVICE_WAIT_CLASS_BL" ADD CONSTRAINT "WRH$_SERVICE_WAIT_CLASS_BL_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "SERVICE_NAME_HASH", "WAIT_CLASS_ID", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
