--------------------------------------------------------
--  Constraints for Table WRH$_PGA_TARGET_ADVICE
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_PGA_TARGET_ADVICE" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_PGA_TARGET_ADVICE" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_PGA_TARGET_ADVICE" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_PGA_TARGET_ADVICE" MODIFY ("PGA_TARGET_FOR_ESTIMATE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_PGA_TARGET_ADVICE" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_PGA_TARGET_ADVICE" ADD CONSTRAINT "WRH$_PGA_TARGET_ADVICE_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "PGA_TARGET_FOR_ESTIMATE", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
