--------------------------------------------------------
--  Constraints for Table WRH$_CELL_DISK_SUMMARY
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_CELL_DISK_SUMMARY" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CELL_DISK_SUMMARY" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CELL_DISK_SUMMARY" MODIFY ("CELL_HASH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CELL_DISK_SUMMARY" MODIFY ("INCARNATION_NUM" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CELL_DISK_SUMMARY" MODIFY ("DISK_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CELL_DISK_SUMMARY" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CELL_DISK_SUMMARY" ADD CONSTRAINT "WRH$_CELL_DISK_SUMM_PK" PRIMARY KEY ("DBID", "SNAP_ID", "CELL_HASH", "INCARNATION_NUM", "DISK_ID", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  LOCAL
 (PARTITION "WRH$_CELL_DISK_SUMMARY_692950692_0" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRH$_CELL_DISK_SUMM_MXDB_MXSN" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" )  ENABLE;
