--------------------------------------------------------
--  DDL for Table WRH$_MEM_DYNAMIC_COMP
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_MEM_DYNAMIC_COMP" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"COMPONENT" VARCHAR2(64 BYTE), 
	"CURRENT_SIZE" NUMBER, 
	"MIN_SIZE" NUMBER, 
	"MAX_SIZE" NUMBER, 
	"USER_SPECIFIED_SIZE" NUMBER, 
	"OPER_COUNT" NUMBER, 
	"LAST_OPER_TYPE" VARCHAR2(13 BYTE), 
	"LAST_OPER_MODE" VARCHAR2(9 BYTE), 
	"LAST_OPER_TIME" DATE, 
	"GRANULE_SIZE" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_MEM_DYNAMIC_COMP" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_MEM_DYNAMIC_COMP" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_MEM_DYNAMIC_COMP" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_MEM_DYNAMIC_COMP" TO "SYSUMF_ROLE";
