--------------------------------------------------------
--  DDL for Table WRH$_SQL_BIND_METADATA
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_SQL_BIND_METADATA" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"SQL_ID" VARCHAR2(13 BYTE), 
	"NAME" VARCHAR2(128 BYTE), 
	"POSITION" NUMBER, 
	"DUP_POSITION" NUMBER, 
	"DATATYPE" NUMBER, 
	"DATATYPE_STRING" VARCHAR2(15 BYTE), 
	"CHARACTER_SID" NUMBER, 
	"PRECISION" NUMBER, 
	"SCALE" NUMBER, 
	"MAX_LENGTH" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_SQL_BIND_METADATA" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_SQL_BIND_METADATA" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_SQL_BIND_METADATA" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_SQL_BIND_METADATA" TO "SYSUMF_ROLE";
