--------------------------------------------------------
--  Constraints for Table WRH$_DYN_REMASTER_STATS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_DYN_REMASTER_STATS" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_DYN_REMASTER_STATS" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_DYN_REMASTER_STATS" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_DYN_REMASTER_STATS" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_DYN_REMASTER_STATS" MODIFY ("REMASTER_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_DYN_REMASTER_STATS" ADD CONSTRAINT "WRH$_DYN_REMASTER_STATS_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "CON_DBID", "REMASTER_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
