--------------------------------------------------------
--  Constraints for Table WRH$_DATAFILE
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_DATAFILE" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_DATAFILE" MODIFY ("FILE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_DATAFILE" MODIFY ("CREATION_CHANGE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_DATAFILE" MODIFY ("FILENAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_DATAFILE" MODIFY ("TS#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_DATAFILE" MODIFY ("TSNAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_DATAFILE" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_DATAFILE" ADD CONSTRAINT "WRH$_DATAFILE_PK" PRIMARY KEY ("DBID", "FILE#", "CREATION_CHANGE#", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
