--------------------------------------------------------
--  Constraints for Table WRH$_REPLICATION_TBL_STATS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_REPLICATION_TBL_STATS" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_REPLICATION_TBL_STATS" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_REPLICATION_TBL_STATS" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_REPLICATION_TBL_STATS" MODIFY ("APPLY_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_REPLICATION_TBL_STATS" MODIFY ("TABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_REPLICATION_TBL_STATS" MODIFY ("TABLE_OWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_REPLICATION_TBL_STATS" MODIFY ("SESSION_MODULE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_REPLICATION_TBL_STATS" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_REPLICATION_TBL_STATS" ADD CONSTRAINT "WRH$_REPLICATION_TBL_STATS_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "APPLY_NAME", "TABLE_NAME", "TABLE_OWNER", "SESSION_MODULE", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
