--------------------------------------------------------
--  Constraints for Table WRH$_BG_EVENT_SUMMARY
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_BG_EVENT_SUMMARY" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_BG_EVENT_SUMMARY" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_BG_EVENT_SUMMARY" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_BG_EVENT_SUMMARY" MODIFY ("EVENT_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_BG_EVENT_SUMMARY" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_BG_EVENT_SUMMARY" ADD CONSTRAINT "WRH$_BG_EVENT_SUMMARY_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "EVENT_ID", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
