--------------------------------------------------------
--  Constraints for Table WRH$_SESS_SGA_STATS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_SESS_SGA_STATS" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SESS_SGA_STATS" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SESS_SGA_STATS" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SESS_SGA_STATS" MODIFY ("OBJECT_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SESS_SGA_STATS" MODIFY ("SESSION_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SESS_SGA_STATS" MODIFY ("SESSION_MODULE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SESS_SGA_STATS" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SESS_SGA_STATS" ADD CONSTRAINT "WRH$_SESS_SGA_STATS_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "OBJECT_NAME", "SESSION_TYPE", "SESSION_MODULE", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
