--------------------------------------------------------
--  DDL for Table WRH$_RECOVERY_PROGRESS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_RECOVERY_PROGRESS" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"START_TIME" DATE, 
	"TYPE" VARCHAR2(64 BYTE), 
	"ITEM" VARCHAR2(32 BYTE), 
	"UNITS" VARCHAR2(32 BYTE), 
	"SOFAR" NUMBER, 
	"TOTAL" NUMBER, 
	"TIMESTAMP" DATE, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_RECOVERY_PROGRESS" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_RECOVERY_PROGRESS" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_RECOVERY_PROGRESS" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_RECOVERY_PROGRESS" TO "SYSUMF_ROLE";
