--------------------------------------------------------
--  DDL for Table WRH$_CELL_METRIC_DESC
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_CELL_METRIC_DESC" SHARING=METADATA 
   (	"DBID" NUMBER, 
	"METRIC_ID" NUMBER, 
	"METRIC_NAME" VARCHAR2(257 BYTE), 
	"METRIC_TYPE" VARCHAR2(17 BYTE), 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_CELL_METRIC_DESC" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_CELL_METRIC_DESC" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_CELL_METRIC_DESC" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_CELL_METRIC_DESC" TO "SYSUMF_ROLE";
