--------------------------------------------------------
--  Constraints for Table WRH$_CON_SYSMETRIC_SUMMARY
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_CON_SYSMETRIC_SUMMARY" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CON_SYSMETRIC_SUMMARY" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CON_SYSMETRIC_SUMMARY" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CON_SYSMETRIC_SUMMARY" MODIFY ("BEGIN_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CON_SYSMETRIC_SUMMARY" MODIFY ("END_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CON_SYSMETRIC_SUMMARY" MODIFY ("INTSIZE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CON_SYSMETRIC_SUMMARY" MODIFY ("GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CON_SYSMETRIC_SUMMARY" MODIFY ("METRIC_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CON_SYSMETRIC_SUMMARY" MODIFY ("NUM_INTERVAL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CON_SYSMETRIC_SUMMARY" MODIFY ("MAXVAL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CON_SYSMETRIC_SUMMARY" MODIFY ("MINVAL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CON_SYSMETRIC_SUMMARY" MODIFY ("AVERAGE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CON_SYSMETRIC_SUMMARY" MODIFY ("STANDARD_DEVIATION" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CON_SYSMETRIC_SUMMARY" MODIFY ("CON_DBID" NOT NULL ENABLE);
