--------------------------------------------------------
--  Constraints for Table WRH$_LMS_STATS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_LMS_STATS" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LMS_STATS" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LMS_STATS" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LMS_STATS" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LMS_STATS" ADD CONSTRAINT "WRH$_LMS_STATS_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "PID", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
