--------------------------------------------------------
--  Constraints for Table WRH$_CHANNEL_WAITS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_CHANNEL_WAITS" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CHANNEL_WAITS" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CHANNEL_WAITS" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CHANNEL_WAITS" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CHANNEL_WAITS" ADD CONSTRAINT "WRH$_CHANNEL_WAITS" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "CHANNEL", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
