--------------------------------------------------------
--  Constraints for Table WRH$_AWR_TEST_1_BL
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_AWR_TEST_1_BL" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_AWR_TEST_1_BL" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_AWR_TEST_1_BL" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_AWR_TEST_1_BL" MODIFY ("STEP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_AWR_TEST_1_BL" ADD CONSTRAINT "WRH$_AWR_TEST_1_BL_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "STEP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
