--------------------------------------------------------
--  DDL for Table WRH$_IOSTAT_FILETYPE
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_IOSTAT_FILETYPE" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"FILETYPE_ID" NUMBER, 
	"SMALL_READ_MEGABYTES" NUMBER, 
	"SMALL_WRITE_MEGABYTES" NUMBER, 
	"LARGE_READ_MEGABYTES" NUMBER, 
	"LARGE_WRITE_MEGABYTES" NUMBER, 
	"SMALL_READ_REQS" NUMBER, 
	"SMALL_WRITE_REQS" NUMBER, 
	"SMALL_SYNC_READ_REQS" NUMBER, 
	"LARGE_READ_REQS" NUMBER, 
	"LARGE_WRITE_REQS" NUMBER, 
	"SMALL_READ_SERVICETIME" NUMBER, 
	"SMALL_WRITE_SERVICETIME" NUMBER, 
	"SMALL_SYNC_READ_LATENCY" NUMBER, 
	"LARGE_READ_SERVICETIME" NUMBER, 
	"LARGE_WRITE_SERVICETIME" NUMBER, 
	"RETRIES_ON_ERROR" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_IOSTAT_FILETYPE" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_IOSTAT_FILETYPE" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_IOSTAT_FILETYPE" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_IOSTAT_FILETYPE" TO "SYSUMF_ROLE";
