--------------------------------------------------------
--  DDL for Table WRH$_LMS_STATS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_LMS_STATS" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"PID" NUMBER, 
	"PRIORITY" NUMBER, 
	"PRIORITY_CHANGES" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_LMS_STATS" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_LMS_STATS" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_LMS_STATS" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_LMS_STATS" TO "SYSUMF_ROLE";
