--------------------------------------------------------
--  Constraints for Table WRH$_STAT_NAME
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_STAT_NAME" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_STAT_NAME" MODIFY ("STAT_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_STAT_NAME" MODIFY ("STAT_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_STAT_NAME" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_STAT_NAME" ADD CONSTRAINT "WRH$_STAT_NAME_PK" PRIMARY KEY ("DBID", "STAT_ID", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
