--------------------------------------------------------
--  DDL for Table WRH$_MEMORY_TARGET_ADVICE
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_MEMORY_TARGET_ADVICE" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"MEMORY_SIZE" NUMBER, 
	"MEMORY_SIZE_FACTOR" NUMBER, 
	"ESTD_DB_TIME" NUMBER, 
	"ESTD_DB_TIME_FACTOR" NUMBER, 
	"VERSION" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_MEMORY_TARGET_ADVICE" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_MEMORY_TARGET_ADVICE" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_MEMORY_TARGET_ADVICE" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_MEMORY_TARGET_ADVICE" TO "SYSUMF_ROLE";
