--------------------------------------------------------
--  DDL for Table WRH$_ROWCACHE_SUMMARY_BL
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_ROWCACHE_SUMMARY_BL" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"PARAMETER" VARCHAR2(32 BYTE), 
	"TOTAL_USAGE" NUMBER, 
	"USAGE" NUMBER, 
	"GETS" NUMBER, 
	"GETMISSES" NUMBER, 
	"SCANS" NUMBER, 
	"SCANMISSES" NUMBER, 
	"SCANCOMPLETES" NUMBER, 
	"MODIFICATIONS" NUMBER, 
	"FLUSHES" NUMBER, 
	"DLM_REQUESTS" NUMBER, 
	"DLM_CONFLICTS" NUMBER, 
	"DLM_RELEASES" NUMBER, 
	"CON_DBID" NUMBER, 
	"PER_PDB" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
