--------------------------------------------------------
--  Constraints for Table WRH$_CELL_METRIC_DESC
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_CELL_METRIC_DESC" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CELL_METRIC_DESC" MODIFY ("METRIC_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CELL_METRIC_DESC" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CELL_METRIC_DESC" ADD CONSTRAINT "WRH$_CELL_METRIC_DESC_PK" PRIMARY KEY ("DBID", "METRIC_ID", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
