--------------------------------------------------------
--  Constraints for Table WRH$_CELL_IOREASON_NAME
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_CELL_IOREASON_NAME" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CELL_IOREASON_NAME" MODIFY ("REASON_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CELL_IOREASON_NAME" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CELL_IOREASON_NAME" ADD CONSTRAINT "WRH$_CELL_IOREASON_NAME_PK" PRIMARY KEY ("DBID", "REASON_ID", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
