--------------------------------------------------------
--  Constraints for Table WRH$_CON_SYS_TIME_MODEL
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_CON_SYS_TIME_MODEL" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CON_SYS_TIME_MODEL" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CON_SYS_TIME_MODEL" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CON_SYS_TIME_MODEL" MODIFY ("STAT_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CON_SYS_TIME_MODEL" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CON_SYS_TIME_MODEL" ADD CONSTRAINT "WRH$_CON_SYS_TIME_MODEL_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "STAT_ID", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  LOCAL
 (PARTITION "WRH$_CON_SYS_TIME_MODEL_692950692_0" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRH$_CON_SYS_TIME_MO_MXDB_MXSN" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" )  ENABLE;
