--------------------------------------------------------
--  Constraints for Table WRH$_IC_DEVICE_STATS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_IC_DEVICE_STATS" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IC_DEVICE_STATS" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IC_DEVICE_STATS" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IC_DEVICE_STATS" MODIFY ("IF_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IC_DEVICE_STATS" MODIFY ("IP_ADDR" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IC_DEVICE_STATS" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_IC_DEVICE_STATS" ADD CONSTRAINT "WRH$_IC_DEVICE_STATS_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "IF_NAME", "IP_ADDR", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
