--------------------------------------------------------
--  Constraints for Table WRH$_SQLCOMMAND_NAME
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_SQLCOMMAND_NAME" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SQLCOMMAND_NAME" MODIFY ("COMMAND_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SQLCOMMAND_NAME" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SQLCOMMAND_NAME" ADD CONSTRAINT "WRH$_SQLCOMMAND_NAME_PK" PRIMARY KEY ("DBID", "COMMAND_TYPE", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
