--------------------------------------------------------
--  Constraints for Table WRH$_BUFFERED_QUEUES
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_BUFFERED_QUEUES" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_BUFFERED_QUEUES" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_BUFFERED_QUEUES" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_BUFFERED_QUEUES" MODIFY ("QUEUE_SCHEMA" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_BUFFERED_QUEUES" MODIFY ("QUEUE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_BUFFERED_QUEUES" MODIFY ("STARTUP_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_BUFFERED_QUEUES" MODIFY ("QUEUE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_BUFFERED_QUEUES" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_BUFFERED_QUEUES" ADD CONSTRAINT "WRH$_BUFFERED_QUEUES_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "QUEUE_SCHEMA", "QUEUE_NAME", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
