--------------------------------------------------------
--  DDL for Table WRH$_SQL_PLAN
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_SQL_PLAN" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"SQL_ID" VARCHAR2(13 BYTE), 
	"PLAN_HASH_VALUE" NUMBER, 
	"ID" NUMBER, 
	"OPERATION" VARCHAR2(30 BYTE), 
	"OPTIONS" VARCHAR2(30 BYTE), 
	"OBJECT_NODE" VARCHAR2(128 BYTE), 
	"OBJECT#" NUMBER, 
	"OBJECT_OWNER" VARCHAR2(128 BYTE), 
	"OBJECT_NAME" VARCHAR2(128 BYTE), 
	"OBJECT_ALIAS" VARCHAR2(261 BYTE), 
	"OBJECT_TYPE" VARCHAR2(20 BYTE), 
	"OPTIMIZER" VARCHAR2(20 BYTE), 
	"PARENT_ID" NUMBER, 
	"DEPTH" NUMBER, 
	"POSITION" NUMBER, 
	"SEARCH_COLUMNS" NUMBER, 
	"COST" NUMBER, 
	"CARDINALITY" NUMBER, 
	"BYTES" NUMBER, 
	"OTHER_TAG" VARCHAR2(35 BYTE), 
	"PARTITION_START" VARCHAR2(64 BYTE), 
	"PARTITION_STOP" VARCHAR2(64 BYTE), 
	"PARTITION_ID" NUMBER, 
	"OTHER" VARCHAR2(4000 BYTE), 
	"DISTRIBUTION" VARCHAR2(20 BYTE), 
	"CPU_COST" NUMBER, 
	"IO_COST" NUMBER, 
	"TEMP_SPACE" NUMBER, 
	"ACCESS_PREDICATES" VARCHAR2(4000 BYTE), 
	"FILTER_PREDICATES" VARCHAR2(4000 BYTE), 
	"PROJECTION" VARCHAR2(4000 BYTE), 
	"TIME" NUMBER, 
	"QBLOCK_NAME" VARCHAR2(128 BYTE), 
	"REMARKS" VARCHAR2(4000 BYTE), 
	"TIMESTAMP" DATE, 
	"OTHER_XML" CLOB, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" 
 LOB ("OTHER_XML") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
  GRANT DELETE ON "SYS"."WRH$_SQL_PLAN" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_SQL_PLAN" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_SQL_PLAN" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_SQL_PLAN" TO "SYSUMF_ROLE";
