--------------------------------------------------------
--  Constraints for Table WRH$_ASM_DISKGROUP
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_ASM_DISKGROUP" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_ASM_DISKGROUP" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_ASM_DISKGROUP" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_ASM_DISKGROUP" MODIFY ("CURRENT_SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_ASM_DISKGROUP" MODIFY ("GROUP_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_ASM_DISKGROUP" ADD CONSTRAINT "WRH$_ASM_DISKGROUP_PK" PRIMARY KEY ("DBID", "GROUP_NUMBER", "NAME", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
