--------------------------------------------------------
--  Constraints for Table WRH$_MEMORY_TARGET_ADVICE
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_MEMORY_TARGET_ADVICE" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_MEMORY_TARGET_ADVICE" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_MEMORY_TARGET_ADVICE" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_MEMORY_TARGET_ADVICE" MODIFY ("MEMORY_SIZE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_MEMORY_TARGET_ADVICE" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_MEMORY_TARGET_ADVICE" ADD CONSTRAINT "WRH$_MEMORY_TARGET_ADVICE_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "MEMORY_SIZE", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
