--------------------------------------------------------
--  Constraints for Table WRH$_DB_CACHE_ADVICE_BL
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_DB_CACHE_ADVICE_BL" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_DB_CACHE_ADVICE_BL" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_DB_CACHE_ADVICE_BL" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_DB_CACHE_ADVICE_BL" MODIFY ("BPID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_DB_CACHE_ADVICE_BL" MODIFY ("BUFFERS_FOR_ESTIMATE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_DB_CACHE_ADVICE_BL" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_DB_CACHE_ADVICE_BL" ADD CONSTRAINT "WRH$_DB_CACHE_ADVICE_BL_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "BPID", "BUFFERS_FOR_ESTIMATE", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
