--------------------------------------------------------
--  Constraints for Table WRH$_INST_CACHE_TRANSFER_BL
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_INST_CACHE_TRANSFER_BL" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_INST_CACHE_TRANSFER_BL" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_INST_CACHE_TRANSFER_BL" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_INST_CACHE_TRANSFER_BL" MODIFY ("INSTANCE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_INST_CACHE_TRANSFER_BL" MODIFY ("CLASS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_INST_CACHE_TRANSFER_BL" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_INST_CACHE_TRANSFER_BL" ADD CONSTRAINT "WRH$_INST_CACHE_TRANSFER_BL_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "INSTANCE", "CLASS", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
