--------------------------------------------------------
--  DDL for Table WRH$_MEMORY_RESIZE_OPS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_MEMORY_RESIZE_OPS" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"COMPONENT" VARCHAR2(64 BYTE), 
	"OPER_TYPE" VARCHAR2(13 BYTE), 
	"START_TIME" DATE, 
	"END_TIME" DATE, 
	"TARGET_SIZE" NUMBER, 
	"OPER_MODE" VARCHAR2(9 BYTE), 
	"PARAMETER" VARCHAR2(80 BYTE), 
	"INITIAL_SIZE" NUMBER, 
	"FINAL_SIZE" NUMBER, 
	"STATUS" VARCHAR2(9 BYTE), 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_MEMORY_RESIZE_OPS" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_MEMORY_RESIZE_OPS" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_MEMORY_RESIZE_OPS" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_MEMORY_RESIZE_OPS" TO "SYSUMF_ROLE";
