--------------------------------------------------------
--  DDL for Table WRH$_TABLESPACE_SPACE_USAGE
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_TABLESPACE_SPACE_USAGE" SHARING=METADATA 
   (	"DBID" NUMBER, 
	"SNAP_ID" NUMBER, 
	"TABLESPACE_ID" NUMBER, 
	"TABLESPACE_SIZE" NUMBER, 
	"TABLESPACE_MAXSIZE" NUMBER, 
	"TABLESPACE_USEDSIZE" NUMBER, 
	"RTIME" VARCHAR2(25 BYTE), 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_TABLESPACE_SPACE_USAGE" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_TABLESPACE_SPACE_USAGE" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_TABLESPACE_SPACE_USAGE" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_TABLESPACE_SPACE_USAGE" TO "SYSUMF_ROLE";
