--------------------------------------------------------
--  DDL for Table WRH$_INST_CACHE_TRANSFER_BL
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_INST_CACHE_TRANSFER_BL" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"INSTANCE" NUMBER, 
	"CLASS" VARCHAR2(18 BYTE), 
	"CR_BLOCK" NUMBER, 
	"CR_BUSY" NUMBER, 
	"CR_CONGESTED" NUMBER, 
	"CURRENT_BLOCK" NUMBER, 
	"CURRENT_BUSY" NUMBER, 
	"CURRENT_CONGESTED" NUMBER, 
	"LOST" NUMBER, 
	"CR_2HOP" NUMBER, 
	"CR_3HOP" NUMBER, 
	"CURRENT_2HOP" NUMBER, 
	"CURRENT_3HOP" NUMBER, 
	"CR_BLOCK_TIME" NUMBER, 
	"CR_BUSY_TIME" NUMBER, 
	"CR_CONGESTED_TIME" NUMBER, 
	"CURRENT_BLOCK_TIME" NUMBER, 
	"CURRENT_BUSY_TIME" NUMBER, 
	"CURRENT_CONGESTED_TIME" NUMBER, 
	"LOST_TIME" NUMBER, 
	"CR_2HOP_TIME" NUMBER, 
	"CR_3HOP_TIME" NUMBER, 
	"CURRENT_2HOP_TIME" NUMBER, 
	"CURRENT_3HOP_TIME" NUMBER, 
	"CON_DBID" NUMBER, 
	"PER_PDB" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
