--------------------------------------------------------
--  DDL for Table WRH$_CLUSTER_INTERCON
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_CLUSTER_INTERCON" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"NAME" VARCHAR2(256 BYTE), 
	"IP_ADDRESS" VARCHAR2(64 BYTE), 
	"IS_PUBLIC" VARCHAR2(3 BYTE), 
	"SOURCE" VARCHAR2(31 BYTE), 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_CLUSTER_INTERCON" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_CLUSTER_INTERCON" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_CLUSTER_INTERCON" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_CLUSTER_INTERCON" TO "SYSUMF_ROLE";
