--------------------------------------------------------
--  DDL for Table WRH$_SQLSTAT
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_SQLSTAT" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"SQL_ID" VARCHAR2(13 BYTE), 
	"PLAN_HASH_VALUE" NUMBER, 
	"OPTIMIZER_COST" NUMBER, 
	"OPTIMIZER_MODE" VARCHAR2(10 BYTE), 
	"OPTIMIZER_ENV_HASH_VALUE" NUMBER, 
	"SHARABLE_MEM" NUMBER, 
	"LOADED_VERSIONS" NUMBER, 
	"VERSION_COUNT" NUMBER, 
	"MODULE" VARCHAR2(64 BYTE), 
	"ACTION" VARCHAR2(64 BYTE), 
	"SQL_PROFILE" VARCHAR2(64 BYTE), 
	"FORCE_MATCHING_SIGNATURE" NUMBER, 
	"PARSING_SCHEMA_ID" NUMBER, 
	"PARSING_SCHEMA_NAME" VARCHAR2(128 BYTE), 
	"FETCHES_TOTAL" NUMBER, 
	"FETCHES_DELTA" NUMBER, 
	"END_OF_FETCH_COUNT_TOTAL" NUMBER, 
	"END_OF_FETCH_COUNT_DELTA" NUMBER, 
	"SORTS_TOTAL" NUMBER, 
	"SORTS_DELTA" NUMBER, 
	"EXECUTIONS_TOTAL" NUMBER, 
	"EXECUTIONS_DELTA" NUMBER, 
	"PX_SERVERS_EXECS_TOTAL" NUMBER, 
	"PX_SERVERS_EXECS_DELTA" NUMBER, 
	"LOADS_TOTAL" NUMBER, 
	"LOADS_DELTA" NUMBER, 
	"INVALIDATIONS_TOTAL" NUMBER, 
	"INVALIDATIONS_DELTA" NUMBER, 
	"PARSE_CALLS_TOTAL" NUMBER, 
	"PARSE_CALLS_DELTA" NUMBER, 
	"DISK_READS_TOTAL" NUMBER, 
	"DISK_READS_DELTA" NUMBER, 
	"BUFFER_GETS_TOTAL" NUMBER, 
	"BUFFER_GETS_DELTA" NUMBER, 
	"ROWS_PROCESSED_TOTAL" NUMBER, 
	"ROWS_PROCESSED_DELTA" NUMBER, 
	"CPU_TIME_TOTAL" NUMBER, 
	"CPU_TIME_DELTA" NUMBER, 
	"ELAPSED_TIME_TOTAL" NUMBER, 
	"ELAPSED_TIME_DELTA" NUMBER, 
	"IOWAIT_TOTAL" NUMBER, 
	"IOWAIT_DELTA" NUMBER, 
	"CLWAIT_TOTAL" NUMBER, 
	"CLWAIT_DELTA" NUMBER, 
	"APWAIT_TOTAL" NUMBER, 
	"APWAIT_DELTA" NUMBER, 
	"CCWAIT_TOTAL" NUMBER, 
	"CCWAIT_DELTA" NUMBER, 
	"DIRECT_WRITES_TOTAL" NUMBER, 
	"DIRECT_WRITES_DELTA" NUMBER, 
	"PLSEXEC_TIME_TOTAL" NUMBER, 
	"PLSEXEC_TIME_DELTA" NUMBER, 
	"JAVEXEC_TIME_TOTAL" NUMBER, 
	"JAVEXEC_TIME_DELTA" NUMBER, 
	"BIND_DATA" RAW(2000), 
	"FLAG" NUMBER, 
	"PARSING_USER_ID" NUMBER, 
	"IO_OFFLOAD_ELIG_BYTES_TOTAL" NUMBER, 
	"IO_OFFLOAD_ELIG_BYTES_DELTA" NUMBER, 
	"IO_INTERCONNECT_BYTES_TOTAL" NUMBER, 
	"IO_INTERCONNECT_BYTES_DELTA" NUMBER, 
	"PHYSICAL_READ_REQUESTS_TOTAL" NUMBER, 
	"PHYSICAL_READ_REQUESTS_DELTA" NUMBER, 
	"PHYSICAL_READ_BYTES_TOTAL" NUMBER, 
	"PHYSICAL_READ_BYTES_DELTA" NUMBER, 
	"PHYSICAL_WRITE_REQUESTS_TOTAL" NUMBER, 
	"PHYSICAL_WRITE_REQUESTS_DELTA" NUMBER, 
	"PHYSICAL_WRITE_BYTES_TOTAL" NUMBER, 
	"PHYSICAL_WRITE_BYTES_DELTA" NUMBER, 
	"OPTIMIZED_PHYSICAL_READS_TOTAL" NUMBER, 
	"OPTIMIZED_PHYSICAL_READS_DELTA" NUMBER, 
	"CELL_UNCOMPRESSED_BYTES_TOTAL" NUMBER, 
	"CELL_UNCOMPRESSED_BYTES_DELTA" NUMBER, 
	"IO_OFFLOAD_RETURN_BYTES_TOTAL" NUMBER, 
	"IO_OFFLOAD_RETURN_BYTES_DELTA" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null, 
	"OBSOLETE_COUNT" NUMBER DEFAULT 0
   ) PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARTITION BY RANGE ("DBID","SNAP_ID") 
 (PARTITION "WRH$_SQLSTAT_692950692_0"  VALUES LESS THAN (692950692, MAXVALUE) 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRH$_SQLSTAT_MXDB_MXSN"  VALUES LESS THAN (MAXVALUE, MAXVALUE) 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" )  ENABLE ROW MOVEMENT ;
  GRANT DELETE ON "SYS"."WRH$_SQLSTAT" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_SQLSTAT" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_SQLSTAT" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_SQLSTAT" TO "SYSUMF_ROLE";
