--------------------------------------------------------
--  Constraints for Table WRH$_PROCESS_WAITTIME_BL
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_PROCESS_WAITTIME_BL" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_PROCESS_WAITTIME_BL" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_PROCESS_WAITTIME_BL" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_PROCESS_WAITTIME_BL" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_PROCESS_WAITTIME_BL" ADD CONSTRAINT "WRH$_PROCESS_WAITTIME_BL_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "CON_DBID", "PROCESS_TYPE", "DESCRIPTION", "WAIT_CLASS_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
