--------------------------------------------------------
--  Constraints for Table WRH$_LOG
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_LOG" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LOG" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LOG" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LOG" MODIFY ("GROUP#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LOG" MODIFY ("THREAD#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LOG" MODIFY ("SEQUENCE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LOG" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LOG" ADD CONSTRAINT "WRH$_LOG_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "GROUP#", "THREAD#", "SEQUENCE#", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
