--------------------------------------------------------
--  Constraints for Table WRH$_CON_SYSTEM_EVENT_BL
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_CON_SYSTEM_EVENT_BL" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CON_SYSTEM_EVENT_BL" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CON_SYSTEM_EVENT_BL" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CON_SYSTEM_EVENT_BL" MODIFY ("EVENT_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CON_SYSTEM_EVENT_BL" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CON_SYSTEM_EVENT_BL" ADD CONSTRAINT "WRH$_CON_SYSTEM_EVENT_BL_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "EVENT_ID", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
