--------------------------------------------------------
--  DDL for Table WRH$_CON_SYSTEM_EVENT_BL
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_CON_SYSTEM_EVENT_BL" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"EVENT_ID" NUMBER, 
	"TOTAL_WAITS" NUMBER, 
	"TOTAL_TIMEOUTS" NUMBER, 
	"TIME_WAITED_MICRO" NUMBER, 
	"TOTAL_WAITS_FG" NUMBER, 
	"TOTAL_TIMEOUTS_FG" NUMBER, 
	"TIME_WAITED_MICRO_FG" NUMBER, 
	"CON_DBID" NUMBER, 
	"PER_PDB" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
