--------------------------------------------------------
--  DDL for Table WRH$_SYSTEM_EVENT
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_SYSTEM_EVENT" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"EVENT_ID" NUMBER, 
	"TOTAL_WAITS" NUMBER, 
	"TOTAL_TIMEOUTS" NUMBER, 
	"TIME_WAITED_MICRO" NUMBER, 
	"TOTAL_WAITS_FG" NUMBER, 
	"TOTAL_TIMEOUTS_FG" NUMBER, 
	"TIME_WAITED_MICRO_FG" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARTITION BY RANGE ("DBID","SNAP_ID") 
 (PARTITION "WRH$_SYSTEM_EVENT_692950692_0"  VALUES LESS THAN (692950692, MAXVALUE) 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRH$_SYSTEM_EVEN_MXDB_MXSN"  VALUES LESS THAN (MAXVALUE, MAXVALUE) 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" )  ENABLE ROW MOVEMENT ;
  GRANT DELETE ON "SYS"."WRH$_SYSTEM_EVENT" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_SYSTEM_EVENT" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_SYSTEM_EVENT" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_SYSTEM_EVENT" TO "SYSUMF_ROLE";
