--------------------------------------------------------
--  Constraints for Table WRH$_RSRC_PDB_METRIC
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_RSRC_PDB_METRIC" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_PDB_METRIC" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_PDB_METRIC" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_PDB_METRIC" MODIFY ("BEGIN_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_PDB_METRIC" MODIFY ("END_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_PDB_METRIC" MODIFY ("INTSIZE_CSEC" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_PDB_METRIC" MODIFY ("SEQUENCE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_PDB_METRIC" MODIFY ("CPU_CONSUMED_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_PDB_METRIC" MODIFY ("CPU_WAIT_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_PDB_METRIC" MODIFY ("IO_REQUESTS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_PDB_METRIC" MODIFY ("IO_MEGABYTES" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_PDB_METRIC" MODIFY ("IO_REQUESTS_THROTTLE_EXEMPT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_PDB_METRIC" MODIFY ("IO_MEGABYTES_THROTTLE_EXEMPT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_PDB_METRIC" MODIFY ("IO_THROTTLE_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_PDB_METRIC" MODIFY ("PQ_ACTIVE_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_PDB_METRIC" MODIFY ("PQ_QUEUED_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_PDB_METRIC" MODIFY ("PS_ACTIVE_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_PDB_METRIC" MODIFY ("PS_QUEUED_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_PDB_METRIC" MODIFY ("SGA_BYTES" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_PDB_METRIC" MODIFY ("BUFFER_CACHE_BYTES" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_PDB_METRIC" MODIFY ("SHARED_POOL_BYTES" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_PDB_METRIC" MODIFY ("PGA_BYTES" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_PDB_METRIC" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_PDB_METRIC" MODIFY ("OS_NUM_CPUS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_PDB_METRIC" MODIFY ("MAX_AVG_RNG_SESS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_RSRC_PDB_METRIC" ADD CONSTRAINT "WRH$_RSRC_PDB_METRIC_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "BEGIN_TIME", "SEQUENCE#", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
