--------------------------------------------------------
--  DDL for Table WRH$_MUTEX_SLEEP
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_MUTEX_SLEEP" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"MUTEX_TYPE" VARCHAR2(32 BYTE), 
	"LOCATION" VARCHAR2(40 BYTE), 
	"SLEEPS" NUMBER, 
	"WAIT_TIME" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_MUTEX_SLEEP" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_MUTEX_SLEEP" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_MUTEX_SLEEP" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_MUTEX_SLEEP" TO "SYSUMF_ROLE";
