--------------------------------------------------------
--  Constraints for Table WRH$_ASM_DISK_STAT_SUMMARY
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_ASM_DISK_STAT_SUMMARY" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_ASM_DISK_STAT_SUMMARY" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_ASM_DISK_STAT_SUMMARY" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_ASM_DISK_STAT_SUMMARY" MODIFY ("GROUP_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_ASM_DISK_STAT_SUMMARY" ADD CONSTRAINT "WRH$_ASM_DISK_STAT_SUMMARY_PK" PRIMARY KEY ("SNAP_ID", "DBID", "INSTANCE_NUMBER", "GROUP_NUMBER", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  LOCAL
 (PARTITION "WRH$_ASM_DISK_STAT_SUMMARY_692950692_0" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRH$_ASM_DISK_ST_MXDB_MXSN" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" )  ENABLE;
