--------------------------------------------------------
--  DDL for Table WRH$_FILESTATXS_BL
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_FILESTATXS_BL" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"FILE#" NUMBER, 
	"CREATION_CHANGE#" NUMBER, 
	"PHYRDS" NUMBER, 
	"PHYWRTS" NUMBER, 
	"SINGLEBLKRDS" NUMBER, 
	"READTIM" NUMBER, 
	"WRITETIM" NUMBER, 
	"SINGLEBLKRDTIM" NUMBER, 
	"PHYBLKRD" NUMBER, 
	"PHYBLKWRT" NUMBER, 
	"WAIT_COUNT" NUMBER, 
	"TIME" NUMBER, 
	"CON_DBID" NUMBER, 
	"OPTIMIZED_PHYBLKRD" NUMBER, 
	"PER_PDB" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
