--------------------------------------------------------
--  DDL for Table WRH$_RSRC_PLAN
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_RSRC_PLAN" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"SEQUENCE#" NUMBER, 
	"START_TIME" DATE, 
	"END_TIME" DATE, 
	"PLAN_ID" NUMBER, 
	"PLAN_NAME" VARCHAR2(128 BYTE), 
	"CPU_MANAGED" VARCHAR2(4 BYTE), 
	"PARALLEL_EXECUTION_MANAGED" VARCHAR2(4 BYTE), 
	"CON_DBID" NUMBER DEFAULT 0, 
	"INSTANCE_CAGING" VARCHAR2(4 BYTE), 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_RSRC_PLAN" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_RSRC_PLAN" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_RSRC_PLAN" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_RSRC_PLAN" TO "SYSUMF_ROLE";
