--------------------------------------------------------
--  Constraints for Table WRH$_SGASTAT_BL
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_SGASTAT_BL" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SGASTAT_BL" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SGASTAT_BL" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SGASTAT_BL" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SGASTAT_BL" ADD CONSTRAINT "WRH$_SGASTAT_BL_U" UNIQUE ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "NAME", "POOL", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
