--------------------------------------------------------
--  Constraints for Table WRH$_SERVICE_WAIT_CLASS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_SERVICE_WAIT_CLASS" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SERVICE_WAIT_CLASS" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SERVICE_WAIT_CLASS" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SERVICE_WAIT_CLASS" MODIFY ("SERVICE_NAME_HASH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SERVICE_WAIT_CLASS" MODIFY ("WAIT_CLASS_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SERVICE_WAIT_CLASS" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SERVICE_WAIT_CLASS" ADD CONSTRAINT "WRH$_SERVICE_WAIT_CLASS_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "SERVICE_NAME_HASH", "WAIT_CLASS_ID", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  LOCAL
 (PARTITION "WRH$_SERVICE_WAIT_CLASS_692950692_0" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRH$_SERVICE_WAIT_MXDB_MXSN" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" )  ENABLE;
