--------------------------------------------------------
--  DDL for Table WRH$_IOSTAT_FUNCTION
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_IOSTAT_FUNCTION" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"FUNCTION_ID" NUMBER, 
	"SMALL_READ_MEGABYTES" NUMBER, 
	"SMALL_WRITE_MEGABYTES" NUMBER, 
	"LARGE_READ_MEGABYTES" NUMBER, 
	"LARGE_WRITE_MEGABYTES" NUMBER, 
	"SMALL_READ_REQS" NUMBER, 
	"SMALL_WRITE_REQS" NUMBER, 
	"LARGE_READ_REQS" NUMBER, 
	"LARGE_WRITE_REQS" NUMBER, 
	"NUMBER_OF_WAITS" NUMBER, 
	"WAIT_TIME" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_IOSTAT_FUNCTION" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_IOSTAT_FUNCTION" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_IOSTAT_FUNCTION" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_IOSTAT_FUNCTION" TO "SYSUMF_ROLE";
