--------------------------------------------------------
--  DDL for Table WRH$_MTTR_TARGET_ADVICE
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_MTTR_TARGET_ADVICE" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"MTTR_TARGET_FOR_ESTIMATE" NUMBER, 
	"ADVICE_STATUS" VARCHAR2(5 BYTE), 
	"DIRTY_LIMIT" NUMBER, 
	"ESTD_CACHE_WRITES" NUMBER, 
	"ESTD_CACHE_WRITE_FACTOR" NUMBER, 
	"ESTD_TOTAL_WRITES" NUMBER, 
	"ESTD_TOTAL_WRITE_FACTOR" NUMBER, 
	"ESTD_TOTAL_IOS" NUMBER, 
	"ESTD_TOTAL_IO_FACTOR" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_MTTR_TARGET_ADVICE" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_MTTR_TARGET_ADVICE" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_MTTR_TARGET_ADVICE" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_MTTR_TARGET_ADVICE" TO "SYSUMF_ROLE";
