--------------------------------------------------------
--  Constraints for Table WRH$_TOPLEVELCALL_NAME
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_TOPLEVELCALL_NAME" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_TOPLEVELCALL_NAME" MODIFY ("TOP_LEVEL_CALL#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_TOPLEVELCALL_NAME" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_TOPLEVELCALL_NAME" ADD CONSTRAINT "WRH$_TOPLEVELCALL_NAME_PK" PRIMARY KEY ("DBID", "TOP_LEVEL_CALL#", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
