--------------------------------------------------------
--  Constraints for Table WRH$_SQL_PLAN
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_SQL_PLAN" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SQL_PLAN" MODIFY ("SQL_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SQL_PLAN" MODIFY ("PLAN_HASH_VALUE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SQL_PLAN" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SQL_PLAN" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SQL_PLAN" ADD CONSTRAINT "WRH$_SQL_PLAN_PK" PRIMARY KEY ("DBID", "SQL_ID", "PLAN_HASH_VALUE", "ID", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
