--------------------------------------------------------
--  DDL for Table WRH$_TABLESPACE
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_TABLESPACE" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"TS#" NUMBER, 
	"TSNAME" VARCHAR2(30 BYTE), 
	"CONTENTS" VARCHAR2(30 BYTE), 
	"SEGMENT_SPACE_MANAGEMENT" VARCHAR2(30 BYTE), 
	"EXTENT_MANAGEMENT" VARCHAR2(30 BYTE), 
	"CON_DBID" NUMBER DEFAULT 0, 
	"BLOCK_SIZE" NUMBER, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_TABLESPACE" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_TABLESPACE" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_TABLESPACE" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_TABLESPACE" TO "SYSUMF_ROLE";
