--------------------------------------------------------
--  Constraints for Table WRH$_SESS_NETWORK
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_SESS_NETWORK" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SESS_NETWORK" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SESS_NETWORK" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SESS_NETWORK" MODIFY ("SESSION_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SESS_NETWORK" MODIFY ("SERIAL#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SESS_NETWORK" MODIFY ("CHANNEL_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SESS_NETWORK" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SESS_NETWORK" ADD CONSTRAINT "WRH$_SESS_NETWORK_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "CON_DBID", "SESSION_ID", "SERIAL#", "CHANNEL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  LOCAL
 (PARTITION "WRH$_SESS_NETWORK_692950692_0" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRH$_SESS_NETWORK_MXDB_MXSN" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" )  ENABLE;
