--------------------------------------------------------
--  Constraints for Table WRH$_CELL_DB_BL
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_CELL_DB_BL" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CELL_DB_BL" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CELL_DB_BL" MODIFY ("CELL_HASH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CELL_DB_BL" MODIFY ("INCARNATION_NUM" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CELL_DB_BL" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CELL_DB_BL" MODIFY ("SRC_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CELL_DB_BL" ADD CONSTRAINT "WRH$_CELL_DB_BL_PK" PRIMARY KEY ("DBID", "SNAP_ID", "SRC_DBID", "CELL_HASH", "INCARNATION_NUM", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
