--------------------------------------------------------
--  Constraints for Table WRH$_WAITCLASSMETRIC_HISTORY
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_WAITCLASSMETRIC_HISTORY" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_WAITCLASSMETRIC_HISTORY" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_WAITCLASSMETRIC_HISTORY" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_WAITCLASSMETRIC_HISTORY" MODIFY ("WAIT_CLASS_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_WAITCLASSMETRIC_HISTORY" MODIFY ("BEGIN_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_WAITCLASSMETRIC_HISTORY" MODIFY ("END_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_WAITCLASSMETRIC_HISTORY" MODIFY ("INTSIZE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_WAITCLASSMETRIC_HISTORY" MODIFY ("GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_WAITCLASSMETRIC_HISTORY" MODIFY ("AVERAGE_WAITER_COUNT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_WAITCLASSMETRIC_HISTORY" MODIFY ("DBTIME_IN_WAIT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_WAITCLASSMETRIC_HISTORY" MODIFY ("TIME_WAITED" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_WAITCLASSMETRIC_HISTORY" MODIFY ("WAIT_COUNT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_WAITCLASSMETRIC_HISTORY" MODIFY ("CON_DBID" NOT NULL ENABLE);
