--------------------------------------------------------
--  Constraints for Table WRH$_SGA_TARGET_ADVICE
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_SGA_TARGET_ADVICE" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SGA_TARGET_ADVICE" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SGA_TARGET_ADVICE" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SGA_TARGET_ADVICE" MODIFY ("SGA_SIZE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SGA_TARGET_ADVICE" MODIFY ("SGA_SIZE_FACTOR" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SGA_TARGET_ADVICE" MODIFY ("ESTD_DB_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SGA_TARGET_ADVICE" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SGA_TARGET_ADVICE" ADD CONSTRAINT "WRH$_SGA_TARGET_ADVICE_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "SGA_SIZE", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
