--------------------------------------------------------
--  Constraints for Table WRH$_INST_CACHE_TRANSFER
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_INST_CACHE_TRANSFER" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_INST_CACHE_TRANSFER" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_INST_CACHE_TRANSFER" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_INST_CACHE_TRANSFER" MODIFY ("INSTANCE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_INST_CACHE_TRANSFER" MODIFY ("CLASS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_INST_CACHE_TRANSFER" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_INST_CACHE_TRANSFER" ADD CONSTRAINT "WRH$_INST_CACHE_TRANSFER_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "INSTANCE", "CLASS", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  LOCAL
 (PARTITION "WRH$_INST_CACHE_TRANSFER_692950692_0" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRH$_INST_CACHE_MXDB_MXSN" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" )  ENABLE;
