--------------------------------------------------------
--  DDL for Table WRH$_TABLESPACE_STAT_BL
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_TABLESPACE_STAT_BL" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"TS#" NUMBER, 
	"TSNAME" VARCHAR2(30 BYTE), 
	"CONTENTS" VARCHAR2(9 BYTE), 
	"STATUS" VARCHAR2(9 BYTE), 
	"SEGMENT_SPACE_MANAGEMENT" VARCHAR2(6 BYTE), 
	"EXTENT_MANAGEMENT" VARCHAR2(10 BYTE), 
	"IS_BACKUP" VARCHAR2(5 BYTE), 
	"CON_DBID" NUMBER, 
	"PER_PDB" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
