--------------------------------------------------------
--  DDL for Table WRH$_ACTIVE_SESSION_HISTORY
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_ACTIVE_SESSION_HISTORY" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"SAMPLE_ID" NUMBER, 
	"SAMPLE_TIME" TIMESTAMP (3), 
	"SESSION_ID" NUMBER, 
	"SESSION_SERIAL#" NUMBER, 
	"USER_ID" NUMBER, 
	"SQL_ID" VARCHAR2(13 BYTE), 
	"SQL_CHILD_NUMBER" NUMBER, 
	"SQL_PLAN_HASH_VALUE" NUMBER, 
	"SERVICE_HASH" NUMBER, 
	"SESSION_TYPE" NUMBER, 
	"SQL_OPCODE" NUMBER, 
	"QC_SESSION_ID" NUMBER, 
	"QC_INSTANCE_ID" NUMBER, 
	"CURRENT_OBJ#" NUMBER, 
	"CURRENT_FILE#" NUMBER, 
	"CURRENT_BLOCK#" NUMBER, 
	"SEQ#" NUMBER, 
	"EVENT_ID" NUMBER, 
	"P1" NUMBER, 
	"P2" NUMBER, 
	"P3" NUMBER, 
	"WAIT_TIME" NUMBER, 
	"TIME_WAITED" NUMBER, 
	"PROGRAM" VARCHAR2(64 BYTE), 
	"MODULE" VARCHAR2(64 BYTE), 
	"ACTION" VARCHAR2(64 BYTE), 
	"CLIENT_ID" VARCHAR2(64 BYTE), 
	"FORCE_MATCHING_SIGNATURE" NUMBER, 
	"BLOCKING_SESSION" NUMBER, 
	"BLOCKING_SESSION_SERIAL#" NUMBER, 
	"XID" RAW(8), 
	"CONSUMER_GROUP_ID" NUMBER, 
	"PLSQL_ENTRY_OBJECT_ID" NUMBER, 
	"PLSQL_ENTRY_SUBPROGRAM_ID" NUMBER, 
	"PLSQL_OBJECT_ID" NUMBER, 
	"PLSQL_SUBPROGRAM_ID" NUMBER, 
	"QC_SESSION_SERIAL#" NUMBER, 
	"REMOTE_INSTANCE#" NUMBER, 
	"SQL_PLAN_LINE_ID" NUMBER, 
	"SQL_PLAN_OPERATION#" NUMBER, 
	"SQL_PLAN_OPTIONS#" NUMBER, 
	"SQL_EXEC_ID" NUMBER, 
	"SQL_EXEC_START" DATE, 
	"TIME_MODEL" NUMBER, 
	"TOP_LEVEL_SQL_ID" VARCHAR2(13 BYTE), 
	"TOP_LEVEL_SQL_OPCODE" NUMBER, 
	"CURRENT_ROW#" NUMBER, 
	"FLAGS" NUMBER, 
	"BLOCKING_INST_ID" NUMBER, 
	"ECID" VARCHAR2(64 BYTE), 
	"TM_DELTA_TIME" NUMBER, 
	"TM_DELTA_CPU_TIME" NUMBER, 
	"TM_DELTA_DB_TIME" NUMBER, 
	"DELTA_TIME" NUMBER, 
	"DELTA_READ_IO_REQUESTS" NUMBER, 
	"DELTA_WRITE_IO_REQUESTS" NUMBER, 
	"DELTA_READ_IO_BYTES" NUMBER, 
	"DELTA_WRITE_IO_BYTES" NUMBER, 
	"DELTA_INTERCONNECT_IO_BYTES" NUMBER, 
	"PGA_ALLOCATED" NUMBER, 
	"TEMP_SPACE_ALLOCATED" NUMBER, 
	"TOP_LEVEL_CALL#" NUMBER, 
	"MACHINE" VARCHAR2(64 BYTE), 
	"PORT" NUMBER, 
	"DBREPLAY_FILE_ID" NUMBER, 
	"DBREPLAY_CALL_COUNTER" NUMBER, 
	"PX_FLAGS" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"DBOP_NAME" VARCHAR2(64 BYTE), 
	"DBOP_EXEC_ID" NUMBER, 
	"SQL_FULL_PLAN_HASH_VALUE" NUMBER, 
	"SQL_ADAPTIVE_PLAN_RESOLVED" NUMBER, 
	"USECS_PER_ROW" NUMBER, 
	"SAMPLE_TIME_UTC" TIMESTAMP (3), 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARTITION BY RANGE ("DBID","SNAP_ID") 
 (PARTITION "WRH$_ACTIVE_SESSION_HISTORY_692950692_0"  VALUES LESS THAN (692950692, MAXVALUE) 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRH$_ACTIVE_SES_MXDB_MXSN"  VALUES LESS THAN (MAXVALUE, MAXVALUE) 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" )  ENABLE ROW MOVEMENT ;
  GRANT DELETE ON "SYS"."WRH$_ACTIVE_SESSION_HISTORY" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_ACTIVE_SESSION_HISTORY" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_ACTIVE_SESSION_HISTORY" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_ACTIVE_SESSION_HISTORY" TO "SYSUMF_ROLE";
