--------------------------------------------------------
--  DDL for Table WRH$_CELL_IOREASON_NAME
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_CELL_IOREASON_NAME" SHARING=METADATA 
   (	"DBID" NUMBER, 
	"REASON_ID" NUMBER, 
	"REASON_NAME" VARCHAR2(257 BYTE), 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_CELL_IOREASON_NAME" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_CELL_IOREASON_NAME" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_CELL_IOREASON_NAME" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_CELL_IOREASON_NAME" TO "SYSUMF_ROLE";
