--------------------------------------------------------
--  Constraints for Table WRH$_DB_CACHE_ADVICE
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_DB_CACHE_ADVICE" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_DB_CACHE_ADVICE" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_DB_CACHE_ADVICE" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_DB_CACHE_ADVICE" MODIFY ("BPID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_DB_CACHE_ADVICE" MODIFY ("BUFFERS_FOR_ESTIMATE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_DB_CACHE_ADVICE" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_DB_CACHE_ADVICE" ADD CONSTRAINT "WRH$_DB_CACHE_ADVICE_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "BPID", "BUFFERS_FOR_ESTIMATE", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  LOCAL
 (PARTITION "WRH$_DB_CACHE_ADVICE_692950692_0" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRH$_DB_CACHE_AD_MXDB_MXSN" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" )  ENABLE;
