--------------------------------------------------------
--  DDL for Table WRH$_PROCESS_WAITTIME
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_PROCESS_WAITTIME" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"PROCESS_TYPE" VARCHAR2(5 BYTE), 
	"DESCRIPTION" VARCHAR2(64 BYTE), 
	"WAIT_CLASS_TYPE" VARCHAR2(64 BYTE), 
	"VALUE" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARTITION BY RANGE ("DBID","SNAP_ID") 
 (PARTITION "WRH$_PROCESS_WAITTIME_692950692_0"  VALUES LESS THAN (692950692, MAXVALUE) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRH$_PROCESS_WAITTIM_MXDB_MXSN"  VALUES LESS THAN (MAXVALUE, MAXVALUE) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ) ;
  GRANT DELETE ON "SYS"."WRH$_PROCESS_WAITTIME" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_PROCESS_WAITTIME" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_PROCESS_WAITTIME" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_PROCESS_WAITTIME" TO "SYSUMF_ROLE";
