--------------------------------------------------------
--  Constraints for Table WRH$_MUTEX_SLEEP
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_MUTEX_SLEEP" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_MUTEX_SLEEP" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_MUTEX_SLEEP" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_MUTEX_SLEEP" MODIFY ("MUTEX_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_MUTEX_SLEEP" MODIFY ("LOCATION" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_MUTEX_SLEEP" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_MUTEX_SLEEP" ADD CONSTRAINT "WRH$_MUTEX_SLEEP_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "MUTEX_TYPE", "LOCATION", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
