--------------------------------------------------------
--  DDL for Table WRH$_AWR_TEST_1
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_AWR_TEST_1" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"STEP_ID" NUMBER
   ) PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARTITION BY RANGE ("DBID","SNAP_ID") 
 (PARTITION "WRH$_AWR_TEST_1_692950692_0"  VALUES LESS THAN (692950692, MAXVALUE) 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRH$_AWR_TEST_1_MXDB_MXSN"  VALUES LESS THAN (MAXVALUE, MAXVALUE) 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" )  ENABLE ROW MOVEMENT ;
  GRANT DELETE ON "SYS"."WRH$_AWR_TEST_1" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_AWR_TEST_1" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_AWR_TEST_1" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_AWR_TEST_1" TO "SYSUMF_ROLE";
