--------------------------------------------------------
--  DDL for Table WRH$_RSRC_CONSUMER_GROUP
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_RSRC_CONSUMER_GROUP" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"SEQUENCE#" NUMBER, 
	"CONSUMER_GROUP_ID" NUMBER, 
	"CONSUMER_GROUP_NAME" VARCHAR2(128 BYTE), 
	"REQUESTS" NUMBER, 
	"CPU_WAIT_TIME" NUMBER, 
	"CPU_WAITS" NUMBER, 
	"CONSUMED_CPU_TIME" NUMBER, 
	"YIELDS" NUMBER, 
	"ACTIVE_SESS_LIMIT_HIT" NUMBER, 
	"UNDO_LIMIT_HIT" NUMBER, 
	"SWITCHES_IN_CPU_TIME" NUMBER, 
	"SWITCHES_OUT_CPU_TIME" NUMBER, 
	"SWITCHES_IN_IO_MEGABYTES" NUMBER, 
	"SWITCHES_OUT_IO_MEGABYTES" NUMBER, 
	"SWITCHES_IN_IO_REQUESTS" NUMBER, 
	"SWITCHES_OUT_IO_REQUESTS" NUMBER, 
	"SQL_CANCELED" NUMBER, 
	"ACTIVE_SESS_KILLED" NUMBER, 
	"IDLE_SESS_KILLED" NUMBER, 
	"IDLE_BLKR_SESS_KILLED" NUMBER, 
	"QUEUED_TIME" NUMBER, 
	"QUEUE_TIME_OUTS" NUMBER, 
	"IO_SERVICE_TIME" NUMBER, 
	"IO_SERVICE_WAITS" NUMBER, 
	"SMALL_READ_MEGABYTES" NUMBER, 
	"SMALL_WRITE_MEGABYTES" NUMBER, 
	"LARGE_READ_MEGABYTES" NUMBER, 
	"LARGE_WRITE_MEGABYTES" NUMBER, 
	"SMALL_READ_REQUESTS" NUMBER, 
	"SMALL_WRITE_REQUESTS" NUMBER, 
	"LARGE_READ_REQUESTS" NUMBER, 
	"LARGE_WRITE_REQUESTS" NUMBER, 
	"PQS_QUEUED" NUMBER, 
	"PQ_QUEUED_TIME" NUMBER, 
	"PQ_QUEUE_TIME_OUTS" NUMBER, 
	"PQS_COMPLETED" NUMBER, 
	"PQ_SERVERS_USED" NUMBER, 
	"PQ_ACTIVE_TIME" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"SWITCHES_IN_IO_LOGICAL" NUMBER DEFAULT 0, 
	"SWITCHES_OUT_IO_LOGICAL" NUMBER DEFAULT 0, 
	"SWITCHES_IN_ELAPSED_TIME" NUMBER DEFAULT 0, 
	"SWITCHES_OUT_ELAPSED_TIME" NUMBER DEFAULT 0, 
	"PGA_LIMIT_SESSIONS_KILLED" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_RSRC_CONSUMER_GROUP" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_RSRC_CONSUMER_GROUP" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_RSRC_CONSUMER_GROUP" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_RSRC_CONSUMER_GROUP" TO "SYSUMF_ROLE";
