--------------------------------------------------------
--  DDL for Table WRH$_COMP_IOSTAT
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_COMP_IOSTAT" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"COMPONENT" VARCHAR2(64 BYTE), 
	"FILE_TYPE" VARCHAR2(64 BYTE), 
	"IO_TYPE" CHAR(5 BYTE), 
	"OPERATION" CHAR(5 BYTE), 
	"BYTES" NUMBER, 
	"IO_COUNT" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_COMP_IOSTAT" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_COMP_IOSTAT" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_COMP_IOSTAT" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_COMP_IOSTAT" TO "SYSUMF_ROLE";
