--------------------------------------------------------
--  Constraints for Table WRH$_FILESTATXS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_FILESTATXS" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_FILESTATXS" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_FILESTATXS" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_FILESTATXS" MODIFY ("FILE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_FILESTATXS" MODIFY ("CREATION_CHANGE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_FILESTATXS" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_FILESTATXS" ADD CONSTRAINT "WRH$_FILESTATXS_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "FILE#", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  LOCAL
 (PARTITION "WRH$_FILESTATXS_692950692_0" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRH$_FILESTATXS_MXDB_MXSN" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" )  ENABLE;
