--------------------------------------------------------
--  Constraints for Table WRH$_EVENT_NAME
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_EVENT_NAME" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_EVENT_NAME" MODIFY ("EVENT_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_EVENT_NAME" MODIFY ("EVENT_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_EVENT_NAME" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_EVENT_NAME" ADD CONSTRAINT "WRH$_EVENT_NAME_PK" PRIMARY KEY ("DBID", "EVENT_ID", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
