--------------------------------------------------------
--  Constraints for Table WRH$_BUFFER_POOL_STATISTICS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_BUFFER_POOL_STATISTICS" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_BUFFER_POOL_STATISTICS" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_BUFFER_POOL_STATISTICS" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_BUFFER_POOL_STATISTICS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_BUFFER_POOL_STATISTICS" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_BUFFER_POOL_STATISTICS" ADD CONSTRAINT "WRH$_BUFFER_POOL_STATS_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "ID", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
