--------------------------------------------------------
--  Constraints for Table WRH$_LATCH_MISSES_SUMMARY_BL
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_LATCH_MISSES_SUMMARY_BL" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LATCH_MISSES_SUMMARY_BL" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LATCH_MISSES_SUMMARY_BL" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LATCH_MISSES_SUMMARY_BL" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LATCH_MISSES_SUMMARY_BL" ADD CONSTRAINT "WRH$_LATCH_MISSES_SUMRY_BL_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "PARENT_NAME", "WHERE_IN_CODE", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
