--------------------------------------------------------
--  DDL for Table WRH$_ENQUEUE_STAT
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_ENQUEUE_STAT" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"EQ_TYPE" VARCHAR2(2 BYTE), 
	"REQ_REASON" VARCHAR2(64 BYTE), 
	"TOTAL_REQ#" NUMBER, 
	"TOTAL_WAIT#" NUMBER, 
	"SUCC_REQ#" NUMBER, 
	"FAILED_REQ#" NUMBER, 
	"CUM_WAIT_TIME" NUMBER, 
	"EVENT#" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_ENQUEUE_STAT" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_ENQUEUE_STAT" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_ENQUEUE_STAT" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_ENQUEUE_STAT" TO "SYSUMF_ROLE";
