--------------------------------------------------------
--  DDL for Table WRH$_IC_DEVICE_STATS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_IC_DEVICE_STATS" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"IF_NAME" VARCHAR2(256 BYTE), 
	"IP_ADDR" VARCHAR2(64 BYTE), 
	"NET_MASK" VARCHAR2(16 BYTE), 
	"FLAGS" VARCHAR2(32 BYTE), 
	"MTU" NUMBER, 
	"BYTES_RECEIVED" NUMBER, 
	"PACKETS_RECEIVED" NUMBER, 
	"RECEIVE_ERRORS" NUMBER, 
	"RECEIVE_DROPPED" NUMBER, 
	"RECEIVE_BUF_OR" NUMBER, 
	"RECEIVE_FRAME_ERR" NUMBER, 
	"BYTES_SENT" NUMBER, 
	"PACKETS_SENT" NUMBER, 
	"SEND_ERRORS" NUMBER, 
	"SENDS_DROPPED" NUMBER, 
	"SEND_BUF_OR" NUMBER, 
	"SEND_CARRIER_LOST" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_IC_DEVICE_STATS" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_IC_DEVICE_STATS" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_IC_DEVICE_STATS" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_IC_DEVICE_STATS" TO "SYSUMF_ROLE";
