--------------------------------------------------------
--  DDL for Table WRH$_LIBRARYCACHE
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_LIBRARYCACHE" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"NAMESPACE" VARCHAR2(15 BYTE), 
	"GETS" NUMBER, 
	"GETHITS" NUMBER, 
	"PINS" NUMBER, 
	"PINHITS" NUMBER, 
	"RELOADS" NUMBER, 
	"INVALIDATIONS" NUMBER, 
	"DLM_LOCK_REQUESTS" NUMBER, 
	"DLM_PIN_REQUESTS" NUMBER, 
	"DLM_PIN_RELEASES" NUMBER, 
	"DLM_INVALIDATION_REQUESTS" NUMBER, 
	"DLM_INVALIDATIONS" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_LIBRARYCACHE" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_LIBRARYCACHE" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_LIBRARYCACHE" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_LIBRARYCACHE" TO "SYSUMF_ROLE";
