--------------------------------------------------------
--  Constraints for Table WRH$_STREAMS_CAPTURE
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_STREAMS_CAPTURE" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_STREAMS_CAPTURE" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_STREAMS_CAPTURE" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_STREAMS_CAPTURE" MODIFY ("CAPTURE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_STREAMS_CAPTURE" MODIFY ("STARTUP_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_STREAMS_CAPTURE" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_STREAMS_CAPTURE" MODIFY ("SESSION_MODULE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_STREAMS_CAPTURE" ADD CONSTRAINT "WRH$_STREAMS_CAPTURE_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "CAPTURE_NAME", "SESSION_MODULE", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
