--------------------------------------------------------
--  Constraints for Table WRH$_PERSISTENT_QMN_CACHE
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_PERSISTENT_QMN_CACHE" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_PERSISTENT_QMN_CACHE" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_PERSISTENT_QMN_CACHE" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_PERSISTENT_QMN_CACHE" MODIFY ("QUEUE_TABLE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_PERSISTENT_QMN_CACHE" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_PERSISTENT_QMN_CACHE" ADD CONSTRAINT "WRH$_PERSISTENT_QMN_CACHE_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "QUEUE_TABLE_ID", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
