--------------------------------------------------------
--  Constraints for Table WRH$_LATCH_CHILDREN_BL
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_LATCH_CHILDREN_BL" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LATCH_CHILDREN_BL" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LATCH_CHILDREN_BL" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LATCH_CHILDREN_BL" MODIFY ("LATCH_HASH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LATCH_CHILDREN_BL" MODIFY ("CHILD#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LATCH_CHILDREN_BL" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LATCH_CHILDREN_BL" ADD CONSTRAINT "WRH$_LATCH_CHILDREN_BL_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "LATCH_HASH", "CHILD#", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
