--------------------------------------------------------
--  DDL for Table WRH$_INTERCONNECT_PINGS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_INTERCONNECT_PINGS" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"TARGET_INSTANCE" NUMBER, 
	"CNT_500B" NUMBER, 
	"WAIT_500B" NUMBER, 
	"WAITSQ_500B" NUMBER, 
	"CNT_8K" NUMBER, 
	"WAIT_8K" NUMBER, 
	"WAITSQ_8K" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARTITION BY RANGE ("DBID","SNAP_ID") 
 (PARTITION "WRH$_INTERCONNECT_PINGS_692950692_0"  VALUES LESS THAN (692950692, MAXVALUE) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRH$_IC_PINGS_MXDB_MXSN"  VALUES LESS THAN (MAXVALUE, MAXVALUE) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" )  ENABLE ROW MOVEMENT ;
  GRANT DELETE ON "SYS"."WRH$_INTERCONNECT_PINGS" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_INTERCONNECT_PINGS" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_INTERCONNECT_PINGS" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_INTERCONNECT_PINGS" TO "SYSUMF_ROLE";
