--------------------------------------------------------
--  Constraints for Table WRH$_SQL_BIND_METADATA
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_SQL_BIND_METADATA" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SQL_BIND_METADATA" MODIFY ("SQL_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SQL_BIND_METADATA" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_SQL_BIND_METADATA" ADD CONSTRAINT "WRH$_SQL_BIND_METADATA_PK" PRIMARY KEY ("DBID", "SQL_ID", "POSITION", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
