--------------------------------------------------------
--  Constraints for Table WRH$_LATCH_PARENT
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_LATCH_PARENT" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LATCH_PARENT" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LATCH_PARENT" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LATCH_PARENT" MODIFY ("LATCH_HASH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LATCH_PARENT" MODIFY ("LEVEL#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LATCH_PARENT" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_LATCH_PARENT" ADD CONSTRAINT "WRH$_LATCH_PARENT_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "LATCH_HASH", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  LOCAL
 (PARTITION "WRH$_LATCH_PARENT_692950692_0" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRH$_LATCH_PAREN_MXDB_MXSN" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" )  ENABLE;
