--------------------------------------------------------
--  Constraints for Table WRH$_BUFFERED_SUBSCRIBERS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_BUFFERED_SUBSCRIBERS" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_BUFFERED_SUBSCRIBERS" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_BUFFERED_SUBSCRIBERS" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_BUFFERED_SUBSCRIBERS" MODIFY ("QUEUE_SCHEMA" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_BUFFERED_SUBSCRIBERS" MODIFY ("QUEUE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_BUFFERED_SUBSCRIBERS" MODIFY ("SUBSCRIBER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_BUFFERED_SUBSCRIBERS" MODIFY ("STARTUP_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_BUFFERED_SUBSCRIBERS" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_BUFFERED_SUBSCRIBERS" ADD CONSTRAINT "WRH$_BUFFERED_SUBSCRIBERS_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "QUEUE_SCHEMA", "QUEUE_NAME", "SUBSCRIBER_ID", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
