--------------------------------------------------------
--  DDL for Table WRH$_EVENT_NAME
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_EVENT_NAME" SHARING=METADATA 
   (	"DBID" NUMBER, 
	"EVENT_ID" NUMBER, 
	"EVENT_NAME" VARCHAR2(64 BYTE), 
	"PARAMETER1" VARCHAR2(64 BYTE), 
	"PARAMETER2" VARCHAR2(64 BYTE), 
	"PARAMETER3" VARCHAR2(64 BYTE), 
	"WAIT_CLASS_ID" NUMBER, 
	"WAIT_CLASS" VARCHAR2(64 BYTE), 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRH$_EVENT_NAME" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRH$_EVENT_NAME" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRH$_EVENT_NAME" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRH$_EVENT_NAME" TO "SYSUMF_ROLE";
