--------------------------------------------------------
--  Constraints for Table WRH$_CELL_CONFIG
--------------------------------------------------------

  ALTER TABLE "SYS"."WRH$_CELL_CONFIG" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CELL_CONFIG" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CELL_CONFIG" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CELL_CONFIG" MODIFY ("CURRENT_SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CELL_CONFIG" MODIFY ("CELLNAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CELL_CONFIG" MODIFY ("CELLHASH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CELL_CONFIG" MODIFY ("CONFTYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CELL_CONFIG" MODIFY ("CONFVAL_HASH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRH$_CELL_CONFIG" ADD CONSTRAINT "WRH$_CELL_CONFIG_PK" PRIMARY KEY ("DBID", "CELLHASH", "CONFTYPE", "CONFVAL_HASH", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
