--------------------------------------------------------
--  DDL for Table WRH$_SERVICE_WAIT_CLASS_BL
--------------------------------------------------------

  CREATE TABLE "SYS"."WRH$_SERVICE_WAIT_CLASS_BL" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"SERVICE_NAME_HASH" NUMBER, 
	"WAIT_CLASS_ID" NUMBER, 
	"WAIT_CLASS" VARCHAR2(64 BYTE), 
	"TOTAL_WAITS" NUMBER, 
	"TIME_WAITED" NUMBER, 
	"CON_DBID" NUMBER, 
	"PER_PDB" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
