--------------------------------------------------------
--  DDL for Table WRHS$_SQL_PLAN
--------------------------------------------------------

  CREATE TABLE "SYS"."WRHS$_SQL_PLAN" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"SQL_ID" VARCHAR2(13 BYTE), 
	"PLAN_HASH_VALUE" NUMBER, 
	"ID" NUMBER, 
	"OPERATION" VARCHAR2(30 BYTE), 
	"OPTIONS" VARCHAR2(30 BYTE), 
	"OBJECT_NODE" VARCHAR2(128 BYTE), 
	"OBJECT#" NUMBER, 
	"OBJECT_OWNER" VARCHAR2(128 BYTE), 
	"OBJECT_NAME" VARCHAR2(128 BYTE), 
	"OBJECT_ALIAS" VARCHAR2(261 BYTE), 
	"OBJECT_TYPE" VARCHAR2(20 BYTE), 
	"OPTIMIZER" VARCHAR2(20 BYTE), 
	"PARENT_ID" NUMBER, 
	"DEPTH" NUMBER, 
	"POSITION" NUMBER, 
	"SEARCH_COLUMNS" NUMBER, 
	"COST" NUMBER, 
	"CARDINALITY" NUMBER, 
	"BYTES" NUMBER, 
	"OTHER_TAG" VARCHAR2(35 BYTE), 
	"PARTITION_START" VARCHAR2(64 BYTE), 
	"PARTITION_STOP" VARCHAR2(64 BYTE), 
	"PARTITION_ID" NUMBER, 
	"OTHER" VARCHAR2(4000 BYTE), 
	"DISTRIBUTION" VARCHAR2(20 BYTE), 
	"CPU_COST" NUMBER, 
	"IO_COST" NUMBER, 
	"TEMP_SPACE" NUMBER, 
	"ACCESS_PREDICATES" VARCHAR2(4000 BYTE), 
	"FILTER_PREDICATES" VARCHAR2(4000 BYTE), 
	"PROJECTION" VARCHAR2(4000 BYTE), 
	"TIME" NUMBER, 
	"QBLOCK_NAME" VARCHAR2(128 BYTE), 
	"REMARKS" VARCHAR2(4000 BYTE), 
	"TIMESTAMP" DATE, 
	"OTHER_XML" CLOB, 
	"CON_DBID" NUMBER, 
	"PER_PDB" NUMBER, 
	"STAGE_INST_ID" NUMBER, 
	"STAGE_ID" NUMBER, 
	"OTHER_XML_L2C" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("OTHER_XML") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
  GRANT DELETE ON "SYS"."WRHS$_SQL_PLAN" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRHS$_SQL_PLAN" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRHS$_SQL_PLAN" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRHS$_SQL_PLAN" TO "SYSUMF_ROLE";
