--------------------------------------------------------
--  Constraints for Table WRHS$_SQLCOMMAND_NAME
--------------------------------------------------------

  ALTER TABLE "SYS"."WRHS$_SQLCOMMAND_NAME" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_SQLCOMMAND_NAME" MODIFY ("COMMAND_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_SQLCOMMAND_NAME" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_SQLCOMMAND_NAME" MODIFY ("STAGE_INST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_SQLCOMMAND_NAME" MODIFY ("STAGE_ID" NOT NULL ENABLE);
