--------------------------------------------------------
--  Constraints for Table WRHS$_SQL_PLAN
--------------------------------------------------------

  ALTER TABLE "SYS"."WRHS$_SQL_PLAN" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_SQL_PLAN" MODIFY ("SQL_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_SQL_PLAN" MODIFY ("PLAN_HASH_VALUE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_SQL_PLAN" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_SQL_PLAN" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_SQL_PLAN" MODIFY ("STAGE_INST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_SQL_PLAN" MODIFY ("STAGE_ID" NOT NULL ENABLE);
