--------------------------------------------------------
--  Constraints for Table WRHS$_SQL_BIND_METADATA
--------------------------------------------------------

  ALTER TABLE "SYS"."WRHS$_SQL_BIND_METADATA" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_SQL_BIND_METADATA" MODIFY ("SQL_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_SQL_BIND_METADATA" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_SQL_BIND_METADATA" MODIFY ("STAGE_INST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_SQL_BIND_METADATA" MODIFY ("STAGE_ID" NOT NULL ENABLE);
