--------------------------------------------------------
--  Constraints for Table WRHS$_TABLESPACE
--------------------------------------------------------

  ALTER TABLE "SYS"."WRHS$_TABLESPACE" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_TABLESPACE" MODIFY ("TS#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_TABLESPACE" MODIFY ("TSNAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_TABLESPACE" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_TABLESPACE" MODIFY ("STAGE_INST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_TABLESPACE" MODIFY ("STAGE_ID" NOT NULL ENABLE);
