--------------------------------------------------------
--  Constraints for Table WRHS$_OPTIMIZER_ENV
--------------------------------------------------------

  ALTER TABLE "SYS"."WRHS$_OPTIMIZER_ENV" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_OPTIMIZER_ENV" MODIFY ("OPTIMIZER_ENV_HASH_VALUE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_OPTIMIZER_ENV" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_OPTIMIZER_ENV" MODIFY ("STAGE_INST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_OPTIMIZER_ENV" MODIFY ("STAGE_ID" NOT NULL ENABLE);
