--------------------------------------------------------
--  Constraints for Table WRHS$_CELL_IOREASON_NAME
--------------------------------------------------------

  ALTER TABLE "SYS"."WRHS$_CELL_IOREASON_NAME" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_CELL_IOREASON_NAME" MODIFY ("REASON_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_CELL_IOREASON_NAME" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_CELL_IOREASON_NAME" MODIFY ("STAGE_INST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_CELL_IOREASON_NAME" MODIFY ("STAGE_ID" NOT NULL ENABLE);
