--------------------------------------------------------
--  Constraints for Table WRHS$_STAT_NAME
--------------------------------------------------------

  ALTER TABLE "SYS"."WRHS$_STAT_NAME" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_STAT_NAME" MODIFY ("STAT_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_STAT_NAME" MODIFY ("STAT_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_STAT_NAME" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_STAT_NAME" MODIFY ("STAGE_INST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_STAT_NAME" MODIFY ("STAGE_ID" NOT NULL ENABLE);
