--------------------------------------------------------
--  Constraints for Table WRHS$_CELL_METRIC_DESC
--------------------------------------------------------

  ALTER TABLE "SYS"."WRHS$_CELL_METRIC_DESC" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_CELL_METRIC_DESC" MODIFY ("METRIC_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_CELL_METRIC_DESC" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_CELL_METRIC_DESC" MODIFY ("STAGE_INST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_CELL_METRIC_DESC" MODIFY ("STAGE_ID" NOT NULL ENABLE);
