--------------------------------------------------------
--  Constraints for Table WRHS$_EVENT_NAME
--------------------------------------------------------

  ALTER TABLE "SYS"."WRHS$_EVENT_NAME" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_EVENT_NAME" MODIFY ("EVENT_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_EVENT_NAME" MODIFY ("EVENT_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_EVENT_NAME" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_EVENT_NAME" MODIFY ("STAGE_INST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_EVENT_NAME" MODIFY ("STAGE_ID" NOT NULL ENABLE);
