--------------------------------------------------------
--  Constraints for Table WRHS$_LATCH_NAME
--------------------------------------------------------

  ALTER TABLE "SYS"."WRHS$_LATCH_NAME" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_LATCH_NAME" MODIFY ("LATCH_HASH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_LATCH_NAME" MODIFY ("LATCH_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_LATCH_NAME" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_LATCH_NAME" MODIFY ("STAGE_INST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_LATCH_NAME" MODIFY ("STAGE_ID" NOT NULL ENABLE);
