--------------------------------------------------------
--  Constraints for Table WRHS$_SEG_STAT_OBJ
--------------------------------------------------------

  ALTER TABLE "SYS"."WRHS$_SEG_STAT_OBJ" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_SEG_STAT_OBJ" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_SEG_STAT_OBJ" MODIFY ("OWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_SEG_STAT_OBJ" MODIFY ("OBJECT_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_SEG_STAT_OBJ" MODIFY ("TABLESPACE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_SEG_STAT_OBJ" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_SEG_STAT_OBJ" MODIFY ("STAGE_INST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_SEG_STAT_OBJ" MODIFY ("STAGE_ID" NOT NULL ENABLE);
