--------------------------------------------------------
--  DDL for Table WRHS$_DATAFILE
--------------------------------------------------------

  CREATE TABLE "SYS"."WRHS$_DATAFILE" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"FILE#" NUMBER, 
	"CREATION_CHANGE#" NUMBER, 
	"FILENAME" VARCHAR2(513 BYTE), 
	"TS#" NUMBER, 
	"TSNAME" VARCHAR2(30 BYTE), 
	"BLOCK_SIZE" NUMBER, 
	"CON_DBID" NUMBER, 
	"PER_PDB" NUMBER, 
	"STAGE_INST_ID" NUMBER, 
	"STAGE_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
  GRANT DELETE ON "SYS"."WRHS$_DATAFILE" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRHS$_DATAFILE" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRHS$_DATAFILE" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRHS$_DATAFILE" TO "SYSUMF_ROLE";
