--------------------------------------------------------
--  Constraints for Table WRHS$_PLAN_OPTION_NAME
--------------------------------------------------------

  ALTER TABLE "SYS"."WRHS$_PLAN_OPTION_NAME" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_PLAN_OPTION_NAME" MODIFY ("OPTION_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_PLAN_OPTION_NAME" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_PLAN_OPTION_NAME" MODIFY ("STAGE_INST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_PLAN_OPTION_NAME" MODIFY ("STAGE_ID" NOT NULL ENABLE);
