--------------------------------------------------------
--  DDL for Table WRHS$_CELL_IOREASON_NAME
--------------------------------------------------------

  CREATE TABLE "SYS"."WRHS$_CELL_IOREASON_NAME" SHARING=METADATA 
   (	"DBID" NUMBER, 
	"REASON_ID" NUMBER, 
	"REASON_NAME" VARCHAR2(257 BYTE), 
	"CON_DBID" NUMBER, 
	"PER_PDB" NUMBER, 
	"STAGE_INST_ID" NUMBER, 
	"STAGE_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
  GRANT DELETE ON "SYS"."WRHS$_CELL_IOREASON_NAME" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRHS$_CELL_IOREASON_NAME" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRHS$_CELL_IOREASON_NAME" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRHS$_CELL_IOREASON_NAME" TO "SYSUMF_ROLE";
