--------------------------------------------------------
--  DDL for Table WRHS$_SQLTEXT
--------------------------------------------------------

  CREATE TABLE "SYS"."WRHS$_SQLTEXT" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"SQL_ID" VARCHAR2(13 BYTE), 
	"SQL_TEXT" CLOB, 
	"COMMAND_TYPE" NUMBER, 
	"REF_COUNT" NUMBER, 
	"CON_DBID" NUMBER, 
	"PER_PDB" NUMBER, 
	"STAGE_INST_ID" NUMBER, 
	"STAGE_ID" NUMBER, 
	"SQL_TEXT_L2C" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("SQL_TEXT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
  GRANT DELETE ON "SYS"."WRHS$_SQLTEXT" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRHS$_SQLTEXT" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRHS$_SQLTEXT" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRHS$_SQLTEXT" TO "SYSUMF_ROLE";
