--------------------------------------------------------
--  DDL for Table WRHS$_SERVICE_NAME
--------------------------------------------------------

  CREATE TABLE "SYS"."WRHS$_SERVICE_NAME" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"SERVICE_NAME_HASH" NUMBER, 
	"SERVICE_NAME" VARCHAR2(64 BYTE), 
	"CON_DBID" NUMBER, 
	"PER_PDB" NUMBER, 
	"STAGE_INST_ID" NUMBER, 
	"STAGE_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
  GRANT DELETE ON "SYS"."WRHS$_SERVICE_NAME" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRHS$_SERVICE_NAME" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRHS$_SERVICE_NAME" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRHS$_SERVICE_NAME" TO "SYSUMF_ROLE";
