--------------------------------------------------------
--  DDL for Table WRHS$_TABLESPACE
--------------------------------------------------------

  CREATE TABLE "SYS"."WRHS$_TABLESPACE" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"TS#" NUMBER, 
	"TSNAME" VARCHAR2(30 BYTE), 
	"CONTENTS" VARCHAR2(30 BYTE), 
	"SEGMENT_SPACE_MANAGEMENT" VARCHAR2(30 BYTE), 
	"EXTENT_MANAGEMENT" VARCHAR2(30 BYTE), 
	"CON_DBID" NUMBER, 
	"BLOCK_SIZE" NUMBER, 
	"PER_PDB" NUMBER, 
	"STAGE_INST_ID" NUMBER, 
	"STAGE_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
  GRANT DELETE ON "SYS"."WRHS$_TABLESPACE" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRHS$_TABLESPACE" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRHS$_TABLESPACE" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRHS$_TABLESPACE" TO "SYSUMF_ROLE";
