--------------------------------------------------------
--  Constraints for Table WRHS$_DATAFILE
--------------------------------------------------------

  ALTER TABLE "SYS"."WRHS$_DATAFILE" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_DATAFILE" MODIFY ("FILE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_DATAFILE" MODIFY ("CREATION_CHANGE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_DATAFILE" MODIFY ("FILENAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_DATAFILE" MODIFY ("TS#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_DATAFILE" MODIFY ("TSNAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_DATAFILE" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_DATAFILE" MODIFY ("STAGE_INST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_DATAFILE" MODIFY ("STAGE_ID" NOT NULL ENABLE);
