--------------------------------------------------------
--  Constraints for Table WRHS$_TEMPFILE
--------------------------------------------------------

  ALTER TABLE "SYS"."WRHS$_TEMPFILE" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_TEMPFILE" MODIFY ("FILE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_TEMPFILE" MODIFY ("CREATION_CHANGE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_TEMPFILE" MODIFY ("FILENAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_TEMPFILE" MODIFY ("TS#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_TEMPFILE" MODIFY ("TSNAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_TEMPFILE" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_TEMPFILE" MODIFY ("STAGE_INST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_TEMPFILE" MODIFY ("STAGE_ID" NOT NULL ENABLE);
