--------------------------------------------------------
--  Constraints for Table WRHS$_IOSTAT_FUNCTION_NAME
--------------------------------------------------------

  ALTER TABLE "SYS"."WRHS$_IOSTAT_FUNCTION_NAME" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_IOSTAT_FUNCTION_NAME" MODIFY ("FUNCTION_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_IOSTAT_FUNCTION_NAME" MODIFY ("FUNCTION_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_IOSTAT_FUNCTION_NAME" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_IOSTAT_FUNCTION_NAME" MODIFY ("STAGE_INST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_IOSTAT_FUNCTION_NAME" MODIFY ("STAGE_ID" NOT NULL ENABLE);
