--------------------------------------------------------
--  Constraints for Table WRHS$_SERVICE_NAME
--------------------------------------------------------

  ALTER TABLE "SYS"."WRHS$_SERVICE_NAME" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_SERVICE_NAME" MODIFY ("SERVICE_NAME_HASH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_SERVICE_NAME" MODIFY ("SERVICE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_SERVICE_NAME" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_SERVICE_NAME" MODIFY ("STAGE_INST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_SERVICE_NAME" MODIFY ("STAGE_ID" NOT NULL ENABLE);
