--------------------------------------------------------
--  Constraints for Table WRHS$_TOPLEVELCALL_NAME
--------------------------------------------------------

  ALTER TABLE "SYS"."WRHS$_TOPLEVELCALL_NAME" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_TOPLEVELCALL_NAME" MODIFY ("TOP_LEVEL_CALL#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_TOPLEVELCALL_NAME" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_TOPLEVELCALL_NAME" MODIFY ("STAGE_INST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_TOPLEVELCALL_NAME" MODIFY ("STAGE_ID" NOT NULL ENABLE);
