--------------------------------------------------------
--  Constraints for Table WRHS$_PLAN_OPERATION_NAME
--------------------------------------------------------

  ALTER TABLE "SYS"."WRHS$_PLAN_OPERATION_NAME" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_PLAN_OPERATION_NAME" MODIFY ("OPERATION_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_PLAN_OPERATION_NAME" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_PLAN_OPERATION_NAME" MODIFY ("STAGE_INST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_PLAN_OPERATION_NAME" MODIFY ("STAGE_ID" NOT NULL ENABLE);
