--------------------------------------------------------
--  Constraints for Table WRHS$_METRIC_NAME
--------------------------------------------------------

  ALTER TABLE "SYS"."WRHS$_METRIC_NAME" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_METRIC_NAME" MODIFY ("GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_METRIC_NAME" MODIFY ("METRIC_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_METRIC_NAME" MODIFY ("METRIC_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_METRIC_NAME" MODIFY ("METRIC_UNIT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_METRIC_NAME" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_METRIC_NAME" MODIFY ("STAGE_INST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_METRIC_NAME" MODIFY ("STAGE_ID" NOT NULL ENABLE);
