--------------------------------------------------------
--  DDL for Table WRHS$_TOPLEVELCALL_NAME
--------------------------------------------------------

  CREATE TABLE "SYS"."WRHS$_TOPLEVELCALL_NAME" SHARING=METADATA 
   (	"DBID" NUMBER, 
	"TOP_LEVEL_CALL#" NUMBER, 
	"TOP_LEVEL_CALL_NAME" VARCHAR2(64 BYTE), 
	"CON_DBID" NUMBER, 
	"PER_PDB" NUMBER, 
	"STAGE_INST_ID" NUMBER, 
	"STAGE_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
  GRANT DELETE ON "SYS"."WRHS$_TOPLEVELCALL_NAME" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRHS$_TOPLEVELCALL_NAME" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRHS$_TOPLEVELCALL_NAME" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRHS$_TOPLEVELCALL_NAME" TO "SYSUMF_ROLE";
