--------------------------------------------------------
--  DDL for Table WRHS$_CELL_METRIC_DESC
--------------------------------------------------------

  CREATE TABLE "SYS"."WRHS$_CELL_METRIC_DESC" SHARING=METADATA 
   (	"DBID" NUMBER, 
	"METRIC_ID" NUMBER, 
	"METRIC_NAME" VARCHAR2(257 BYTE), 
	"METRIC_TYPE" VARCHAR2(17 BYTE), 
	"CON_DBID" NUMBER, 
	"PER_PDB" NUMBER, 
	"STAGE_INST_ID" NUMBER, 
	"STAGE_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
  GRANT DELETE ON "SYS"."WRHS$_CELL_METRIC_DESC" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRHS$_CELL_METRIC_DESC" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRHS$_CELL_METRIC_DESC" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRHS$_CELL_METRIC_DESC" TO "SYSUMF_ROLE";
