--------------------------------------------------------
--  Constraints for Table WRHS$_PARAMETER_NAME
--------------------------------------------------------

  ALTER TABLE "SYS"."WRHS$_PARAMETER_NAME" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_PARAMETER_NAME" MODIFY ("PARAMETER_HASH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_PARAMETER_NAME" MODIFY ("PARAMETER_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_PARAMETER_NAME" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_PARAMETER_NAME" MODIFY ("STAGE_INST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_PARAMETER_NAME" MODIFY ("STAGE_ID" NOT NULL ENABLE);
