--------------------------------------------------------
--  Constraints for Table WRHS$_IM_SEG_STAT_OBJ
--------------------------------------------------------

  ALTER TABLE "SYS"."WRHS$_IM_SEG_STAT_OBJ" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_IM_SEG_STAT_OBJ" MODIFY ("DATAOBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_IM_SEG_STAT_OBJ" MODIFY ("OWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_IM_SEG_STAT_OBJ" MODIFY ("STAGE_INST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_IM_SEG_STAT_OBJ" MODIFY ("STAGE_ID" NOT NULL ENABLE);
