--------------------------------------------------------
--  Constraints for Table WRHS$_IOSTAT_FILETYPE_NAME
--------------------------------------------------------

  ALTER TABLE "SYS"."WRHS$_IOSTAT_FILETYPE_NAME" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_IOSTAT_FILETYPE_NAME" MODIFY ("FILETYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_IOSTAT_FILETYPE_NAME" MODIFY ("FILETYPE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_IOSTAT_FILETYPE_NAME" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_IOSTAT_FILETYPE_NAME" MODIFY ("STAGE_INST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRHS$_IOSTAT_FILETYPE_NAME" MODIFY ("STAGE_ID" NOT NULL ENABLE);
