REM INSERTING into SYS.WRI$_ADV_DEF_EXEC_TYPES
SET DEFINE OFF;
Insert into SYS.WRI$_ADV_DEF_EXEC_TYPES (ADVISOR_ID,NAME,ID,DESCRIPTION,FLAGS) values (4,'TUNE SQL',1,'SMG-00925',null);
Insert into SYS.WRI$_ADV_DEF_EXEC_TYPES (ADVISOR_ID,NAME,ID,DESCRIPTION,FLAGS) values (8,'TEST EXECUTE',2,'SMG-00930',null);
Insert into SYS.WRI$_ADV_DEF_EXEC_TYPES (ADVISOR_ID,NAME,ID,DESCRIPTION,FLAGS) values (8,'EXPLAIN PLAN',3,'SMG-00931',null);
Insert into SYS.WRI$_ADV_DEF_EXEC_TYPES (ADVISOR_ID,NAME,ID,DESCRIPTION,FLAGS) values (9,'SQL DIAGNOSIS',4,null,null);
Insert into SYS.WRI$_ADV_DEF_EXEC_TYPES (ADVISOR_ID,NAME,ID,DESCRIPTION,FLAGS) values (8,'COMPARE PERFORMANCE',5,'SMG-00933',null);
Insert into SYS.WRI$_ADV_DEF_EXEC_TYPES (ADVISOR_ID,NAME,ID,DESCRIPTION,FLAGS) values (8,'CONVERT SQLSET',6,null,null);
Insert into SYS.WRI$_ADV_DEF_EXEC_TYPES (ADVISOR_ID,NAME,ID,DESCRIPTION,FLAGS) values (11,'SPM EVOLVE',7,'SMG-00943',null);
Insert into SYS.WRI$_ADV_DEF_EXEC_TYPES (ADVISOR_ID,NAME,ID,DESCRIPTION,FLAGS) values (12,'STATISTICS',8,'SMG-00945',null);
Insert into SYS.WRI$_ADV_DEF_EXEC_TYPES (ADVISOR_ID,NAME,ID,DESCRIPTION,FLAGS) values (8,'COMPARE PLANS',9,'SMG-00946',null);
Insert into SYS.WRI$_ADV_DEF_EXEC_TYPES (ADVISOR_ID,NAME,ID,DESCRIPTION,FLAGS) values (2,'AUTO',10,null,null);
