--------------------------------------------------------
--  DDL for Table WRI$_SQLSET_DEFINITIONS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_SQLSET_DEFINITIONS" SHARING=METADATA 
   (	"ID" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"NAME" VARCHAR2(128 BYTE), 
	"OWNER" VARCHAR2(128 BYTE), 
	"DESCRIPTION" VARCHAR2(256 BYTE), 
	"CREATED" DATE, 
	"LAST_MODIFIED" DATE, 
	"STATEMENT_COUNT" NUMBER, 
	"PROPERTY" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRI$_SQLSET_DEFINITIONS" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRI$_SQLSET_DEFINITIONS" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRI$_SQLSET_DEFINITIONS" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRI$_SQLSET_DEFINITIONS" TO "SYSUMF_ROLE";
