--------------------------------------------------------
--  DDL for Table WRI$_ADV_SQLT_BINDS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_ADV_SQLT_BINDS" SHARING=METADATA 
   (	"TASK_ID" NUMBER(38,0), 
	"OBJECT_ID" NUMBER(38,0), 
	"POSITION" NUMBER(38,0), 
	"VALUE" "SYS"."ANYDATA" 
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" 
 OPAQUE TYPE ("VALUE") STORE AS SECUREFILE LOB (
  ENABLE STORAGE IN ROW CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES ) ;
  GRANT DELETE ON "SYS"."WRI$_ADV_SQLT_BINDS" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRI$_ADV_SQLT_BINDS" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRI$_ADV_SQLT_BINDS" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRI$_ADV_SQLT_BINDS" TO "SYSUMF_ROLE";
