--------------------------------------------------------
--  DDL for Table WRI$_ADV_TASKS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_ADV_TASKS" SHARING=METADATA 
   (	"ID" NUMBER, 
	"OWNER#" NUMBER, 
	"OWNER_NAME" VARCHAR2(128 BYTE), 
	"NAME" VARCHAR2(128 BYTE), 
	"DESCRIPTION" VARCHAR2(256 BYTE), 
	"ADVISOR_ID" NUMBER, 
	"ADVISOR_NAME" VARCHAR2(128 BYTE), 
	"CTIME" DATE, 
	"MTIME" DATE, 
	"PARENT_ID" NUMBER, 
	"PARENT_REC_ID" NUMBER, 
	"PROPERTY" NUMBER, 
	"VERSION" NUMBER, 
	"LAST_EXEC_NAME" VARCHAR2(128 BYTE), 
	"EXEC_START" DATE, 
	"EXEC_END" DATE, 
	"STATUS" NUMBER, 
	"STATUS_MSG_ID" NUMBER, 
	"PCT_COMPLETION_TIME" NUMBER, 
	"PROGRESS_METRIC" NUMBER, 
	"METRIC_UNITS" VARCHAR2(64 BYTE), 
	"ACTIVITY_COUNTER" NUMBER, 
	"REC_COUNT" NUMBER, 
	"ERROR_MSG#" NUMBER, 
	"CLEANUP" NUMBER, 
	"HOW_CREATED" VARCHAR2(30 BYTE), 
	"SOURCE" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRI$_ADV_TASKS" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRI$_ADV_TASKS" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRI$_ADV_TASKS" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRI$_ADV_TASKS" TO "SYSUMF_ROLE";
