REM INSERTING into SYS.WRI$_DBU_FEATURE_METADATA
SET DEFINE OFF;
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Baseline Adaptive Thresholds',1,1,'Adaptive Thresholds have been configured.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Baseline Static Computations',1,1,'Static baseline statistics have been computed.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Client Identifier',1,1,'Application User Proxy Authentication: Client Identifier is used at this specific time.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Clusterwide Global Transactions',1,1,'Clusterwide Global Transactions is being used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Crossedition Triggers',1,1,'Crossedition triggers is being used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Character Semantics',1,1,'Character length semantics is used in Oracle Database');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Character Set',1,1,'Character set is used in Oracle Database');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Data Guard',1,2,'Data Guard, a set of services, is being used to create, maintain, manage, and monitor one or more standby databases.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Data Mining',1,2,'There exist Oracle Data Mining models in the database.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Dynamic SGA',1,2,'The Oracle SGA has been dynamically resized through an ALTER SYSTEM SET statement.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Database Migration Assistant for Unicode',2,2,'Database Migration Assistant for Unicode has been used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Editions',1,1,'Editions is being used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('EM Cloud Control',1,2,'EM Cloud Control Database Home Page has been visited at least once.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('EM Performance Page',1,2,'EM Performance Page has been visited at least once.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('SQL Monitoring and Tuning pages',1,2,'EM SQL Monitoring and Tuning pages has been visited at least once.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Flashback Database',1,1,'Flashback Database, a rewind button for the database, is enabled');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Flashback Data Archive',1,1,'Flashback Data Archive, a historical repository of changes to data contained in a table, is used ');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Internode Parallel Execution',1,1,'Internode Parallel Execution is being used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Label Security',1,2,'Oracle Label Security is being used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Oracle Database Vault',2,2,'Oracle Database Vault is being used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Deferred Segment Creation',1,2,'Deferred Segment Creation is being used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Locally Managed Tablespaces (system)',1,2,'There exists tablespaces that are locally managed in the database.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Messaging Gateway',2,1,'Messaging Gateway, that enables communication between non-Oracle messaging systems and Advanced Queuing (AQ), link configured.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Very Large Memory',1,1,'Very Large Memory is enabled.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Automatic Memory Tuning',1,2,'Automatic Memory Tuning is enabled.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Automatic SGA Tuning',1,2,'Automatic SGA Tuning is enabled.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Encrypted Tablespaces',1,1,'Encrypted Tablespaces is enabled.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('MTTR Advisor',1,1,'Mean Time to Recover Advisor is enabled.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Multiple Block Sizes',1,1,'Multiple Block Sizes are being used with this database.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('OLAP - Analytic Workspaces',1,1,'OLAP - the analytic workspaces stored in the database.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('OLAP - Cubes',2,1,'OLAP - number of cubes in the OLAP catalog that are fully mapped and accessible by the OLAP API.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Oracle Managed Files',1,1,'Database files are being managed by Oracle.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Oracle Secure Backup',1,1,'Oracle Secure Backup is used for backups to tertiary storage.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Parallel SQL DML Execution',1,1,'Parallel SQL DML Execution is being used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Oracle Multitenant',1,2,'Oracle Multitenant is being used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Oracle Pluggable Databases',1,4,'Oracle Pluggable Databases is being used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Parallel SQL Query Execution',1,1,'Parallel SQL Query Execution is being used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Partitioning (system)',1,2,'Oracle Partitioning option is being used - there is at least one partitioned object created.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Zone maps',1,2,'Zone maps');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Oracle Text',2,2,'Oracle Text is being used - there is at least one oracle text index');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('PL/SQL Native Compilation',1,2,'PL/SQL Native Compilation is being used - there is at least one natively compiled PL/SQL library unit in the database.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Quality of Service Management',1,2,'Quality of Service Management has been used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Real Application Cluster One Node',1,2,'Real Application Cluster One Node is being used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Real Application Clusters (RAC)',1,2,'Real Application Clusters (RAC) is configured.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Recovery Manager (RMAN)',1,2,'Recovery Manager (RMAN) is being used to backup the database.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('RMAN - Disk Backup',1,2,'Recovery Manager (RMAN) is being used to backup the database to disk.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('RMAN - Tape Backup',1,2,'Recovery Manager (RMAN) is being used to backup the database to tape.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Backup ZLIB Compression',1,2,'ZLIB compressed backups are being used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Backup BZIP2 Compression',1,2,'BZIP2 compressed backups are being used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Backup BASIC Compression',1,2,'BASIC compressed backups are being used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Backup LOW Compression',1,2,'LOW compressed backups are being used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Backup MEDIUM Compression',1,2,'MEDIUM compressed backups are being used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Backup HIGH Compression',1,2,'HIGH compressed backups are being used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Long-term Archival Backup',1,1,'Long-term archival backups are being used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Block Media Recovery',1,1,'Block Media Recovery is being used to repair the database.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Logfile Multiplexing',1,1,'Multiple members are used in a single log file group');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Bigfile Tablespace',1,1,'Bigfile tablespace is being used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Read Only Tablespace',1,1,'Read only tablespace is being used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Active Data Guard - Real-Time Query on Physical Standby',1,2,'Active Data Guard, a set of services, is being used to enhance Data Guard');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Online Move Datafile',1,2,'Online Move Datafile is being used to move datafiles');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Backup Rollforward',1,1,'Backup Rollforward strategy is being used to backup the database.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Data Recovery Advisor',1,1,'Data Recovery Advisor (DRA) is being used to repair the database.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Backup and Restore of plugged database',1,1,'Backup and Restore of plugged database by RMAN is used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Recover Table',1,1,'Recover Table is used to recover a table in the database.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Recover Until Snapshot',1,1,'Recover until snapshot is used to recover the database.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('TRANSPORT TABLESPACE command',1,1,'RMAN''s TRANSPORT TABLESPACE command used by the database.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('CONVERT command',1,1,'RMAN''s CONVERT command used by the database.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Cross-Platform Backups',1,1,'Cross-Platform Backup and Restore used by the database.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Duplicate Db from Active Db using BackupSet',1,1,'Duplicate from Active Database using BackupSet is used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Resource Manager',1,2,'Oracle Database Resource Manager is being used to manage database resources.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Direct NFS',1,1,'Direct NFS is being used to connect to an NFS server');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('PDB I/O Rate Limits',1,1,'PDB I/O Rate Limits are being used to limit the I/O usage by Pluggable databases.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Server Flash Cache',1,1,'Server Flash Cache is being used with this database.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Server Parameter File',1,1,'The server parameter file (SPFILE) was used to startup the database.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Shared Server',1,1,'The database is configured as Shared Server, where one server process can service multiple client programs.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Database Resident Connection Pooling (DRCP)',1,1,'Active Database Resident Connection Pool has been detected');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Spatial',2,1,'There is at least one usage of the Oracle Spatial feature usage table.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Locator',2,1,'There is at least one usage of the Oracle Locator feature usage table.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('ADDM',1,1,'ADDM has been used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Undo Advisor',1,1,'Undo Advisor has been used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('SQL Workload Manager',1,1,'SQL Workload Manager has been used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Advanced Replication',1,1,'Advanced Replication has been enabled.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('ASO native encryption and checksumming',1,1,'ASO network native encryption and checksumming is being used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Oracle Advanced Network Compression Service',1,1,'Oracle Advanced Network Compression Service Used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Thin Provisioning',1,2,'Thin Provisioning in use');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Flex ASM',1,2,'Flex ASM in use');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('ASM Filter Driver',1,2,'ASM Filter Driver in use');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('ACFS',1,2,'ACFS in use');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('ACFS Snapshot',1,2,'ACFS Snapshot in use');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('ACFS Encryption',1,2,'ACFS encryption in use');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Traditional Audit',1,2,'Traditional Audit in use.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Fine Grained Audit',1,2,'Fine Grained Audit in use.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Unified Audit',1,2,'Unified Audit in use.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Automatic Maintenance - Space Advisor',1,1,'Automatic initiation of Space Advisor');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Automatic Maintenance - SQL Tuning Advisor',1,1,'Automatic initiation of SQL Tuning Advisor');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Automatic Segment Space Management (system)',1,2,'Extents of locally managed tablespaces are managed automatically by Oracle.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Automatic SQL Execution Memory',1,1,'Sizing of work areas for all dedicated sessions (PGA) is automatic.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Automatic Storage Management',1,2,'Automatic Storage Management has been enabled');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Automatic Undo Management',1,2,'Oracle automatically manages undo data using an UNDO tablespace.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Automatic Workload Repository',1,2,'A manual Automatic Workload Repository (AWR) snapshot was taken in the last sample period.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('AWR Baseline Template',1,1,'At least one AWR Baseline Template has been created by the user');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Backup Encryption',1,2,'Encrypted backups are being used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Real-Time SQL Monitoring',1,1,'Real-Time SQL Monitoring Usage.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('SQL Tuning Set (user)',1,1,'A SQL Tuning Set has been created in the database in a user schema.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('SQL Tuning Set (system)',1,1,'A SQL Tuning Set has been created in the database in the SYS schema.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Automatic SQL Tuning Advisor',1,2,'Automatic SQL Tuning Advisor has been used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Database Replay: Workload Capture',1,2,'Database Replay: Workload was ever captured.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Database Replay: Workload Replay',1,2,'Database Replay: Workload was ever replayed.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Streams (system)',1,2,'Oracle Streams processes have been configured');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Streams (user)',1,1,'Users have configured Oracle Streams AQ');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('XStream In',1,2,'Oracle XStream Inbound servers have been configured');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('XStream Out',1,2,'Oracle XStream Outbound servers have been configured');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('XStream Streams',1,2,'Oracle Streams with XStream functionality has been configured');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('GoldenGate',1,2,'Oracle GoldenGate Capabilities are in use.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Transparent Gateway',1,1,'Heterogeneous Connectivity, access to a non-Oracle system, has been configured.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Virtual Private Database (VPD)',1,2,'Virtual Private Database (VPD) policies are being used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Workspace Manager',2,1,'There is at least one version enabled table.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('XDB',2,2,'XDB feature is being used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('JSON',1,2,'JSON feature is being used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Application Express',1,2,'Application Express feature is being used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Object',1,2,'Object feature is being used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Real Application Security',2,2,'Oracle Real Application Security is being used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Privilege Capture',1,2,'Privilege Capture is being used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Online Redefinition',2,2,'Online Redefinition is being used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('In-Memory Aggregation',1,2,'In-Memory Aggregation is being used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('In-Memory FastStart',1,2,'In-Memory FastStart is being used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('_DBFUS_TEST_SQL_1',5,1,'Test sql 1');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('_DBFUS_TEST_SQL_2',5,1,'Test sql 2');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('_DBFUS_TEST_SQL_3',5,1,'Test sql 3');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('_DBFUS_TEST_SQL_4',6,1,'Test sql 4');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('_DBFUS_TEST_SQL_5',6,1,'Test sql 5');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('_DBFUS_TEST_SQL_6',6,1,'Test sql 6');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('_DBFUS_TEST_SQL_7',5,4,'Test sql 7');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('_DBFUS_TEST_SQL_8',5,1,'Test sql 8 - Test error case');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('_DBFUS_TEST_SQL_9',6,1,'Test sql 9 - Test error case for install');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('_DBFUS_TEST_SQL_10',6,1,'Test sql 10 - Test infrastructure');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('_DBFUS_TEST_PROC_1',5,2,'Test feature 1');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('_DBFUS_TEST_PROC_2',5,2,'Test feature 2');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('_DBFUS_TEST_PROC_3',5,2,'Test feature 3 - Bad procedure name');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('_DBFUS_TEST_PROC_4',5,2,'Test feature 4');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('_DBFUS_TEST_PROC_5',5,2,'Test feature 5');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Transparent Sensitive Data Protection',1,2,'Transparent Sensitive Data Protection (TSDP)');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Segment Maintenance Online Compress',1,2,'Segment Maintenance Online Compress');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('EM Express',2,2,'EM Database Express has been used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('BA Owner',1,2,'BA OWNER');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('INSTANT RESTORE command',1,1,'RMAN''s INSTANT RESTORE command used by the database.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Container Usage',1,1,'CONTAINER FILES used by backup appliance.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Client Result Cache',1,1,'Client Result Cache has been enabled');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Oracle Call Interface (OCI)',1,1,'Oracle Call Interface (OCI) used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('SQL*Plus',1,1,'SQL*Plus used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('JDBC Thin',1,1,'JDBC Thin used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('ODP.Net, Unmanaged Driver',1,1,'ODP.Net, Unmanaged Driver used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('PERL DBD::Oracle',1,1,'PERL DBD::Oracle used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('PHP OCI8',1,1,'PHP OCI8 used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('cx_Oracle',1,1,'cx_Oracle used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('ROracle',1,1,'ROracle used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('OCCI',1,1,'OCCI used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Pro*Cobol',1,1,'Pro*Cobol used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Pro*Fortran',1,1,'Pro*Fortran used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('ODA Infrastructure',1,1,'Oracle Database Appliance infrastructure in use');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Instance Caging',1,1,'Instance Caging is being used to limit the CPU usage by the database instance.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('SQL Access Advisor',1,1,'SQL Access Advisor has been used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('SQL Tuning Advisor',1,1,'SQL Tuning Advisor has been used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Automatic Maintenance - Optimizer Statistics Gathering',1,1,'Automatic initiation of Optimizer Statistics Collection');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Automatic Segment Space Management (user)',1,1,'Extents of locally managed user tablespaces are managed automatically by Oracle.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('AWR Baseline',1,1,'At least one AWR Baseline has been created by the user');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('AWR Report',1,1,'At least one Workload Repository Report has been created by the user');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Change-Aware Incremental Backup',1,1,'Track blocks that have changed in the database.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('CSSCAN',2,1,'Oracle Database has been scanned at least once for character set:CSSCAN has been run at least once.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Editioning Views',1,1,'Editioning views is being used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('File Mapping',1,1,'File Mapping, the mechanism that shows a complete mapping of a file to logical volumes and physical devices, is being used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Locally Managed Tablespaces (user)',1,1,'There exists user tablespaces that are locally managed in the database.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Parallel SQL DDL Execution',1,1,'Parallel SQL DDL Execution is being used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Partitioning (user)',1,2,'Oracle Partitioning option is being used - there is at least one user partitioned object created.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Recovery Area',1,1,'The recovery area is configured.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Multi Section Backup',1,1,'Multi section backups are being used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Restore Point',1,1,'Restore Points are being used as targets for Flashback');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Transportable Tablespace',1,1,'Transportable tablespace is being used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Deferred Open Read Only',1,1,'Deferred open read only feature is enabled');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Extensibility',1,2,'Extensibility feature is being used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('SQL Plan Management',1,1,'SQL Plan Management has been used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Adaptive Plans',1,2,'Adaptive Plans have been used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Automatic Reoptimization',1,2,'Automatic Reoptimization have been used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('SQL Plan Directive',1,2,'Sql plan directive has been used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Concurrent Statistics Gathering',1,2,'Concurrent Statistics Gathering has been used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('DBMS_STATS Incremental Maintenance',1,2,'DBMS_STATS Incremental Maintenance has been used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Rules Manager',2,2,'Rules Manager and Expression Filter');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Oracle Utility Datapump (Export)',1,2,'Oracle Utility Datapump (Export) has been used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Oracle Utility Datapump (Import)',1,2,'Oracle Utility Datapump (Import) has been used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Oracle Utility SQL Loader (Direct Path Load)',1,1,'Oracle Utility SQL Loader (Direct Path Load) has been used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Oracle Utility Metadata API',1,2,'Oracle Utility (Metadata API) has been used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Oracle Utility External Table',1,4,'Oracle Utility External Table has been used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Oracle Utility External Table (ORACLE_DATAPUMP)',1,2,'Oracle Utility External Table (ORACLE_DATAPUMP) has been used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Oracle Utility External Table (ORACLE_LOADER)',1,2,'Oracle Utility External Table (ORACLE_LOADER) has been used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Oracle Utility External Table (ORACLE_BIGSQL)',1,2,'Oracle Utility External Table (ORACLE_BIGSQL) has been used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Result Cache',1,1,'The Result Cache feature has been used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Transparent Data Encryption',1,1,'Transparent Database Encryption is being used. There is atleast one column or tablespace that is encrypted.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Data Redaction',1,2,'Data redaction is being used. There is at least one policy that is defined.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Oracle Multimedia',2,2,'Oracle Multimedia has been used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Oracle Multimedia DICOM',2,2,'Oracle Multimedia DICOM (Digital Imaging and COmmunications in Medicine) has been used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('SecureFile Deduplication (system)',1,2,'SecureFile Deduplication is being used by system users');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('In-Memory Column Store',1,2,'In-Memory Column Store is being used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Heat Map',1,2,'Heat Map is used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Pillar Storage with EHCC',1,2,'EHCC used on tablespaces stored on Oracles Pillar Axiom Storage');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Job Scheduler',1,2,'Job Scheduler feature is being used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('DBFS Content',1,2,'Oracle Database FileSystem Content feature is being used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Global Data Services',1,1,'Database contains global services.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Sharding Catalog',1,1,'Database is a Sharding Catalog.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Materialized Views (User)',1,2,'User Materialized Views exist in the database');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Change Data Capture',1,4,'Change Data Capture exit in the database');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Services',1,2,'Oracle Services.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Semantics/RDF',2,1,'A semantic network has been created indicating usage of the RDF Semantic Graph feature of Oracle Spatial and Graph.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('SecureFiles (user)',1,2,'SecureFiles is being used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('SecureFiles (system)',1,2,'SecureFiles is being used by system users');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('SecureFile Encryption (user)',1,2,'SecureFile Encryption is being used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('SecureFile Encryption (system)',1,2,'SecureFile Encryption is being used by system users');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('SecureFile Compression (user)',1,2,'SecureFile Compression is being used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('SecureFile Compression (system)',1,2,'SecureFile Compression is being used by system users');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('SecureFile Deduplication (user)',1,2,'SecureFile Deduplication is being used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Segment Advisor (user)',1,2,'Segment Advisor has been used. There is at least one user task executed.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('In-Memory Expressions',1,2,'In-Memory Expressions or In-Memory Virtual Columns are being used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('In-Memory Join Groups',1,2,'In-Memory Join Groups are being used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('In-Memory ADO Policies',2,2,'In-Memory ADO Policies are being used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('HeapCompression',1,2,'Heap Compression is being used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Advanced Index Compression',1,2,'Advanced Index Compression is used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Index Organized Tables',1,2,'Index Organized Tables are being used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('In-Memory Distribute For Service (User Defined)',1,2,'In-Memory Distribute For Service (User Defined) is being used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Hybrid Columnar Compression',1,2,'Hybrid Columnar Compression is used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Hybrid Columnar Compression Conventional Load',1,2,'Hybrid Columnar Compression with Conventional Load is used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Hybrid Columnar Compression Row Level Locking',1,2,'Hybrid Columnar Compression Row Level Locking is used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Information Lifecycle Management',2,2,'Information Lifecycle Management is used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('ZFS Storage',1,2,'Tablespaces stored on Oracles Sun ZFS Storage');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Pillar Storage',1,2,'Tablespaces stored on Oracles Pillar Axiom Storage');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Sun ZFS with EHCC',1,2,'EHCC used on tablespaces stored on Oracles Sun ZFS Storage');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Cloud DB with EHCC',1,2,'EHCC used for Cloud Database');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Segment Shrink',1,1,'Segment Shrink has been used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Gateways',1,2,'Gateways feature is being used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Oracle Java Virtual Machine (user)',2,2,'OJVM has been used by at least one non-system user');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Oracle Java Virtual Machine (system)',2,2,'OJVM default system users');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Oracle In-Database Hadoop',2,2,'In-Database Hadoop for running MapReduce in java');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('DBFS SFS',1,2,'Oracle Database FileSystem SecureFile Store feature is being used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('DBFS HS',1,2,'Oracle Database FileSystem Hierarchical Store feature is being used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Exadata',1,2,'Exadata is being used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('GDS Catalog',1,1,'Database is a GDS catalog database.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Shard Database',1,2,'Database is a Shard.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Tune MView',1,1,'Tune MView has been used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('SQL Repair Advisor',1,1,'SQL Repair Advisor has been used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('SPM Evolve Advisor',1,1,'SPM Evolve Advisor has been used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Statistics Advisor',1,1,'Statistics Advisor has been used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('SQL Profile',1,1,'SQL profiles have been used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('LOB',1,1,'Persistent LOBs are being used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Scrollable Cursors',1,1,'Scrollable Cursors has been used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Application Continuity',1,1,'Application Continuity has been enabled');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('JDBC OCI',1,1,'JDBC OCI used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('ODBC',1,1,'ODBC used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('ODP.Net, Managed Driver',1,1,'ODP.Net, Managed Driver used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Ruby-oci8',1,1,'Ruby-oci8 used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('node-oraceldb',1,1,'node-oraceldb used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Pro*C',1,1,'Pro*C used');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('SQL Performance Analyzer',1,1,'SQL Performance Analyzer has been used.');
Insert into SYS.WRI$_DBU_FEATURE_METADATA (NAME,INST_CHK_METHOD,USG_DET_METHOD,DESCRIPTION) values ('Compression Advisor',1,1,'Compression Advisor has been used.');
