--------------------------------------------------------
--  Constraints for Table WRI$_ADV_SQLT_STATISTICS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRI$_ADV_SQLT_STATISTICS" MODIFY ("TASK_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_SQLT_STATISTICS" MODIFY ("OBJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_SQLT_STATISTICS" ADD CONSTRAINT "WRI$_ADV_SQLT_STATISTICS_PK" PRIMARY KEY ("TASK_ID", "OBJECT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
