--------------------------------------------------------
--  DDL for Table WRI$_SQLSET_MASK
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_SQLSET_MASK" SHARING=METADATA 
   (	"STMT_ID" NUMBER, 
	"PLAN_HASH_VALUE" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PRIORITY" NUMBER, 
	"OTHER" CLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" 
 LOB ("OTHER") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
