--------------------------------------------------------
--  DDL for Table WRI$_ADV_SQLT_PLAN_STATS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_ADV_SQLT_PLAN_STATS" SHARING=METADATA 
   (	"PLAN_ID" NUMBER, 
	"PARSE_TIME" NUMBER, 
	"EXEC_TIME" NUMBER, 
	"CPU_TIME" NUMBER, 
	"USER_IO_TIME" NUMBER, 
	"BUFFER_GETS" NUMBER, 
	"DISK_READS" NUMBER, 
	"DIRECT_WRITES" NUMBER, 
	"ROWS_PROCESSED" NUMBER, 
	"FETCHES" NUMBER, 
	"EXECUTIONS" NUMBER, 
	"END_OF_FETCH_COUNT" NUMBER, 
	"OPTIMIZER_COST" NUMBER, 
	"OTHER" CLOB, 
	"IO_INTERCONNECT_BYTES" NUMBER, 
	"SPARE_N1" NUMBER, 
	"SPARE_N2" NUMBER, 
	"SPARE_N3" NUMBER, 
	"SPARE_N4" NUMBER, 
	"SPARE_N5" NUMBER, 
	"SPARE_C1" VARCHAR2(4000 BYTE), 
	"SPARE_C2" VARCHAR2(4000 BYTE), 
	"SPARE_C3" CLOB, 
	"TESTEXEC_TOTAL_EXECS" NUMBER, 
	"FLAGS" NUMBER, 
	"SPARE_N6" NUMBER, 
	"SPARE_N7" NUMBER, 
	"SPARE_N8" NUMBER, 
	"SPARE_N9" NUMBER, 
	"SPARE_N10" NUMBER, 
	"CACHED_GETS" NUMBER, 
	"DIRECT_GETS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" 
 LOB ("OTHER") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("SPARE_C3") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
  GRANT DELETE ON "SYS"."WRI$_ADV_SQLT_PLAN_STATS" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRI$_ADV_SQLT_PLAN_STATS" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRI$_ADV_SQLT_PLAN_STATS" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRI$_ADV_SQLT_PLAN_STATS" TO "SYSUMF_ROLE";
