--------------------------------------------------------
--  Constraints for Table WRI$_ADV_JOURNAL
--------------------------------------------------------

  ALTER TABLE "SYS"."WRI$_ADV_JOURNAL" MODIFY ("TASK_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_JOURNAL" MODIFY ("SEQ_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_JOURNAL" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_JOURNAL" MODIFY ("MSG_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_JOURNAL" ADD CONSTRAINT "WRI$_ADV_JOURNAL" PRIMARY KEY ("TASK_ID", "SEQ_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
