REM INSERTING into SYS.WRI$_SQLSET_DEFINITIONS
SET DEFINE OFF;
Insert into SYS.WRI$_SQLSET_DEFINITIONS (ID,CON_DBID,NAME,OWNER,DESCRIPTION,CREATED,LAST_MODIFIED,STATEMENT_COUNT,PROPERTY) values (1,1413006993,'SYS_AUTO_STS','SYS','System auto SQL Tuning Set',to_date('30-MAY-19','DD-MON-RR'),to_date('30-MAY-19','DD-MON-RR'),0,1);
