--------------------------------------------------------
--  DDL for Table WRI$_SEGADV_OBJLIST
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_SEGADV_OBJLIST" SHARING=METADATA 
   (	"AUTO_TASKID" NUMBER, 
	"TS_ID" NUMBER, 
	"OBJN" NUMBER, 
	"OBJD" NUMBER, 
	"STATUS" VARCHAR2(40 BYTE), 
	"TASK_ID" NUMBER, 
	"REASON" VARCHAR2(40 BYTE), 
	"REASON_VALUE" NUMBER, 
	"CREATION_TIME" TIMESTAMP (6), 
	"PROC_TASKID" NUMBER, 
	"END_TIME" TIMESTAMP (6), 
	"SEGMENT_OWNER" VARCHAR2(128 BYTE), 
	"SEGMENT_NAME" VARCHAR2(128 BYTE), 
	"PARTITION_NAME" VARCHAR2(128 BYTE), 
	"SEGMENT_TYPE" VARCHAR2(18 BYTE), 
	"TABLESPACE_NAME" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRI$_SEGADV_OBJLIST" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRI$_SEGADV_OBJLIST" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRI$_SEGADV_OBJLIST" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRI$_SEGADV_OBJLIST" TO "SYSUMF_ROLE";
