--------------------------------------------------------
--  DDL for Table WRI$_ADV_INST_FDG
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_ADV_INST_FDG" SHARING=METADATA 
   (	"TASK_ID" NUMBER, 
	"FINDING_ID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"EXEC_NAME" VARCHAR2(128 BYTE), 
	"PERC_IMPACT" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRI$_ADV_INST_FDG" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRI$_ADV_INST_FDG" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRI$_ADV_INST_FDG" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRI$_ADV_INST_FDG" TO "SYSUMF_ROLE";
