--------------------------------------------------------
--  DDL for Table WRI$_ADV_ACTIONS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_ADV_ACTIONS" SHARING=METADATA 
   (	"ID" NUMBER, 
	"TASK_ID" NUMBER, 
	"EXEC_NAME" VARCHAR2(128 BYTE), 
	"OBJ_ID" NUMBER, 
	"COMMAND" NUMBER, 
	"FLAGS" NUMBER, 
	"ATTR1" VARCHAR2(4000 BYTE), 
	"ATTR2" VARCHAR2(4000 BYTE), 
	"ATTR3" VARCHAR2(4000 BYTE), 
	"ATTR4" VARCHAR2(4000 BYTE), 
	"ATTR5" CLOB, 
	"ATTR6" CLOB, 
	"NUM_ATTR1" NUMBER, 
	"NUM_ATTR2" NUMBER, 
	"NUM_ATTR3" NUMBER, 
	"NUM_ATTR4" NUMBER, 
	"NUM_ATTR5" NUMBER, 
	"MSG_ID" NUMBER, 
	"FILTERED" CHAR(1 BYTE), 
	"RES_STATUS#" NUMBER, 
	"RES_LAST_MODIFIED" TIMESTAMP (3), 
	"RES_MSG_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" 
 LOB ("ATTR5") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("ATTR6") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
  GRANT DELETE ON "SYS"."WRI$_ADV_ACTIONS" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRI$_ADV_ACTIONS" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRI$_ADV_ACTIONS" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRI$_ADV_ACTIONS" TO "SYSUMF_ROLE";
