--------------------------------------------------------
--  DDL for Table WRI$_ADV_SQLW_STMTS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_ADV_SQLW_STMTS" SHARING=METADATA 
   (	"WORKLOAD_ID" NUMBER, 
	"SQL_ID" NUMBER, 
	"HASH_VALUE" NUMBER, 
	"OPTIMIZER_COST" NUMBER, 
	"USERNAME" VARCHAR2(128 BYTE), 
	"MODULE" VARCHAR2(64 BYTE), 
	"ACTION" VARCHAR2(64 BYTE), 
	"ELAPSED_TIME" NUMBER, 
	"CPU_TIME" NUMBER, 
	"BUFFER_GETS" NUMBER, 
	"DISK_READS" NUMBER, 
	"ROWS_PROCESSED" NUMBER, 
	"EXECUTIONS" NUMBER, 
	"PRIORITY" NUMBER, 
	"LAST_EXECUTION_DATE" DATE, 
	"COMMAND_TYPE" NUMBER, 
	"STAT_PERIOD" NUMBER, 
	"SQL_TEXT" CLOB, 
	"VALID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" 
 LOB ("SQL_TEXT") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
