--------------------------------------------------------
--  Constraints for Table WRI$_DBU_FEATURE_USAGE
--------------------------------------------------------

  ALTER TABLE "SYS"."WRI$_DBU_FEATURE_USAGE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_DBU_FEATURE_USAGE" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_DBU_FEATURE_USAGE" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_DBU_FEATURE_USAGE" MODIFY ("DETECTED_USAGES" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_DBU_FEATURE_USAGE" ADD CONSTRAINT "WRI$_DBU_FEATURE_USAGE_PK" PRIMARY KEY ("NAME", "DBID", "VERSION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE;
