--------------------------------------------------------
--  Constraints for Table WRI$_ADV_DIRECTIVE_INSTANCES
--------------------------------------------------------

  ALTER TABLE "SYS"."WRI$_ADV_DIRECTIVE_INSTANCES" MODIFY ("DIR_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_DIRECTIVE_INSTANCES" MODIFY ("INST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_DIRECTIVE_INSTANCES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_DIRECTIVE_INSTANCES" MODIFY ("DATA" NOT NULL ENABLE);
