--------------------------------------------------------
--  DDL for Table WRI$_OPTSTAT_SYNOPSIS_HEAD$
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_OPTSTAT_SYNOPSIS_HEAD$" SHARING=METADATA 
   (	"BO#" NUMBER, 
	"GROUP#" NUMBER, 
	"INTCOL#" NUMBER, 
	"SYNOPSIS#" NUMBER, 
	"SPLIT" NUMBER, 
	"ANALYZETIME" DATE, 
	"SPARE1" NUMBER, 
	"SPARE2" BLOB
   ) PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 LOB ("SPARE2") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT))  ENABLE ROW MOVEMENT ;
