--------------------------------------------------------
--  DDL for Table WRI$_SQLTEXT_REFCOUNT
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_SQLTEXT_REFCOUNT" SHARING=METADATA 
   (	"DBID" NUMBER, 
	"SQL_ID" VARCHAR2(13 BYTE), 
	"REF_COUNT" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PER_PDB" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRI$_SQLTEXT_REFCOUNT" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRI$_SQLTEXT_REFCOUNT" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRI$_SQLTEXT_REFCOUNT" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRI$_SQLTEXT_REFCOUNT" TO "SYSUMF_ROLE";
