--------------------------------------------------------
--  Constraints for Table WRI$_SEGADV_CNTRLTAB
--------------------------------------------------------

  ALTER TABLE "SYS"."WRI$_SEGADV_CNTRLTAB" ADD CONSTRAINT "WRI$_SEGADV_CNTRLTAB_PK" PRIMARY KEY ("AUTO_TASKID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE;
