--------------------------------------------------------
--  DDL for Table WRI$_HEATMAP_TOPN_DEP1
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "SYS"."WRI$_HEATMAP_TOPN_DEP1" SHARING=METADATA 
   (	"OBJECT_NAME" VARCHAR2(128 BYTE), 
	"OBJECT_OWNER" VARCHAR2(128 BYTE), 
	"OBJECT_TYPE" VARCHAR2(128 BYTE), 
	"SEGMENT_COUNT" NUMBER, 
	"OBJECT_SIZE" NUMBER
   ) ON COMMIT PRESERVE ROWS ;
  GRANT DELETE ON "SYS"."WRI$_HEATMAP_TOPN_DEP1" TO PUBLIC;
  GRANT INSERT ON "SYS"."WRI$_HEATMAP_TOPN_DEP1" TO PUBLIC;
  GRANT SELECT ON "SYS"."WRI$_HEATMAP_TOPN_DEP1" TO PUBLIC;
