--------------------------------------------------------
--  DDL for Table WRI$_DBU_FEATURE_USAGE
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_DBU_FEATURE_USAGE" SHARING=METADATA 
   (	"NAME" VARCHAR2(128 BYTE), 
	"DBID" NUMBER, 
	"VERSION" VARCHAR2(17 BYTE), 
	"FIRST_USAGE_DATE" DATE, 
	"LAST_USAGE_DATE" DATE, 
	"DETECTED_USAGES" NUMBER, 
	"AUX_COUNT" NUMBER, 
	"FEATURE_INFO" CLOB, 
	"ERROR_COUNT" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 LOB ("FEATURE_INFO") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
