--------------------------------------------------------
--  DDL for Table WRI$_ADV_ADDM_INST
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_ADV_ADDM_INST" SHARING=METADATA 
   (	"TASK_ID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"INSTANCE_NAME" VARCHAR2(16 BYTE), 
	"HOST_NAME" VARCHAR2(64 BYTE), 
	"STATUS" VARCHAR2(10 BYTE), 
	"DATABASE_TIME" NUMBER, 
	"ACTIVE_SESSIONS" NUMBER, 
	"PERC_ACTIVE_SESS" NUMBER, 
	"PERC_FLUSH_TIME" NUMBER, 
	"METER_LEVEL" VARCHAR2(6 BYTE), 
	"LOCAL_TASK_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
