--------------------------------------------------------
--  DDL for Table WRI$_SCH_CONTROL
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_SCH_CONTROL" SHARING=METADATA 
   (	"SCHEDULE_ID" NUMBER, 
	"SCHEDULE_MODE" NUMBER, 
	"START_CALIBRATE" NUMBER, 
	"LAST_VOTE" NUMBER, 
	"NUM_VOTES" NUMBER, 
	"SYNCED_TIME" NUMBER, 
	"STATUS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
