--------------------------------------------------------
--  Constraints for Table WRI$_SQLSET_STATEMENTS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRI$_SQLSET_STATEMENTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_SQLSET_STATEMENTS" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_SQLSET_STATEMENTS" MODIFY ("SQLSET_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_SQLSET_STATEMENTS" MODIFY ("SQL_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_SQLSET_STATEMENTS" MODIFY ("FORCE_MATCHING_SIGNATURE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_SQLSET_STATEMENTS" ADD CONSTRAINT "WRI$_SQLSET_STATEMENTS_PK" PRIMARY KEY ("ID", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
