--------------------------------------------------------
--  DDL for Table WRI$_ADV_RATIONALE
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_ADV_RATIONALE" SHARING=METADATA 
   (	"ID" NUMBER, 
	"TASK_ID" NUMBER, 
	"EXEC_NAME" VARCHAR2(128 BYTE), 
	"TYPE" VARCHAR2(30 BYTE), 
	"REC_ID" NUMBER, 
	"IMPACT_MSG_ID" NUMBER, 
	"IMPACT_VAL" NUMBER, 
	"OBJ_ID" NUMBER, 
	"MSG_ID" NUMBER, 
	"ATTR1" VARCHAR2(4000 BYTE), 
	"ATTR2" VARCHAR2(4000 BYTE), 
	"ATTR3" VARCHAR2(4000 BYTE), 
	"ATTR4" VARCHAR2(4000 BYTE), 
	"ATTR5" CLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 LOB ("ATTR5") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  GRANT DELETE ON "SYS"."WRI$_ADV_RATIONALE" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRI$_ADV_RATIONALE" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRI$_ADV_RATIONALE" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRI$_ADV_RATIONALE" TO "SYSUMF_ROLE";
