--------------------------------------------------------
--  Constraints for Table WRI$_SQLSET_PLAN_LINES
--------------------------------------------------------

  ALTER TABLE "SYS"."WRI$_SQLSET_PLAN_LINES" MODIFY ("STMT_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_SQLSET_PLAN_LINES" MODIFY ("PLAN_HASH_VALUE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_SQLSET_PLAN_LINES" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_SQLSET_PLAN_LINES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_SQLSET_PLAN_LINES" ADD CONSTRAINT "WRI$_SQLSET_PLAN_LINES_PK" PRIMARY KEY ("STMT_ID", "PLAN_HASH_VALUE", "ID", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
