--------------------------------------------------------
--  DDL for Table WRI$_ADV_OBJECTS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_ADV_OBJECTS" SHARING=METADATA 
   (	"ID" NUMBER, 
	"TYPE" NUMBER, 
	"TASK_ID" NUMBER, 
	"EXEC_NAME" VARCHAR2(128 BYTE), 
	"ATTR1" VARCHAR2(4000 BYTE), 
	"ATTR2" VARCHAR2(4000 BYTE), 
	"ATTR3" VARCHAR2(4000 BYTE), 
	"ATTR4" CLOB, 
	"ATTR5" VARCHAR2(4000 BYTE), 
	"ATTR6" RAW(2000), 
	"ATTR7" NUMBER, 
	"ATTR8" NUMBER, 
	"ATTR9" NUMBER, 
	"ATTR10" NUMBER, 
	"ATTR11" NUMBER, 
	"ATTR12" NUMBER, 
	"ATTR13" NUMBER, 
	"ATTR14" NUMBER, 
	"ATTR15" NUMBER, 
	"ATTR16" VARCHAR2(4000 BYTE), 
	"ATTR17" VARCHAR2(4000 BYTE), 
	"ATTR18" VARCHAR2(4000 BYTE), 
	"ATTR19" VARCHAR2(4000 BYTE), 
	"ATTR20" VARCHAR2(4000 BYTE), 
	"OTHER" CLOB, 
	"SPARE_N1" NUMBER, 
	"SPARE_N2" NUMBER, 
	"SPARE_N3" NUMBER, 
	"SPARE_N4" NUMBER, 
	"SPARE_C1" VARCHAR2(4000 BYTE), 
	"SPARE_C2" VARCHAR2(4000 BYTE), 
	"SPARE_C3" VARCHAR2(4000 BYTE), 
	"SPARE_C4" VARCHAR2(4000 BYTE), 
	"SQL_ID_VC" VARCHAR2(13 BYTE) GENERATED ALWAYS AS (DECODE("TYPE",7,SUBSTR("ATTR1",1,13),NULL)) VIRTUAL 
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 LOB ("ATTR4") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("OTHER") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  GRANT DELETE ON "SYS"."WRI$_ADV_OBJECTS" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRI$_ADV_OBJECTS" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRI$_ADV_OBJECTS" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRI$_ADV_OBJECTS" TO "SYSUMF_ROLE";
