--------------------------------------------------------
--  DDL for Table WRI$_SQLSET_STATISTICS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_SQLSET_STATISTICS" SHARING=METADATA 
   (	"STMT_ID" NUMBER, 
	"PLAN_HASH_VALUE" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"ELAPSED_TIME" NUMBER, 
	"ELAPSED_TIME_DELTA" NUMBER, 
	"CPU_TIME" NUMBER, 
	"CPU_TIME_DELTA" NUMBER, 
	"BUFFER_GETS" NUMBER, 
	"BUFFER_GETS_DELTA" NUMBER, 
	"DISK_READS" NUMBER, 
	"DISK_READS_DELTA" NUMBER, 
	"DIRECT_WRITES" NUMBER, 
	"DIRECT_WRITES_DELTA" NUMBER, 
	"ROWS_PROCESSED" NUMBER, 
	"ROWS_PROCESSED_DELTA" NUMBER, 
	"FETCHES" NUMBER, 
	"FETCHES_DELTA" NUMBER, 
	"EXECUTIONS" NUMBER, 
	"EXECUTIONS_DELTA" NUMBER, 
	"END_OF_FETCH_COUNT" NUMBER, 
	"OPTIMIZER_COST" NUMBER, 
	"FIRST_LOAD_TIME" VARCHAR2(19 BYTE), 
	"FIRST_LOAD_TIME_DELTA" VARCHAR2(19 BYTE), 
	"STAT_PERIOD" NUMBER, 
	"ACTIVE_STAT_PERIOD" NUMBER, 
	"LAST_EXEC_START_TIME" VARCHAR2(19 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
