--------------------------------------------------------
--  Constraints for Table WRI$_SCH_CONTROL
--------------------------------------------------------

  ALTER TABLE "SYS"."WRI$_SCH_CONTROL" MODIFY ("SCHEDULE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_SCH_CONTROL" MODIFY ("SCHEDULE_MODE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_SCH_CONTROL" ADD CONSTRAINT "WRM$_SCH_CONTROL_PK" PRIMARY KEY ("SCHEDULE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE;
