--------------------------------------------------------
--  Constraints for Table WRI$_ADV_SQLT_BINDS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRI$_ADV_SQLT_BINDS" MODIFY ("TASK_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_SQLT_BINDS" MODIFY ("OBJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_SQLT_BINDS" MODIFY ("POSITION" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_SQLT_BINDS" ADD CONSTRAINT "WRI$_ADV_SQLT_BINDS_PK" PRIMARY KEY ("TASK_ID", "OBJECT_ID", "POSITION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
