--------------------------------------------------------
--  DDL for Table WRI$_ADV_PARAMETERS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_ADV_PARAMETERS" SHARING=METADATA 
   (	"TASK_ID" NUMBER, 
	"NAME" VARCHAR2(128 BYTE), 
	"VALUE" VARCHAR2(4000 BYTE), 
	"DATATYPE" NUMBER, 
	"FLAGS" NUMBER, 
	"DESCRIPTION" VARCHAR2(9 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRI$_ADV_PARAMETERS" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRI$_ADV_PARAMETERS" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRI$_ADV_PARAMETERS" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRI$_ADV_PARAMETERS" TO "SYSUMF_ROLE";
