--------------------------------------------------------
--  DDL for Table WRI$_DBU_CPU_USAGE_SAMPLE
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_DBU_CPU_USAGE_SAMPLE" SHARING=METADATA 
   (	"DBID" NUMBER, 
	"VERSION" VARCHAR2(17 BYTE), 
	"LAST_SAMPLE_DATE" DATE, 
	"LAST_SAMPLE_DATE_NUM" NUMBER, 
	"LAST_SAMPLE_PERIOD" NUMBER, 
	"TOTAL_SAMPLES" NUMBER, 
	"SAMPLE_INTERVAL" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
