--------------------------------------------------------
--  Constraints for Table WRI$_ALERT_THRESHOLD
--------------------------------------------------------

  ALTER TABLE "SYS"."WRI$_ALERT_THRESHOLD" ADD CONSTRAINT "WRI$_ALERT_THRESHOLD_PK" UNIQUE ("T_OBJECT_TYPE", "T_OBJECT_NAME", "T_METRICS_ID", "T_INSTANCE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE;
