--------------------------------------------------------
--  Constraints for Table WRI$_SQLSET_PLANS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRI$_SQLSET_PLANS" MODIFY ("STMT_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_SQLSET_PLANS" MODIFY ("PLAN_HASH_VALUE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_SQLSET_PLANS" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_SQLSET_PLANS" ADD CONSTRAINT "WRI$_SQLSET_PLANS_PK" PRIMARY KEY ("STMT_ID", "PLAN_HASH_VALUE", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
