--------------------------------------------------------
--  Constraints for Table WRI$_DBU_USAGE_SAMPLE
--------------------------------------------------------

  ALTER TABLE "SYS"."WRI$_DBU_USAGE_SAMPLE" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_DBU_USAGE_SAMPLE" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_DBU_USAGE_SAMPLE" MODIFY ("TOTAL_SAMPLES" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_DBU_USAGE_SAMPLE" ADD CONSTRAINT "WRI$_DBU_USAGE_SAMPLE_PK" PRIMARY KEY ("DBID", "VERSION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE;
