--------------------------------------------------------
--  DDL for Table WRI$_ADV_USAGE
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_ADV_USAGE" SHARING=METADATA 
   (	"ADVISOR_ID" NUMBER, 
	"LAST_EXEC_TIME" DATE, 
	"NUM_EXECS" NUMBER, 
	"NUM_DB_REPORTS" NUMBER DEFAULT 0, 
	"FIRST_REPORT_TIME" DATE, 
	"LAST_REPORT_TIME" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRI$_ADV_USAGE" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRI$_ADV_USAGE" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRI$_ADV_USAGE" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRI$_ADV_USAGE" TO "SYSUMF_ROLE";
