--------------------------------------------------------
--  DDL for Table WRI$_SEGADV_CNTRLTAB
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_SEGADV_CNTRLTAB" SHARING=METADATA 
   (	"AUTO_TASKID" NUMBER, 
	"SNAPID" NUMBER, 
	"SEGMENTS_SELECTED" NUMBER, 
	"SEGMENTS_PROCESSED" NUMBER, 
	"TABLESPACE_SELECTED" NUMBER, 
	"TABLESPACE_PROCESSED" NUMBER, 
	"RECOMMENDATIONS_COUNT" NUMBER, 
	"START_TIME" TIMESTAMP (6), 
	"END_TIME" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRI$_SEGADV_CNTRLTAB" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRI$_SEGADV_CNTRLTAB" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRI$_SEGADV_CNTRLTAB" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRI$_SEGADV_CNTRLTAB" TO "SYSUMF_ROLE";
