--------------------------------------------------------
--  DDL for Table WRI$_ADV_FINDINGS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_ADV_FINDINGS" SHARING=METADATA 
   (	"ID" NUMBER, 
	"TASK_ID" NUMBER, 
	"EXEC_NAME" VARCHAR2(128 BYTE), 
	"TYPE" NUMBER, 
	"PARENT" NUMBER, 
	"OBJ_ID" NUMBER, 
	"IMPACT_MSG_ID" NUMBER, 
	"IMPACT_VAL" NUMBER, 
	"MSG_ID" NUMBER, 
	"MORE_INFO_ID" NUMBER, 
	"NAME_MSG_CODE" VARCHAR2(9 BYTE), 
	"FILTERED" CHAR(1 BYTE), 
	"FLAGS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRI$_ADV_FINDINGS" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRI$_ADV_FINDINGS" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRI$_ADV_FINDINGS" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRI$_ADV_FINDINGS" TO "SYSUMF_ROLE";
