REM INSERTING into SYS.WRI$_ADV_DEFINITIONS
SET DEFINE OFF;
Insert into SYS.WRI$_ADV_DEFINITIONS (ID,NAME,PROPERTY,TYPE) values (0,'Default Advisor',0,SYS.WRI$_ADV_ABSTRACT_T(0));
Insert into SYS.WRI$_ADV_DEFINITIONS (ID,NAME,PROPERTY,TYPE) values (1,'ADDM',1,SYS.WRI$_ADV_HDM_T(1));
Insert into SYS.WRI$_ADV_DEFINITIONS (ID,NAME,PROPERTY,TYPE) values (2,'SQL Access Advisor',303,SYS.WRI$_ADV_SQLACCESS_ADV(2));
Insert into SYS.WRI$_ADV_DEFINITIONS (ID,NAME,PROPERTY,TYPE) values (3,'Undo Advisor',1,SYS.WRI$_ADV_UNDO_ADV(3));
Insert into SYS.WRI$_ADV_DEFINITIONS (ID,NAME,PROPERTY,TYPE) values (4,'SQL Tuning Advisor',935,SYS.WRI$_ADV_SQLTUNE(4));
Insert into SYS.WRI$_ADV_DEFINITIONS (ID,NAME,PROPERTY,TYPE) values (5,'Segment Advisor',67,SYS.WRI$_ADV_OBJSPACE_TREND_T(5));
Insert into SYS.WRI$_ADV_DEFINITIONS (ID,NAME,PROPERTY,TYPE) values (6,'SQL Workload Manager',0,SYS.WRI$_ADV_WORKLOAD(6));
Insert into SYS.WRI$_ADV_DEFINITIONS (ID,NAME,PROPERTY,TYPE) values (7,'Tune MView',31,SYS.WRI$_ADV_TUNEMVIEW_ADV(7));
Insert into SYS.WRI$_ADV_DEFINITIONS (ID,NAME,PROPERTY,TYPE) values (8,'SQL Performance Analyzer',935,SYS.WRI$_ADV_SQLPI(8));
Insert into SYS.WRI$_ADV_DEFINITIONS (ID,NAME,PROPERTY,TYPE) values (9,'SQL Repair Advisor',679,SYS.WRI$_ADV_SQLTUNE(9));
Insert into SYS.WRI$_ADV_DEFINITIONS (ID,NAME,PROPERTY,TYPE) values (10,'Compression Advisor',3,SYS.WRI$_ADV_COMPRESSION_T(10));
Insert into SYS.WRI$_ADV_DEFINITIONS (ID,NAME,PROPERTY,TYPE) values (11,'SPM Evolve Advisor',935,SYS.WRI$_ADV_SPM_EVOLVE(11));
Insert into SYS.WRI$_ADV_DEFINITIONS (ID,NAME,PROPERTY,TYPE) values (12,'Statistics Advisor',935,SYS.WRI$_ADV_STATS(12));
