--------------------------------------------------------
--  DDL for Table WRI$_ADV_MESSAGE_GROUPS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_ADV_MESSAGE_GROUPS" SHARING=METADATA 
   (	"TASK_ID" NUMBER, 
	"EXEC_NAME" VARCHAR2(128 BYTE), 
	"ID" NUMBER, 
	"SEQ" NUMBER, 
	"MESSAGE#" NUMBER, 
	"FAC" VARCHAR2(3 BYTE), 
	"HDR" NUMBER, 
	"LM" NUMBER, 
	"NL" NUMBER, 
	"P1" VARCHAR2(4000 BYTE), 
	"P2" VARCHAR2(4000 BYTE), 
	"P3" VARCHAR2(4000 BYTE), 
	"P4" VARCHAR2(4000 BYTE), 
	"P5" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRI$_ADV_MESSAGE_GROUPS" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRI$_ADV_MESSAGE_GROUPS" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRI$_ADV_MESSAGE_GROUPS" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRI$_ADV_MESSAGE_GROUPS" TO "SYSUMF_ROLE";
