--------------------------------------------------------
--  DDL for Table WRI$_HEATMAP_TOP_OBJECTS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_HEATMAP_TOP_OBJECTS" SHARING=METADATA 
   (	"TASK_TIME" DATE, 
	"OBJECT_OWNER" VARCHAR2(128 BYTE), 
	"OBJECT_NAME" VARCHAR2(128 BYTE), 
	"OBJECT_TYPE" VARCHAR2(18 BYTE), 
	"TABLESPACE_NAME" VARCHAR2(30 BYTE), 
	"SEGMENT_COUNT" NUMBER, 
	"OBJECT_SIZE" NUMBER, 
	"MIN_WRITETIME" DATE, 
	"MAX_WRITETIME" DATE, 
	"AVG_WRITETIME" DATE, 
	"MIN_READTIME" DATE, 
	"MAX_READTIME" DATE, 
	"AVG_READTIME" DATE, 
	"MIN_FTSTIME" DATE, 
	"MAX_FTSTIME" DATE, 
	"AVG_FTSTIME" DATE, 
	"MIN_LOOKUPTIME" DATE, 
	"MAX_LOOKUPTIME" DATE, 
	"AVG_LOOKUPTIME" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
