--------------------------------------------------------
--  Constraints for Table WRI$_ADV_EXEC_PARAMETERS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRI$_ADV_EXEC_PARAMETERS" MODIFY ("TASK_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_EXEC_PARAMETERS" MODIFY ("EXEC_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_EXEC_PARAMETERS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_EXEC_PARAMETERS" MODIFY ("VALUE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_EXEC_PARAMETERS" ADD CONSTRAINT "WRI$_ADV_EXEC_PARAMETERS_PK" PRIMARY KEY ("TASK_ID", "EXEC_NAME", "NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE;
