--------------------------------------------------------
--  DDL for Table WRI$_ADV_DEFINITIONS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_ADV_DEFINITIONS" SHARING=METADATA 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(128 BYTE), 
	"PROPERTY" NUMBER, 
	"TYPE" "SYS"."WRI$_ADV_ABSTRACT_T" 
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
