--------------------------------------------------------
--  DDL for Table WRI$_ADV_SQLW_TABVOL
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_ADV_SQLW_TABVOL" SHARING=METADATA 
   (	"WORKLOAD_ID" NUMBER, 
	"OWNER_NAME" VARCHAR2(128 BYTE), 
	"TABLE_OWNER#" NUMBER, 
	"TABLE_NAME" VARCHAR2(128 BYTE), 
	"TABLE#" NUMBER, 
	"UPD_FREQ" NUMBER, 
	"INS_FREQ" NUMBER, 
	"DEL_FREQ" NUMBER, 
	"DIR_FREQ" NUMBER, 
	"UPD_ROWS" NUMBER, 
	"INS_ROWS" NUMBER, 
	"DEL_ROWS" NUMBER, 
	"DIR_ROWS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
