--------------------------------------------------------
--  Constraints for Table WRI$_ADV_DEFINITIONS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRI$_ADV_DEFINITIONS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_DEFINITIONS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_DEFINITIONS" MODIFY ("PROPERTY" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_DEFINITIONS" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_DEFINITIONS" ADD CONSTRAINT "WRI$_ADV_DEFINITIONS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE;
