--------------------------------------------------------
--  Constraints for Table WRI$_OPTSTAT_HISTGRM_HISTORY
--------------------------------------------------------

  ALTER TABLE "SYS"."WRI$_OPTSTAT_HISTGRM_HISTORY" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_OPTSTAT_HISTGRM_HISTORY" MODIFY ("INTCOL#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_OPTSTAT_HISTGRM_HISTORY" MODIFY ("BUCKET" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_OPTSTAT_HISTGRM_HISTORY" MODIFY ("ENDPOINT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_OPTSTAT_HISTGRM_HISTORY" MODIFY ("EP_REPEAT_COUNT" NOT NULL ENABLE);
