--------------------------------------------------------
--  Constraints for Table WRI$_ADV_ADDM_TODO
--------------------------------------------------------

  ALTER TABLE "SYS"."WRI$_ADV_ADDM_TODO" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_ADDM_TODO" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_ADDM_TODO" MODIFY ("IS_RAC_COORD" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_ADDM_TODO" MODIFY ("END_SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_ADDM_TODO" MODIFY ("SCHEDULE_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_ADDM_TODO" ADD PRIMARY KEY ("INSTANCE_NUMBER", "DBID", "END_SNAP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
