--------------------------------------------------------
--  DDL for Table WRI$_SQLSET_REFERENCES
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_SQLSET_REFERENCES" SHARING=METADATA 
   (	"ID" NUMBER, 
	"SQLSET_ID" NUMBER, 
	"OWNER" VARCHAR2(128 BYTE), 
	"CREATED" DATE, 
	"DESCRIPTION" VARCHAR2(256 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRI$_SQLSET_REFERENCES" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRI$_SQLSET_REFERENCES" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRI$_SQLSET_REFERENCES" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRI$_SQLSET_REFERENCES" TO "SYSUMF_ROLE";
