--------------------------------------------------------
--  DDL for Table WRI$_INDEX_USAGE
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_INDEX_USAGE" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"TOTAL_EXEC_COUNT" NUMBER, 
	"TOTAL_ACCESS_COUNT" NUMBER, 
	"TOTAL_ROWS_RETURNED" NUMBER, 
	"BUCKET_0_ACCESS_COUNT" NUMBER, 
	"BUCKET_1_ACCESS_COUNT" NUMBER, 
	"BUCKET_2_10_ACCESS_COUNT" NUMBER, 
	"BUCKET_2_10_ROWS_RETURNED" NUMBER, 
	"BUCKET_11_100_ACCESS_COUNT" NUMBER, 
	"BUCKET_11_100_ROWS_RETURNED" NUMBER, 
	"BUCKET_101_1000_ACCESS_COUNT" NUMBER, 
	"BUCKET_101_1000_ROWS_RETURNED" NUMBER, 
	"BUCKET_1000_PLUS_ACCESS_COUNT" NUMBER, 
	"BUCKET_1000_PLUS_ROWS_RETURNED" NUMBER, 
	"LAST_USED" DATE, 
	"SPARE1" VARCHAR2(64 BYTE), 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" NUMBER, 
	"SPARE5" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
