--------------------------------------------------------
--  DDL for Table WRI$_SCH_VOTES
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_SCH_VOTES" SHARING=METADATA 
   (	"SCHEDULE_ID" NUMBER, 
	"VECTOR_INDEX" NUMBER, 
	"VECTOR" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
