--------------------------------------------------------
--  DDL for Table WRI$_ADV_ASA_RECO_DATA
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "SYS"."WRI$_ADV_ASA_RECO_DATA" SHARING=METADATA 
   (	"TASK_ID" NUMBER, 
	"CTIME" TIMESTAMP (6), 
	"SEGOWNER" VARCHAR2(128 BYTE), 
	"SEGNAME" VARCHAR2(128 BYTE), 
	"SEGTYPE" VARCHAR2(128 BYTE), 
	"PARTNAME" VARCHAR2(128 BYTE), 
	"TSNAME" VARCHAR2(128 BYTE), 
	"BENEFIT_TYPE" NUMBER, 
	"USP" NUMBER, 
	"ALSP" NUMBER, 
	"REC" NUMBER, 
	"CHCT" NUMBER, 
	"CMD_ID" NUMBER, 
	"C1" VARCHAR2(1000 BYTE), 
	"C2" VARCHAR2(1000 BYTE), 
	"C3" VARCHAR2(1000 BYTE)
   ) ON COMMIT PRESERVE ROWS ;
  GRANT DELETE ON "SYS"."WRI$_ADV_ASA_RECO_DATA" TO PUBLIC;
  GRANT INSERT ON "SYS"."WRI$_ADV_ASA_RECO_DATA" TO PUBLIC;
  GRANT SELECT ON "SYS"."WRI$_ADV_ASA_RECO_DATA" TO PUBLIC;
