--------------------------------------------------------
--  DDL for Table WRI$_REPT_FORMATS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_REPT_FORMATS" SHARING=METADATA 
   (	"ID" NUMBER, 
	"REPORT_ID" NUMBER, 
	"NAME" VARCHAR2(128 BYTE), 
	"DESCRIPTION" VARCHAR2(256 BYTE), 
	"TYPE" NUMBER, 
	"CONTENT_TYPE" NUMBER, 
	"STYLESHEET_ID" NUMBER, 
	"TEXT_LINESIZE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
