--------------------------------------------------------
--  DDL for Table WRI$_ADV_JOURNAL
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_ADV_JOURNAL" SHARING=METADATA 
   (	"TASK_ID" NUMBER, 
	"EXEC_NAME" VARCHAR2(128 BYTE), 
	"SEQ_ID" NUMBER, 
	"TYPE" NUMBER, 
	"MSG_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRI$_ADV_JOURNAL" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRI$_ADV_JOURNAL" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRI$_ADV_JOURNAL" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRI$_ADV_JOURNAL" TO "SYSUMF_ROLE";
