--------------------------------------------------------
--  DDL for Table WRI$_OPTSTAT_OPR
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_OPTSTAT_OPR" SHARING=METADATA 
   (	"ID" NUMBER, 
	"OPERATION" VARCHAR2(64 BYTE), 
	"TARGET" VARCHAR2(512 BYTE), 
	"START_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"END_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"STATUS" NUMBER, 
	"JOB_NAME" VARCHAR2(32 BYTE), 
	"SESSION_ID" NUMBER, 
	"NOTES" VARCHAR2(4000 BYTE), 
	"FLAGS" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" VARCHAR2(1000 BYTE), 
	"SPARE5" VARCHAR2(1000 BYTE), 
	"SPARE6" TIMESTAMP (6) WITH TIME ZONE
   ) PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE ROW MOVEMENT ;
  GRANT DELETE ON "SYS"."WRI$_OPTSTAT_OPR" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRI$_OPTSTAT_OPR" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRI$_OPTSTAT_OPR" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRI$_OPTSTAT_OPR" TO "SYSUMF_ROLE";
