--------------------------------------------------------
--  DDL for Table WRI$_ADV_SQLT_PLAN_HASH
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_ADV_SQLT_PLAN_HASH" SHARING=METADATA 
   (	"TASK_ID" NUMBER(38,0), 
	"EXEC_NAME" VARCHAR2(128 BYTE), 
	"OBJECT_ID" NUMBER(38,0), 
	"SQL_ID" VARCHAR2(13 BYTE), 
	"ATTRIBUTE" NUMBER, 
	"PLAN_HASH" NUMBER, 
	"PLAN_ID" NUMBER, 
	"SPARE_N1" NUMBER, 
	"SPARE_N2" NUMBER, 
	"SPARE_N3" NUMBER, 
	"SPARE_N4" NUMBER, 
	"SPARE_N5" NUMBER, 
	"SPARE_C1" VARCHAR2(4000 BYTE), 
	"SPARE_C2" VARCHAR2(4000 BYTE), 
	"CON_DBID" NUMBER DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRI$_ADV_SQLT_PLAN_HASH" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRI$_ADV_SQLT_PLAN_HASH" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRI$_ADV_SQLT_PLAN_HASH" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRI$_ADV_SQLT_PLAN_HASH" TO "SYSUMF_ROLE";
