--------------------------------------------------------
--  DDL for Table WRI$_OPTSTAT_SYNOPSIS$
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_OPTSTAT_SYNOPSIS$" SHARING=METADATA 
   (	"BO#" NUMBER, 
	"GROUP#" NUMBER, 
	"INTCOL#" NUMBER, 
	"HASHVALUE" NUMBER
   ) PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
  PARTITION BY LIST ("BO#") 
  SUBPARTITION BY HASH ("GROUP#") 
  SUBPARTITIONS 32
 (PARTITION "P0"  VALUES (0) 
PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 ( SUBPARTITION "SYS_SUBP121" 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 NOCOMPRESS , 
  SUBPARTITION "SYS_SUBP122" 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 NOCOMPRESS , 
  SUBPARTITION "SYS_SUBP123" 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 NOCOMPRESS , 
  SUBPARTITION "SYS_SUBP124" 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 NOCOMPRESS , 
  SUBPARTITION "SYS_SUBP125" 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 NOCOMPRESS , 
  SUBPARTITION "SYS_SUBP126" 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 NOCOMPRESS , 
  SUBPARTITION "SYS_SUBP127" 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 NOCOMPRESS , 
  SUBPARTITION "SYS_SUBP128" 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 NOCOMPRESS , 
  SUBPARTITION "SYS_SUBP129" 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 NOCOMPRESS , 
  SUBPARTITION "SYS_SUBP130" 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 NOCOMPRESS , 
  SUBPARTITION "SYS_SUBP131" 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 NOCOMPRESS , 
  SUBPARTITION "SYS_SUBP132" 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 NOCOMPRESS , 
  SUBPARTITION "SYS_SUBP133" 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 NOCOMPRESS , 
  SUBPARTITION "SYS_SUBP134" 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 NOCOMPRESS , 
  SUBPARTITION "SYS_SUBP135" 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 NOCOMPRESS , 
  SUBPARTITION "SYS_SUBP136" 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 NOCOMPRESS , 
  SUBPARTITION "SYS_SUBP137" 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 NOCOMPRESS , 
  SUBPARTITION "SYS_SUBP138" 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 NOCOMPRESS , 
  SUBPARTITION "SYS_SUBP139" 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 NOCOMPRESS , 
  SUBPARTITION "SYS_SUBP140" 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 NOCOMPRESS , 
  SUBPARTITION "SYS_SUBP141" 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 NOCOMPRESS , 
  SUBPARTITION "SYS_SUBP142" 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 NOCOMPRESS , 
  SUBPARTITION "SYS_SUBP143" 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 NOCOMPRESS , 
  SUBPARTITION "SYS_SUBP144" 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 NOCOMPRESS , 
  SUBPARTITION "SYS_SUBP145" 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 NOCOMPRESS , 
  SUBPARTITION "SYS_SUBP146" 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 NOCOMPRESS , 
  SUBPARTITION "SYS_SUBP147" 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 NOCOMPRESS , 
  SUBPARTITION "SYS_SUBP148" 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 NOCOMPRESS , 
  SUBPARTITION "SYS_SUBP149" 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 NOCOMPRESS , 
  SUBPARTITION "SYS_SUBP150" 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 NOCOMPRESS , 
  SUBPARTITION "SYS_SUBP151" 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 NOCOMPRESS , 
  SUBPARTITION "SYS_SUBP152" 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 NOCOMPRESS ) )  ENABLE ROW MOVEMENT ;
