--------------------------------------------------------
--  DDL for Table WRI$_ALERT_OUTSTANDING
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_ALERT_OUTSTANDING" SHARING=METADATA 
   (	"REASON_ID" NUMBER, 
	"OBJECT_ID" NUMBER, 
	"SUBOBJECT_ID" NUMBER, 
	"INTERNAL_INSTANCE_NUMBER" NUMBER, 
	"OWNER" VARCHAR2(128 BYTE), 
	"OBJECT_NAME" VARCHAR2(513 BYTE), 
	"SUBOBJECT_NAME" VARCHAR2(128 BYTE), 
	"SEQUENCE_ID" NUMBER, 
	"REASON_ARGUMENT_1" VARCHAR2(581 BYTE), 
	"REASON_ARGUMENT_2" VARCHAR2(581 BYTE), 
	"REASON_ARGUMENT_3" VARCHAR2(581 BYTE), 
	"REASON_ARGUMENT_4" VARCHAR2(581 BYTE), 
	"REASON_ARGUMENT_5" VARCHAR2(581 BYTE), 
	"TIME_SUGGESTED" TIMESTAMP (6) WITH TIME ZONE, 
	"CREATION_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"ACTION_ARGUMENT_1" VARCHAR2(128 BYTE), 
	"ACTION_ARGUMENT_2" VARCHAR2(128 BYTE), 
	"ACTION_ARGUMENT_3" VARCHAR2(128 BYTE), 
	"ACTION_ARGUMENT_4" VARCHAR2(128 BYTE), 
	"ACTION_ARGUMENT_5" VARCHAR2(128 BYTE), 
	"MESSAGE_LEVEL" NUMBER, 
	"HOSTING_CLIENT_ID" VARCHAR2(64 BYTE), 
	"PROCESS_ID" VARCHAR2(128 BYTE), 
	"HOST_ID" VARCHAR2(256 BYTE), 
	"HOST_NW_ADDR" VARCHAR2(256 BYTE), 
	"INSTANCE_NAME" VARCHAR2(16 BYTE), 
	"INSTANCE_NUMBER" NUMBER, 
	"USER_ID" VARCHAR2(128 BYTE), 
	"EXECUTION_CONTEXT_ID" VARCHAR2(128 BYTE), 
	"ERROR_INSTANCE_ID" VARCHAR2(142 BYTE), 
	"CONTEXT" RAW(128), 
	"METRIC_VALUE" NUMBER, 
	"STATE_TRANSITION_NUMBER" NUMBER, 
	"PDB_NAME" VARCHAR2(128 BYTE), 
	"CON_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
