REM INSERTING into SYS.WRI$_SQLMON_USAGE
SET DEFINE OFF;
Insert into SYS.WRI$_SQLMON_USAGE (NUM_DB_REPORTS,NUM_EM_REPORTS,FIRST_DB_REPORT_TIME,LAST_DB_REPORT_TIME,FIRST_EM_REPORT_TIME,LAST_EM_REPORT_TIME,SPARE1,SPARE2,SPARE3,SPARE4,SPARE5,SPARE6,SPARE7,SPARE8) values (0,0,null,null,null,null,null,null,null,null,null,null,null,null);
