--------------------------------------------------------
--  DDL for Index WRI$_ALERT_THRESHOLD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."WRI$_ALERT_THRESHOLD_PK" ON "SYS"."WRI$_ALERT_THRESHOLD" ("T_OBJECT_TYPE", "T_OBJECT_NAME", "T_METRICS_ID", "T_INSTANCE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
