--------------------------------------------------------
--  Constraints for Table WRI$_SQLTEXT_REFCOUNT
--------------------------------------------------------

  ALTER TABLE "SYS"."WRI$_SQLTEXT_REFCOUNT" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_SQLTEXT_REFCOUNT" MODIFY ("SQL_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_SQLTEXT_REFCOUNT" MODIFY ("REF_COUNT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_SQLTEXT_REFCOUNT" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_SQLTEXT_REFCOUNT" ADD CONSTRAINT "WRI$_SQLTEXT_REFCOUNT_PK" PRIMARY KEY ("DBID", "SQL_ID", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
