--------------------------------------------------------
--  Constraints for Table WRI$_ADV_USAGE
--------------------------------------------------------

  ALTER TABLE "SYS"."WRI$_ADV_USAGE" MODIFY ("ADVISOR_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_USAGE" MODIFY ("LAST_EXEC_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_USAGE" MODIFY ("NUM_EXECS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_USAGE" MODIFY ("NUM_DB_REPORTS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_USAGE" ADD CONSTRAINT "WRI$_ADV_USAGE_PK" PRIMARY KEY ("ADVISOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE;
