--------------------------------------------------------
--  Constraints for Table WRI$_ADV_ACTIONS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRI$_ADV_ACTIONS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_ACTIONS" MODIFY ("TASK_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_ACTIONS" MODIFY ("COMMAND" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_ACTIONS" ADD CONSTRAINT "WRI$_ADV_ACTIONS_PK" PRIMARY KEY ("TASK_ID", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
