--------------------------------------------------------
--  DDL for Table WRI$_SQLSET_PLANS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_SQLSET_PLANS" SHARING=METADATA 
   (	"STMT_ID" NUMBER, 
	"PLAN_HASH_VALUE" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"PARSING_SCHEMA_NAME" VARCHAR2(128 BYTE), 
	"BIND_DATA" RAW(2000), 
	"OPTIMIZER_ENV" RAW(2000), 
	"PLAN_TIMESTAMP" DATE, 
	"BINDS_CAPTURED" CHAR(1 BYTE), 
	"FLAGS" NUMBER, 
	"MASKED_BINDS_FLAG" RAW(1000)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
