--------------------------------------------------------
--  DDL for Table WRI$_SQLSET_BINDS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_SQLSET_BINDS" SHARING=METADATA 
   (	"STMT_ID" NUMBER, 
	"PLAN_HASH_VALUE" NUMBER, 
	"POSITION" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"VALUE" "SYS"."ANYDATA" 
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" 
 OPAQUE TYPE ("VALUE") STORE AS SECUREFILE LOB (
  ENABLE STORAGE IN ROW CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES ) ;
