--------------------------------------------------------
--  Constraints for Table WRI$_ADV_ADDM_INST
--------------------------------------------------------

  ALTER TABLE "SYS"."WRI$_ADV_ADDM_INST" MODIFY ("TASK_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_ADDM_INST" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_ADDM_INST" ADD PRIMARY KEY ("TASK_ID", "INSTANCE_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
