--------------------------------------------------------
--  DDL for Table WRI$_OPTSTAT_OPR_TASKS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_OPTSTAT_OPR_TASKS" SHARING=METADATA 
   (	"OP_ID" NUMBER, 
	"JOB_NAME" VARCHAR2(50 BYTE), 
	"STATUS" NUMBER, 
	"START_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"END_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"TARGET" VARCHAR2(512 BYTE), 
	"TARGET_OBJN" NUMBER, 
	"TARGET_TYPE" NUMBER, 
	"TARGET_SIZE" NUMBER, 
	"ESTIMATED_COST" NUMBER, 
	"BATCHING_COEFF" NUMBER, 
	"ACTIONS" NUMBER, 
	"PRIORITY" NUMBER, 
	"FLAGS" NUMBER, 
	"NOTES" VARCHAR2(4000 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" VARCHAR2(1000 BYTE), 
	"SPARE5" VARCHAR2(1000 BYTE), 
	"SPARE6" TIMESTAMP (6) WITH TIME ZONE
   ) PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE ROW MOVEMENT ;
