REM INSERTING into SYS.WRI$_HEATMAP_TOP_TABLESPACES
SET DEFINE OFF;
Insert into SYS.WRI$_HEATMAP_TOP_TABLESPACES (TASK_TIME,TABLESPACE_NAME,SEGMENT_COUNT,ALLOCATED_BYTES,MIN_WRITETIME,MAX_WRITETIME,AVG_WRITETIME,MIN_READTIME,MAX_READTIME,AVG_READTIME,MIN_FTSTIME,MAX_FTSTIME,AVG_FTSTIME,MIN_LOOKUPTIME,MAX_LOOKUPTIME,AVG_LOOKUPTIME) values (to_date('27-MAR-25','DD-MON-RR'),'USERS',29,3670016,null,null,null,null,null,null,null,null,null,null,null,null);
