REM INSERTING into SYS.WRI$_SCH_VOTES
SET DEFINE OFF;
Insert into SYS.WRI$_SCH_VOTES (SCHEDULE_ID,VECTOR_INDEX,VECTOR) values (0,0,0);
Insert into SYS.WRI$_SCH_VOTES (SCHEDULE_ID,VECTOR_INDEX,VECTOR) values (0,1,0);
Insert into SYS.WRI$_SCH_VOTES (SCHEDULE_ID,VECTOR_INDEX,VECTOR) values (0,2,0);
Insert into SYS.WRI$_SCH_VOTES (SCHEDULE_ID,VECTOR_INDEX,VECTOR) values (0,3,0);
Insert into SYS.WRI$_SCH_VOTES (SCHEDULE_ID,VECTOR_INDEX,VECTOR) values (0,4,0);
Insert into SYS.WRI$_SCH_VOTES (SCHEDULE_ID,VECTOR_INDEX,VECTOR) values (0,5,0);
Insert into SYS.WRI$_SCH_VOTES (SCHEDULE_ID,VECTOR_INDEX,VECTOR) values (0,6,0);
