--------------------------------------------------------
--  Constraints for Table WRI$_SQLSET_REFERENCES
--------------------------------------------------------

  ALTER TABLE "SYS"."WRI$_SQLSET_REFERENCES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_SQLSET_REFERENCES" MODIFY ("SQLSET_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_SQLSET_REFERENCES" ADD CONSTRAINT "WRI$_SQLSET_REFERENCES_PK" PRIMARY KEY ("ID", "SQLSET_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
