--------------------------------------------------------
--  DDL for Table WRI$_ALERT_THRESHOLD_LOG
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_ALERT_THRESHOLD_LOG" SHARING=METADATA 
   (	"SEQUENCE_ID" NUMBER, 
	"OBJECT_TYPE" NUMBER, 
	"OBJECT_NAME" VARCHAR2(513 BYTE), 
	"OBJECT_ID" NUMBER, 
	"OPCODE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
