--------------------------------------------------------
--  Constraints for Table WRI$_ADV_INST_FDG
--------------------------------------------------------

  ALTER TABLE "SYS"."WRI$_ADV_INST_FDG" MODIFY ("TASK_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_INST_FDG" MODIFY ("FINDING_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_INST_FDG" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_INST_FDG" ADD PRIMARY KEY ("TASK_ID", "FINDING_ID", "INSTANCE_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
