--------------------------------------------------------
--  Constraints for Table WRI$_ADV_EXECUTIONS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRI$_ADV_EXECUTIONS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_EXECUTIONS" MODIFY ("TASK_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_EXECUTIONS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_EXECUTIONS" MODIFY ("ADVISOR_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_EXECUTIONS" MODIFY ("EXEC_MTIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_EXECUTIONS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_EXECUTIONS" ADD CONSTRAINT "WRI$_ADV_EXECS_PK" PRIMARY KEY ("TASK_ID", "NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE;
