--------------------------------------------------------
--  DDL for Table WRI$_OPTSTAT_HISTHEAD_HISTORY
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_OPTSTAT_HISTHEAD_HISTORY" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"INTCOL#" NUMBER, 
	"SAVTIME" TIMESTAMP (6) WITH TIME ZONE, 
	"FLAGS" NUMBER, 
	"NULL_CNT" NUMBER, 
	"MINIMUM" NUMBER, 
	"MAXIMUM" NUMBER, 
	"DISTCNT" NUMBER, 
	"DENSITY" NUMBER, 
	"LOWVAL" RAW(1000), 
	"HIVAL" RAW(1000), 
	"AVGCLN" NUMBER, 
	"SAMPLE_DISTCNT" NUMBER, 
	"SAMPLE_SIZE" NUMBER, 
	"TIMESTAMP#" DATE, 
	"EXPRESSION" CLOB, 
	"COLNAME" VARCHAR2(128 BYTE), 
	"SAVTIME_DATE" DATE GENERATED ALWAYS AS (TRUNC("SAVTIME")) VIRTUAL , 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" VARCHAR2(1000 BYTE), 
	"SPARE5" VARCHAR2(1000 BYTE), 
	"SPARE6" TIMESTAMP (6) WITH TIME ZONE, 
	"MINIMUM_ENC" RAW(1000), 
	"MAXIMUM_ENC" RAW(1000)
   ) PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 LOB ("EXPRESSION") STORE AS SECUREFILE (
  ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
  PARTITION BY RANGE ("SAVTIME_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) 
 (PARTITION "P_PERMANENT"  VALUES LESS THAN (TO_DATE(' 1900-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 LOB ("EXPRESSION") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) )  ENABLE ROW MOVEMENT ;
