--------------------------------------------------------
--  Constraints for Table WRI$_SQLSET_WORKSPACE
--------------------------------------------------------

  ALTER TABLE "SYS"."WRI$_SQLSET_WORKSPACE" MODIFY ("WORKSPACE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_SQLSET_WORKSPACE" MODIFY ("SQLSET_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_SQLSET_WORKSPACE" MODIFY ("SQL_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_SQLSET_WORKSPACE" MODIFY ("PLAN_HASH_VALUE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_SQLSET_WORKSPACE" ADD CONSTRAINT "WRI$_SQLSET_WORKSPACE_PK" PRIMARY KEY ("WORKSPACE_NAME", "SQLSET_NAME", "SQL_ID", "PLAN_HASH_VALUE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
