--------------------------------------------------------
--  Constraints for Table WRI$_SQLSET_WORKSPACE_PLANS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRI$_SQLSET_WORKSPACE_PLANS" MODIFY ("PLAN_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_SQLSET_WORKSPACE_PLANS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_SQLSET_WORKSPACE_PLANS" ADD CONSTRAINT "WRI$_SQLSET_WORKSPACE_PLANS_PK" PRIMARY KEY ("PLAN_ID", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
