--------------------------------------------------------
--  DDL for Table WRI$_ADV_SQLT_RTN_PLAN
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_ADV_SQLT_RTN_PLAN" SHARING=METADATA 
   (	"TASK_ID" NUMBER(38,0), 
	"EXEC_NAME" VARCHAR2(128 BYTE), 
	"RTN_ID" NUMBER(38,0), 
	"OBJECT_ID" NUMBER(38,0), 
	"PLAN_ATTR" NUMBER(1,0), 
	"OPERATION_ID" NUMBER(38,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRI$_ADV_SQLT_RTN_PLAN" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRI$_ADV_SQLT_RTN_PLAN" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRI$_ADV_SQLT_RTN_PLAN" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRI$_ADV_SQLT_RTN_PLAN" TO "SYSUMF_ROLE";
