--------------------------------------------------------
--  Constraints for Table WRI$_ADV_DIRECTIVE_DEFS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRI$_ADV_DIRECTIVE_DEFS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_DIRECTIVE_DEFS" MODIFY ("ADVISOR_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_DIRECTIVE_DEFS" MODIFY ("DOMAIN" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_DIRECTIVE_DEFS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_DIRECTIVE_DEFS" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_DIRECTIVE_DEFS" MODIFY ("TYPE#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_DIRECTIVE_DEFS" MODIFY ("FLAGS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_DIRECTIVE_DEFS" MODIFY ("METADATA_ID" NOT NULL ENABLE);
