REM INSERTING into SYS.WRI$_ADV_USAGE
SET DEFINE OFF;
Insert into SYS.WRI$_ADV_USAGE (ADVISOR_ID,LAST_EXEC_TIME,NUM_EXECS,NUM_DB_REPORTS,FIRST_REPORT_TIME,LAST_REPORT_TIME) values (0,to_date('30-MAY-19','DD-MON-RR'),0,0,null,null);
Insert into SYS.WRI$_ADV_USAGE (ADVISOR_ID,LAST_EXEC_TIME,NUM_EXECS,NUM_DB_REPORTS,FIRST_REPORT_TIME,LAST_REPORT_TIME) values (1,to_date('30-MAY-19','DD-MON-RR'),0,0,null,null);
Insert into SYS.WRI$_ADV_USAGE (ADVISOR_ID,LAST_EXEC_TIME,NUM_EXECS,NUM_DB_REPORTS,FIRST_REPORT_TIME,LAST_REPORT_TIME) values (2,to_date('30-MAY-19','DD-MON-RR'),0,0,null,null);
Insert into SYS.WRI$_ADV_USAGE (ADVISOR_ID,LAST_EXEC_TIME,NUM_EXECS,NUM_DB_REPORTS,FIRST_REPORT_TIME,LAST_REPORT_TIME) values (3,to_date('30-MAY-19','DD-MON-RR'),0,0,null,null);
Insert into SYS.WRI$_ADV_USAGE (ADVISOR_ID,LAST_EXEC_TIME,NUM_EXECS,NUM_DB_REPORTS,FIRST_REPORT_TIME,LAST_REPORT_TIME) values (4,to_date('30-MAY-19','DD-MON-RR'),0,0,null,null);
Insert into SYS.WRI$_ADV_USAGE (ADVISOR_ID,LAST_EXEC_TIME,NUM_EXECS,NUM_DB_REPORTS,FIRST_REPORT_TIME,LAST_REPORT_TIME) values (5,to_date('30-MAY-19','DD-MON-RR'),0,0,null,null);
Insert into SYS.WRI$_ADV_USAGE (ADVISOR_ID,LAST_EXEC_TIME,NUM_EXECS,NUM_DB_REPORTS,FIRST_REPORT_TIME,LAST_REPORT_TIME) values (6,to_date('30-MAY-19','DD-MON-RR'),0,0,null,null);
Insert into SYS.WRI$_ADV_USAGE (ADVISOR_ID,LAST_EXEC_TIME,NUM_EXECS,NUM_DB_REPORTS,FIRST_REPORT_TIME,LAST_REPORT_TIME) values (7,to_date('30-MAY-19','DD-MON-RR'),0,0,null,null);
Insert into SYS.WRI$_ADV_USAGE (ADVISOR_ID,LAST_EXEC_TIME,NUM_EXECS,NUM_DB_REPORTS,FIRST_REPORT_TIME,LAST_REPORT_TIME) values (8,to_date('30-MAY-19','DD-MON-RR'),0,0,null,null);
Insert into SYS.WRI$_ADV_USAGE (ADVISOR_ID,LAST_EXEC_TIME,NUM_EXECS,NUM_DB_REPORTS,FIRST_REPORT_TIME,LAST_REPORT_TIME) values (9,to_date('30-MAY-19','DD-MON-RR'),0,0,null,null);
Insert into SYS.WRI$_ADV_USAGE (ADVISOR_ID,LAST_EXEC_TIME,NUM_EXECS,NUM_DB_REPORTS,FIRST_REPORT_TIME,LAST_REPORT_TIME) values (10,to_date('30-MAY-19','DD-MON-RR'),0,0,null,null);
Insert into SYS.WRI$_ADV_USAGE (ADVISOR_ID,LAST_EXEC_TIME,NUM_EXECS,NUM_DB_REPORTS,FIRST_REPORT_TIME,LAST_REPORT_TIME) values (11,to_date('30-MAY-19','DD-MON-RR'),0,0,null,null);
Insert into SYS.WRI$_ADV_USAGE (ADVISOR_ID,LAST_EXEC_TIME,NUM_EXECS,NUM_DB_REPORTS,FIRST_REPORT_TIME,LAST_REPORT_TIME) values (12,to_date('27-MAR-25','DD-MON-RR'),47,0,null,null);
