--------------------------------------------------------
--  DDL for Table WRI$_ADV_EXECUTIONS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_ADV_EXECUTIONS" SHARING=METADATA 
   (	"ID" NUMBER, 
	"TASK_ID" NUMBER, 
	"NAME" VARCHAR2(128 BYTE), 
	"DESCRIPTION" VARCHAR2(256 BYTE), 
	"EXEC_TYPE" VARCHAR2(128 BYTE), 
	"EXEC_TYPE_ID" NUMBER, 
	"ADVISOR_ID" NUMBER, 
	"EXEC_START" DATE, 
	"EXEC_MTIME" DATE, 
	"EXEC_END" DATE, 
	"STATUS" NUMBER, 
	"STATUS_MSG_ID" NUMBER, 
	"ERROR_MSG_ID" NUMBER, 
	"FLAGS" NUMBER, 
	"REQ_DOP" NUMBER, 
	"ACTUAL_DOP" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRI$_ADV_EXECUTIONS" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRI$_ADV_EXECUTIONS" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRI$_ADV_EXECUTIONS" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRI$_ADV_EXECUTIONS" TO "SYSUMF_ROLE";
