--------------------------------------------------------
--  DDL for Table WRI$_SQLSET_STATEMENTS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_SQLSET_STATEMENTS" SHARING=METADATA 
   (	"ID" NUMBER, 
	"CON_DBID" NUMBER DEFAULT 0, 
	"SQLSET_ID" NUMBER, 
	"SQL_ID" VARCHAR2(13 BYTE), 
	"FORCE_MATCHING_SIGNATURE" NUMBER, 
	"PARSING_SCHEMA_NAME" VARCHAR2(128 BYTE), 
	"MODULE" VARCHAR2(64 BYTE), 
	"ACTION" VARCHAR2(64 BYTE), 
	"COMMAND_TYPE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
