--------------------------------------------------------
--  DDL for Index WRI$_ADV_JOURNAL
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."WRI$_ADV_JOURNAL" ON "SYS"."WRI$_ADV_JOURNAL" ("TASK_ID", "SEQ_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRI$_ADV_JOURNAL" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRI$_ADV_JOURNAL" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRI$_ADV_JOURNAL" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRI$_ADV_JOURNAL" TO "SYSUMF_ROLE";
