--------------------------------------------------------
--  DDL for Table WRI$_ADV_AI_COL_USAGE
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_ADV_AI_COL_USAGE" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"COLS" VARCHAR2(192 CHAR), 
	"SEL_COLS" VARCHAR2(192 CHAR), 
	"KEY_ID" VARCHAR2(192 CHAR), 
	"STATUS" NUMBER, 
	"LAST_UPDATED" TIMESTAMP (6) WITH TIME ZONE, 
	"COVERED_BY" VARCHAR2(192 CHAR), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(4000 BYTE), 
	"SPARE4" VARCHAR2(4000 BYTE), 
	"SPARE5" CLOB, 
	"SPARE6" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" 
 LOB ("SPARE5") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
