--------------------------------------------------------
--  DDL for Table WRI$_ADV_SQLT_PLANS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_ADV_SQLT_PLANS" SHARING=METADATA 
   (	"TASK_ID" NUMBER(38,0), 
	"OBJECT_ID" NUMBER(38,0), 
	"ATTRIBUTE" NUMBER, 
	"PLAN_HASH_VALUE" NUMBER, 
	"PLAN_ID" NUMBER, 
	"STATEMENT_ID" VARCHAR2(30 BYTE), 
	"TIMESTAMP" DATE, 
	"REMARKS" VARCHAR2(4000 BYTE), 
	"OPERATION" VARCHAR2(30 BYTE), 
	"OPTIONS" VARCHAR2(255 BYTE), 
	"OBJECT_NODE" VARCHAR2(128 BYTE), 
	"OBJECT_OWNER" VARCHAR2(128 BYTE), 
	"OBJECT_NAME" VARCHAR2(128 BYTE), 
	"OBJECT_ALIAS" VARCHAR2(261 BYTE), 
	"OBJECT_INSTANCE" NUMBER(38,0), 
	"OBJECT_TYPE" VARCHAR2(30 BYTE), 
	"OPTIMIZER" VARCHAR2(255 BYTE), 
	"SEARCH_COLUMNS" NUMBER, 
	"ID" NUMBER(38,0), 
	"PARENT_ID" NUMBER(38,0), 
	"DEPTH" NUMBER(38,0), 
	"POSITION" NUMBER(38,0), 
	"COST" NUMBER(38,0), 
	"CARDINALITY" NUMBER(38,0), 
	"BYTES" NUMBER(38,0), 
	"OTHER_TAG" VARCHAR2(255 BYTE), 
	"PARTITION_START" VARCHAR2(255 BYTE), 
	"PARTITION_STOP" VARCHAR2(255 BYTE), 
	"PARTITION_ID" NUMBER(38,0), 
	"OTHER" LONG, 
	"DISTRIBUTION" VARCHAR2(30 BYTE), 
	"CPU_COST" NUMBER(38,0), 
	"IO_COST" NUMBER(38,0), 
	"TEMP_SPACE" NUMBER(38,0), 
	"ACCESS_PREDICATES" VARCHAR2(4000 BYTE), 
	"FILTER_PREDICATES" VARCHAR2(4000 BYTE), 
	"PROJECTION" VARCHAR2(4000 BYTE), 
	"TIME" NUMBER(38,0), 
	"QBLOCK_NAME" VARCHAR2(128 BYTE), 
	"OTHER_XML" CLOB, 
	"OUTROWS" NUMBER(38,0), 
	"STARTS" NUMBER(38,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" 
 LOB ("OTHER_XML") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
  GRANT DELETE ON "SYS"."WRI$_ADV_SQLT_PLANS" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRI$_ADV_SQLT_PLANS" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRI$_ADV_SQLT_PLANS" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRI$_ADV_SQLT_PLANS" TO "SYSUMF_ROLE";
