REM INSERTING into SYS.WRI$_REPT_REPORTS
SET DEFINE OFF;
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (201,101,'all','SQLPA report',260);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (202,101,'task_list','List of sqlpa tasks',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (203,101,'create_task','Create new sqlpa task',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (204,101,'alter','Alter sqlpa existing task',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (205,101,'sts_list','List of sql tuning sets',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (206,101,'execution_list','List of sqlpa executions and reports',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (207,101,'create_execution','Create new sqlpa execution',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (208,101,'create_compare','Create new sqlpa compare report',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (209,101,'compare_summary','Sqlpa task comparison report summary',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (210,101,'compare_sql','Sqlpa task comparison report per SQL',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (211,101,'quick_check','Create a quick check task',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (212,101,'default_params','List of sqlpa default params',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (213,101,'set_default_params','Set sqlpa default param values',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (214,101,'default_qc_params','List of sqlpa quick check default params',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (215,101,'set_default_qc_params','Set sqlpa quick check default param values',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (216,101,'compare_plans','Compare plans',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (217,102,'summary','SQLTune EM Summary',262);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (218,102,'auto_summary','Auto SQLTune EM Summary',263);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (219,102,'sql_table','SQLTune EM SQL Table',264);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (220,102,'compare_plans','SQLTune Compare Explain Plans',265);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (221,102,'single_sql','SQLTune Single SQL',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (222,102,'task_list','List of sqltune Tasks',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (223,102,'main','Main sqltune Report',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (224,102,'implement','sqltune Implement Recommendation',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (225,102,'schedule','Schedule sqltune New Task',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (226,102,'create_and_execute','Create sqltune New Task and Execute',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (227,102,'dblinks','Get DB Links',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (228,102,'alter','Alter sqltune existing Task',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (229,102,'configure','configure sqltune existing Task',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (230,103,'typical','explain plan report',266);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (231,104,'all','DB Replay Report',268);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (232,105,'show_params','Show Initialization Parameters report',272);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (233,105,'set_param','Set Initialization Parameter',273);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (234,105,'server_info','Get Server Information for EM Express Shell',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (235,105,'show_feature_usage','Show Feature Usage',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (236,105,'show_db_props','Show Database Properties',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (237,105,'dbsearch','database search',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (238,106,'show_tablespaces','Get tablespace and datafile data',273);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (239,106,'create_tablespace','Create tablespace',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (240,106,'add_datafile','Add datafile to a tablespace',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (241,106,'drop_tablespace','Drop a tablespace',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (242,106,'drop_datafile','Drop a datafile or tempfile',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (243,106,'change_tbs_status','Change tablespace status',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (244,106,'change_df_status','Bring a datafile online or offline',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (245,106,'df_auto_extend','Change auto extend attribute of a datafile',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (246,106,'tbs_auto_extend','Change auto extend attribute of a tablespace',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (247,106,'resize_datafile','Resize a datafile',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (248,106,'resize_tablespace','Resize a tablespace',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (249,106,'set_default_tbs','Set default tablespace',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (250,106,'set_tablespace_group','Set tablespace group',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (251,106,'alter_tbs_inmemory','Alter tablespace in-memory setting',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (252,106,'show_control_files','Show Control files',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (253,106,'backup_control_file','Backup control file',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (254,106,'show_redolog_files','Show Redo Log Files',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (255,106,'create_redolog_group','Create a new redo log group',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (256,106,'drop_redolog_group','Drop an existing redo log group',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (257,106,'add_redolog_group_member','Add member to an existing redo log group',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (258,106,'switch_redo_logfile','Switch current instance log file',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (259,106,'clear_redo_logfile','Clear current instance log file',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (260,106,'force_checkpoint','Execute a global checkpoint',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (261,106,'show_undo_summary','Show Instance Level Undo Summary',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (262,106,'show_undo_details','Show Detail Undo Information for Instance',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (263,106,'show_unused_undo_tbs','Show Unused Undo Tablespaces',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (264,106,'switch_undo_tbs','Switch Undo Tablespace',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (265,106,'show_archlog_files','Show list of archive log files',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (266,107,'show_users','Get users',280);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (267,107,'show_userdetail','Get user details',281);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (268,107,'drop_user','Drop user',282);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (269,107,'create_user','Create new user',283);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (270,107,'alter_user','Alter user',283);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (271,107,'show_tablespaces','Show available tablespaces',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (272,107,'show_privs','Show available system privileges',284);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (273,107,'show_roles','Show available roles',285);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (274,107,'show_roledetail','Show role details',286);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (275,107,'grant','Grant privileges to user or role',287);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (276,107,'create_role','Create new role',288);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (277,107,'drop_role','Drop role',289);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (278,107,'show_objfilters','Show object filters',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (279,107,'show_objects','Show objects',290);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (280,107,'show_objprivs','Show object privileges',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (281,107,'show_profiles','Show profiles',291);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (282,107,'create_profile','Create new profile',292);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (283,107,'drop_profile','Drop profile',293);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (284,107,'show_profiledetail','Show profile resource limits',294);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (285,107,'alter_profile','Alter profile',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (286,108,'show_memory','Memory Advisors Report',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (287,109,'main','SQL Monitor report',295);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (288,109,'list','SQL Monitor report',298);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (289,110,'all','all plan diff in one report',301);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (290,111,'all','SPM evolve report',303);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (291,112,'viewer','ash viewer report',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (292,113,'viewer','AWR viewer report',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (293,113,'timepicker','Timepicker report',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (294,113,'topsql','Top SQL report',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (295,113,'addm','ADDM report',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (296,113,'rac','RAC report',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (297,113,'viewer_inst','AWR viewer instance report',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (298,114,'main','PerfHub report',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (299,114,'inst','PerfHub Instance report',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (300,114,'sql_detail','SqlHub report',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (301,114,'session','Session Hub report',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (302,114,'addm_watchdog','ADDM Watchdog report',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (303,114,'awrrep','AWR html report',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (304,115,'main','ADDM task report',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (305,116,'main','Real-Time ADDM',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (306,117,'main','Compare Period ADDM',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (307,117,'snap_list','Compare Period ADDM Snapshots List',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (308,118,'list','Auto Report Capture Repository',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (309,118,'detail','Auto Report Capture Repository',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (310,119,'main','Perf page',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (311,120,'details','Session Details report',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (312,120,'kill_session','Kill Session Action',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (313,121,'main','SQL Details report',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (314,121,'alter_plan_object','Alter SQL plan object',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (315,121,'drop_plan_object','Drop SQL plan object',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (316,121,'export_plan_object','Export Plan Object',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (317,121,'import_plan_object','Import Plan Object',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (318,121,'load_plan_baseline','Load sql plan baseline from the cursor cache',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (319,121,'list_all_directories','List all directories',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (320,122,'show_regions','DB Home regions',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (321,122,'show_instance_details','Instance details report for RAC',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (322,122,'show_containers','cdb container details report for CDB',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (323,122,'create_pdb','create a pdb in a CDB',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (324,122,'drop_pdb','drop a pdb in a CDB',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (325,122,'alter_pdb','alter a pdb in a CDB',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (326,122,'clone_pdb','clone a pdb in a CDB',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (327,122,'unplug_pdb','unplug a pdb in from CDB',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (328,122,'plug_pdb','plug a pdb in from CDB',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (329,122,'noncdb2pdb','convert non-cdb to pdb',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (330,122,'show_dblinks','show list of db links',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (331,122,'pdb_storage_limits','show pdb storage limits',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (332,122,'cdb_resource_plans','show cdb resource plan list',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (333,122,'set_cdb_resource_plan','enable/disable cdb resource plan',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (334,122,'pdb_violations','check for pdb violations',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (335,122,'show_pdb_instances','show list of instances for PDB',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (336,123,'all','Optimizer statistics report',305);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (337,124,'typical','SQL Testcase Builder report',307);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (338,125,'main','Exadata cell statistics',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (339,125,'diff','Exadata cell diff statistics',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (340,126,'main','Statistics Advisor report',311);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (341,127,'show_timeline','Resource Manager Plan History Timeline',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (342,127,'show_dashboard','Resource Manager Dashboard',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (343,127,'show_plans','Show list of all resource manager plans',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (344,127,'set_active_plan','Set the currently active resource plan',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (345,127,'set_instance_caging','Set Instance Caging cpu count',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (346,127,'show_plan','Resource Manager Plan Homepage',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (347,127,'create_consumer_group','Create a Consumer Group',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (348,127,'show_consumer_groups','Show a List of All Consumer Groups',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (349,127,'add_consumer_group','Add a Consumer Group to Current Plan',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (350,127,'group_deletable','Check if a Consumer Group is Deletable',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (351,127,'remove_consumer_group','Remove a Consumer Group',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (352,127,'update_consumer_group','Update a Consumer Group',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (353,127,'set_plan_directive','Set a Plan Directive for a Consumer Group',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (354,127,'show_group_mappings','Show a List of Consumer Group Mapping Rules',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (355,127,'set_group_mappings','Set Mapping Rules For a Consumer Group',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (356,127,'set_mapping_priorities','Set Mapping Rule Priorities',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (357,127,'create_plan','Create Resource Plan',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (358,127,'delete_plan','Delete a Resource Plan',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (359,127,'update_plan','Update a Resource Plan',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (360,127,'show_maintenance_windows','Show Maintenance Windows',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (361,127,'set_maintenance_windows','Set Maintenance Windows',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (362,127,'update_cdb_plan','Update a CDB Resource Plan',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (363,127,'update_pdb_directive','Update a PDB directive in a CDB plan',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (364,127,'get_attributes','Get list of services/users/programs',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (365,128,'main','Automatic Index report',313);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (366,129,'timepicker','Timepicker in OMX',250);
Insert into SYS.WRI$_REPT_REPORTS (ID,COMPONENT_ID,NAME,DESCRIPTION,SCHEMA_ID) values (367,129,'viewer','ASH Chart in OMX',250);
