--------------------------------------------------------
--  DDL for Table WRI$_ADV_ADDM_TASKS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_ADV_ADDM_TASKS" SHARING=METADATA 
   (	"TASK_ID" NUMBER, 
	"DBID" NUMBER, 
	"DBNAME" VARCHAR2(9 BYTE), 
	"DBVERSION" VARCHAR2(17 BYTE), 
	"ANALYSIS_VERSION" VARCHAR2(17 BYTE), 
	"BEGIN_SNAP_ID" NUMBER, 
	"BEGIN_TIME" TIMESTAMP (3), 
	"END_SNAP_ID" NUMBER, 
	"END_TIME" TIMESTAMP (3), 
	"REQUESTED_ANALYSIS" VARCHAR2(8 BYTE), 
	"ACTUAL_ANALYSIS" VARCHAR2(8 BYTE), 
	"DATABASE_TIME" NUMBER, 
	"ACTIVE_SESSIONS" NUMBER, 
	"PERC_FLUSH_TIME" NUMBER, 
	"PERC_MW_TIME" NUMBER, 
	"METER_LEVEL" VARCHAR2(6 BYTE), 
	"FDG_COUNT" NUMBER, 
	"DBTYPE_FLAGS" NUMBER, 
	"DBTYPE_FLAGS_USED" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
