--------------------------------------------------------
--  Constraints for Table WRI$_SQLSET_BINDS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRI$_SQLSET_BINDS" MODIFY ("STMT_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_SQLSET_BINDS" MODIFY ("PLAN_HASH_VALUE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_SQLSET_BINDS" MODIFY ("POSITION" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_SQLSET_BINDS" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_SQLSET_BINDS" ADD CONSTRAINT "WRI$_SQLSET_BINDS_PK" PRIMARY KEY ("STMT_ID", "PLAN_HASH_VALUE", "POSITION", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
