--------------------------------------------------------
--  DDL for Table WRI$_TOPN_METADATA
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_TOPN_METADATA" SHARING=METADATA 
   (	"TASK_ID" NUMBER, 
	"TASK_STARTTIME" DATE, 
	"TASK_COMPLETIONTIME" DATE, 
	"TASK_STATUS" VARCHAR2(10 BYTE), 
	"TBS_PROCESSED" NUMBER, 
	"OBJECTS_PROCESSED" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
