--------------------------------------------------------
--  DDL for Table WRI$_TRACING_ENABLED
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_TRACING_ENABLED" SHARING=METADATA 
   (	"TRACE_TYPE" NUMBER, 
	"PRIMARY_ID" VARCHAR2(64 BYTE), 
	"QUALIFIER_ID1" VARCHAR2(64 BYTE), 
	"QUALIFIER_ID2" VARCHAR2(64 BYTE), 
	"INSTANCE_NAME" VARCHAR2(16 BYTE), 
	"FLAGS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
