--------------------------------------------------------
--  Constraints for Table WRI$_ADV_REC_ACTIONS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRI$_ADV_REC_ACTIONS" MODIFY ("TASK_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_REC_ACTIONS" MODIFY ("REC_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_REC_ACTIONS" MODIFY ("ACT_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_REC_ACTIONS" ADD CONSTRAINT "WRI$_ADV_REC_ACTIONS_PK" PRIMARY KEY ("TASK_ID", "REC_ID", "ACT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
