--------------------------------------------------------
--  DDL for Table WRI$_ADV_RECOMMENDATIONS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_ADV_RECOMMENDATIONS" SHARING=METADATA 
   (	"ID" NUMBER, 
	"TASK_ID" NUMBER, 
	"TYPE" VARCHAR2(30 BYTE), 
	"EXEC_NAME" VARCHAR2(128 BYTE), 
	"FINDING_ID" NUMBER, 
	"RANK" NUMBER, 
	"PARENT_RECS" VARCHAR2(4000 BYTE), 
	"BENEFIT_MSG_ID" NUMBER, 
	"BENEFIT_VAL" NUMBER, 
	"ANNOTATION" NUMBER, 
	"FLAGS" NUMBER, 
	"FILTERED" CHAR(1 BYTE), 
	"REC_TYPE_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRI$_ADV_RECOMMENDATIONS" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRI$_ADV_RECOMMENDATIONS" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRI$_ADV_RECOMMENDATIONS" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRI$_ADV_RECOMMENDATIONS" TO "SYSUMF_ROLE";
