--------------------------------------------------------
--  DDL for Table WRI$_SQLSET_WORKSPACE
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_SQLSET_WORKSPACE" SHARING=METADATA 
   (	"WORKSPACE_NAME" VARCHAR2(128 BYTE), 
	"SQLSET_NAME" VARCHAR2(128 BYTE), 
	"SQL_ID" VARCHAR2(13 BYTE), 
	"PLAN_HASH_VALUE" NUMBER, 
	"CONTROL_OPTIONS" CLOB, 
	"NEW_PLAN_HASH" NUMBER, 
	"PLAN_ID" NUMBER, 
	"EXTRA_RESULT" CLOB, 
	"ERROR_CODE" NUMBER, 
	"ERROR_MESSAGE" CLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("CONTROL_OPTIONS") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("EXTRA_RESULT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("ERROR_MESSAGE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
