--------------------------------------------------------
--  DDL for Table WRI$_REPT_REPORTS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_REPT_REPORTS" SHARING=METADATA 
   (	"ID" NUMBER, 
	"COMPONENT_ID" NUMBER, 
	"NAME" VARCHAR2(128 BYTE), 
	"DESCRIPTION" VARCHAR2(256 BYTE), 
	"SCHEMA_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
