--------------------------------------------------------
--  DDL for Table WRI$_OPTSTAT_HISTGRM_HISTORY
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_OPTSTAT_HISTGRM_HISTORY" SHARING=METADATA 
   (	"OBJ#" NUMBER, 
	"INTCOL#" NUMBER, 
	"SAVTIME" TIMESTAMP (6) WITH TIME ZONE, 
	"BUCKET" NUMBER, 
	"ENDPOINT" NUMBER, 
	"EPVALUE" VARCHAR2(1000 BYTE), 
	"COLNAME" VARCHAR2(128 BYTE), 
	"EP_REPEAT_COUNT" NUMBER DEFAULT 0, 
	"EPVALUE_RAW" RAW(1000), 
	"SAVTIME_DATE" DATE GENERATED ALWAYS AS (TRUNC("SAVTIME")) VIRTUAL , 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" VARCHAR2(1000 BYTE), 
	"SPARE5" VARCHAR2(1000 BYTE), 
	"SPARE6" TIMESTAMP (6) WITH TIME ZONE, 
	"ENDPOINT_ENC" RAW(1000)
   ) PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
  PARTITION BY RANGE ("SAVTIME_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) 
 (PARTITION "P_PERMANENT"  VALUES LESS THAN (TO_DATE(' 1900-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" )  ENABLE ROW MOVEMENT ;
