--------------------------------------------------------
--  Constraints for Table WRI$_ADV_DEF_PARAMETERS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRI$_ADV_DEF_PARAMETERS" MODIFY ("ADVISOR_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_DEF_PARAMETERS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_DEF_PARAMETERS" MODIFY ("DATATYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_DEF_PARAMETERS" MODIFY ("FLAGS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_DEF_PARAMETERS" MODIFY ("VALUE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_DEF_PARAMETERS" ADD CONSTRAINT "WRI$_ADV_DEF_PARAMETERS_PK" PRIMARY KEY ("ADVISOR_ID", "NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE;
