--------------------------------------------------------
--  DDL for Table WRI$_SQLMON_USAGE
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_SQLMON_USAGE" SHARING=METADATA 
   (	"NUM_DB_REPORTS" NUMBER, 
	"NUM_EM_REPORTS" NUMBER, 
	"FIRST_DB_REPORT_TIME" DATE, 
	"LAST_DB_REPORT_TIME" DATE, 
	"FIRST_EM_REPORT_TIME" DATE, 
	"LAST_EM_REPORT_TIME" DATE, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" NUMBER, 
	"SPARE5" DATE, 
	"SPARE6" DATE, 
	"SPARE7" DATE, 
	"SPARE8" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
