--------------------------------------------------------
--  Constraints for Table WRI$_ADV_TASKS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRI$_ADV_TASKS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_TASKS" MODIFY ("OWNER#" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_TASKS" MODIFY ("ADVISOR_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_TASKS" MODIFY ("CTIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_TASKS" MODIFY ("MTIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_TASKS" MODIFY ("PROPERTY" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_TASKS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_TASKS" ADD CONSTRAINT "WRI$_ADV_TASKS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE;
