--------------------------------------------------------
--  DDL for Sequence WRI$_SQLSET_REF_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SYS"."WRI$_SQLSET_REF_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "SYS"."WRI$_SQLSET_REF_ID_SEQ" TO "SYSUMF_ROLE";
