REM INSERTING into SYS.WRI$_DBU_CPU_USAGE_SAMPLE
SET DEFINE OFF;
Insert into SYS.WRI$_DBU_CPU_USAGE_SAMPLE (DBID,VERSION,LAST_SAMPLE_DATE,LAST_SAMPLE_DATE_NUM,LAST_SAMPLE_PERIOD,TOTAL_SAMPLES,SAMPLE_INTERVAL) values (1713764371,'19.0.0.0.0',null,null,0,0,43200);
Insert into SYS.WRI$_DBU_CPU_USAGE_SAMPLE (DBID,VERSION,LAST_SAMPLE_DATE,LAST_SAMPLE_DATE_NUM,LAST_SAMPLE_PERIOD,TOTAL_SAMPLES,SAMPLE_INTERVAL) values (43306430,'19.0.0.0.0',null,null,0,0,43200);
