--------------------------------------------------------
--  Constraints for Table WRI$_DBU_CPU_USAGE
--------------------------------------------------------

  ALTER TABLE "SYS"."WRI$_DBU_CPU_USAGE" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_DBU_CPU_USAGE" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_DBU_CPU_USAGE" MODIFY ("TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_DBU_CPU_USAGE" ADD CONSTRAINT "WRI$_DBU_CPU_USAGE_PK" PRIMARY KEY ("DBID", "VERSION", "TIMESTAMP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
