--------------------------------------------------------
--  Constraints for Table WRI$_ADV_SQLT_RTN_PLAN
--------------------------------------------------------

  ALTER TABLE "SYS"."WRI$_ADV_SQLT_RTN_PLAN" MODIFY ("TASK_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_SQLT_RTN_PLAN" MODIFY ("EXEC_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_SQLT_RTN_PLAN" MODIFY ("RTN_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_SQLT_RTN_PLAN" MODIFY ("OBJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_SQLT_RTN_PLAN" MODIFY ("PLAN_ATTR" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_SQLT_RTN_PLAN" MODIFY ("OPERATION_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_SQLT_RTN_PLAN" ADD CONSTRAINT "WRI$_ADV_SQLT_RTN_PLAN_PK" PRIMARY KEY ("TASK_ID", "EXEC_NAME", "RTN_ID", "OBJECT_ID", "PLAN_ATTR", "OPERATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
