--------------------------------------------------------
--  DDL for Table WRI$_ALERT_THRESHOLD
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_ALERT_THRESHOLD" SHARING=METADATA 
   (	"T_OBJECT_TYPE" NUMBER, 
	"T_OBJECT_NAME" VARCHAR2(513 BYTE), 
	"T_METRICS_ID" NUMBER, 
	"T_INSTANCE_NAME" VARCHAR2(16 BYTE), 
	"T_FLAGS" NUMBER, 
	"T_WARNING_OPERATOR" NUMBER, 
	"T_WARNING_VALUE" VARCHAR2(256 BYTE), 
	"T_CRITICAL_OPERATOR" NUMBER, 
	"T_CRITICAL_VALUE" VARCHAR2(256 BYTE), 
	"T_OBSERVATION_PERIOD" NUMBER, 
	"T_CONSECUTIVE_OCCURRENCES" NUMBER, 
	"T_OBJECT_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
