--------------------------------------------------------
--  DDL for Table WRI$_ADV_SQLT_STATISTICS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_ADV_SQLT_STATISTICS" SHARING=METADATA 
   (	"TASK_ID" NUMBER(38,0), 
	"OBJECT_ID" NUMBER(38,0), 
	"PARSING_SCHEMA_ID" NUMBER, 
	"MODULE" VARCHAR2(64 BYTE), 
	"ACTION" VARCHAR2(64 BYTE), 
	"ELAPSED_TIME" NUMBER, 
	"CPU_TIME" NUMBER, 
	"BUFFER_GETS" NUMBER, 
	"DISK_READS" NUMBER, 
	"DIRECT_WRITES" NUMBER, 
	"ROWS_PROCESSED" NUMBER, 
	"FETCHES" NUMBER, 
	"EXECUTIONS" NUMBER, 
	"END_OF_FETCH_COUNT" NUMBER, 
	"OPTIMIZER_COST" NUMBER, 
	"OPTIMIZER_ENV" RAW(2000), 
	"COMMAND_TYPE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRI$_ADV_SQLT_STATISTICS" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRI$_ADV_SQLT_STATISTICS" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRI$_ADV_SQLT_STATISTICS" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRI$_ADV_SQLT_STATISTICS" TO "SYSUMF_ROLE";
