--------------------------------------------------------
--  Constraints for Table WRI$_ADV_SQLT_PLAN_STATS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRI$_ADV_SQLT_PLAN_STATS" MODIFY ("PLAN_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_SQLT_PLAN_STATS" ADD CONSTRAINT "WRI$_ADV_SQLT_PLAN_STATS_PK" PRIMARY KEY ("PLAN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
