--------------------------------------------------------
--  DDL for Table WRI$_DBU_HIGH_WATER_MARK
--------------------------------------------------------

  CREATE TABLE "SYS"."WRI$_DBU_HIGH_WATER_MARK" SHARING=METADATA 
   (	"NAME" VARCHAR2(128 BYTE), 
	"DBID" NUMBER, 
	"VERSION" VARCHAR2(17 BYTE), 
	"HIGHWATER" NUMBER, 
	"LAST_VALUE" NUMBER, 
	"ERROR_COUNT" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
