--------------------------------------------------------
--  Constraints for Table WRI$_ADV_SQLT_PLAN_HASH
--------------------------------------------------------

  ALTER TABLE "SYS"."WRI$_ADV_SQLT_PLAN_HASH" MODIFY ("TASK_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_SQLT_PLAN_HASH" MODIFY ("EXEC_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_SQLT_PLAN_HASH" MODIFY ("OBJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_SQLT_PLAN_HASH" MODIFY ("SQL_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_SQLT_PLAN_HASH" MODIFY ("ATTRIBUTE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_SQLT_PLAN_HASH" MODIFY ("PLAN_HASH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_SQLT_PLAN_HASH" MODIFY ("PLAN_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_SQLT_PLAN_HASH" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRI$_ADV_SQLT_PLAN_HASH" ADD CONSTRAINT "WRI$_ADV_SQLT_PLAN_HASH_PK" PRIMARY KEY ("TASK_ID", "EXEC_NAME", "OBJECT_ID", "ATTRIBUTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
