--------------------------------------------------------
--  Constraints for Table WRM$_PDB_IN_SNAP_BL
--------------------------------------------------------

  ALTER TABLE "SYS"."WRM$_PDB_IN_SNAP_BL" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_PDB_IN_SNAP_BL" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_PDB_IN_SNAP_BL" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_PDB_IN_SNAP_BL" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_PDB_IN_SNAP_BL" ADD CONSTRAINT "WRM$_PDB_IN_SNAP_BL_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "CON_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
