--------------------------------------------------------
--  DDL for Table WRM$_WR_USAGE
--------------------------------------------------------

  CREATE TABLE "SYS"."WRM$_WR_USAGE" SHARING=METADATA 
   (	"FEATURE_TYPE" VARCHAR2(32 BYTE), 
	"FEATURE_NAME" VARCHAR2(64 BYTE), 
	"USAGE_TIME" TIMESTAMP (3)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRM$_WR_USAGE" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRM$_WR_USAGE" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRM$_WR_USAGE" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRM$_WR_USAGE" TO "SYSUMF_ROLE";
