--------------------------------------------------------
--  DDL for Table WRM$_TABLE_SETTINGS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRM$_TABLE_SETTINGS" SHARING=METADATA 
   (	"DBID" NUMBER, 
	"TABLE_NAME" VARCHAR2(128 BYTE), 
	"FLUSH_LEVEL_VAL" VARCHAR2(32 BYTE) DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRM$_TABLE_SETTINGS" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRM$_TABLE_SETTINGS" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRM$_TABLE_SETTINGS" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRM$_TABLE_SETTINGS" TO "SYSUMF_ROLE";
