--------------------------------------------------------
--  DDL for Index WRM$_ACTIVE_PDBS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."WRM$_ACTIVE_PDBS_PK" ON "SYS"."WRM$_ACTIVE_PDBS" ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "PDBID", "CON_DBID", "TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  LOCAL
 (PARTITION "WRM$_ACTIVE_PDBS_692950692_0" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRM$_ACTIVE_PDBS_MXDB_MXSN" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ) ;
