--------------------------------------------------------
--  DDL for Table WRM$_PDB_IN_SNAP
--------------------------------------------------------

  CREATE TABLE "SYS"."WRM$_PDB_IN_SNAP" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"CON_DBID" NUMBER, 
	"FLAG" NUMBER, 
	"OPEN_TIME_TZ" TIMESTAMP (3) WITH TIME ZONE
   ) PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARTITION BY RANGE ("DBID","SNAP_ID") 
 (PARTITION "WRM$_PDB_IN_SNAP_692950692_0"  VALUES LESS THAN (692950692, MAXVALUE) 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRM$_PDB_IN_SNAP_MXDB_MXSN"  VALUES LESS THAN (MAXVALUE, MAXVALUE) 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" )  ENABLE ROW MOVEMENT ;
  GRANT DELETE ON "SYS"."WRM$_PDB_IN_SNAP" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRM$_PDB_IN_SNAP" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRM$_PDB_IN_SNAP" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRM$_PDB_IN_SNAP" TO "SYSUMF_ROLE";
