--------------------------------------------------------
--  DDL for Table WRM$_PDB_INSTANCE
--------------------------------------------------------

  CREATE TABLE "SYS"."WRM$_PDB_INSTANCE" SHARING=METADATA 
   (	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"STARTUP_TIME" TIMESTAMP (3), 
	"CON_DBID" NUMBER, 
	"OPEN_TIME" TIMESTAMP (3), 
	"OPEN_MODE" VARCHAR2(16 BYTE), 
	"PDB_NAME" VARCHAR2(128 BYTE), 
	"SNAP_ID" NUMBER, 
	"STARTUP_TIME_TZ" TIMESTAMP (3) WITH TIME ZONE, 
	"OPEN_TIME_TZ" TIMESTAMP (3) WITH TIME ZONE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRM$_PDB_INSTANCE" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRM$_PDB_INSTANCE" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRM$_PDB_INSTANCE" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRM$_PDB_INSTANCE" TO "SYSUMF_ROLE";
