--------------------------------------------------------
--  Constraints for Table WRM$_TABLE_SETTINGS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRM$_TABLE_SETTINGS" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_TABLE_SETTINGS" MODIFY ("TABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_TABLE_SETTINGS" ADD CONSTRAINT "WRM$_TABLE_SETTINGS_PK" PRIMARY KEY ("DBID", "TABLE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
