--------------------------------------------------------
--  Constraints for Table WRM$_SNAPSHOT_DETAILS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRM$_SNAPSHOT_DETAILS" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_SNAPSHOT_DETAILS" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_SNAPSHOT_DETAILS" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_SNAPSHOT_DETAILS" MODIFY ("TABLE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_SNAPSHOT_DETAILS" MODIFY ("STEP_ID" NOT NULL ENABLE);
