--------------------------------------------------------
--  DDL for Table WRM$_BASELINE_DETAILS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRM$_BASELINE_DETAILS" SHARING=METADATA 
   (	"DBID" NUMBER, 
	"BASELINE_ID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"START_SNAP_ID" NUMBER, 
	"START_SNAP_TIME" TIMESTAMP (3), 
	"END_SNAP_ID" NUMBER, 
	"END_SNAP_TIME" TIMESTAMP (3), 
	"SHUTDOWN" VARCHAR2(3 BYTE), 
	"ERROR_COUNT" NUMBER, 
	"PCT_TOTAL_TIME" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRM$_BASELINE_DETAILS" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRM$_BASELINE_DETAILS" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRM$_BASELINE_DETAILS" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRM$_BASELINE_DETAILS" TO "SYSUMF_ROLE";
