--------------------------------------------------------
--  DDL for Table WRM$_WR_CONTROL
--------------------------------------------------------

  CREATE TABLE "SYS"."WRM$_WR_CONTROL" SHARING=METADATA 
   (	"DBID" NUMBER, 
	"SNAP_INTERVAL" INTERVAL DAY (5) TO SECOND (1), 
	"SNAPINT_NUM" NUMBER, 
	"RETENTION" INTERVAL DAY (5) TO SECOND (1), 
	"RETENTION_NUM" NUMBER, 
	"MOST_RECENT_SNAP_ID" NUMBER, 
	"MOST_RECENT_SNAP_TIME" TIMESTAMP (3), 
	"MRCT_SNAP_TIME_NUM" NUMBER, 
	"STATUS_FLAG" NUMBER, 
	"MOST_RECENT_PURGE_TIME" TIMESTAMP (3), 
	"MRCT_PURGE_TIME_NUM" NUMBER, 
	"MOST_RECENT_SPLIT_ID" NUMBER, 
	"MOST_RECENT_SPLIT_TIME" NUMBER, 
	"SWRF_VERSION" NUMBER, 
	"REGISTRATION_STATUS" NUMBER, 
	"MRCT_BASELINE_ID" NUMBER, 
	"TOPNSQL" NUMBER, 
	"MRCT_BLTMPL_ID" NUMBER, 
	"SRC_DBID" NUMBER DEFAULT 0, 
	"SRC_DBNAME" VARCHAR2(128 BYTE), 
	"T2S_DBLINK" VARCHAR2(128 BYTE), 
	"FLUSH_TYPE" NUMBER DEFAULT 0, 
	"SNAP_ALIGN" NUMBER DEFAULT 0, 
	"MRCT_SNAP_STEP_TM" NUMBER DEFAULT 0, 
	"MRCT_SNAP_STEP_ID" NUMBER DEFAULT 0, 
	"TABLESPACE_NAME" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRM$_WR_CONTROL" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRM$_WR_CONTROL" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRM$_WR_CONTROL" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRM$_WR_CONTROL" TO "SYSUMF_ROLE";
