--------------------------------------------------------
--  Constraints for Table WRM$_BASELINE
--------------------------------------------------------

  ALTER TABLE "SYS"."WRM$_BASELINE" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_BASELINE" MODIFY ("BASELINE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_BASELINE" ADD CONSTRAINT "WRM$_BASELINE_PK" PRIMARY KEY ("DBID", "BASELINE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE;
