--------------------------------------------------------
--  DDL for Table WRM$_SNAP_ERROR
--------------------------------------------------------

  CREATE TABLE "SYS"."WRM$_SNAP_ERROR" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"TABLE_NAME" VARCHAR2(128 BYTE), 
	"ERROR_NUMBER" NUMBER, 
	"STEP_ID" NUMBER DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRM$_SNAP_ERROR" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRM$_SNAP_ERROR" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRM$_SNAP_ERROR" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRM$_SNAP_ERROR" TO "SYSUMF_ROLE";
