--------------------------------------------------------
--  DDL for Table WRM$_DATABASE_INSTANCE
--------------------------------------------------------

  CREATE TABLE "SYS"."WRM$_DATABASE_INSTANCE" SHARING=METADATA 
   (	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"STARTUP_TIME" TIMESTAMP (3), 
	"PARALLEL" VARCHAR2(3 BYTE), 
	"VERSION" VARCHAR2(17 BYTE), 
	"DB_NAME" VARCHAR2(9 BYTE), 
	"INSTANCE_NAME" VARCHAR2(16 BYTE), 
	"HOST_NAME" VARCHAR2(64 BYTE), 
	"LAST_ASH_SAMPLE_ID" NUMBER, 
	"PLATFORM_NAME" VARCHAR2(101 BYTE), 
	"CDB" VARCHAR2(3 BYTE), 
	"EDITION" VARCHAR2(7 BYTE), 
	"DB_UNIQUE_NAME" VARCHAR2(30 BYTE), 
	"DATABASE_ROLE" VARCHAR2(16 BYTE), 
	"CDB_ROOT_DBID" NUMBER, 
	"STARTUP_TIME_TZ" TIMESTAMP (3) WITH TIME ZONE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRM$_DATABASE_INSTANCE" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRM$_DATABASE_INSTANCE" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRM$_DATABASE_INSTANCE" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRM$_DATABASE_INSTANCE" TO "SYSUMF_ROLE";
