--------------------------------------------------------
--  Constraints for Table WRM$_DATABASE_INSTANCE
--------------------------------------------------------

  ALTER TABLE "SYS"."WRM$_DATABASE_INSTANCE" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_DATABASE_INSTANCE" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_DATABASE_INSTANCE" MODIFY ("STARTUP_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_DATABASE_INSTANCE" MODIFY ("PARALLEL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_DATABASE_INSTANCE" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_DATABASE_INSTANCE" MODIFY ("LAST_ASH_SAMPLE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_DATABASE_INSTANCE" ADD CONSTRAINT "WRM$_DATABASE_INSTANCE_PK" PRIMARY KEY ("DBID", "INSTANCE_NUMBER", "STARTUP_TIME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
