--------------------------------------------------------
--  Constraints for Table WRM$_SNAP_ERROR
--------------------------------------------------------

  ALTER TABLE "SYS"."WRM$_SNAP_ERROR" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_SNAP_ERROR" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_SNAP_ERROR" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_SNAP_ERROR" MODIFY ("TABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_SNAP_ERROR" MODIFY ("ERROR_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_SNAP_ERROR" MODIFY ("STEP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_SNAP_ERROR" ADD CONSTRAINT "WRM$_SNAP_ERROR_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "TABLE_NAME", "STEP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
