--------------------------------------------------------
--  Constraints for Table WRM$_SNAPSHOT
--------------------------------------------------------

  ALTER TABLE "SYS"."WRM$_SNAPSHOT" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_SNAPSHOT" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_SNAPSHOT" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_SNAPSHOT" MODIFY ("STARTUP_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_SNAPSHOT" MODIFY ("BEGIN_INTERVAL_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_SNAPSHOT" MODIFY ("END_INTERVAL_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_SNAPSHOT" ADD CONSTRAINT "WRM$_SNAPSHOT_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
