REM INSERTING into SYS.WRM$_BASELINE
SET DEFINE OFF;
Insert into SYS.WRM$_BASELINE (DBID,BASELINE_ID,BASELINE_NAME,START_SNAP_ID,END_SNAP_ID,BASELINE_TYPE,MOVING_WINDOW_SIZE,CREATION_TIME,EXPIRATION,TEMPLATE_NAME,LAST_TIME_COMPUTED) values (692950692,0,'SYSTEM_MOVING_WINDOW',null,null,'MOVING_WINDOW',8,to_date('25-NOV-24','DD-MON-RR'),null,null,null);
