--------------------------------------------------------
--  Constraints for Table WRM$_COLORED_SQL
--------------------------------------------------------

  ALTER TABLE "SYS"."WRM$_COLORED_SQL" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_COLORED_SQL" MODIFY ("SQL_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_COLORED_SQL" MODIFY ("OWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_COLORED_SQL" MODIFY ("CREATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_COLORED_SQL" ADD CONSTRAINT "WRM$_COLORED_SQL_PK" PRIMARY KEY ("DBID", "SQL_ID", "OWNER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
