--------------------------------------------------------
--  DDL for Table WRM$_SNAPSHOT_DETAILS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRM$_SNAPSHOT_DETAILS" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"TABLE_ID" NUMBER, 
	"BEGIN_TIME" TIMESTAMP (3), 
	"END_TIME" TIMESTAMP (3), 
	"STEP_ID" NUMBER DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRM$_SNAPSHOT_DETAILS" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRM$_SNAPSHOT_DETAILS" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRM$_SNAPSHOT_DETAILS" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRM$_SNAPSHOT_DETAILS" TO "SYSUMF_ROLE";
