--------------------------------------------------------
--  DDL for Table WRM$_BASELINE
--------------------------------------------------------

  CREATE TABLE "SYS"."WRM$_BASELINE" SHARING=METADATA 
   (	"DBID" NUMBER, 
	"BASELINE_ID" NUMBER, 
	"BASELINE_NAME" VARCHAR2(128 BYTE), 
	"START_SNAP_ID" NUMBER, 
	"END_SNAP_ID" NUMBER, 
	"BASELINE_TYPE" VARCHAR2(13 BYTE), 
	"MOVING_WINDOW_SIZE" NUMBER, 
	"CREATION_TIME" DATE, 
	"EXPIRATION" NUMBER, 
	"TEMPLATE_NAME" VARCHAR2(128 BYTE), 
	"LAST_TIME_COMPUTED" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRM$_BASELINE" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRM$_BASELINE" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRM$_BASELINE" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRM$_BASELINE" TO "SYSUMF_ROLE";
