--------------------------------------------------------
--  Constraints for Table WRM$_TABLE_DEFAULT_SETTINGS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRM$_TABLE_DEFAULT_SETTINGS" MODIFY ("TABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_TABLE_DEFAULT_SETTINGS" MODIFY ("DEFAULT_FLUSH_LEVEL_VAL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_TABLE_DEFAULT_SETTINGS" ADD CONSTRAINT "WRM$_TABLE_DEFAULT_SETTINGS_PK" PRIMARY KEY ("TABLE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE;
