--------------------------------------------------------
--  Constraints for Table WRM$_BASELINE_DETAILS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRM$_BASELINE_DETAILS" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_BASELINE_DETAILS" MODIFY ("BASELINE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_BASELINE_DETAILS" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_BASELINE_DETAILS" ADD CONSTRAINT "WRM$_BASELINE_DETAILS_PK" PRIMARY KEY ("DBID", "BASELINE_ID", "INSTANCE_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
