--------------------------------------------------------
--  DDL for Table WRM$_COLORED_SQL
--------------------------------------------------------

  CREATE TABLE "SYS"."WRM$_COLORED_SQL" SHARING=METADATA 
   (	"DBID" NUMBER, 
	"SQL_ID" VARCHAR2(13 BYTE), 
	"OWNER" NUMBER, 
	"CREATE_TIME" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRM$_COLORED_SQL" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRM$_COLORED_SQL" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRM$_COLORED_SQL" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRM$_COLORED_SQL" TO "SYSUMF_ROLE";
