--------------------------------------------------------
--  Constraints for Table WRM$_ACTIVE_PDBS_BL
--------------------------------------------------------

  ALTER TABLE "SYS"."WRM$_ACTIVE_PDBS_BL" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_ACTIVE_PDBS_BL" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_ACTIVE_PDBS_BL" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_ACTIVE_PDBS_BL" MODIFY ("PDBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_ACTIVE_PDBS_BL" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_ACTIVE_PDBS_BL" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_ACTIVE_PDBS_BL" ADD CONSTRAINT "WRM$_ACTIVE_PDBS_BL" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "PDBID", "CON_DBID", "TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
