--------------------------------------------------------
--  Constraints for Table WRM$_ACTIVE_PDBS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRM$_ACTIVE_PDBS" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_ACTIVE_PDBS" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_ACTIVE_PDBS" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_ACTIVE_PDBS" MODIFY ("PDBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_ACTIVE_PDBS" MODIFY ("CON_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_ACTIVE_PDBS" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRM$_ACTIVE_PDBS" ADD CONSTRAINT "WRM$_ACTIVE_PDBS_PK" PRIMARY KEY ("DBID", "SNAP_ID", "INSTANCE_NUMBER", "PDBID", "CON_DBID", "TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  LOCAL
 (PARTITION "WRM$_ACTIVE_PDBS_692950692_0" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" , 
 PARTITION "WRM$_ACTIVE_PDBS_MXDB_MXSN" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" )  ENABLE;
