--------------------------------------------------------
--  DDL for Index WRM$_TABLE_DEFAULT_SETTINGS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."WRM$_TABLE_DEFAULT_SETTINGS_PK" ON "SYS"."WRM$_TABLE_DEFAULT_SETTINGS" ("TABLE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
