--------------------------------------------------------
--  DDL for Table WRM$_BASELINE_TEMPLATE
--------------------------------------------------------

  CREATE TABLE "SYS"."WRM$_BASELINE_TEMPLATE" SHARING=METADATA 
   (	"DBID" NUMBER, 
	"TEMPLATE_ID" NUMBER, 
	"TEMPLATE_NAME" VARCHAR2(128 BYTE), 
	"TEMPLATE_TYPE" VARCHAR2(9 BYTE), 
	"BASELINE_NAME_PREFIX" VARCHAR2(128 BYTE), 
	"START_TIME" DATE, 
	"END_TIME" DATE, 
	"DAY_OF_WEEK" VARCHAR2(9 BYTE), 
	"HOUR_IN_DAY" NUMBER, 
	"DURATION" NUMBER, 
	"EXPIRATION" NUMBER, 
	"REPEAT_INTERVAL" VARCHAR2(128 BYTE), 
	"LAST_GENERATED" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
  GRANT DELETE ON "SYS"."WRM$_BASELINE_TEMPLATE" TO "SYSUMF_ROLE";
  GRANT INSERT ON "SYS"."WRM$_BASELINE_TEMPLATE" TO "SYSUMF_ROLE";
  GRANT SELECT ON "SYS"."WRM$_BASELINE_TEMPLATE" TO "SYSUMF_ROLE";
  GRANT UPDATE ON "SYS"."WRM$_BASELINE_TEMPLATE" TO "SYSUMF_ROLE";
