--------------------------------------------------------
--  Constraints for Table WRMS$_SNAPSHOT
--------------------------------------------------------

  ALTER TABLE "SYS"."WRMS$_SNAPSHOT" MODIFY ("SNAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRMS$_SNAPSHOT" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRMS$_SNAPSHOT" MODIFY ("INSTANCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRMS$_SNAPSHOT" MODIFY ("STARTUP_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRMS$_SNAPSHOT" MODIFY ("BEGIN_INTERVAL_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRMS$_SNAPSHOT" MODIFY ("END_INTERVAL_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRMS$_SNAPSHOT" MODIFY ("STAGE_INST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRMS$_SNAPSHOT" MODIFY ("STAGE_ID" NOT NULL ENABLE);
