--------------------------------------------------------
--  DDL for Table WRP$_REPORTS_CONTROL
--------------------------------------------------------

  CREATE TABLE "SYS"."WRP$_REPORTS_CONTROL" SHARING=METADATA 
   (	"DBID" NUMBER, 
	"EXECUTION_MODE" NUMBER DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
