--------------------------------------------------------
--  DDL for Table WRP$_REPORTS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRP$_REPORTS" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"REPORT_ID" NUMBER, 
	"CON_DBID" NUMBER, 
	"COMPONENT_ID" NUMBER, 
	"SESSION_ID" NUMBER, 
	"SESSION_SERIAL#" NUMBER, 
	"PERIOD_START_TIME" DATE, 
	"PERIOD_END_TIME" DATE, 
	"GENERATION_TIME" DATE, 
	"COMPONENT_NAME" VARCHAR2(128 BYTE), 
	"REPORT_NAME" VARCHAR2(128 BYTE), 
	"REPORT_PARAMS" VARCHAR2(1024 BYTE), 
	"KEY1" VARCHAR2(128 BYTE), 
	"KEY2" VARCHAR2(128 BYTE), 
	"KEY3" VARCHAR2(128 BYTE), 
	"KEY4" VARCHAR2(256 BYTE), 
	"GENERATION_COST" NUMBER, 
	"REPORT_SUMMARY" VARCHAR2(4000 BYTE), 
	"SPARE1" NUMBER DEFAULT null, 
	"SPARE2" NUMBER DEFAULT null, 
	"SPARE3" NUMBER DEFAULT null, 
	"SPARE4" VARCHAR2(4000 BYTE) DEFAULT null, 
	"SPARE5" VARCHAR2(4000 BYTE) DEFAULT null, 
	"SPARE6" VARCHAR2(4000 BYTE) DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
  PARTITION BY RANGE ("GENERATION_TIME") INTERVAL (NUMTODSINTERVAL(1, 'DAY')) 
 (PARTITION "P0"  VALUES LESS THAN (TO_DATE(' 2010-01-01 01:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ) ;
