--------------------------------------------------------
--  DDL for Table WRP$_REPORTS_TIME_BANDS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRP$_REPORTS_TIME_BANDS" SHARING=METADATA 
   (	"SNAP_ID" NUMBER, 
	"DBID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"CON_DBID" NUMBER, 
	"SESSION_ID" NUMBER, 
	"SESSION_SERIAL#" NUMBER, 
	"COMPONENT_ID" NUMBER, 
	"COMPONENT_NAME" VARCHAR2(128 BYTE), 
	"BAND_START_TIME" DATE, 
	"BAND_LENGTH" NUMBER, 
	"REPORT_ID" NUMBER, 
	"REPORT_GENERATION_TIME" DATE, 
	"PERIOD_START_TIME" DATE, 
	"PERIOD_END_TIME" DATE, 
	"KEY1" VARCHAR2(128 BYTE), 
	"KEY2" VARCHAR2(128 BYTE), 
	"KEY3" VARCHAR2(128 BYTE), 
	"KEY4" VARCHAR2(256 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
  PARTITION BY RANGE ("BAND_START_TIME") INTERVAL (NUMTODSINTERVAL(1, 'DAY')) 
 (PARTITION "P0"  VALUES LESS THAN (TO_DATE(' 2010-01-01 01:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ) ;
