--------------------------------------------------------
--  DDL for Table WRR$_REPLAY_COMMIT_REMAPPING
--------------------------------------------------------

  CREATE TABLE "SYS"."WRR$_REPLAY_COMMIT_REMAPPING" SHARING=METADATA 
   (	"FILE_ID" NUMBER(*,0), 
	"COMMIT_SCN" NUMBER(*,0), 
	"NEW_COMMIT_SCN" NUMBER(*,0), 
	 CONSTRAINT "WRR$_REPLAY_REMAPPING_PK" PRIMARY KEY ("FILE_ID", "COMMIT_SCN") ENABLE
   ) ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 PCTTHRESHOLD 50;
