--------------------------------------------------------
--  Constraints for Table WRR$_CAPTURE_FILE_DETAILS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRR$_CAPTURE_FILE_DETAILS" MODIFY ("CAP_FILE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_CAPTURE_FILE_DETAILS" MODIFY ("OBJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_CAPTURE_FILE_DETAILS" MODIFY ("ACTION_CODE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_CAPTURE_FILE_DETAILS" MODIFY ("NUM_CALLS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_CAPTURE_FILE_DETAILS" ADD CONSTRAINT "WRR$_CAPTURE_FILE_DETAILS_PK" PRIMARY KEY ("CAP_FILE_ID", "OBJECT_ID", "ACTION_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
