--------------------------------------------------------
--  Constraints for Table WRR$_REPLAY_DATA
--------------------------------------------------------

  ALTER TABLE "SYS"."WRR$_REPLAY_DATA" MODIFY ("SCHEDULE_CAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_DATA" MODIFY ("FILE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_DATA" MODIFY ("CALL_CTR" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_DATA" MODIFY ("RANK" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_DATA" MODIFY ("DATA_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_DATA" ADD CONSTRAINT "WRR$_REPLAY_DATA_PK" PRIMARY KEY ("FILE_ID", "CALL_CTR", "RANK", "DATA_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "SYSAUX"  ENABLE;
