--------------------------------------------------------
--  Constraints for Table WRR$_REPLAY_DIRECTORY
--------------------------------------------------------

  ALTER TABLE "SYS"."WRR$_REPLAY_DIRECTORY" MODIFY ("DIRECTORY" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_DIRECTORY" MODIFY ("DIR_PATH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_DIRECTORY" ADD CONSTRAINT "WRR$_REPLAY_DIRS_PK" PRIMARY KEY ("DIRECTORY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
