--------------------------------------------------------
--  Constraints for Table WRR$_CAPTURE_BUCKETS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRR$_CAPTURE_BUCKETS" MODIFY ("CAPTURE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_CAPTURE_BUCKETS" MODIFY ("BUCKET_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_CAPTURE_BUCKETS" ADD CONSTRAINT "WRR$_CAPTURE_BUCKETS_PK" PRIMARY KEY ("CAPTURE_ID", "BUCKET_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
