--------------------------------------------------------
--  DDL for Table WRR$_REPLAY_SQL_BINDS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRR$_REPLAY_SQL_BINDS" SHARING=METADATA 
   (	"CAPTURE_ID" NUMBER, 
	"FILE_ID" NUMBER, 
	"CALL_COUNTER" NUMBER, 
	"CAP_FILE_ID" NUMBER, 
	"ITERATION" NUMBER, 
	"BIND_POS" NUMBER, 
	"BIND_VARNAME" VARCHAR2(1000 BYTE), 
	"BIND_VALUE" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
