--------------------------------------------------------
--  Constraints for Table WRR$_REPLAY_GROUP_ASSIGNMENTS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRR$_REPLAY_GROUP_ASSIGNMENTS" MODIFY ("REPLAY_DIR_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_GROUP_ASSIGNMENTS" MODIFY ("INST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_GROUP_ASSIGNMENTS" MODIFY ("GID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_GROUP_ASSIGNMENTS" ADD CONSTRAINT "WRR$_REPLAY_GROUP_ASSIGNS_PK" PRIMARY KEY ("REPLAY_DIR_NUMBER", "INST_ID", "GID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
