--------------------------------------------------------
--  Constraints for Table WRR$_SCHEDULE_CAPTURES
--------------------------------------------------------

  ALTER TABLE "SYS"."WRR$_SCHEDULE_CAPTURES" MODIFY ("SCHEDULE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_SCHEDULE_CAPTURES" MODIFY ("SCHEDULE_CAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_SCHEDULE_CAPTURES" MODIFY ("CAPTURE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_SCHEDULE_CAPTURES" MODIFY ("CAPTURE_DIR" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_SCHEDULE_CAPTURES" MODIFY ("OS_SUBDIR" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_SCHEDULE_CAPTURES" MODIFY ("STOP_REPLAY" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_SCHEDULE_CAPTURES" MODIFY ("TAKE_BEGIN_SNAPSHOT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_SCHEDULE_CAPTURES" MODIFY ("TAKE_END_SNAPSHOT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_SCHEDULE_CAPTURES" MODIFY ("QUERY_ONLY" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_SCHEDULE_CAPTURES" ADD CONSTRAINT "WRR$_SCHEDULE_CAPTURES_PK" PRIMARY KEY ("SCHEDULE_NAME", "SCHEDULE_CAP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
