--------------------------------------------------------
--  DDL for Table WRR$_CAPTURE_STATS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRR$_CAPTURE_STATS" SHARING=METADATA 
   (	"ID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"STARTUP_TIME" DATE, 
	"HOST_NAME" VARCHAR2(64 BYTE), 
	"PARALLEL" VARCHAR2(3 BYTE), 
	"CAPTURE_SIZE" NUMBER, 
	"DBTIME" NUMBER, 
	"DBTIME_TSTART" NUMBER, 
	"DBTIME_TEND" NUMBER, 
	"USER_CALLS" NUMBER, 
	"USER_CALLS_TSTART" NUMBER, 
	"USER_CALLS_TEND" NUMBER, 
	"USER_CALLS_EMPTY" NUMBER, 
	"TXNS" NUMBER, 
	"TXNS_TSTART" NUMBER, 
	"TXNS_TEND" NUMBER, 
	"CONNECTS" NUMBER, 
	"CONNECTS_TSTART" NUMBER, 
	"CONNECTS_TEND" NUMBER, 
	"ERRORS" NUMBER, 
	"PLSQL_SUBCALL_SIZE" NUMBER(*,0), 
	"PLSQL_CALLS" NUMBER(*,0), 
	"PLSQL_SUBCALLS" NUMBER(*,0), 
	"PLSQL_DBTIME" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
