--------------------------------------------------------
--  DDL for Table WRR$_CAPTURE_LONG_SQLTEXT
--------------------------------------------------------

  CREATE TABLE "SYS"."WRR$_CAPTURE_LONG_SQLTEXT" SHARING=METADATA 
   (	"CAPTURE_ID" NUMBER(*,0), 
	"SQL_ID" VARCHAR2(13 BYTE), 
	"SQL_FULLTEXT" CLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" 
 LOB ("SQL_FULLTEXT") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
