--------------------------------------------------------
--  DDL for Table WRR$_REPLAY_SCN_ORDER
--------------------------------------------------------

  CREATE TABLE "SYS"."WRR$_REPLAY_SCN_ORDER" SHARING=METADATA 
   (	"CALL_ID" NUMBER, 
	"CALL_TIME" NUMBER, 
	"POST_COMMIT_SCN" NUMBER, 
	"STREAM_ID" NUMBER, 
	"MODULE" VARCHAR2(100 BYTE), 
	"ACTION" VARCHAR2(100 BYTE), 
	"ECID" VARCHAR2(100 BYTE), 
	"ECID_HASH" NUMBER, 
	"VALID" CHAR(1 BYTE), 
	"SCHEDULE_CAP_ID" NUMBER(*,0) DEFAULT 0, 
	"CALL_ELAPSED" NUMBER(*,0), 
	"CALL_TYPE" NUMBER(*,0), 
	 CONSTRAINT "WRR$_REPLAY_SCN_ORDER_PK" PRIMARY KEY ("SCHEDULE_CAP_ID", "POST_COMMIT_SCN", "STREAM_ID") ENABLE
   ) ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 PCTTHRESHOLD 50;
