--------------------------------------------------------
--  DDL for Table WRR$_REPLAY_SQL_TEXT
--------------------------------------------------------

  CREATE TABLE "SYS"."WRR$_REPLAY_SQL_TEXT" SHARING=METADATA 
   (	"SQL_ID" VARCHAR2(13 BYTE), 
	"SQL_TEXT" VARCHAR2(4000 BYTE), 
	"FULL_SQL_TEXT" CLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" 
 LOB ("FULL_SQL_TEXT") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
