--------------------------------------------------------
--  DDL for Table WRR$_REPLAY_DIVERGENCE
--------------------------------------------------------

  CREATE TABLE "SYS"."WRR$_REPLAY_DIVERGENCE" SHARING=METADATA 
   (	"ID" NUMBER, 
	"TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"TYPE" NUMBER, 
	"EXP_NUM_ROWS" NUMBER, 
	"OBS_NUM_ROWS" NUMBER, 
	"EXP_ERROR" NUMBER, 
	"OBS_ERROR" NUMBER, 
	"FILE_ID" NUMBER, 
	"CALL_COUNTER" NUMBER, 
	"CAP_FILE_ID" NUMBER, 
	"SQL_ID" VARCHAR2(13 BYTE), 
	"SESSION_ID" NUMBER, 
	"SESSION_SERIAL#" NUMBER, 
	"SERVICE" VARCHAR2(64 BYTE), 
	"MODULE" VARCHAR2(64 BYTE), 
	"ACTION" VARCHAR2(64 BYTE), 
	"SQL_PHASE" NUMBER, 
	"SQL_EXEC_CALL_CTR" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
