--------------------------------------------------------
--  Constraints for Table WRR$_COMPONENT_TIMING
--------------------------------------------------------

  ALTER TABLE "SYS"."WRR$_COMPONENT_TIMING" MODIFY ("INST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_COMPONENT_TIMING" MODIFY ("REPLAY_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_COMPONENT_TIMING" MODIFY ("COMP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_COMPONENT_TIMING" MODIFY ("COMP_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_COMPONENT_TIMING" MODIFY ("ELAPSED_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_COMPONENT_TIMING" MODIFY ("NUM_EXECS" NOT NULL ENABLE);
