--------------------------------------------------------
--  Constraints for Table WRR$_REPLAY_SCN_ORDER
--------------------------------------------------------

  ALTER TABLE "SYS"."WRR$_REPLAY_SCN_ORDER" MODIFY ("CALL_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_SCN_ORDER" MODIFY ("POST_COMMIT_SCN" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_SCN_ORDER" MODIFY ("STREAM_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_SCN_ORDER" MODIFY ("SCHEDULE_CAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_SCN_ORDER" ADD CONSTRAINT "WRR$_REPLAY_SCN_ORDER_PK" PRIMARY KEY ("SCHEDULE_CAP_ID", "POST_COMMIT_SCN", "STREAM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE;
