--------------------------------------------------------
--  Constraints for Table WRR$_FILTERS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRR$_FILTERS" MODIFY ("WRR_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_FILTERS" MODIFY ("FILTER_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_FILTERS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_FILTERS" MODIFY ("ATTRIBUTE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_FILTERS" MODIFY ("VALUE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_FILTERS" ADD CONSTRAINT "WRR$_FILTERS_PK" PRIMARY KEY ("WRR_ID", "FILTER_TYPE", "NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
