--------------------------------------------------------
--  Constraints for Table WRR$_REPLAY_SEQ_DATA
--------------------------------------------------------

  ALTER TABLE "SYS"."WRR$_REPLAY_SEQ_DATA" MODIFY ("SCHEDULE_CAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_SEQ_DATA" MODIFY ("FILE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_SEQ_DATA" MODIFY ("CALL_CTR" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_SEQ_DATA" MODIFY ("RANK" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_SEQ_DATA" MODIFY ("SEQ_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_SEQ_DATA" MODIFY ("SEQ_BNM" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_SEQ_DATA" MODIFY ("SEQ_BOW" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_SEQ_DATA" MODIFY ("FIRST_VALUE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_SEQ_DATA" ADD CONSTRAINT "WRR$_REPLAY_SEQ_DATA_PK" PRIMARY KEY ("SCHEDULE_CAP_ID", "FILE_ID", "CALL_CTR", "RANK", "SEQ_NAME", "SEQ_BNM", "SEQ_BOW")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "SYSAUX"  ENABLE;
