--------------------------------------------------------
--  DDL for Table WRR$_MASKING_DEFINITION
--------------------------------------------------------

  CREATE TABLE "SYS"."WRR$_MASKING_DEFINITION" SHARING=METADATA 
   (	"SCRIPT_ID" NUMBER, 
	"OWNER_NAME" VARCHAR2(128 BYTE), 
	"TABLE_NAME" VARCHAR2(128 BYTE), 
	"COLUMN_NAME" VARCHAR2(128 BYTE), 
	"COLUMNGROUP" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
