--------------------------------------------------------
--  Constraints for Table WRR$_REPLAYS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRR$_REPLAYS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAYS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAYS" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAYS" MODIFY ("DBNAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAYS" MODIFY ("DBVERSION" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAYS" MODIFY ("DIRECTORY" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAYS" MODIFY ("DIR_PATH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAYS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAYS" MODIFY ("NUM_CLIENTS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAYS" MODIFY ("NUM_CLIENTS_DONE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAYS" MODIFY ("DEFAULT_ACTION" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAYS" MODIFY ("SYNCHRONIZATION" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAYS" MODIFY ("CONNECT_TIME_SCALE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAYS" MODIFY ("THINK_TIME_SCALE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAYS" MODIFY ("THINK_TIME_AUTO_CORRECT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAYS" MODIFY ("SCALE_UP_MULTIPLIER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAYS" ADD CONSTRAINT "WRR$_REPLAYS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
