--------------------------------------------------------
--  Constraints for Table WRR$_CAPTURES
--------------------------------------------------------

  ALTER TABLE "SYS"."WRR$_CAPTURES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_CAPTURES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_CAPTURES" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_CAPTURES" MODIFY ("DBNAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_CAPTURES" MODIFY ("DBVERSION" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_CAPTURES" MODIFY ("DIRECTORY" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_CAPTURES" MODIFY ("DIR_PATH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_CAPTURES" MODIFY ("DIR_PATH_SHARED" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_CAPTURES" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_CAPTURES" MODIFY ("START_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_CAPTURES" MODIFY ("START_SCN" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_CAPTURES" MODIFY ("DEFAULT_ACTION" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_CAPTURES" ADD CONSTRAINT "WRR$_CAPTURES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
