--------------------------------------------------------
--  DDL for Table WRR$_REPLAY_DIV_SUMMARY
--------------------------------------------------------

  CREATE TABLE "SYS"."WRR$_REPLAY_DIV_SUMMARY" SHARING=METADATA 
   (	"REPLAY_ID" NUMBER, 
	"TYPE" NUMBER, 
	"FILE_ID" NUMBER, 
	"SQL_ID" VARCHAR2(13 BYTE), 
	"EXP_ERROR" NUMBER, 
	"OBS_ERROR" NUMBER, 
	"SERVICE" VARCHAR2(64 BYTE), 
	"MODULE" VARCHAR2(64 BYTE), 
	"OCCURRENCES" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
