--------------------------------------------------------
--  DDL for Index WRR$_WKLD_REPLAY_THREAD_IDX
--------------------------------------------------------

  CREATE INDEX "SYS"."WRR$_WKLD_REPLAY_THREAD_IDX" ON "SYS"."WRR$_WORKLOAD_REPLAY_THREAD" ("INST_ID", "FILE_ID", "REPLAY_DIR_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  LOCAL
 (PARTITION "WRR_REPLAY_THREAD_P1" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ) ;
