--------------------------------------------------------
--  DDL for Index WRR$_REPLAY_SCN_ORDER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."WRR$_REPLAY_SCN_ORDER_PK" ON "SYS"."WRR$_REPLAY_SCN_ORDER" ("SCHEDULE_CAP_ID", "POST_COMMIT_SCN", "STREAM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
