--------------------------------------------------------
--  DDL for Table WRR$_SCHEDULE_CAPTURES
--------------------------------------------------------

  CREATE TABLE "SYS"."WRR$_SCHEDULE_CAPTURES" SHARING=METADATA 
   (	"SCHEDULE_NAME" VARCHAR2(128 BYTE), 
	"SCHEDULE_CAP_ID" NUMBER, 
	"CAPTURE_ID" NUMBER, 
	"CAPTURE_DIR" VARCHAR2(128 BYTE), 
	"OS_SUBDIR" VARCHAR2(4000 BYTE), 
	"MAX_CONCURRENT_SESSIONS" NUMBER, 
	"NUM_CLIENTS_ASSIGNED" NUMBER, 
	"NUM_CLIENTS" NUMBER, 
	"NUM_CLIENTS_DONE" NUMBER, 
	"STOP_REPLAY" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"TAKE_BEGIN_SNAPSHOT" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"TAKE_END_SNAPSHOT" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"QUERY_ONLY" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"START_DELAY_SECS" NUMBER DEFAULT 0, 
	"DEPENDENT_LEVEL" NUMBER, 
	"START_TIME" DATE, 
	"END_TIME" DATE, 
	"AWR_DBID" NUMBER, 
	"AWR_BEGIN_SNAP" NUMBER, 
	"AWR_END_SNAP" NUMBER, 
	"STATUS" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
