--------------------------------------------------------
--  Constraints for Table WRR$_REPLAY_DIVERGENCE
--------------------------------------------------------

  ALTER TABLE "SYS"."WRR$_REPLAY_DIVERGENCE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_DIVERGENCE" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_DIVERGENCE" MODIFY ("FILE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_DIVERGENCE" MODIFY ("CALL_COUNTER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_DIVERGENCE" MODIFY ("SESSION_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_DIVERGENCE" MODIFY ("SESSION_SERIAL#" NOT NULL ENABLE);
