--------------------------------------------------------
--  Constraints for Table WRR$_REPLAY_COMMIT_REMAPPING
--------------------------------------------------------

  ALTER TABLE "SYS"."WRR$_REPLAY_COMMIT_REMAPPING" ADD CONSTRAINT "WRR$_REPLAY_REMAPPING_PK" PRIMARY KEY ("FILE_ID", "COMMIT_SCN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE;
