--------------------------------------------------------
--  DDL for Table WRR$_REPLAY_TRACKED_COMMITS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRR$_REPLAY_TRACKED_COMMITS" SHARING=METADATA 
   (	"REPLAY_DIR_NUMBER" NUMBER, 
	"INSTANCE_NUMBER" NUMBER(*,0), 
	"FILE_ID" NUMBER(*,0), 
	"CALL_CTR" NUMBER(*,0), 
	"COMMIT_SCN" NUMBER(*,0), 
	"PREV_GLOBAL_COMMIT_FILE_ID" NUMBER(*,0), 
	"PREV_GLOBAL_COMMIT_SCN" NUMBER(*,0), 
	"PREV_LOCAL_COMMIT_CALL_CTR" NUMBER(*,0), 
	"CAP_COMMIT_TIME" NUMBER(*,0), 
	"CAP_COMMIT_TIME_DELTA" NUMBER(*,0), 
	"REP_COMMIT_TIME" NUMBER(*,0), 
	"REP_COMMIT_TIME_DELTA" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
