--------------------------------------------------------
--  DDL for Table WRR$_WORKLOAD_ATTRIBUTES
--------------------------------------------------------

  CREATE TABLE "SYS"."WRR$_WORKLOAD_ATTRIBUTES" SHARING=METADATA 
   (	"CAPTURE_ID" NUMBER, 
	"REPLAY_ID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"VALUE" VARCHAR2(400 BYTE), 
	 CONSTRAINT "WRR$_WORKLOAD_ATTRIBUTES_PK" PRIMARY KEY ("CAPTURE_ID", "REPLAY_ID", "NAME") ENABLE
   ) ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 PCTTHRESHOLD 50;
