--------------------------------------------------------
--  DDL for Table WRR$_REPLAY_STATS
--------------------------------------------------------

  CREATE TABLE "SYS"."WRR$_REPLAY_STATS" SHARING=METADATA 
   (	"ID" NUMBER, 
	"INSTANCE_NUMBER" NUMBER, 
	"STARTUP_TIME" DATE, 
	"HOST_NAME" VARCHAR2(64 BYTE), 
	"PARALLEL" VARCHAR2(3 BYTE), 
	"USER_CALLS" NUMBER, 
	"DBTIME" NUMBER, 
	"NETWORK_TIME" NUMBER, 
	"THINK_TIME" NUMBER, 
	"TIME_GAIN" NUMBER, 
	"TIME_LOSS" NUMBER, 
	"TIME_PAUSED" NUMBER, 
	"PLSQL_CALLS" NUMBER(*,0), 
	"PLSQL_SUBCALLS" NUMBER(*,0), 
	"PLSQL_DBTIME" NUMBER(*,0), 
	"REPLAY_DEADLOCKS" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
