--------------------------------------------------------
--  Constraints for Table WRR$_REPLAY_SQL_BINDS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRR$_REPLAY_SQL_BINDS" MODIFY ("CAPTURE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_SQL_BINDS" MODIFY ("FILE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_SQL_BINDS" MODIFY ("CALL_COUNTER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_SQL_BINDS" MODIFY ("CAP_FILE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_SQL_BINDS" MODIFY ("ITERATION" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_SQL_BINDS" MODIFY ("BIND_POS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_SQL_BINDS" ADD CONSTRAINT "WRR$_REPLAY_SQL_BINDS_PK" PRIMARY KEY ("CAPTURE_ID", "FILE_ID", "CALL_COUNTER", "ITERATION", "BIND_POS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
