--------------------------------------------------------
--  Constraints for Table WRR$_WORKLOAD_ATTRIBUTES
--------------------------------------------------------

  ALTER TABLE "SYS"."WRR$_WORKLOAD_ATTRIBUTES" MODIFY ("CAPTURE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_WORKLOAD_ATTRIBUTES" MODIFY ("REPLAY_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_WORKLOAD_ATTRIBUTES" ADD CONSTRAINT "WRR$_WORKLOAD_ATTRIBUTES_PK" PRIMARY KEY ("CAPTURE_ID", "REPLAY_ID", "NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE;
