--------------------------------------------------------
--  DDL for Table WRR$_WORKLOAD_REPLAY_THREAD
--------------------------------------------------------

  CREATE TABLE "SYS"."WRR$_WORKLOAD_REPLAY_THREAD" SHARING=METADATA 
   (	"REPLAY_DIR_NUMBER" NUMBER, 
	"INST_ID" NUMBER, 
	"SID" NUMBER, 
	"SERIAL#" NUMBER, 
	"SPID" VARCHAR2(24 BYTE), 
	"LOGON_USER" VARCHAR2(128 BYTE), 
	"LOGON_TIME" DATE, 
	"FILE_ID" NUMBER, 
	"CALL_COUNTER" NUMBER, 
	"SESSION_TYPE" VARCHAR2(13 BYTE), 
	"WRC_ID" NUMBER, 
	"SCHEDULE_CAP_ID" NUMBER, 
	"FILE_NAME" VARCHAR2(51 BYTE), 
	"DBTIME" NUMBER, 
	"NETWORK_TIME" NUMBER, 
	"THINK_TIME" NUMBER, 
	"USER_CALLS" NUMBER, 
	"PLSQL_CALLS" NUMBER, 
	"PLSQL_SUBCALLS" NUMBER, 
	"PLSQL_DBTIME" NUMBER, 
	"CAPTURE_ELAPSED_TIME" NUMBER, 
	"REPLAY_ELAPSED_TIME" NUMBER, 
	"FLAGS" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARTITION BY LIST ("INST_ID") 
 (PARTITION "WRR_REPLAY_THREAD_P1"  VALUES (1) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ) ;
