--------------------------------------------------------
--  Constraints for Table WRR$_REPLAY_INSTANCES
--------------------------------------------------------

  ALTER TABLE "SYS"."WRR$_REPLAY_INSTANCES" MODIFY ("REPLAY_DIR_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_INSTANCES" MODIFY ("INST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_INSTANCES" ADD CONSTRAINT "WRR$_REPLAY_INSTANCES_PK" PRIMARY KEY ("REPLAY_DIR_NUMBER", "INST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
