--------------------------------------------------------
--  Constraints for Table WRR$_REPLAY_LOGIN_QUEUE
--------------------------------------------------------

  ALTER TABLE "SYS"."WRR$_REPLAY_LOGIN_QUEUE" MODIFY ("CAP_FILE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_LOGIN_QUEUE" MODIFY ("SLAVE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_LOGIN_QUEUE" ADD CONSTRAINT "WRR$_REPLAY_LOGIN_QUEUE_PK" PRIMARY KEY ("CAP_FILE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
