--------------------------------------------------------
--  Constraints for Table WRR$_WORKLOAD_EX_OBJECTS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRR$_WORKLOAD_EX_OBJECTS" MODIFY ("OBJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_WORKLOAD_EX_OBJECTS" MODIFY ("IGNORED_BY" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_WORKLOAD_EX_OBJECTS" ADD CONSTRAINT "WRR$_WORKLOAD_EX_OBJECTS_PK" PRIMARY KEY ("OBJECT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
