--------------------------------------------------------
--  Constraints for Table WRR$_CAPTURE_FILES
--------------------------------------------------------

  ALTER TABLE "SYS"."WRR$_CAPTURE_FILES" MODIFY ("CAP_FILE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_CAPTURE_FILES" MODIFY ("SLAVE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_CAPTURE_FILES" ADD CONSTRAINT "WRR$_CAPTURE_FILES_PK" PRIMARY KEY ("CAPTURE_ID", "CAP_FILE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
