--------------------------------------------------------
--  Constraints for Table WRR$_FILE_ID_MAP
--------------------------------------------------------

  ALTER TABLE "SYS"."WRR$_FILE_ID_MAP" MODIFY ("CAP_FILE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_FILE_ID_MAP" MODIFY ("SCHEDULE_CAP_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_FILE_ID_MAP" ADD CONSTRAINT "WRR$_FILE_ID_MAP_PK" PRIMARY KEY ("CAP_FILE_ID", "SCHEDULE_CAP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
