--------------------------------------------------------
--  Constraints for Table WRR$_CONNECTION_MAP
--------------------------------------------------------

  ALTER TABLE "SYS"."WRR$_CONNECTION_MAP" MODIFY ("REPLAY_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_CONNECTION_MAP" MODIFY ("CONN_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_CONNECTION_MAP" MODIFY ("CAPTURE_CONN" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_CONNECTION_MAP" ADD CONSTRAINT "WRR$_CONNECTION_MAP_PK" PRIMARY KEY ("REPLAY_ID", "CONN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
