--------------------------------------------------------
--  DDL for Table WRR$_REPLAY_SEQ_DATA
--------------------------------------------------------

  CREATE TABLE "SYS"."WRR$_REPLAY_SEQ_DATA" SHARING=METADATA 
   (	"SCHEDULE_CAP_ID" NUMBER DEFAULT 0, 
	"FILE_ID" NUMBER, 
	"CALL_CTR" NUMBER, 
	"RANK" NUMBER, 
	"SEQ_NAME" VARCHAR2(128 BYTE), 
	"SEQ_BNM" VARCHAR2(128 BYTE), 
	"SEQ_BOW" VARCHAR2(128 BYTE), 
	"FIRST_VALUE" NUMBER, 
	"LAST_VALUE" NUMBER, 
	"CHANGE" NUMBER, 
	"NUM_VALUES" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "SYSAUX" ;
