--------------------------------------------------------
--  Constraints for Table WRR$_REPLAY_SCHEDULES
--------------------------------------------------------

  ALTER TABLE "SYS"."WRR$_REPLAY_SCHEDULES" MODIFY ("SCHEDULE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_SCHEDULES" MODIFY ("DIRECTORY" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_SCHEDULES" ADD CONSTRAINT "WRR$_REPLAY_SCHEDULES_PK" PRIMARY KEY ("SCHEDULE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
