--------------------------------------------------------
--  Constraints for Table WRR$_WORKLOAD_GROUPS
--------------------------------------------------------

  ALTER TABLE "SYS"."WRR$_WORKLOAD_GROUPS" MODIFY ("GID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_WORKLOAD_GROUPS" MODIFY ("CONCURRENCY" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_WORKLOAD_GROUPS" MODIFY ("NUM_FILES" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_WORKLOAD_GROUPS" MODIFY ("NUM_CALLS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_WORKLOAD_GROUPS" MODIFY ("DB_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_WORKLOAD_GROUPS" ADD CONSTRAINT "WRR$_WORKLOAD_GROUPS_PK" PRIMARY KEY ("GID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
