--------------------------------------------------------
--  Constraints for Table WRR$_REPLAY_FILTER_SET
--------------------------------------------------------

  ALTER TABLE "SYS"."WRR$_REPLAY_FILTER_SET" MODIFY ("CAPTURE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_FILTER_SET" MODIFY ("SET_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_FILTER_SET" MODIFY ("FILTER_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_FILTER_SET" MODIFY ("ATTRIBUTE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_FILTER_SET" MODIFY ("VALUE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRR$_REPLAY_FILTER_SET" ADD CONSTRAINT "WRR$_REPLAY_FILTER_SET_PK" PRIMARY KEY ("CAPTURE_ID", "SET_NAME", "FILTER_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
