--------------------------------------------------------
--  Constraints for Table WRW$_WAREHOUSE_CONFIG
--------------------------------------------------------

  ALTER TABLE "SYS"."WRW$_WAREHOUSE_CONFIG" MODIFY ("NODE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRW$_WAREHOUSE_CONFIG" MODIFY ("NODE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRW$_WAREHOUSE_CONFIG" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRW$_WAREHOUSE_CONFIG" MODIFY ("WAREHOUSE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRW$_WAREHOUSE_CONFIG" MODIFY ("MAILBOX" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRW$_WAREHOUSE_CONFIG" MODIFY ("CONFIG_STATE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRW$_WAREHOUSE_CONFIG" ADD CONSTRAINT "WRW$_WAREHOUSE_CONFIG_PK" PRIMARY KEY ("NODE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
  ALTER TABLE "SYS"."WRW$_WAREHOUSE_CONFIG" ADD CONSTRAINT "WRW$_WAREHOUSE_CONFIG_U" UNIQUE ("NODE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
