--------------------------------------------------------
--  Constraints for Table WRW$_CLIENT_DELIVERY_SVC
--------------------------------------------------------

  ALTER TABLE "SYS"."WRW$_CLIENT_DELIVERY_SVC" MODIFY ("SERVICE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRW$_CLIENT_DELIVERY_SVC" MODIFY ("SERVICE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRW$_CLIENT_DELIVERY_SVC" ADD CONSTRAINT "WRW$_CLIENT_DELIVERY_SVC_PK" PRIMARY KEY ("SERVICE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
