--------------------------------------------------------
--  DDL for Table WRWS$_WAREHOUSE_REGISTRATION
--------------------------------------------------------

  CREATE TABLE "SYS"."WRWS$_WAREHOUSE_REGISTRATION" SHARING=METADATA 
   (	"CLIENT_NAME" VARCHAR2(128 BYTE), 
	"SRC_DBID" NUMBER, 
	"WH_DBID" NUMBER, 
	"QUEUE_MAILBOX" VARCHAR2(128 BYTE), 
	"UPLOAD_MAILBOX" VARCHAR2(128 BYTE), 
	"REGISTRATION_STATE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
