--------------------------------------------------------
--  Constraints for Table WRWS$_WAREHOUSE_REGISTRATION
--------------------------------------------------------

  ALTER TABLE "SYS"."WRWS$_WAREHOUSE_REGISTRATION" MODIFY ("CLIENT_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRWS$_WAREHOUSE_REGISTRATION" MODIFY ("SRC_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRWS$_WAREHOUSE_REGISTRATION" MODIFY ("WH_DBID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRWS$_WAREHOUSE_REGISTRATION" MODIFY ("QUEUE_MAILBOX" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRWS$_WAREHOUSE_REGISTRATION" MODIFY ("UPLOAD_MAILBOX" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRWS$_WAREHOUSE_REGISTRATION" MODIFY ("REGISTRATION_STATE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."WRWS$_WAREHOUSE_REGISTRATION" ADD CONSTRAINT "WRWS$_WAREHOUSE_REG_PK" PRIMARY KEY ("CLIENT_NAME", "SRC_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
  ALTER TABLE "SYS"."WRWS$_WAREHOUSE_REGISTRATION" ADD CONSTRAINT "WRWS$_WAREHOUSE_REG_U" UNIQUE ("WH_DBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
