--------------------------------------------------------
--  DDL for Operator XMLSEQUENCE
--------------------------------------------------------

  CREATE OR REPLACE OPERATOR "SYS"."XMLSEQUENCE" BINDING
	("SYS"."XMLTYPE") RETURN "SYS"."XMLSEQUENCETYPE"
	   USING "SYS"."XMLSEQUENCEFROMXMLTYPE",
	("STANDARD"."SYS_REFCURSOR", "SYS"."XMLGENFORMATTYPE") RETURN "SYS"."XMLSEQUENCETYPE"
	   USING "SYS"."XMLSEQUENCEFROMREFCURSOR",
	("STANDARD"."SYS_REFCURSOR") RETURN "SYS"."XMLSEQUENCETYPE"
	   USING "SYS"."XMLSEQUENCEFROMREFCURSOR2";
  GRANT EXECUTE ON "SYS"."XMLSEQUENCE" TO PUBLIC WITH GRANT OPTION;
