--------------------------------------------------------
--  DDL for Operator XQWINDOWSEQUENCE
--------------------------------------------------------

  CREATE OR REPLACE OPERATOR "SYS"."XQWINDOWSEQUENCE" BINDING
	("SYS"."XMLTYPE", NUMBER, VARCHAR2, VARCHAR2, "SYS"."XMLTYPE", "SYS"."XMLTYPE", "SYS"."XMLTYPE", "SYS"."XMLTYPE", "SYS"."XMLTYPE", "SYS"."XMLTYPE", "SYS"."XMLTYPE", "SYS"."XMLTYPE") RETURN "SYS"."XMLSEQUENCETYPE"
	   USING "SYS"."XQWINDOWSEQUENCEFROMXMLTYPE";
  GRANT EXECUTE ON "SYS"."XQWINDOWSEQUENCE" TO PUBLIC WITH GRANT OPTION;
