--------------------------------------------------------
--  DDL for Table XS$AGGR_PRIV
--------------------------------------------------------

  CREATE TABLE "SYS"."XS$AGGR_PRIV" SHARING=METADATA 
   (	"SC#" NUMBER, 
	"AGGR_PRIV#" NUMBER, 
	"IMPLIED_PRIV#" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  GRANT SELECT ON "SYS"."XS$AGGR_PRIV" TO "XS_CACHE_ADMIN";
