--------------------------------------------------------
--  Constraints for Table XS$CACHE_ACTIONS
--------------------------------------------------------

  ALTER TABLE "SYS"."XS$CACHE_ACTIONS" MODIFY ("TIME_VAL" NOT NULL ENABLE);
  ALTER TABLE "SYS"."XS$CACHE_ACTIONS" ADD UNIQUE ("ROW_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
