--------------------------------------------------------
--  DDL for Table XS$NSTMPL_ATTR
--------------------------------------------------------

  CREATE TABLE "SYS"."XS$NSTMPL_ATTR" SHARING=METADATA 
   (	"NS#" NUMBER, 
	"ATTR_NAME" VARCHAR2(4000 BYTE), 
	"DEF_VALUE" VARCHAR2(4000 BYTE), 
	"EVENT_CBK" NUMBER DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
