REM INSERTING into SYS.XS$NSTMPL_ATTR
SET DEFINE OFF;
Insert into SYS.XS$NSTMPL_ATTR (NS#,ATTR_NAME,DEF_VALUE,EVENT_CBK) values (2147483680,'NLS_LANGUAGE',null,0);
Insert into SYS.XS$NSTMPL_ATTR (NS#,ATTR_NAME,DEF_VALUE,EVENT_CBK) values (2147483680,'NLS_TERRITORY',null,0);
Insert into SYS.XS$NSTMPL_ATTR (NS#,ATTR_NAME,DEF_VALUE,EVENT_CBK) values (2147483680,'NLS_SORT',null,0);
Insert into SYS.XS$NSTMPL_ATTR (NS#,ATTR_NAME,DEF_VALUE,EVENT_CBK) values (2147483680,'NLS_DATE_LANGUAGE',null,0);
Insert into SYS.XS$NSTMPL_ATTR (NS#,ATTR_NAME,DEF_VALUE,EVENT_CBK) values (2147483680,'NLS_DATE_FORMAT',null,0);
Insert into SYS.XS$NSTMPL_ATTR (NS#,ATTR_NAME,DEF_VALUE,EVENT_CBK) values (2147483680,'NLS_CURRENCY',null,0);
Insert into SYS.XS$NSTMPL_ATTR (NS#,ATTR_NAME,DEF_VALUE,EVENT_CBK) values (2147483680,'NLS_NUMERIC_CHARACTERS',null,0);
Insert into SYS.XS$NSTMPL_ATTR (NS#,ATTR_NAME,DEF_VALUE,EVENT_CBK) values (2147483680,'NLS_ISO_CURRENCY',null,0);
Insert into SYS.XS$NSTMPL_ATTR (NS#,ATTR_NAME,DEF_VALUE,EVENT_CBK) values (2147483680,'NLS_CALENDAR',null,0);
Insert into SYS.XS$NSTMPL_ATTR (NS#,ATTR_NAME,DEF_VALUE,EVENT_CBK) values (2147483680,'NLS_TIME_FORMAT',null,0);
Insert into SYS.XS$NSTMPL_ATTR (NS#,ATTR_NAME,DEF_VALUE,EVENT_CBK) values (2147483680,'NLS_TIMESTAMP_FORMAT',null,0);
Insert into SYS.XS$NSTMPL_ATTR (NS#,ATTR_NAME,DEF_VALUE,EVENT_CBK) values (2147483680,'NLS_TIME_TZ_FORMAT',null,0);
Insert into SYS.XS$NSTMPL_ATTR (NS#,ATTR_NAME,DEF_VALUE,EVENT_CBK) values (2147483680,'NLS_TIMESTAMP_TZ_FORMAT',null,0);
Insert into SYS.XS$NSTMPL_ATTR (NS#,ATTR_NAME,DEF_VALUE,EVENT_CBK) values (2147483680,'NLS_DUAL_CURRENCY',null,0);
Insert into SYS.XS$NSTMPL_ATTR (NS#,ATTR_NAME,DEF_VALUE,EVENT_CBK) values (2147483680,'NLS_COMP',null,0);
Insert into SYS.XS$NSTMPL_ATTR (NS#,ATTR_NAME,DEF_VALUE,EVENT_CBK) values (2147483680,'NLS_LENGTH_SEMANTICS',null,0);
Insert into SYS.XS$NSTMPL_ATTR (NS#,ATTR_NAME,DEF_VALUE,EVENT_CBK) values (2147483680,'NLS_NCHAR_CONV_EXCP',null,0);
