--------------------------------------------------------
--  DDL for Table XS$OLAP_POLICY
--------------------------------------------------------

  CREATE TABLE "SYS"."XS$OLAP_POLICY" SHARING=METADATA 
   (	"SCHEMA_NAME" VARCHAR2(128 BYTE), 
	"LOGICAL_NAME" VARCHAR2(128 BYTE), 
	"POLICY_NAME" VARCHAR2(128 BYTE), 
	"POLICY_SCHEMA" VARCHAR2(128 BYTE), 
	"ENABLE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
  GRANT SELECT ON "SYS"."XS$OLAP_POLICY" TO "OLAP_XS_ADMIN";
