--------------------------------------------------------
--  DDL for Table XS$OBJ
--------------------------------------------------------

  CREATE TABLE "SYS"."XS$OBJ" SHARING=METADATA 
   (	"NAME" VARCHAR2(128 BYTE), 
	"WS" VARCHAR2(128 BYTE) DEFAULT 'XS', 
	"OWNER" VARCHAR2(128 BYTE) DEFAULT 'SYS', 
	"TENANT" VARCHAR2(128 BYTE) DEFAULT 'SYSTEM', 
	"ID" NUMBER, 
	"TYPE" NUMBER, 
	"STATUS" NUMBER, 
	"FLAGS" NUMBER DEFAULT 0, 
	"EARLY_DEP_CNT" NUMBER DEFAULT 0, 
	"LATE_DEP_CNT" NUMBER DEFAULT 0, 
	"ACLID" NUMBER DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  GRANT SELECT ON "SYS"."XS$OBJ" TO "XS_CACHE_ADMIN";
  GRANT READ ON "SYS"."XS$OBJ" TO "DVSYS";
