--------------------------------------------------------
--  DDL for Table XS$PRIN
--------------------------------------------------------

  CREATE TABLE "SYS"."XS$PRIN" SHARING=METADATA 
   (	"PRIN#" NUMBER, 
	"TYPE" NUMBER, 
	"GUID" RAW(16), 
	"EXT_SRC" VARCHAR2(128 BYTE), 
	"START_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"END_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"SCHEMA" VARCHAR2(128 BYTE), 
	"TABLESPACE" VARCHAR2(30 BYTE), 
	"CREDENTIAL" VARCHAR2(128 BYTE), 
	"FAILEDLOGINS" NUMBER, 
	"ENABLE" NUMBER DEFAULT 0, 
	"DURATION" NUMBER, 
	"SYSTEM" NUMBER DEFAULT 0, 
	"SCOPE" NUMBER DEFAULT 0, 
	"POWNER" VARCHAR2(128 BYTE), 
	"PNAME" VARCHAR2(128 BYTE), 
	"PFNAME" VARCHAR2(128 BYTE), 
	"OBJACL#" NUMBER, 
	"NOTE" VARCHAR2(4000 BYTE), 
	"STATUS" NUMBER DEFAULT 1, 
	"CTIME" TIMESTAMP (6), 
	"MTIME" TIMESTAMP (6), 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"PROFILE#" NUMBER DEFAULT 0, 
	"PTIME" DATE, 
	"EXPTIME" DATE, 
	"LTIME" DATE, 
	"LSLOGONTIME" DATE, 
	"ASTATUS" NUMBER DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  GRANT SELECT ON "SYS"."XS$PRIN" TO "XS_CACHE_ADMIN";
