--------------------------------------------------------
--  DDL for Table XSTREAM$_SERVER_CONNECTION
--------------------------------------------------------

  CREATE TABLE "SYS"."XSTREAM$_SERVER_CONNECTION" SHARING=METADATA 
   (	"OUTBOUND_SERVER" VARCHAR2(128 BYTE), 
	"INBOUND_SERVER" VARCHAR2(128 BYTE), 
	"INBOUND_SERVER_DBLINK" VARCHAR2(128 BYTE), 
	"OUTBOUND_QUEUE_OWNER" VARCHAR2(128 BYTE), 
	"OUTBOUND_QUEUE_NAME" VARCHAR2(128 BYTE), 
	"INBOUND_QUEUE_OWNER" VARCHAR2(128 BYTE), 
	"INBOUND_QUEUE_NAME" VARCHAR2(128 BYTE), 
	"RULE_SET_OWNER" VARCHAR2(128 BYTE), 
	"RULE_SET_NAME" VARCHAR2(128 BYTE), 
	"NEGATIVE_RULE_SET_OWNER" VARCHAR2(128 BYTE), 
	"NEGATIVE_RULE_SET_NAME" VARCHAR2(128 BYTE), 
	"FLAGS" NUMBER, 
	"STATUS" NUMBER, 
	"CREATE_DATE" DATE, 
	"ERROR_MESSAGE" VARCHAR2(4000 BYTE), 
	"ERROR_DATE" DATE, 
	"ACKED_SCN" NUMBER, 
	"AUTO_MERGE_THRESHOLD" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(4000 BYTE), 
	"SPARE4" VARCHAR2(4000 BYTE), 
	"SPARE5" VARCHAR2(4000 BYTE), 
	"SPARE6" VARCHAR2(4000 BYTE), 
	"SPARE7" DATE, 
	"SPARE8" DATE, 
	"SPARE9" RAW(2000), 
	"SPARE10" RAW(2000)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
