--------------------------------------------------------
--  Constraints for Table XSTREAM$_SUBSET_RULES
--------------------------------------------------------

  ALTER TABLE "SYS"."XSTREAM$_SUBSET_RULES" MODIFY ("SERVER_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."XSTREAM$_SUBSET_RULES" MODIFY ("RULES_OWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."XSTREAM$_SUBSET_RULES" MODIFY ("INSERT_RULE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."XSTREAM$_SUBSET_RULES" MODIFY ("DELETE_RULE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."XSTREAM$_SUBSET_RULES" MODIFY ("UPDATE_RULE" NOT NULL ENABLE);
