--------------------------------------------------------
--  Constraints for Table XSTREAM$_HANDLE_COLLISIONS
--------------------------------------------------------

  ALTER TABLE "SYS"."XSTREAM$_HANDLE_COLLISIONS" MODIFY ("APPLY_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."XSTREAM$_HANDLE_COLLISIONS" MODIFY ("SCHEMA_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."XSTREAM$_HANDLE_COLLISIONS" MODIFY ("TABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."XSTREAM$_HANDLE_COLLISIONS" MODIFY ("SOURCE_SCHEMA_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."XSTREAM$_HANDLE_COLLISIONS" MODIFY ("SOURCE_TABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."XSTREAM$_HANDLE_COLLISIONS" MODIFY ("HANDLE_COLLISIONS" NOT NULL ENABLE);
