--------------------------------------------------------
--  DDL for Table XSTREAM$_DML_CONFLICT_HANDLER
--------------------------------------------------------

  CREATE TABLE "SYS"."XSTREAM$_DML_CONFLICT_HANDLER" SHARING=METADATA 
   (	"OBJECT_NAME" VARCHAR2(128 BYTE), 
	"SCHEMA_NAME" VARCHAR2(128 BYTE), 
	"APPLY_NAME" VARCHAR2(128 BYTE), 
	"CONFLICT_TYPE" NUMBER, 
	"USER_ERROR" NUMBER, 
	"OPNUM" NUMBER, 
	"METHOD_TXT" CLOB, 
	"METHOD_NAME" VARCHAR2(4000 BYTE), 
	"OLD_OBJECT" VARCHAR2(128 BYTE), 
	"OLD_SCHEMA" VARCHAR2(128 BYTE), 
	"METHOD_NUM" NUMBER, 
	"CONFLICT_HANDLER_NAME" VARCHAR2(128 BYTE), 
	"RESOLUTION_COLUMN" VARCHAR2(128 BYTE), 
	"CONFLICT_HANDLER_ID" NUMBER, 
	"SET_BY" NUMBER DEFAULT NULL, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" TIMESTAMP (6), 
	"SPARE5" VARCHAR2(4000 BYTE), 
	"SPARE6" VARCHAR2(4000 BYTE), 
	"SPARE7" RAW(64), 
	"SPARE8" DATE, 
	"SPARE9" CLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("METHOD_TXT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("SPARE9") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
