--------------------------------------------------------
--  DDL for Table XSTREAM$_DML_CONFLICT_COLUMNS
--------------------------------------------------------

  CREATE TABLE "SYS"."XSTREAM$_DML_CONFLICT_COLUMNS" SHARING=METADATA 
   (	"CONFLICT_HANDLER_ID" NUMBER, 
	"COLUMN_NAME" VARCHAR2(128 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" TIMESTAMP (6), 
	"SPARE5" VARCHAR2(4000 BYTE), 
	"SPARE6" VARCHAR2(4000 BYTE), 
	"SPARE7" RAW(64), 
	"SPARE8" DATE, 
	"SPARE9" CLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("SPARE9") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
