--------------------------------------------------------
--  DDL for Table XSTREAM$_MAP
--------------------------------------------------------

  CREATE TABLE "SYS"."XSTREAM$_MAP" SHARING=METADATA 
   (	"APPLY_NAME" VARCHAR2(128 BYTE), 
	"SRC_OBJ_OWNER" VARCHAR2(128 BYTE), 
	"SRC_OBJ_NAME" VARCHAR2(128 BYTE), 
	"TGT_OBJ_OWNER" VARCHAR2(128 BYTE), 
	"TGT_OBJ_NAME" VARCHAR2(128 BYTE), 
	"COLMAP" CLOB, 
	"SQLEXEC" CLOB, 
	"SEQUENCE" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" TIMESTAMP (6), 
	"SPARE5" VARCHAR2(4000 BYTE), 
	"SPARE6" VARCHAR2(4000 BYTE), 
	"SPARE7" CLOB, 
	"SPARE8" CLOB, 
	"SPARE9" RAW(100)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("COLMAP") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("SQLEXEC") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("SPARE7") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("SPARE8") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
