--------------------------------------------------------
--  Constraints for Table XSTREAM$_SYSGEN_OBJS
--------------------------------------------------------

  ALTER TABLE "SYS"."XSTREAM$_SYSGEN_OBJS" MODIFY ("SERVER_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."XSTREAM$_SYSGEN_OBJS" MODIFY ("OBJECT_OWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."XSTREAM$_SYSGEN_OBJS" MODIFY ("OBJECT_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."XSTREAM$_SYSGEN_OBJS" MODIFY ("OBJECT_TYPE" NOT NULL ENABLE);
