--------------------------------------------------------
--  DDL for Table XSTREAM$_HANDLE_COLLISIONS
--------------------------------------------------------

  CREATE TABLE "SYS"."XSTREAM$_HANDLE_COLLISIONS" SHARING=METADATA 
   (	"APPLY_NAME" VARCHAR2(128 BYTE), 
	"SCHEMA_NAME" VARCHAR2(128 BYTE), 
	"TABLE_NAME" VARCHAR2(128 BYTE), 
	"SOURCE_SCHEMA_NAME" VARCHAR2(128 BYTE), 
	"SOURCE_TABLE_NAME" VARCHAR2(128 BYTE), 
	"HANDLE_COLLISIONS" VARCHAR2(1 BYTE), 
	"SET_BY" NUMBER DEFAULT NULL, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" TIMESTAMP (6), 
	"SPARE5" VARCHAR2(4000 BYTE), 
	"SPARE6" VARCHAR2(4000 BYTE), 
	"SPARE7" RAW(64), 
	"SPARE8" DATE, 
	"SPARE9" CLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" 
 LOB ("SPARE9") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
