--------------------------------------------------------
--  Constraints for Table XSTREAM$_REPERROR_HANDLER
--------------------------------------------------------

  ALTER TABLE "SYS"."XSTREAM$_REPERROR_HANDLER" MODIFY ("APPLY_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."XSTREAM$_REPERROR_HANDLER" MODIFY ("SCHEMA_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."XSTREAM$_REPERROR_HANDLER" MODIFY ("TABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."XSTREAM$_REPERROR_HANDLER" MODIFY ("SOURCE_SCHEMA_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."XSTREAM$_REPERROR_HANDLER" MODIFY ("SOURCE_TABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."XSTREAM$_REPERROR_HANDLER" MODIFY ("ERROR_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."XSTREAM$_REPERROR_HANDLER" MODIFY ("METHOD" NOT NULL ENABLE);
