--------------------------------------------------------
--  DDL for Table XSTREAM$_SERVER
--------------------------------------------------------

  CREATE TABLE "SYS"."XSTREAM$_SERVER" SHARING=METADATA 
   (	"SERVER_NAME" VARCHAR2(128 BYTE), 
	"APP_SRC_DATABASE" VARCHAR2(128 BYTE) DEFAULT null, 
	"CAPTURE_NAME" VARCHAR2(128 BYTE) DEFAULT NULL, 
	"CAP_SRC_DATABASE" VARCHAR2(128 BYTE) DEFAULT null, 
	"QUEUE_OWNER" VARCHAR2(128 BYTE), 
	"QUEUE_NAME" VARCHAR2(128 BYTE), 
	"FLAGS" NUMBER, 
	"USER_COMMENT" VARCHAR2(4000 BYTE), 
	"CREATE_DATE" TIMESTAMP (6), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" TIMESTAMP (6), 
	"SPARE5" VARCHAR2(4000 BYTE), 
	"SPARE6" VARCHAR2(4000 BYTE), 
	"STATUS_CHANGE_TIME" DATE, 
	"CONNECT_USER" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
