--------------------------------------------------------
--  DDL for Procedure COBORROWERDATA_TEMP_20240606
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" 
AS
   v_EffectiveFromTimeKey NUMBER(10,0) := ( SELECT TimeKey 
     FROM RBL_MISDB_PROD.Automate_Advances 
    WHERE  EXT_FLG = 'Y' );

BEGIN

   EXECUTE IMMEDIATE ' TRUNCATE TABLE RBL_TEMPDB.TempCoBorrowerData_20240606 ';
   INSERT INTO RBL_TEMPDB.TempCoBorrowerData_20240606
     ( SrcSystem_PriAccount, UCCIF_PriAccount, CustId_PriAccount, AcNo_PriAccount, UCCIF_CoBorrower, EffectiveFromTimeKey, EffectiveToTimeKey, CreatedBy, DateCreated, ModifiedBy, DateModified, ApprovedBy, DateApproved )
     ( SELECT SourceSystemName_PrimaryAccount SrcSystem_PriAccount  ,
              UCCIFID_PrimaryAccount UCCIF_PriAccount  ,
              CustomerId_PrimaryAccount CustId_PriAccount  ,
              CustomerACID_PrimaryAccount AcNo_PriAccount  ,
              UCIFID_COBORROWER UCCIF_CoBorrower  ,
              v_EffectiveFromTimeKey EffectiveFromTimeKey  ,
              '49999' EffectiveToTimeKey  ,
              'D2K' CreatedBy  ,
              SYSDATE DateCreated  ,
              NULL ModifiedBy  ,
              NULL DateModified  ,
              NULL ApprovedBy  ,
              NULL DateApproved  
       FROM RBL_STGDB.CoBorrower_STG_20240606  );

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "MAIN_PRO";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "RBL_STGDB";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "MAIN_PRO";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "RBL_STGDB";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "RBL_TEMPDB";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "ETL_MAIN_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_TEMP_RBL_TEMPDB"."COBORROWERDATA_TEMP_20240606" TO "ADF_CDR_RBL_STGDB";
