--------------------------------------------------------
--  File created - Wednesday-March-19-2025   
--------------------------------------------------------
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DWH_SCRIPTS\ALL_CUSTOMER_EXPOSURE_DETAIL.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DWH_SCRIPTS\BILLS_DATA_STG_SCF.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DWH_SCRIPTS\CONSTITUTION_CODE.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DWH_SCRIPTS\GLBAL.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DWH_SCRIPTS\INVESTMENTISSUERDETAIL.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DWH_SCRIPTS\WRITEOFFDATA.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DWH_SCRIPTS\WRITEOFFDATA_SCF.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DWH_SCRIPTS\ALL_CUSTOMER_EXPOSURE_DETAIL_DATA_TABLE.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DWH_SCRIPTS\BILLS_DATA_STG_SCF_DATA_TABLE.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DWH_SCRIPTS\CONSTITUTION_CODE_DATA_TABLE.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DWH_SCRIPTS\GLBAL_DATA_TABLE.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DWH_SCRIPTS\INVESTMENTISSUERDETAIL_DATA_TABLE.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DWH_SCRIPTS\WRITEOFFDATA_DATA_TABLE.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DWH_SCRIPTS\WRITEOFFDATA_SCF_DATA_TABLE.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DWH_SCRIPTS\UTILS.sql
