--------------------------------------------------------
--  File created - Wednesday-March-19-2025   
--------------------------------------------------------
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DWH_STG_SCRIPTS\ACCOUNT_DATA_FINACLE.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DWH_STG_SCRIPTS\COBORROWERDATA.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DWH_STG_SCRIPTS\CURRENCY_RATE_MASTER.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DWH_STG_SCRIPTS\PRODUCT_CODE_MASTER.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DWH_STG_SCRIPTS\PRODUCT_CODE_MASTER_FINACLE.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DWH_STG_SCRIPTS\PRODUCT_CODE_MASTER_FIS.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DWH_STG_SCRIPTS\PRODUCT_CODE_MASTER_MIFIN.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DWH_STG_SCRIPTS\PRODUCT_CODE_MASTER_VISIONPLUS.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DWH_STG_SCRIPTS\PRODUCT_MASTER_ECBF.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DWH_STG_SCRIPTS\REVERSEFEED_CALYPSO.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DWH_STG_SCRIPTS\ACCOUNT_DATA_FINACLE_DATA_TABLE.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DWH_STG_SCRIPTS\COBORROWERDATA_DATA_TABLE.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DWH_STG_SCRIPTS\CURRENCY_RATE_MASTER_DATA_TABLE.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DWH_STG_SCRIPTS\PRODUCT_CODE_MASTER_DATA_TABLE.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DWH_STG_SCRIPTS\PRODUCT_CODE_MASTER_FINACLE_DATA_TABLE.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DWH_STG_SCRIPTS\PRODUCT_CODE_MASTER_FIS_DATA_TABLE.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DWH_STG_SCRIPTS\PRODUCT_CODE_MASTER_MIFIN_DATA_TABLE.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DWH_STG_SCRIPTS\PRODUCT_CODE_MASTER_VISIONPLUS_DATA_TABLE.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DWH_STG_SCRIPTS\PRODUCT_MASTER_ECBF_DATA_TABLE.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_DWH_STG_SCRIPTS\REVERSEFEED_CALYPSO_DATA_TABLE.sql
