--------------------------------------------------------
--  DDL for Procedure ADVSECURITYVALUEDETAIL_MAIN_29032022
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" 
-- =============================================
 -- Author:		<Author,,Name>
 -- Create date: <Create Date,,>
 -- Description:	<Description,,>
 -- =============================================

AS
   -- SET NOCOUNT ON added to prevent extra result sets from
   -- interfering with SELECT statements.
   v_VEFFECTIVETO NUMBER(10,0);
-- Add the parameters for the stored procedure here

BEGIN

   SELECT TIMEKEY - 1 

     INTO v_VEFFECTIVETO
     FROM RBL_MISDB.AUTOMATE_ADVANCES 
    WHERE  EXT_FLG = 'Y';
   ----------For New Records
   MERGE INTO A 
   USING (SELECT A.ROWID row_id, 'N'
   FROM A ,RBL_TEMPDB.TempAdvSecurityValueDetail A 
    WHERE NOT EXISTS ( SELECT 1 
                       FROM RBL_MISDB_PROD.AdvSecurityValueDetail B
                        WHERE  B.EffectiveToTimeKey = 49999
                                 AND A.SecurityEntityID = B.SecurityEntityID )) src
   ON ( A.ROWID = src.row_id )
   WHEN MATCHED THEN UPDATE SET A.IsChanged
                                ----Select * 
                                 = 'N';
   MERGE INTO O 
   USING (SELECT O.ROWID row_id, v_vEffectiveto, UTILS.CONVERT_TO_VARCHAR2(SYSDATE,200,p_style=>103) AS pos_3, 'SSISUSER'
   FROM O ,RBL_MISDB_PROD.AdvSecurityValueDetail O
          JOIN RBL_TEMPDB.TempAdvSecurityValueDetail T   ON O.SecurityEntityID = T.SecurityEntityID
          AND O.EffectiveToTimeKey = 49999
          AND T.EffectiveToTimeKey = 49999 
    WHERE ( NVL(o.ValuationSourceAlt_Key, 0) <> NVL(T.ValuationSourceAlt_Key, 0)
     OR NVL(o.ValuationDate, '1990-01-01') <> NVL(T.ValuationDate, '1990-01-01')
     OR NVL(o.CurrentValue, 0) <> NVL(T.CurrentValue, 0)
     OR NVL(o.ValuationExpiryDate, '1990-01-01') <> NVL(T.ValuationExpiryDate, '1990-01-01') )) src
   ON ( O.ROWID = src.row_id )
   WHEN MATCHED THEN UPDATE SET O.EffectiveToTimeKey = v_vEffectiveto,
                                O.DateModified = pos_3,
                                O.ModifiedBy = 'SSISUSER';
   ----------For Changes Records
   MERGE INTO A 
   USING (SELECT A.ROWID row_id, 'C'
   FROM A ,RBL_TEMPDB.TempAdvSecurityValueDetail A
          JOIN RBL_MISDB_PROD.AdvSecurityValueDetail B   ON A.SecurityEntityID = B.SecurityEntityID 
    WHERE B.EffectiveToTimeKey = v_vEffectiveto) src
   ON ( A.ROWID = src.row_id )
   WHEN MATCHED THEN UPDATE SET A.IsChanged
                                ----Select * 
                                 = 'C';
   ---------------------------------------------------------------------------------------------------------------
   -------Expire the records
   MERGE INTO AA 
   USING (SELECT AA.ROWID row_id, v_vEffectiveto, UTILS.CONVERT_TO_VARCHAR2(SYSDATE,200,p_style=>103) AS pos_3, 'SSISUSER'
   FROM AA ,RBL_MISDB_PROD.AdvSecurityValueDetail AA
          JOIN RBL_MISDB_PROD.AdvSecurityDetail CC   ON AA.SecurityEntityID = CC.SecurityEntityID
          AND AA.EffectiveFromTimeKey = CC.EffectiveFromTimeKey
          JOIN RBL_TEMPDB.TempAdvAcBasicDetail BB   ON CC.AccountEntityId = BB.ACCOUNTENTITYID 
    WHERE AA.EffectiveToTimeKey = 49999
     AND BB.SourceAlt_Key = 4
     AND NOT EXISTS ( SELECT 1 
                      FROM RBL_TEMPDB.TempAdvSecurityValueDetail BB
                       WHERE  AA.SecurityEntityID = BB.SecurityEntityID
                                AND BB.EffectiveToTimeKey = 49999 )) src
   ON ( AA.ROWID = src.row_id )
   WHEN MATCHED THEN UPDATE SET EffectiveToTimeKey = v_vEffectiveto,
                                DateModified = pos_3,
                                ModifiedBy = 'SSISUSER';
   INSERT INTO RBL_MISDB_PROD.AdvSecurityValueDetail
     ( ENTITYKEY, SecurityEntityID, ValuationSourceAlt_Key, ValuationDate, CurrentValue, ValuationExpiryDate, AuthorisationStatus, EffectiveFromTimeKey, EffectiveToTimeKey, CreatedBy, DateCreated, ModifiedBy, DateModified, ApprovedBy, DateApproved, D2Ktimestamp, CurrentValueSource, CollateralValueatthetimeoflastreviewinRs, CollateralID, ExpiryBusinessRule, PeriodinMonth )
     ( SELECT ENTITYKEY ,
              SecurityEntityID ,
              ValuationSourceAlt_Key ,
              ValuationDate ,
              CurrentValue ,
              ValuationExpiryDate ,
              AuthorisationStatus ,
              EffectiveFromTimeKey ,
              EffectiveToTimeKey ,
              CreatedBy ,
              DateCreated ,
              ModifiedBy ,
              DateModified ,
              ApprovedBy ,
              DateApproved ,
              D2Ktimestamp ,
              NULL ,
              NULL ,
              NULL ,
              NULL ,
              NULL 
       FROM RBL_TEMPDB.TempAdvSecurityValueDetail T
        WHERE  NVL(T.IsChanged, 'U') IN ( 'N','C' )
      );

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "MAIN_PRO";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "MAIN_PRO";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "RBL_STGDB";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "RBL_STGDB";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "RBL_TEMPDB";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."ADVSECURITYVALUEDETAIL_MAIN_29032022" TO "ADF_CDR_RBL_STGDB";
