--------------------------------------------------------
--  DDL for Procedure CONTSINCEDT_04122023
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" 
AS
   v_Timekey NUMBER(10,0);

BEGIN

   SELECT Timekey 

     INTO v_Timekey
     FROM RBL_MISDB.AUTOMATE_ADVANCES 
    WHERE  EXT_FLG = 'Y';
   UPDATE PRO_RBL_MISDB_PROD.ContExcsSinceDtAccountCal_RBL
      SET EffectiveToTimeKey = v_Timekey - 1
    WHERE  EffectiveFromTimeKey < v_Timekey
     AND EffectiveToTimeKey = 49999;
   DELETE PRO_RBL_MISDB_PROD.ContExcsSinceDtAccountCal_RBL

    WHERE  EffectiveFromTimeKey = v_Timekey;
   INSERT INTO PRO_RBL_MISDB_PROD.ContExcsSinceDtAccountCal_RBL
     ( CustomerAcID, AccountEntityId, SanctionAmt, SanctionDt, Balance, DrawingPower, ContExcsSinceDt, EffectiveFromTimeKey, EffectiveToTimeKey )
     ( SELECT A.CustomerAcID ,
              A.AccountEntityId ,
              currentLimit SanctionAmt  ,
              CurrentLimitDt SanctionDt  ,
              c.Balance ,
              DrawingPower ,
              ContExcsSinceDt ,
              v_Timekey ,
              49999 
       FROM RBL_TEMPDB.TempAdvAcBasicDetail A
              JOIN RBL_TEMPDB.TempAdvFacCCDetail B   ON A.AccountEntityId = B.AccountEntityId
              JOIN RBL_TEMPDB.TempAdVAcBalanceDetail C   ON C.AccountEntityId = A.AccountEntityId
              JOIN RBL_TEMPDB.TempAdVAcBalanceDetail D   ON D.AccountEntityId = A.AccountEntityId
              JOIN RBL_TEMPDB.TempAdvAcFinancialDetail E   ON E.AccountEntityId = A.AccountEntityId
        WHERE  ContExcsSinceDt IS NOT NULL );
   UPDATE PRO_RBL_MISDB_PROD.ContExcsSinceDtDebitAccountCal
      SET EffectiveToTimeKey = v_Timekey - 1
    WHERE  EffectiveFromTimeKey < v_Timekey
     AND EffectiveToTimeKey = 49999;
   DELETE PRO_RBL_MISDB_PROD.ContExcsSinceDtDebitAccountCal

    WHERE  EffectiveFromTimeKey = v_Timekey;
   -----
   INSERT INTO PRO_RBL_MISDB_PROD.ContExcsSinceDtDebitAccountCal
     ( CustomerAcID, AccountEntityId, SanctionAmt, SanctionDt, Balance, DrawingPower, ContExcsSinceDebitDt, EffectiveFromTimeKey, EffectiveToTimeKey )
     ( SELECT A.CustomerAcID ,
              A.AccountEntityId ,
              A.currentLimit SanctionAmt  ,
              CurrentLimitDt SanctionDt  ,
              c.Balance ,
              E.DrawingPower ,
              DebitSinceDate ,
              v_Timekey ,
              49999 
       FROM RBL_TEMPDB.TempAdvAcBasicDetail A
              JOIN RBL_TEMPDB.TempAdvFacCCDetail B   ON A.AccountEntityId = B.AccountEntityId
              JOIN RBL_TEMPDB.TempAdVAcBalanceDetail C   ON C.AccountEntityId = A.AccountEntityId
              JOIN RBL_TEMPDB.TempAdvAcFinancialDetail E   ON E.AccountEntityId = A.AccountEntityId
              JOIN RBL_STGDB.ACCOUNT_ALL_SOURCE_SYSTEM AA   ON AA.CustomerAcID = A.CustomerACID
        WHERE  AA.DebitSinceDate IS NOT NULL );

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "MAIN_PRO";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "MAIN_PRO";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "RBL_STGDB";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "RBL_STGDB";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "RBL_TEMPDB";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."CONTSINCEDT_04122023" TO "ADF_CDR_RBL_STGDB";
