--------------------------------------------------------
--  DDL for Procedure DERVCANCEL_SOURCESYSTEM_MAIN_09062021
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" 
AS
   -- SET NOCOUNT ON added to prevent extra result sets from
   -- interfering with SELECT statements.
   v_VEFFECTIVETO NUMBER(10,0);
-- Add the parameters for the stored procedure here

BEGIN

   SELECT TIMEKEY - 1 

     INTO v_VEFFECTIVETO
     FROM RBL_MISDB.AUTOMATE_ADVANCES 
    WHERE  EXT_FLG = 'Y';
   ----------For New Records
   MERGE INTO A 
   USING (SELECT A.ROWID row_id, 'N'
   FROM A ,RBL_TEMPDB.TEMPDERVCANCEL_SOURCESYSTEM A 
    WHERE NOT EXISTS ( SELECT 1 
                       FROM CurDat_RBL_MISDB_PROD.DerivativeDetail B
                        WHERE  B.EffectiveToTimeKey = 49999
                                 AND A.DerivativeRefNo = B.DerivativeRefNo )) src
   ON ( A.ROWID = src.row_id )
   WHEN MATCHED THEN UPDATE SET A.IsChanged
                                ----Select * 
                                 = 'N';-- And A.SourceAlt_Key=B.SourceAlt_Key)
   MERGE INTO O 
   USING (SELECT O.ROWID row_id, v_vEffectiveto, UTILS.CONVERT_TO_VARCHAR2(SYSDATE,200,p_style=>103) AS pos_3, 'SSISUSER'
   FROM O ,CurDat_RBL_MISDB_PROD.DerivativeDetail O
          JOIN RBL_TEMPDB.TEMPDERVCANCEL_SOURCESYSTEM T   ON O.DerivativeRefNo = T.DerivativeRefNo
          AND O.EffectiveToTimeKey = 49999
          AND T.EffectiveToTimeKey = 49999 
    WHERE ( NVL(O.CustomerACID, 0) <> NVL(T.AcID, 0)
     OR NVL(O.CustomerID, 0) <> NVL(T.CustID, 0)
     OR NVL(O.CustomerName, 0) <> NVL(T.CustomerName, 0)
     OR NVL(O.DerivativeRefNo, 0) <> NVL(T.DerivativeRefNo, 0)
     OR NVL(O.Duedate, '1990-01-01') <> NVL(T.Duedate, '1990-01-01')
     OR NVL(O.DueAmt, 0) <> NVL(T.DueAmt, 0)
     OR NVL(O.OsAmt, 0) <> NVL(T.Os_Amt, 0)
     OR NVL(O.POS, 0) <> NVL(T.POS, 0) )) src
   ON ( O.ROWID = src.row_id )
   WHEN MATCHED THEN UPDATE SET O.EffectiveToTimeKey = v_vEffectiveto,
                                O.DateModified = pos_3,
                                O.ModifiedBy = 'SSISUSER';
   ----------For Changes Records
   MERGE INTO A 
   USING (SELECT A.ROWID row_id, 'C'
   FROM A ,RBL_TEMPDB.TEMPDERVCANCEL_SOURCESYSTEM A
          JOIN CurDat_RBL_MISDB_PROD.DerivativeDetail B   ON A.DerivativeRefNo = B.DerivativeRefNo 
    WHERE B.EffectiveToTimeKey = v_vEffectiveto) src
   ON ( A.ROWID = src.row_id )
   WHEN MATCHED THEN UPDATE SET A.IsChanged
                                ----Select * 
                                 = 'C';
   ---------------------------------------------------------------------------------------------------------------
   -------Expire the records
   MERGE INTO AA 
   USING (SELECT AA.ROWID row_id, v_vEffectiveto, UTILS.CONVERT_TO_VARCHAR2(SYSDATE,200,p_style=>103) AS pos_3, 'SSISUSER'
   FROM AA ,CurDat_RBL_MISDB_PROD.DerivativeDetail AA 
    WHERE AA.EffectiveToTimeKey = 49999
     AND NOT EXISTS ( SELECT 1 
                      FROM RBL_TEMPDB.TEMPDERVCANCEL_SOURCESYSTEM BB
                       WHERE  AA.DerivativeRefNo = BB.DerivativeRefNo
                                AND BB.EffectiveToTimeKey = 49999 )) src
   ON ( AA.ROWID = src.row_id )
   WHEN MATCHED THEN UPDATE SET EffectiveToTimeKey = v_vEffectiveto,
                                DateModified = pos_3,
                                ModifiedBy = 'SSISUSER';
   INSERT INTO CurDat_RBL_MISDB_PROD.DerivativeDetail
     ( DateofData, SourceSystem, BranchCode, UCIC_ID, CustomerID, CustomerName, CustomerACID, DerivativeRefNo, Duedate, DueAmt, OsAmt, POS, AuthorisationStatus, EffectiveFromTimeKey, EffectiveToTimeKey, CreatedBy, DateCreated, ModifiedBy, DateModified, ApprovedBy, DateApproved, DerivativeEntityID )
     ( SELECT DateofData ,
              SourceSystem ,
              BranchCode ,
              UCIC_ID ,
              CustID ,
              CustomerName ,
              AcID ,
              DerivativeRefNo ,
              Duedate ,
              DueAmt ,
              Os_Amt ,
              POS ,
              AuthorisationStatus ,
              EffectiveFromTimeKey ,
              EffectiveToTimeKey ,
              CreatedBy ,
              DateCreated ,
              ModifiedBy ,
              DateModified ,
              ApprovedBy ,
              DateApproved ,
              DerivativeEntityID 
       FROM RBL_TEMPDB.TEMPDERVCANCEL_SOURCESYSTEM T
        WHERE  NVL(T.IsChanged, 'U') IN ( 'N','C' )
      );

EXCEPTION WHEN OTHERS THEN utils.handleerror(SQLCODE,SQLERRM);
END;

/

  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "PREMOC_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "QPI_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "ALERT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "DWH_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "MAIN_PRO";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "CURDAT_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "BS_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "ACL_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "ROLE_LOCAL_RBL_MISDB_PROD_ORACLE";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "PREMOC_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "QPI_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "ALERT_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "DWH_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "MAIN_PRO";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "D2KMNTR_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "CURDAT_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "BS_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "ACL_RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "RBL_MISDB_PROD";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "DATAUPLOAD_RBL_MISDB_PROD";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "ROLE_ALL_DB";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "CC_CDR_RBL_STGDB";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "RBL_BI_RBL_STGDB";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "BSG_READ_RBL_STGDB";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "STD_FIN_RBL_STGDB";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "RBL_STGDB";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "RBL_TEMPDB";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "STG_FIN_RBL_STGDB";
  GRANT EXECUTE ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "ADF_CDR_RBL_STGDB";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "ROLE_ALL_DB";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "CC_CDR_RBL_STGDB";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "RBL_BI_RBL_STGDB";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "BSG_READ_RBL_STGDB";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "STD_FIN_RBL_STGDB";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "RBL_STGDB";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "ETL_TEMP_RBL_TEMPDB";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "RBL_TEMPDB";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "STG_FIN_RBL_STGDB";
  GRANT DEBUG ON "ETL_MAIN_RBL_MISDB_PROD"."DERVCANCEL_SOURCESYSTEM_MAIN_09062021" TO "ADF_CDR_RBL_STGDB";
