--------------------------------------------------------
--  File created - Wednesday-March-19-2025   
--------------------------------------------------------
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_ALERT_SCRIPTS\GTT_BRANCH.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_ALERT_SCRIPTS\GTT_DIMREGION.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_ALERT_SCRIPTS\TT_CODE.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_ALERT_SCRIPTS\TT_DIMTHRESHOLDMASTER_2.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_ALERT_SCRIPTS\TT_DIMTHRESHOLDMASTER_3.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_ALERT_SCRIPTS\GTT_BRANCH_DATA_TABLE.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_ALERT_SCRIPTS\GTT_DIMREGION_DATA_TABLE.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_ALERT_SCRIPTS\TT_CODE_DATA_TABLE.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_ALERT_SCRIPTS\TT_DIMTHRESHOLDMASTER_2_DATA_TABLE.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_ALERT_SCRIPTS\TT_DIMTHRESHOLDMASTER_3_DATA_TABLE.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_ALERT_SCRIPTS\DIMTHRESHOLDMASTER_LOCATION_LOCATIONCOCDE.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_ALERT_SCRIPTS\TRESHOLDQUICKSERACHSELECT.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_ALERT_SCRIPTS\TRESHOLDSELECT.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_ALERT_SCRIPTS\TRESHOLDSELECT_DATA.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_ALERT_SCRIPTS\TRESHOLD_META.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_ALERT_SCRIPTS\TRESHOLD_SHOW_SELECT.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_ALERT_SCRIPTS\UTILS.sql
@C:\Users\Zulqarnain.Shaikh\PROJECTS\ORCALE SCRIPTS\ALL_ALERT_SCRIPTS\GTT_DIMREGION_CONSTRAINT.sql
