--------------------------------------------------------
--  DDL for Table TT_DIMTHRESHOLDMASTER_2
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "ALERT_RBL_MISDB_PROD"."TT_DIMTHRESHOLDMASTER_2" 
   (	"THRESHOLD_SETID" NUMBER(10,0), 
	"LOCATION" VARCHAR2(10 BYTE), 
	"LOCATIONCODE" VARCHAR2(10 BYTE), 
	"MASTERNAMEALT_KEY" NUMBER(10,0), 
	"MASTERALT_KEY" NUMBER(10,0), 
	"EFFECTIVEDT" VARCHAR2(10 BYTE), 
	"INCREASETHRESHOLD" NUMBER(18,2), 
	"DECREASETHRESHOLD" NUMBER(18,2), 
	"AUTHORISATIONSTATUS" VARCHAR2(2 BYTE), 
	"CRMODAPBY" VARCHAR2(20 BYTE), 
	"D2KTIMESTAMP" NUMBER(10,0), 
	"CHANGEFIELDS" VARCHAR2(20 BYTE), 
	"ISMAINTABLE" CHAR(1 BYTE)
   ) ON COMMIT DELETE ROWS ;
